### ISSUE TITLE
grunt start can't launch app

### ISSUE THREAD

**Issue by arshavindn** [popcorntime/popcorntime#10]
```
Running "start" task

Running "exec:linux64" (exec) task
>> Exited with code: 127.
>> /bin/sh: 1: build/Popcorn-Time/linux64/Popcorn-Time: not found
Warning: Task "exec:linux64" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by team-pct** [comment]
Check your folder for cache .
if not you can start it manually by executing ./cache/0.12.2/nw
If you have no cache , please rebuild using gulp build

**Comment by micopiira** [comment]
@team-pct Mind explaining why are you using 2 build tools (gulp and grunt)?

Shouldn't you just move all the tasks to either one?

**AND** if you run `gulp run` it will automatically download nwjs to the cache folder, i see no point using `grunt start`

**Comment by team-pct** [comment]
We are migrating from Grunt to GULP , if you can help , Please do

**Comment by micopiira** [comment]
@team-pct Sure I can help. I wrote that gulpfile you are using at the moment. (atleast most of it).
