### ISSUE TITLE
Duplicate icon on systray

### ISSUE THREAD

**Issue by vageliskatsiotis** [popcorntime/popcorntime#1000]
#### Operating System Version:
Antergos x86_64 Linux 4.19.34-1-lts

#### Popcorn Time Version:
popcorntime 0.3.10-15

#### Download date:
2019-04-08

#### Expected Behaviour
Single icon in systray gnome panel

#### Actual Behaviour
With each minimize a new icon is created

#### Steps to reproduce the behaviour
Just minimize to tray, restore and minimize again

Maybe something to do with latest gnome-shell update? There were some issues all around cause of this.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
