### ISSUE TITLE
Cant Use 1080p

### ISSUE THREAD

**Issue by 16lionheart16** [popcorntime/popcorntime#1003]
Operating System Version:
Windows 10

Popcorn Time Version:
3.1

Download date:
22/4/19

#### Expected Behaviour
allow me to watch tv shows at 1080p

#### Actual Behaviour
won't let me select 1080p

#### Steps to reproduce the behaviour 
It is always not letting me select 1080p
![Capture1080](https://user-images.githubusercontent.com/50107758/56898354-be298780-6a88-11e9-82f0-9781374b470b.PNG)

**Comment by rafaell-lycan** [comment]
Hi @16lionheart16, this will happen if the resource cannot find any download of type 1080p.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
