### ISSUE TITLE
App only on foreground. Only way to minimize is by clicking on minimize button

### ISSUE THREAD

**Issue by lfsando** [popcorntime/popcorntime#1005]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
Long time ago

#### Expected Behaviour
 Minimize when clicking outside of the windows. When opening other files it should open on top instead being hidden by popcorn time
...

#### Actual Behaviour
It suddenly started a few weeks ago.  The windows always stay on foreground. If I open file explorer for example, it will be open on the background. Sometimes the only way to access anything when a movie is loaded is to close it and minimize the windows manually.

#### Steps to reproduce the behaviour
Just open Popcorn Time

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
