### ISSUE TITLE
Some files have audio and no video, and some files have video no audio

### ISSUE THREAD

**Issue by kronikpillow** [popcorntime/popcorntime#1007]
Operating System Version:
ArcoLinuxB-i3 v19.06.1

Popcorn Time Version:
git clone version

Download date:
15.05.2019

#### Expected Behaviour
Play video and audio
...

#### Actual Behaviour
Some files don't play audio, some files don't play video
...

#### Steps to reproduce the behaviour

1. Go To Series / The Flash / Season 5 / Episode 21 (has video, no audio)
2. Go To Series / The Flash / Season 5 / Episode 22 (has audio, no video)

installed using git clone method
&
yarn config set yarn-offline-mirror ./node_modules/
yarn install --ignore-engines
yarn build
yarn gulp run

**Comment by Persei08** [comment]
have you tried to play the video in vlc or mpv?

**Comment by kronikpillow** [comment]
Yes I have and both VLC and MPV playback them perfectly fine, but that's not the point is it? MPV and VLC have their own Codecs, and this seems to be a Butter issue, I do not have my language subtitles offered when i run it with VLC and MPV

**Comment by carolaquintanilha** [comment]
i'm with the same issue. I was trying to watch GLEE, but there's only audio, no video, and it seems like all of the episodes are the same. When I try to open in mpv, it opens, perfectly, but there's no subtitles of my language :(

**Comment by kronikpillow** [comment]
this issue doesn't exist on the version that can be found on the popcorntime website, only on the build that is on the git version, shame that there is no feedback from the developers, this issue has been open for months

**Comment by Persei08** [comment]
The latest dev builds (or latest commits of development branch) actually support less codecs than the 0.3.10.

This is because it's really painfull to build the custom nwjs (and custom ffmpeg) with all the previously supported codecs. So it was switched to use nwjs+[nwjs-ffmpeg-prebuilt](https://github.com/iteufel/nwjs-ffmpeg-prebuilt) (which provide only the few more common codecs than nwjs itself) until something better is found.

**Comment by kiriles90** [comment]
@Persei08 close this please
