### ISSUE TITLE
Popcorn Time doesn't load

### ISSUE THREAD

**Issue by MauroSerrano-dev** [popcorntime/popcorntime#1009]
Operating System Version:
Windows 10 Home Single Language

Popcorn Time Version:
0.3.10

Download date:
may 18th, 2019

#### Expected Behaviour
Since I had this app in my other laptop, I downloaded it expecting it work correctly and I would get to watch movies, tv shows etc via torrent just like I did on my last laptop.
...

#### Actual Behaviour
The app keeps loading and loading but the movies never show up on the screen, and it's been like ths for quite sometime, so I tried uninstalling it and downloading it again but it still doesn't work.
...

#### Steps to reproduce the behaviour

1. click on the icon to open the app
2. there you go, it'll be loading forever and ever and that's my issue.

**Comment by lyam20** [comment]
Same problem

**Comment by Persei08** [comment]
What do you mean exactly? Does it show a blue spinning circle (loader). ?

**Comment by carolinemo** [comment]
i do have the same problem

**Comment by carolinemo** [comment]
how to fix it ???

**Comment by Persei08** [comment]
@carolinemo go to popcorntime.app and install the new v4.4. It use the new api domain

For other people, I close this issue since its old, and no additional infos were provided. My guess is it happened because api domain was blocked by ISP, which can be bypassed by using unfiltered DNS or VPN.
