### ISSUE TITLE
Dead link to https://popcorntime.sh

### ISSUE THREAD

**Issue by fitzhavey** [popcorntime/popcorntime#1010]
The project description contains a link to https://popcorntime.sh. This link is not live. 

It is also present in the project readme. Having a link to an official source would be very useful. 

Thanks for the work on this great project!

**Comment by ozkanpakdil** [comment]
site maybe blocked at your country. its working in Poland.

**Comment by fitzhavey** [comment]
The link was dead when I opened this issue. It seems to be back up and running now so closing it 😄
