### ISSUE TITLE
kan geen films afspelen hoe kan dit 

### ISSUE THREAD

**Issue by eline2244** [popcorntime/popcorntime#1020]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by eline2244** [comment]
hallo ik kan geen films afspelen er staat dan geen doawnload starten alleen verbinden hoe kan dat ik zou graag weer films willen kijken op jullie site want dat vind ik net zo leuk alvast bedankt eline

**Comment by lg188** [comment]
Hallo Eline, ik denk dat je niet veel antwoord gaat krijgen met een Nederlandstalige en oningevulde bug-report.
In ieder geval, er is geen update meer gebeurt sinds 11de januari, dus ik denk dat er gewoon dingen niet up-to-date zijn.

**Comment by eline2244** [comment]
misschien ff updaten ???

**Comment by lg188** [comment]
ik kan proberen maar kan ook niks garanderen.

**Comment by eline2244** [comment]
of misschien zijn ze met de site bezig heb dit wel eerder gehad ik weet t ff niet
