### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by akollip1** [popcorntime/popcorntime#1026]
Operating System Version:
Fedora 28

Popcorn Time Version:
latest as of 11 July 2019

Download date:
11 July 2019

#### Expected Behaviour
complete installation upon execution of  "./make_popcorn.sh" in terminal
...

#### Actual Behaviour
Returns with "permission denied" in terminal
...

#### Steps to reproduce the behaviour

1. open terminal
2. log in as root
3. enter directory where "make_popcorn.sh" is located and attempt to execute the make file

**Comment by akollip1** [comment]
I'm still getting the same issue.

`akollipara@localhost popcorn-desktop-c7799212b5a4779a7b34ad2d9a28632e50e3ae55]$ ./make_popcorn.sh
bash: ./make_popcorn.sh: Permission denied`

I also tried as root

`[root@localhost popcorn-desktop-c7799212b5a4779a7b34ad2d9a28632e50e3ae55]# ./make_popcorn.sh
-bash: ./make_popcorn.sh: Permission denied
`

**Comment by akollip1** [comment]
I made a little progress. So I didn't allow for `make_popcorn.sh` to be run as an executable, so I checked the box in the properties. I'm missing a `gulp-load-plugins module`.

`[akollipara@localhost popcorn-desktop-c7799212b5a4779a7b34ad2d9a28632e50e3ae55]$ ./make_popcorn.sh
Cloning Popcorn Time
Where do you wish to clone Popcorn Time to? [popcorn] 
Cloning into 'popcorn'...
remote: Enumerating objects: 41833, done.
remote: Total 41833 (delta 0), reused 0 (delta 0), pack-reused 41833
Receiving objects: 100% (41833/41833), 32.01 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (28142/28142), done.
Cloned Popcorn Time successfully
Switched to /home/akollipara/Downloads/popcorn-desktop-c7799212b5a4779a7b34ad2d9a28632e50e3ae55/popcorn
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-load-plugins'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/akollipara/Downloads/popcorn-desktop-c7799212b5a4779a7b34ad2d9a28632e50e3ae55/popcorn/gulpfile.js:16:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Popcorn Time encountered an error and couldn't be built
`

I'm also noticing there are several modules, like `run-sequence`, `del`, or `gulp-download2` that can't be found. I'll install them with npm and see where I end up.

**Comment by ozkanpakdil** [comment]
did you try with https://raw.githubusercontent.com/ozkanpakdil/popcorn-desktop/patch-2/make_popcorn.sh ?

actually popcorn has been using yarn for a long time now. if you check the read me. here are the commands to build locally
yarn config set yarn-offline-mirror ./node_modules/
yarn install --ignore-engines
yarn build
yarn gulp run
