### ISSUE TITLE
The Walking Dead - 9 Season

### ISSUE THREAD

**Issue by augustopagot** [popcorntime/popcorntime#1029]
Operating System Version:Windows 10

Popcorn Time Version:

Download date:
13 July - 2019

#### Expected Behaviour
Very Good
...

#### Actual Behaviour
Good
...

#### Steps to reproduce the behaviour

The Walking Dead 9 Season the episodes 3, 4, 5, 6 and 7 don't show the image, only the sound and the subtitles. Image All Black!

**Comment by Persei08** [comment]
I guess it's because the video codec isn't supported by the bundled player. As a workaround you can use VLC
