### ISSUE TITLE
Sometimes it doesn´t open

### ISSUE THREAD

**Issue by Melokap** [popcorntime/popcorntime#1032]
Sometimes I click the icon and it doesn´t open. I try reinstall and doesn´t work.
Operating System Version:

windows 8.1
Popcorn Time Version:

0.3.10
Download date:

today
#### Expected Behaviour

...
open
#### Actual Behaviour

...
don´t open
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
can't reproduce

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
