### ISSUE TITLE
blank black page and configs don't save!

### ISSUE THREAD

**Issue by rawkon** [popcorntime/popcorntime#1033]
Operating System Version:
win10

Popcorn Time Version:
0.3.10 beta

Download date:
29.06.2019

#### Expected Behaviour
show me something.

#### Actual Behaviour
it doesn't show any content, only blank black page with menu at the header. also everytime i start it, prompt the agreement popup and resets it's configs and databases.
...

#### Steps to reproduce the behaviour
closing and opening by shortcut.

1. ...
2. ...
3. ...

--------

besides that:

IMDB ratings are wrong and not updated regularly. A movie on popcorntime shows 8.0 but it's actually 5.7 rating currently. 
Also, we need a better content shorting/ordering/filtering options...
Thanks for all your efforts!

**Comment by Persei08** [comment]
Can't reproduce.
also there are not "IMDB ratings" but trakt.tv ratings

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
