### ISSUE TITLE
How to improve PopcornTime bit torrent trackers

### ISSUE THREAD

**Issue by EmanuelFaria** [popcorntime/popcorntime#1034]
Operating System Version:
OS X 10.14.6

Popcorn Time Version:
6.12

FEATURE REQUEST:
Is there any way to permanently add new trackers to the app to make downloads faster and more reliable?

Perhaps an addition to the interface that allows users to copy and paste trackers from sites such as these? Or, create a way to automatically scrape from these sites every time popcorntime is open?

https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt
https://github.com/ngosang/trackerslist/blob/master/trackers_all.txt
https://torrents.io/tracker-list/

Thanks

**Comment by ozkanpakdil** [comment]
Hello

I tried that with https://github.com/ozkanpakdil/popcorn-desktop/blob/development/src/app/settings.js line 91 but in my experience it did not bring much. feel free to elaborate and test more :)

Thanks

**Comment by Persei08** [comment]
> Popcorn Time Version:
> 6.12

You're using a version from another clone/fork. Here the version number is 3.10 (or 0.3.10)

The version from here got this issue too, but some trackers from those lists were added in latest development versions

**Comment by EmanuelFaria** [comment]
Thanks for the tip, but I can’t find this file or even the Src folder. I’m using a Mac, are you?---- On Fri, 02 Aug 2019 02:06:26 -0400  notifications@github.com<notifications@github.com> wrote ----Hello 
I tried that with https://github.com/ozkanpakdil/popcorn-desktop/blob/development/src/app/settings.js line 91 but in my experience it did not bring much. feel free to elaborate and test more :) 
Thanks

**Comment by EmanuelFaria** [comment]
Whoops. Never mind. Found it. But my settings.json file only has one line that says“Editor.trimAutoEhitesoace”:trueCan I just paste your text in here to make it work?---- On Fri, 02 Aug 2019 02:06:26 -0400  notifications@github.com<notifications@github.com> wrote ----Hello 
I tried that with https://github.com/ozkanpakdil/popcorn-desktop/blob/development/src/app/settings.js line 91 but in my experience it did not bring much. feel free to elaborate and test more :) 
Thanks

**Comment by EmanuelFaria** [comment]
Oh thanks!

I’m not really versed in gitbub. Can you point me to a link to download the latest fork, please?

Thanks!

Manny

On Aug 2, 2019, at 3:38 AM, Persei08 <notifications@github.com> wrote:

Popcorn Time Version:
6.12

You're using a version from another clone/fork. Here the version number is 3.10 (or 0.3.10)

The version from here got this issue too, but some trackers from those lists were added in latest development versions

**Comment by Persei08** [comment]
You should probably try [dev build 362](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/362/) (or 361) . But actually the CI platform (Jenkins) have an issue which make the downloads fails after few seconds, so you should use a download manager (with auto resume feature) or aria2. There are more explanations in #963

**Comment by EmanuelFaria** [comment]
Thank you for your response! I’ll check it out.Can you explain this to me please? “you should a download manager (with auto resume feature) or aria2”... if that also in the link you posted, never mind.Thanks again!---- On Sun, 04 Aug 2019 14:42:04 -0400  notifications@github.com<notifications@github.com> wrote ----You should probably try dev build 362 (or 361) . But actually the CI platform have a settings which make the downloads fails after few seconds, so you should a download manager (with auto resume feature) or aria2. There are more explanations in #963
