### ISSUE TITLE
Subtitles matching the torrent

### ISSUE THREAD

**Issue by hugojcqs** [popcorntime/popcorntime#1035]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

#### Expected Behaviour
Sync the subtitles with the video.

#### Actual Behaviour
Doesn't sync, need to be synced manually.

### Hash and subtitles syncing
I was wondering if the downloaded files were downloaded based on the hash of the downloaded file (just like VLC). Because most of the time I can't get proper subtitles 😢 
Is there a way to get the hash of the movie i'm watching so that i can download my own subtitles ? 👍

**Comment by Persei08** [comment]
On 3.10 beta, there is an algorithm calculating a score based on matching criterias (filename, episode number , tag, etc..) (maybe hash too)

But in last development versions, PT return multiple subtitles per language

**Comment by hugojcqs** [comment]
Too bad ... But i don't think hash is used at this point, hash doesn't lie. When you have the hash of a file, you don't need the title, episode number, etc.

**Comment by Persei08** [comment]
I don't remember exactly if the hash is used or not. 
But let's assume you have the hash but no subtitiles are found for this exact hash. Then you will use other criterias to find subtitles for other releases of the same movie... and it partially explain why some subtitles aren't perfectly synced

**Comment by kiriles90** [comment]
@Persei08 close please
