### ISSUE TITLE
Seeding. Unwatchable.

### ISSUE THREAD

**Issue by jo-neves** [popcorntime/popcorntime#1036]
Operating System Version:
Windows 10

Popcorn Time Version:
Lastest

#### Expected Behaviour
Watch a movie till' the end without pauses.

#### Actual Behaviour
Popcorn Time is becoming unwatchable. The are almost no seeds and the download is always hanging while watching.

#### Steps to reproduce the behaviour
Just use it...

**Comment by hugojcqs** [comment]
I don't think popcorn time have something to do with the seeds...

**Comment by jo-neves** [comment]
popcorn time does not seed. therefore yes, it has, its ruins the network.

**Comment by Persei08** [comment]
@joao-neves95 [popcorntime can seed](http://i.imgur.com/5QmH3RI.png). It isn't as effective as some other torrent clients, and a "keep seeding" feature will certainly be welcome. But there are also lot of other things which can explain a low download speed.

**Comment by jo-neves** [comment]
Solved on the last update.
