### ISSUE TITLE
VLC player not working

### ISSUE THREAD

**Issue by ironstamp** [popcorntime/popcorntime#1037]
Operating System Version:
OS X 10.14

Popcorn Time Version:
0.3.10

Download date:
July 2019

#### Expected Behaviour
Allow playback in VLC

#### Actual Behaviour
Playback starts and stops soon after. Media loads and begins to play but then stops shortly after (frame freezes). It's not consistent where. Will not progress any further, even after waiting some time. Works fine in Butter player, so doesn't seem to be a torrent health issue. Happens on ALL devices (MacBook Pro, Mac Mini, iMac).

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
