### ISSUE TITLE
/Popcorn-Time-0.3.10-Linux-64/Popcorn-Time[5418]: ../../third_party/node/src/node_crypto_bio.h:83:static node::NodeBIO *node::NodeBIO::FromBIO(BIO *): Assertion `(bio->ptr) != (nullptr)' failed. Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by SAUCYSOUP76** [popcorntime/popcorntime#1039]
Operating System Version:

Linux Fedora 30
Popcorn Time Version:

Latest
Download date:

2019-08-15 17:00
#### Expected Behaviour

...
Launch
#### Actual Behaviour

...
Crash and terminal output: /Popcorn-Time-0.3.10-Linux-64/Popcorn-Time[5418]: ../../third_party/node/src/node_crypto_bio.h:83:static node::NodeBIO *node::NodeBIO::FromBIO(BIO *): Assertion `(bio->ptr) != (nullptr)' failed.
Illegal instruction (core dumped)
#### Steps to reproduce the behaviour

1. ... Launch the App from the terminal
2. ...
3. ...

**Comment by superorc** [comment]
Same issue on fedora 30

```
$ ./Popcorn-Time 
[13935:13935:0912/061909:ERROR:sandbox_linux.cc(345)] InitializeSandbox() called with multiple threads in process gpu-process. 
---popcorn/Popcorn-Time[13938]: ../../third_party/node/src/node_crypto_bio.h:83:static node::NodeBIO *node::NodeBIO::FromBIO(BIO *): Assertion (bio->ptr) != (nullptr)' failed.
Illegal instruction (core dumped)

$ node -v
v10.16.3
```

Is related to chrome sandbox setup?
