### ISSUE TITLE
I can't watch my series because of the format or something

### ISSUE THREAD

**Issue by Sara0605** [popcorntime/popcorntime#1042]
When I try to watch my series I can only watch the first episode and then when I try the next one there is a message that says "the video could not be loaded, either because the server or network failed or because the format is not supported"
I don´t get why this is happening. I can watch other series that I don´t watch regularly, (that is when I´m testing why it doesn´t works). 
I need help!

<img width="816" alt="Captura de pantalla 2019-08-28 a la(s) 22 31 24" src="https://user-images.githubusercontent.com/54658255/63913757-eacdbb80-c9f6-11e9-9bab-84c2d4b5f975.png">

**Comment by tingspain** [comment]
Any update on this issue?
