### ISSUE TITLE
Problem with Codecs (Latin America) impossible to view!

### ISSUE THREAD

**Issue by SliderKP** [popcorntime/popcorntime#1044]
Operating System Version:

Windows 10 transmiting to a Samsung Smart TV

Popcorn Time Version:

Popcorn-Time 0.3.10
Download date:

a month ago
#### Expected Behaviour

...

#### Actual Behaviour

when I transmit to my Samsung Smart TV television, the codecs are missing to see words with "ACENTS" examples: à è ì ò ù
and subtitles appears with SIMBOLS and make impossible to understand the text ... probe with all available codecs and does not work in any way,

#### Steps to reproduce the behaviour

1. ... Pop Corn Time in PC transmit to Samsung TV a film and use subtitles in spanish.
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by SliderKP** [comment]
@kiriles90 
@Persei08 

This is not solved.

**Comment by dutchy1001** [comment]
@SliderKP 
What version are you using? (many updates have been made after version 0.3.10)
If not sure what version, open PCT info/about (the i ) tab and on the right bottom corner is a number between brackets (xxxxxxxx).
Does it happen when watching PCT on the PC? 
Are you using a dev build or the one from the main website?
Any info they can use to recreate the issue would be great.

**Comment by kiriles90** [comment]
@SliderKP this isnt an issue with Popcorn Time to begin with, you need to set the correct encoding on your TV.
