### ISSUE TITLE
Madam Secretary

### ISSUE THREAD

**Issue by aseabram** [popcorntime/popcorntime#1046]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...Try to see Madam Secretary
2. ...You wont be able to
3. ...Madam Secretary doesn't work.
If the movie or the series dont work, why they stay in the site????

**Comment by Persei08** [comment]
Because PT use YTS.lt and eztv.io APIs. Episodes are removed when there are removed from thoses apis
