### ISSUE TITLE
Stuck on "connecting"

### ISSUE THREAD

**Issue by nicolesiu** [popcorntime/popcorntime#1047]
Operating System Version:
OS 10.14.5

Popcorn Time Version:
Popcorn Time 3.10

Download date:
6th Sep 2019

#### Expected Behaviour
...

#### Actual Behaviour
I have used it for years in my old macbook without VPN and it worked well, but now after I downloaded it on my new one, for all movies, whenever I pressed "watch now", it's stuck on "connecting" and never started downloading.

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
