### ISSUE TITLE
Can't login to Trakt / OpenSubtitles / GitLab

### ISSUE THREAD

**Issue by samlemarnais** [popcorntime/popcorntime#1048]
Operating System Version:
Windows 10 (latest updates)

Popcorn Time Version:
0.3.10-0

Download date:
09/09/2019

#### Expected Behaviour
I should be able to sign in on my Trakt / OpenSubtitles / GitLab accounts via the application

#### Actual Behaviour
For Trakt: A popup ask me "Allow Butter to use your account?", I click "Yes", the popup closes, nothing changes, still "Connectez-vous à Trakt.tv......."
For OpenSubtitles, the spinner never ends spinning
For GitLab: the spinner never ends spinning

#### Steps to reproduce the behaviour
Simply enter your credentials via the PCT interface.

**Comment by Persei08** [comment]
Try dev builds, it's already fixed. 0.3.10 is old

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
