### ISSUE TITLE
Search box hides while typing

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1049]
Operating System Version:
Debian GNU/Linux 10 (amd64) +Gnome desktop

Popcorn Time Version:
Build #363 (Dec 30, 2018 3:53:15 PM)

Download date:
2019.09.11

#### Expected Behaviour
Click on search icon, type words I'm looking for, and complete to press ENTER.

#### Actual Behaviour
While I type, at 3rd or 4th letter textbox hides and I must click on len icon to continue tyiping.

#### Steps to reproduce the behaviour
1. Click on search (len) icon
2. Type letters

**Comment by narcisgarcia** [comment]
This problem doesn't occur with Popcorn-Time-0.3.10-Linux from home website.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
