### ISSUE TITLE
Feature request: Videos catalogs sources

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1050]
Operating System Version:
any

Popcorn Time Version:
Next version

#### Expected Behaviour
Option to customize catalog sources at settings tab.

#### Actual Behaviour
No control over titles selection on main page. What if I have my own film list to offer? What if I only want to get titles preselected with spanish soundtrack? Or only those pre-selected by my trusted website?

**Comment by Persei08** [comment]
This project is popcorntime.sh. Audio  soundtrack are always english, sources are YTS.lt and eztv.io, and I think the reason PT rely on them is because theirs magnets links are public (no authentication required) and you can easily find IMDB ids on their pages.... so you can easily request other apis and get the movie/episodes descriptions, etc...

If you start to allow users to add and share their torrents it will quickly becomes full of junks and fakes torrents... like it was for emule, edonkey, kazaa. Eventually you can add a reputation system which will allow user to leave comment and ratings on torrents. but it can always be abused too.

**Comment by narcisgarcia** [comment]
I'm not asking for people pushes their torrents to current catalog sources: I'm asking to sources (url's?) be configurable, and/or offer a list of well-known ones. Just as FOSS repositories do.

And... Is there some special reason to audio soundtracks be always english?

**Comment by Persei08** [comment]
Well, first the URLs have to be popcorm-api endpoints. I don't think there are a lot running and people who run popcorm-api can easily patch PT to use there own API and distribute it. Eventually it could be a good thing to have the option you ask but is there really some people you run popcorm-api with for example Spanish language... Eventually if there is a real need why not... But I have a doubt about it

**Comment by narcisgarcia** [comment]
I can confirm there is a real need for Spanish, as the world's second-most spoken native language, after Mandarin Chinese. Today has over 450 million native speakers in Spain and the Americas.

About URL, the first thing to do is to allow this customization and to have API/PT requirements published. Without this, project itself is not allowing others to develop or patch counterpart solutions.

**Comment by ivan1986** [comment]
Hi
i also write api server for russian trackers and want see this option

**Comment by ivan1986** [comment]
@narcisgarcia Can you give me links for some spanish trackers? I write parsers for it's and test multilang api.
Also i add in my api translations for titles, posters and owerview, but need update client - now it in process

**Comment by narcisgarcia** [comment]
Did you see my e-mail sent to you?

**Comment by ivan1986** [comment]
@narcisgarcia yes, thanks

**Comment by Persei08** [comment]
@narcisgarcia I wasn't saying there isn't need for Spanish (or other languages) dubbed movies, but I was saying there wasn't popcorn-api returning other languages dubbed movies.

Now, apparently I was wrong, there is a vietnamese api and @ivan1986 have a multilang one

**Comment by Persei08** [comment]
@narcisgarcia since dev build 410 , there is a field to add custom api sever in PT.

The only two i know are https://popcorn-api.io/ and https://popcorn-ru.tk/ , but things doesn't to work very well at the moment especially with popcorn-ru.tk.... any idea @ivan1986 maybe ?

**Comment by team-pct** [comment]
http://api-fetch.sh/

**Comment by ivan1986** [comment]
@Persei08 now main issue if my server is 600mb ram and 43% usage of mysql - it's google cloud free tier.
Any issues with api, or only slow working? I try to fix it's.

**Comment by Persei08** [comment]
I don't know, i just retried and now everything work as expected. Maybe i made a mistake. Sorry, my bad :|

**Comment by Persei08** [comment]
@narcisgarcia so, do you consider this solved ?

**Comment by narcisgarcia** [comment]
I've tested with PopcornTime / Butter v4.4.0 and I still see 4.4 version at popcorntime.app
I don't see any GUI setting to setup content sources at Configuration tab.

**Comment by kiriles90** [comment]
@narcisgarcia get the latest dev build from ci.popcorntime.app

**Comment by Persei08** [comment]
![pt_custom_server](https://user-images.githubusercontent.com/22459458/96717737-3b486b00-13a7-11eb-8c3a-897ae46e17a3.png)

'Custom api server' option in advanced settings (recent dev build)
you can try with https://popcorn-ru.tk/ (popcorn-api.io is down :/ )

**Comment by Persei08** [comment]
ok, I close because it's done. @narcisgarcia check latest dev builds and try with `https://popcorn-ru.tk/`
