### ISSUE TITLE
Feature request: Add 480p-576p resolution to be selected

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1051]
Operating System Version:
any

Popcorn Time Version:
Next versions

#### Expected Behaviour
More resolutions to select as preferred: PAL/NTSC, 720p, 1080p, 2160p, or as simple as type nearest to ideal.
+Show more resolutions available on video sheet.

#### Actual Behaviour
Only 720p and 1080p resolutions to select.
+Not everybody has necessary bandwidth to watch a so high definition video.

#### Steps to reproduce the behaviour
1. Open video sheet

**Comment by ivan1986** [comment]
fixed in client

**Comment by narcisgarcia** [comment]
Thanks.
Which version is available to download with this fix included?

**Comment by ivan1986** [comment]
last dev - in action - all after "Merge pull request #1150 from popcorn-time-ru/select-quality-dev2"
but api has not torrents with small resolutions now

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
