### ISSUE TITLE
Feature request: Go to Kodi/XBMC plugin

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1052]
Operating System Version:
(multiplatform)

Popcorn Time Version:
Future version

#### Expected Behaviour
Popcorn-Time be installable as a Kodi environment extension (ARM architecture too)
Kodi has already a mature GUI, and Popcorn-time only needs to use its API to provide catalogue and torrent streams.

#### Actual Behaviour
Popcorn-time is only a standalone application, and project needs to work on everything (OS environment, GUI, usability, etc.).

**Comment by Persei08** [comment]
There is already an unofficial kodi plugin: https://github.com/markop159/KODI-Popcorn-Time

**Comment by kiriles90** [comment]
@Persei08 maybe close this since its not an actual issue with the desktop app (nor I think its something thats happening tbh)
