### ISSUE TITLE
I still can't play movies eaaeen to connect further, in the case of anything custom made trailers to do it

### ISSUE THREAD

**Issue by eline2244** [popcorntime/popcorntime#1053]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Please stop spamming and go to reddit for help: https://www.reddit.com/r/PopCornTime/
