### ISSUE TITLE
Search for tv shows doesn't return results

### ISSUE THREAD

**Issue by benjaminholhjem** [popcorntime/popcorntime#1054]
Operating System Version:
Windows 10 build 1809

Popcorn Time Version:
0.3.10

Download date:
18.09.2019

#### Expected Behaviour
Search results showing up when searching for tv shows

#### Actual Behaviour
Shows error: "The remote shows API failed to respond, please check http://status.popcorntime.sh and try again later"

Most shows becomes searchable after they're added to my favorites, but not all.

#### Steps to reproduce the behaviour

1. Search for a show currently not in your favorites
2. Find the show by scrolling through the series tab, and add to favorites
3. Search again to see if it shows up

**Comment by Persei08** [comment]
PT Api is down, actually it use cached results from cloudflare cache, so some search works, some other don't.

**Comment by benjaminholhjem** [comment]
Then it makes sense. Any estimate on when the API will be available again?
And why doesn't the status page indicate this issue?

**Comment by Persei08** [comment]
oops, I forgot to reply.

No, no idea at all.
For the status page I guess it check if the API server is offline. But the API server is still online the issue is just it return 503 errors

**Comment by christian130** [comment]
why dont we start a completely new development using Java for android? and
Java in General... or using NW i dont know the desktop version is not
working properly...

**Comment by christian130** [comment]
in my defense, the place where i live not even the NX (and you know what IT
is...) does not exist, i mean i cannot access... i think it's applying in
different places and not mine at all... also a 144 and 240p would be good
since WE the poor country cannot have the right to access to 10Mbps and so
on

**Comment by kiriles90** [comment]
@Persei08 not an actual issue? close please
