### ISSUE TITLE
Popcorn-api is down: err 503

### ISSUE THREAD

**Issue by Persei08** [popcorntime/popcorntime#1055]
**Operating System Version**:
OS X, Windows, Linux

**Popcorn Time Version**:
0.3.10 and dev builds

#### Expected Behaviour
Api return results from popcorn-api instead of cloudflare cache

#### Actual Behaviour
Actually, since one week, PT get responses from the cloudflare cache instead of the popcorn-api.

#### Steps to reproduce the behaviour
1. Try to request PT api directly from browser or something, you get error 503.
2. Open PT and debug node-module "butter-provider-movies-es6" to find that responses come from cloudflare

#### Personal suggestions
1. Fix actual API server or use alternatives APIs (if there is some alternative popcorn-api available somewhere, or YTS/eztv api directly)

**Comment by Persei08** [comment]
Popcorn-api is back.

Can eventually someone tell us more about what happened ?

Should we (the community/contributors/users) not host alternative api servers as fallback instead of starting to become anxious when the main one is down?

**Comment by eline2244** [comment]
what is it going I do not know to do it annoying but I do not see why we can not watch movies more that s the point

**Comment by ehssh** [comment]
Popcorn-api is down again

**Comment by eline2244** [comment]
ooooo what is this annoying friend of mine also has the same problem he popcorn time

**Comment by tiffanyhaltom** [comment]
Is anyone else still having issues? I've encountered some odd behavior with Search. It seems that past search results have been cached and easily fetched, but any new searches result in hanging. When inspecting console, Cloudfare request returns 503. I wonder if the Cloudfare account has been shut off?

**Comment by Persei08** [comment]
@tiffanyhaltom No. I think it is just because clouflare cache the most popular search results. But actually API is back again, so every search should work again

**Comment by Persei08** [comment]
i'm closing the issue since it seem fixed
