### ISSUE TITLE
yes I I still can not play movies and the trailers do it if I want to watch a movie only connect more done nothing

### ISSUE THREAD

**Issue by eline2244** [popcorntime/popcorntime#1057]
Operating System Version:
0.3.10-0

Download date:
a week a go

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Stop spamming! Ask help on reddit : https://www.reddit.com/r/PopCornTime/
