### ISSUE TITLE
can't Able to see the subtitles over wifi connection but when I use personal hotspot from mobile I Can able to get automatically 

### ISSUE THREAD

**Issue by sai241994** [popcorntime/popcorntime#1058]
Operating System Version:

OS X
Popcorn Time Version:

New Version
Download date:

over year
#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
This is the issue board for reporting bugs about the development version.

For support and help ask on reddit: https://www.reddit.com/r/PopCornTime/
