### ISSUE TITLE
VLC doesn't open during stream

### ISSUE THREAD

**Issue by HafMann** [popcorntime/popcorntime#1063]
Operating System Version:
Windows 10 

Popcorn Time Version:
 3.10 

Download date:
5/30/2019 

#### Expected Behaviour

Play a movie on VLC media player from Popcorn Time
...

#### Actual Behaviour

When I select VLC Popcorn Time loads the movie and says "Streaming to VLC" yet VLC doesn't open at all.
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
VLC version ?  
Movie title to test?

**Comment by HafMann** [comment]
Currently have version VLC version 3.0.8 Vetinari
And the issue began when I tried to watch "Star Trek: Nemesis"

**Comment by Persei08** [comment]
I'm i don't know, it works for me.

Try a clean reinstall of VLC, restart PT and retry. If it don't work try also a clean reinstall of PT and retry.

**Comment by kiriles90** [comment]
@Persei08 not an actual Popcorn Time issue, close please
