### ISSUE TITLE
I have a problem managing my favorites

### ISSUE THREAD

**Issue by bart766** [popcorntime/popcorntime#1065]
everything I tick as a favorite is not added
the heart is indicated in red
but is not in the list of favorites

Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 close please
