### ISSUE TITLE
I have problem with bower.json

### ISSUE THREAD

**Issue by EVOgeek618** [popcorntime/popcorntime#1066]
Operating System Version: Ubuntu 8.2

Popcorn Time Version: 0.33.4

Download date: 10.14.2019

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

When i try build popcorn with "gulp build", I have error "No bower.json present". This problem was decided in version 0.35.3, but when i clone Popcorn, version is 0.33.4.

**Comment by Persei08** [comment]
Your version number isn't correct, I guess you're not using a version from this repo.

but I think you use wrong command. PT development branch switched to yarn around November 2018.

Check the new instructions: https://github.com/popcorn-official/popcorn-desktop#quickstart
