### ISSUE TITLE
Suggestion: Make subtitle languages into categories so that multiple subs can be downloaded from OpenSubtitles per language rather than just one.

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1067]
OpenSubtitles has multiple subs per language for different releases, but PopcornTime gets only one which more often than not results in bad subs.

Solution: Make each language into a category so that the user can select the next subs if the default file is bad.

**Comment by Persei08** [comment]
Already done in development version

**Comment by ghost** [comment]
Nice. Do you reckon I can upgrade without losing all of my settings again? Long time ago after I updated popcorntime I lost all my settings, watched shows and bookmarks.

**Comment by Persei08** [comment]
I can't guarantee nothing. Backup your popcorntime settings folder if you fear to lost them. 

I think multiple subtitles results were introduced since dev build 293. and 293 is IMO the best dev build to use ATM (less bugged).

**Comment by ghost** [comment]
Thank you. This dev build is doing exactly what I wanted.  

> **For anyone that wants build 293:**
> 
> https://mega.nz/#F!20VBkaqK!yVC2H-yAKtc32hZgmCnUqw (Dev builds here, because for some reason the devs removed them from the official website)
> 
> As you can see the dev build 293 is the linux version, **to use with windows**:
> 
> Open the file with 7zip and extract only:
> 
> node_modules\\
> src\\
> .git.json
> icudtl.dat
> nacl_irt_x86_64.nexe
> natives_blob.bin
> nw_100_percent.pak
> nw_200_percent.pak
> package.json
> 
> Put those files in your popcorntime folder and voila you have build 293 for Windows. 
> 
> **I recommend deleting those same files and folders from your popcorntime folder first before you move in the new ones, since Windows takes its sweet time comparing each of them and there's thousands of files so it would take a while, if you delete them first it only takes a minute to copy them over.**

**Comment by Persei08** [comment]
>because for some idiotic reason the devs removed them from the official website

For which reason you said they removed them for "idiotic reason" ? Do you really know or you're saying that for free?

**Comment by ghost** [comment]
There's no reason stated. There's zero communication from the devs. I said idiotic because I was angry that the dev builds were so hard to find... I had to scour some old reddit threads in order to find them posted by some guy that had a few of them saved. They probably had their reason, but at least upload the dev builds somewhere else first if you have to close that part of the website down...

Anyway, I removed the term as it was not very nice of me.

**Comment by Persei08** [comment]
>to find them posted by some guy that had a few of them saved.

Yeah, that's me :smile: 

>They probably had their reason, but at least upload the dev builds somewhere else first if you have to close that part of the website down...

I doubt it is really intentional. There was a series of issues. If I remember correctly, 1rst there was an issue with download, then was an ssl certificat issue and now the server timeout.

But yes, there is probably a lack of communication, and we don't really know what is going on.

**Comment by ghost** [comment]
> Yeah, that's me 😄

Ohh. Haha, thank you for the uploads then. They were very helpful.

> But yes, there is probably a lack of communication, and we don't really know what is going on.

Oh well, it is what it is. ¯\\\_(ツ)\_/¯
