### ISSUE TITLE
Can not play movies using either Butter or VLC.

### ISSUE THREAD

**Issue by Usalabs** [popcorntime/popcorntime#1069]
Operating System Version:
Windows 10 Home Premium

Popcorn Time Version:
0.3.10 Beta

Download date:
4 days a go from https://popcorntime.sh/

#### Expected Behaviour
Play a movie either using Butter or VLC
...

#### Actual Behaviour
Throws up this error when trying to use VLC:-
VLC is unable to open the MRL 'http://127.0.0.1:63580/'. Check the log for details.
And when using Butter I get:-
The video could not be loaded, either because the server or network failed or because the format is not supported.
...

#### Steps to reproduce the behaviour

1. ...Choose a movie
2. ...Click Play Now (using default Butter), show an error
3. ...Change player to VLC, and get bad url.

Here's the PT Logs File:-
[logs.txt](https://github.com/popcorn-official/popcorn-desktop/files/3732583/logs.txt)

**Comment by Jonadabe** [comment]
Hi there,

I had the same problem and it was because I uninstalled flash player. Try to install it again. The problem that I see is when flash drop occur, what then?

**Comment by Usalabs** [comment]
I don't see how flash player can be the culprit, because even when using VLC, so that popcorn time can stream through it, it seems to try and open a localhost url, but if I were to close the error box in VLC, then click on 'Media', then click open file, and navigate to the popcorn time folder where the movie is being downloaded to, then select the video MP4 file, it plays with no problem, but popcorn time app can't stream to VLC or even it's own player (Butter).

I just looked at my programs list and I see Flash Player 32 PPAPI is installed, and uninstalling it and reinstalling it made no difference.

**Comment by Persei08** [comment]
@Usalabs It don't require flash player. It was coincidence.

Doess it happen with all movies, or just some ones ?

Can you provide a title which have this issue?

**Comment by DJChoi00** [comment]
It's strange has I am getting the error message for some episodes in a tv series but not for others.  I have switch from 720p to 420p and it sometimes work. And only been using Butter. Maybe I'll download VLC and see if I get better results.

**Comment by Persei08** [comment]
Seem like you guys have codec issues. 

In butter player it is because it don't support all codecs and you end either with an error message saying something like it's a 'network or format issue', or a black screen with audio working (since the begining of movies are often silent for few seconds you can check if the playing time counter still run in controls bar).

For VLC, it's the rendering option... You should check in VLC settings and try them one by one to see which one work better with computer

**Comment by Mladia** [comment]
I have the same problem. Butter does say "network or format issue" and vlc has the same error message as @Usalabs.
The torrent continues downloading in the background. I can open the video file with vlc and everything runs as intended, no codecs problems. After a while, the torrent is finished and the seeking in the whole video works.  Still, automatic playback through butter or vlc gives out a false error.
Linux, Popcorntime 0.4.1-0

**Comment by Usalabs** [comment]
> @Usalabs It don't require flash player. It was coincidence.
> 
> Doess it happen with all movies, or just some ones ?
> 
> Can you provide a title which have this issue?

It's all titles no matter which one, oh and sorry for replying to late, but it seems that Googles email system pushes these messages elsewhere and not in my inbox, neither in junk folder either, anyway, it seems popcorn time uses a local address of 127.0.0.1 as a streaming server to stream the video for either Butter or VLC to play from, and doesn't use video files directly, which further investigation showed that localhost (127.0.0.1) is in use by something other than popcorn time and it seems it's in use by the Windows subsystem for local networks, (as I have an internal network setup for various computers in the building), using a VPN makes no difference either, it seems to me that the dev's of popcorn time need to change the part that feeds Butter or VLC a url and change to use a direct file access taking the file from the location where the video file(s) are being downloaded to.

EG
Instead of popcorn time using it's internal server and sending a 127.0.0.1 MRL to either Butter or VLC, just send the file name along with its location to the player(s), IE, if popcorn time is downloading videos to the default location, then send that location along with the filename to Butter or VLC, then it'll work.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
