### ISSUE TITLE
Urgent a reload button

### ISSUE THREAD

**Issue by StarLordFree** [popcorntime/popcorntime#107]
You need to insert a button for reload the app and the movies, because i have to download 3.9 version everytime i want to see new movies and the subtitules. Maybe if you insert a button: looking updates or new changes.

Operating System Version:
 Windows 10

Popcorn Time Version:
 3.9

Download date:
 Today
#### Expected Behaviour

 Good, but im actually very confused about what is the true POPCORN TIME
...

**Comment by VitorVRS** [comment]
Popcorn doesnt have updater yet, there is an issue to develop that.

**Comment by Breaking1** [comment]
I think you can reload/restart PT with F11(Windows).

This is the true and official popcorntime version.
