### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by dmvsnapshot** [popcorntime/popcorntime#1070]
Operating System Version:
 Mac OS

Popcorn Time Version:
3.10

Download date:
 today

#### Expected Behaviour

... will not load movies 

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Can't reproduce.

You can ask help to the community on https://www.reddit.com/r/PopCornTime/
