### ISSUE TITLE
Missing some movies

### ISSUE THREAD

**Issue by anon45697** [popcorntime/popcorntime#1074]
Operating System Version:
 Windows 10

Popcorn Time Version:
 Latest

Download date:
 Today

#### Expected Behaviour

...

#### Actual Behaviour

… Scary Movie 2 3 4 is missing 
   prom night 2 3 4 is missing 
   slient night deadly night 3 4 5 is missing

#### Steps to reproduce the behaviour

1. … 
2. ...
3. ...

**Comment by Persei08** [comment]
Movies list is provided by yts.lt actually

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
