### ISSUE TITLE
missing some movies 

### ISSUE THREAD

**Issue by anon45697** [popcorntime/popcorntime#1075]
Operating System Version:
 Windows 10

Popcorn Time Version:
 latest

Download date:
 today

#### Expected Behaviour

… need 100% every movie to date

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. … 
2. ...
3. ...

**Comment by ghost** [comment]
The extended cuts of the hobbit and the lord of the rings aren't on popcorn time 6.2 for windows

**Comment by Persei08** [comment]
Duplicate of #1074
