### ISSUE TITLE
Error in Series episode listings 

### ISSUE THREAD

**Issue by crave98** [popcorntime/popcorntime#1076]
Operating System Version:

OS X 10.15
Popcorn Time Version:

3.10
Download date:

2 days ago
#### Expected Behaviour

...
show the correct episode listings 
#### Actual Behaviour

...
added random episode listings that are not related to the series or anything 
#### Steps to reproduce the behaviour

go to series tab
1. ... find "Madam secretary"
2. ...error can be found on " season 13" 
3. ... episode 21 " the seeds of doom "
 
_ this season 13 or episode 21 doesn't exist in the series and is not related, 
I have seen this exact error showing in other tv shows also and behaving in the same way.
Somehow its just added itself to many listings on your database...

<img width="1440" alt="Screen Shot 2019-10-28 at 3 14 36 pm" src="https://user-images.githubusercontent.com/57083047/67651574-cad65c00-f995-11e9-8838-7ce74147e4be.png">

**Comment by Persei08** [comment]
Can confirm this issue.

The entry is corrupted in popcorn-api.
imdb_id of show: tt3501074
episode  number: 116
tvdb_id of episode: 297513

**Comment by kiriles90** [comment]
@Persei08 is this something than can be fixed or should we close this?

**Comment by Persei08** [comment]
I don't know why but it's s01e21 of madam secretary but the episode have metadata of  Dr Who S13E21 - The Seeds of Doom (1)

The issue have nearly one year, it isn't blocking the app to function... let's close it. someone will ask again eventually
