### ISSUE TITLE
Add Rotten Tomatoes rating

### ISSUE THREAD

**Issue by aneeskA** [popcorntime/popcorntime#1077]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
28-Oct-2019

#### Expected Behaviour
A way to sort based on Rotten Tomatoes instead of IMDB
...

#### Actual Behaviour
Only IMDB sorting is allowed
...

#### Steps to reproduce the behaviour
Sort option

Excellent tool, but Rotten Tomatoes rating is more often reliable than IMDB. So pretty please?

**Comment by Persei08** [comment]
Is not IMDB rating but trakt.tv rating... not really important, but now you know :)

**Comment by ghost** [comment]
> Excellent tool, but Rotten Tomatoes rating is more often reliable than IMDB. So pretty please?

Really? Have you not seen critics basing their score on how much social justice there is in the movie? IMDB all the way.

**Comment by kiriles90** [comment]
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1659, close please
