### ISSUE TITLE
unable to log in to trakt

### ISSUE THREAD

**Issue by Oakey76uk** [popcorntime/popcorntime#1078]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
2 weeks ago

#### Expected Behaviour
Log into Trakt

#### Actual Behaviour
Shows all steps to log in but doesn't connect

#### Steps to reproduce the behaviour
Enter login details and select yes

**Comment by ImJustTheCat** [comment]
Same Issue for me #801 describes it exactly.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
