### ISSUE TITLE
title buttons on windows

### ISSUE THREAD

**Issue by riclas** [popcorntime/popcorntime#1082]
Operating System Version:
Windows 10

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour
The topbar button images are not shown properly. I have tried tinkering with the styl file but no progress. Seems like an artifact from changing 20px to 45px buttons.

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Fixed #1151
