### ISSUE TITLE
Stopped werking on Fedora 31

### ISSUE THREAD

**Issue by rebelC0der** [popcorntime/popcorntime#1083]
Operating System Version:
Fedora 31

Popcorn Time Version:
1) 0.3.10
2) 0.3.8

Error when launching:
Window shows up, starts loading then disappears and terminal shows this:

```
[3761:3761:1105/171205:ERROR:sandbox_linux.cc(345)] InitializeSandbox() called with multiple threads in process gpu-process. 
/usr/share/popcorntime/Popcorn-Time[3764]: ../../third_party/node/src/node_crypto_bio.h:83:static node::NodeBIO *node::NodeBIO::FromBIO(BIO *): Assertion `(bio->ptr) != (nullptr)' failed.
/usr/bin/popcorntime: line 2:  3729 Illegal instruction     (core dumped) ./Popcorn-Time

```

**Comment by Persei08** [comment]
Fixed in dev builds.

The version you use 3.10 is old and mostly outdated. People reporting issues should better use dev builds or build PT from the development branch.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
