### ISSUE TITLE
Can't compile - ENOENT No bower.json present

### ISSUE THREAD

**Issue by drasko** [popcorntime/popcorntime#1088]
Operating System Version:

Linux Debian

Popcorn Time Version:

master

Download date:

Couldn't compile master

#### Expected Behaviour

Compile fine

#### Actual Behaviour

```
added 1299 packages from 716 contributors and audited 13408 packages in 38.786s
found 10 vulnerabilities (4 low, 2 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Local dependencies installed successfully!
Local permissions corrected successfully!
Setting up Bower
bower                           ENOENT No bower.json present
Encountered an error while installing bower
```

#### Steps to reproduce the behaviour

Run `./make_popcorn.sh

**Comment by Persei08** [comment]
Not sure if the script is working or not.

On Ubuntu 18.04 I build it with those instructions:


   1. yarn config set yarn-offline-mirror ./node_modules/
   1. yarn install --ignore-engines
   1. yarn build
   1. yarn gulp run
