### ISSUE TITLE
Website down ?? Popcorntime dead?

### ISSUE THREAD

**Issue by kronikpillow** [popcorntime/popcorntime#1089]
what happened to the popcorntime.sh website? it can't be reached

**Comment by virtualdxs** [comment]
There is a dot TW website that claims to be the replacement, but we haven't seen any real proof that it's legit. If a developer could chime in on this, that would be really helpful.

**Comment by kronikpillow** [comment]
url?

**Comment by virtualdxs** [comment]
I'd rather not post it as there is no evidence as of yet to show that it's legit. If you still want to see it (which I seriously advise against), you can find it by searching the subreddit r/popcorntime.

**Comment by Persei08** [comment]
popcorntime.sh domain was disabled by registrar but the apps and the popcorn-api are still working.

Check reddit subreddit: [/r/popcorntime](https://www.reddit.com/r/PopCornTime/) for news and discuss it.

Edit: **Website is up again**.

**Comment by Breaking1** [comment]
Its up and running again https://popcorntime.sh/
