### ISSUE TITLE
Movie pictures not showing on favorites view

### ISSUE THREAD

**Issue by crbelaus** [popcorntime/popcorntime#109]
Operating System Version: Ubuntu 14.04 LTS

Popcorn Time Version: 0.3.9

Download date: I don't remember, sorry
#### Expected Behaviour

When I open the _favourites_ view I expect to see my favourite movies and series along with their pictures.
#### Actual Behaviour

Movies are showing but they use a generic picture instead of the proper one. Meanwhile pictures for series are properly shown. [Click to see a picture showing the problem](http://i.imgur.com/p9mgER1.png)
#### Steps to repoduce the behaviour
1. Go to the _movies_ view and mark a movie as favourite. 
2. Go to the _series_ view and mark a serie as favourite.
3. Go to the _favourites_ view. You will see both the movie and the serie, but the movie has a generic picture.

**Comment by VitorVRS** [comment]
@team-pct  this issue can be closed.
