### ISSUE TITLE
Resize Thumbnails Option

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1091]
Add an option to resize the movie thumbnails to make them bigger or smaller

![345345](https://user-images.githubusercontent.com/18757054/69005638-5ef86b00-0925-11ea-9934-c41a8cb8f42d.jpg)

**Comment by Breaking1** [comment]
This already exists, if you press shift+? you will get all the short cuts you can use in popcorntime. This can also be found by going to settings and press the pic of a keyboard on top of the page.

ctrl and + will enlarge covers
ctrl and - will reduce covers

**Comment by GKid94** [comment]
Can you add a slider like on this website https://popcorntime-online.ch/

**Comment by Persei08** [comment]
Duplicate of #1155 :/

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
