### ISSUE TITLE
No Sound on Archlinux

### ISSUE THREAD

**Issue by GrbavaCigla** [popcorntime/popcorntime#1092]
Operating System Version:
Arch Linux, Kernel:5.3.11

Popcorn Time Version:
nwjs 74.0.3729.169

Download date:
Recently (About an hour ago)

#### Actual Behaviour
Sound just doesn't work on any Movie/TV Serie
I Tried more then all episodes of Disenchantment, Silicon Valley, Rick and Morty, also tried a lot of films, but no sound. Vlc works.

#### Steps to reproduce the behaviour
Install Popcorntime with AUR: https://aur.archlinux.org/packages/popcorntime/

**Comment by Persei08** [comment]
I think it happen because the sound codecs aren't supported by the nwjs version used.

some supported codec were dropped lately due to difficulties to builds the custom nwjs with all the extra codecs and the need for a more recent nwjs version.

You should better use VLC for the moment.

**Comment by GrbavaCigla** [comment]
But when VLC reaches the end, it just stops and doesn't work again. So I Have to redownload torrent.
Is there any solution to use butter with sound,maybe downgrade?

**Comment by Persei08** [comment]
https://aur.archlinux.org/packages/popcorntime-bin/ will install the 0.3.10 from 2016 with a custom nwjs version supporting extra codecs

**Comment by GrbavaCigla** [comment]
Thanks! It works!
