### ISSUE TITLE
cannot stream to lg webos

### ISSUE THREAD

**Issue by jmaric** [popcorntime/popcorntime#1096]
Operating System Version:

linux mint latest

Popcorn Time Version:

3.10.0

Download date:

#### Expected Behaviour

...i was trying to stream movie on my lg tv webos

#### Actual Behaviour

 popcorn time doesnt recognize my webos device. There is no button to stream
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
