### ISSUE TITLE
FFmpegDemuxer: no supported streams

### ISSUE THREAD

**Issue by Franchute13** [popcorntime/popcorntime#1097]
Operating System Version:
Linux, ubuntu 18

Popcorn Time Version:
3.10 #374

Download date:
2019/12/02

#### Expected Behaviour

Watch movie

#### Actual Behaviour
Error while trying to watch the movie

The media could not be loaded, either because the server or network failded or because the format is not supporte

Console log
[28018:28154:1202/211256.461266:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[28018:28018:1202/211256.461329:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS

**Comment by natescaringi** [comment]
Having the same error, would appreciate some help...

**Comment by edomato** [comment]
Hi,

I still need to check out why this is happening, but I tried with a new clean account on my Linux box and it worked just fine, I had this problem with the everyday account.

So, what I recommend is to test again with a new "clean" account on your system.

Greets.

**Comment by team-pct** [comment]
Build #380 should fix that
