### ISSUE TITLE
Not connecting to sources to stream

### ISSUE THREAD

**Issue by julesmoretti** [popcorntime/popcorntime#1098]
Operating System Version:
OS X 10.15.1

Popcorn Time Version:
0.3.10

Download date:
Dec 2nd 2019

#### Expected Behaviour
When clicking on *Watch Now* for a connection to establish and for some data to download...

#### Actual Behaviour
After clicking on *Watch Now* it hangs on the *Connecting* screen and never connects.

#### Steps to reproduce the behaviour
1. Download PopCorn time from https://popcorntime.sh/ 
2. Enable all security accesses needed
3. Browse for a new film like Rambo
4. Click on *Watch Now*

**Comment by Persei08** [comment]
Sound like a network issue on your side. Maybe your ISP is blocking the trackers or something and you can't connect to other users to download the files.
