### ISSUE TITLE
Popcorn-Time quit unexpectedly

### ISSUE THREAD

**Issue by kessiler** [popcorntime/popcorntime#110]
Operating System Version: OS X 10.11
Popcorn Time Version: 3.9
Download date: Couple months ago
#### Expected Behaviour

No crash at all.
#### Actual Behaviour

Application Specific Information:
objc_msgSend() selector name: windowDidResize:

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                 0x00007fff9c91f4dd objc_msgSend + 29
1   com.apple.CoreFoundation        0x00007fff8d02267f ___CFXRegistrationPost_block_invoke + 63
2   com.apple.CoreFoundation        0x00007fff8d021d47 _CFXRegistrationPost + 407
3   com.apple.CoreFoundation        0x00007fff8d021ab2 ___CFXNotificationPost_block_invoke + 50
4   com.apple.CoreFoundation        0x00007fff8d01bd42 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
5   com.apple.CoreFoundation        0x00007fff8cf0a145 _CFXNotificationPost + 693
6   com.apple.Foundation            0x00007fff8b9c9921 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
7   com.apple.AppKit                0x00007fff8fd3f84e -[NSWindow _setFrameCommon:display:stashSize:] + 3507
8   com.apple.AppKit                0x00007fff8fd3ea8c -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
9   com.apple.AppKit                0x00007fff8fd3e9a7 -[NSWindow setFrame:display:] + 67
10  com.apple.AppKit                0x00007fff8fe30745 __25-[NSWindow setStyleMask:]_block_invoke + 2241
11  com.apple.AppKit                0x00007fff904ac659 NSPerformVisuallyAtomicChange + 147
12  com.apple.AppKit                0x00007fff8fe2fe05 -[NSWindow setStyleMask:] + 222
13  com.apple.AppKit                0x00007fff8ffb3201 -[NSWindow _didExitFullScreen:] + 309
14  com.apple.AppKit                0x00007fff905c5c89 __123-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:windowController:options:customWindows:doKitAnimation:]_block_invoke_2 + 397
15  com.apple.AppKit                0x00007fff905c59ec __123-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:windowController:options:customWindows:doKitAnimation:]_block_invoke + 1300
16  com.apple.AppKit                0x00007fff904d8ad3 __177-[NSDockConnection(FullScreenMessages) sendFullScreenExitForTransition:synchronous:window:exitForClose:backgroundWindows:participatingWindows:customAnimation:completionHandler:]_block_invoke + 60
#### Steps to repoduce the behaviour

Watch any tv series that you wanna watch in fullscreen and wait :)

I guess, this would be fixed with https://github.com/popcorn-official/popcorn-desktop/pull/73.

**Comment by ChrisAlderson** [comment]
If it is fixed with #73 try ([159](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/159/))
