### ISSUE TITLE
Missing episodes after 27 November

### ISSUE THREAD

**Issue by voodoobg** [popcorntime/popcorntime#1100]
Operating System Version:

Windows
Popcorn Time Version:

Lastest
Download date:

Today, so that I can confirm it's a bug
Expected Behaviour

...
Actual Behaviour

Missing episodes after 27 November
Steps to reproduce the behaviour

Everything works except that no new episodes are showing up after 27 November, I've reinstalled Popcorn Time but the result is the same.

**Comment by jmorsut** [comment]
Same issue here. Episodes have not been updating for T.V. shows for the last two weeks.  Don't know if I should do a reinstall, flush all databases or reset to default settings.

**Comment by Persei08** [comment]
@jmorsut there is nothing to do on user side. The issue is with the API.. on the api server

**Comment by jmorsut** [comment]
That sucks. Thanks for the heads up.

**Comment by liron-navon** [comment]
It does seem to work fine for me (OSX 10.14 and Windows 10), rick & morty, southpark, harley queen (the animated series), and silicon valley, all seem to have been updated in the last weeks properly...

Maybe you talk about a specific series?

**Comment by thom4parisot** [comment]
Listings are just fine now. Seems the API has been restored to display updated results.

**Comment by voodoobg** [comment]
For me it's working again also. I'm closing this.
