### ISSUE TITLE
Autoplay next episode

### ISSUE THREAD

**Issue by liron-navon** [popcorntime/popcorntime#1104]
I'm not sure if this is a feature request or a bug since this Reddit question (from 1 year ago) suggests that this feature should already exist: https://www.reddit.com/r/PopCornTime/comments/9c1l2o/autoplay/

Operating System Version:
OS X 10.14.6

Popcorn Time Version:
6.1.2

Download date:
11-12-2019 (same day as I created this issue)

#### Expected Behaviour
When I watch a series, I would like to be able the play the next episode as soon as the episode is over (either automatically after a set amount of time, or with a single button), kind of like Netflix does, since it's easier to binge-watching like that.
There doesn't seem to be any setting for such a feature in the settings menu.
...

#### Actual Behaviour
When the episode is over, it just goes into a black screen until I click X to go back to the menu.
...

#### Steps to reproduce the behaviour
1. Watch any series
2. Wait for the episode to be over
3. That's it, it should start playing the next episode
...

If this feature doesn't exist and you would like to add it, I would be more than happy to contribute by implementing it myself =)

**Comment by FlashyReese** [comment]
I'm pretty sure it is already a feature while it has been for a long while now, judging by the version you comment it is not from https://popcorntime.sh/ it's been on 3.10 for a while now. I have tried on the Windows and Linux versions and both seem to work fine.

**Comment by Persei08** [comment]
I close this issue. OP is about another project
