### ISSUE TITLE
some wrong info in README which is inside the zip file which I downloaded form official site.

### ISSUE THREAD

**Issue by PranavBhattarai** [popcorntime/popcorntime#1105]
OS: Ubuntu 19.10
Downloaded this file name: Popcorn-Time-0.3.10-Linux-64.tar.xz
Extracted it and there is no `./make_popcorn.sh` as mentioned in README.

**Comment by danielrc14** [comment]
The readme is really broken

**Comment by snowc0de** [comment]
Yes there is a big problem with documentation in this project. And unfortunately, nobody seems to care about it.

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop#getting-started
The readme says to optionally run `./make_popcorn.sh` if you are building from a `git clone.` 

You have no need for it if you downloaded the .tar.xz its already built.
