### ISSUE TITLE
Cannot install to directory other than C:\Program Files

### ISSUE THREAD

**Issue by gslasor** [popcorntime/popcorntime#1106]
Operating System Version:
Windows 10 Home

Popcorn Time Version:
6.2.0.13

Download date:
2019-12-12

#### Expected Behaviour
Install to my second HDD
...

#### Actual Behaviour
Installs to C:\Program Files(x86), even when another directory is selected.
...

#### Steps to reproduce the behaviour

1. Download latest popcorn time installer 
2. Run as administrator from C:\Users\<Username>\Downloads
3. Select a folder on a different hard drive, say D:\Program Files
4. Click "Next" -> The app installs to C:\Program Files (x86)\Popcorn Time

![image](https://user-images.githubusercontent.com/15150448/70855557-b5ac8280-1e9a-11ea-8494-99078f417e33.png)

![image](https://user-images.githubusercontent.com/15150448/70855562-c957e900-1e9a-11ea-9539-b27b2f954945.png)

![image](https://user-images.githubusercontent.com/15150448/70855568-d7a60500-1e9a-11ea-8fcf-4aa4cacf77aa.png)

**Comment by Persei08** [comment]
You use Time4popcorn fork, you should report to them.
This repo is for version available at popcorntime.sh website
