### ISSUE TITLE
PopCorn 64, does not run on windows 10 64bits

### ISSUE THREAD

**Issue by Franchute13** [popcorntime/popcorntime#1107]
Operating System Version:
Windows 10 64 bits

Popcorn Time Version:
#374

Download date:
Today

#### Expected Behaviour
Run, load popcorn time

#### Actual Behaviour
Do not open the application.
In the Debug.log file it says:
ERROR: main_dll_loader_win.cc (145)] Failed to load NW DLL from XXXX \ nw.dll:% 1 is not a valid Win32 application.

#### Steps to reproduce the behaviour

1. ... Download #374 
2. ... install
3. ...try to run

**Comment by Franchute13** [comment]
popcorn 64bit and windows 10 64

**Comment by scyto** [comment]
working fine here, try downloading again

**Comment by Franchute13** [comment]
Hi scyto. New version #388 work fine!, the #374 don't work correct.
