### ISSUE TITLE
Add movies in other languages

### ISSUE THREAD

**Issue by wuniversales** [popcorntime/popcorntime#1110]
It would be nice to add the possibility of listening to the movies in Spanish and other languages ...

**Comment by ghost** [comment]
It would be nice to have the extended editions of the hobbit and the lord of the rings on popcorn time

**Comment by ivan1986** [comment]
@wuniversales 
i write server for russian trackers
https://github.com/ivan1986/popcorn-ru
it's may extends for any languages 
if you know some spanish or other trackers you can get me links and i write modules for it
spider for tracker it just one simple php class

**Comment by ivan1986** [comment]
@toonbartholome need add interface for show all torrents by film then user can select extended edition or some author translate for example (for LofR goblin translate for example)
