### ISSUE TITLE
This repository won't be maintain anymore.

### ISSUE THREAD

**Issue by datnguyencse** [popcorntime/popcorntime#1111]
Oldest pull request and issue was two years ago. So I decided to fork and continue to maintain this project, feel free to open issue and pull request to my fork, I promise to resolve all of them and release new version every 6 months.

[Popcorn Desktop Fork](https://github.com/datnguyencse/popcorn-desktop)

**Comment by ivan1986** [comment]
https://github.com/datnguyencse/popcorn-desktop/blob/development/src/app/lib/popcorn.bin

https://github.com/datnguyencse/popcorn-desktop/commit/62e1f361f16023e79c776abe4385c20be7b9f610#diff-5c7a0450198c31089d049bdbf5f63223

WTF?

**Comment by datnguyencse** [comment]
> https://github.com/datnguyencse/popcorn-desktop/blob/development/src/app/lib/popcorn.bin
> 
> [datnguyencse@62e1f36#diff-5c7a0450198c31089d049bdbf5f63223](https://github.com/datnguyencse/popcorn-desktop/commit/62e1f361f16023e79c776abe4385c20be7b9f610#diff-5c7a0450198c31089d049bdbf5f63223)
> 
> WTF?

Ops sorry, That binary is for Vietnamese version, I forgot to remove it when I merge features from `https://github.com/datnguyencse/popcorn-desktop-vn`.  I'll delete and fallback that commit.
For Vietnamese version, I save all video files on server and encode the webseed url before send to popcorn and decode by popcorn.bin
Example: `http://anime-vi.popcorn-api.io/anime/5d341d85338e4805291a6c0f` return 
`"url": "popcorn:d35dd6a57c9de4504b60cefea852054c15145b8401c0bfa5db56f54683351cb5b66e8cb9a305378a1e9301b872b8d5afd4aed63af24237d2f65589d44b3b8091cf398eb714d0f6f12a9bbda71b223c5d82b53b199785e7f36cbea930e1c201f4b29eebbd80e242b893552af4d83e96d441b2f0b635af2c183bf8981a3a17aed1db9fca0f46f47710fc3e8d682b7b34daf58635ed1e2af671368a01e7a55edecd8db25ef96ba819cf74bf15b88da1fb1f"`

Decode this link by popcorn.bin will return the direct link to the video files.

**Comment by datnguyencse** [comment]
> https://github.com/datnguyencse/popcorn-desktop/blob/development/src/app/lib/popcorn.bin
> 
> [datnguyencse@62e1f36#diff-5c7a0450198c31089d049bdbf5f63223](https://github.com/datnguyencse/popcorn-desktop/commit/62e1f361f16023e79c776abe4385c20be7b9f610#diff-5c7a0450198c31089d049bdbf5f63223)
> 
> WTF?

Ops sorry, That binary is for Vietnamese version, I forgot to remove it when I merge features from `https://github.com/datnguyencse/popcorn-desktop-vn`.  I'll delete and fallback that commit.
For Vietnamese version, I save all video files on server and encode the webseed url before send to popcorn and decode by popcorn.bin
Example: `http://anime-vi.popcorn-api.io/anime/5d341d85338e4805291a6c0f` return 
`"url": "popcorn:d35dd6a57c9de4504b60cefea852054c15145b8401c0bfa5db56f54683351cb5b66e8cb9a305378a1e9301b872b8d5afd4aed63af24237d2f65589d44b3b8091cf398eb714d0f6f12a9bbda71b223c5d82b53b199785e7f36cbea930e1c201f4b29eebbd80e242b893552af4d83e96d441b2f0b635af2c183bf8981a3a17aed1db9fca0f46f47710fc3e8d682b7b34daf58635ed1e2af671368a01e7a55edecd8db25ef96ba819cf74bf15b88da1fb1f"`

Decode this url by popcorn.bin will return the direct link to the .torrent file. It's my bad because I forgot to delete this binary file when I merge new features I wrote for  `popcorn-desktop-vn` to `popcorn-desktop`. I'll delete them right now.

For the Vietnamese version of popcorn, all the animes video file is saved on cloud and return the direct link as a webseed because there're no seed available, that why I have to protect the direct link with popcorn.bin

Update: Binary file removed.

Popcorn Desktop for VN
![screenshot_12](https://user-images.githubusercontent.com/11866125/71884453-fb432f00-316a-11ea-9c1e-fc82cc00340e.png)

**Comment by VitorVRS** [comment]
Seems to be convenient to ship a hidden binary file in your project

**Comment by confuzled-dev** [comment]
So is this safe to use? The main repo seems to have bad build instructions

**Comment by Persei08** [comment]
What do you mean by "This repository won't be maintain anymore"?

@team-pct have merged a pull request 5 days ago.. Is this an official statement or you're just promoting your fork?

**Comment by datnguyencse** [comment]
@Persei08 They continue their work on popcorn project because of someone like me. When they back with popcorn and spend more time on it, resolve all issues, merge pull requests and release new version, I'll contribute my work from my fork to it or else I will help them do it on my own fork.

Popcorn is opensource and nonprofit project, there are no reason to promoting it.
