### ISSUE TITLE
Philips Hue listed as cast device

### ISSUE THREAD

**Issue by dossjjx** [popcorntime/popcorntime#1112]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10 Beta

Download date:
1/3/2020

#### Expected Behaviour
Show Chromecast/DLNA devices only

#### Actual Behaviour
Shows Philips Hue hub as a "cast-able" device

#### Steps to reproduce the behaviour
1. Have Philips Hue smart light hub connected to home network
2. Select any title in Popcorn Time
3. Select dropdown for cast devices
4. Notice Philips Hue as a device in list

Screenshot:
![2020-01-02 23_51_42-Butter](https://user-images.githubusercontent.com/35515947/71710036-e14aca80-2dbf-11ea-948c-31d0d734cae8.png)

**Comment by oshank** [comment]
I wouldn't call this an issue with PT itself, but rather with the implementation of how Philips Hue connects to the network or how Windows picks up the devices on the network.

**Comment by kiriles90** [comment]
@Persei08 not an actual Popcorn Time issue? close please
