### ISSUE TITLE
os filmes de Harry Potter não tem legenda?

### ISSUE THREAD

**Issue by anarapha** [popcorntime/popcorntime#1113]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by utkarshsethi** [comment]
If you are watching on a PC I suggest to use VLC+VLSub

https://addons.videolan.org/p/1154045/
https://github.com/exebetche/vlsub

While the devs find time to fix your issue.

**Comment by Persei08** [comment]
Subtitles are requested to and downloaded from opensubtitles.org.
Someone need to upload good subtitles to opensubtitles so PT can find them.

So, in short nothing to fix in popcorn-desktop. Also, since dev build 293 PT display multiple subtitles results per language.
