### ISSUE TITLE
Valdez is coming. Please synchronize the subtitles with the spoken language.

### ISSUE THREAD

**Issue by aucancahuel** [popcorntime/popcorntime#1115]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
PT get subtitles from opensubtitles.org.
You need to fix the subtitle file yourself and then upload it on opensubtiles so PT will find it
