### ISSUE TITLE
Request: Movie MPAA ratings or similar

### ISSUE THREAD

**Issue by DregonX2** [popcorntime/popcorntime#1120]
Operating System Version:
<all>

Popcorn Time Version:
<3.110>

Just wondering if there's ever been any thought given to adding MPAA ratings from a site like https://www.filmratings.com to each movie's description. It would be helpful for families looking for age-appropriate movies.

**Comment by Persei08** [comment]
popcorn-api already have age certification rating for movies (not sure how it's called), but it isn't displayed in PT.

It could be done, someone have already done it in a patched version.

You need the dev build 279 (which you can find on [this mega folder](https://mega.nz/#F!i11j1bRJ!Yqdn7vWL4lQ1tpcKJ5kQjQ!LkciUaJZ)) and to apply [this patch](www88.zippyshare.com/v/5sqqVLNk/file.html) into the PT install dir.

Hopefully this patch will be applied here soon

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
