### ISSUE TITLE
Strategy for Legal Challenges

### ISSUE THREAD

**Issue by casey** [popcorntime/popcorntime#1121]
_Sorry for posting this as an issue. This is more of a high-level strategic suggestion, but I couldn't find an appropriate place to post it, given that the forums are down._

_I put a better written and formatted copy of this post on [my blog](https://rodarmor.com/blog/popcorn-time-should-become-a-browser/)._

_I am not a lawyer. This is not legal advice._

It seems that Popcorn Time-style apps are vulnerable to legal action by rights holders. For example:

- The recent suspension of popcorntime.sh: https://torrentfreak.com/registrar-suspends-popcorn-time-domain-name-following-complaint-200121/

- A prison sentence handed down to a Danish operator of a site which merely provided information about how to use Popcorn Time: https://torrentfreak.com/operator-of-popcorn-time-info-site-is-liable-for-piracy-supreme-court-rules-200115/

This may seem unfair to those of us who know that Popcorn Time's servers don't host any infringing content, but it is simply a reality of the world we live in.

However, it is interesting to note that although web browsers can be used in exactly the same way as Popcorn Time, namely displaying search results to the user and allowing them to stream video content from those search results, web browsers have not faced serious legal challenges.

From my research (and I would really appreciate if someone with an intellectual property background could give more details on this) I think that the salient factors differentiating web browsers from Popcorn Time are the following:

1. After a web browser is opened, the user must supply the URL of the site they wish to visit. In Popcorn Time's case, after the application is opened, it immediately displays a selection of infringing content. This greatly weaken's Popcorn Time's claims against contributory copyright infringement.

2. Web browsers have substantial non-infringing uses. "Substantial non-infringing use" is jargon for a United States legal test which prevents the creator or purveyor of a piece of technology from being liable for its use in infringement by users if there are "substantial non-infringing uses". A good illustration of this principle is from _Sony Corp. of America v. Universal City Studios, Inc._:

	https://en.wikipedia.org/wiki/Sony_Corp._of_America_v._Universal_City_Studios,_Inc.

	However, in Popcorn Time's case, I believe it would be hard to argue that there are substantial non-infringing uses of the application, given that default search results overwhelmingly contain copyrighted content.

Fortunately, I believe that Popcorn Time can make a small number of changes that would allow it to withstand legal aggression:

- Add a URL to the top of the GUI
- When opening the app for the first time, the URL bar is empty and there are no default search results
- The user must put the URL of the API backend of their choice into the URL bar, at which point the application retrieves search results from the API backend and populates the search results
- For a good user experience, when the user re-opens the app later, the URL bar stays populated with the URL of the last API that they used

Doing this would fix `#1`. Upon first opening popcorn time, no results are displayed and the user must they themselves enter the URL of the search index they wish to use. Popcorn Time, legally speaking, would become much more like a web browser, which is a class of app which is generally well understood to not be legally liable for any possible infringements committed by its users.

Additionally, I would suggest creating a default search/API backend which focuses exclusively on free, non-infringing, user-created content.

Doing this would fix `#2`. A search index populated with non-infringing content may well allow Popcorn Time to pass the "substantial non-infringing uses" test. And, I suspect that it may be useful and popular in its own right.

Additionally, I would suggest that the developers and distributors of the app distance themselves from the operation of backends other than the above-mentioned single official backend that focuses on free content. Ideally, a large number of third-party and community-run backends will appear, running the exiting API software created by the developers.

**Comment by SrPatinhas** [comment]
@casey That already exists, it's https://github.com/butterproject/butter-desktop, the old devs wanted to create a free content platform, and so, the Devs created ButteProject, that is the base of this project

**Comment by casey** [comment]
@SrPatinhas Thanks for the pointer! I didn't know how The Butter Project relates to Popcorn Time. I think my suggestion is still sound. The Butter Project is dead, and, I believe, never implemented pluggable backends.

**Comment by VitorVRS** [comment]
@casey you can plug providers (backends) on Butter, Popcorn have the same source code, but its shipped with it's own providers (Movie, Show, Anime, etc).
Every once in a while, the Popcorn team take the new code from Butter.
To be short, I agree with your suggestion, however that's the current state of Butter.
