### ISSUE TITLE
Messiah series missing

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1122]
Messiah series is missing https://www.imdb.com/title/tt7671598/

![Screenshot_1](https://user-images.githubusercontent.com/18757054/73075125-83d80400-3ebb-11ea-89c3-a356f1f77b64.png)

**Comment by Persei08** [comment]
Issue should be reported on [popcorn-api repo](https://github.com/popcorn-official/popcorn-api)
