### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by HandThigh** [popcorntime/popcorntime#1124]
Operating System Version:

Windows 10
Popcorn Time Version:

3.10
Download date:

27/01/2020

I Have a question
When i click on the button "Watch Now" it says downloading
Is popcorn time downloading the movie on to my PC? 
If it is downloading onto my PC how do i find it and delete the movie file

**Comment by Persei08** [comment]
Yes, PT download the movie, it save it in the 'cache' directory which is just a folder in the temp folders of your OS (by default, but you can change it to somewhere else so your OS don't remove it).

You can find the path of this cahce directory, in PT settings; Tick "advanced settings" checkbox, and look at cache directory section.

By default PT delete the downloaded files when you close it

**Comment by HandThigh** [comment]
Ok thank you!
