### ISSUE TITLE
Impractical Jokers

### ISSUE THREAD

**Issue by MaxSancho** [popcorntime/popcorntime#1125]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
2018

90% of Impractical Jokers' episodes in the app do not work

**Comment by Persei08** [comment]
I just tested 3 random ones: 
1 is working and the 2 other are dead.

My guess is 90% are dead, but I should need to test more than 3 to be sure.
Can you provide a list of 4-5 episodes you have issue with ?

**Comment by Persei08** [comment]
Closing because issue is related to dead torrents, so nothing to fix in popcorn-desktop.
Correct me if i'm wrong
