### ISSUE TITLE
Progress bar and mouse pointer appear constantly

### ISSUE THREAD

**Issue by DejanPerovic** [popcorntime/popcorntime#1126]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
2019

#### Actual Behaviour
The progress bar and mouse pointer appear constantly sometimes on every few seconds.

**Comment by Persei08** [comment]
Do you use a laser mouse ? if yes, does it still occur if you disable the mouse ?

**Comment by Persei08** [comment]
Closing because duplicate of #992 or #900 .
Correct me if I'm wrong

**Comment by DejanPerovic** [comment]
> Do you use a laser mouse ? if yes, does it still occur if you disable the mouse ?

I have optical and laser mouse. The problem always appears, turned off or turned on. On laptop is all the same only with a touchpad without a mouse.



> Closing because duplicate of #992 or #900 .
> Correct me if I'm wrong

Yes, it's duplicate. How I see this is an old question and has not been fixed.

**Comment by Persei08** [comment]
Yes, #992 and #900 are still open and not fixed.
