### ISSUE TITLE
Cannot change cache dir on arch linux (popcorn 0.3.10)

### ISSUE THREAD

**Issue by lyuben-todorov** [popcorntime/popcorntime#1131]
This issue has been mentioned before. Going into popcorn settings, clicking on Cache Directory and selecting a different one results in no changes. My /tmp is in memory and limited to 2gb. This means popcorn will crash anytime I watch an HD movie over 2gb. What is even worse, it hogs my /tmp directory and prevents other software from properly working, such as my package manager because it needs a build folder.

Editing this line and hardcoding it to another location works and movies are properly downloaded in the directory I picked:

https://github.com/popcorn-official/popcorn-desktop/blob/987e8fa1b60259168061fa5541ff015928ca3e6d/src/app/settings.js#L172

**Comment by Persei08** [comment]
What version are you using, I can't reproduce this issue with 0.3.10 on Ubuntu 18.04.

Which aur package are you using, plz provide the link so we can check the pkgbuild. and eventually ping the maintainer.

**Comment by lyuben-todorov** [comment]
I'm sorry, I no longer have access to the computer I reproduced this on and I also cannot reproduce it on my own computer (same kernel version). It was using yay and the package was [this](https://aur.archlinux.org/packages/popcorntime/). This isn't helpful so I'm closing this issue unless someone else reopens it.
