### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by kimt72** [popcorntime/popcorntime#1133]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour
<!-- What does the app do
every movie i play keeps freezing what can i do??

**Comment by Persei08** [comment]
Great.
Can't reproduce. :/

**Comment by Persei08** [comment]
Please provide details describing your issue, else I close them

**Comment by kimt72** [comment]
every movie i click on to play as soon as the movie starts it just freezes
up for a few seconds then play again for a few seconds then freeze again
thats the entire movie i tried playing other movies and they all do that
same thing.

**Comment by Persei08** [comment]
Which movies, which quality. 

Provides some specific examples so we can check, because when if I choose a random one everything work as expected.
