### ISSUE TITLE
New CI build

### ISSUE THREAD

**Issue by longnd** [popcorntime/popcorntime#1134]
Could you trigger a new CI build? The last build was 2 months ago and there have been a lot of fixes since then.
Thanks.

**Comment by Persei08** [comment]
Why you don't build it yourself ?

>
    yarn config set yarn-offline-mirror ./node_modules/
    yarn install --ignore-engines
    yarn build
    yarn gulp dist --platforms=win64

platforms values can be: all, win32, win64, osx64, linux32, linux64

Then you will find packages in dist folder

**Comment by longnd** [comment]
@Persei08 I tried to follow that instruction but got many errors which I didn't know how to resolve, and I believe many normal users don't know how to build it themself.
anw, thank you for the guidance.

**Comment by team-pct** [comment]
Check build #380
