### ISSUE TITLE
Cover Missing

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1135]
Some movies are missing covers

![Screenshot_2](https://user-images.githubusercontent.com/18757054/74347076-d3219e00-4db0-11ea-9890-dc276a5888ab.png)

**Comment by Persei08** [comment]
Hi... it's long time!

It's [your 33rd issues here](https://github.com/popcorn-official/popcorn-desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AGKid94+) and you still don't follow the issue template or doing basic checks like checking console logs (F12 key > "console" tab) or API responses.  

You want other to waste time on your issues, but you don't even waste time to check basic things on your side. You were new i could understand but it's your 33rd issues here.
 :pensive:

---

PT works as expected here. popcorn-api don't have posters for those movies, so PT don't display cover.

Here the API responses for the first 3 ones in your screenshot:
- [Shiraz: A Romance of India](https://movies-v2.api-fetch.website/movie/tt0019374)
- [Sweeney Killing Sweeney](https://movies-v2.api-fetch.website/movie/tt7477820)
- [John Travolto: The Face with Two Left Feet](https://movies-v2.api-fetch.website/movie/tt0123927)

Check the PT console, there is no errors.

See you next month for another non-issue :|

**Comment by Persei08** [comment]
Ok, I close this issue since it isn't related to desktop client.

If you want you can open an issue to https://github.com/popcorn-official/popcorn-api to see why there isn't covers for those movies
