### ISSUE TITLE
Stream subtitles to chromecast

### ISSUE THREAD

**Issue by blackshot** [popcorntime/popcorntime#1136]
Operating System Version:

macOS catalina 10.15.2 (it also happens with my windows 10 pc)

Popcorn Time Version:

0.3.10-0 Beta (HEAD - 84a68ce6)

Download date:

Today, it is a fresh install (first time on this machine)

#### Expected Behaviour

after Selected the default subtitle language i expected to have subtitles on chromecast

#### Actual Behaviour

Just streams audio and video

#### Steps to reproduce the behaviour

just start popcorn time, select any movie then select the chromecast device and Watch it now.

i attach all console logs: https://pastebin.com/CnMBtbaj

as log shows, it finds the subtitles but doesn't stream them 
`Subtitle download url: http://dl.opensubtitles.org/en/download/src-api/vrf-19e70c5b/sid-OExoXpzWVg2jjqhRxVH8jRXxLV4/filead/1956667631`

**Comment by Persei08** [comment]
PR #609 fixed it. Dev builds >= 293 (November 2018) have it

**Comment by blackshot** [comment]
alright it is fixed :) thanks for replying. also is there any way to fix subtitle syncing like with butter player but in chromecast?

**Comment by Persei08** [comment]
> also is there any way to fix subtitle syncing like with butter player but in chromecast?

No such feature in PT. I don't even know if it's possible with chromecast
