### ISSUE TITLE
No movies are shown

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1138]
Operating System Version:
Windows 10 Pro 64bit

Popcorn Time Version:
3.10

Download date:
/

#### Expected Behaviour
To show movies 
...

#### Actual Behaviour
No movies are shown
...

![Screenshot_2](https://user-images.githubusercontent.com/18757054/75098210-bc025d80-55b3-11ea-947c-10a35b185b85.png)

**Comment by team-pct** [comment]
Cant Reproduce can you try last BuilD?
