### ISSUE TITLE
Can't run Popcorn Time on Cortex-A7 device

### ISSUE THREAD

**Issue by madezent** [popcorntime/popcorntime#114]
Operating System Version:
Linux 3.4.108-lime armv71 Debian Jessie

Popcorn Time Version:
Up-to-date with origin/development in git right now.
#### Expected Behaviour

I expect

> grunt start

to succeed after running

> make_popcorn.sh
#### Actual Behaviour

grunt says the OS is not supported and exits.

Log for the build: http://paste.debian.net/417724/

Log for starting: http://paste.debian.net/417725/

If you can't give a fix, could you point me where to start to fix this?

**Comment by ChrisAlderson** [comment]
NWJS does not support the ARMv7 platform, so we cannot fix this issue
