### ISSUE TITLE
Subtitle list won't show up when hovering the balloon icon

### ISSUE THREAD

**Issue by renamed** [popcorntime/popcorntime#1141]
Operating System Version:
Windows 10 

Popcorn Time Version:
0.3.10-0

Download date:
2020-02-29

#### Expected Behaviour
I should see a list of expected Subtitles when I hover the corresponding ballon icon. 
...

#### Actual Behaviour
I can only see two options when I hover the subttle balloon. This happens to any movie I try to watch.
![image](https://user-images.githubusercontent.com/2809309/75716981-08822300-5caf-11ea-9b0c-950d877a4ac7.png)

#### Steps to reproduce the behaviour
It happened twice to me, when I stopped watching the movie, turned off the computer and came back. Then, I'm unable to watch any other movie with subtitles.

When I inspect the console, this error appears:
![image](https://user-images.githubusercontent.com/2809309/75717125-497a3780-5caf-11ea-8a48-9cfdb127d7d1.png)

**Comment by Persei08** [comment]
Look like an opensubtitle.org API issue to me. It happen sometimes, I think it is just the XML which is bad formatted
