### ISSUE TITLE
SSL certificate legitimacy issues

### ISSUE THREAD

**Issue by migralito** [popcorntime/popcorntime#1143]
Operating System Version: MacOS 10.15.3

Popcorn Time Version: 0.3.10

Download date: 2020-03-12

#### Expected Behaviour
Install the app throw homebrew

#### Actual Behaviour
Using brew to install reject downloading the app as curl fails to validate legitimacy of certificate. In one hand the cert is expired and on the other hand it goes for get.popcorntime.sh instead of mirror03.popcortime.sh

#### Steps to reproduce the behaviour
➜  ~ brew cask install https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb
==> Downloading https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb.
==> Downloading https://mirror03.popcorntime.sh/repo/build/Popcorn-Time-0.3.10-Mac.zip
##O=#  #
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask 'popcorn-time' with message: Download failed: https://mirror03.popcorntime.sh/repo/build/Popcorn-Time-0.3.10-Mac.zip

**Comment by team-pct** [comment]
Fixed
