### ISSUE TITLE
Popcorn Time no thumbnails showed on Linux 64 bits

### ISSUE THREAD

**Issue by Marcostux** [popcorntime/popcorntime#115]
Operating System Version:

Linux Ubuntu 64 bits
Popcorn Time Version:

0.3.9-0 https://k60.kn3.net/7/6/9/4/A/F/2DC.png
Download date:

03/15/2016
#### Expected Behaviour

...Show the thumbnails 
#### Actual Behaviour

...No show  thumbnails 
https://k61.kn3.net/E/B/C/A/9/7/5AB.png
#### Steps to repoduce the behaviour

1. ...start the program, no more
2. ...
3. ...

**Comment by micopiira** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/9 already here..

**Comment by kiakeu** [comment]
I have the same issue, but it only affects my laptops not my desktop (all running linux x64)

**Comment by sashoa** [comment]
Same on Arch Linux.

**Comment by esarandon** [comment]
same thing on xfce 64bits

**Comment by Aqa-Ib** [comment]
Same on debian sid.

**Comment by n4rf** [comment]
Same behaviour on Fedora 23 x86_64 runing Kernel 4.4.9-300 KDE5/Plasma on Asus N53SV, Intel core i5, and Nvidia 540M with Bumblebee (Formerly Optimus) technology laptop.

**Comment by Clavos-Studios** [comment]
Same on Linux Ubuntu 64 bits :(

**Comment by ibsenleo** [comment]
Same here on Ubuntu gnome. 16.04 LTS 64bits
I have opened DevTools on first load and says this for each thumbnail. 98 errors:

This is just one of them :S and loads perfect on browser so is something about the compilation of PCT.
    GET https://walter.trakt.us/images/movies/000/138/212/posters/medium/2f06a4b846.jpg net::ERR_SSL_PROTOCOL_ERROR

Could be some issue with chromium version? i read somewhere about some bug on chromium and SSL but dont remember. 

Any solution?

**Comment by ghost** [comment]
Same here Xubuntu 16.04 64 bits

**Comment by ViniciusGiroto** [comment]
Same on Arch linux
