### ISSUE TITLE
Remove the blinking VPN icon

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1153]
Operating System Version:
Windows 10 Pro 64bit 1909

Popcorn Time Version:
0.3.10 

Download date:
/

#### Expected Behaviour
To have a normal gray VPN icon

#### Actual Behaviour
The VPN icon is red and keeps blinking

#### Steps to reproduce the behaviour
Change the VPN icon to a normal gray one

![Screenshot_1](https://user-images.githubusercontent.com/18757054/76697766-a0164700-669b-11ea-87be-db6b6f29de45.png)

**Comment by Persei08** [comment]
Seem after all, you can fill the issue template when you want :)

Personally I don't care the icon being red, but the fact it is blinking annoy me a bit

**Comment by diwu1989** [comment]
I find it annoying that Popcorn time tries to push a specific VPN on me.
I already run a system wide IPSec VPN, but the app still thinks I'm insecure just because I'm not using the in-app VPN.

Can we add an advanced option to  just straight up hide this icon altogether?

**Comment by Speekless** [comment]
+1

**Comment by jorg2123** [comment]
go to the advance setting. Under the connection, you will see "Enable VPN". uncheck that. Done

**Comment by GKid94** [comment]
> go to the advance setting. Under the connection, you will see "Enable VPN". uncheck that. Done

I don't have that option

![Screenshot_1](https://user-images.githubusercontent.com/18757054/76825975-97e51580-681b-11ea-9cb4-3b7d4d9360de.png)

**Comment by jorg2123** [comment]
I am on Mac and using the latest version. 
<img width="735" alt="Screen Shot 2020-03-17 at 1 51 41 AM" src="https://user-images.githubusercontent.com/62276895/76826277-74f23b80-67f2-11ea-8fdc-625fd291adb9.png">

**Comment by creativeosmose** [comment]
Option is not present on the Windows release.

**Comment by team-pct** [comment]
Enable Advanced Settings you will see it

**Comment by creativeosmose** [comment]
Already with Advanced Settings enabled
![image](https://user-images.githubusercontent.com/17967961/76876868-df4ac080-6872-11ea-81d5-49302428326b.png)

**Comment by douglascamata** [comment]
Installed the Windows release and was able to disable VPN

**Comment by creativeosmose** [comment]
Strange. Which version?
I tried on 2 different PCs. 
Tried 32 & 64 bits on both PCs.
Tried with clean install.
Still have the issue.
I’m using build #387.

**Comment by Persei08** [comment]
This is fixed in v0.4.0

**Comment by digitigradeit** [comment]
> I find it annoying that Popcorn time tries to push a specific VPN on me. I already run a system wide IPSec VPN, but the app still thinks I'm insecure just because I'm not using the in-app VPN.
> 
> Can we add an advanced option to just straight up hide this icon altogether?

I know right? Like if you're gonna have ads, at least let pet me pay you like $5 to remove the ads... don't force some VPN service with questionable logging and retention policy under the guise off a secure vpn service (which its not) with no option to disable it. especialy when I am using a perfectly fine vpn service already which your software also doesn't detect. GIRL.
