### ISSUE TITLE
Resize thumbnails slider

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1155]
Add a slider to resize the thumbnails

**Comment by team-pct** [comment]
Your PR are welcome

**Comment by GKid94** [comment]
> Your PR are welcome

PR?

**Comment by team-pct** [comment]
If you wanna contribute you are welcome to do so , as for now we do not have the ressources to add new features

**Comment by GKid94** [comment]
> If you wanna contribute you are welcome to do so , as for now we do not have the ressources to add new features

You don't have to do it now, it's just a suggestion and if you like it then you can add it whenever you want

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
