### ISSUE TITLE
Add go to cache folder

### ISSUE THREAD

**Issue by Speekless** [popcorntime/popcorntime#1156]
Operating System Version: OS X 10.13.6
Popcorn Time Version: 4.0
Download date: March 17th 2020

Under Settings, the button for going to the cache directory has been removed. This was a really useful feature and imo it should be added again.

**Comment by diwu1989** [comment]
This was useful for me too to figure out what kind of files are stored temporarily by the app.

**Comment by ze0ss** [comment]
+1

**Comment by stavr0cks** [comment]
You can still go to the directory if you click on the path textbox.
