### ISSUE TITLE
Interface very slow and unresponsive

### ISSUE THREAD

**Issue by Speekless** [popcorntime/popcorntime#1157]
Operating System Version: OS X 10.13.6
Popcorn Time Version: 4.0
Download date: March 17th 2020

The interface is incredibly slow and unresponsive after the 4.0 update. I run Popcorn time on a MBP 2010, the app is basically unusable as is. I don't know what changes were made, but this indicates a deeper-lying problem to me, which should be taken a serious look.

Besides, I didn't even have the choice to not auto-update. There are alls sorts of issues, this just being one of them, and I see no improvements whatsoever. I'm not quick to judge, but this should never have been released! Really gutted by this update.

**Comment by jorg2123** [comment]
yep, got the same issues. the main page doesn't load up. The bookmark icon is gone. downgraded to 0.3.10. happy camper

**Comment by Ioan-Popovici** [comment]
I looked at the code changes, everything checks out. This is the real thing.
The bookmark icon has been replaced with a favorite tab.

I have zero performance issues, on the contrary it is much faster for me.

Running macOSX Catalina 

Thank you so much @team-pct for this unexpected release!
I like the 'Love in the Time of Corona' release 🥇

**Comment by esarbe** [comment]
Got the same issue here; interface is very slow and unresponsive. Fan is running all the time, even if just browsing.

Platform: GNU/Linux x86_64
Version: 0.4.0

**Comment by ze0ss** [comment]
Yeah, interface is slow and clunky now, since 0.4.0, looks so broken, and the download process isn't the same anymore, can't really make out if the content is downloaded or not, and the subtitle and audio language selector just sucks, basically invisible, and broken.
Considering downgrading to 0.3.0 :/

**Comment by anthofo** [comment]
Same, the interface freeze for at least 2 min when I launch it, and the cpu skyrock at 100%.
1/2 times the video is dowloading but doesn't play. When the video plays 1/2 there are no buttons at all, just the video, can't pause the etc.
I go back to the previous version.

**Comment by Speekless** [comment]
@team-pct Before hearting the one positive comment on this page, you should probably be taking a look at the other ones. Sorry for saying it like it is, but there's absolutely nothing to be proud of in this release.

**Comment by Ioan-Popovici** [comment]
> @team-pct Before hearting the one positive comment on this page, you should probably be taking a look at the other ones. Sorry for saying it like it is, but there's absolutely nothing to be proud of in this release.

You can always go back to the old version. There’s no need to bash someone who does this for free. It would be more productive to submit a pull request that fixes the issue...

**Comment by Speekless** [comment]
I'm not bashing. I'm just saying before releasing anything make sure it works for users! No need to take it personally. And to be perfectly honest, again I don't mean to be rude, but you'd be better off doing nothing if this is the work you deliver for free.

I won't venture into a pull request because I can't fix this. I created this as an issue, because that's what is is. Team popcorn time did the work, messed it up. Then fix it as well.

**Comment by esarbe** [comment]
Apparently this issue is not present on all systems. @team-pct Can we provide some measurements to get to the root of this?

**Comment by Ioan-Popovici** [comment]
> I'm not bashing. I'm just saying before releasing anything make sure it works for users! No need to take it personally. And to be perfectly honest, again I don't mean to be rude, but you'd be better off doing nothing if this is the work you deliver for free.
> 
> I won't venture into a pull request because I can't fix this. I created this as an issue, because that's what is is. Team popcorn time did the work, messed it up. Then fix it as well.

They actually don’t need to fix anything, or make sure that it works. This is probably one guy who does this in his free time and he owes you or anyone else exactly nothing.
Also he probably doesn’t have the resources or time to test all platforms.

Clearly you haven’t contributed even one line of code in any open source community, because otherwise you would understand this. Don’t take it personally...

**Comment by Ioan-Popovici** [comment]
> I'm not bashing. I'm just saying before releasing anything make sure it works for users! No need to take it personally. And to be perfectly honest, again I don't mean to be rude, but you'd be better off doing nothing if this is the work you deliver for free.
> 
> I won't venture into a pull request because I can't fix this. I created this as an issue, because that's what is is. Team popcorn time did the work, messed it up. Then fix it as well.

They actually don’t need to fix anything, or make sure that it works. This is probably one guy who does this in his free time and he owes you or anyone else exactly nothing. It’s best effort. If you don’t like it fix it yourself, or wait for a fix that will come or not.
Also he probably doesn’t have the resources or time to test all platforms.

Clearly you haven’t contributed even one line of code in any open source community, because otherwise you would understand this. Don’t take it personally...

**Comment by Speekless** [comment]
Isn't that a bit easy? First we break everything, and then we don't need to fix it. You're right, they don't. What they however do need to, when contributing to an open-source project, is make sure these changes work. End of discussion? This should be about getting the changes fixed.

**Comment by Ioan-Popovici** [comment]
> You're right, they don't. What they however do need to, when contributing to an open-source project, is make sure these changes work.

They work, just not for you...

**Comment by Speekless** [comment]
Can you please stop being so defensive? Have you seen the number of comments and threads in here that have the same issues?!?! Now let's please get back to that!

**Comment by Ioan-Popovici** [comment]
> Can you please stop being so defensive? Have you seen the number of comments and threads in here that have the same issues?!?! Now let's please get back to that!

I think the issue is pretty clear, it doesn’t work for everyone.

On macOS catalina last version there are no noticeable issues

**Comment by team-pct** [comment]
Should be Faster running ( disabling Update Seeding and Seeding on start ) 
 https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/394
