### ISSUE TITLE
Bookmark Icon (Heart) is gone

### ISSUE THREAD

**Issue by jorg2123** [popcorntime/popcorntime#1158]
With the new version, I can't find the icon or bookmarks anymore? I am on OSX 13.4
looking for some assistance.

<img width="248" alt="Screen Shot 2020-03-17 at 1 57 40 AM" src="https://user-images.githubusercontent.com/62276895/76826379-baaf0400-67f2-11ea-8df9-0a4009c30b8f.png">

**Comment by Ioan-Popovici** [comment]
Check the new favorite tab, the heart next to watchlist was confusing as hell

**Comment by team-pct** [comment]
Its a TAB now
