### ISSUE TITLE
Failed to stream to MPC-HC

### ISSUE THREAD

**Issue by Incarceron** [popcorntime/popcorntime#116]
Operating System Version:

Windows 8.1
Popcorn Time Version:

0.3.9 "There's nothing on TV" Beta - (69375736)
Download date:

3/23/2016
#### Expected Behaviour

Stream The Flash Season 2 Episode 1 to MPC-HC
#### Actual Behaviour

MPC-HC begins to load the stream then outputs "Failed to render file." in the status bar.
#### Steps to repoduce the behaviour

1. ... Change video player to MPC-HC 64bit
2. ...Open MPC-HC 64bit
3. ...Attempt to stream show to MPC-HC 64bit
# 

I should also mention I'm running CCCP codecs with the addition of madVR.

**Comment by itzViking** [comment]
Hi,

I had a similar issue with Popcorn Time + MPC-HC 64bit + madVR.

In my case what happened is that Popcorn Time tried to run the 32bit version of MPC-HC, so a quick workaround was to replace the binary in the 32bit folder with the binary in the 64bit folder.

So I copied the binary from my 64bit folder:
C:\Program Files (x86)\LAV Filters\x64\mpc-hc\mpc-hc.exe

And replaced it here:
C:\Program Files (x86)\LAV Filters\x86\mpc-hc\mpc-hc.exe

Seems replacing the binary tricks Popcorn Time into running the 64bit MPC-HC with madVR and all your settings working properly.

A good fix for that would be to allow users to select the external player, or the path at least.
