### ISSUE TITLE
Favorites button missing

### ISSUE THREAD

**Issue by RZMiRaN** [popcorntime/popcorntime#1160]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.0-0

Download date: a few weeks ago, updated to version 0.4 just now

#### Expected Behaviour
Before updating, there was a heart icon (favorites button) in the top right
...

#### Actual Behaviour
That button is gone
![Screenshot_12](https://user-images.githubusercontent.com/11421315/76877303-3b6a1080-6884-11ea-9657-84a51b765305.png)

**Comment by team-pct** [comment]
Its a TAB NOW 
<img width="434" alt="Capture d’écran 2020-03-17 à 17 21 13" src="https://user-images.githubusercontent.com/17107280/76877467-b8d95500-6873-11ea-9913-227f36c2b7c7.png">

**Comment by skfd** [comment]
I would also add that favorites are not migrated from previous version, that's not good... Is it by design?
