### ISSUE TITLE
Subtitles' settings aren't apply

### ISSUE THREAD

**Issue by thomaSS36** [popcorntime/popcorntime#1162]
Operating System Version:
Windows 8

Popcorn Time Version:
0.4.0

Download date:
2020-03-17

#### Expected Behaviour
change subtitles' settings should be applied (Font, decoration, size and color)
...

#### Actual Behaviour
Any subtitles' settings that I change are apply when I run a video. It happens with the font, decoration, size en color
...

#### Steps to reproduce the behaviour
1. change subtitles' settings
2. run a video

**Comment by douglascamata** [comment]
This doesn't seem to be affecting tv series.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
