### ISSUE TITLE
Download progress bar doesn't show progress in GB/MB anymore.

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1166]
Operating System Version: windows 10 x64
Popcorn Time Version: 0.4.0
Download date: March 17, 2020
#### Expected Behaviour
<It should display the progress of the movie/series currently being downloaded, as in version 0.3.0. >
...

#### Actual Behaviour
<It just bugs now, the bar is stuck at 0%, although the content is downloaded sometime, but it is impossible to know if it's finished or not.>
...

#### Steps to reproduce the behaviour:

1. Choose any movie/series.
2. Click play, on either player.
3. You see the progress bar, which doesn't move at all.

![screenshot](https://user-images.githubusercontent.com/56572179/76922726-925cfd80-68f7-11ea-9a3f-d571a1b956b8.jpeg)

**Comment by Speekless** [comment]
In my case the download bar isn't showing the progress, it just fills up and restarts again until the movie starts.

**Comment by tassia-ferreira** [comment]
This is also happening on macos catalina.

**Comment by dutchy1001** [comment]
it would be nice to see the progress bar back with the % GB/MB's showing. I often wait to start watching to avoid buffering which is now a guess...

**Comment by reddo** [comment]
> it would be nice to see the progress bar back with the % GB/MB's showing. I often wait to start watching to avoid buffering which is now a guess...

You can also use uTorrent Web.

**Comment by team-pct** [comment]
Fixed

**Comment by ze0ss** [comment]
Thanks
