### ISSUE TITLE
Magnet links show as false after update and no way to disable VPN if I already have one.

### ISSUE THREAD

**Issue by jackpinesavage67** [popcorntime/popcorntime#1167]
Operating System Version:
windows 10 64

Popcorn Time Version:
was running 3.1 until update to 4.0

Download date:
March 17/20

#### Expected Behaviour
allow me to use my own paid for vpn.
...

#### Actual Behaviour
It now wants to continuously update to 4.0 as there is no way to disable automatic updates, I disabled vpn in settings, yet still get that annoying blinking lock symbol in title bar/top menu
...

#### Steps to reproduce the behaviour

1. ... just install 3.1 - works great as it was without being continuously prompted about using a vpn
2. ...
3. ...

**Comment by Persei08** [comment]
Plz edit your ticket, you talk about different issues in one ticket when it should be one ticket per issue.

**Comment by jackpinesavage67** [comment]
Sorry Persei08, sometimes I get a little ahead of myself. When I took the upgrade to 4.0, I noticed that the magnet links (when you rolled the mouse over them) said "false" and I was unable to download/view the torrent.

**Comment by firstroad** [comment]
There is an option you can uncheck to disable the blinking VPN icon: Settings/Connection/Enable VPN. Restart when you are done.
magnet links showing as false doesn't help me a lot, maybe a screenshot would be helpful

**Comment by Persei08** [comment]
@jackpinesavage67 no problem, but can you edit your ticket so it focus on only one issue ?.. and then you can report other issues separately. 
Like @firstroad is saying, there is "Enable VPN" option to untick for hiding the padlock icon... but this isn't doing it instally, it require to switch tab... but I'll send a fix forit to be instantly

**Comment by Persei08** [comment]
My sentence seem weird, excuse my english :D

**Comment by Persei08** [comment]
Ok, I close the issue. Let's said it was related to "Enable VPN" option

**Comment by jackpinesavage67** [comment]
firstroad, I did do that, went into setting and found the check box and unchecked it, and this did fix that issue, but when I went to another movie title after that, the issue was back even after unchecking that box earlier. I will update to 4.0 again and will grab some screen captures. Thank you.

**Comment by jackpinesavage67** [comment]
It would appear that it does not like Nordvpn
![vpn not enabled](https://user-images.githubusercontent.com/29686751/77019584-9feda400-6946-11ea-9f46-f42b2088df70.png)
![connection not secure](https://user-images.githubusercontent.com/29686751/77019585-a0863a80-6946-11ea-82df-38959e391a86.png)
![health false and connection not secure](https://user-images.githubusercontent.com/29686751/77019586-a11ed100-6946-11ea-803a-a187695fefcd.png)
