### ISSUE TITLE
Shuffle or randomize button

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1170]
Operating System Version:

linux
Popcorn Time Version:

Download date:

#### Expected Behaviour
i suppose there be a feature to have a randomly generated playlist of say tv shows or movies like you do on a regular old tv. then, we could maybe expand that into like genre wise playlists that a user could create on their own.
then, maybe a separate tab skin to "channels" where one could find those playlists and shuffle through them

**Comment by test2a** [comment]
Was this implemented? Not implemented ?

**Comment by Persei08** [comment]
No, Man PCT will not host a service to share users playlists. They will better use an existing one like trakt.tv list, but it's seem really out of scope for me now.

if I understand well, the feature you request is kinda have PCT working like a TV channel (or multiple thematique Tv channels), Having multiple movies playing one after another automatically. 
There are different ways, I can think it could be implemented, it could use trakt.tv list or better a "playlist/queue" tab with ability to import lists from trakt.tv and other similar sites, ... but it's some works and is a bit out of scope for now... unless someone come and serve the thing on a silver platter.

I reopen your suggestion and tag it with "feature" label. Will see if some people are interested.

**Comment by test2a** [comment]
@Persei08 noooooo... i am not asking about hosting playlists anywhere. neither i am asking for trakt or similar. think more simple than that. 
when we open PCT, we are shown a bunch of movies. i am asking would it be possible to open just these movies. not going outside the window, no third party involvement. Dont we already have torrent files of the movies from say yts api? then pipe that to the video player.

 in future we could open genre tab and start from there.

**Comment by kiriles90** [comment]
@test2a I'm sorry but can you explain what you actually suggest again?

>  we open PCT, we are shown a bunch of movies. i am asking would it be possible to open just these movies. not going outside the window, no third party involvement. Dont we already have torrent files of the movies from say yts api? then pipe that to the video player.
in future we could open genre tab and start from there.

This makes no sense to me.

**Comment by test2a** [comment]
https://yts.mx/api/v2/list_movies.json

i am assuming we are using APIs similar to this if not this one exactly. Look how it shows movies and its associated torrent files. My suggestion is to load up all these torrent files and play them one after the other. we already have all this data. shuffling would come later, From lets say we select  a random "ID" and the api would return the associated torrent file.


example.

this api lists ID : 22745 
movie:  "The Disrupted"
torrent: URL for 720p and URL for 1080p

and 
ID : 22743
movie:  "Bruce Springsteen's Letter to You"
torrent: URL for 720p and URL for 1080p

Take these torrent  files and play them one after the other

**Comment by kiriles90** [comment]
Load up what torrent files and play them one after the other? 22000 movies? Also the API response is truncated to 50 items by YTS and Popcorn Time's API too. So realistically to not make a million calls you will have a button that always loads the first 50 movies on the list (any list you are on) and play's them one after the other? Even if behind them are 22000 more that were never taken into account? Why??

**Comment by test2a** [comment]
https://yts.mx/api
 you are right there. i am not asking to play 22k movies. just the default 20 loaded by the api as you are aware. or say 3 or 4. there is a limit parameter between 1 and 50 as described in this page.  we can pick 3 and once the button is pressed, only latest 3 are given by api which the software plays. thats all.

**Comment by kiriles90** [comment]
Hmm now I think I got the idea. So a button that plays the last X movies in whatever list you are on. Not sure how useful that would be but it wouldnt be hard to implement in code.

What Popcorn Time API returns btw is something like https://movies-v2.api-fetch.sh/movies/1 and documentation at https://popcorntime.api-docs.io/

**Comment by test2a** [comment]
yes. so if i am in movies> horror, i would click button and just like on tv, movies would start playing because people usually dont know what to watch. the "TV" model works for a lot of people who now go to netflix to binge watch stuff one after the other. Doing this would bring that functionality here as well. 
essentially we are taking the "choice" out of their hands which is what a lot of people want believe it or not. programmed by tv and all that. :-)

**Comment by kiriles90** [comment]
Yes but in this case its not much of a feature. Nor is like netflix which actually records what you watch and tries to makes suggestion based on that (+ on what they try to push).

In Popcorn Time's case its a button that once you click it plays the first movie on the list. Well.. just click the first movie on the list and press play.. :)

**Comment by test2a** [comment]
yes. and no. Neflix provides suggestions, we dont want to go there. 
>just click the first movie on the list and press play..


yes. that is what everyone is doing but once the movie closes, what if something plays automatically. 
TV comes to mind. you just open a channel and watch. that is what i want to mimic. thats all

**Comment by Persei08** [comment]
That's why I was thinking a queue tab, could be a good thing for your idea. with an 'add to queue' button on covers and in descriptions, and then it could works a bit like the 'play next episode' feature. so people can easily search 'lord of the rings' or something and then just add all results and leave it playing. but it's just idea like that, at this point we're more focused into fixing what is broke.
