### ISSUE TITLE
Series Subtitles only display in English when watch in DLNA LG WebOs 

### ISSUE THREAD

**Issue by Mormam** [popcorntime/popcorntime#1172]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.0

Download date:
18 March

#### Expected Behaviour
Subtitle is displayed in the language i choose in Settings/Default Subtitle

#### Actual Behaviour
Always display the subtitle in English

#### Steps to reproduce the behaviour
1. choose in Settings/Default Subtitle -> Portuguese(Brasil)
2. Select a episode from a serie
3. Select DLNA
4. Click Watch Now

----------------------

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
