### ISSUE TITLE
nw_elf.dll

### ISSUE THREAD

**Issue by NessunoIM** [popcorntime/popcorntime#1174]
Operating System Version:
Windows 10 
Popcorn Time Version:
0.4

Download date:
19 March 2020

Kaspersky Total Security, updated to the latest version with standard settings says, after installing popcorn time, that nw_elf.dll file is a Trojan.

UDS:Trojan.Win32.Fsysna

So is impossible to use popcorn time (unless i add to exception)

**Comment by reddo** [comment]
Same for me with Bitdefender and the latest Popcorn Time v388

**Comment by scyto** [comment]
seems like a mis-detection to me (i uploaded filer versions 0.44.5) https://www.virustotal.com/gui/file/00daf4ebcdbb9f90cc8440d46b66bbb8300af546f98877f55b0abd56824d1cbd/detection

**Comment by magnusbjarnason** [comment]
Just tried same file from 0.3.10, received same result, multiple warnings about Trojan:
See result from online virus scanner Virustotal here: https://imgur.com/a/Pp0eFBO

**Comment by team-pct** [comment]
Same is happening with all Nwjs build ,
Get your clean build from nwjs.io and Scan nw_elf.dll you will get same result 
https://www.virustotal.com/gui/file/dc7f76ab3cf6dd30cbb1c3767aecabdea40695232060cfde3fea54f82367ec9a/detection

**Comment by scyto** [comment]
@team-pct thanks for filing with nwjs, cross linking for others https://github.com/nwjs/nw.js/issues/7418

**Comment by team-pct** [comment]
After contacting Microsoft AV , Kaspersky  now its marked as undetected

**Comment by team-pct** [comment]
Major AV marked it as false positive https://www.virustotal.com/gui/file/00daf4ebcdbb9f90cc8440d46b66bbb8300af546f98877f55b0abd56824d1cbd/detection

**Comment by jssuttles** [comment]
There are still a few AVs marking this as a problem.
https://www.virustotal.com/gui/file/00daf4ebcdbb9f90cc8440d46b66bbb8300af546f98877f55b0abd56824d1cbd/detection
