### ISSUE TITLE
No subtitles in v4

### ISSUE THREAD

**Issue by leossmith** [popcorntime/popcorntime#1176]
Operating System Version:
Windows 10

Popcorn Time Version:
v4.0

Download date:
18/03

#### Expected Behaviour
Show subtitles
...

#### Actual Behaviour
Doesn't show subtitles
...

#### Steps to reproduce the behaviour
Tried setting different languages as default

**Comment by dutchy1001** [comment]
Subtitles work fine, you need to click on the bottom right side of the "movie" page and choose your language from there.

![subs](https://user-images.githubusercontent.com/5569980/77050617-ef24ea80-69c1-11ea-95c7-943d71794060.png)
I do know it's a bit confusing as you can set a default language in the settings which indeed isn't working the way it should.

**Comment by leossmith** [comment]
Sorry I forgot to mention that i was referring to Series. There is no option to select language any more. Also there is no option when you start watching the episode. 

In movies it works without issues.

![image](https://user-images.githubusercontent.com/4300876/77057591-daa21b80-69dc-11ea-849a-31d227372429.png)

I tried setting a default language to "force" subtitles from the global settings but that didnt work either.

**Comment by dutchy1001** [comment]
I have no issue with "English subs" in the series section, there is an other [post](https://github.com/popcorn-official/popcorn-desktop/issues/1172) that refers to non-English subs not working.
When testing this myself with "Young Sheldon"(S03E09) both the Dutch language and English did work for me. I presume there are still episodes from a/any serie that just don't have subs added (yet).

**Comment by leossmith** [comment]
Similarly when I go to series and episode you refer to, I dont have an option to select a language before starting the episode. When I start it, again I cannot select subtitles.

![image](https://user-images.githubusercontent.com/4300876/77082410-afcbbd80-6a04-11ea-8650-cfe469ce9c7a.png)

Also if i click on custom, nothing happens.

**Comment by dutchy1001** [comment]
What language are you trying to get?
Could it be an issue with the popcorn default player?
I use SMPlayer to watch any film or serie,  you can then also add a sub you download from "[opensubtitle.org](https://www.opensubtitles.org/en/search/subs)".
If you know were popcorn time stores the temp file (or change it in the settings to a location you have easy access too) what your watching, you could then check that location for the subtitle's file (.srt or .vtt). I have notest that in some cases the file was there but didn't display in the player.

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/391/

**Comment by dutchy1001** [comment]
that link brings you back to version 0.3.10.
Version 0.4.0 has it's issue's but the subs issue can be overcome by using alternative players and subs download from opesubtitles.org or simular sites.

**Comment by team-pct** [comment]
Subtitle issue was fixed https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/394

**Comment by leossmith** [comment]
> Subtitle issue was fixed https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/394

It now works on build 394. Thank you for fixing that.
