### ISSUE TITLE
Connect to TVShow Time button results in infinite spinner.

### ISSUE THREAD

**Issue by scyto** [popcorntime/popcorntime#1177]
Operating System Version:
Window 10
MaOS 10.5.x

Popcorn Time Version:
4.0 

Download date:
3/18/20

#### Expected Behaviour
When i click Connect to TV Show Time i expected some sort of UI to handle connection.
...

#### Actual Behaviour
wheel on button spins forever
...

#### Steps to reproduce the behaviour
1. download either 32 or 64 bit version
2. run popcorn
3. goto settings
4 click connect to TV show time button

**Comment by diegogarciar** [comment]
I'm a user, I found out that tvshow's https certificate expired, that's why the api is failing internally

**Comment by scyto** [comment]
hi @diegogarciar i am user too, after i posted i noticed this PR https://github.com/popcorn-official/popcorn-desktop/pull/1171 i am suspecting this will fix it, i am waiting for a new build (or i may get brave and try the mac instructions for building it myself....)

**Comment by diegogarciar** [comment]
Nice! I did it and it worked
here are the steps
`show package contents` of popcorn-time
go to `contents/resources/ap.nw/src/app/lib/providers/tvshowtime.js`

modify the `API_ENDPOINT` to https://api.tvtime.com/v1
relaunch popcorn time
enjoy!

**Comment by scyto** [comment]
Nice! i never even thought to just edit the file locally, lol.

For any windows users that can't wait for next build this can be edited in ```C:\Users\%username%\AppData\Local\Popcorn-Time\src\app\lib\providers``` .

Closing as fixed by #1171

**Comment by scyto** [comment]
@diegogarciar QQ have you tried airplay? i tried sending from Mac to my ATV - nothing, could you see if you have same issue?
(sorry for abusing closed issue lol)

**Comment by diegogarciar** [comment]
I don't remember achieving this, can't say it's working, I usually cast to my samsung tv. If it fails, I think I end up Airplay(ing?) my whole screen

**Comment by scyto** [comment]
yeah i can airplay my whole screen, i couldn't get the airplay buttons working in the app UI, i will try casting to something else and the file the appropriate issues. Thanks.

**Comment by kiriles90** [comment]
Reopening this since they now (months ago actually) have terminated their API service. The only solution I guess now is a third party one or if something adequate cant be found remove the feature completely so as to not misdirect people thinking there is an issue on their end or this is some temporary connectivity issue.
