### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by cervantes33** [popcorntime/popcorntime#118]
please fix the subtitles to be acord to the audio please

**Comment by Breaking1** [comment]
You know you can sync subtitles in the internal player in popcorntime?

Press shift+? anywhere in PT or go to settings and press the pic of a keyboard to get up all the short cuts including how to sync subtitles.

Pretty sure all the external media players PT supports like VLC, MPC HC all have the possibility to sync subtitles in settings as well.

PT has no control over the subtitles, it just fetches them from different sites.

**Comment by jokhallouf** [comment]
I have the same problem!
I have popcorntime.sh version 0.3.9-0
i have tried so many episodes of so many different series . all tell me no subtitles found! i have set a default subtitle in the settings as English . All movies work fine but series don't work. subtitles for series work in my popcorntime CE though for the same series !
