### ISSUE TITLE
User interface suggestions

### ISSUE THREAD

**Issue by maximousblk** [popcorntime/popcorntime#1183]
Not that it looks bad, but it can be much improved.

There is just too much information and call for action that makes it cluttered.

I made a concept app which I recently realized looks very similar to popcorn time. So I renamed the title and here is what it looks like:

<img width="1500" alt="PopcornTime" src="https://user-images.githubusercontent.com/28438021/77165930-49649f00-6ad9-11ea-8165-944e3bf2c589.png">

You can also look at the [design files](https://www.figma.com/file/wA6Uw0WIYILosAEJxdrcok/Popcorn-Time) and build upon that if you want.

I'm not saying that this what it should look like, but it can be a starting point.

If this is something that is not needed at all, you can close this issue right away

**Comment by stavr0cks** [comment]
The font you used is fucking horrendous and you speak about clutter but you put all movies in an extra card? Get off your high horse.

**Comment by maximousblk** [comment]
I was actually talking about the layout. The reference was to be used as just a visual for the concept I made.

**Comment by maximousblk** [comment]
If you would agree, I can actually help make a proper design.

**Comment by fisforfaheem** [comment]
Yes we need Fluent Ui like Ui i mena just check out the youtube apps made for windows 10

**Comment by maximousblk** [comment]
Porting over to fluent would be way bigger project but if it does it would be awesome for windows user and a headache for maintainers as they have to replicate the interface for linux, and mac.

**Comment by fisforfaheem** [comment]
Maybe They could Use Flutter toolkit which outputs multiplatform
executables usingsingle code
