### ISSUE TITLE
Showing download size when selecting torrent quality 

### ISSUE THREAD

**Issue by ragrag** [popcorntime/popcorntime#1187]
Right now the only way to check for download size is to check it through the mobile client(Android). It would be very nice to see the download size of the selected torrent/quality just like the android client.

**Comment by team-pct** [comment]
Hover on quality selector you will get file size
EDIT : it was removed with last commit i will see how to get it back

**Comment by ivan1986** [comment]
for movies work fine last commit (https://github.com/popcorn-official/popcorn-desktop/commit/8e37235bfd4abcab04670dc6fa29df6ecdb8082e) for serials - api not send info for episode

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
