### ISSUE TITLE
Trojan reported in 0.3.10

### ISSUE THREAD

**Issue by magnusbjarnason** [popcorntime/popcorntime#1188]
Downloaded 0.3.10 from here: https://ci.popcorntime.app/view/All/job/Desktop2/
Filename: Popcorn-Time-0.3.10_win64.zip

Ran nw_elf.dll through online virus scanner, after reading this post concerning Trojan in 0.4.0: https://www.reddit.com/r/PopCornTime/comments/flcqsd/trojan_script_located_in_popcorntime_downloaded/, and received multiple warnings.

See result here: https://imgur.com/a/Pp0eFBO
MD5: 00daf4ebcdbb9f90cc8440d46b66bbb8300af546f98877f55b0abd56824d1cbd

Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Duplicate
