### ISSUE TITLE
Can't watch from my "favorites" tab

### ISSUE THREAD

**Issue by Bastidn** [popcorntime/popcorntime#1189]
Operating System Version:

Windows 10

Popcorn Time Version:

0.4.0-0

Download date:

20/03/2020
#### Expected Behaviour

to work normally, like it worked yesterday

#### Actual Behaviour

the first problem is that most of the movie posters in my "favorites" tab doesn't load, and all them in the "movie" tab don't load at all

![image](https://user-images.githubusercontent.com/18116834/77200196-60f85380-6aea-11ea-929e-14e747bbf749.png)

![image](https://user-images.githubusercontent.com/18116834/77200262-81c0a900-6aea-11ea-95d0-81a5fb7de60a.png)

second problem, i can't watch any movies that are in my "favorites" tab, the "watch now" button doesn't even appear

![image](https://user-images.githubusercontent.com/18116834/77200327-a0bf3b00-6aea-11ea-890d-fc76f804d0ef.png)

I also had that problem with the first 0.4.0 update, but not at the beginning, it first occured yesterday evening, and when I updated with the last version today, the problem is still occuring

#### Steps to reproduce the behaviour

1. open popcorn time
2. go in the "favorites" tab
3. open any movie which doesn't have it's artwork loaded

**Comment by hugobqd** [comment]
The same with macOs 10.15.3

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
