### ISSUE TITLE
Very high CPU load on Windows when idling

### ISSUE THREAD

**Issue by jonas-sk** [popcorntime/popcorntime#1190]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.0-0

Download date:
20.03.2020

#### Expected Behaviour
Popcorn-Time being a Javascript app I am used to a higher CPU load, especially while watching. 0.3.10 used around 20% while watching and 5-10% while browsing or doing nothing.

#### Actual Behaviour
0.4 uses up to 70% while watching and 40-60% while idling (not even having playback open, enough when you just open it up). It almost seems like it is running a cryptocurrency miner in the background.
 
#### Steps to reproduce the behaviour

1. Start the new PopcornTime app
2. Watch a movie, browse, or just let it idle in the background
3. Observe CPU load in the Task Manager

**Comment by Leoxur** [comment]
I notice that to, and I was wondering about the possibility of Popcorn is mining

**Comment by team-pct** [comment]
Before saying something like that you should first know that Popcorn Time is open source and we use the builds from CI that is built with all transparence

**Comment by Leoxur** [comment]
> Before saying something like that you should first know that Popcorn Time is open source and we use the builds from CI that is built with all transparence

Yes, of course, I have been using Popcorn for almost 3 years, I have not said that popcorn is mining, I meant to say that at the beginning "mining" is what came to my mind. I'm not a programmer, so I don't know the possible related cause

**Comment by team-pct** [comment]
What version you are using ?

**Comment by Leoxur** [comment]
> What version you are using ?

I notice the problem on 0.4.0.
I just upadate to 0.4.1, testing it since half an hour and seem problem is gone.

**Comment by team-pct** [comment]
The issue was with Seeding the update it was fixed on 0.4.1

**Comment by Leoxur** [comment]
Perfect!!!

**Comment by jonas-sk** [comment]
I didn't test it yet but thanks for fixing the issue! I didn't want to imply that PCT is mining, just that the usage was really reminiscent

**Comment by elektrinis** [comment]
Very old issue, however in-movie CPU usage of v0.4.5 is still much higher than VLC for example. Drains the laptop very quickly.

**Comment by dutchy1001** [comment]
@elektrinis have you updated to 0.4.6 to see if that makes a difference?
(get 0.4.6 [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/1528068254) )

**Comment by elektrinis** [comment]
I saw the 0.4.6 and updated only today, so I will check in a week or so, once I have the chance to watch a movie again. :)

**Comment by kiriles90** [comment]
@elektrinis VLC doesnt have to download/upload the movie in a thousand pieces and different places in torrent form. But ignoring that, even for playback alone its a more complete dedicated media player so it makes sense. That's why external player support exists, you can use any of the currently supported media players instead of the Popcorn Time native player if you prefer.
