### ISSUE TITLE
Not downloading movies thumbnails

### ISSUE THREAD

**Issue by hugojcqs** [popcorntime/popcorntime#1191]
Operating System Version:
Windows 10

Popcorn Time Version:
Where can I find it ? Anyway, I did the last update.

#### Expected Behaviour

- Download all the thumbnails / pictures for the movies. 

- "Report a trouble" link that does not open my web browser. 

#### Other infos
The VPN is disabled, but the problem existed before that. 
By the way, all the thumbnails for the series are downloaded while those for movies are not.

Good job for the last update, keep it up cowboy_hat_face:​

**Comment by aneeskA** [comment]
Yes same experience here.

**Comment by hamza-jmai** [comment]
Yes same experience here.

**Comment by hamza-jmai** [comment]
What Now!!??

**Comment by team-pct** [comment]
Fanart.tv Issue , it will be fixed by itself

**Comment by hamza-jmai** [comment]
When?

**Comment by team-pct** [comment]
ask fanart ....

**Comment by hamza-jmai** [comment]
are the size of the movie pictura have changed?

**Comment by hamza-jmai** [comment]
picture size?

**Comment by team-pct** [comment]
No
