### ISSUE TITLE
Too many bugs to consider it a pleasant experience

### ISSUE THREAD

**Issue by stavr0cks** [popcorntime/popcorntime#1192]
Operating System Version:
macOS Catalina 10.15.3

Popcorn Time Version:
Popcorn Time 4.0

Download date:
March 19, 2020

1. Movie posters seem to randomly not load at all, sometimes they load for some movies/series, sometimes the entire list only shows the Popcorn Time logo placeholder which makes it painfully hard to browse content;

2. That annoying red blinking VPN icon is really too much;

3. While playing a movie, but not in full screen, there is no top bar with icons to minimize, expand or close app. Seriously?

4. While playing a movie, there is no subtitle selector, so you have to quit the movie and go back a screen to select subtitle track. Come on.

5. While at subtitles, the app completely ignores the default subtitle language in Settings and by default loads no subtitle at all;

6. The buttons to increase/decrease the subtitle font don't do anything, they don't work;

7. After closing the app, the movie file remains downloaded in the cache folder filing up my hard drive even though I have selected to clean the tmp directory when closed. I need to manually delete movies.

**Comment by hamza-jmai** [comment]
Yes same experience here. on windows 7 or 10 the same. the old version of popcorn or the latest the same problem.

**Comment by omerl13** [comment]
Regarding 7 (caching), not sure if it is a bug, but maybe an option to enable/disable this functionality on Settings would be a good solution

**Comment by stavr0cks** [comment]
> Regarding 7 (caching), not sure if it is a bug, but maybe an option to enable/disable this functionality on Settings would be a good solution

There used to be an option not to save the movies after you're done watching them. But this version is just a big clusterfuck of unfinished things. And they ruined most of the good old stuff.

**Comment by team-pct** [comment]
@stavros3006  you are welcome to fix things , or even use your private version

**Comment by stavr0cks** [comment]
> @stavros3006 you are welcome to fix things , or even use your private version

With all due respect, but when you create software to be used by the public, you decide on your own wether you'll be charging for it or will give it out for free, nobody's putting a gun to your head to do it.

In your case it would be unheard of to charge for it as your entire software is based on criminal. I'm noy saying we the users are not in the same boat, but anyway.

Having that in mind, just because you offer something for free, doesn't mean that when you receive negative feedback for it, your defense should always be "here, build one yourself if you can do it better". It's out there publicly, it's on the internet, it can be downloaded and everybody has the right to report something wrong with it.

All the issues I and countless others listed only speak volumes of how much lousy QA you put into the thing and that with issues like these, it doesn't even come close to it being a minimum viable product.

**Comment by team-pct** [comment]
these changes are sitting here for years no one cared to comment or test and now everyone is bitching , so if you wanna fix things you are welcome that is all what i said yea its free and open source

**Comment by stavr0cks** [comment]
> these changes are sitting here for years no one cared to comment or test and now everyone is bitching , so if you wanna fix things you are welcome that is all what i said yea its free and open source

I abandoned development several years ago to fully focus on UI design and user experience.

If there's anything needed on that front, I'd be happy to help out.

**Comment by team-pct** [comment]
make yourself home ,
https://github.com/popcorn-official/popcorn-desktop/tree/development/src/app/styl
https://github.com/popcorn-official/popcorn-desktop/tree/development/src/app/templates

**Comment by team-pct** [comment]
Most of issues cited here are fixed Please open a new issue if you find new bug
