### ISSUE TITLE
Why dont this app uses Latest version of node JS? It has Huge benefits and speed

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#1199]
Operating System Version:
 Windows 10
Popcorn Time Version:
latest new version

Download date:
2 days ago

#### Expected Behaviour
Fluent and latest everything
...

#### Actual Behaviour
Same old Node.js and other way older tech, Please update to latest atleast

#### Steps to reproduce the behaviour

1. ...Just update the main core, and use latess node.js
use better new engine
2: also please add a section for hindi dubbed movies too

**Comment by team-pct** [comment]
We are using Nwjs44.5 ( node.js v13)

**Comment by fisforfaheem** [comment]
What about other underlying tech? is it the very latest?

**Comment by fisforfaheem** [comment]
also please tell where is the release button? on github it;s gone now

**Comment by team-pct** [comment]
underlying tech ? Do you mean the code?

**Comment by team-pct** [comment]
https://github.com/popcorn-official/popcorn-desktop/releases ?

**Comment by fisforfaheem** [comment]
Thanks! also please  please update the changelog in the app its too old!!! and provide easy update from app itself! and add some Fluent Ui

**Comment by guilherme93** [comment]
Or you know since you're complaining so much YOU can do it

**Comment by fisforfaheem** [comment]
I dont know Man! I just want you guys to make the best version of your
software! with best regards
