### ISSUE TITLE
Travis CI and David

### ISSUE THREAD

**Issue by 394394394** [popcorntime/popcorntime#12]
The links for [Travis](https://travis-ci.org/butterproject/butter-desktop) and [David](https://david-dm.org/butterproject/butter-desktop) in the README are linking to Butter accounts. Will you create accounts in those services?

**Comment by team-pct** [comment]
As soon as possible , i will look into it

**Comment by 394394394** [comment]
:smile:

**Comment by team-pct** [comment]
Done
