### ISSUE TITLE
Time calculation and Peers gathering issues

### ISSUE THREAD

**Issue by iMansoorAliKhan** [popcorntime/popcorntime#1201]
Operating System Version:

10.13.6
Popcorn Time Version:

4.1
Download date:

Today as I am posting this
#### Expected Behaviour

...

#### Actual Behaviour

...

While I was using the last version in mac, it was smooth, but this new version is completely disastrous. Why?
1- The quality selection
2- Peers finding and basic movie cache calculation takes too much time
3-the new apply VPN screen blocker is disturbing. It looks like you guys have opted the other variant style, which is not something I like about that. 
this version speed is decreased
The remaining time bug
![Uploading image.png…]()

**Comment by iMansoorAliKhan** [comment]
https://share.getcloudapp.com/JruWmnXD

**Comment by iMansoorAliKhan** [comment]
https://share.getcloudapp.com/9ZuALRN8

The download speed + the time require, why this is changing too much speed? it was not like this before .

In last version 3.2.0 it was far better than this one

**Comment by team-pct** [comment]
Fixed on ed3316b
