### ISSUE TITLE
Popcorn Time prompts for allowing incoming connection every time it launches. 

### ISSUE THREAD

**Issue by sohojmanush** [popcorntime/popcorntime#1206]
Operating System Version: OS X 10.14.6

Popcorn Time Version: v0.4.0

Download date: Auto Updated

#### Expected Behaviour
No firewall related prompts because the app is already in the firewall exception list. 

#### Actual Behaviour
![Screen Shot 2020-03-23 at 03 37 40](https://user-images.githubusercontent.com/5019527/77261315-d9f8d600-6cb7-11ea-8388-6db36da0216e.png)
Asking to allow the app to accept the incoming connections.
![Screen Shot 2020-03-23 at 03 41 24](https://user-images.githubusercontent.com/5019527/77261372-3f4cc700-6cb8-11ea-9224-ea5de0037aa1.png)

...

#### Steps to reproduce the behaviour

1. Go System Preferences>Security & Privacy>Firewall
2. Turn on Firewall

**Comment by kiriles90** [comment]
Its not Popcorn Time that prompts you to allow connection its your OS. This doesnt seem to be an issue with macOS either or we would have a lot more people reporting it. Its probably something specific to your system. Try clean installing the latest dev build (439 at the moment) then make sure its allowed in your firewall (it might be named 'nwjs' also) and check if the issue persists.

@Persei08 can you close this please since its not an actual issue with Popcorn Time?

**Comment by tingspain** [comment]
@sohojmanush, did you solve this issue? I tried to uninstall it and install it again (with new versions), and nothing, I keep getting the same msg.  

Thanks in advance

**Comment by sohojmanush** [comment]
No, It's a probably macOS app notarization issue.

**Comment by tingspain** [comment]
I managed to "fix it" by signing the application using the following command:

`sudo codesign --force --deep --sign - /Applications/Popcorn-Time.app`

**Comment by sohojmanush** [comment]
Didn't work for me.

**Comment by tingspain** [comment]
Did you add the popcorn time application and nwjs helper into the firewall to allow incoming connections?

**Comment by sohojmanush** [comment]
Yes, it's added to the firewall. And working perfectly. But, that prompt still persists after applying that codesign command.

**Comment by tingspain** [comment]
Did you remove popcorn time app from firewall before codesign it? That is what i did. I removed it from the firewall, codesign it and run popcorn time.  I hope these steps will work to you. I did for me

**Comment by sohojmanush** [comment]
> Did you add the popcorn time application and nwjs helper into the firewall to allow incoming connections?

It's working now, after following your steps that popup disappeared. Really appreciated the help, Thank You.

**Comment by tingspain** [comment]
I am glad to hear that it is working for you too. ^__^
