### ISSUE TITLE
Installing 64 instead of 32 bit version

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1208]
Operating System Version:
Windows 10 32 bit

Popcorn Time Version:
4.1

Download date:
22/03/2020

#### Expected Behaviour
Launch after installing
...

#### Actual Behaviour
Update installs a 64 bit version on a 32 bit windows, which then fails to start.
...

#### Steps to reproduce the behaviour
Create a virtual machine with 32 bit Windows 10. Install 3.1 version and then turn on the updater.
When you go to the official website, it also downloads the version that has "64" in the file name.
The part that determines what version of windows you have to download the right version is not working correctly.

Edit: I just installed it on my second laptop which has 64 bit Windows 10... The installer this time installs the 32 bit version by default. I think you got something mixed up in the coding.

**Comment by diwu1989** [comment]
Using the 32bit on 64bit machine actually reduces the memory consumption as well.

**Comment by joliett1234** [comment]
https://get.popcorntime.app/repo/build/

Get the newest version 4.3

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
