### ISSUE TITLE
"Report issue" button doesn't work in app.

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1209]
Operating System Version:
Windows 10, both 32 and 64 bit.

Popcorn Time Version:
Doesn't work in 4.1. It was working in 3.1.

Download date:
22/03/2020

#### Expected Behaviour
When you click "Report Issue" in the Popcorn app, it asks you for Github login and password, but it doesn't work anymore in 4.1 version.

#### Actual Behaviour
Weird behaviour.

#### Steps to reproduce the behaviour
Install on windows 10 and click "Report Issue" under "About App" or when you go to settings and click "Help section" or something like this.

**Comment by Persei08** [comment]
So, now it just open the issue board in your browser. More a workaround than a fix but it do the job
