### ISSUE TITLE
Trakt.tv not show the List

### ISSUE THREAD

**Issue by lucawen** [popcorntime/popcorntime#121]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
26/03/2016
#### Expected Behaviour

Show the list of TV Shows from Trakt.tv
...
#### Actual Behaviour

Show a message to configure or sync my Trakt.tv account.
...
#### Steps to repoduce the behaviour

Click on List

Console Print
![print](https://cloud.githubusercontent.com/assets/1365208/14063238/f85c8150-f39e-11e5-9064-759d7b3e1cfa.png)

**Comment by SeungRyul** [comment]
Also have the exact same problem. Hopefully it is fixed soon.

**Comment by Pretenderr** [comment]
The same issue. Ubuntu. Version of PT: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/97/

**Comment by VitorVRS** [comment]
I was uncapable to reproduce this bug. Can you inform more detailed steps?

**Comment by JimiC** [comment]
The actual bug is that PT doesn't show the `Watchlist` from Trakt.tv. The movies and TV shows are marked correctly as shown.

**Comment by VitorVRS** [comment]
I've created an Trakt.tv account yesterday, marked 2 shows: Mr Robot and Batman; watched and add to watchlist, respectively.
I opened PCT, synced my account, then i clicked on "Watclist" icon (some kind a box?) and showed Batman (the same show i've marked to watchlist on Trakt.tv website).

So, it works for me, can you try the latest build?

**Comment by AlexFMM** [comment]
After reading the last comment I tried, uninstalling completely and installing the latest build and it worked, now the watch list works with no errors

**Comment by JimiC** [comment]
I'll try what @AlexFMM did and see if this fixes it. Will report back with any findings.

**Comment by JimiC** [comment]
@VitorVRS Unfortunately, it doesn't work for me. Perhaps I'm doing something wrong. I'm on Windows 10 and using PCT v0.3.9. Couldn't install v0.4.0 (call me stupid).

**Comment by VitorVRS** [comment]
@JimiC calm down :) 
Can you reproduce those steps again, but with devtools open (F12)?
If it shows an error put an print here or ctrl-v.

I am not able to reproduce on windows, since i dont have it.

**Comment by JimiC** [comment]
Here is my print:
![untitled](https://cloud.githubusercontent.com/assets/1716442/14749785/25aefc60-08ca-11e6-8386-3713c617de57.png)

**Comment by lucawen** [comment]
Yep, this is the same error.. I just do not fix the error because I'm not time to work on the project, but for those who are active, this is a problem function that could not take place ..

**Comment by JimiC** [comment]
@VitorVRS I could be wrong but here is my 0.02 cents.
While trying to debug the issue the problem seems to occur on `generic_collection` line 8. In my case `torrentsPromise` has 13 objects in the array but when trying to `bind` the `torrentProvider.extractIds` the `idsPromise` results in having an array with 2 `undefined` objects.

Edit1: In `watchlist` line 185 `_.pluck(items, 'imdb_id')` returns an array of `undefined` objects although `items` is an object of 

```
hasMore: false
results: Array[13]
__proto__: Object
```

Edit2: OK. Found it! The passing parameter is `items` instead of `items.results`. When I replaced `_.pluck(items, 'imdb_id')` with `_.pluck(items.results, 'imdb_id')` it worked.

**Comment by JimiC** [comment]
@lucawen @VitorVRS See my edits above.

**Comment by VitorVRS** [comment]
@JimiC the way i've tested, worked for me.
Don't know where our tests are diverging, but with the information i have, it's some problem with Windows.

I'm not home now, i'll test your changes in my workspace and see if still works.
Can you inform your testing flow?

**Comment by JimiC** [comment]
@VitorVRS 
1.Opened `watchlist.js` made the change in line 185. 
2. Opened PCT
3. Clicked Watclist icon.
4. Profit (show images appeared).

But still there is an issue when you click on any of the shows image. It crashes there.

**Comment by AlexFMM** [comment]
Yeah i have the same problem, when entering the watchlist i get a bunch of warningsaying that it was unable to find the show, and when a click any show it gives an error
![screenshot_1](https://cloud.githubusercontent.com/assets/1975276/14755187/75c48d2e-08d8-11e6-8535-7c015155e6bc.png)

**Comment by JimiC** [comment]
@AlexFMM That's the same crash I get now.

**Comment by gonsaaa** [comment]
@JimiC 
Made the changes to watchlist.js and now they appear as well but I have the same issue of clicking on the images and nothing happens...

**Comment by sgarro** [comment]
same issue, still doesn't work

**Comment by JimiC** [comment]
With version 0.3.10. this issue is kinda redundant, as the problem has moved from not showing the watchlist, to not selecting the movie/show upon clicking on them. I believe this issue should be closed and the #273 should be kept alive.

I leave a comment with my findings about the issue on the other issue (#273).

**Comment by ChrisAlderson** [comment]
Agree with @JimiC

**Comment by stellaki13** [comment]
hello i have winows 7 and pct 6.0 builts i cannot download from server sayw eror even with manager i have problem with trakt no opening at all even when i make the connection and butter closing the window and in watclist sayw to synchronize with trakt whats the pro again i have connected and allowd butter to sync but nothing why?
