### ISSUE TITLE
Torrent file upload does not work

### ISSUE THREAD

**Issue by jplaut** [popcorntime/popcorntime#1210]
Operating System Version:
OS X 10.15.2

Popcorn Time Version:
0.4.1

Download date:
03/22/2020

#### Expected Behaviour
As in 0.3.10, when I upload a torrent file, I expect the app to find the playable video, allow me to select it, and then play said video.

#### Actual Behaviour
Shows me a "Sign up for VPN banner (I already use Nord VPN so the banner is both superfluous and incredibly annoying)" and continues to say connect, despite the torrent having at least 2000 seeders and me getting over 2mb/s download on Transmission.

#### Steps to reproduce the behaviour
Download a highly seeded torrent (from pirate bay or 1337.to) and try to play using popcorn time. Observe the shittiness.

**Comment by team-pct** [comment]
Past magnet to fix immediate solution
we will look for drag and drop torrent

**Comment by team-pct** [comment]
Commit 7dbe9f1 should fix that please test https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/400/
