### ISSUE TITLE
Cannot play any torrent if cache directory is not default

### ISSUE THREAD

**Issue by harmonymeow** [popcorntime/popcorntime#1213]
Operating System Version:
Windows 10

Popcorn Time Version:
Build 398

Download date:
3/22/2020

#### Expected Behaviour
In Build 396, if I play a movie for the first time. I see:
app.js:17 [INFO] Loading torrent
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'D:\temp\Popcorn Time/TorrentCache/9185a249fa36f5743c8315fbab1b596af691a3db'

At this point, if I click cancel and start the movie again, it continues without complaining.

#### Actual Behaviour
In Build 398, the error message appears every time I try to play any movie. The "cancel and restart" trick no longer works.

#### Steps to reproduce the behaviour
1. change "Cahced diretory" to anything that is not default.
2. Play any title.

It is highly possible this bug is introduced in bb76111030dbd8699de2e174a4ddf435d1cf1414

**Comment by dutchy1001** [comment]
This is the same in [build 399,](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/399/) nothing will play for me as I don't have the default directory. I've tried using the default popcorn player and SMPlayer without any luck. As the OP already mentioned the "cancel/restart" trick isn't working anymore.
The movie or serie episode will still download to my given directory were I can then start it manual with SMPlayer. 
With that said, the progress bar is still missing and guessing when a movie or serie episode is downloaded is then difficult to see.

**Comment by RafaelDominiquini** [comment]
I have the same problem and I believe it is related to the bug: [1218](https://github.com/popcorn-official/popcorn-desktop/issues/1218)

Thanks

**Comment by team-pct** [comment]
fixed on 759b5e2
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/401/

**Comment by dutchy1001** [comment]
thank you team-pct

Edit:
still only works if usung the default cache location
