### ISSUE TITLE
movies tile images do not load 

### ISSUE THREAD

**Issue by dandydarshan** [popcorntime/popcorntime#1214]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.10

Download date:
22nd March 2020

#### Expected Behaviour
movie tile images to load upon clicking of the movie tab 
...

#### Actual Behaviour
tile images do not load and default image is loaded
...

#### Steps to reproduce the behaviour
1...  click on movie tab 
![img1](https://user-images.githubusercontent.com/33479560/77427331-32d18700-6dfc-11ea-8722-9661a3454928.png)

**Comment by Persei08** [comment]
Due to traffic increase, fanart.tv have limited the requests to 3 per second and their servers send 503 response after that.

More infos on their twitter: https://twitter.com/fanartdottv/status/1242045876035563520?s=20
