### ISSUE TITLE
Can't change cache directory?

### ISSUE THREAD

**Issue by andreportaro** [popcorntime/popcorntime#1218]
Operating System Version:
Windos 10

Popcorn Time Version:
0.4.1

Download date:
mar/24 2020

#### Expected Behaviour
Selecting a different temporary folder for the downloads saves the new selection

#### Actual Behaviour
Nothing happens after selecting a different download location

Hi all! 
I did this before time and again, but for some reason, I cannot change the default location of downloads anymore. It doesn't matter where I chose the folder or if I open the app with administrator access or not. 

Any help appreciated.

**Comment by RafaelDominiquini** [comment]
I have the same problem and I believe it is related to the bug: [1213](https://github.com/popcorn-official/popcorn-desktop/issues/1213)

Thanks

**Comment by team-pct** [comment]
Fixed on 759b5e2
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/401/
