### ISSUE TITLE
Favorites menu crashes app once clicked twice

### ISSUE THREAD

**Issue by bkahen619** [popcorntime/popcorntime#1219]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
a few years back. have re downloaded since to try to fix problem

#### Expected Behaviour
go back and forth from fav to regular menu
...

#### Actual Behaviour
App crashes every time
...

#### Steps to reproduce the behaviour

1. click favorites
2.  click any other menu screen button
3. crashes whole app
![popcorn2](https://user-images.githubusercontent.com/27939408/77495243-5f969600-6e1e-11ea-921b-b9cff8e37055.jpg)
![Annotation 2020-03-24 222539](https://user-images.githubusercontent.com/27939408/77495259-691ffe00-6e1e-11ea-945e-6658b603cdea.jpg)

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
