### ISSUE TITLE
PCT won't play any torrent if cache directory is not default

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1221]
Operating System Version:
Windows 10

Popcorn Time Version:
latest build 401

Download date:
25/03/2020 (time 15:15)

#### Expected Behaviour
after changing the default Cache Directory the movie or serie play as normal.
...

#### Actual Behaviour
after changing the default Cache Directory the movie or serie wont play.
...

#### Steps to reproduce the behaviour

1. Change Cache Directory in settings (in my case to G-drive) to different location
2. start watching movie or serie
3. Screen stuck at "connecting"
![connecting](https://user-images.githubusercontent.com/5569980/77567253-cbc8d680-6ebe-11ea-8cdb-abcaa88b750b.png)
4. File still downloads to "new" location and can be started manual

**Comment by team-pct** [comment]
Open console with F12 and see if there is an error

**Comment by dutchy1001** [comment]
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/00d3b686172de76f03b0e9e3506f6853048ed48a'
win.error @ app.js:36
app.js:17 [INFO] Closing loading view
app.js:17 [INFO] Streaming cancelled
quality-selector.js:79 Select quality:  720p
show_detail.js:497 Playing next episode automatically: true
app.js:17 [INFO] Loading torrent
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/00d3b686172de76f03b0e9e3506f6853048ed48a'
win.error @ app.js:36

full log is [here](https://pastebin.com/yDPkpKiA)

**Comment by team-pct** [comment]
Seems it was not able to create TorrentCache folder
try to remove This folder and create a new one
https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L584

**Comment by dutchy1001** [comment]
After deleting the folder and re-apply the path it worked, as soon I added a serie to the favorite folder it stopped working

app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/df6304836a07293f0159e4b3a8a216d23176bfb2'
win.error @ app.js:36
app.js:17 [INFO] Closing loading view
app.js:17 [INFO] Streaming cancelled
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
show_detail.js:497 Playing next episode automatically: true
app.js:17 [INFO] Loading torrent
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/df6304836a07293f0159e4b3a8a216d23176bfb2'
win.error @ app.js:36
app.js:17 [INFO] Closing loading view
app.js:17 [INFO] Streaming cancelled
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
show_detail.js:497 Playing next episode automatically: true
app.js:17 [INFO] Loading torrent
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/07f6892608a891c8732ce40207734381822bfc2e'
win.error @ app.js:36
app.js:17 [INFO] Closing loading view
app.js:17 [INFO] Streaming cancelled
app.js:17 [INFO] Returning cached provider Favorites
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
item.js:296 Bookmark deleted (tt5555260)
app.js:17 [INFO] Returning cached provider Favorites
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
app.js:17 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
quality-selector.js:79 Select quality:  720p
show_detail.js:497 Playing next episode automatically: true
app.js:17 [INFO] Loading torrent
app.js:36 [ERROR] Error: ENOENT: no such file or directory, open 'G:\Popcorn Time/TorrentCache/b85e33db77bd73d5e3e1afe8eda818162235bd06'
win.error @ app.js:36
handleErrors @ streamer.js:105
Promise.catch (async)
start @ streamer.js:70
_ @ backbone.js:369
m @ backbone.js:356
f @ backbone.js:155
u.trigger @ backbone.js:346
startStreaming @ show_detail.js:499
N @ underscore-min.js:5
(anonymous) @ underscore-min.js:5
(anonymous) @ underscore-min.js:5
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

full log [here](https://pastebin.com/uTzRa6GE)

After deleting the serie from the favorite folder it still won't play but downloads to the path I gave it

**Comment by team-pct** [comment]
Replace https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L135

'/TorrentCache' by '/' 

it should fix this issue

**Comment by dutchy1001** [comment]
I'm not a coder and compiling my own version is not an option.

**Comment by dutchy1001** [comment]
Found the file, changed the '/TorrentCache' to '/' and working now.

Will this be changed in the next update or do we have to manual keep changing this?

Thanks for your great work on PCT

**Comment by team-pct** [comment]
I will push it as fix later today

**Comment by dutchy1001** [comment]
great, thank for your help

**Comment by dutchy1001** [comment]
Spoke to soon, after restarting and adding series to the favorite folder.
See log [here](https://pastebin.com/b1Vqvyjw) as to long to post 
![no-folder](https://user-images.githubusercontent.com/5569980/77578098-db9ce680-6ecf-11ea-8b54-f77fed460c38.png)
As you can see it wont make a folder now were the files are saved in

**Comment by team-pct** [comment]
Can you tell me the steps you made so i reproduce it locally?

**Comment by dutchy1001** [comment]
I'll start fresh and see if I can reproduce this myself, as soon I done this I let you know tonight.

**Comment by dutchy1001** [comment]
1 - Reverted back to build 396 (all working with cancel/restart trick)
2 - Updated PCT with Popcorn-Time-0.4.1_win64.zip (build 401). Overwriting files
3 - Start PCT open favorite tab and choose file to watch
	- Nothing happens, stuck on "connecting"
	- File still downloads to folder, manual starting with SMplayer works
4 - Clear Cache Directory (G-drive) location manual (set in settings not to clear after closing)
5 - Update change you gave  '/TorrentCache' to '/' PCT starts normal
6 - Download screen starts, SMPlayer starts but is stuck on loading (see red arrow circle going around and around in SMPlayer)
![screenshot](https://user-images.githubusercontent.com/5569980/77586253-c333c880-6edd-11ea-9cee-e1698d340a30.png)
7 - folder location on G-drive looking as previous posted pic in above post.

Next post I will uninstall PCT clean DB's and start with new install build 401

**Comment by dutchy1001** [comment]
1 - Fresh download "Popcorn-Time-0.4.1-win64-Setup.exe" build 401.
2 - Install to default location (AppData-Local)
3 - Start PCT right after install (only setting changed to use SMPlayer)
		- series: no issue
		- movies: no issue
4 - changing settings
		- Cache Directory to "G:\", PCT auto change this to "G:\Popcorn Time"
		- Disable VPN (bit annoying if you dont have one)
		- Untick "Activate automatic updating"
5 - Choose serie to watch 
		- Download screen starts
		- SMPlayer starts
		- File playing normal
6 - Choose movie to watch
		- Download screen starts
		- SMPlayer starts
		- File playing normal
7 -  adding series to favorite folder
8 - Choose serie to watch 
		- Download screen starts
		- SMPlayer starts
		- File playing normal
9 -  Closing PCT
10 - Opening PCT
11 - Choosing file from Favorite folder
		- Connecting screen starts
		- Stuck on "connecting" screen
		- Cancel/restart trick not working
		- File still downloading to "G:\Popcorn Time"
		- log can be found [here](https://pastebin.com/tyKXSe5z) 
12 - Reverting "Cache Directory" back to default "AppData/Local/Temp" directory and all is working again.

to be continued

**Comment by dutchy1001** [comment]
13 - Cache Directory set back to G-drive
14 - Change "streamer.js" from '/TorrentCache' to '/' 
15 - starting PCT again
16 - Choosing serie from favorite folder
17 - Download screen starts, SMPlayer starts but is stuck on loading (see previous pic with red arrow)
18 - File saved in "G:\Popcorn Time" is again same as before
19 - log can be found [here](https://pastebin.com/2QQ8e3Gb)

hope this helps

**Comment by harmonymeow** [comment]
I don't know anything about node.js but based on https://gist.github.com/drodsou/de2ba6291aea67ffc5bc4b52d8c32abd#gistcomment-2943513

`/` may not behave as expected on Windows platform.

Can we try what is suggested:
```
const path = require("path");
```

And then replace all instances of hardcoded `/` with `path.sep`?

**Comment by dutchy1001** [comment]
With the latest build 402 it seems this issue has been fixed.

thx
