### ISSUE TITLE
Torrent magnet links drag&drop not working

### ISSUE THREAD

**Issue by kkrcelic** [popcorntime/popcorntime#1222]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.1

Download date:
20.03.2020.

#### Expected Behaviour
Drag&drop of magnet link streams movie/series.

#### Actual Behaviour
When magnet link is drag&drop-ed, nothing happens.

#### Steps to reproduce the behaviour
1. drag&drop magnet link

**Comment by team-pct** [comment]
Magnet you just have to Past it / Copy Magnet / Past Magnet

**Comment by kkrcelic** [comment]
I tried that and it wasn't working. Also, in previous version (0.3.1), drag&drop magnet links was working so I don't see why it wouldn't work anymore.

**Comment by team-pct** [comment]
Try https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/401/
if this is not working when you open Popcorn Time press F12 and give us the console content after pasting magnet

**Comment by kkrcelic** [comment]
Works in the latest build, so I'm closing this issue.
