### ISSUE TITLE
Subtitle timings messed up

### ISSUE THREAD

**Issue by kkrcelic** [popcorntime/popcorntime#1223]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.1
Download date:
20.03.2020.

#### Expected Behaviour
Subtitles work and are timed correctly

#### Actual Behaviour
Subtitles work and are timed correctly for a portion of the movie, after some time it gets messed up. If you restart movie again and start from the spot you were before, the same subtitles are now timed correctly.

#### Steps to reproduce the behaviour
1. Start a movie and select subtitles Watch for some time and it timings will get messed up.

**Comment by kiriles90** [comment]
@kk47042 does this still happen with the latest dev build from ci.popcorntime.app? I couldn't reproduce it.

**Comment by kiriles90** [comment]
Closing this for now. I'll re-open if the OP or someone else who can reproduce this on the latest build replies.

**Comment by kkrcelic-ub** [comment]
I'll try to reproduce it on the latest build. If there's no more replies from me, consider it solved.
