### ISSUE TITLE
Cannot change download directory on OSX and it freezes.

### ISSUE THREAD

**Issue by rapito** [popcorntime/popcorntime#1224]
Operating System Version:
OS X 10.11

Popcorn Time Version:
4.1
Download date:
forced yesterday even if auto update was offf
#### Expected Behaviour
after selecting the directory it should show the path on the input and be saved...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. open settings
2. click on cache directory input
3. notice it freezes for some time
4. navigate to desired directory and notice it freezes a couple more times
5. finally select the desired directory and click ok
6. notice the input path did not change

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
