### ISSUE TITLE
Version 4.1 Time counter bug and other counter glitches

### ISSUE THREAD

**Issue by DK013** [popcorntime/popcorntime#1230]
Operating System Version:
Windows 10 version 1909 build 18363.720

Popcorn Time Version:
4.1

Download date:

![2020 03 27-13 09](https://user-images.githubusercontent.com/22991490/77733700-60514700-702d-11ea-84fc-15c2b15cf103.gif)
26 March 2020

#### Expected Behaviour
Show proper remaining time in download status

#### Actual Behaviour
1. Time count is wrong and showing ~300 hours when the right count should be minutes
2. Other counters like download speed, peers are glitchy. maybe put a 1sec interval for showing count on the client side?

#### Steps to reproduce the behaviour

1. Start downloading anything and check the status (the eye icon)

**Comment by joliett1234** [comment]
There is a new version 
Popcorn-Time-0.4.3-win64-Setup.exe
Fixes all the issues.

Download:
https://get.popcorntime.app/repo/build/

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
