### ISSUE TITLE
any place to see stats? like current seeding

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1231]
Is there a place in the app where we can see stats? like how much we have downloaded today and weekly and also current downloading/seeding. 
Same for speeds as well. What i am expecting is if i have set a torrent on seed but dont want to seed the day after, that time i should be able to stop seeding that one only and not others.

**Comment by Persei08** [comment]
Nothing like that, maybe open a feature request

**Comment by test2a** [comment]
oh look. they introduced this and there was no news about it. anyways, good job team
![1](https://user-images.githubusercontent.com/39449563/78424884-118b5900-768e-11ea-8cc7-71aa3f4d6c66.png)

**Comment by test2a** [comment]
yeah well i guess its closed now
