### ISSUE TITLE
Overall ratio not displayed in settings

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1232]
Operating System Version:
At least Linux

Popcorn Time Version:
4.4 

Download date:
n/a

#### Expected Behaviour
Display overall ratio in settings

#### Actual Behaviour
Display 'None'
![Screenshot_2020-05-04_14-50-20](https://user-images.githubusercontent.com/22459458/80967405-9e087300-8e16-11ea-9e82-53620b956422.png)

#### Steps to reproduce the behaviour

1. Launch PCT, go in settings, check "Advanced Settings" (so overall ratio field is now displayed)
2. Go back and watch episodes or movies
3. When finish go in settings to check overall ratio

**Comment by test2a** [comment]
i am on 3.1 linux and i did try 4.1 but same issue

**Comment by Persei08** [comment]
It isn't for settings the ratio.. it's your ratio

**Comment by test2a** [comment]
nah man.   even that isnt working. its showing "none" which doesnt make any sense because i did get a couple of movies
![11](https://user-images.githubusercontent.com/39449563/77882153-085d4f00-727e-11ea-945b-10d360b4ef3a.png)

**Comment by Persei08** [comment]
It's your global ratio. It is just bugged

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
