### ISSUE TITLE
Trakt Watchlist Artwork Doesn't Load

### ISSUE THREAD

**Issue by vincekruger** [popcorntime/popcorntime#1233]
Operating System Version:
macOS 10.15.4

Popcorn Time Version:
0.4.1

Download date:
2020-03-27 < Re-installation

#### Expected Behaviour
Was hoping for Trakt watchlist artwork to load

#### Actual Behaviour
Artwork doesn't load

#### Steps to reproduce the behaviour
Sign in to a Trakt account and sync watchlist

**Comment by Dgaduin** [comment]
I'm on 0.4.3 and getting the same issue - no errors in the console, but when I try and step through the code it fails somewhere in the promise chain without it being handled - can't figure where.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
