### ISSUE TITLE
Debug with Visual Studio Code

### ISSUE THREAD

**Issue by Yosifz8** [popcorntime/popcorntime#1236]
Operating System Version:
Mac OSX 10.15.4

Popcorn Time Version:
Last version

Download date:
29/3/2020

#### Actual Behaviour
I'm trying to debug the application with Visual Studio Code, After run `yarn start` i try to Debug the app with Visual Studio Code and i get this error:
```
/usr/local/bin/node --nolazy --inspect-brk=34766 node_modules/gulp/bin/gulp.js build 
Debugger listening on ws://127.0.0.1:34766/764acb18-ccc5-4e50-afca-331342e9c739
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Branch: development
gulpfile.js:465
Commit: 0adc8c72
gulpfile.js:466
Stylus files compiled in /Users/***/Documents/GitHub/popcorn-desktop/src/app/themes/
gulpfile.js:488
Error: Command failed: npm ls --production=true --parseable=true
gulpfile.js:91
Using v0.44.5 (sdk)
events.js:311
Create cache folder in /Users/***/Documents/GitHub/popcorn-desktop/cache/0.44.5-sdk
events.js:311
Using cache for: osx64
events.js:311
Create release folder in /Users/***/Documents/GitHub/popcorn-desktop/build/Popcorn-Time/osx64
```

Any idea what can be the problem?

**Comment by kiriles90** [comment]
@Yosifz8 does this issue still exist?

**Comment by Persei08** [comment]
`Error: Command failed: npm ls --production=true --parseable=true` can be ignored, the app should still build If you have all the right versions of node, npm and yarn.
