### ISSUE TITLE
Media download doesn't start because of the VPN prompt

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [popcorntime/popcorntime#1237]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.0-0

Download date:
17.03.2020

#### Expected Behaviour
when I disable VPN, I expect the app to start the movie download without further interruption.

#### Actual Behaviour
The app does not start the movie download. I have to hit cancel and try again. It always starts on the second attempt.

#### Steps to reproduce the behaviour

1. Start the app and disable the VPN.
2. Attempt to watch any movie or TV show.
3. Notice that the download doesn't start on the 1st attempt.

I recoreded a video with it. Here it is: https://youtu.be/A4bh01yZGC4

**Comment by debugger89** [comment]
Upvote. The same thing happened to me.

**Comment by HeLiOn--PrImE** [comment]
Same thing happens on the latest version 0.4.1-0.

**Comment by AndreLuisGO** [comment]
Same here. 0.4.1-0

**Comment by team-pct** [comment]
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/ try this version

**Comment by HeLiOn--PrImE** [comment]
@team-pct I just installed it.

Unfortunately, this one seems to be more broken. The download process doesn't start. I don't know if it's a server side issue or not, but regardless of what title I choose, I get the screen you see in the picture.

I figure this may also have something to do with the April fools titles, so I'll try again after I get some sleep and come back with an update in a few hours.

![connecting](https://user-images.githubusercontent.com/10486881/78086636-3b5f2a00-73c7-11ea-96ba-ac3077e46a52.jpg)

**Comment by HeLiOn--PrImE** [comment]
@team-pct back, as promised. The behavior is still the same. The media download doesn't start at all. It gets stuck in that screen.

**Comment by reddo** [comment]
It's probably because the TorrentCache folder does not get created. I am having the same issue, I temporarily fix it by creating the folder manually.

**Comment by team-pct** [comment]
Are you people changing the Temp folder ? can you debug by opening the console
Windows : F12 
and OSX : Cmd+0 ? 
and try start the torrent ?

**Comment by HeLiOn--PrImE** [comment]
@team-pct yes, I have in fact changed the temp folder to a secondary partition, as the main one is a bit limited. I got the following error when I tried to watch Bloodshot.
![image](https://user-images.githubusercontent.com/10486881/78151496-52426280-7441-11ea-818d-9d415542d615.png)

**Comment by team-pct** [comment]
TorrentCache try to create this folder on your new PAth

**Comment by HeLiOn--PrImE** [comment]
@team-pct Worked like a charm. And the download now starts on the first attempt.
So... you can mark this one as solved. Thank you very much! :)

**Comment by reddo** [comment]
The problem persists on each load, the folder gets deleted each time.

**Comment by team-pct** [comment]
Yes i will try to solve this issue once for all just give us time

**Comment by dutchy1001** [comment]
this issue is related to #1221 , the default "Cache Directory" has been changed

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
