### ISSUE TITLE
Movie download speeds are not displayed during playback

### ISSUE THREAD

**Issue by debugger89** [popcorntime/popcorntime#1238]
Operating System Version:
OS X 10.14.6

Popcorn Time Version:
0.4.1

Download date:
29-March-2019 updated from older version to new version

#### Expected Behaviour
The popcorn video should be played right after the play button is clicked and should display the download speeds during the playback.

#### Actual Behaviour
The first attempt is not playing the video and prompting for the VPN. And the next attempt plays the video. 
However, download speeds are not displayed during the play. 
Refer to the below video.
https://youtu.be/Dlt0SyGAEnk 

#### Steps to reproduce the behavior
1. Open the application
2. Click on any movie title on the homepage
3. Select the Butter player for video playback
4. Click Play

**Comment by AndreLuisGO** [comment]
Same herer. Windows 10, 
version 0.4.1

**Comment by team-pct** [comment]
try the version on https://ci.popcorntime.app/job/Popcorn-Time-Desktop/

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
