### ISSUE TITLE
Mac OS Version 5.4 Crashing

### ISSUE THREAD

**Issue by jojobling** [popcorntime/popcorntime#124]
Operating System Version:
OS X 10.11

Popcorn Time Version:
5.4

Download date:
3/27/16
#### Expected Behaviour

I wasn't sure because I am doing it on a computer where lots of stuff is blocked so i was trying a new way to open/download it off of this link https://goo.gl/TXkUMd
#### Actual Behaviour

It kept crashing after I tested out this method and I was wondering if there is any way to fix that
#### Steps to repoduce the behaviour
1. Watch the Youtube video
2. Do what it says

**Comment by VitorVRS** [comment]
Can you inform where did download yout pct?
I guess pct is on version 0.3.9

Can you try to use the latest build?

**Comment by jojobling** [comment]
I downloaded it off the popcorn time website and it said that it was the latest build

**Comment by Breaking1** [comment]
@jojobling Your on the  wrong place, this is for people who download their version from here:

https://popcorntime.sh/

The latest version is 0.3.9.0

I would recommend you to read the last post in the [FAQ](https://www.reddit.com/r/PopCornTime/comments/4bbxw4/popcorn_time_faq/?) thread regarding the version you are using.

Here is a picture that might help you navigate in the PT jungle out there.

https://i.imgur.com/Ul2bD9A.png

**Comment by jojobling** [comment]
Thanks that link worked for me
