### ISSUE TITLE
No subtitles when streaming to DLNA device (Windows)

### ISSUE THREAD

**Issue by aretsmarvin** [popcorntime/popcorntime#1244]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.1

Download date:
3-april-2020

#### Expected Behaviour
Streaming to my Samsung TV (via DLNA) with selected subtitle.

#### Actual Behaviour
Streaming to my Samsung TV (via DLNA) without the selected subtitle (any language)

#### Steps to reproduce the behaviour

1. Search movie.
2. Select subtitle.
3. Select DLNA device.
4. Play movie.

![image](https://user-images.githubusercontent.com/45003967/78360231-c2262980-75b6-11ea-97e9-b1db225f814e.png)

**Comment by BNX070** [comment]
DLNA doesn't support Subtitles. It's not a problem with Popcorn Time. The only possible way of streaming subtitles over DLNA is to hardcode them in the video file.

**Comment by aretsmarvin** [comment]
Are you sure? On the Android version of popcorn time it does work on the same TV with DLNA?
But the Android version doesn't work very well (on my phone?) so I wanted to use the Windows version of popcorn time.

**Comment by osrl** [comment]
>DLNA doesn't support Subtitles. 

It's absolutely wrong.

I can stream the subtitles but I'm here to report that there is no custom sub option for DLNA

I've managed to load a custom subtitle by triggering `subtitle:convert` in `handleSubtitles` method in `streamer.js` instead of downloading a new subtitle. But I thing custom subtitle should be an option before playing the show, like in movies section.

**Comment by aretsmarvin** [comment]
> > DLNA doesn't support Subtitles.
> 
> It's absolutely wrong.
> 
> I can stream the subtitles but I'm here to report that there is no custom sub option for DLNA
> 
> I've managed to load a custom subtitle by triggering `subtitle:convert` in `handleSubtitles` method in `streamer.js` instead of downloading a new subtitle. But I thing custom subtitle should be an option before playing the show, like in movies section.

I don't use custom subtitles. I was talking about the "builtin" subtitle function of popcorntime, which one doesn't stream to the TV using DLNA.

**Comment by osrl** [comment]
Yes I know, I just didn't want to open a new issue. I can stream subs to my Samsung TV(Tizen) successfully on Mac version. But I don't think it's about Windows or Mac.

**Comment by GitHub-gr** [comment]
Streaming to my Samsung TV (via DLNA) with selected subtitle, was working with version Popcorn Time Version:0.3.10 & Windows 7.
Not working with Popcorn Time Version:0.4.4 & Windows 7.

**Comment by Persei08** [comment]
I've already tried that with a samsung TV and it was working as expected.

Can @everyone retry to test with [latest dev build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/) and give new feedback
