### ISSUE TITLE
Playing a dubbed French version instead of English

### ISSUE THREAD

**Issue by Eran1130** [popcorntime/popcorntime#1246]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.3-0

Download date:
1hour ago

#### Expected Behaviour
Play 'star wars: the clone wars' normally -> spoken in English

#### Actual Behaviour
Play it dubbed in French I don't know why I don't speak French and I don't live in France.
All my settings are in English so I don't understand why it's doing this.
...

**Comment by gladykov** [comment]
It is not issue with the app, but with source of torrents.

**Comment by Persei08** [comment]
Probably a torrent with multiple audio tracks and the default one is french.

Try to play in VLC and see if you can switch audio track and find the english one.

**Comment by kiriles90** [comment]
@Persei08 not an actual Popcorn Time issue, close please?
