### ISSUE TITLE
OSX v0.4.0 v0.4.1 v0.4.2 v0.4.3 incompatible with 10.9.5

### ISSUE THREAD

**Issue by juanpc2018** [popcorntime/popcorntime#1247]
Operating System Version:
OSX 10.9.5 Maveriks

Popcorn Time Version:
v0.4.0
v0.4.1
v0.4.2
v0.4.3

Installer Works,
Web page says 10.7 or better.
but .app is Incompatible "Requires 10.10 or later"

cannot test older/legacy, uncompiled.
https://github.com/popcorn-official/popcorn-desktop/archive/v0.3.9-flatpak0-a.zip
https://github.com/popcorn-official/popcorn-desktop/archive/v0.3.9-a.zip
https://github.com/popcorn-official/popcorn-desktop/archive/0.3.10.zip
https://github.com/popcorn-official/popcorn-desktop/archive/untagged-d9bddbb5aa7d198e5807.zip
https://github.com/popcorn-official/popcorn-desktop/archive/untagged-c2e34cd5641375ce75d5.zip
https://github.com/popcorn-official/popcorn-desktop-legacy/releases

Maveriks still used by lots of people, specially owners of ProToolsHD10.3.10

Latest Firefox Works. v74.0
Opera 49.0.2725.64
Chrome 67.0.3396.79 (Official Build) (64-bit)

some video player use ffmpeg others do Not,
some video players are incompatible with latest FireFox "do Not have sound".
but play ok in Chrome, or Opera.
and vise versa, videos that do Not play in Chrome or Opera play Ok in Firefox.
Firefox is almost perfect.
but lacks features of Opera like WhatsApp, Telegram, etc...

to install Maveriks needs to change CPU clock/date a few years back, All OSX installers have a time bomb.
https://en.wikipedia.org/wiki/OS_X_Mavericks

i have a MacPro5,1 2010
and another hdd, with Mojave 10.14.6
BUT... im locked out...
Mojave changes hhd & ssd to APFS,
and i have a Metal compatible video card **without** boot screen, GTX Titan 6GB
cannot see APFS drive from Maveriks to change Boot drive in System Preferences,
and cannot see Bootscreen to change Boot OSX.

Paragon had discontinued "free" APFS driver but were only 10.10 or later.
HighSierra 10.13.6 only changed SSD to APFS, but HDDs were left untouched HFS+
i did the mistake of upgrading to Mojave without cloning HighSierra to another HDD.

**Comment by kiriles90** [comment]
@Persei08 maybe close this? I dont think its something that can be fixed without rolling back nwjs
