### ISSUE TITLE
Chromecast issue

### ISSUE THREAD

**Issue by mirko506** [popcorntime/popcorntime#125]
Operating System Version: Windows 7

Popcorn Time Version: Desktop Beta 5.4

Download date: 27/3/2016
#### Expected Behaviour

1) Subtitles should appear correctly in my TV screen when using popcorn -> Chromecast streaming option. 
2) There should be a setting where I can select the size of the subtitles for the Chromecast option (and it's position) 
3) Subtitle size and position does not match popcorp-desktop vs popcorn - Chromecast option.
...
#### Actual Behaviour

When streaming a movie from popcorn-desktop app to my TV using the Chromecast option, subtitles are cut in half, making them unreadable.
#### Steps to repoduce the behaviour

1. Install Windows 7 (lol)
2. Download the popcorn-desktop app from http://popcorn-time.to/ and run it
3. Select any movie (Batman: Bad Blood.. just because...)
4. Connect the Chromecast to your TV
5. Play the movie
6. Click on the "Chromecast" icon at the bottom right
7. Select "Español" subtitles... 
8. Wait until you can see the Movie playing in the TV, and see how the subtitles are cut in half

**Comment by Breaking1** [comment]
Your on the  wrong place, this is for people who download their version from here:

https://popcorntime.sh/

The latest version is 0.3.9.0.

I would recommend you to read the last post in the [FAQ](https://www.reddit.com/r/PopCornTime/comments/4bbxw4/popcorn_time_faq/?) thread regarding the version you are using.

Here is a picture that might help you navigate in the PT jungle out there.

https://i.imgur.com/Ul2bD9A.png

**Comment by mirko506** [comment]
My bad! Sorry about that... Thanks for pointing me in the right direction!

I'll install the right version of the application and I will test again to check is the issue persist :)

**Comment by mirko506** [comment]
Using:
- Windows 7
- popcorn-desktop version 3.9 (from https://popcorntime.sh/)

When playing a movie I don't see the Chromecast button anywhere.

What am I missing @Breaking1 ?

**Comment by Breaking1** [comment]
You will find it in the players menu. Right next to the watch now button you will see a little arrow, press it and all your available players will show.

If you have any special characters in the Chromecast name like an apostrophe or something, remove it because it can cause some issues with Chromecast not showing up in the players menu.

To get subtitles on TV shows you need to set a default one in settings, for movies just select one before pressing the watch now button.

A simpel restart of popcorntime(F11 in Windows) will often do the trick of your Chromecast doesn't show up in the players menu.

If you can't get it to show some people has solved it by doing a factory reset or  installing their Chromecast and the Chromecast extensions again.

**Comment by nakp** [comment]
I can confirm this is the actual behavior with the _real_ popcorntime, I have tested the latest version (from the CI) as well in Windows and OSX.

Mine is 0.3.9-0 (80e3fc19)

As another app has the same issues, I suspect it has to do with one of the npm packages

**Comment by Breaking1** [comment]
Correct, there was nothing wrong with the issue in itself. He was just using the wrong version to report it here.

**Comment by bsphere** [comment]
I think its a Chromecast firmware issue - https://productforums.google.com/forum/?hl=da#!topic/chromecast/Qe76EGhzlII;context-place=forum/chromecast

**Comment by Breaking1** [comment]
@bsphere  i think so to, after my CC updated the problem disappeared.

**Comment by bsphere** [comment]
actually that bug discussion is related to the latest Chromecast firmware..

**Comment by Eliams0** [comment]
When using [chromecast windows 10](https://appuals.com/stream-popcorn-time-to-chromecast-on-windows/), sometimes you might face issues with the computer’s firewall settings. You will have to configure these settings by going to Control Panel and select Windows Firewall from System and Security. At the top left side you need to allow an app or feature through Windows Firewall. Now you need to click the change settings. If prompted you will have to provide your username, with administrator privileges, and its password. Scroll down to find the Popcorn Time in the alphabetically sorted list of apps. Check the Private and Public boxes. I hope this helps you out.
