### ISSUE TITLE
Not playing custom Torrent files....

### ISSUE THREAD

**Issue by BNX070** [popcorntime/popcorntime#1250]
Operating System Version:

Windows 10
Popcorn Time Version:

0.4.3-0
Download date:

4/4/2020
#### Expected Behaviour

...Play a torrent file downloaded seperately.

#### Actual Behaviour

...Stuck on resolving. Torrent file works fine as tried on a different program.

#### Steps to reproduce the behaviour

1. ...Download a torrent file for movie/series
2. ...Drag onto Popcorn Time
3. ...Will be stuck on resolving....

**Comment by kiriles90** [comment]
To me it looks like its https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L166 that causes it.
When drag&dropping a .torrent it returns an error and `infoHash` remains blank so https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L185 tries to open the `../Torrentcache/` dir like if it was a file and it EISDIR's, ..while it normally returns the hash (and `infoHash` becomes that) when drag&dropping a magnet link so L185 works and those dont get stuck on resolving.

No idea how to correctly fix it though..

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/7dbe9f117887de8d0aa3c2ab55c87350e42a7ad3 fixed it and https://github.com/popcorn-official/popcorn-desktop/commit/84f99e746853510c1decab559a30eacf1f7e30ba removed the fix. 

@team-pct any insight on this?

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/89d26bf16201858923ec7ca0397bb00c9b113fca fixed it again

@Axe090  close this when you can?

**Comment by Axe090** [comment]
> [89d26bf](https://github.com/popcorn-official/popcorn-desktop/commit/89d26bf16201858923ec7ca0397bb00c9b113fca) fixed it again
> 
> @Axe090 close this when you can?

Sorry bro, not fixed. Did a clean install of the latest version as well. Stuck on resolving, tried multiple torrents.......

**Comment by Axe090** [comment]
It's also giving me "Error resolving torrent" for some files

**Comment by BNX070** [comment]
> [89d26bf](https://github.com/popcorn-official/popcorn-desktop/commit/89d26bf16201858923ec7ca0397bb00c9b113fca) fixed it again
> 
> @Axe090 close this when you can?

I installed the x32 version on a different drive and now it gets up till connecting but is stuck there. (Note I'm on x64 bit win and was using x64 ver before)
