### ISSUE TITLE
PopcornTime 4.3.0 - Many broken features... Tutorial inside on how to revert to the best PT version and remove the auto-updater and popup.

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1251]
Things that were working and were available in very old development builds are not in the newest version, which frankly looks like one of the many popcorntime ripoffs, especially with all the VPN shilling. Build 293 had categories for languages so when OpenSubs spits out a bunch of subtitle versions, you could select the one for the proper release. Default subtitle setting also doesn't work.

Guess I'm going back to the development build 293. Damn, I should've saved my database before updating... Still no saving of watched items on update huh?

PS: What's up with the huge ass minimize/expand/close buttons?

Overall a very low effort update that doesn't add anything useful, deletes your history and breaks existing features. I guess the VPN plug works well tho...

Edit: Oh wow, custom torrents don't load and you cannot save them like before, talk about development failure... 

> Superior version: 
> 00000
> 
> Delete everything from you Popcorn-Time folder and replace with this ^ all of the features that we know and love are there and there aren't any VPN annoyances.
> 
> Since the developers are really money hungry and push their crappy update with the VPN scare tactics even if you don't want it, giving you a pop-up and launching the installer when you exit the program. Add this to your hosts file and both of these issues will be solved.
> 
> 0.0.0.0 popcorntime.app
>
> Alternatively, just close the popup and installer everytime you open PopcornTime.

**Comment by ghost** [comment]
Leaving this for the people that want to do this manually or download the Linux build, you can get the lazy Windows version from above.

> For anyone that wants build 293, a much much better version of popcorntime:
> 
> ---- (Dev builds here, because for some reason the devs removed them from the official website)
> 
> As you can see the dev build 293 is the linux version, to use with windows:
> 
> Install the windows version of Beta 0.3.10 (from the Mega link) and then:
> 
> Open the file (build 293) with 7zip and extract only:
> 
> node_modules\
> src\
> .git.json
> icudtl.dat
> nacl_irt_x86_64.nexe
> natives_blob.bin
> nw_100_percent.pak
> nw_200_percent.pak
> package.json
> 
> Put those files in your popcorntime folder and voila you have build 293 for Windows.
> 
> I recommend deleting those same files and folders from your popcorntime folder first before you move in the new ones, since Windows takes its sweet time comparing each of them and there's thousands of files so it would take a while, if you delete them first it only takes a minute to copy them over.
> 
> Edit: Since the developers are really money hungry and push their crappy update with the VPN scare tactics even if you don't want it, giving you a pop-up and launching the installer when you exit the program. Add this to your hosts file and both of these issues will be solved.
> 
> 0.0.0.0 popcorntime.app

**Comment by team-pct** [comment]
Just Send Pull Request and stop sharing external LINks this is not how open source project work

**Comment by AcharyaOne** [comment]
the mega link file was an installer? where do i get build 293 files?
edit: i realize everything is in your megadownload link. I also don't understand why those versions were removed.

"Build 293 had categories for languages so when OpenSubs spits out a bunch of subtitle versions, you could select the one for the proper release. "

After installing following your directions I can't seem to find those options, to be fair I have never seen that possibility and that would be awesome because many times the default subtitle isn't appropriate. Default subtitles aren't working either.

I came to this thread because popcorn time updated by itself and broke everything.

edit: seems there is a problem on opensubtitles itself therefore can't test it yet

**Comment by AcharyaOne** [comment]
Opensubtitles is up again and it works but I have a problem, portuguese subtitles aren't loaded on version 293, i think it's because wrong language code, not sure if i can fix it

edit: more specifically, pt-br subtitles aren't loaded when there is no pt subtitles
