### ISSUE TITLE
No aparecen idiomas de los subtitulos

### ISSUE THREAD

**Issue by hdalforno** [popcorntime/popcorntime#1253]
Operating System Version:
windows 8

Popcorn Time Version:
4.3

Download date:
4 april 2020

#### Expected Behaviour

...

#### Actual Behaviour
no aparecen los idiomas para subtitulos
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Dupe https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in dev build 407

**Comment by dutchy1001** [comment]
Fix explained in #1318

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
