### ISSUE TITLE
Does not connect with OpenSubtitles

### ISSUE THREAD

**Issue by martinkluck** [popcorntime/popcorntime#1254]
Operating System Version:
Windows 10 Pro

Popcorn Time Version:
0.4.3

Download date:

#### Expected Behaviour
Connecting to OpenSubtitles
...

#### Actual Behaviour
Does not connect with OpenSubtitles
...

#### Steps to reproduce the behaviour

1. Go to app settings
2. Scroll to OpenSubtitles
3. Try to connect

**Comment by kiriles90** [comment]
Dupeplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in dev build 407 (https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/)

**Comment by martinkluck** [comment]
OpenSubtitles.login(...).then(...).delay is not a function

**Comment by kiriles90** [comment]
@martinkluck Install build 407, I've linked it above. Its already fixed.  
0.4.3 that you are using is build 406

**Comment by martinkluck** [comment]
![image](https://user-images.githubusercontent.com/7407717/78674529-1fbdbd00-78ba-11ea-8b41-65a12f18ab04.png)

**Comment by kiriles90** [comment]
Is that build 407?
You are still not getting authorized. Did you use an opensubtitles.org account? (not .com)

**Comment by martinkluck** [comment]
Is build 407 and this error is when the app try to get subtitle for a movie and i not login in opensubtitles

**Comment by kiriles90** [comment]
Make an account in opensubtitles.org then login in Popcorn Time settings
(you need build 407 for all this, in older builds there is a bug in the login)

**Comment by martinkluck** [comment]
Ok, that works, but please in app for this changes in opensubtitles.org policity add a redirect for de movie detail view to form in settings and add a link to register or form to register there in settings. Thanks!
