### ISSUE TITLE
none subtitles at all

### ISSUE THREAD

**Issue by misumma** [popcorntime/popcorntime#1261]
Operating System Version:
OS X 10
Popcorn Time Version:
 0.43
Download date:
05.04.2020
#### Expected Behaviour
show subtitles
#### Actual Behaviour
none in the list
#### Steps to reproduce the behavior

1. ...after first install, in the time of the first movie, the subs disappear
2. ...since I reinstall the app but none of subs appear ...

![New Bitmap Image](https://user-images.githubusercontent.com/43290464/78472579-c0896c80-7742-11ea-8173-539816947c01.png)

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by MBEyes** [comment]
I am having the same problem. I've already registered in the OpenSubtitles site, the email was actived. I tried to log in on popcorn and it was eternal waiting...

**Comment by team-pct** [comment]
Did you tried https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/ ?

**Comment by misumma** [comment]
> Duplicate #1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/
> 
> (you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

I did that,                                 dont work.
idid the post  #1252                dont work.

I did a double check in settings/subtitles/default subtitle a language and it work!!! (i saw that somewere)

Thanks and regards

**Comment by annyag** [comment]
> I did a double check in settings/subtitles/default subtitle a language and it work!!! (i saw that somewere)

How exactly did you do this? I've tried the 1252 instructions too and did not worked! I'm desperate!

**Comment by misumma** [comment]
You must put a language in settings/subtitles/default subtitle and repeat that.
 In movie you won't see the subtitle by default, but if you click on subtitle and wait for seconds, the flags for available subtitles will appear.
