### ISSUE TITLE
problems with the subtitles

### ISSUE THREAD

**Issue by pietrabarreto** [popcorntime/popcorntime#1265]
the subtitles aren't opening
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ghost** [comment]
And for me the same problem!

**Comment by iquecoellho** [comment]
for me too

**Comment by ycristan** [comment]
Sad. After the update many features no longer work. Subtitles are the ones that most impact the use of the system ... Another problem is the TV stream, which doesn't work anymore either ...

**Comment by Jany-M** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/1252

**Comment by kobeljacky** [comment]
problems with the subitlesssssss

**Comment by Persei08** [comment]
Please before creating new issue search if it don't already exist.

Duplicate of #1252
