### ISSUE TITLE
[Feature Request] Option to hide watched films

### ISSUE THREAD

**Issue by pcriadoperez** [popcorntime/popcorntime#1267]
I love popcorn, and gone through a lot of the popular movie list, to the point where most movies I've seen. It would be great to have a feature to hide those movies already seen.

What do you think?

**Comment by kiriles90** [comment]
Settings > Show advanced settings > Watched Items -> Hide

**Comment by pcriadoperez** [comment]
had to update popcorn and worked! You are all amazing, thanks!
