### ISSUE TITLE
all the movies and series lost sub titles. When they will be fixed?

### ISSUE THREAD

**Issue by nunocatorze** [popcorntime/popcorntime#1269]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Please read through the issue list to find multiple issues about this. Keep making new posts doesnt help this.

**Comment by jurly5** [comment]
Me too for 3 days. I tried to figure out but seem, I couldn't find how to figure out that subtitle return?

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment]
Duplicate of #1252
