### ISSUE TITLE
Popcorntime doesn't seem to obey connection limit

### ISSUE THREAD

**Issue by diwu1989** [popcorntime/popcorntime#1271]
Operating System Version:
Windows

Popcorn Time Version:
4.1

Download date:
3/21/2020

#### Expected Behaviour
Setting connection limit to 5 should restrict popcorn to talk to 5 peers at most.

#### Actual Behaviour
My router still get overloaded and I see Popcorntime issuing connections to dozens of peer IP

#### Steps to reproduce the behaviour
Use Windows Resource Monitor to look at the active network connections that Popcorn sends and receive data over when streaming.

It's well in excess of the connection limit set in the settings page.
As an extreme example, set the connection limit to 1 for testing.

This is a problem because my upload link is very easily saturated and my entire home network becomes unstable whenever streaming with Popcorntime.

The webtorrent default conn per torrent is 55, which is much too high because Popcorn could be seeding multiple torrents in the background. Please consider changing the default conn limit to something like 5.

Please also limit torrent seeding to only 1 at a time, otherwise, multiple background seeding will also quickly saturate the home network.

**Comment by Persei08** [comment]
5 is too low, you will have issue downloading the video at a good enough speed.

I think it is more probably something with the upload or DHT.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
