### ISSUE TITLE
LEGENDAS AUSENTES

### ISSUE THREAD

**Issue by rdisystem** [popcorntime/popcorntime#1272]
A nova versão do Popcorn Time não funciona direito, os filmes não são todos exibidos, as legendas nao aparecem !!!

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by rdisystem** [comment]
Não preciso de VPN, nunca precisei ! E tem outro defeito, o programa não
tem opção de SAIR !!

 O [x] NÃO FECHA MAIS A janela !!!

*Reginaldo*

*Projetos de **Produtos e In**teriores*

*Imóveis na Planta*


*http://www.r3dprojetos.com <http://www.r3dprojetos.com/>*https://w
<https://sites.google.com/creci.org.br/imoveis-na-planta/p%C3%A1gina-inicial>
ww.imoveisnovoseusados.com

*[11] 9-8390-0197 -  Nextel - (Whatsapp)*

*[11] 9-4151-2782  - Vivo*






Em ter., 7 de abr. de 2020 às 03:50, kiriles90 <notifications@github.com>
escreveu:

**Comment by kiriles90** [comment]
No habla espanol

**Comment by rdisystem** [comment]
OK, THEN

I don't need a VPN, I never did! And there is another defect, the program
has no option to EXIT !!

  [X] DOES NOT CLOSE THE WINDOW !!!

*Reginaldo*

*Projetos de **Produtos e In**teriores*

*Imóveis na Planta*


*http://www.r3dprojetos.com <http://www.r3dprojetos.com/>*https://w
<https://sites.google.com/creci.org.br/imoveis-na-planta/p%C3%A1gina-inicial>
ww.imoveisnovoseusados.com

*[11] 9-8390-0197 -  Nextel - (Whatsapp)*

*[11] 9-4151-2782  - Vivo*






Em ter., 7 de abr. de 2020 às 15:16, kiriles90 <notifications@github.com>
escreveu:

**Comment by kiriles90** [comment]
> I don't need a VPN, I never did!

Go in the settings and uncheck the 'VPN' checkbox. It will disable that ad permanently.  

> the program has no option to EXIT !!

Yes this is a bug, it will be fixed in a newer version for now force close it or use whatever other workaround works for you

**Comment by cinntia** [comment]
nao consigo ver as legendas. funcionou bem ate semana passada e de repente a legenda sumiu.

**Comment by kiriles90** [comment]
@cinntia check #1252

**Comment by rdisystem** [comment]
Ok, I disabled VPN, but now the menus don't load anymore, movies and series
🙆

*Reginaldo*

*Projetos de **Produtos e In**teriores*

*Imóveis na Planta*


*http://www.r3dprojetos.com <http://www.r3dprojetos.com/>*https://w
<https://sites.google.com/creci.org.br/imoveis-na-planta/p%C3%A1gina-inicial>
ww.imoveisnovoseusados.com

*[11] 9-8390-0197 -  Nextel - (Whatsapp)*

*[11] 9-4151-2782  - Vivo*






Em qua., 8 de abr. de 2020 às 03:25, kiriles90 <notifications@github.com>
escreveu:

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
