### ISSUE TITLE
[ISSUE] Magnet links no longer working (4k content)

### ISSUE THREAD

**Issue by JacopoV** [popcorntime/popcorntime#1274]
Operating System Version:
OSX 10.14 / Macbook Air i5 Mid 2012

Popcorn Time Version:
4.3, dev build 407

Download date:
April 6th

#### Expected Behaviour
Copying and paste torrent magnet links inside Popcorn for a 4k movie, should prompt the interface to pick the content and the device to stream to. Once decided, start streaming.

#### Actual Behaviour
Copying and paste torrent magnet links inside Popcorn for a 4k movie, it prompts, correctly, the interface to pick the content and the device to stream to. Once decided the streaming device (popcorn itself for example) the download won't start. 
Instead it hangs forever showing the label "connecting...". 
For reference, PopcornTime 3.10 it starts buffering pretty fast, almost immediately.

#### Steps to reproduce the behaviour

1. Retrieve a 4K movie (well shared)
2. Copy the magnet link
3. Paste into PopcornTime App
4. Select the file to be streamed
5. Notice that shows "Connecting"
6. From now and how the "Connecting" label will stay without proceeding.

**Comment by annyag** [comment]
Have this issue for all magnet link.

**Comment by JacopoV** [comment]
Yeah you're correct. Even 720-1080 won't load

**Comment by kiriles90** [comment]
To me it looks like its https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L122 that causes it. If you quote out this line it works every time, no more stuck on 'connecting'. But ofc this causes other problems elsewhere down the line so I'm not really sure how to correctly fix it or the exact reason why `this.torrent.destroy();` became https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L119-L127 with https://github.com/popcorn-official/popcorn-desktop/commit/84f99e746853510c1decab559a30eacf1f7e30ba

Just leaving this info here in case it motivates someone more knowledgeable to fix it :)

**Comment by team-pct** [comment]
Will take a look into that and fix it asap

**Comment by JacopoV** [comment]
@team-pct sorry to bother you :) did you get any chance to look into? the latest builds are pretty solid and it would be awesome to have the external magnets working back again :) thanks a lot... i really appreciate you work 👍

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
