### ISSUE TITLE
No subtitles at all, #1252 do not resolve the problem

### ISSUE THREAD

**Issue by annyag** [popcorntime/popcorntime#1275]
Operating System Version:
Windows 10

Popcorn Time Version:
Build 407

Download date:
latest version installed April 6th

#### Actual Behaviour

... Not possible to select a language for subtitles, because none is displayed and not possible to load a custom subtitles 

#### Steps to reproduce the behaviour

1. ...Load a show or movie
2. ... Try to select a subtitles
3. ...and fail

I've tried de #1252 solution, didn't work! So is there something else to try? 

P.S: I love this app! But with no subtitles at all is hard to have a good experience!

**Comment by kiriles90** [comment]
Not really. The issue is that opensubtitles now requires to login and that Popcorn Time's login in the settings was broken until build #407. You can either **a)** manually edit settings.js **b)** fix your older version and login from the settings, or if both of the above sound confusing and you have no attachment to an older version **c)** clean(!) install #407 and just login from the settings.  

If nothing works start a movie, pause it, press F12 go to console, and check for any errors and paste them here so we can maybe see what the issue is and it doesnt work for you while it works for everyone else.

**Comment by annyag** [comment]
> Oh and the credentials must be for opensubtitles.org

It wasn't working because I was forcing the login of the wrong credentials! Was a account from opensubtitles.com. With a new clean install and the correct account credentials is working fine.
Thanks for the patience!

**Comment by kbourro** [comment]
Connected with opensubtitles but I still have the same issue. 
I tried complete uninstall and install again but nothing.
![image](https://user-images.githubusercontent.com/40888336/78706483-d4d29280-7917-11ea-8252-67999488cf48.jpg)

**Comment by edik06** [comment]
![image](https://user-images.githubusercontent.com/63171130/78710927-d18ed500-791e-11ea-802e-bb184989a12c.png
only english sub when streming to TV

**Comment by kiriles90** [comment]
@kbourro UPDATE TO BUILD 407 (https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/) THEN CONNECT TO OPENSUBTITLES.ORG FROM THE SETTINGS.

I write it in every single comment guys but none seems to care, its like you read 1 every 3 words..

**Comment by kiriles90** [comment]
@edit06 We need a screenshot of the error in the 'Console' tab. Also make sure you updated to build 407, logged in to opensubtitles.org in the settings, and selected a default subtitle language (also in the settings)

**Comment by fabiofragoso** [comment]
ERROR] subtitleProvider.fetch() Error: 401 Unauthorized
    at (DISK)\Popcorn Time\Popcorn-Time\node_modules\opensubtitles-api\index.js:58:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
win.error @ app.js:36
(anonymous) @ streamer.js:599
processTicksAndRejections @ internal/process/task_queues.js:97

Account from opensubtitles.org, connected at the settings, language selected, but still not working.
Oh, and freshly downloaded and installed 4.3 version.

![image](https://user-images.githubusercontent.com/44402364/78838836-6819cf80-79cd-11ea-9c9a-a5aad18006fc.png)

**Comment by kiriles90** [comment]
@fabiofragoso UPDATE TO BUILD 407 (https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/) THEN CONNECT TO OPENSUBTITLES.ORG FROM THE SETTINGS. None even reads it even if its the exact comment above you?

**Comment by dutchy1001** [comment]
Build 407 still wont add the OpenSubtitles.org login details into the settings.js and need to be done manual as explained in #1252 . This has been mentioned in previous post but not been read properly I guess.
Just tested this  before posting

**Comment by kiriles90** [comment]
Test again @dutchy1001 Build 407 works without editing the settings.js. Its confirmed many times by many people. The fix was https://github.com/popcorn-official/popcorn-desktop/commit/e0beb97881181da0d4c3ccc4127376992840ced6 and its only present in 407 (not 0.4.3, thats build 406)

**Comment by dutchy1001** [comment]
I just woke up (no coffee yet) so i can say the testing was not as precise as I normally do. It works for me now (as it already did before).
