### ISSUE TITLE
Worst ever Update: you guys ruined it !! Sorry

### ISSUE THREAD

**Issue by iMansoorAliKhan** [popcorntime/popcorntime#1277]
Operating System Version:

MAC high sierra
Popcorn Time Version:

4.2
Download date:

1 week since the release
#### Expected Behaviour

...

Just like the version 3.9 was smooth stable good in finding movie seeds and good speed. 
#### Actual Behaviour

...

download button next to watch is dead: this don't do anything
![image](https://user-images.githubusercontent.com/11312949/78649120-70dbaa00-78d6-11ea-9fd2-29b04181eec7.png)

lesser health and torrent health compared to 3.9

first time click on watch now do nothing, then 3ndtime notihng

then click on movie twice nothing happens and then 3rd time click on the episode video title actually start buffering it

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...ada

**Comment by hetzbh** [comment]
It's not related specifically to mac. In version 0.4.x - the download button has been removed.

If you just want to download an episode, then make sure you have a torrent client installed and configured, and simply click the magnet link (the U in the upper right) and it will launch your torrent client and download the content.

**Comment by hetzbh** [comment]
looks like it was fixed in 0.4.3

**Comment by Persei08** [comment]
I'm closing this. Change the title for something more helpful. Being bitter don't fix things quicker
