### ISSUE TITLE
No option to stream to smart TV

### ISSUE THREAD

**Issue by p-mannn** [popcorntime/popcorntime#1278]
Operating System Version: OS Catalina 10.15.4
Popcorn Time Version: 0.4.3
Download date: 07/04/20

#### Expected Behaviour

Drop down arrow next to "watch now" usually displays my LG TV as an option to stream to (no chrome cast or anything, just the TV)

#### Actual Behaviour

The option for the TV has disappeared. VLC and Butter still show as normal. 

I have tried deleting and reinstalling PT. Also tried turning the wifi off and back on from my laptop and tv. Restarted both TV and laptop.

#### Steps to reproduce the behaviour

Happens every time.

**Comment by kiriles90** [comment]
@Persei08 duplicate issue, close please

**Comment by p-mannn** [comment]
Where is the thread for the duplicate issue?

**Comment by kiriles90** [comment]
@p-mannn Basically DLNA to LG works fine. Its something with your network. Try updating to the latest build from ci.popcorntime.app (437 at the moment) and if it still doesnt detect it, if you use a VPN try turning it off, start Popcorn Time so it detects your device, then turn the VPN back on and stream what you want.

**Comment by p-mannn** [comment]
I deleted the previous one I had, downloaded the new version from the website you advised but I still have the same issue, only popcorn time and VLC are coming up as the options for watching. VPN is off. Any other suggestions?

**Comment by kiriles90** [comment]
Something network related? Does anything else detect your TV? Check the console log (F12) and link any errors if there are any.

**Comment by p-mannn** [comment]
No errors come up, they're all just listed as "info". When it scans for external players including DLNA devices, all it comes up with as an external player is VLC (see below). My TV is linked up to my network and it has been used before to stream directly to the tv...

[INFO] Scanning: Local Network for Airplay devices
app.js:17 [INFO] Scanning: Local Network for DLNA devices
app.js:17 [INFO] Scanning: Local Network for Chromecast devices
app.js:17 [INFO] Scanning: /usr/bin
app.js:17 [INFO] Scanning: /usr/local/bin
app.js:17 [INFO] Scanning: /Applications
app.js:17 [INFO] Scanning: /Users/p/Applications
app.js:17 [INFO] Found External Player: VLC in /Applications/VLC.app/Contents/MacOS
app.js:17 [INFO] External Players: scan finished

**Comment by kiriles90** [comment]
So the scanning starts but just doesnt find anything. 
If a clean install doesnt fix it, it mostly seems like a network issue to me.
