### ISSUE TITLE
Missing Episodes

### ISSUE THREAD

**Issue by ElioseFin** [popcorntime/popcorntime#1279]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Due to the enormous amount of info the OP has given us you devs should drop all your other work and fix this for him/her in great speed.

If any dev can close issue's, this would be the one to do so.
