### ISSUE TITLE
Popcorn time wont close

### ISSUE THREAD

**Issue by Arizona-dev** [popcorntime/popcorntime#1280]
Operating System Version:
Windows 10 latest update

Popcorn Time Version:
0.4.3-0

Download date:
07/04/2020

#### Expected Behaviour
when clicking close button or alt-f4, it won't close, so I have to close it from taskmanager.

#### Actual Behaviour
Not closing

#### Steps to reproduce the behaviour

1. Installed new update from the app
2. launch the app
3. downloaded a movie
4. stopped the download
5. Click red cross button

**Comment by reddo** [comment]
This is also happening for me

**Comment by edik06** [comment]
yes me to

**Comment by VladimiroPaschali** [comment]
You can "fix" it by disabling the "Clear tmp folder after closing app" in the Cache directory settings, but you will have to manually delete the downloaded files every now and then

**Comment by Simsan** [comment]
same to me.

**Comment by maryanabeatriz** [comment]
it's happening to me too

**Comment by Persei08** [comment]
Can you all confirm that you use windows too ?

Also if some of you can copy-paste console output (F12 key > "console" tab) when the issue happen, it can be useful

**Comment by JavierLopezBravo** [comment]
![imagen](https://user-images.githubusercontent.com/46054179/79117554-bba06a80-7d8b-11ea-9ae8-803a78fc4324.png)

This is the console output

**Comment by Jany-M** [comment]
Also on `0.4.4`

**Comment by Persei08** [comment]
Yep issue is confirmed. 
It happen because PT encounter issue when trying to delete the cache, on exit.

Like @vlod98 pointed, you can disable "Clear Tmp folder when app exit" in settings as a workaround, but you will have to delete it yourself.. if you really want

**Comment by elitonfilho** [comment]
Same problem on 0.4.7, flushing the cache in settings solves it

**Comment by JavierLopezBravo** [comment]
> 
> 
> ![imagen](https://user-images.githubusercontent.com/46054179/79117554-bba06a80-7d8b-11ea-9ae8-803a78fc4324.png)
> 
> This is the console output

As you can see, the issue is caused by the **_rmdir_** command not being able to delete a non-empty directory. I think you should use _**rmdir "directory name" /s /q**_ instead

**Comment by Mitezuss** [comment]
This problem is because the download/upload do not stop when you cancel (press X) a movie/serie/... so, on the temporary directory, the file keep "sharing" and blocked.

One solution is do not delete if the file is opened/in use, and just close (end the app) and delete after new start.

*************

Temporary solution, open and edit:

src\app\app.js

> 
> var deleteFolder = function (path) {
>   try {
>     rimraf.sync(path);
>   } catch (e) {
>   }
> };

**Comment by zephuros-droid** [comment]
Same problem on Windows 10, version 1909.

**Comment by PollutionMAN** [comment]
same problem for me windows 10 1909 latest on popcorn time 0.4.4

**Comment by dutchy1001** [comment]
This should be fixed in build 415, get it from **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/415/)**

**Comment by Persei08** [comment]
dev build 415 don't fix it. Check my comment here: https://github.com/popcorn-official/popcorn-desktop/pull/1369#issuecomment-616189121

**Comment by dutchy1001** [comment]
I looked at the changes of build 415
 "Update DeleteFolder / Fix bug when changing TMPfolder"
I presumed it was fixed this way, sorry about the misunderstanding.

**Comment by PollutionMAN** [comment]
> This should be fixed in build 415, get it from **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/415/)**

not fixed in this version too , problem is still there

**Comment by Persei08** [comment]
415, 416 ?

**Comment by amberphoenix** [comment]
same here, I can reproduce it everytime, also exists in version 0.4.4

**Comment by ze0ss** [comment]
same for me, windows 10, 0.4.4-beta

**Comment by Persei08** [comment]
I pin this issue in hope it will reduce the number of duplicate reports

**Comment by afonsosantos** [comment]
Hi, any ETA for this issue to be solved?
Thank you!

**Comment by Arizona-dev** [comment]
Issue still not fixed.

Le jeu. 30 avr. 2020 à 01:03, Afonso Santos <notifications@github.com> a
écrit :

**Comment by Persei08** [comment]
I just tried (windows 10 - build 423), for me it works.

Can you guys tell us which build number you use, because it should be fixed since build ~417~ 416.

**Comment by linchiyu** [comment]
I noticed that if you go to the "Seedbox" and delete all the entries there, it will exit the program normally.
So maybe this might be an approach to solve this issue temporarily.
On exit > delete all seedbox entries > exit

**Comment by Persei08** [comment]
@Arizona-dev @linchiyu This issue should be already fixed since dev build 416.

Have you tried the latest dev builds ? https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastStableBuild/.

**Comment by dsnvwlmnt** [comment]
> I just tried (windows 10 - build 423), for me it works.
> 
> Can you guys tell us which build number you use, because it should be fixed since build ~417~ 416.

2007344

![image](https://user-images.githubusercontent.com/14173022/83079462-c1e36100-a030-11ea-9cd2-bce672bf0308.png)

**Comment by Jany-M** [comment]
Yep latest stable build works for me too.

**Comment by Persei08** [comment]
@Jany-M  You mean dev build, right ? Because latest stable (project still in beta in reality) build is 0.4.4 (=dev build 412)

**Comment by Jany-M** [comment]
Yes, sorry didn't specify that.
I've always updated by checking manually the successful dev builds, since the app actually gets updated quite rarely, while the dev releases are relatively frequent. 
[Latest one here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/).

**Comment by Persei08** [comment]
Ok, thx

**Comment by linchiyu** [comment]
Hi, reopening this bug. I installed the latest version.
Now what happens is:
-if you are using the software and then closes it, it closes normally
-but if finished watching something, then leave it open for a while, then tries to close it, it doesn't close

Then I tried to delete the entries in the seedbox, but nothing happens (it doesn't delete).

Edit: by the way, I'm a Windows user.

**Comment by Persei08** [comment]
>-but if finished whatching something, then leave it open for a while, then tries to close it, it doesn't close
>
>Then I tried to delete the entries in the seedbox, but nothing happens (it doesn't delete).

Like it totally freeze ?

**Comment by linchiyu** [comment]
No, just nothing happens when you click on Close or on delete in the seedbox. I can still navigate and the rest just still works normally, even after clicking.

**Comment by sheepdestroyer** [comment]
I'm on last windows build from https://ci.popcorntime.app/job/Popcorn-Time-Desktop/
Currently 424, Revision: 5eb53fc0

I see the same behaviour : nothing happens when you click on Close after watching something. if manually deleting temp files, then I can close

**Comment by ze0ss** [comment]
@sheepdestroyer expected behaviour... it's a dev build (and not the stable release) after all...

**Comment by sheepdestroyer** [comment]
The stable release exposes the same bug...
It was suggested here that dev builds have it corrected, so I just chimed in to say that wasn't the case

**Comment by AsmodusLustro** [comment]
One problem I have is when I watch a movie and then I can't close the program from x  .The program is 0.4.4 and my o.s is win10 pro 1909

**Comment by soeirotm** [comment]
I'd got same problem with 0.4.4 x32... version x64 is working properly on my win10 1909.  
I'd downloaded x64 from https://popcorntime.app/windows

**Comment by dutchy1001** [comment]
@soeirotm 
please download the version you need from this link here,  https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastStableBuild/ .
This way you will have the latest build which might fix your the issue

**Comment by soeirotm** [comment]
> 
> 
> @soeirotm
> please download the version you need from this link here, https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastStableBuild/ .
> This way you will have the latest build which might fix your the issue

TY!

**Comment by ArcticZeroo** [comment]
I'm still getting this issue, even after installing the latest build. Dev console is telling me that it's the same "directory is not empty" error.

**Comment by ze0ss** [comment]
> I'm still getting this issue, even after installing the latest build. Dev console is telling me that it's the same "directory is not empty" error.

Try installing a CI build.

**Comment by ArcticZeroo** [comment]
@abh-oss01 I already have whatever was linked above from https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/ , which seems to be 12 commits behind development. That is also apparently the latest successful build

**Comment by dutchy1001** [comment]
@ArcticZeroo 
Have you tried a clean install? ("export database" from the settings page if you dont want to loose "seen" movies/series)

**Comment by ArcticZeroo** [comment]
@dutchy1001 I have not yet tried a clean install, will do later tonight.

Regardless, there are clear issues that would lead to this happening (even on a clean install) in `app.js`. If I can actually get this thing to build (node v0.10.0 is quite finnicky) I plan to submit a PR to "fix" it tonight. By "fix", I mean I will actually properly catch the errors associated with directory deletion and close the app regardless of error status. Right now, errors from `deleteDirectory` are uncaught. Still unsure why those errors appear to begin with

**Comment by ArcticZeroo** [comment]
Should be fixed now that #1557 has landed. I can no longer reproduce. We should figure out why the directory errors are appearing to begin with, but in the mean time this mitigation will ensure that users no longer feel the consequences of those errors.

If anyone else was having this issue, please install a CI build at https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/ and let me know if it's still happening for you

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by ArcticZeroo** [comment]
I don't really agree with the (now deleted) request to close this issue, my fix is only a workaround. There are still large (multi-GB or more) temp files being left in users' `%Temp%` directories when removal of the folder fails

**Comment by kiriles90** [comment]
@ArcticZeroo hmm ok, I just went by your comment above with this. Removing the 'close' request.

**Comment by kiriles90** [comment]
@Persei08 reopen this one please, sorry my bad!

**Comment by Persei08** [comment]
arf sorry, closed issues in batch and forget to unselect this one.. and maybe some other  :/ .

**Comment by kiriles90** [comment]
nop, only this I changed to 'dont close', rest is good!

**Comment by ze0ss** [comment]
@Persei08 can the close button and the other two follow windows title bar guidelines? this was seen in some older popcorn time builds iirc.

**Comment by kiriles90** [comment]
@abh-oss01 you mean unskinning the title bar? If you do that you will get a Win10 titlebar that kinda matches the whole theme (IF you use dark mode, and have the default dark skin in Popcorn Time), and 'break it' for everyone else (old versions of Windows and people without dark mode or using different Popcorn Time themes included).
Everything in Popcorn Time is skinned, even the checkboxes, why unskin the titlebar?

**Comment by ze0ss** [comment]
it was unskinned in some versions of PT iirc,. in those brief periods of time, there were absolutely no problems with closing, minimising, the app, ever, and it never once lagged or hanged/crashed, and also, it was a good look overall, it seemed it "blends in" with the rest of the win32 programs we use, like, a universal design language is desirable, to me at least.
this is all ofcourse my personal views., what you're saying (may not work on older win10 versions) might be true as well,
but tbh, you've got to upgrade win10 sometime, like sooner or later, it's a big security risk lol, and I've seen Devs dropping support for very older win10 versions, like, version 1709, even 1803.

**Comment by kiriles90** [comment]
The issue with the app closing has nothing to do with the titlebar being skinned/unskinned. Those few builds that was unskinned was because other updates (commits from butter, new nwjs etc) broke it, and was left like that for a couple of builds until someone fixed it.

> it seemed it "blends in" with the rest of the win32 programs we use,  

For win10 users with dark mode on and the default Popcorn Time theme, yes.. How about everyone else?

**Comment by ze0ss** [comment]
>For win10 users with dark mode on and the default Popcorn Time theme, yes.. How about everyone else?

it's the same for all win10 users on or after v1809 
did you read the last part of my previous reply? 😅
some devs drop support for older versions because being a win10 user, you have to upgrade sometime, sooner or later, because it's a security nightmare to have an older version of the os.

**Comment by kiriles90** [comment]
I've edited above. Check my last sentence. Not everyone uses windows, or windows 10..

**Comment by italocjs** [comment]
So, ive seen the "fix" on this thread (to disable clean folder), but i cant delete the temp files?  i have no idea whats going on,  i dont have permission to delete the temp even being administrator and having "taken ownership".  maybe this is whats causing the issue.

**Comment by kiriles90** [comment]
@italocjs just update to the latest dev build (438 at the moment) from ci.popcorntime.app and you wont have to do any of that

**Comment by refex** [comment]
Same here but I noticed that if I terminate all torrent file sharing, then it let me close the app.

**Comment by dutchy1001** [comment]
@refex 
As @kiriles90 said in his previous post, update to the latest build **[438](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

_Cant understand why ppl not updating before they post after they found this post WITH the solution_

**Comment by qdubz** [comment]
> You can "fix" it by disabling the "Clear tmp folder after closing app" in the Cache directory settings, but you will have to manually delete the downloaded files every now and then

WORKS.

**Comment by kiriles90** [comment]
@qdubz Updating to the latest build and having to do none of that also works since this is fixed for months now...

**Comment by qdubz** [comment]
> @qdubz Updating to the latest build and having to do none of that also works since this is fixed for months now...

i mean...considering i just downloaded it 3 days ago, i'm pretty up to date ;)

**Comment by ArcticZeroo** [comment]
> > @qdubz Updating to the latest build and having to do none of that also works since this is fixed for months now...
> 
> i mean...considering i just downloaded it 3 days ago, i'm pretty up to date ;)

Did you download a _dev build_, or a build from the website? I'm assuming the latter, which means you're using a build from ~April. If you were using a dev build, it would help if you provided some logs since that problem should be fixed.

**Comment by qdubz** [comment]
Ah ok, valid point. I'll pull down a dev build then. Thanks.

**Comment by kiriles90** [comment]
@ArcticZeroo I think its time to close this. Your fix works great for a long time now and basically does what Popcorn Time did before this bug appeared. The times were some files fail to be deleted are basically when they are in use by something (e.g an external player) and it was the same pre-#1280. I don't think there's much to do about this, and even if we could.. should we or it would cause undesired behavior in various scenarios?

**Comment by ArcticZeroo** [comment]
@kiriles90 Hmm okay, I can agree with that. Even if we do leave large files in temp, I suppose the whole point of temp is that the files can be safely deleted at any time. So with that in mind, I think it would be OK to close this
