### ISSUE TITLE
No subtitles at all...what´s wrong? (Popcorn Time)

### ISSUE THREAD

**Issue by JUANCA1566** [popcorntime/popcorntime#1281]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment]
Duplicate #1252
