### ISSUE TITLE
There is no Arabic subtitle at all and I can't choose any subtitle for the movie

### ISSUE THREAD

**Issue by Rowda109** [popcorntime/popcorntime#1282]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment]
Duplicate of #1265
