### ISSUE TITLE
Master issues topic

### ISSUE THREAD

**Issue by nando182** [popcorntime/popcorntime#1286]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.3
Download date:
08/4/2020
#### Expected Behavior
1) when click on watch it is supposed to start the buffering 
2) App is closed when we close it
3) Download button start the download of the movie/show
4) The download speed is displayed when you choose another player

#### Actual Behavior
1) nothing is happening
2) it is not being closed after buffering a movie, something is preventing it to be closed
3) It completely frozen the app
4) The download speed is showing 0kbps

#### Steps to reproduce the behavior
Just perform the listed actions, it is sad to see too much errors, seems that no one is testing it before release it

**Comment by M-Porter** [comment]
I'd suggest using the legacy popcorn time version. It does not have any of these problems. The new version acts as adware limiting your download speeds to push their VPN on you.

**Comment by Persei08** [comment]
Please make one report for each single issue. But those ones are already reported
