### ISSUE TITLE
Question about Georgian localization

### ISSUE THREAD

**Issue by arabuli** [popcorntime/popcorntime#129]
Hello, I translated both, Popcorntime for Desktop and for Android in Georgian language but they are not available in settings, even tough Transifex translation is completed to 100%. Is there any problem with translation or why isn't it added?

**Comment by VitorVRS** [comment]
Did you make an PR for this?

**Comment by arabuli** [comment]
I sent translation file to old developers few months ago. ka.json is available in /src/app/language right now but for some reason it doesn't show up in app settings.

**Comment by VitorVRS** [comment]
Hmm, ok. Later i'll take a look.

**Comment by team-pct** [comment]
https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/language.js#L404

It is listed here , so should be pulled please check on ci.popcorntime.sh if it is
