### ISSUE TITLE
Green Screen

### ISSUE THREAD

**Issue by ethemozer** [popcorntime/popcorntime#1290]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.4.3-0

Download date:
09/04/2020

#### Expected Behaviour
when i start a movie i have green screen

#### Actual Behaviour
Green screen issue

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 not an actual issue with Popcorn Time, close please?
