### ISSUE TITLE
Sync Russian translate from transifex.com

### ISSUE THREAD

**Issue by IgorPolyakov** [popcorntime/popcorntime#1293]
Hello, Russian translation finished
Can you sync it?

![Screenshot_2020-04-09 Popcorn Time App Transifex Editor](https://user-images.githubusercontent.com/2613581/78933696-3837fe00-7a99-11ea-926d-7af41844eee3.png)

**Comment by kiriles90** [comment]
@Persei08 any idea about this?

**Comment by dutchy1001** [comment]
I presume he wants the project added to this translation platform. 
https://www.youtube.com/watch?v=3y0x8q3Oj7Q

I don't think this is relevant to PCT

**Comment by Persei08** [comment]
@kiriles90 No idea, i don't know how transiflex translations are added :/

**Comment by dutchy1001** [comment]
This topic can then be closed, unless you get a further explanation why this should be added but I doubt this as the OP hasn't reacted in the last 5 months.

**Comment by kiriles90** [comment]
@Persei08 maybe close this one.. the OP doesnt seem to be coming back to explain anything

**Comment by kiriles90** [comment]
Sorry it took so long for a relevant answer but if you mean the translation at transifex.com/popcorn-time/popcorn-time-app/language/ru/ it looks synced to me. Download the latest dev build from ci.popcortime.app and compare them if you want and tell me if there is any issue.
