### ISSUE TITLE
subtitle dont work

### ISSUE THREAD

**Issue by foxmm** [popcorntime/popcorntime#130]
i want to add another subtitle from the internet  but dont work at all

popcorn 3.9 

windows7

**Comment by VitorVRS** [comment]
There is an option do select external subtitle file when you are watching a movie/show.
Can you put an print sceen of you subtitles selection list here?

**Comment by RubyRed72** [comment]
Hi, when I add subtitle via custom button, I receive letters which is not suitable for my language.
Serbian language, latin letters.
I save srt file by notepad on utf-8, and usually on my desktop PC, everything is OK.
But problem is on my Lenovo IdeaPad laptop OS Windows 7, when I try to put my subtitles for external source. As I said I receive unusual letters.
Popcorn version is latest 0.3.9.(80e3fc19 ).
I attach screenshot which Imarked with red square which containing unusual letters, despite letter "ć".
Please fix this.
![untitled](https://cloud.githubusercontent.com/assets/18181935/14165285/c4439d9c-f707-11e5-88ba-fa79bc34b50f.png)

**Comment by VitorVRS** [comment]
Ok, thanks for your response.
As you said, you can load external subtitles (so there is no problem with pct).
You should try to convert your srt file to utf8 ( usually i do this with iconv).
Your laptop encoding is configured right? I dont know windows very well, but there is an options to setup system encoding?

**Comment by RubyRed72** [comment]
Every srt file I encode with UTF-8. (Notepad)
When I load it to PCT, occured unusual letters instead for example "ć" gave some scandinavs lette something btwn ae.
I am not sure that is problem with Windows 7.
Because I last year use Windows 7 on my PC along with PCT, and never occur things like this.

**Comment by VitorVRS** [comment]
What player are you using?
Have you tried another player (vlc, mpc...) with the same srt file?

**Comment by RubyRed72** [comment]
Using that PCT player.
I not yet try with VLC player on laptop.
I have installed this one on my lptp.
Will try.
VLC player is not very well for me.
Do not allow to put down subtitles on movie, tv show which have black letterbox.
You know what I mean.
Don't know to express myself accuratelly.
On VLC subtitles always is on pic, can't put in black field of letterbox.
You know what I mean.
