### ISSUE TITLE
Update to 0.4.3.0 emptied database. Can I restore the previous?

### ISSUE THREAD

**Issue by humanplayer2** [popcorntime/popcorntime#1301]
Operating System Version:
Windows 10
Popcorn Time Version:
0.4.3.0

Download date:
10 April 2020

#### Expected Behaviour
Update previous version, but keep database.
...

#### Actual Behaviour
Update previous version, but now has empty database.
...

#### Steps to reproduce the behaviour
I guess:
1. Install 0.3.10
2. Add something to favorites
3. Install 0.4.3.0
4. See that favorites is now empty.

Can I restore my old database? 3.10 used default settings for databases, but I didn't export before updating. Is the databse lost, then?

**Comment by dutchy1001** [comment]
If you haven't exported then I'm afraid it will be lost.
For this reason I have auto update unticked in the settings and make a export file every week.

With making an export backup I have also notest that it will crash when importing it. Best way (if you have a backup) is to add them manual (C:\Users\Your PC Name)\AppData\Local\Popcorn-Time\User Data\Default\data) except for the "setting.db" as that is the cause of the crash. Rather redo the settings as there aint that much you will change then adding all movies and shows again.
Hope this makes sence.

**Comment by kiriles90** [comment]
@Persei08 duplicate issue, close please
