### ISSUE TITLE
ALL WRONG

### ISSUE THREAD

**Issue by rdisystem** [popcorntime/popcorntime#1303]
Please, the version 4. don't loading the movies and series and also not closing the program through [X].

Please return with the previous version 3 !!!

**Comment by Persei08** [comment]
You still have the choice, you can always use 0.3.10 if you want.

Just disable "automatic updating" option or delete "updater.js" file in `<popcorntime folder>/src/app` if it's still forcing the update.

**Comment by rdisystem** [comment]
ok, i did this

But the legends don't loading more !! All movies and series, why ?

*Reginaldo*

*Projetos de **Produtos e In**teriores*

*Imóveis na Planta*


*http://www.r3dprojetos.com <http://www.r3dprojetos.com/>*https://w
<https://sites.google.com/creci.org.br/imoveis-na-planta/p%C3%A1gina-inicial>
ww.imoveisnovoseusados.com

*[11] 9-8390-0197 -  Nextel - (Whatsapp)*

*[11] 9-4151-2782  - Vivo*






Em seg., 13 de abr. de 2020 às 07:12, Persei08 <notifications@github.com>
escreveu:

**Comment by rdisystem** [comment]
ok, i did this,  0.3.10

But the legends don't loading more !! All movies and series, why ?

*Reginaldo*

*Projetos de **Produtos e In**teriores*

*Imóveis na Planta*


*http://www.r3dprojetos.com <http://www.r3dprojetos.com/>*https://w
<https://sites.google.com/creci.org.br/imoveis-na-planta/p%C3%A1gina-inicial>
ww.imoveisnovoseusados.com

*[11] 9-8390-0197 -  Nextel - (Whatsapp)*

*[11] 9-4151-2782  - Vivo*






Em seg., 13 de abr. de 2020 às 07:12, Persei08 <notifications@github.com>
escreveu:

**Comment by Persei08** [comment]
Please do some search, lot of user have opened duplicate reports for this subtitles issue. It's even pinned. Opensubtitles is restricting subtitles download to registered users only due to coronavirus and traffic increase. Read whole comments on issues #1252, there are detailed explanations eventually even for 3.10. Hope you will find what you need.
