### ISSUE TITLE
Video is choppy in the middle

### ISSUE THREAD

**Issue by toumbo** [popcorntime/popcorntime#1304]
Operating System Version: Lubuntu 18.04.4 LTS amd64 & nouveau

Popcorn Time Version: 0.4.3 - Build #407

![Στιγμιότυπο από 2020-04-11 04-17-42](https://user-images.githubusercontent.com/63482834/79032119-96a1d100-7bac-11ea-8862-510f831eeeac.png)

Download date: Apr 4th, 2020

There is vlc, which works perfectly as a workaround though...
What further info should I write?

**Comment by kiriles90** [comment]
@Persei08 not really a Popcorn Time issue, close please
