### ISSUE TITLE
NEW UPDATE IS WORST

### ISSUE THREAD

**Issue by carlosr11** [popcorntime/popcorntime#1305]
Operating System Version:
 WINDOWS 10

Popcorn Time Version:
 Version 6.2 

Download date:
 4/10/2020
#### Expected Behaviour

... IT WAS PERFECT BUT WITH THE LAST UPDATE I CAN EVEN START WATCHING A MOVIE, DOESNT START. IM USING THE PAST ONE THE 0.4.35 THINK SO BUT I CANT USE THE SUBTITLES. HELPPP

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
> I CANT USE THE SUBTITLES. HELPPP

Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)
