### ISSUE TITLE
Extremely slow download with external torrents

### ISSUE THREAD

**Issue by vviotto-masti** [popcorntime/popcorntime#1308]
Operating System Version:

Win 10

Popcorn Time Version:

0.4.3

Download date:

Installed the last update when it came out

The new version of popcorn time is having some problem handling external torrents, for some reason, it seems that the app is unable to connect to seeds/peers resulting is extremely slow download speeds on a healthy torrent(1543/163 seed/leech ratio).
As soon as I load the same torrent in qBitTorrent (using the 'download in sequential order' option to mimic popcorn time download), the torrent immediately goes to max speed, so its not a problem with the torrent.
I'm seeing this with almost all torrents that I've tried, in a small percentage of them it does connect as expected and download speed is normal, but 95% of the time it doesn't work.

**Comment by Persei08** [comment]
>As soon as I load the same torrent in qBitTorrent (using the 'download in sequential order' option to mimic popcorn time download), the torrent immediately goes to max speed, so its not a problem with the torrent.

PT use webtorrent, you should better try with [webtorrent desktop](https://webtorrent.io/desktop/) it will be more close into mimicking popcorntime.

**Comment by vviotto-masti** [comment]
> > As soon as I load the same torrent in qBitTorrent (using the 'download in sequential order' option to mimic popcorn time download), the torrent immediately goes to max speed, so its not a problem with the torrent.
> 
> PT use webtorrent, you should better try with [webtorrent desktop](https://webtorrent.io/desktop/) it will be more close into mimicking popcorntime.

Thanks for the reply, I didn't know that popcorn time used webtorrent, so I tried it per your suggestion and with webtorrent desktop the download speed is just fine, using the same torrent that had problems in popcorn time, of course.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
