### ISSUE TITLE
the remote movies API failed to respond

### ISSUE THREAD

**Issue by laweafome** [popcorntime/popcorntime#131]
Operating System Version:
Windows 10

Popcorn Time Version:
3.9

Download date:
30/03/2016
#### Expected Behaviour

this will work :P
...
#### Actual Behaviour

dont work, i cant view movies
...
#### Steps to repoduce the behaviour
1. ...install popcorn time
2. ...open popcorn time
3. ...boom! the bug appears

![4b2726993d5c6913cc8e67a0f2750008](https://cloud.githubusercontent.com/assets/18182637/14166120/49fe47b8-f6c5-11e5-8395-4bf0de28147b.png)

**Comment by Breaking1** [comment]
Works perfectly fine in my version could you be blocked in any way?

Did it work before?

**Comment by aborgeld** [comment]
Hi people i got the same specs and in my case the API was loading and seem to load forever (rotating circle). I closed my hotspotshield VPN and i saw the movies loading. And now i have this workaround.
1. Close VPN
2. Choose movie
3. Open VPN 
4. Download movie and it works

Maybe it is an idea to ask the user if he has a VPN and try something like this.
You can look at firewall too (443, or 8443) if api is ssl.
