### ISSUE TITLE
Issue downloading

### ISSUE THREAD

**Issue by Archundix** [popcorntime/popcorntime#1311]
Operating System Version:
<OS X 10.13.6>

Popcorn Time Version:
<0.4.3.0>

Download date:
<April 10>

#### Expected Behaviour
<App should show download status including speed, percentage downloaded, etc.>
...

#### Actual Behaviour
<Doesn't show information, but downloads the movie>
...

#### Steps to reproduce the behaviour
<What steps do we need to take to find the same bug that you found?>

1. Go to movies
2. Select Movie
3. click "Download"

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
