### ISSUE TITLE
Subtitles are gone 

### ISSUE THREAD

**Issue by aborgeld** [popcorntime/popcorntime#1312]
Operating System Version:
Windows 10

Popcorn Time Version:
https://get.popcorntime.app/
 Popcorn-Time-0.4.3-win64-Setup.exe

Download date:
NL: 11-04-2020  US: 04/11/2020

#### Expected Behaviour
Choose between subtitles

#### Actual Behaviour
At subtitles you see an X, no language at all

#### Steps to reproduce the behaviour
1) Select any movie
2) Directly go to subtitles on the right.

**Comment by aborgeld** [comment]
I have tested build: https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/
But still the same error


![subtitle error](https://user-images.githubusercontent.com/18404019/79062788-6a19b200-7c9d-11ea-945b-da39bf2586e3.JPG)

**Comment by kiriles90** [comment]
You need build 407 then to login to opensubtitles.org in the settings. Then no more error. Then close this issue because there are about 30 of them. Everyone is opening a new one for the same FIXED thing.

**Comment by aborgeld** [comment]
Thank you very much, you're right. I'm sorry for the misunderstanding. Have a wonderful easter

**Comment by kiriles90** [comment]
No worries. Have a great easter as well :)
