### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by JohnFinn** [popcorntime/popcorntime#1314]
I've spend great many time searching for german audio stream for one movie. How can I upload it, so it will be available at popcorn time, so that everyone who wants watch the film in german would not have to search for it?

**Comment by kiriles90** [comment]
Popcorn Time doesnt upload/host/maintain any of the content, it automatically indexes it from 3rd party providers.

The movies provider is YTS.mx you can contact them but.. they dont do dubbed movies (as they should if you ask me) so if whatever movie you are talking about is a dubbed one and wasnt originally in german I dont think they will want to add it.
