### ISSUE TITLE
Don't work the subtitles even restarting, reinstalling etc and was worok fine few days ago, microsoft windows 10 pro 

### ISSUE THREAD

**Issue by kimfesol** [popcorntime/popcorntime#1316]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by dutchy1001** [comment]
fix at #1318
