### ISSUE TITLE
SUBTITLES ISSUE read before posting new issue's

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1318]
To fix the issue most people have with the subtitles you need to update to the latest dev build, **you can find this version [here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

### EDIT: updated to get the "latest" version when clicking link (21-07-2020)

To be sure this will work you need to do a clean install, this meaning to uninstall your old version and delete all files and folders from Popcorn-Time. 
The default location for those folders are:
1. C:\Users\Your PC Name\AppData\Local\Popcorn-Time
2. C:\Users\Your PC Name\AppData\Local\Temp\Popcorn-Time

Due to changes in the API from Opensubtitle.org everybody that need the subtitles to work need to make an account there, **a link to their website is [here](https://www.opensubtitles.org/en/newuser)**.

After you made an account at Opensubtitle.org you have to fill in your logon details into the settings page of Popcorn-time. 
This will fix the subtitle issue you all have and therefore there is no need to make a new issue.

**Comment by Persei08** [comment]
This board look more like a forum than a real issue board.
I've edited the title and I will pin it termporary in hope users will stop open unnecessary duplicate reports.

People with subtitles issue should read whole comments in issues #1252

**Comment by dutchy1001** [comment]
thanks for making this  pinned

**Comment by Ezinho031** [comment]
It still doesn't work for me. I have completely uninstalled Popcorn-Time from my pc, deleted all the files that may be left behind, created an account in OpenSubtitles, reinstalled Popcorn-Time again and logged in to OpenSubtitles and still no subtitles :(

**Comment by dutchy1001** [comment]
@Ezinho031 
Did you fill in the Opensubtitle login details in the settings of PCT?
The way I read your message is that you logged in on the Opensubtitle site.

**Comment by Ezinho031** [comment]
Oh, sorry for the confusion. English is not my main language.

And yes, I put my login credentials of OpenSubtitles in Popcorn-Time.
Here's a pic.
![Anotación 2020-04-13 151739](https://user-images.githubusercontent.com/63608605/79152196-c530cf00-7d99-11ea-85f6-06a66be44064.jpg)

**Comment by dutchy1001** [comment]
Have you downloaded the version from the link in the above post?

If you click in the **i** top right of your PCT, what code you see in the right bottom?
![code](https://user-images.githubusercontent.com/5569980/79152604-67fe4300-7dc4-11ea-8135-831f5d407a99.png)

**Comment by Ezinho031** [comment]
Ohh I thought that the download link at popcorntime.sh was updated. Now with that build installed the subtitles are working perfectly haha. Thanks.

**Comment by dutchy1001** [comment]
that is the reason why there was a direct link to the latest version.
Glad you sorted it

**Comment by wenrei09** [comment]
hello, step by step what you explain but now the movies don't load me
![Captura de pantalla 2020-04-14 a las 13 00 15](https://user-images.githubusercontent.com/23667052/79218824-63cc3700-7e51-11ea-94ea-21093827cf0a.png)

**Comment by dutchy1001** [comment]
@wenrei09 
This has nothing to do with the subtitles, please read #1321

**Comment by DanielDeeb** [comment]
Opensubtitle login details in the settings of PCT keep loading without sign in / save

**Comment by DanielDeeb** [comment]
![Screenshot 2020-04-15 at 9 02 49 PM](https://user-images.githubusercontent.com/63741213/79371230-b34b5980-7f5c-11ea-846e-f764ffbe12c2.png)

**Comment by Hattshire** [comment]
Related: #1339

**Comment by dutchy1001** [comment]
@DanielDeeb 

your login details are not correct there.
It should say DanielDeep@yourmailprovider.whatever, not only your name.
When filling in your user name at opensubtitle you fill in your full e-mail address too there, and then the password ofcourse.

**Comment by nayaracd** [comment]
I can't login on to OpenSubtitles and my credencials are correct.

On the web site of OpenSubtitles i can login, but on the popcorn doesn't work.

![image](https://user-images.githubusercontent.com/5407568/79413762-32ea2000-7f7f-11ea-8508-b571d6e9c3fa.png)

**Comment by dutchy1001** [comment]
@nayaracd 
It works for everybody else to log in so I would double check the credentials you put in.

**Comment by DanielDeeb** [comment]
changed my username to email address. again it does not log in. just loading. does it take time ?

**Comment by dutchy1001** [comment]
@DanielDeeb 

Like I said, it works for everybody else. Recheck with your account with opensubtitle.org. Other option is to make a new account with an alternative e-mail and see if that works.

**Comment by douglascamata** [comment]
Subtitles are not being loaded into VLC. They are loaded and work fine in the built-in player.

It used to work fine in the past.

**Comment by sralmei** [comment]
HI! I Speak portuguese and i think its very confusing. Can you explain in Portuguese?

**Comment by dutchy1001** [comment]
@sralmei 
this is an international project, the common language used is English so most people can understand this. 
If you have problems with that then try and use google translate is your best bet.
And before people start to me on this language problem, my first language isn't English either and I'll have to manage too

**Comment by sralmei** [comment]
Hi! It Worked! Thanks a lot.

**Comment by Jany-M** [comment]
Comments work once the movie starts but not in the single movie screen (no subtitles show).
They must be chosen manually for each movie every time, even if everything is all set in PT options (including which lang to pick).
