### ISSUE TITLE
I cant Found Money Heist TV Show Series 

### ISSUE THREAD

**Issue by rayankhres5** [popcorntime/popcorntime#1319]
Operating System Version:
 Windows 10

Popcorn Time Version:
 latest popcorn time update on pc  0.4.3

Download date:
 today at 2:04pm

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
If it aint there it aint there.
This is for programming/coding issue's not missing series, episodes or movies

**Comment by Persei08** [comment]
Don't know what happened but this could be a [popcorn-api](https://github.com/popcorn-official/popcorn-api) issue. (eztv.io/shows/9222/money-heist/)

**Comment by team-pct** [comment]
Nop Trakt issue

**Comment by Persei08** [comment]
oh ok, i think i know why now
