### ISSUE TITLE
Popcorn time 0.4.3 no movies load in 

### ISSUE THREAD

**Issue by balinbob1** [popcorntime/popcorntime#1323]
Operating System Version:
 windows 10 

Popcorn Time Version:
 0.4.3

Download date:
 reinstalled it 5min ago but i used it yesterday.

#### Expected Behaviour
 show me the movies.
...

#### Actual Behaviour
 nothing it just keeps loading infinite i guess, i just see the blue circle spinning and spinning nothing happend.
...

#### Steps to reproduce the behaviour

1. ...i don't know it just happend suddenly
2. ...
3. ...
![popcorn timee](https://user-images.githubusercontent.com/63644867/79217968-88e68880-7e04-11ea-801b-ca796c9e3e25.png)

**Comment by dutchy1001** [comment]
duplicate #1321

**Comment by gstapelber** [comment]
> Operating System Version:
> 
> windows 10
> Popcorn Time Version:
> 
> 0.4.3
> Download date:
> 
> reinstalled it 5min ago but i used it yesterday.
> #### Expected Behaviour
> show me the movies.
> ...
> 
> #### Actual Behaviour
> nothing it just keeps loading infinite i guess, i just see the blue circle spinning and spinning nothing happend.
> ...
> 
> same is happening on my OS, no movies showing

**Comment by balinbob1** [comment]
i don't really know what to do now, the thing is it worked fine yesterday night. the next morning i open it up and it just keeps loading. maybe it is just temporarily ?

**Comment by balinbob1** [comment]
i just noticed that there is a new version of popcorn time: 0.4.4 ?

**Comment by balinbob1** [comment]
yep the new version works with me. 
just download 0.4.4 and it will probably work

**Comment by MhadCode** [comment]
Same problem here, How to download 0.4.4?

**Comment by iKenshu** [comment]
You can go [here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/409/) @MhadCode

**Comment by team-pct** [comment]
https://popcorntime.app

**Comment by MhadCode** [comment]
Thanks, Everyone! I appreciate ur help.

**Comment by asadmalik** [comment]
Seems to be fixed. Window 10 home, latest version.

**Comment by esnover70** [comment]
I have the same problem

**Comment by kiriles90** [comment]
@esnover70 same solution, update to 0.4.4 or 0.2.10 if on android.

**Comment by Persei08** [comment]
Duplicate of #1321
