### ISSUE TITLE
Readme.md on site is not sync with the one in source code

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#1324]
On your site, the readme tells:
#### Quickstart:
`yarn start`
If you encounter trouble with the above method, you can try:

```
yarn config set yarn-offline-mirror ./node_modules/
yarn install --ignore-engines
yarn build
yarn start

```
in source code:
#### Quickstart:

1. `gulp run`

If you encounter trouble with the above method, you can try:

1. `npm install -g bower gulp` (Linux: you may need to run with `sudo`)

2. `npm install`
3. `bower install`
4. `gulp build`
5. `gulp run`

**Comment by Persei08** [comment]
What do you mean by "Readme.md on site" ?

**Comment by vRITHNER** [comment]
Sorry, I was not clear.
If you see the documentation on https://github.com/popcorn-official/popcorn-desktop
The readme.md is supposed the be the same the good one but the one I get from the cloned source code is different and it's bugging me.

**Comment by Persei08** [comment]
oh ok, i guess it's because you are on an old master branch. The default branch here (on github) was set to development. The master branch is the releases code, and i think it was updated yesterday.

Look like you need to sync your local repo.

**Comment by Persei08** [comment]
@vRITHNER is it good now ? Do you need some help ?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
