### ISSUE TITLE
[feature] Bring back multiple subtitle options

### ISSUE THREAD

**Issue by iKenshu** [popcorntime/popcorntime#1325]
On some of the builds of Popcorn Time there was a feature to choose a subtitle of multiple option for the same language

![Annotation 2020-04-14 090157](https://user-images.githubusercontent.com/5619966/79228462-7a619680-7e2f-11ea-8434-61f753aa9642.png)

This should be a nice to have in the new version of Popcorn Time

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
