### ISSUE TITLE
[Feature request] Back button on mouse 

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1327]
When browsing through the movies we always have to use the **X** in the top right corner to go back to the main page (either movie, serie, anime or favorites). 

Would it be possible to add a back button with the use of our mouse. Most mice have these days more than the left/right and middle mouse button. This would browsing through movies/series a lot easier and quicker.

With my internet browser I can use my mouse button 4 (on the side above my thumb) to go back a page.

**Comment by dutchy1001** [comment]
Is there any  progress for this feature request, or should I create a new feature request with the new template?

**Comment by Persei08** [comment]
Hi, it's a good idea, I added "good first issue" tag, in case it will interest some new contributors.

I'm think it could be easy and quick to do, but i'm focused on other things actually...

ping me next friday if there is no progress here.

**Comment by Persei08** [comment]
PR submitted. I will wait a bit for eventual reviews/feedbacks

**Comment by dutchy1001** [comment]
As soon the build is made I will test this new cool feature

**Comment by dutchy1001** [comment]
new feature works great

many thanks for adding this

**Comment by Persei08** [comment]
yep, a bit faster to switch from one synopsis to another ;)
