### ISSUE TITLE
Remove tacky and borderline fraudulent vpn commercial

### ISSUE THREAD

**Issue by rickisen** [popcorntime/popcorntime#1330]
There is nothing wrong with trying to fund a project like this. Sure commercials are annoying. But adding a blinking lock icon that says "connection not secure" even if you are already using a vpn is just next level shady.

What's next? A bitcoin minig "anti virus"? Find hot singles in your area?

Iv'e already seen confused people on reddit thinking that this vpn is required for a connection to work.

Please have some taste.

**Comment by team-pct** [comment]
Just stop with that whining already ! and if you dont like it just go to settings and disable VPN

**Comment by test2a** [comment]
Can I suggest you have a donate button? Paetron, liberapay, crypto, PayPal.

**Comment by team-pct** [comment]
We cannot accept donations ... its more complicated than it appears

**Comment by rickisen** [comment]
So why not have an regular commercial? I'd wager you probably get some
initial boost doing this fraud thing.
But after a while you'll see people drop of or even fork over something
like this.

Overly aggressive monetization has killed many similar software projects
you know...
