### ISSUE TITLE
Keyboard stops working when opening a title and then going back

### ISSUE THREAD

**Issue by 88hcsif** [popcorntime/popcorntime#1333]
Operating System Version:
OS X 10.15.4

Popcorn Time Version:
0.4.4

Download date:
2020 04 14

#### Expected Behaviour
Keyboard always works

#### Actual Behaviour
Keyboard stops working when opening a title (either movie or series or anime) and then going back.
Keyboard starts working again if you first switch tabs using the mouse.

#### Steps to reproduce the behaviour

1. Open application
2. Confirm you can move around with the keyboard
3. Select on any movie (click with mouse or press space or press enter)
4. Go back (click on X with mouse or press escape)
5. Confirm that keyboard has completely stopped working
6. Use the mouse to switch tabs (eg. from Movies to Series)
7. Confirm you can move around with the keyboard again

**Comment by Persei08** [comment]
Xubuntu 18.04
PT v0.4.4
Can't reproduce the bug.

Does someone else can confirm this bug, on macOS, win or linux ?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
