### ISSUE TITLE
I don't get moving picture on 

### ISSUE THREAD

**Issue by sadpersn** [popcorntime/popcorntime#1338]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by sadpersn** [comment]
The screen is just black, I get no picture... Please fix!!!

**Comment by Persei08** [comment]
Closing because report don't follow the rules
