### ISSUE TITLE
ola

### ISSUE THREAD

**Issue by horacio1987** [popcorntime/popcorntime#1339]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by horacio1987** [comment]
ola no programa que tenho popcorn pus o meu idioma e nas legendas também ou seja português mas não aparece legendas em nenhum filme podem me ajudar obrigado

**Comment by Hattshire** [comment]
Not all movies are in every audio language (the feature is implemented, but the server part doesn't find more languages), and subtitles are there only if they're available in _opensubtitles_ (and you _**logged in**_ to your _opensubtitles_ account in settings).

Also please write in **english** only here, and consider that this is not stable software, expect crashes and non working functions, and open an issue with the required data. (and use punctuation pls)

### Em português (auto-tradução)
Nem todos os filmes estão em todos os idiomas de áudio (o recurso está implementado, mas a parte do servidor não encontra mais idiomas), e as legendas só existem se estiverem disponíveis em _opensubtitles_ (e você fez login nos _opensubtitles_ conta nas configurações).

Além disso, escreva aqui apenas _**em inglês**_ e considere que este não é um software estável, espere falhas e funções que não funcionem e abra um problema com os dados necessários. (e use pontuação, por favor)

**Comment by Persei08** [comment]
So, i close this issue @Hattshire replied and issue #1318 explain the subtitles issue
