### ISSUE TITLE
Is master now official "latest commits" branch or still development?

### ISSUE THREAD

**Issue by smac89** [popcorntime/popcorntime#1341]
For the longest time, we have been relying on watching the `development` branch to get the latest commits, but now it seems that master is seeing some action.

As you can see [here](https://github.com/popcorn-official/popcorn-desktop/pulls?q=is%3Acommit+is%3Apr+base%3Amaster), before this year, the last commit to master was in 2016 (https://github.com/popcorn-official/popcorn-desktop/pull/277)

Should we now rely on `master` to contain the latest commits, or still watch `development` branch?

Thanks.

**Comment by team-pct** [comment]
development will have the the last improvement

**Comment by smac89** [comment]
@team-pct Please update the [README](https://github.com/popcorn-official/popcorn-desktop#getting-started) so that it does not tell people to use the master branch.
Interestingly the link actually points to `development` branch, but says `master`.

**Comment by kiriles90** [comment]
@Persei08 close this please
