### ISSUE TITLE
Torrent metadata(Item model) provider conflicts

### ISSUE THREAD

**Issue by Hattshire** [popcorntime/popcorntime#1342]
A cached favourite torrent metadata with a no longer working _provider_ attribute breaks the flow, as it tries to fetch metadata from the cached dead provider and does not try other providers nor shows feedback to the user about this issue (Near Infinite Wait Loop).
Seen at: 
```javascript
this.model.get('provider')
```
https://github.com/popcorn-official/popcorn-desktop/blob/ef22f16d274bc41215b037a3306eed848337c5eb/src/app/lib/views/browser/item.js#L169

Also on trying to resolve that provider, it ends up adding a new provider, even if there is another one with the same name, but different apiUrls (cache having `DeltaAPI?&ApiUrl=https://api.delta.local` and `DeltaAPI?&ApiUrl=https://broken.delta.local` at the end of the day)
Seen at:
https://github.com/popcorn-official/popcorn-desktop/blob/ef22f16d274bc41215b037a3306eed848337c5eb/src/app/lib/providers/generic.js#L67-L88

**Comment by kiriles90** [comment]
Hmm this was added with https://github.com/popcorn-official/popcorn-desktop/commit/19ddcb095a2a2a740a8b8b4db43491a5fe149406 to fix when opening a show from the Favorites tab. There is also no other mention of `this.model.get('provider')` anywhere in Popcorn Time's code. It seems we need a better way to fix the original issue without causing the one mentioned above by the OP.

@Persei08 can you tag this as 'bug' please?

**Comment by kiriles90** [comment]
@Hattshire couldnt find more info on this, or perfectly understand what you mean and if its an issue to be honest. If you can reproduce this on the latest dev build from ci.popcorntime.app and you believe this to still be an issue say so and I'll reopen.
