### ISSUE TITLE
Some covers don't loaded

### ISSUE THREAD

**Issue by PoetaGA** [popcorntime/popcorntime#1343]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
15/04/2020

#### Expected Behaviour
Loaded the cover, the cover exists in TMDB.org, for example:
- The Karate Kid (1984)
- Independence Day: Resurgence (2016)
...

#### Actual Behaviour
Covers don't loaded, only "overview info" from the tmdb.org
...

#### Steps to reproduce the behaviour
1. Load app
2. Search movie
3. Some movies don't show cover

         

> 
    loadImage: function () {
            var noimg = 'images/posterholder.png';
            var poster = this.model.get('image');
            if (!poster && this.model.get('images')){
            poster = this.model.get('images').poster;
            }
            else {
            poster = this.model.get('poster') || noimg;
            }

            var setImage = function (img) {
                if (this.ui.cover.css) {
                this.ui.cover.css('background-image', 'url(' + img + ')').addClass('fadein');
                }
            }.bind(this);

            var posterCache = new Image();
            posterCache.src = poster;

            posterCache.onload = function () {
                if (poster.indexOf('.gif') !== -1) { // freeze gifs
                    var c = document.createElement('canvas');
                    var w  = c.width = posterCache.width;
                    var h = c.height = posterCache.height;

                    c.getContext('2d').drawImage(posterCache, 0, 0, w, h);
                    poster = c.toDataURL();
                }
                setImage(poster);
            };
            posterCache.onerror = function (e) {
                setImage(noimg);
            };

**Comment by Persei08** [comment]
Wasn't able to reproduce with movies named by OP but when i searched for karate kid, i found some movies without cover:

- The Karate Kid Part II - 1986 - tt0091326
- The Next Karate Kid - 1994 - tt0110657

Requesting those movies to popcorn-api returned no images

```json
    "genres": [
        "adventure"
    ],
    "images": {},
    "rating": {
        "percentage": 56,
        "watching": 0,
        "votes": 846,
        "loved": 100,
        "hated": 100
    }
```

So, **I close this issue until someone can provide information that the issue come from popcorntime client**. 

@PoetaGA you should probably report this issue to [popcorn-api repo](https://github.com/popcorn-official/popcorn-api) instead
