### ISSUE TITLE
The app is just a black screen

### ISSUE THREAD

**Issue by Faaabiii** [popcorntime/popcorntime#1347]
Operating System Version:
Windows 8

Popcorn Time Version:
0.4.4

Download date:
16/04

#### Expected Behaviour
/ /

#### Actual Behaviour
It won't initialize. I click to open the app and it's just a black screen. There's no icon indicating that it's loading, nothing. It is, quite literally, a black screen.

I have already uninstalled it and downloaded it twice, but still isn't working. Help?

**Comment by popcornhelp** [comment]
mine is doing the exact same, except i am getting the blue loading icon, except it never loads..have also done the uninstall and download again thing but nothing, was working fine a few days ago now just blank,super annoying. I'm using a mac

**Comment by dutchy1001** [comment]
This should be fixed in a newer build, get the latest build **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/415/)**

**Comment by biustech** [comment]
i fixed my problem, not sure what exactly but one of two things i did:
installed all Visual C++ libraries
or changed the windows theme to default
but it's working now version 0.4.4

**Comment by kiriles90** [comment]
@Persei08 close this since its not an issue with Popcorn Time?
