### ISSUE TITLE
VPN on Butter

### ISSUE THREAD

**Issue by Cottonlane** [popcorntime/popcorntime#1349]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...VPN on butter is getting to be a pain in the arse I have my own VPN but it still nags me to use that one?
2. ...
3. ...

**Comment by dutchy1001** [comment]
then turn it off in the "**advanced** setings"

**Comment by confuzled-dev** [comment]
Seems like a REALLY simply compromise would be to ask the user if they are currently using thier own VPN. 
I am all about you guys generating revenue but this is bordering on fear-mongering. 
Asking will avoid complaints from people with existing VPN's as well as prompt users who don't to make a decision as to whether or not they want to use your or to get their own.

Further, are there details about what vpn this is using and how end users can educate themselves on the details of said VPN and if it is decent or not?

Also, please dont point me to source to get details about the VPN.

**Comment by Persei08** [comment]
I close, Invalid report, issue was already discussed many times

Please follow guidelines, search similar reports before creating new one and make a valid report.

**Comment by Cottonlane** [comment]
Wee seeing as I have only just joined your group, How the hell was I Supposed to know that?

**Comment by Persei08** [comment]
Know what ? Searching similar issue ? This is common sense I guess...

Now there is a template when you create issue and you leave almost everything empty. It's not my job to teach everyone how to fill a report. 
How some people find it logic and how other are bugged by it is a mystery to me. I just want this place to have valid reports. Sorry if you feel offended
