### ISSUE TITLE
Heavy CPU usage + Low Response Time

### ISSUE THREAD

**Issue by ar0ra1** [popcorntime/popcorntime#1350]
Operating System Version: OS X 10.15.4
Popcorn Time Version: Version 0.4.4 (0.4.4)
Download date: 16-04-2020
#### Expected Behaviour
Play the movie / series fine without any issue.

#### Actual Behaviour
Heavy CPU Usage, low response time of the app (press spacebar and it pauses after 5 seconds).
This continues until the entire episode is loaded. 
In the case of movie, the app stops responding all together.
Same case when playing on VLC.

#### Steps to reproduce the behaviour
1. Launch App
2. Play a movie / series (720p or higher)
3. Wait for it to throttle while playback. Usually within first 5 minutes.

**Comment by Persei08** [comment]
Possible similar issues #1299, #1373

**Comment by kiriles90** [comment]
@Persei08 close this since duplicate?
