### ISSUE TITLE
Slow 

### ISSUE THREAD

**Issue by pell0463** [popcorntime/popcorntime#1351]
for some reason the movies/series dosnt load well, when i try seeing the flash i get loading all the time even if i have a 100 MB/s upload and download, i love popcorntime, but this is just destroying the fun of watching a free movie
if needed i got the last update, and windows 10

**Comment by Persei08** [comment]
Popcorntime is based on bittorrent technology. More users share the files and more quick you download it.

I close this issue. Please follow guidelines and make a valid report and please check there isn't an issue for this already.
