### ISSUE TITLE
Play next episode does not work

### ISSUE THREAD

**Issue by Kalepeer** [popcorntime/popcorntime#1352]
Operating System Version:
Win 10 64 bit

Popcorn Time Version:
4.4

Download date:
16-4-2020

#### Expected Behaviour

play next episode automatically
...

#### Actual Behaviour 

does not work. Goes back to serie episodes list
...

#### Steps to reproduce the behaviour 

1. In preferences, check "Play next episode automatically"
2. Select a serie and play an episode (for example season 1 episode  1)
3. ...play /start. 

_Report cleaned and updated on April 21, 2020_

**Comment by salah3x** [comment]
Experiencing the same issue.
OS: Windows 10 (1909)
Popcorn: 0.4.4 (HEAD [0c54b2cd](https://github.com/popcorn-official/popcorn-desktop/commit/0c54b2cd2bc2af8e08664cd9d13d8ea4d99dee89))

**Comment by tanvir-10** [comment]
Experiencing the same issue.
OS: Debian (deepin 15.11)
Popcorn: 0.4.4

**Comment by Kalepeer** [comment]
Congratulations.
The broblem is not beeing address to unfortunately .
I don't know even if it reached popcorn admin.
Still have the same problem

**Comment by Persei08** [comment]
@Kalepeer the issue was tagged with "bug" label. 
Now the reality is there isn't enough devs or contributors to fix all the bugs, it require time, this one is nobody top priority or didn't catch their attention enough. Be patient don't loose hope.

**Comment by tanvir-kx** [comment]
This bug should be in the top priority among all other bugs.

**Comment by iKenshu** [comment]
This is one of the best features of PT

**Comment by Kalepeer** [comment]
then why doesn't it function on pt 4.4 ??

Op za 2 jan. 2021 12:01 schreef Kevin Morales <notifications@github.com>:

**Comment by dutchy1001** [comment]
@Kalepeer as been said before 

> @Kalepeer the issue was tagged with "bug" label.
**Now the reality is there isn't enough devs or contributors to fix all the bugs**, it require time, this one is nobody top priority or didn't catch their attention enough. Be patient don't loose hope.

**Comment by Kalepeer** [comment]
i won't 🙂.
but it is too bad there are so little devs.
sadly i am just a amateur programmer.
but i did make some donations for i also Love Popcorn 🤗

Op za 2 jan. 2021 12:39 schreef dutchy1001 <notifications@github.com>:

**Comment by dutchy1001** [comment]
I'm no dev either, just doing support so the devs don't have to spend time answering questions that I can help with. 
This is just 1 of those bugs that isn't a deal breaking issue unfortunately. When time permits someone will have a look.

**Comment by Kalepeer** [comment]
i  am still qwestioning why 3.10 was abandoned/ stopped when it was working
fine.

but thanks for your reaction and good luck with development of the current
version.

Op za 2 jan. 2021 12:49 schreef dutchy1001 <notifications@github.com>:

**Comment by Persei08** [comment]
@Kalepeer 
3.10 was working for you... on windows... but other users were experiencing issues especially on linux where fedora users were asking for an update of nwjs 0.30+. (3.10 was using nwjs 0.18). I'm a bit annoying by selfish users bitching around about the upgrade. Developers don't like to maintain obsolete version and live with too big technological debt. 
Today we are using 0.44.5 when they are at 0.50.3... the reason we don't use 0.50.3 is because we need a custom buils including extra codecs, now 3.10 source code is always availlable, you can try to compile it and you will see how it fail... but yeah 3.10 executable compiled years ago still works :/
