### ISSUE TITLE
more filter

### ISSUE THREAD

**Issue by aydinnmu** [popcorntime/popcorntime#1353]
Hi guys,

i want to feature request. Can you add more filter option under movies tab?
Nationally, award-winning?
and another request about search bar. Search bar only works if all words included. can you change to accept some of letters included.

**Comment by Persei08** [comment]
Filters are based on categories from trakt.tv api see PR #965 but BTW before adding other filter to PT client you have to implement them to Popcorn-api. 

Same for research, it request the popcorn-api. You should address issue there: https://github.com/popcorn-official/popcorn-api
