### ISSUE TITLE
Wrong Audio Language

### ISSUE THREAD

**Issue by Dranylis** [popcorntime/popcorntime#1355]
Operating System Version:
windows 10

Popcorn Time Version:
4.0

Download date:
a couple days ago with update

#### Expected Behaviour
I thought it would download in english
...

#### Actual Behaviour
for Constantine: city of Demons - The Movie, it downloads and plays in french
...

#### Steps to reproduce the behaviour

1. ... Find Constantine: City of Demons - The Movie in the database for English Audio
2. ... Replace the French file with the English file
3. ...

**Comment by apailleau** [comment]
Same issue for me on version 0.4.4 just reinstalled now, happens with Brooklyn Nine Nine S07E08 on either VLC or Butter player. Plays in french when all language settings are set to english

**Comment by Persei08** [comment]
Hi, I fear nobody here will check, movies are requested to YTS. This torrent is probably a multi-language release, but PT bundled player is only able to play default audio track.

As a workaround you can play the movie with VLC or another supported player and select the English audio track.
