### ISSUE TITLE
Popcorn-Time not working in Ubuntu 19.04

### ISSUE THREAD

**Issue by Loly2302** [popcorntime/popcorntime#1356]
Operating System Version:
 Ubuntu 19.04

Popcorn Time Version:
 I guess 3.10

Download date:
 a year ago

#### Expected Behaviour
 
...

#### Actual Behaviour
 not working
...

#### Steps to reproduce the behaviour
 Just try to use it.

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
It should works. Please provides more details or i close your issue because it doesn't explain anything.

3.10 is no longer maintained, you should use 4.4 at least: https://get.popcorntime.app/
