### ISSUE TITLE
Buffering is so slow on Linux

### ISSUE THREAD

**Issue by getsadzeg** [popcorntime/popcorntime#136]
Operating System Version:
Ubuntu Linux

Popcorn Time Version:
0.3.9

Download date:
Simply two days ago.
#### Expected Behaviour

I thaught that I would be comfortable with app, i.e watch movies fast and comfortably. 
#### Actual Behaviour

In general, app is good. But buffering is very,very slow despite of my internet connection is pretty good.

**Comment by nicolau10010** [comment]
@getsadzeg the buffering speed, in the end, relies on the torrent, and like any other torrent's service the seeders is what matters. Cheers!!

**Comment by getsadzeg** [comment]
Okay,got it.
