### ISSUE TITLE
help please popcorn time stuck on loading 

### ISSUE THREAD

**Issue by orantd** [popcorntime/popcorntime#1361]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by orantd** [comment]
Operating System Version: windows 10
Popcorn Time Version: Popcorn-Time 0.3.10
Download date: 18.04.2020

**Comment by outliners** [comment]
same here.

**Comment by dutchy1001** [comment]
please read through the issue's as this has been posted and fixed

Duplicate of #1321 #1346

**Comment by Persei08** [comment]
Duplicate of #1321

**Comment by orantd** [comment]
> fixed
 Thanks
It worked out for me

I changed dns address
8.8.8.8
1.0.0.1
