### ISSUE TITLE
Is no longer loading anything when I open it, it's just stuck on a loading icon

### ISSUE THREAD

**Issue by Rowda109** [popcorntime/popcorntime#1363]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.4.3-win32-Setup

Download date:
2020/04/08

#### Actual Behaviour
It's just stuck on a loading icon 
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by james-gould** [comment]
I had this yesterday, uninstall and reinstall and your issue should be fixed.

**Comment by dherykw** [comment]
same here, I have downloaded and installed again and I receive the next message when Popcorn-Time 3.10 tries to update to 4.4

```
app.js:21 [ERROR] updater.update() Error: invalid tar file(…)
``` 

editing → Downloading latest version from jenkins seems to work but I have had problems downloading from web

**Comment by dutchy1001** [comment]
Duplicate of #1321 #1346 

Try latest build [**here**](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/413/) as the main download page might be behind this version

**Comment by Persei08** [comment]
Duplicate of #1321 #1346 as @dutchy1001 said
