### ISSUE TITLE
Torrent downloading but playback freezes after some time

### ISSUE THREAD

**Issue by j-a-h-i-r** [popcorntime/popcorntime#1364]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date:

#### Expected Behaviour

File plays without interruption

#### Actual Behaviour

Playback starts normally but freezes after some random amount of time. Happens with MPC-HC. I've also tried with VLC, same behaviour.

**Comment by Persei08** [comment]
What is the health of the torrent ?
else, which movie/episode, which quality ?

**Comment by j-a-h-i-r** [comment]
Big bang theory. Tried several episodes of season 2/3. Health shows green
circle

**Comment by ar0ra1** [comment]
I reported the same issue but on Mac, check your CPU usage.

**Comment by Persei08** [comment]
Duplicate of #1350 #1373
