### ISSUE TITLE
popcorn time 0.4.4 gives 32 bit error,  0.3.10 has problems 

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1368]
Operating System Version:
 windows 7

Popcorn Time Version:

0.4.4 
0.3.10 
Download date:

18.04.2020 - 22.00
#### Expected Behaviour

...
0.4.4 - installed and to work
0.3.10 - installed and load the movies and TV shows... 

#### Actual Behaviour

...
0.4.4 - installed but didnt work, gives 32/64 bit warning message
0.3.10 - installed yet didnt load, ... API failed to response please check status.popcorntime.sh and try again later

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
0.3.10 is no longer maintained. You will have to change the Api urls yourself, in node_modules/butter-settings-popcorntime.io/index.js

0.4.4 should works, you probably installed the wrong version. Be sure to install the 32 bit or 64bit version depending your system: https://popcorntime.app/windows
