### ISSUE TITLE
The movie "handsome devil" plays the wrong video. Please check it out.

### ISSUE THREAD

**Issue by anonomistuser** [popcorntime/popcorntime#1370]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Hi, I fear nobody here will check, movies are requested to YTS. This torrent is probably a multilanguage release, but PT blundeled player is only able to play default audio track.

As a workaround you can play the movie with VLC or another supported player and select the english audio track.

**Comment by anonomistuser** [comment]
I don't understand, what should I do? the link open the wrong movie. The problem is the movie, not the subtext.

**Comment by Persei08** [comment]
My bad, I assumed it was wrong audio language.
But still, the movies are requested to yts.mx. if it's wrong on yts, it's wrong in PT too. So see with them on yts.mx
