### ISSUE TITLE
Sync With Trakt crashes Popcorn Time

### ISSUE THREAD

**Issue by AAT-100** [popcorntime/popcorntime#1372]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4-0 b2007377

Download date: 17th of April 2020

#### Expected Behaviour
Whan I click on 'Sync With Trakt' in Settings, I expect to update Seen/Not Seen movies and TV shows based on my Trakt.TV account. 
On Pocorn Time 0.3.10 it was taking some time, but eventualy the button turns green and all TV shows and movies are marked in accordance with the Trakt.TV data. 
The sane button works just fine on another PC with the same Win 10 and 0.4.4-0 Popcorn Time. They are both aged HW, working one CPU is Intel Core i5 and the 'having-the-problem' one is AMD Radeon, both have Nvidia GPU - the rest is basically the same. 'Having-the-problem' one needs a solution as the problem happens all the time without any exception.

#### Actual Behaviour
Instead of updating from Trakt, when I click Stettings->Sync With Trakt, Popocorn Time just crashes. I checked also 'Automatically Sync on Start' in Settings but it does not sync on start and all movies and TV shows are marked as not seen. Still, it states 'You are currently connected to Trakt.tv'.

#### Steps to reproduce the behaviour
Go Settings->Sync With Trakt.

**Comment by dutchy1001** [comment]
Cant reproduce this with build [416](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/416/) on a Windows 10 (intell i7) machine

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
