### ISSUE TITLE
having trouble with downloading and waching movies 

### ISSUE THREAD

**Issue by shannen123** [popcorntime/popcorntime#1378]
Operating System Version:  Windows 10? 

Popcorn Time Version:
What version of Popcorn Time are you running? 0.4

Download date:
  ive resetmy computer every time this has happened ive taken off my lock screen wifi is fine my computer is up to date with all of its software's im unable to download any movies or watch any as the same thing keeps on happening after a bit the popcorn closes down and wont open up 

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
I don't understand. Please use punctuation, describe what you want to do, and what happen. Thx

**Comment by kiriles90** [comment]
@Persei08 close this since the op doesnt seem to be coming back with those details?

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
