### ISSUE TITLE
No updates 

### ISSUE THREAD

**Issue by rebelbery** [popcorntime/popcorntime#1382]
Operating System Version:
OS X 10.11

Popcorn Time Version:
4.4

Download date
Last Friday (updated)

There were no updates in tv series since Sunday. Is it me or someone else also not seeing any updated in episodes?

**Comment by Persei08** [comment]
It is most probably an issue on eztv or popcorn-api. 

Please provides some series names which should have new episodes released since sunday, so we can check if new episodes were released on eztv.

**Comment by rebelbery** [comment]
Good girls, manifest, insecure, killing eve - these are ones I’ve checked.

**Comment by Persei08** [comment]
Ok, Thx

- Good girls, PT have last episode S03E09 added on eztv, which was added yesterday on eztv (eztv.io/shows/2694/good-girls/)
- Manifest, PT have the last episode S02E13 added on eztv, which was added last week on eztv (eztv.io/shows/3228/manifest/)
- Insecure, PT last episode is S04E01 while it's S04E02 on eztv, it was added yesterday on eztv (eztv.io/shows/2187/insecure/)
- Killing Eve, PT last episode is S03E01 while it's S03E02 on eztv, it was added yesterday on eztv  (eztv.io/shows/2857/killing-eve/)
- Westworld, PT last episode is S03E05 while it's S03E06 on eztv, it was added yesterday on eztv  (eztv.io/shows/2857/killing-eve/)

So, I cannot really confirm or not, but i think it took less time usually. 
For the moment, wait a bit more, maybe they will be referenced in few hours or tomorrow.

**Comment by dutchy1001** [comment]
Good Girls  "Incentive" broadcast 20-4-2020 is on PCT
Manifest "Icing Conditions" broadcast on 06-04-2020 was the last one and is on PCT
Killing Eve episode 2 broadcast on 19-04-2020 is indeed missing
Ozark released full season 3 released on 27-03-2020 only 3 episodes (1, 5 and 8)
Westworld S03 E06 · Decoherence broadcast 19-04-2020 missing

Hit and miss what is there or not

**Comment by Persei08** [comment]
Ozark, PT have all episodes listed on eztv ;)

**Comment by rebelbery** [comment]
Yeah. Almost all of them are on Ezra but not on popcorn. That’s why I am wondering is it me or the app

**Comment by dutchy1001** [comment]
Season 1 & 2 are there but this is what I get (using build 416)
![ozark](https://user-images.githubusercontent.com/5569980/79881553-42d38b00-83e9-11ea-92f7-b3e97699777c.png)

**Comment by rebelbery** [comment]
> Season 1 & 2 are there but this is what I get (using build 416)
> ![ozark](https://user-images.githubusercontent.com/5569980/79881553-42d38b00-83e9-11ea-92f7-b3e97699777c.png)

Same here

**Comment by Persei08** [comment]
- Insecure s04e02 now in PT
- Killing Eve S03e02 now in PT
- Westworld S03e06 now in PT

So, it needed more time I guess

**Comment by kiriles90** [comment]
@Persei08 close please since its not an actual issue?
