### ISSUE TITLE
Export/Import not working

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1383]
Operating System Version:
Windows 10

Popcorn Time Version:
Build 416

Download date:
21/04/2020

#### Expected Behaviour
after updating importing the database.zip back all settings and movies/series as it was before the update
...

#### Actual Behaviour
stuck at loading screen
...

#### Steps to reproduce the behaviour

1. create export file from settings
2. update PCT with a clean version (using the **win64-Setup** file)
3. start PCT go to settings and import database.zip made in point 1
4. stuck on loading screen (Status: init Database ...)

Log can be found [here](https://pastebin.com/5PaBVTqL)

After closing PCT I go to the install folder and delete the "C:\Users\MyPC\AppData\Local\Popcorn-Time\User Data\", restart PCT again to get a fresh "User Data" folder and add manual "bookmarks.db, movie.db, settings.db, shows.db and watched.db to the folder C:\Users\MyPC\AppData\Local\Popcorn-Time\User Data\Default\data which then gives me all my settings back.

(When using the **win64.zip** file and overwrite all files in the install folder this wont happen as you don't have to import the Database.zip)

**Comment by team-pct** [comment]
Can you upload an example of Database.zip so we can test here and fix it ?

**Comment by dutchy1001** [comment]
Last database.zip used is [here ](https://mega.nz/file/P8k1wLAJ#-oT3-IPvLu4UZ9_tVp2Bt4UirRi1DOnOo_423fw8Vi4). Previous made export files did all the same for me

EDIT:
Updated link working now.

**Comment by dutchy1001** [comment]
With Build 422 this issue seems to be fixed. I will open a new issue if it happens again.
