### ISSUE TITLE
Stopped working on Debian 

### ISSUE THREAD

**Issue by vimtechnologies** [popcorntime/popcorntime#1386]
Operating System Version:
<Deepin Linux - Debian >

Popcorn Time Version:

Download date:
<was installed long ago and always worked - stopped working about a month ago. Reinstalling it Did not fix the issue>

#### Expected Behaviour
<used to display movies>
...

#### Actual Behaviour
<does not display anything and the blue wheel keep spinning >
...

#### Steps to reproduce the behaviour
<not sure it just stopped working and nothing changed on the machine >

1. ...
2. ...
3. ...

**Comment by KingOrdinaryCitizen** [comment]
What's the version?

**Comment by Persei08** [comment]
Plz provides technical details.
Which version number have you tried to reinstall?
How have you installed it ? Which method ?
What happen when you try to launch it ?

Describes things a bit more.

**Comment by kiriles90** [comment]
@Persei08 close this since the OP doesnt seem to be coming back with those details?
