### ISSUE TITLE
Desktop app stuck on infinite loading screen

### ISSUE THREAD

**Issue by Snazzie** [popcorntime/popcorntime#1387]
Operating System Version:
Windows 10 latest updates

Popcorn Time Version:
v0.4.4

Download date:
today

#### Expected Behaviour
it to show me all the content

#### Actual Behaviour
stuck on infinite loading screen

#### Steps to reproduce the behaviour
1. launch the app

**Comment by Persei08** [comment]
Can't reproduce.

Did you updated from a previous version or is it a new install?

**Comment by Snazzie** [comment]
i tried both, first time it was update from previous version. then i tried fresh install.
I tried to go a version back aswell just incase latest installer is bugged.

Im not the only one having this issue, my friends are aswell.

are there any logs i can give?

**Comment by dutchy1001** [comment]
When you have PCT open click on F12, any log will be shown in the "console" tab. Copy/Paste here or use [Pastebin](https://pastebin.com/) and link it here.

**Comment by dutchy1001** [comment]
Any chance you imported a Database.zip from a previous installation?? If so look at #1383

**Comment by Snazzie** [comment]
```js

[ERROR] Error: addMembership EHOSTUNREACH Error: addMembership EHOSTUNREACH
    at Socket.addMembership (dgram.js:835:11)
    at addMembership (C:\Users\x\AppData\Local\Popcorn-Time\node_modules\node-ssdp\lib\index.js:182:19)
    at Socket.onSocketListening (C:\Users\x\AppData\Local\Popcorn-Time\node_modules\node-ssdp\lib\index.js:178:5)
    at Socket.emit (events.js:328:22)
    at startListening (dgram.js:153:10)
    at dgram.js:348:7
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:489:9)
win.error @ app.js:36


[ERROR] updater.update() Error: connect EACCES 104.26.13.130:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)
win.error @ app.js:36
```

**Comment by Snazzie** [comment]
> 
> 
> Any chance you imported a Database.zip from a previous installation?? If so look at #1383

no, ive even `flushed all databases`.

**Comment by Snazzie** [comment]
[pastebin](https://pastebin.com/y4Nht80p)

**Comment by Persei08** [comment]
@Snazzie retry to launch PT and before closing it, Open this url `https://movies-v2.api-fetch.sh/status` in browser, what do you see

**Comment by Snazzie** [comment]
> @Snazzie retry to launch PT and before closing it, Open this url `https://movies-v2.api-fetch.sh/status` in browser, what do you see

Im able to see the API response 
```json
{"repo":"https://github.com/popcorn-official/popcorn-api.git","server":"serv01","status":"Scraping YTS","totalAnimes":704,"totalMovies":16680,"totalShows":4113,"updated":1587553200,"uptime":19523,"version":"2.2.3","commit":"6c8a9a4"}
```

**Comment by quentincaffeino** [comment]
Same behavior. Flushing all helped.

**Comment by DiegoAstiazaran** [comment]
> Same behavior. Flushing all helped.

Same behavior, but flushing didn't help.

**Comment by Persei08** [comment]
I don't really understand :/

In advanced settings.

Disable "Continue seeding torrent after restart app?" and set "Maximum number of active torrents" to 1. Then restart PT and see if it works.

Also can you check that on movie tab, the category filter is set on "all" ?

How have you done your fresh install ? Are you sure you removed the settings folder ?

**Comment by Snazzie** [comment]
> I don't really understand :/
> 
> In advanced settings.
> 
> Disable "Continue seeding torrent after restart app?" and set "Maximum number of active torrents" to 1. Then restart PT and see if it works.

nope still not working.

> Also can you check that on movie tab, the category filter is set on "all" ?

[![Screenshot from Gyazo](https://gyazo.com/7ecd9e74eebbe3070db19962d93a8018/raw)](https://gyazo.com/7ecd9e74eebbe3070db19962d93a8018)

> How have you done your fresh install ? Are you sure you removed the settings folder ?

by uninstalling via programs and features, then executing the installer

**Comment by quentincaffeino** [comment]
Programs mostly don't remove their data folders on uninstall.
I don't use windows, but I'd suggest checking AppData folder and removing PT folder manually if present.

**Comment by Snazzie** [comment]
> 
> 
> Programs mostly don't remove their data folders on uninstall.
> I don't use windows, but I'd suggest checking AppData folder and removing PT folder manually if present.

i checked, it does remove it completely :) the folder path the uninstall proccess removes is `C:\Users\x\AppData\Local\Popcorn-Time\`

**Comment by dutchy1001** [comment]
there is also a folder made at:
C:\Users\x\AppData\Local\ **Temp** \Popcorn-Time

**Comment by team-pct** [comment]
@Snazzie Check your firewall rules about NWjs or popcorn time

**Comment by kaumudpa** [comment]
Totally Uninstalling the app and then reinstalling it works!

**Comment by Snazzie** [comment]
> C:\Users\x\AppData\Local\ **Temp** \Popcorn-Time

That gets cleared aswell

> @Snazzie Check your firewall rules about NWjs or popcorn time

I disabled my firewall just to be sure, still having the problem. Nothing really changed on my system, besides probably windows updates, the app just one day suddenly stopped working.

**Comment by Snazzie** [comment]
OMFG... i feel like an absolute idiot.    My NetLimiter had out blocker active on nwjs...
disabling that resolved the issue.

**Comment by Snazzie** [comment]
> Totally Uninstalling the app and then reinstalling it works!

i will relay this to my friends
