### ISSUE TITLE
Implement the ability to auto check for new version

### ISSUE THREAD

**Issue by longnd** [popcorntime/popcorntime#1390]
Operating System Version: **OS X 10.11**

Popcorn Time Version: 0.4.4

#### Expected Behaviour
The app should automatically check for a newer version if available & notify the user to update.
...

#### Actual Behaviour
No automation check is available. As a normal user, I have to go to the website to check and download.

**Comment by dutchy1001** [comment]
The auto update (Activate automatic updating) can be set (on default it's ticked) in the Settings-Miscellaneous section at the bottom

**Comment by longnd** [comment]
ah, it is hidden in the advanced settings. I didn't know that. Thanks.
