### ISSUE TITLE
Popcorn Time won't quit / close when the " X " button is clicked.

### ISSUE THREAD

**Issue by amberphoenix** [popcorntime/popcorntime#1391]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date: 22 / April / 2020

#### Expected Behaviour
I was trying to close the Popcorn Time application by clicking the X button and it wouldn't quit. Had to force quit it by using the Task Manager instead.

#### Actual Behaviour
The application doesn't quit when clicking the X button.

#### Steps to reproduce the behaviour

1. Open the Popcorn Time application and try selecting a movie to watch
2. Click Watch Now and allow the movie to begin to play
3. Once the movie is playing try clicking the x button to exit the movie and that woud take you to the movie's synopsis page
4. From there try clicking the Popcorn TIme X button to quit the app 
5. The Popcorn TIme app fails to quit.

**Comment by dutchy1001** [comment]
Really????

**Comment by ThomasVermeersch** [comment]
I have experienced the same issue, multiple times. And I am able to reproduce issue with the steps specified above

**Comment by omerl13** [comment]
Same. 

Error thrown saying it fails to remove the cache folder.

**Comment by dutchy1001** [comment]
Just read through the issue's and you will find similar issue's regarding this. Opening a new issue before reading through at least the first 2 pages is just being lazy.

**Comment by anicetoclucas** [comment]
Same to me.

**Comment by zilemax** [comment]
Its not working.I click watch movie and try to do all steps,but its not working,still dont want close on X

**Comment by KingOrdinaryCitizen** [comment]
Update your popcorntime.
Duplicate #1202 #1280

**Comment by Persei08** [comment]
Please search for similar issues before creating new ones.
Duplicate of #1280
