### ISSUE TITLE
The movies display screen is forever loading

### ISSUE THREAD

**Issue by raghottam96** [popcorntime/popcorntime#1393]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.3

Download date:
20/4/2020

#### Expected Behaviour
Display the movies list
...

#### Actual Behaviour
Stuck in a loading screen
...

#### Steps to reproduce the behaviour
don't know it happened suddenly

**Comment by maverick908** [comment]
Same problem...

Windows 7

**Comment by raghottam96** [comment]
It got solved with update
i.e Popcorn TV 0.4.4

**Comment by dobuora** [comment]
Since I updated to new Version Popcorn-Time-0.4.4-win64-Setup.exe it don't show any movies or series any more. Its stuck on loading...
