### ISSUE TITLE
OSX v0.4.4 Not compatible with 10.9.5

### ISSUE THREAD

**Issue by juanpc2018** [popcorntime/popcorntime#1395]
Operating System Version:
OSX 10.9.5 Mavericks

Web site: https://popcorntime.app says:
> For Mac OSX 10.7 and above
but .app is Incompatible "Requires 10.10 or later"

Previous:
https://github.com/popcorn-official/popcorn-desktop/issues/1247

**Comment by kiriles90** [comment]
@Persei08 duplicate issue, close please
