### ISSUE TITLE
Watch Now button not working, content not loading, "Remember Filters" not working

### ISSUE THREAD

**Issue by mmob91** [popcorntime/popcorntime#1399]
Operating System Version:

OS X 10.14.6 Mojave
Popcorn Time Version:

4.4
Download date:

I installed the newest version on April 18, 2020 but have used previous versions for years.
#### Expected Behaviour

Stream movies and series

#### Actual Behaviour

Does not load anything, the watch button does not work

#### Steps to reproduce the behaviour

1. Open the app
2. Select a movie or series
3. Click watch now

**Comment by mmob91** [comment]
I have also tried updating it with the new build that dutchy suggesten in another thread and still nothing. I tried clearing all databases, selecting and the selecting the "Remember Filters" option in settings. Nothing seems to work.

**Comment by kiriles90** [comment]
@Persei08 duplicate, close please
