### ISSUE TITLE
External torrent stuck at Resolving

### ISSUE THREAD

**Issue by yoplait2** [popcorntime/popcorntime#1402]
I find another issue with "slow external torrent", but not one with stuck at resolving step

Operating System Version:
OSX 10.15.4

Popcorn Time Version:
0.4.4,415

Download date:
19th April 2020

#### Expected Behaviour
Download and stream Torrent from another website
#### Actual Behaviour
Stuck at "Resolving"
...

#### Steps to reproduce the behaviour

1. Open the app 
2. Drag an drop torrent to stream
3. Torrent is never opening/downloading
![Capture d’écran 2020-04-25 à 19 57 46](https://user-images.githubusercontent.com/3725861/80286990-13958480-872f-11ea-9318-22ae20ff9b1f.png)

I have tried to change the cache directory to see if it is related to directory permission, no effect.
It seems like streamer.js is expecting the full path of te torrent but having instead the directory  so it gives EISDIR error.
I'm not familiar with Popcorn-Time code. Still trying to debug from my side.

 
Thanks

**Comment by KingOrdinaryCitizen** [comment]
Could you try a build >= 416?

**Comment by yoplait2** [comment]
Tried on 419 same results

**Comment by kiriles90** [comment]
To me it looks like its https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L166 that causes it.
When drag&dropping a .torrent it returns an error and `infoHash` remains blank so https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L185 tries to open the `../Torrentcache/` dir like if it was a file and it EISDIR's, ..while it normally returns the hash (and `infoHash` becomes that) when drag&dropping a magnet link so L185 works and those dont get stuck on resolving.

No idea how to correctly fix it though..

Also, duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1250

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/7dbe9f117887de8d0aa3c2ab55c87350e42a7ad3 fixed it and https://github.com/popcorn-official/popcorn-desktop/commit/84f99e746853510c1decab559a30eacf1f7e30ba removed the fix.

@team-pct any insight about this?

**Comment by yoplait2** [comment]
So I tried to modify the code inside the package to make it like this commit https://github.com/popcorn-official/popcorn-desktop/commit/7dbe9f117887de8d0aa3c2ab55c87350e42a7ad3 it works (surely not best development practice).
But not with all torrents some of them are stuck to "connection" status but no error is displayed in debug view moreover there is another bug 

Steps : 

1 Drag and drop the torrent
2 cancel 
3 drag and drop again 
![Capture d’écran 2020-04-27 à 21 08 11](https://user-images.githubusercontent.com/3725861/80410929-a1a67200-88cb-11ea-9555-5a6f06ea2460.png)

**Comment by kiriles90** [comment]
@yoplait2 yep https://github.com/popcorn-official/popcorn-desktop/commit/7dbe9f117887de8d0aa3c2ab55c87350e42a7ad3 still works, it probably got removed by accident.
But for the 'sometimes it doesnt work' bug its this https://github.com/popcorn-official/popcorn-desktop/issues/1274 (for both .torrents and magnet links, its the same one)

**Comment by kiriles90** [comment]
@yoplait2 your commit got merged and the bug was fixed thank you, close this when you can

**Comment by kiriles90** [comment]
@yoplait2 your PR got merged and this bug was fixed, thank you! close this when you can?

**Comment by yoplait2** [comment]
Thanks
