### ISSUE TITLE
external players not showing up on ubuntu 18.04.4

### ISSUE THREAD

**Issue by leenpaws** [popcorntime/popcorntime#1406]
Operating System Version:

Ubuntu 18.04.4 Gnome 3.34
Popcorn Time Version:

0.3.10
Download date:

4/12
#### Expected Behaviour

Previously installed it, it used to show external players in the "Watch Now" menu.

#### Actual Behaviour

Only shows the Popcorn Time player.

#### Steps to reproduce the behaviour

1. Install Popocorn Time, using nodejs v10 using npm build
2. try to play movie on vlc
3. notice the option is no longer there

**Comment by Persei08** [comment]
3.10 is no longer maintained, but VLC was well working as far as I remember.

What is your PT commit version? Check about view in PT, bottom right, after version nuumber you should have `HEAD(xxxxx)` what is the id between parenthesis ?

What is VLC version number ? Installed via official repos, or snap/flatpak packages ?

**Comment by leenpaws** [comment]
problem was solved by updating to latest stable version of nodejs(12.x)

**Comment by Persei08** [comment]
mmmh, PT use nwjs, which have node js bundled with it... it's weird or i missed something.... but i your issue is fixed, well, it's good
