### ISSUE TITLE
Remote control API not working for events with 'keydown' in player

### ISSUE THREAD

**Issue by toblich** [popcorntime/popcorntime#1407]
# Description

The `toggleplaying` and `togglemute` JSON-RPC calls made to the Remote Control API do not work inside the player view (the `toggleplaying` call does work inside the movie/episode details view, from which it does start to play). 

Investigating locally the issue with `toggleplay`, I understand that the Remote Control API just simulates a spacebar keypress
https://github.com/popcorn-official/popcorn-desktop/blob/44a283f2c89c5c5c6e28d258e134975ec17b850d/src/app/httpapi.js#L633

---
In the movie/episode details view, the space is registered and it works just fine
https://github.com/popcorn-official/popcorn-desktop/blob/44a283f2c89c5c5c6e28d258e134975ec17b850d/src/app/lib/views/movie_detail.js#L232-L234

---
In the player view though, the space is registered but specifies it requires a 'keydown', which the API call does not simulate
https://github.com/popcorn-official/popcorn-desktop/blob/44a283f2c89c5c5c6e28d258e134975ec17b850d/src/app/lib/views/player/player.js#L664-L666

---
The change that seems to break this appears to be https://github.com/popcorn-official/popcorn-desktop/blame/44a283f2c89c5c5c6e28d258e134975ec17b850d/src/app/lib/views/player/player.js#L666

## Details

Operating System Version: OS X 10.14.6

Popcorn Time Version: 4.4.0

Download date: 26 April 2020 (a couple hours ago)

#### Expected Behaviour

When I do the JSON-RPC call to `toggleplay` while in the player, it should pause/play the video

#### Actual Behaviour

While in the video player, it responds to my call but has no effect on the player.

#### Steps to reproduce the behaviour

1. Start Popcorn Time and begin playing any video in the embedded player
2. Make a JSON-RPC call to `toggleplay`. To do that, you can execute the following javascript (run `npm i jayson` first, and make sure to replace parameters with what you've set up for your Remote Control API in the advanced settings)
```js
const jaysonPromise = require('jayson/promise');

jaysonPromise.Client.http({ host: '192.168.0.3', port: 8008, auth: `${username}:${password}` }).request('toggleplay', []);
```

**Comment by kiriles90** [comment]
@Persei08 any idea about this since you just did https://github.com/popcorn-official/popcorn-desktop/pull/1744 ?

**Comment by Persei08** [comment]
those changes 'keydown' where introduced by PR #537... and seem we have a conflict

**Comment by Persei08** [comment]
@kiriles90 @ivan1986 ? Are you guys using non-latin keyboards ? if yes, were you having keyboard shortcuts issue before ? (before #537 was merged.. PCT 3.10 stable and before around dev builds 277)

I wonder what could the most acceptable solution for this, any suggestions everyone ?

**Comment by Persei08** [comment]
this httpapi.js need a good check and refactoring, if you call togglefullscreen method on movie_detail view it add the movie in favourite, which isn't expected.

I'll will just do quick fixes here because I think remote control deserve to work better, but I don't want to spend too much time on this too.

**Comment by kiriles90** [comment]
@Persei08 `Mousetrap.trigger('f');` seems to be the only one with duplicate function (in code atleast I dont know if you noticed anything more while using it)

Would something like https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/httpapi.js#L638L639 for the `f` in the player work? e.g

    server.expose('togglefullscreen', function (args, opt, callback) {
        var view = App.PlayerView;
        if (view !== undefined && view.player !== undefined) {
            Mousetrap.trigger('f');
            butterCallback(callback, false, {
                'fullscreen': win.isFullscreen
            });
            return;
        }
        butterCallback(callback, 'Can\'t toggle fullscreen, player is not open.');
    });

**Comment by Persei08** [comment]
lol i used line 415 `App.ViewStack[App.ViewStack.length - 1] === 'app-overlay'`... your comment is welcome :D
