### ISSUE TITLE
Download folder name named after the torrent hash and not after the video file

### ISSUE THREAD

**Issue by vageliskatsiotis** [popcorntime/popcorntime#1408]
Operating System Version:
Windows 10 and Linux

Popcorn Time Version:
0.4.4-1

Download date:
26/4/20

#### Expected Behaviour
Download torrent in folder named like the video file

#### Actual Behaviour
Downloads torrent in folder name named after the torrent hash.

#### Steps to reproduce the behaviour

1. Just stream anything

**Comment by KingOrdinaryCitizen** [comment]
As far as I know, this is intended.

Torrenthashes are, like the name suggests, unique. The name of a torrent isn't 100% unique.

**Comment by aaron-ic** [comment]
Putting the download into a folder named by the infohash does make it difficult to find the folder containing the movie/show that you're looking for. A large portion of multi-file torrents already contain a folder that is named after the video.

@KingOrdinaryCitizen Is the use of the infohash folder necessary so it's not possible to have more than 1 torrent occupying a folder and conflicting when the torrent is removed? It seems like something that would rarely happen but is confusing for users. Were there scenarios where the name of a file was shared across torrents, like the "Download from ..." source file?

**Comment by vageliskatsiotis** [comment]
> As far as I know, this is intended.
> 
> Torrenthashes are, like the name suggests, unique. The name of a torrent isn't 100% unique.

Sure, but in previous versions (I do not remember from which one it started) was not like this..

**Comment by ivan1986** [comment]
hm, for now we create file in torrent cache folder for write full magnet link and also we can save folder name for download

**Comment by vageliskatsiotis** [comment]
So, is not going to change..?

**Comment by ivan1986** [comment]
no, it's easy to change
i think need name like name-hash
but need looks from where get name

**Comment by rapito** [comment]
Please put this back how it was with the original name, append the hash if you want after the name of it.
Also you can definitely make the name unique if you name it wth "name (year)"

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
