### ISSUE TITLE
Incorrect color rendering

### ISSUE THREAD

**Issue by cristian-home** [popcorntime/popcorntime#1409]
Operating System Version:
Linux Ubuntu 19.10

Popcorn Time Version:
0.4.4

Download date:
April 25 2020

#### Expected Behaviour
Blue is expected to show up as blue
...

#### Actual Behaviour
The color blue is shown as purple
...

#### Steps to reproduce the behaviour
1. Install version 0.4.4
2. Start program

This problem has also been seen in Google Chrome and is corrected by changing the color profile to sRGB, it has also been seen in electron-based applications such as VisualStudio Code.

Expected view:
![image](https://user-images.githubusercontent.com/4079493/80317095-6b7fca00-87c7-11ea-9b61-5aa3f9f49555.png)

Actual view:
![Captura de pantalla de 2020-04-26 14-01-12](https://user-images.githubusercontent.com/4079493/80317145-9d912c00-87c7-11ea-8247-f2fae1375ed0.png)
![Captura de pantalla de 2020-04-26 14-01-22](https://user-images.githubusercontent.com/4079493/80317147-a1bd4980-87c7-11ea-90df-c57bd55e85de.png)
![Captura de pantalla de 2020-04-26 14-00-55](https://user-images.githubusercontent.com/4079493/80317151-a5e96700-87c7-11ea-8707-6bb1e94abdd8.png)

**Comment by Persei08** [comment]
How is this not related to your system ? 
I mean everybody have the same css files and colours, if it render differently for you and also impact other softwares, it mean the bug isn't specific to PT.

**Comment by Persei08** [comment]
I close this, unless someone have good argument that this is something to fix in PT, in this case i will reopen :/
