### ISSUE TITLE
Não tem filme Dublado! Porque?

### ISSUE THREAD

**Issue by VitorMoyses** [popcorntime/popcorntime#1410]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by cderivan** [comment]
lol, pega eles moyses :D :D

**Comment by Persei08** [comment]
Duplicate of #1110
