### ISSUE TITLE
It doesn't mark the episodes that I watched

### ISSUE THREAD

**Issue by aurileide** [popcorntime/popcorntime#1411]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
As far I can remember you have to click on the "eye" in the movies or on the series episode page yourself. I never seen this mark itself after watching.

**Comment by pcenta** [comment]
There is supposed to be some logic behind that auto marks episode as watched when you've watched it to some point.

**Comment by dutchy1001** [comment]
@pcenta 
Why?
People become lazy and think everything wil  be done for them.
For all those years I used PCT it never did, it's just something that you can mark yourself so you know what you have watched. Clicking that button is not the end of the world.

**Comment by pcenta** [comment]
@dutchy1001 I agree, I'd even say that auto marking it as viewed is not ideal, but I was just saying that I remember that it used to work like that.
But in the end some users will want that functionality, some will hate it and you need to draw a line somewhere unless you want infinite scrolll of settings.

**Comment by dutchy1001** [comment]
@pcenta 
I'm fine with clicking it myself, I luckily don't have to draw that line.

The more they add to more can go wrong the more ppl complain, 
the more they complain the more developers get fed up,
developers get fed up they leave, we end up with nothing...

**Comment by dijycorp** [comment]
Hi,
For information and for me, the click button work.
You actually have to close the tv-show window and re open it.
If you click manually one time as suggested, it will make it as not show...

**Comment by pcenta** [comment]
@dijycorp 
Just for a test, sounds like change gets saved but it's not shown to the user.
After some quick playing around, second click (not double click) successfully marks it as viewed.

**Comment by dijycorp** [comment]
As I say, if you activate the track tv provider, you will see the show mark as show in log with auto-maker. So two click will place the show as not play and play but in the UI it's will be the contrary.
It's just some problems about the UI refresh. 
I have the same problem when I mark a movie watch, as this moment, he will download and show the subtitle.

From previous versions, it's seen the event engine have change. I will check if I can compare and found the problem.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
