### ISSUE TITLE
Not loading for a month now and its the new update of popcorntime on windows 10.

### ISSUE THREAD

**Issue by Nkbaby** [popcorntime/popcorntime#1412]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
ever thought of reading through the issue's here and see for a solution?

Duplicate of #1361 #1363  #1393

**Comment by Persei08** [comment]
Please follow guidelines and make a valid report if necessary.
