### ISSUE TITLE
data loss and unresponsive interface after upgrading from older version

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#1413]
I'm on windows. How do I completely uninstall popcorn time and reset its settings? I want to do a completely clean re-install. Also, updating to the new version deleted all my watched "marks".

**Comment by dutchy1001** [comment]
duplicate of #1301  #1357 

in **advanced settings** is an option to **Export** your database and when installing a new version you can **Import** this. There is an issue #1383 with a temporally fix for Import/Export

**Comment by beppe9000** [comment]
ok, but to delete everything I just kill the folder in application data ?

also, regading interface bein unresponsive (many buttons not working, including close button) I want to see if resetting the settings fixes that....

**Comment by dutchy1001** [comment]
Both issue's you mentioned are already been posted with solutions or temporally fixes. Have you tried the latest build?
Latest build can be found **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/421/)**

**Comment by beppe9000** [comment]
ok I deleted the popcorn time folder in %appdata% and re-installed. now it works. maybe some leftover bit from 0.3 version
