### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1414]
Operating System Version: Windows 10 x64

Popcorn Time Version: 0.4.4-beta

Download date: April 26, 2020 (Auto updated)

#### Expected Behaviour
The close button must exit the app (popcorn time)

#### Actual Behaviour
It just shows the "clicked" animation, but nothing happens, popcorn time does not gets closed.

#### Steps to reproduce the behaviour
This may not happen if you reproduce it, it's subjective:
1) Open pt
2) Surf the movie/series list
3) Start watching anything you like
4) Close it
5) Now close popcorn time, it isn't closed, nothing happens by clicking the red cross button (top right)

**Comment by dutchy1001** [comment]
Duplicate of #1388 #1391

Bit of research before posting wont hurt

**Comment by ze0ss** [comment]
@dutchy1001 bruh

**Comment by pcenta** [comment]
@abh-oss01 
Can you post a screenshot or paste content of error in developer console? You can open it by pressing F12.

**Comment by ze0ss** [comment]
@pcenta I just updated to a ci build, apparently it's fixed in this build, so I can't see what error it gives now, but in any case, I'm sure there was no error, it just was broken in a way to be a fully useless button.

**Comment by Persei08** [comment]
Please search if report for your issue don't already exist before creating new one.
Duplicate of #1280
