### ISSUE TITLE
the app doesn't work well

### ISSUE THREAD

**Issue by ruicarvalh** [popcorntime/popcorntime#1415]
Operating System Version:

win 10
Popcorn Time Version:

0.4.4-0 beta
Download date:

24 of April 2020
#### Expected Behaviour

...what should you download movies and translations and turn off the app

#### Actual Behaviour

...

#### Steps tit does not turn off sometimes and often does not have translations and also often does not download movieso reproduce the behaviour

1. ...run the app
2. ...
3. ...

**Comment by Persei08** [comment]
Your issue is too vague and unclear, it will not help use enough.

Be more specific, and check if similar issue like your don't already exist. 
If needed, you can use translator like [Google Translate](https://translate.google.com/) or [DeepL](https://www.deepl.com/translator)
