### ISSUE TITLE
Downloads do not show up or show progress, but they download

### ISSUE THREAD

**Issue by Archundix** [popcorntime/popcorntime#1416]
Operating System Version:
OS X 13.1

Popcorn Time Version:
4.4

Download date:
4/27

#### Expected Behaviour
show download progress and speed
...

#### Actual Behaviour
does not show anything, but downloads
...

#### Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found?

1. Movies
2. Select Movie
3. Press Download

**Comment by antar88** [comment]
Same here. 

Also changed cache dir, related to this one: https://github.com/popcorn-official/popcorn-desktop/issues/1365

**Comment by antar88** [comment]
After restoring to default the cache path worked again. Maybe perms for the new path?

**Comment by Archundix** [comment]
> After restoring to default the cache path worked again. Maybe perms for the new path?

Good to know!! Never thought of that
Thanks!

**Comment by rapito** [comment]
Downloads also dont download subtitles.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
