### ISSUE TITLE
How can I install the last stable release on mac . I need 3.9.2 which was running before you released 4.0

### ISSUE THREAD

**Issue by iMansoorAliKhan** [popcorntime/popcorntime#1422]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
There is no 3.9.2. The latest version before v4 was 0.3.10 or 3.10.
3.10 is no longer maintained. Ask the community on reddit https://www.reddit.com/r/PopCornTime/ or the forum: https://discuss.popcorntime.app/ . Eventually some users will help you there
