### ISSUE TITLE
When running popcorn time it outputs: Opening in existing browser session and exit

### ISSUE THREAD

**Issue by ahfarouk** [popcorntime/popcorntime#1424]
OS: Linux (Ubuntu 20.04)
Popcorn time version:  4.4
Downloaded on 28/04/2020
Expected behavior: run the application and open application window
Actual behavior: 
if I run the application from the application desktop launcher nothing happens,
and when run from command line it says:
Opening in existing browser session. 
and then exits.

I am not sure what is the cause of this?  any help ?

Steps to produce:
Install application .deb on fresh ubuntu 20.04 install.
and when run it exits with the above message.

N.B. I tried to install by unpacking the zip file, and also by installing .deb file and both give me the same results

**Comment by Persei08** [comment]
Hi,
have you tried this way ? :

* Install unzip && dependencies (not sure if they are always necessary, but it isn't a big deal) :
`sudo apt update && sudo apt install unzip libcanberra-gtk-module libgconf-2-4 libatomic1`
* Create popcorn-time folder in /opt/ :  
`sudo mkdir /opt/popcorn-time`
* Download PT :  
`wget https://get.popcorntime.app/repo/build/Popcorn-Time-0.4.4-linux64.zip`
* Extract the zip in /opt/popcorn-time :  
`sudo unzip Popcorn-Time-0.4.4-linux64.zip -d /opt/popcorn-time`
* Create symlink of Popcorn-Time in /usr/bin :  
`sudo ln -sf /opt/popcorn-time/Popcorn-Time /usr/bin/popcorn-time`
* Create .desktop file (so the launcher) :   
`sudo nano /usr/share/applications/popcorntime.desktop`
* and copy paste the following text in the editor and save  

&nbsp;

    [Desktop Entry]  
    Version = 1.0
    Type = Application
    Terminal = false
    Name = Popcorn Time
    Exec = /usr/bin/popcorn-time
    Icon = /opt/popcorn-time/src/app/images/icon.png
    Categories = Application;

**Comment by ahfarouk** [comment]
I can confirm that after installing the dependencies and reboot it's now working.

Can you please update the readme file because the dependencies for Linux installation are not clearly mentioned. 

Thank you a lot.
