### ISSUE TITLE
Indie Tab is missing, or...?

### ISSUE THREAD

**Issue by fredphoesh** [popcorntime/popcorntime#1429]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4-0

Download date: 29-04-2020

#### Expected Behaviour - see the Indie tab, presumably for Indie movies?

...

#### Actual Behaviour not visible, despite it not being hidden in the advanced settings

...

#### Steps to reproduce the behaviour

1. ... open the app

**Comment by kiriles90** [comment]
indie tab got removed for good

@Persei08 close please
