### ISSUE TITLE
"Watch now" button doesn't work - movies/shows don't play.

### ISSUE THREAD

**Issue by stgrabowskii** [popcorntime/popcorntime#1430]
Operating System Version:
OS 10.12.6

Popcorn Time Version:
0.4.4

Download date:
29apr20

#### Expected Behaviour
Play the movies and shows selected.
...

#### Actual Behaviour
Nothing
...

#### Steps to reproduce the behaviour
I don't know.

1. ...
2. ...
3. ...

**Comment by afonsosantos** [comment]
Also happening to me.

Windows 10 Home, build 1909. Latest PopCorn Time version (0.4.4).

**Comment by pcenta** [comment]
@stgrabowskii @afonsosantos 
Can you provide a screenshot of an error in developer console?

**Comment by fbarbare** [comment]
I think this issue refers to this one #1340 , I have got the same problem and from what I have seen with Fiddler @pcenta there is some timeout happening on an IP based request. Not sure this helps.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
