### ISSUE TITLE
parental guide from imdb

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1431]
Feature Request.

Parental Guide is a powerful tool built into imdb that is able to tell potentially harmful scenes that may or may not be in the movie/ show about to be watched.
Currently, if i have to check this, i have to click on the movie imdb button and proceed to /parentalguide which shows results as submitted by users.
My suggestion. 
Popcorn time "already" has a way to have imdb link of a movie that is shown on the listing. I am asking there be a button "parental guide" which scrapes the imdb parental guide and puts it there. The issue would be of scraping only, everything else would be easy from there.

**Comment by test2a** [comment]
here. someone has already done the work. dont even have to do scraping
https://github.com/clamytoe/pguide
https://github.com/alberanid/imdbpy
Now, using this, all you have to do is show the output.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by test2a** [comment]
@kiriles90 was this implemented? not implemented?

**Comment by kiriles90** [comment]
![Capture](https://user-images.githubusercontent.com/38388670/94365657-57742780-00db-11eb-8f51-ec0fe9595bf3.jpg)

It was implemented. Wherever the API has parental guidance data (I think they are from traktv along with almost all the other metadata we fetch) Popcorn Time will show it.
