### ISSUE TITLE
New version's problems!!!!

### ISSUE THREAD

**Issue by MedDimessi** [popcorntime/popcorntime#1436]
Operating System Version: Windows 10

Popcorn Time Version: 4.4

1. Subtitles are all over the place, out-synced, it doesn't turn off when trying, the settings of it is confusing, user experience is not at all okey.
2. The downloading of the movie/series... doesn't work well on low network speed (it used to in older versions), when exiting and reopen the file (expected behavior: resume progress from last rupture. Actual behavior: restarts from the beginning.) 
3. The settings page is so limited, literally a fraction of control on what it was (again in older versions)
4. In conclusion, can the developers link the new API with the old version layout and interfaces with those particular features that it used the have??
At least give the users the option to use the version they do please and much more comfortable with.

**Comment by team-pct** [comment]
I am confused , all the issues you are talking about are not clear can you please report bugs

**Comment by MedDimessi** [comment]
I know this is not the right place to post this, but I didn't find a blog or a contact email that I can report to, all I can say that the user experience in the 4.4 version is really bad!
if you have a website or subreddit that tackles the issues I am trying to report please guide me to it.

**Comment by team-pct** [comment]
No you can report the bug here but Please with debugging i mean 
Subtitles issues? ok Give us a Movie or Tvshow where its out of sync did you know that subtitles are provided by opensubtitles.org ? 
2 - Downloading Do you know how torrenting work ? we are not hosting the content on our servers
3 - Settings page is limited how? have you taken a look in advanced settings ? what is missing comparing to 0.3.10? 
4 - Link the new api ? what do you mean?

https://discuss.popcorntime.app/ forum and reddit https://www.reddit.com/r/PopCornTime/

**Comment by MedDimessi** [comment]
I'll try my best to explain, i'll even take screenshots to be more clear, I
know how torrenting works.
[image: versioComparison.png]



As for the subtitles, even when I try to turn them off, they don't.
To be more specific about ' link to the new API', I like the older version
of the software, but as I understand, fetching movies and series in it
doesn't work anymore, so by "linking to the new API" I mean to connect the
older version app with the API that you use for the latest version of the
app!

**Comment by team-pct** [comment]
The image is not showing , 
for Applying the patch on previous version please read https://discuss.popcorntime.app/t/all-of-a-sudden-0-3-10-0-doesnt-work-anymore/287/36

**Comment by MedDimessi** [comment]
I have follow the instructions for applying the patch to the old version,
it works as expected, thanks for helping me.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
