### ISSUE TITLE
Watch Now button does not work

### ISSUE THREAD

**Issue by cfpotel** [popcorntime/popcorntime#1437]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1 - I open the program
2 - I click on Series
3 - Search and select the series
4 - I click on the episode
5 - Click on the Watch Now button
6 - Nothing happens

![Screenshot_1](https://user-images.githubusercontent.com/865690/80782662-7632ba00-8b4d-11ea-8ecc-40f17dd108c4.png)

**Comment by itsphysix** [comment]
I have exactly the same thing, I've tried with Movies, Series and even Anime tabs but the Watch Now button doesn't work.

**Comment by pcenta** [comment]
@cfpotel @itsphysix 
Can you post screenshot of console output in developer console?

**Comment by cfpotel** [comment]
Where do I find the console?

**Comment by cfpotel** [comment]
@pcenta 
Where do I find the console?

**Comment by pcenta** [comment]
@cfpotel 
F12 on keyboard will open developer console. There should be a bunch of normal log stuff, red one is what we're looking for.

**Comment by rosumatei** [comment]
same problem :(((

**Comment by aaron-ic** [comment]
Can everyone provide the information requested by the issue template? I.e. operating system and PCT version… This is working for most people so you’re going to have to help the devs work out what is so special about your situation.

**Comment by PiR1** [comment]
Same issue for me:
Operating System Version: W10 64bits
Popcorn Time Version: v0.4.4 HEAD(0c54b2cd)
Download date: 02/05/20

Console:
In my case, this error does not occur for all videos. Only on some of them.
When I click nothing happen, when I click once again I have this error.
![Capture02052020](https://user-images.githubusercontent.com/12834310/80871891-d4c37980-8cae-11ea-9e35-3d2e826c9b4c.PNG)

**Comment by PiR1** [comment]
And if I click on "Download" I have this issue
![Capture02052020-2](https://user-images.githubusercontent.com/12834310/80892337-81125980-8cc9-11ea-8fc7-6b71c17aa733.PNG)

**Comment by mellingham** [comment]
Same issue.

Operating System Version: W10 64bits
Popcorn Time Version: v0.4.4 (also happened with previous build)
Download date: 03/05/20

My console output reads the same as @PiR1 

If I click the watch button several times it will eventually work.

Also have similar issue in that the X to close button doesn't always work.

**Comment by pcenta** [comment]
I'll try to look into that although currently the situation is that I can't replicate your issue.
Meanwhile you can try with updating to the latest [build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/423/) (do mind to backup your database).

@mellingham 
As for the close button. Do you mean that you click it and it doesn't close so you have to click it several times? If so, try to click it once and wait for a few moments. With default settings app goes and deletes downloaded files and that can take a moment.

**Comment by fbarbare** [comment]
It seems it's coming from the `selectFile` function in the `streamer.js` file

```js
            this.torrentModel.set('video_file', {
                name: path.basename(torrent.files[fileIndex].path),
                size: fileSize,
                index: fileIndex,
                path: path.join(torrent.path, torrent.files[fileIndex].path)
            });
```

`torrent.files` is empty for some reason so it cannot read the property `path` of `torrent.files[fileIndex]` as it's `undefined`

**Comment by Persei08** [comment]
Duplicate #1340

**Comment by mellingham** [comment]
> @mellingham
> As for the close button. Do you mean that you click it and it doesn't close so you have to click it several times? If so, try to click it once and wait for a few moments. With default settings app goes and deletes downloaded files and that can take a moment.

Thanks for the reply. I will check that out and let you know. It does seem to take a long time and also doesn't respond to ALT F4.

**Comment by Persei08** [comment]
@mellingham the bug for closing PT is another issue. check #1280.
One issue per report ;)

oops, and it's fixed since [dev builds](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/) 416 I think

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
