### ISSUE TITLE
Cannot open TV shows

### ISSUE THREAD

**Issue by Lusitaniae** [popcorntime/popcorntime#1439]
Operating System Version:
Linux

Popcorn Time Version:
0.4.4

Download date:
2/3 weeks ago

#### Expected Behaviour
Select TV SHOW 
Display list of episodes/seasons

#### Actual Behaviour
Loading TV show stuck at loading

#### Steps to reproduce the behaviour

Only thing in console is 
```[INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,```

**Comment by dutchy1001** [comment]
If you updated from the main webpage you might not have the latest build. Click **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/)** to download the latest. 
If you use the **"setup"** version make sure you **"export"** the database, you can find this in "Advance Settings", this way you avoid to lose all watched movies and series.
If you use the .zip file you probably know what your doing.

**Comment by Lusitaniae** [comment]
I installed the latest .deb from GH releases.

In the info page I can verify I'm running 0.4.4.

I have another data point, 
the same TV show, will work when I open from Series tab, but won't work from the Liked" tab

**Comment by dutchy1001** [comment]
Did you use the link I provided in my post? (this way I know for sure you got the latest (at time of writng))
I presume you you mean with "liked" tab your **Favorites** tab.
If you delete a serie and re-add it from the series tab will it work then??

**Comment by Lusitaniae** [comment]
Thanks for the support @dutchy1001 

I've reinstalled using the .deb listed in url you provided now

It seems the favorite tab is now completely gone. Cannot find it anymore, but I can see the database is still there, I can do mouseover the movie/show and see the heart button in red for my shows.

![image](https://user-images.githubusercontent.com/58325/80872283-2a158000-8cdb-11ea-8b67-5b3789e96ba2.png)


I also see a new error in the console

```
[ERROR] Error: not a number: buffer[0] = 80 Error: not a number: buffer[0] = 80
    at getIntFromBuffer (/opt/Popcorn-Time/node_modules/bencode/lib/decode.js:42:11)
    at Function.decode.buffer (/opt/Popcorn-Time/node_modules/bencode/lib/decode.js:158:16)
    at Function.decode.next (/opt/Popcorn-Time/node_modules/bencode/lib/decode.js:98:21)
    at Object.decode (/opt/Popcorn-Time/node_modules/bencode/lib/decode.js:81:17)
    at decodeTorrentFile (/opt/Popcorn-Time/node_modules/webtorrent/node_modules/parse-torrent/index.js:110:23)
    at parseTorrent (/opt/Popcorn-Time/node_modules/webtorrent/node_modules/parse-torrent/index.js:35:12)
    at parseOrThrow (/opt/Popcorn-Time/node_modules/webtorrent/node_modules/parse-torrent/index.js:94:23)
    at /opt/Popcorn-Time/node_modules/webtorrent/node_modules/parse-torrent/index.js:78:7
    at /opt/Popcorn-Time/node_modules/simple-get/index.js:89:7
    at IncomingMessage.<anonymous> (/opt/Popcorn-Time/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:422:28)
    at IncomingMessage.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
win.error @ app.js:36
(anonymous) @ app.js:923
emit @ events.js:316
(anonymous) @ internal/process/execution.js:165
```

**Comment by dutchy1001** [comment]
I'm sorry I missed your using a Linux version. I don't do the coding, just trying to help out with the simple errors people have.
The favorite tab is still there, you mean it's empty. In my first message I did say to "**export**" the database, this way you always have a backup incase things go wrong. What if you re-add a serie, does it then show up in the favorite tab (with all the watched episodes)?
One of the devs need to look at the error code you posted, I can't do anything with it.

**Comment by Lusitaniae** [comment]
ah nevermind, I was looking for a :heart: on the right  hah

Didn't have to backup the favorites, I reinstalled the deb package, everything still in place.

The problem is still there, cannot open a show from the favorites tab.

**Comment by aaron-ic** [comment]
What is the show and how long ago were the episodes aired?

I have a suspicion that torrent that have very few seeders will take a while to get started, particularly if they are magnet links that require metadata to be retrieved. In that case I’ve seen that the “stream starting” view does not appear until the link has been resolved.

**Comment by Lusitaniae** [comment]
Is seal team, is on top of the shows list. Should be popular enough?!

**Comment by Lusitaniae** [comment]
And the issue is it  doesn't load episode list. This comes from some API not torrents ?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
