### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by TheRealBobRed** [popcorntime/popcorntime#1440]
Operating System Version:
Windows 10?

Popcorn Time Version:
Latest Update 4.4

for some reason after some time I am getting an infinite loading when trying to load popcorn time.

view screenshot https://ibb.co/GxpSXDB

**Comment by dutchy1001** [comment]
If you updated from the main webpage you might not have the latest build. Click **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/)** to download the latest. 
If you use the **"setup"** version make sure you **"export"** the database, you can find this in "Advance Settings", this way you avoid to lose all watched movies and series.
If you use the .zip file you probably know what your doing.

**Comment by TheRealBobRed** [comment]
> If you updated from the main webpage you might not have the latest build. Click **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/)** to download the latest.
> If you use the **"setup"** version make sure you **"export"** the database, you can find this in "Advance Settings", this way you avoid to lose all watched movies and series.
> If you use the .zip file you probably know what your doing.

Gotcha, thanks a lot 👍

**Comment by dutchy1001** [comment]
If you got it sorted please close the issue

**Comment by marinaview** [comment]
It is happening to me since the 20th May
I download from https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/  and it didn't help

**Comment by dutchy1001** [comment]
Maybe try the latest dev build from [**here**](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)

Backup your db's by "Export Database" (you can find that in your "**Advanced**" settings tab) and do a clean install to avoid leftovers from previous builds. 
Build 423 should work as the issue you refer to has been fixed a few builds back of 423.

**Comment by fisforfaheem** [comment]
i hope this thing gets cured in final verison

**Comment by Archer11111** [comment]
Make sure your PT is downloaded from Popcorntime.sh
Also, change your DNS to google/cloudflare/etc and see if it loads. If it does it means your ISP has the API URLs blocked. In this case, you can either stay with the DNS change or if you also want to be protected from piracy/copyright laws, etc, use a VPN. 
I fixed mine finally via the [tips here >>](https://www.winxdvd.com/resource/popcorn-time-not-working-error-loading.htm)

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
