### ISSUE TITLE
Settings view not openning when clicking cogwheel and UI language set to French

### ISSUE THREAD

**Issue by ojazzd** [popcorntime/popcorntime#1441]
Operating System Version:
OS X 10.11, Ubuntu 18.04

Popcorn Time Version:
0.4.4, dev build 421, dev build 423

Download date:
30 Avril 2020

#### Expected Behaviour
Clicking cogwheel icon should load settings view

#### Actual Behaviour
Nothing happens. Error is thrown:
![Screenshot_2020-05-04_10-54-52](https://user-images.githubusercontent.com/22459458/80950464-33473f80-8df6-11ea-9422-e6dede2a8921.png)

```
common.js:111 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.Common.fileSize (common.js:111)
    at eval (eval at m.template (underscore.js:1454), <anonymous>:413:16)
    at c (underscore.js:1461)
    at Object.render (renderer.js:24)
    at n._renderHtml (view.js:154)
    at n._renderTemplate (view.js:148)
    at n.render (view.js:124)
    at $ (view.js:12)
    at constructor.show (region.js:75)
    at n.showChildView [(regions.js:150)]
```

*Related code* (common.js line 111):

```js
    if (Settings.language === 'fr') {
        unit = unit.replace('B', 'o');
    }
```

#### Steps to reproduce the behaviour

1. Launch PT,
1. Select Series tab
1. Go to settings and switch PT UI language to French
1. Go back to series tab,
1. Try to click settings icon (cogwheel)

**Comment by Persei08** [comment]
Steps to reproduce?

**Comment by Persei08** [comment]
Was able to reproduce on linux ubuntu 18.04 with (0.4.4) dev build 421 and 423.

edit: i've updated the issue description

**Comment by Persei08** [comment]
As a workaround, you can start to watch a movie ("Visionner maintenant" button), then cancel ("Annuler"), and the click on cogwheel will works as expected
