### ISSUE TITLE
vpn i already use but ask for vpn Can i choose somewhere ?

### ISSUE THREAD

**Issue by JohanvdS** [popcorntime/popcorntime#1442]
Operating System Version:
 Linux ubuntu 20.04
Popcorn Time Version:
today 

#### Expected Behaviour
 going to mine own vpn ( lockbutton) above
...

#### Actual Behaviour
 is asked for having and buy vpn
...

#### Steps to reproduce the behaviour

1. ... if you already use vpn click on this 
2. ...app to connect your own vpn
3. ...

**Comment by pcenta** [comment]
@JohanvdS 
You can disable VPN from settings.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
