### ISSUE TITLE
Can't play any movies from my favourites.

### ISSUE THREAD

**Issue by Sexycat369** [popcorntime/popcorntime#1446]
Operating System Version:

OSX 10.14

Popcorn Time Version:

0.4.4.

Download date:

1 year ago

#### Expected Behaviour

In the favourites tab I have movies saved. Normally it shows all the movies covers and when I click it it shows the menu to stream the movie. 

#### Actual Behaviour

However, since a few weeks, all the covers of the movies are gone. And when I click on the movie to play it, the buttons to play the movie are all gone. And the magnet that shows the seeding activity Is grey. So I can't stream the movie I have added to my favourites. If I look for the movie in the search bar, the movies are still not streamable. Only the movies that I added to favourites recently, show a coloured cover, and are streamable. 
<img width="1440" alt="Schermafbeelding 2020-05-03 om 12 31 38" src="https://user-images.githubusercontent.com/64730314/80911977-26fdac80-8d3a-11ea-9d5e-09d134f14e68.png">
<img width="1438" alt="Schermafbeelding 2020-05-03 om 12 31 29" src="https://user-images.githubusercontent.com/64730314/80911978-27964300-8d3a-11ea-8954-689587c32722.png">

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
