### ISSUE TITLE
Can't select download folder

### ISSUE THREAD

**Issue by cypriankoech** [popcorntime/popcorntime#1448]
Operating System Version: Ubuntu 19.10

Popcorn Time Version: 4.4

Download date: May 1 , 2020

#### Expected Behaviour

Allow me to select download(cache) location

#### Actual Behaviour

Theres a choice to view download folder, but no option to change it

#### Steps to reproduce the behaviour

1. Go to settings
2. Click show advanced settings
3. Scroll down to cache directory
4. Folder Icon present, only allows you to view download folder , cannot change it

![proof](https://user-images.githubusercontent.com/59407091/80915503-6983b100-8d5b-11ea-96f5-05f0afef6aea.png)

**Comment by KingOrdinaryCitizen** [comment]
Just change the url in the textbox?

**Comment by cypriankoech** [comment]
Thank you for responding , but...

I have done that already by pasting of course ...it still doesn't work,  in
fact when I restart the app the url changes back to tmp/Popcorn-time

**Comment by Persei08** [comment]
when you click the cache directory value field, it should open your file explorer to select a folder

**Comment by kiriles90** [comment]
@Persei08 close since this is not an issue?

**Comment by cypriankoech** [comment]
Oooh ok
