### ISSUE TITLE
Movies Response is Coming as String in _formatForPopcorn()

### ISSUE THREAD

**Issue by amankgo** [popcorntime/popcorntime#1450]
In the below code, I am getting the response as String in **Movies** tab on latest Jenkins build #423. 
https://github.com/popcorn-official/popcorn-desktop/blob/875efc1443493bc5fb5f5fa3ff5b9a10b9afa85d/src/app/butter-provider/movie.js#L80

In the code below, because the above object is String, it is throwing error.
https://github.com/popcorn-official/popcorn-desktop/blob/875efc1443493bc5fb5f5fa3ff5b9a10b9afa85d/src/app/butter-provider/movie.js#L22

OS: Mac 10.15.2
Build: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/ (OSx64)

**Comment by amankgo** [comment]
Any updates?

**Comment by kiriles90** [comment]
@amankgo it might be me not understanding the issue but.. where is the error? The provider works fine.

**Comment by amankgo** [comment]
@kiriles90 I have been able to run the program properly so maybe it was an issue then. I think you can close this for now.
