### ISSUE TITLE
Eteindre

### ISSUE THREAD

**Issue by mommarin22** [popcorntime/popcorntime#1451]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by mommarin22** [comment]
Bonjour,
je n’arrive pas à fermer la nouvelle version!!
Bug ou mauvaise version?
Merci
0.4.4-0 "Love in the Time of Corona" Beta - HEAD (b2007344)

**Comment by Persei08** [comment]
Duplicate of #1280
