### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by speedy1076** [popcorntime/popcorntime#1453]
Operating System Version:

windows 10
Popcorn Time Version:

04.4.0
Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...randomly crashes

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Any additional info welcome

**Comment by kiriles90** [comment]
@Persei08 close?

**Comment by kiriles90** [comment]
@Persei08 close please
