### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MrTana** [popcorntime/popcorntime#1459]
Operating System Version:  Windows 10

Popcorn Time Version: 0.4.4

Download date: April 2020

Actual Behaviour : Eternal loading, can see the interface but no content at all.

![PCT](https://user-images.githubusercontent.com/28660493/80993668-c191e480-8e3b-11ea-95dc-fa8532d4cb34.png)

**Comment by Persei08** [comment]
Please follow guidelines and make a valid report.
