### ISSUE TITLE
App doesn't work well

### ISSUE THREAD

**Issue by OwellR** [popcorntime/popcorntime#1461]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
18/5/2020

Expected Behaviour
Display the movies list
...

Actual Behaviour
Stuck in a loading screen
...

Steps to reproduce the behaviour
don't know it happened suddenly

**Comment by paramvir-phagura** [comment]
Can confirm it started happening suddenly, just hangs on the loading screen. Sometimes can't even close app and have to close it via task manager.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
