### ISSUE TITLE
The Office 

### ISSUE THREAD

**Issue by MaeBeterraba** [popcorntime/popcorntime#1462]
In the previous update, I had access to all the seasons of The Office, but now it's all messed up and switched up so I can't really watch it here

**Comment by snowc0de** [comment]
I don't know if this really depends on Popcorn Time. I am not a dev but I know the torrents are managed by YTS.

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents. 
Asking here to add movies or series is not the right place as they have no control over what's added and not.

**Comment by Persei08** [comment]
I close. Check @dutchy1001 comment
