### ISSUE TITLE
The Vampire Diaries

### ISSUE THREAD

**Issue by caitlinlex** [popcorntime/popcorntime#1464]
Operating System Version:
Mac OS X 10.12.6
Download date:
May 18, 2020

The Vampire Diaries Season 1 will play audio but has no video.
Thanks

**Comment by Persei08** [comment]
Video codec issue. The video codec used to encode the video isn't supported by PT bundled player.
Use an external player like VLC, IINA, ... ([list of supported external players](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js)).

Install the player, restart PT, select episode, click the icon of the "watch now" button, It should display a list of detected players, select the one you want and click "watch now".
