### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by FAQuller** [popcorntime/popcorntime#1467]
Operating System Version: Mac Mojave 10.14.6

I have a VPN working. Whenever I want to see a film,
popcorn says I cannot and should install a VPN.
The red lock above the screen is flickering, as if I 
do not have a VPN. But I have. Each time, I want
to see a move, I get a screen with two options:
cancel OR install a VPN. (Catch 22.) There is no option: continue.
Now what?

**Comment by Persei08** [comment]
Please search for similar issues before opening new ones.
If you wait some seconds it will continue downloading, there is no obligation to click the other buttons.
This said you will be probably interested into disabling this option by going into advanced settings and disabling "enable VPN" option.
