### ISSUE TITLE
Chromecast with multiples network interfaces not work

### ISSUE THREAD

**Issue by figui** [popcorntime/popcorntime#147]
Operating System Version: Windows 10, Ubuntu 15.10

Popcorn Time Version: 0.3.9-0

Download date: 12/04/2010

#### Expected Behaviour

Play a movie and stream through Chromecast
...
#### Actual Behaviour

Chromecast option does not appear
...
#### Steps to repoduce the behaviour

1. Install VirtualBox and check that create another network interfaces
2. Create multiple virtual machines
3. Open Popcorn time, and check that Chromecast options does not appear

I think that chromecast discovery are trying in one network interface, if we've got many networks interfaces. the process fails and chromecast option does not appear

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/ Can you try the last build ?

**Comment by figui** [comment]
Hi, the problem still there

P.D: Sorry for the delay
