### ISSUE TITLE
Torrent Collection and magnet links and search

### ISSUE THREAD

**Issue by hunter-ep** [popcorntime/popcorntime#1471]
Operating System Version:
<Windows 10>

Popcorn Time Version:
<0.44 , #423 from the CI website>

Download date:
<2020-05-09>

#### Expected Behaviour
<The torrent collection section will work either by .torrent file or magnet>

The recent updates are very good and an improvement from the last updates finally fixed the popcorn player although it buffers or lags when there is anything else running but it does the work

The app is working very well compared to before

BUT....

//The torrent collection section is very important when you don't find the file you want, or you want a better quality and in the recent updates it stopped working which is very bad, sometimes it catches the file but most of the times it is stuck on the download screen// 

Also, the torrent collection search should work and it best linked to popular websites exp.(13*7)

also the new download section doesn't work

Still great work recently :)

All the best.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
