### ISSUE TITLE
Can't cast

### ISSUE THREAD

**Issue by DayWallker** [popcorntime/popcorntime#1473]
Operating System Version:
Windows 10

Popcorn Time Version:
4.4

Download date:
5.15.20

Download url (optional):

#### Expected Behaviour
Cast to Samsung TV

#### Actual Behaviour
Don't have a casting button

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
There is no cast button, your device is in the dropdown menu next to the 'Watch now' button. Select it there.

@Persei08 close please
