### ISSUE TITLE
Latest Version - Can't Close program. Alt + F4, End Task, don't work. 

### ISSUE THREAD

**Issue by Unkn0wnfear** [popcorntime/popcorntime#1474]
Operating System Version:

Windows 10

Popcorn Time Version:

0.4.4-0
Download date:

I recently re-installed it, so under a week ago. 

Download url (optional):

https://get.popcorntime.app/build/Popcorn-Time-0.4.4-win64-Setup.exe
#### Expected Behaviour

Be able to close.

#### Actual Behaviour

Not close. It's like a phantom app. It still functions, but it wont show up in my Task Window and the X doesn't close it. Nothing closes it except a full computer restart. 

#### Steps to reproduce the behaviour

Simply opening the program.

**Comment by Persei08** [comment]
Issue already reported. Please think to search similar issues before opening new ones. Thx
