### ISSUE TITLE
After playing film, does not return to the same place in the catalogue of films

### ISSUE THREAD

**Issue by JosiahCarberry** [popcorntime/popcorntime#1475]
Operating System Version:

Ubuntu 20.04

Popcorn Time Version:

0.4.4-0
Download date:

April 2020
Download url (optional):

?
#### Expected Behaviour

After viewing a film and clicking on X I expect to return to the same place in the catalogue of films from which the film was initially selected

#### Actual Behaviour

Instead, the display of the catalogue of films skips some 30-50 films lower in the list

#### Steps to reproduce the behaviour

1. Open Popcorn time
2. Change Sort by to Last Added
3. Scroll down the list  some arbitrary amount (say, 100 films)
4. Click on a film 
5. Click on Watch now
6. After the film return to the screen with the Watch Now button
7. Click on the X in the upper right corner to return to the catalogue of films
8. You are in a completely different place now, some 30-50 films lower in the list.

#### Screenshot of error from developer console (optional)

N/A

**Comment by Persei08** [comment]
Can't reproduce on dev branch, apparently was fixed
