### ISSUE TITLE
Remember filters issue.

### ISSUE THREAD

**Issue by Aky96** [popcorntime/popcorntime#1476]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4 build 424

Download date:
22-May-20

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

#### Expected Behaviour
Tick remember filters in advanced settings and app to work as expected.
...

#### Actual Behaviour
Remember filters does work when selected however the issue is when you go to the movies or series tabs the screen will not load until you change the sort by to another setting. Unticking remember filters the screens will load normally in any sort by setting.
...

#### Steps to reproduce the behaviour

1. Tick remember filters in advanced settings
2. Switch to Movies or Series tabs and screens will not load until sort by changed.
3. Untick remember filters and screens will load with no change required.

**Comment by Aky96** [comment]
Update to the issue detailed above:  Just installed build 430 and tried the remember filters option in settings. It will now load the Series section without having to change the sort-by to another option however the Movies section still has the above issue.

**Comment by Aky96** [comment]
Using build 438 and this issue now seems to have been fixed. Both Movies/Series will now load when the 'remember filters' option has been selected.

**Comment by Aky96** [comment]
Sorry to report this but this issue is still present.  I'm currently using build #441and I've now worked out that this issue occurs as soon as you use the search function from the apps taskbar for the first time. Once 'Remember Filters' is selected you can bookmark anything which is showing in either the movies or series screens and the app will respond as expected however if you then have to search for a movie or series then this is when the issue detailed above starts.

**Comment by kiriles90** [comment]
@AKy96 If you are up for a little manual edit, until the next dev build is out try doing https://github.com/popcorn-official/popcorn-desktop/pull/1804/files and tell me what you think.

**Comment by Aky96** [comment]
@kiriles90 I've made the changes, tried various settings and that has fixed the issue. Me and my OCD offer you many thanks as I can now have my favourites in alphabetical order once again!
