### ISSUE TITLE
the last kingdom season 4: the 5 and 8 chaptor of the latest season is missing a popcorn time is it possible to put in online

### ISSUE THREAD

**Issue by Harden130** [popcorntime/popcorntime#1478]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents. 
Asking here to add movies or series is not the right place as they have no control over what's added and not.

**Comment by Persei08** [comment]
I close this. check @dutchy1001 comment. Thx
