### ISSUE TITLE
Watching a series does not auto start the next episode

### ISSUE THREAD

**Issue by anselantz** [popcorntime/popcorntime#1483]
Operating System Version:

Windows 10
Popcorn Time Version:

Popcorn-Time 0.4.4

Download date:

At least 3 years ago, updated about a month ago

Download url (optional):

#### Expected Behaviour

Play the next episode in the series

#### Actual Behaviour

Goes back to the episode list

#### Steps to reproduce the behaviour

1. Watch an episode to the end.
2. ...
3. ...

**Comment by camila-araujo** [comment]
it happens to me too

**Comment by Persei08** [comment]
Duplicate of #1352
