### ISSUE TITLE
The feed is not updating...

### ISSUE THREAD

**Issue by marinaview** [popcorntime/popcorntime#1484]
Operating System Version:

Windows 10
Popcorn Time Version:4.4.0   from Jenkings  HEAD fc976813

Download date:

Download url (optional):

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/423/

#### Expected Behaviour

Retrieve the latest series that have been updated

#### Actual Behaviour

I hangs and when you change the filter it loads the same version that the last time

#### Steps to reproduce the behaviour

1. ...Open the Application 
2. ...Select Series
3. ...Change "order by" to a different option
4.... Change "order by" to "latest updates"

I shows the list retrieved the 20th May

#### Screenshot of error from developer console (optional)

![imagen](https://user-images.githubusercontent.com/65876488/82768641-28496300-9e28-11ea-89dd-c3bd46f4f220.png)

**Comment by Persei08** [comment]
Genre (Género) is empty in your screenshot. Pretty sure this is what cause the bug.

**Comment by marinaview** [comment]
I'm not so sure if it was that...
It started to update itself again today and it was still empty
I'll kep it in mind if it happens again

**Comment by Persei08** [comment]
Genre isn't supposed to be empty, by default it should be on "ALL", but I think it's bugging sometimes.
Do you have "Remmeber filters" option enabled? I think it's related to this.
