### ISSUE TITLE
Subtitle not shown when casting to google chrome cast

### ISSUE THREAD

**Issue by junda15** [popcorntime/popcorntime#1486]
Operating System Version:
Windows 10 Home

Popcorn Time Version:
0.4.4-0

Download date:
12 May 2020

Download url (optional):

#### Expected Behaviour
Cast to google chrome cast with subtitle being cast too
...

#### Actual Behaviour
Cast to google chrome cast without subtitle, view on popcorn time app and there is subtitle
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
@Persei08 close please
