### ISSUE TITLE
popcorn desktop do not show any catalog of movies or series

### ISSUE THREAD

**Issue by kalashnikov2** [popcorntime/popcorntime#1487]
Windows 10

v0.4.4

Download date:
25/5/2020

Download url (optional):
https://ci.popcorntime.app/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/artifact/build/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
normally open catalog

#### Actual Behaviour
app loads but not catalog is displayed on the program

#### Steps to reproduce the behaviour
just open 

#### Screenshot of error from developer console (optional)

![imagen](https://user-images.githubusercontent.com/44566/83036743-9779af80-a000-11ea-9ab5-0496256782a7.png)
![imagen](https://user-images.githubusercontent.com/44566/83037519-80878d00-a001-11ea-930e-11dac2655c3f.png)

**Comment by Persei08** [comment]
Seem you can reach popcorn-api. Often it's because ISPs block popcorn-api domains and it could be bypassed by using a no filtering DNS. Else try to use a vpn to see if it works better

**Comment by kalashnikov2** [comment]
Hello
Thanks for the help

in effect it seems that the operator that I use (Claro Colombia) is not only filtering the api, but also filters many other web pages.

it is not a DNS filtering ,it is something else

Is there any way to know what type of filtering I have?

the pages that do not open throw this error
"
Secure connection failed
web.archive.org. PR_END_OF_FILE_ERROR  "

**Comment by Persei08** [comment]
if settings your dns to google dns or cloudflare dns don't help to bypass, then use a vpn like pia vpn, nord vpn, or others

**Comment by kalashnikov2** [comment]
I also want to clarify that these blockages seem illegal or network problems.

So I ask if there is a way to verify this.

There is some general test that tells me if my connection is being filtered so that I can generate a support request with test results.

**Comment by kalashnikov2** [comment]
https://github.com/ooni/probe-cli

**Comment by Persei08** [comment]
Have you tried with a VPN ?

**Comment by kalashnikov2** [comment]
Yes, I have another connection that does not have that problem.

And I have my own vpn since everyone tries to sell you something. . .

**Comment by kalashnikov2** [comment]
I'm trying to build a list to test.  in ooni/probe-cli

what are the url of tv and movie api of popconrtime?

	popcorntime.app
	movies-v2.api-fetch.sh
	api.thetvdb.com
	dht.transmissionbt.com
	router.bittorrent.com

**Comment by rocobertoco** [comment]
hey man im also having the same trouble and i see we have the same isp. did you found a way to solve it?

**Comment by kalashnikov2** [comment]
hola

estoy recopilando una lista de dominios bloqueados  y sigo buscando el listado completo de apis del pt para hacer pruebas con ooni-cli
https://etherpad.wikimedia.org/p/urlbloqueadasclaro

hay un caso de soporte abierto pero dudo mucho que funcione para algo

**Comment by kalashnikov2** [comment]
pode probar si te abre este link ?

https://movies-v2.api-fetch.sh/movie/tt1469304

en un navegador normal

y si te abre un json con datos....

luego trata de abrir el  app del popcorntime

a mi me esta trabajando  :S  sin vpn por la red de claro


pero solo trabaja un rato, después se daña otra vez

**Comment by WiBla** [comment]
Try disabling the "Remember Filters" option in the advanced settings.
By looking at #1476 and from personal experience, this settings makes the Movie and Series tab unable to load.

**Comment by kalashnikov2** [comment]
> Try disabling the "Remember Filters" option in the advanced settings.
> By looking at #1476 and from personal experience, this settings makes the Movie and Series tab unable to load.

this did not help to solve the problem

the problem is that the ISP breaks the TLS requests of many web URLs like the one of the apis

the problem was solved after 3 technical visits, many hours on the phone and 2 changes to public IP (business connection)

During one of the visits, the highest level technician on the phone mentioned that it could be an AS edge problem, but he did not want to give details.

its clear that ISP Claro Colombia is filtering content not by DNS but by another method, not to block it but for other purposes?

**Comment by kalashnikov2** [comment]
It would be interesting if another users of the Claro Colombia ISP opened the Popcorntime to test.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please

**Comment by Godarth** [comment]
Try disabling the "Remember Filters" option in the advanced settings.
Traffic Shaping from you internet company could be a problem too.
