### ISSUE TITLE
"suggestion ", can we implement WINUI in htis project?

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#1488]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ShaneZhengNZ** [comment]
Why? WinUI is only for Windows, but Electron is cross-platform.

If you want WinUI, I would rather go for [MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/)

**Comment by KingOrdinaryCitizen** [comment]
PopcornTime/Butterproject is build on Node Webkit (NW.js), which as far as I know will remain the same.

I really don't see an advantage in using WINUI? Are you just asking in favor of a design standpoint? Because you can create a custom style within PopcornTime using CSS...

**Comment by fisforfaheem** [comment]
Popcorn-Official/Popcorn-Desktop already have a great UI, And millions love
it. I just wanted to knew about technologies that it can be converted into.
I hope more people join the development and make it the ULTIMATE NETFLIX
for poor.

**Comment by KingOrdinaryCitizen** [comment]
But why would you want to convert it into a different technology/language? That seems like a lot of work, for what? I really don't see a point in it?

**Comment by fisforfaheem** [comment]
to make single PROJECT CODEBASE, Like suppose you make an app in FLUTTER ,
it can be exported to all major platforms easily....that what i was after//

**Comment by fisforfaheem** [comment]
Electron only offers pc and mac,....whereas UNO and FLUTTER provide
multiplatform...

**Comment by ShaneZhengNZ** [comment]
I get that.. you want to support more platforms, then why WINUI?

**Comment by fisforfaheem** [comment]
Because i heard they are combing everything under win ui and making it
crossplatform..

**Comment by Persei08** [comment]
Why restarting from beginning? why taking the risk to lost contributors by switching technos when the project already lack of contributors to fix everything ?

Will be simpler you start another popcorntime clone project aside written with the technos you want and eventually when it will be good enough more people will join or PCT will switch to it.

There are already PCT clones based on different technos

**Comment by fisforfaheem** [comment]
Oh yes, anywho! i have no plans for that... i just want this project to be
my netflix!
