### ISSUE TITLE
Request For Season

### ISSUE THREAD

**Issue by imrantahir123** [popcorntime/popcorntime#1489]
Hi there,

I was trying to contact you guys to apricate your brilliant job in the form of POP Corn time. That's a outstanding application for Entertainment. 

I am searching for my childhood seasons from a very log ago e.g. (The manimal movie, Automan, The A team). That would be highly apricated if you guys provide such seasons on this application

Warm Regards,
Imran Tahir

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents. 
Asking here to add movies or series is not the right place as they have no control over what's added and not.

PS. I agree the devs do a brilliant job keeping this software going.

**Comment by Persei08** [comment]
I'm closing this, nobody add torrents. PT request apis or scrap results of different websites as @dutchy1001 explained.

If you guys want other websites/api to be scraped/requested, then they should have some imdb or tvdb links or id in their pages and you should suggest that to popcorn-api repo. thx
