### ISSUE TITLE
Chromecast subtitle position

### ISSUE THREAD

**Issue by brianardiles** [popcorntime/popcorntime#149]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
2 weeks?
#### Expected Behaviour

Change subtitle position with chromecast
...
#### Actual Behaviour

Nothing change
...
#### Steps to repoduce the behaviour
1. Change setting of position
2. Select a movie
3. Select chromecast2 and play

**Comment by brianardiles** [comment]
fixed https://github.com/butterproject/butter-desktop/pull/379

**Comment by Breaking1** [comment]
Isn't this a Chromecast problem?

https://productforums.google.com/forum/?hl=da#!topic/chromecast/Qe76EGhzlII;context-place=forum/chromecast

It work fine in my version now.
