### ISSUE TITLE
kat search and rarbag search in torrent collection still not workiing after have download the last build

### ISSUE THREAD

**Issue by raphcool12** [popcorntime/popcorntime#15]
sorry for that but I download the last build and now the result appear but when I click on a torrent file form the list nothing is happen

**Comment by team-pct** [comment]
Should be fixed f08a0ca6fb4868f36ad680e69f6e6afe9f50e069
Build #40 https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/40/
