### ISSUE TITLE
outside torrents don't work most of the time

### ISSUE THREAD

**Issue by L0rdM** [popcorntime/popcorntime#1507]
hey guys, I've recently updated the program because of a prompt to get the new version and since then running outside torrents almost never works. I drag the magnet link, choose the right file and nothing. it just stays on the "connecting" screen until I cancel the download or close the app. Closing and starting the program doesn't help.
I'm currently running version 0.4.4 on Win10

Any help would be much appreciated

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
