### ISSUE TITLE
stop at loading and no response for months same thing

### ISSUE THREAD

**Issue by tigerlero** [popcorntime/popcorntime#1510]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Maybe try and update PCT

**Comment by kiriles90** [comment]
@Persei08 close please
