### ISSUE TITLE
Play next episode automatically does not work

### ISSUE THREAD

**Issue by Kanzy11** [popcorntime/popcorntime#1513]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
duplicate of #1352

**Comment by kiriles90** [comment]
@Persei08 duplicate of #1352, close this please
