### ISSUE TITLE
missing episodes/names

### ISSUE THREAD

**Issue by riclas** [popcorntime/popcorntime#1515]
How is the shows list curated/updated?
there are shows with missing episodes and episodes without titles

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Asking here to add movies or series (or missing episodes) is not the right place as they have no control over what's added and not.

**Comment by riclas** [comment]
your answer is what i intended :) thanks

found it's by trakt.tv, needs to be improved
