### ISSUE TITLE
arm / Raspbian binaries

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1518]
Operating System Version:
Raspbian GNU/Linux 10 on Raspberry Pi

Popcorn Time Version:
none

Download date:
N.A.

Download url (optional):
https://popcorntime.app/#get-app

#### Expected Behaviour
Find Linux arm or package or repo for Raspbian
...

#### Actual Behaviour
Linux only x86 options
...

#### Steps to reproduce the behaviour
Visit website and go to Downloads

My main suggestion is to build .deb packages (Debian compatible) for i386 and amd64 architectures, and packages (Raspbian compatible) that run on a Raspberry Pi 4 / 3 / 2

**Comment by Persei08** [comment]
PopcornTime is based nwjs (even a custom version with extra codecs), which don't officially support arm. It will need nwjs community builds for arm (https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases) and to adapt some other things.

The projects here (desktop or android version) are already lacking of devs and contributors, so i don't think you will find lot of people to work on an raspberry/arm version.

But, If someone want to works on that, @LeonardLaszlo who make the nwjs binaries for arm above, have written some guides based on PCT 3.8.5 years ago, (which are a bit outdated now but still seem to be a good start to begin with) : 
- [Popcorn time instalation guide for ARMv7](https://github.com/LeonardLaszlo/popcorn-time-installation-guide-armv7), 
- [Popcorn time building guide for ARMv7](https://github.com/LeonardLaszlo/popcorn-time-building-guide-armv7)

Now people who want to do it can always make an arm/raspi version like [PopcornTimeTV](https://github.com/PopcornTimeTV/PopcornTimeTV) made an iOS one.

**Comment by LeonardLaszlo** [comment]
With your attitude @narcisgarcia, things will probably stay like this.

**Comment by LeonardLaszlo** [comment]
**Expected behaviour**: don't be a dick!

**Comment by davidnavas-ashkalabs** [comment]
I made torrent stream work in raspberry OS using peerflix, pretty solid stuff. Anyone knows of a popcorntime web based so i can browse titles and copy the magnet link? that's all i'm looking for

**Comment by Persei08** [comment]
@davidnavas-ashkalabs , look at butter-settings-popcorntime.io npm module, you will find api urls

and you can google 'popcorn-api doc' for routes and parameters... doc

**Comment by Persei08** [comment]
No plan for that as far as I know. Closing it.

**Comment by eoyilmaz** [comment]
> I made torrent stream work in raspberry OS using peerflix, pretty solid stuff. Anyone knows of a popcorntime web based so i can browse titles and copy the magnet link? that's all i'm looking for

I've written a very simple Python code that converts the magnet code string that I copied from the source of the video page at https://popcorntime-online.ch/ to a proper formated one and feed it to peerflix :) and it works flawlessly:

```python
#!/usr/bin/python
#-*- coding: utf-8 -*-

import sys
import os

if __name__ == '__main__':
    magnet_link = sys.argv[1]
    # replace characters
    magnet_link = magnet_link.replace("%3A", ":").replace("%2F", "/").replace("u0026", "&")

    # call peerflix
    os.system("peerflix '%s' --vlc --fullscreen" % magnet_link)
```
