### ISSUE TITLE
I downloaded the VPN and now popcorn time wont stream 

### ISSUE THREAD

**Issue by Tdubs88** [popcorntime/popcorntime#1519]
Operating System Version:

Mac OS Catalina 10.15.5 (19F101)
Popcorn Time Version:

0.4.4
Download date:

May 2020 
Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...
It was streaming well before I downloaded the VPN and now it will not stream 
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
so, it's a vpn issue. :|

Which vpn are you talking about?

**Comment by Tdubs88** [comment]
Thanks for replying! 

The VPN is VPN.ht (V1.1.2)

can I change the settings in the VPN? Or do I need to try a new one?

best

Tobi Webster
tobi@tobiaswebster.com <mailto:tobi@tobiaswebster.com>











On 12 Jun 2020, at 9:39 pm, Persei08 <notifications@github.com> wrote:


so, it's a vpn issue. :|

Which vpn are you talking about?

**Comment by alb277** [comment]
I have the same problem since I ought the VPN.ht, it is almost impossible to watch a movie, 9 times out of 10 the VPN doesn't connect and stays .....connecting..... and nothing happens.

**Comment by kiriles90** [comment]
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1578, close please
