### ISSUE TITLE
"Friendly" Labels for AirPlay

### ISSUE THREAD

**Issue by joshtylerclarke** [popcorntime/popcorntime#152]
Operating System Version:
OS X 10.11

Popcorn Time Version:
0.3.9 Build #105

Download date:
4/24/2016

There needs to be a "friendly" label for AirPlay devices/Apple TVs. As of now, my Apple TV shows up as AppleTV.tcp_local ...

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/friendly-labels-for-airplay/101
