### ISSUE TITLE
Movies screen not loading

### ISSUE THREAD

**Issue by Pepixel** [popcorntime/popcorntime#1521]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
About 2 weeks ago

Download url (optional):
Automatic update

#### Expected Behaviour
Movies list screen loading
...

#### Actual Behaviour
Movies list screen not loading. The rest of tabs work (Series, Anime)
...

#### Steps to reproduce the behaviour
Open PopCorn Time

#### Screenshot of error from developer console (optional)
Nothing special on screen, just loading animation

**Comment by JNQ71** [comment]
I have same problem
![image](https://user-images.githubusercontent.com/66844326/84533883-abf0c400-acf1-11ea-83c8-fc4fa88f9ea7.png)
![image](https://user-images.githubusercontent.com/66844326/84533940-bf9c2a80-acf1-11ea-9858-447ff4ff687f.png)
![image](https://user-images.githubusercontent.com/66844326/84533967-ce82dd00-acf1-11ea-9c7a-7661c463a666.png)

**Comment by georgikoemdzhiev** [comment]
I have the same problem but on Linux (Manjaro 20.0.3). I use the same version

**Comment by dutchy1001** [comment]
The link to the "movie" torrents site is not connecting.
Either the torrent site might be down for maintenance/other "reasons" or the link needs adjusting within PCT.

**Comment by dutchy1001** [comment]
the issue seems to be fixed again.
If it works again for the OP please close this issue.

**Comment by JNQ71** [comment]
> the issue seems to be fixed again.
> If it works again for the OP please close this issue.

Fixed!

**Comment by Pepixel** [comment]
Fixed, thanks!
