### ISSUE TITLE
Downloading TV shows issue

### ISSUE THREAD

**Issue by goeldesu** [popcorntime/popcorntime#1525]
Operating System Version:
Windows 10

Popcorn Time Version:
Version 4.4

Download date:
End of June. 

#### Expected Behaviour
Download an episode (from the Scream TV show).
...

#### Actual Behaviour
When I press download I just get a black screen.
...

#### Steps to reproduce the behaviour

1. Open Popcorn time
2. Go to the TV shows tab
3. Search 'Scream'
4. Download an episode (I only tested it on season 3).

NOTE: sometimes it shows up but doesn't download it.

**Comment by goeldesu** [comment]
Nothing to preview

**Comment by dutchy1001** [comment]
If you have a look if there is any availability at the "magnet link" on the right side of the screen you will see that all episodes (of Scream) are with a red dot, meaning there is very low or no seed(s) to be downloaded or to watch.
PCT does not have control over the availability of any movie or serie as this is done through "torrents". Torrents are depending on how many people are sharing those files.
Your screen stays blank/black as it can't find a seed. If you try an other serie/movie with a "green" magnet link you will see it pops up in no time, either to watch or download.

**Comment by goeldesu** [comment]
Ooh, okay thank you.
