### ISSUE TITLE
Sort by: Year / Sort by: Title

### ISSUE THREAD

**Issue by KoffeePi** [popcorntime/popcorntime#1526]
Operating System Version:

macOS Catalina
Version 10.15.5

Popcorn Time Version:

Version 0.4.4 (0.4.4)

Download date:

April 15, 2020

#### Expected Behaviour

When I sort my favorites by year or title I would expect them to sort in ascending or descending order. So from old to new / new to old, or from a to z / z to a

#### Actual Behaviour

It sorts x amount of titles and than starts over again. So, for example: 1933 > 2019, 1940 > 2019, 1948 > 2017, 1941 > ..., etc.

#### Steps to reproduce the behaviour

1. Create favorites
2. Sort favorites
3. Verify order

**Comment by dutchy1001** [comment]
This is probably only a MAC issue as it sort my favorites fine in a Windows 10 PC. 
When I click on "year" once and it's from low to high, click "year" again and it changes from high to low.
I don't have a MAC (and never will) so I can't check this but for Windows it seems to work OK..

**Comment by tuesd4y** [comment]
I've tried this with `macOS Catalina Version 10.15.5` right now on the develop branch and it seems to be working fine as well.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
