### ISSUE TITLE
Uninstalling Popcorn on Kubuntu

### ISSUE THREAD

**Issue by aardvaark11** [popcorntime/popcorntime#1527]
I can't find anywhere to uninstall Popcorn from my computer

Operating System Version:
 Linux/Kubuntu

Popcorn Time Version:
 0.4.4-0

Download date:
 a month ago

Download url (optional):

#### Expected Behaviour
 that's not important to this issue
...

#### Actual Behaviour
 that;s not important to this issue
...

#### Steps to reproduce the behaviour
 tell me how I can delete the app

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Where have you installed it ? in /opt/ ?

Eventually.

```console
sudo rm -rf /opt/popcorn-time
sudo rm /usr/bin/popcorn-time
sudo rm /usr/share/applications/popcorntime.desktop
sudo rm -rf /tmp/Popcorn-Time
rm -rf ~/.config/Popcorn-Time
```

**Comment by Persei08** [comment]
Closing this one, will eventually reopen, depending the replies

**Comment by aardvaark11** [comment]
Yea, sorry. Haven't done anything yet. Been busy and just forgot. lol get to it and let you know what happens.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
