### ISSUE TITLE
I have a VPN but it won't let me watch videos unless I download their VPN

### ISSUE THREAD

**Issue by ihaveaVPNdammit** [popcorntime/popcorntime#1529]
Operating System Version:
Windows 10

Popcorn Time Version:
popcorntime.app

Download date:
a month ago

Download url (optional):
popcorntime.app

#### Expected Behaviour
Let me stream videos
...

#### Actual Behaviour
Tells me I need to download a VPN and gives me a link to download theirs and won't let me proceed until i do even though I have one. 
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Have you turned the VPN option off in the settings? (you have to tic "show advance" settings" on the top of the settings page).

**Comment by kiriles90** [comment]
@Persei08 close please
