### ISSUE TITLE
Popcorn Time OSX download file doesn't open

### ISSUE THREAD

**Issue by metteemo** [popcorntime/popcorntime#153]
The download file for OSX is a .xz format file. This doesn't open on OSX unless you download an extraction app in order to open it. 

Considering that Popcorn Time is supposed to be "torrents made easy", the fact that the installer won't even open is really bad. Is it really that hard to not pack it as a xz file and use a .DMG or .PKG like every other osx app?

**Comment by VitorVRS** [comment]
Actually there is and issue for this: https://github.com/popcorn-official/popcorn-desktop/issues/83

If you can, feel free to help :smile:

**Comment by metteemo** [comment]
Nope, users can't help (via submitting a pull request). 

This is a problem with your CI (the Jenkins configuration) for your builds, not a problem with your source code. Therefore, the maintainers are going to need to fix it themselves- otherwise I would have submitted a pull request already.

**Comment by metteemo** [comment]
If the issue has been there for so long, why hasn't any maintainer bothered to fix it? It's up to you guys to change your Jenkins CI config, users can't change how you're packaging the file and uploading it...
