### ISSUE TITLE
Can't watch or download most films & series

### ISSUE THREAD

**Issue by 22U2** [popcorntime/popcorntime#1530]
Hi!

A few days ago I tried to watch some episodes of Superstore Season 5. But I encoutered a major issue while trying to do that : there are a lot of movies and series episodes I can't watch or download.

I've tried several episodes from The Office, Space Force, Superstore, Brooklyn Nine-Nine as well as a few movies that were trending. For most of them nothing happens when I click on **Watch Now** but I can download them, others won't download nor play. A small few work fine.

Yesterday was a lucky day as I was able to download 2 episodes (Superstore s5e6 and s5e7) that I can't download or watch anymore. Before a few days ago I hadn't use PCT for a while but I was already on 0.4.4 and it was working great!

Operating System Version:
Windows 10 64 Bits Version 1909

Popcorn Time Version:
0.4.4-0 (b2007344) 64 Bits, but I've tried with PCT's 64 bit Github release and 32 bit website release as well

Download date:
20/06/2020

Download url (optional):
https://get.popcorntime.app/build/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
When I click on Download, the download page shows up and the selected file starts downloading.
When I click on Watch Now, the PCT Player opens up and the selected file starts playing.

#### Actual Behaviour
When I click on Download, the download page shows up but nothing else happens.
When I click on Watch Now, nothing happens
...

#### Steps to reproduce the behaviour

1. Open the app and go to Series then search for Superstore
2. Select Season 5 Episode 8 and click on Watch Now
3. If, as it does for me nothing happens, click on Download and check if it starts downloading.
4. Try the same with Space Force. For me I seem to be able to download episodes but not **Watch** them **Now**

#### Screenshot of error from developer console (optional)
I don't know how to access developer console but this is what happens with some episodes/movies when I try to download them :

![Popcorntime Clicked on Download](https://user-images.githubusercontent.com/67207149/85212017-daece280-b34e-11ea-86bf-d943b22a220b.png)

**Comment by dutchy1001** [comment]
You might want to update PCT with the latest build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)**

PCT itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
On the right side of the screen in a movie/serie page is a coloured dot (green, yellow, red or gray), this tells you the availability of the torrent(s) were green is good and red or gray is not good. If the dot is red or gray your most likely will have issues, lots of buffering or not playing at all.
Depending on how many ppl are online "sharing" the torrent it will go up or down with the availability.

To open the developers console you only have to press F12.
