### ISSUE TITLE
star wars: the clone wars tv series not watchable

### ISSUE THREAD

**Issue by orief** [popcorntime/popcorntime#1531]
i try to press watch now or download torrent but its just not working

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
On the right side of the screen in a movie/serie page is a coloured dot (green, yellow, red or gray), this tells you the availability of the torrent(s) were green is good and red or gray is not good. If the dot is red or gray your most likely will have issues, lots of buffering or not playing at all.
Depending on how many ppl are online "sharing" the torrent it will go up or down with the availability.

**Comment by orief** [comment]
some are green and some are red but it does not work either way

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
בלי
וירוסים. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום א׳, 21 ביוני 2020 ב-20:34 מאת ‪dutchy1001‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dutchy1001** [comment]
As you havent filled in the default issue form so it's hard to understand the issue. 
My previous answer is the most common answer for the issue you mentioned without any other info what version you use of PCT, when you downloaded, what OS you use, etc. etc

Without the info needed we can not give further help on the issue. 
Best way to do this is to close this issue and open a new issue and fill in the needed info.
