### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by vasansri248** [popcorntime/popcorntime#1532]
Operating System Version: win 10 64 bit home

Popcorn Time Version:0.44.5

Download date:23-06-2020

Download url (optional):

#### Expected Behaviour
resume download button after shut down
...

#### Actual Behaviour
no option for stop and resume download
...

#### Steps to reproduce the behaviour

1. ...stop download & resume download options
2. ...
3. ...

**Comment by dutchy1001** [comment]
This is more a feature request then an issue

**Comment by kiriles90** [comment]
@Persei08 close please
