### ISSUE TITLE
Outlander Season 5, Episode 11 gets stuck

### ISSUE THREAD

**Issue by THFCSpurs** [popcorntime/popcorntime#1533]
Operating System Version:
 Windows 10

Popcorn Time Version:
 Can't see the version but I just downloaded what I think is the latest version. Love in the time of Corona

Download date:
 2 weeks ago

Download url (optional):

#### Expected Behaviour

Download the whole episode

#### Actual Behaviour

Downloads around 15 minutes of the episode. Afterwards only the sound continues

#### Steps to reproduce the behaviour

1. Try downloading the episode ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Availability is subject of the torrent being shared by others (see the magnet link on the right side).
Asking here to add movies or series is not the right place as they have no control over what's added and not.
the latest dev build can be found **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/)**

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
