### ISSUE TITLE
I can't watch the Stranger Things Season 2 / It says it has Health Problems

### ISSUE THREAD

**Issue by Jilus** [popcorntime/popcorntime#1534]
Operating System Version:
Windows 10 

Popcorn Time Version:
Popcorn Time 4.4 x64

Download date:
Yesterday

Download url (optional):
https://popcorntime.app/pt/windows

Expected Behaviour
I thought it would play the episodes normaly.
...

Actual Behaviour
I doesn't play anything at all.
...

Steps to reproduce the behaviour
1. Just try to watch the Stranger Things Season 2

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Availability is subject of the torrent being shared by others (see the magnet link on the right side).
Asking here to add movies or series is not the right place as they have no control over what's added and not.

**Comment by Jilus** [comment]
I am not asking anyone to put something new into popcorn. 
I was just asking why the Season 2 of Stranger Things didn´t work.
Aprreciated your attencion.

**Comment by dutchy1001** [comment]
Like I said before:
> Availability is subject of the torrent being shared by others (see the magnet link on the right side).

There is nothing else the PCT team can do about that.

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
