### ISSUE TITLE
Breaking bad episode 1 it has a strange xbox gameplay

### ISSUE THREAD

**Issue by vichoA27** [popcorntime/popcorntime#1535]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
This makes no sense at all, fill in the form for an issue or close it

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
