### ISSUE TITLE
Dark _Netflix Season 1

### ISSUE THREAD

**Issue by adrianus2108** [popcorntime/popcorntime#1537]
Please fix Dark Season 1! The video on Popcorn is another TV show completely different from the series

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Asking here to add movies or series (or missing episodes) is not the right place as they have no control over what's added and not.
Wrongly named movies or episodes is also out of PCT's controle then.

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
