### ISSUE TITLE
Watch/Download not working

### ISSUE THREAD

**Issue by riasat-sheikh** [popcorntime/popcorntime#1538]
Operating System Version:
macOS Mojave 10.14.6

Popcorn Time Version:
0.4.4 #424 latest ci build ( installed after trying the latest stable build 0.4.4)

Download date:
28/06/2020

Download url (optional):
the 424ci build: https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/artifact/build/Popcorn-Time-0.4.4_osx64.zip
the stable build: https://get.popcorntime.app/build/Popcorn-Time-0.4.4.pkg

#### Expected Behaviour
Pressing the watch now button should open the player. or download button should download something
...

#### Actual Behaviour
The app is not opening anything. I pressed the shit out of it. Not working.
...

#### Steps to reproduce the behaviour

1. I did a clean install of stable build 0.4.4
2. searched for a title
3. clicked watch now and puff nothing working.
4. changed to ci build 424 nothing working either

#### Screenshot of error from developer console (optional)

![image](https://user-images.githubusercontent.com/63984668/85958496-84694f00-b9b3-11ea-9dc5-cfd8072897ac.png)

**Comment by rob0727** [comment]
I have the same issue. Here is a screenshot of error
![2020-07-03](https://user-images.githubusercontent.com/67804677/86494483-8bd18500-bd32-11ea-98ca-80fa3b152899.png)

**Comment by reddo** [comment]
I subscribe, it's happening for me too.

**Comment by riasat-sheikh** [comment]
Well, it seems this is fixed without any update. It started working automatically. Been two days still fine. 

Edit: it's still working

**Comment by rkarmus** [comment]
It doesn't work for me. Do I have to download it again??

**Comment by riasat-sheikh** [comment]
> It doesn't work for me. Do I have to download it again??

I would suggest a clean install. Remove everything related to popcorn time and then reinstall it.
