### ISSUE TITLE
Missing letters in subtitles

### ISSUE THREAD

**Issue by mmenzyns** [popcorntime/popcorntime#154]
Operating System Version: Win10
Popcorn Time Version: 0.3.9
Download date: 26.04.2016
#### Steps to repoduce the behaviour:
1. Open a film/tv series with a butter player
2. Load czech language in auto subtitle box
3. People that know this language will notice that there are missing these letters

**Comment by VitorVRS** [comment]
Are you using default PCT player? Did you tried VLC instead?

**Comment by mmenzyns** [comment]
I am too lazy to download external subtitles and VLC doesnt have auto subtitles.

**Comment by Breaking1** [comment]
@menzac if you choose VLC from the players menu in popcorntime it will include subtitles if they are available in your language just as in the internal player, so no need to download any external subtitles if they are already available in popcorntime. 

They will show even if you use an external player like VLC if they are available in the language you have set as default for tv shows, movies just pick one before you press watch now.

**Comment by mmenzyns** [comment]
Oh now subtitles download. But letters with carons dont work there neither. I think the subtitles are downloading in wrong encoding.

**Comment by Breaking1** [comment]
If its something wrong with the subtitle, popcorntime can do little to help you. They do download with the right encoding or this would be a problem on most subtitles, this is probably something you need to address to the sites PT fetches subtitles from or am i wrong?

UTF-8 is probably the encoding you need to use i think if they are in a different encoding from the subtitle provider.

**Comment by mmenzyns** [comment]
Oh you are right. I have seen 3 movies before, all had broken subtitles. Now I played one movie and they are OK :/. When I saw 3 broken subtitles in a row I thought the problem was everywhere.
