### ISSUE TITLE
[Feature request] Change subtitle while streaming

### ISSUE THREAD

**Issue by isrmicha** [popcorntime/popcorntime#1540]
Windows 10
Popcorn Time Version: 0.4-4
Download date: 28/06/2020

#### Expected Behaviour
Could select the subtitle while streaming
...

#### Actual Behaviour
Cant change subtitle while streaming
...

#### Possible prototype
![image](https://user-images.githubusercontent.com/8812005/85961854-9632fe00-b983-11ea-95a2-661d9334a41b.png)

**Comment by Persei08** [comment]
If someone want to look at this.

There was already a little implement of this, (maybe for chromecast only)... When user dropped a subtitle in this view, it stopped the stream and restarted it (seeking 5 seconds backward) with dropped sub. 
If i remember well, was not totally "perfect" but was definitely not bad and a good start... but I think it's broken now and someone should look at that.

**Comment by isrmicha** [comment]
Thanks

**Comment by kiriles90** [comment]
@isrmicha since you closed this tagging this one as duplicate of #1332 and removing the dupe tag from there

(I know they're not exactly the same and this one is somewhat solved but they are very similar)

**Comment by dutchy1001** [comment]
If you are using the external player from **[SMPlayer](https://www.smplayer.info/)** this is possible. While the movie starts (then pause it) right click on the screen and choose "subtitles", drop down menu opens and on the bottom you have "Find subtitles at Opensubtitles.org..."
![subs1](https://user-images.githubusercontent.com/5569980/94399114-b464f180-015e-11eb-8eda-41eeeae0e8b7.png)

Fill the name of the movie in at arrow 1, click "Search" at arrow 2 and if you want a special language choose that at arrow 3.

![subs3](https://user-images.githubusercontent.com/5569980/94399823-fc384880-015f-11eb-812d-1a466851daed.png)

I'm not sure this is possible with other players as I only use SMPlayer
