### ISSUE TITLE
Fullscreen button bug

### ISSUE THREAD

**Issue by valik1228** [popcorntime/popcorntime#1542]
Operating System Version:
OS X 10.15, Xubuntu Linux 18.04

Popcorn Time Version:
0.4.4 

#### Expected Behaviour
Press on the dedicated fullscreen button (the double arrow one, top right on mac, top left on linux and windows) to enter fullscreen, then press it again to exit fullscreen and keep the minimize and maximize buttons displayed.

#### Actual Behaviour
When exiting fullscreen, It remove the minimize & maximize buttons of the window

#### Steps to reproduce the behaviour
1. Press on the dedicated fullscreen button (double arrow one)
2. Press on the dedicated exit fullscreen button  (double arrow one)
3. Try minimizing the window

#### Screenshots:

MacOS:
![image](https://user-images.githubusercontent.com/15063125/86001888-3b97b180-ba18-11ea-9d44-115f142688e8.png)

Xubuntu:
![Screenshot_2020-08-07_03-55-21](https://user-images.githubusercontent.com/22459458/89600260-e003e380-d861-11ea-86a6-00b68f3bf918.png)

**Comment by Persei08** [comment]
Just experienced this bug, I will edit your report to make it more easy to understand. thx
