### ISSUE TITLE
Movies TAB

### ISSUE THREAD

**Issue by SantiChR** [popcorntime/popcorntime#1543]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4.0

Download date:
A month ago maybe

#### Expected Behaviour
I clicked on the 'Movies' tab, and then it should open the movies

#### Actual Behaviour
I clicked on the 'Movies' tab, and then it didn't load (I waited a long time and it still didn't load even though the other tabs, like 'Series' did)

#### Steps to reproduce the behaviour

1. ... Start downloading multiple movies in the seedbox, or wait for them to download
2. ... Click on the 'Movies' tab 
3. ... If it still loads then do steps 1 and 2 again

**Comment by dutchy1001** [comment]
Try and update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)**

If the issue still happens then report back here

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
