### ISSUE TITLE
Can't close the app. Need to kill using Task manager

### ISSUE THREAD

**Issue by alaminio** [popcorntime/popcorntime#1548]
Operating System Version:
Windows 10

Popcorn Time Version:
4.4

Download date:
4th July, 2020

Download url (optional):
https://mirror05.popcorntime.app/build/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
Close the app on clicking X icon on top right

#### Actual Behaviour
Do nothing

#### Steps to reproduce the behaviour
Just click close button after opening or watching something.

**Comment by dutchy1001** [comment]
You might want to read the pinned topic on top here.

Duplicate of #1280

**Comment by alaminio** [comment]
thanks
