### ISSUE TITLE
Chromecast: no audio when casting a video with AC3/DTS audio format

### ISSUE THREAD

**Issue by bsphere** [popcorntime/popcorntime#155]
Operating System Version: Ubuntu 14.04

Popcorn Time Version: 0.3.9-0

Download date: April, 17 2016
#### Expected Behaviour

Unsupported audio by Chromecast (e.g.: DTS) should be transcoded to a supported format. this is one of the main feature of the [videostream](getvideostream.com) extension. for some reason videos with AC3 soundtrack also have no sound.
#### Actual Behaviour

Video is played on Chromecast with no audio
#### Steps to repoduce the behaviour
1. Click on the "torrent collection" icon
2. Search KAT/Rarbg for a video that has an AC3 soundtrack or an unsupported Chromecast audio format such as DTS
3. Play on Chromecast..

**Comment by TriPSs** [comment]
Same here:

Operating System Version: Windows 10

Popcorn Time Version: 0.3.9-0
