### ISSUE TITLE
Watch now not working and download shows a blank page

### ISSUE THREAD

**Issue by Llallos** [popcorntime/popcorntime#1550]
Operating System Version:

OS 10.15.4 
Popcorn Time Version:

0.4.4
Download date:

29/04/20
Download url (optional):

#### Expected Behaviour

I expected the watch now button to work and for the download to work

#### Actual Behaviour

Neither work for any title

#### Steps to reproduce the behaviour

1. No
2. Bloody
3. Clue

**Comment by dutchy1001** [comment]
Update your PCT from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)** and see if the issue still happens.
If your issue is fixed close this topic please.

**Comment by poojakohli** [comment]
HI!  @dutchy1001

Still the same issue. Watch now button don't work. Download button opens to a blank page

Operating system version: 
macOS Catalina 10.5.5

I updated my version to the latest build #428. Used 'update-0.4.4_osx64.zip' found [here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/428/)

**Comment by dutchy1001** [comment]
Have you tried unistalling and make a clean install?
If not, try this first.
The "watch now" button should work, depending on the torrents it could take some time to start streaming.

**Comment by dutchy1001** [comment]
This issue should be fixed in the latest dev build. Get it **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
