### ISSUE TITLE
popcorn time wont close

### ISSUE THREAD

**Issue by MAXG1996** [popcorntime/popcorntime#1554]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
No info given of what version PCT, OS, etc. etc. Again didn't read any of the pinned topics on top.

Duplicate #1280
