### ISSUE TITLE
Seedbox tab no longer works after changing configuration settings

### ISSUE THREAD

**Issue by andrewgraham1** [popcorntime/popcorntime#1555]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4-1

Download date:
11/07/2020

Download url (optional):
https://popcorntime.app/windows

#### Expected Behaviour
Updating the Cache directory from the default position to a different hard drive allows the continued use of software.

#### Actual Behaviour
When the cache directory has been changed the seedbox UI element no longer functions and it is not possible to see the contents within the seedbox tab anymore

#### Steps to reproduce the behaviour

1. Go into the settings tab and hit the checkbox for the "Show Advanced settings"
2. Scroll down to cache directory and change it to another drive, in my case: D:\Windows\Videos\Movies\Popcorn-Time
3. Observe that when you leave the settings menu and attempt to click on the seedbox UI it will not show the seedbox.

**Comment by dutchy1001** [comment]
Update to the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.
If the issue still happening report back or close the issue if it's solved.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
