### ISSUE TITLE
Development Environment: "Shader cache creation failed" due to insufficient permissions to move file

### ISSUE THREAD

**Issue by ArcticZeroo** [popcorntime/popcorntime#1556]
Operating System Version:
Windows 10

Popcorn Time Version:
N/A, development branch

Download date:
N/A

#### Steps to reproduce the behaviour

1. Clone project on a windows 10 machine
2. `nvm install 12.8.0`, `nvm use 12.8.0` (I'm aware that I should be using `0.10.x`, but I can't even install node-gyp with that version. `4.0.0` is the first version of node with windows-build-tools)
3. `gulp build`
4. `gulp run`

#### Screenshot of error from developer console (optional)

![image of windows terminal](https://user-images.githubusercontent.com/5075030/87491461-304aa580-c616-11ea-99e5-83898ea91165.png)

#### Comments

Obviously this isn't the usual user-facing bug. I'm trying to set up a development environment for popcorn-desktop on develop, and running into this issue on a win10 machine. Has anyone else already solved this? I can launch popcorn time perfectly fine from the `build` folder, but it's not happy when I try to launch it using gulp directly.

I am using an administrator command prompt as well.

**Comment by Persei08** [comment]
node -v && npm -v
v13.10.1
6.13.7


~~Also, I'm on linux and I switched from "nvm" to "n" because of nvm issues (I don't remember well but it was some recurring permission issues with the nvm cache)~~ edit: forget that, nvm for windows is different :|

**Comment by Persei08** [comment]
Hi @ArcticZeroo did you still experience the issue or can i close it.

Also forget my comment about nvm for windows... implementation is different than nvm for linux

**Comment by ArcticZeroo** [comment]
I think we can close this, I believe it resolved after I switched to node v12 from v0.12 (or whatever is specified in the contribution guidelines).
