### ISSUE TITLE
Classical movies section in Genre menu. 

### ISSUE THREAD

**Issue by hypernote** [popcorntime/popcorntime#1558]
Operating System Version:
OS X 10.15

Download date:
03/07/2020

It would be great have a "Classical" section in Genre menu. 

If you guys need, I can provide a good classical movie list.

**Comment by ivan1986** [comment]
films and show info get's from https://www.themoviedb.org/
there isn't have classical tag

**Comment by Persei08** [comment]
Well I tag "feature" label, but i close it because it's dependent from api and the api don't have this genre, so we can't do it for now.
