### ISSUE TITLE
[Suggestion] Show peers and seeds in downloads tab

### ISSUE THREAD

**Issue by saxobroko** [popcorntime/popcorntime#1559]
Operating System Version:

Windows 10 

Popcorn Time Version:

Latest

Download date:

A week or 2 ago

Download url (optional):

From GitHub

#### Expected Behaviour

... Show me the peers and seeds in the downloads tab

#### Actual Behaviour

... Just shows a green icon even if there are no peers to download from

#### Steps to reproduce the behaviour

1. ... Try to download a not popular tv-show 
2. ... Look at your downloads tab
3. ... It'll show a green dot with no information about peers or seeds even if it isn't downloading

**Comment by ArcticZeroo** [comment]
This will be fixed when https://github.com/popcorn-official/popcorn-desktop/pull/1560 lands
