### ISSUE TITLE
I am logged in so whats happening with SSL certificate? Cant connect

### ISSUE THREAD

**Issue by tytower** [popcorntime/popcorntime#156]
Operating System Version:
<Linux?-->

Popcorn Time Version:
Latest on site 30th April 2016

Download date:
Latest on site 30th April 2016
#### Expected Behaviour

...
#### Actual Behaviour

see below code 
...
#### Steps to repoduce the behaviour

1. ...# ./make_popcorn.sh
   Cloning Popcorn Time
   Where do you wish to clone Popcorn Time to? [popcorn] 
   Cloning into 'popcorn'...
   error: Problem with the SSL CA cert (path? access rights?) while accessing https://github.com/popcorn-official/popcorn-desktop.git/info/refs
   fatal: HTTP request failed
   Popcorn Time encountered an error and could not be cloned
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Cannot reproduce

**Comment by tytower** [comment]
Well thats a bit cheeky isn't it !
I am trying to download this and you have it set up with an SSL certificate required . So whats the can't reproduce about / does that mean "Could not be bothered " or maybe "not interested ". WTF . Then you have the gall to close the bloody thing -Arsehole

**Comment by tytower** [comment]
Should be ChrisArsehole
