### ISSUE TITLE
dissatisfied already in the long run

### ISSUE THREAD

**Issue by rdisystem** [popcorntime/popcorntime#1563]
Operating System Version:

10
Popcorn Time Version:

4
Download date:

20/07
Download url (optional):

#### Expected Behaviour

...
after upgrading to version 4 the movies no longer load and neither do the subtitles

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
If you have read the pinned post on the top about the subtittles then you would understand how to get the subtittles working again.
If you have updated from the main PCT page then you will still have some issue's indeed, use this link **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** to get a dev build version.

If all works again after installing this version then please close (both) your issue(s).

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
