### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1566]
Clicking the "Download" button beside the "Play" button in movies does not do anything, tried closing and reopening the app, uninstall, and reinstall the latest Dev/CI build..... but the same issue persists. 

Expected behaviour: The movie, or series, must start downloading, with a separate progress screen. 

OS: Win10 x64
PT: 0.4.4 CI build 21 July 2020

**Comment by dutchy1001** [comment]
Using same OS and last build 425 (21/07/2020) but my download works as normal. Used the download button to get "Palm Springs" (1080) including English subs, downloaded within 6 minutes.

**Comment by ze0ss** [comment]
Oh ok, but it's still not working for me.

**Comment by ze0ss** [comment]
@dutchy1001 you are right, it indeed downloads it, the problem is with the UI, it doesn't show any sort of progress or anything like that whatsoever, the only way I know it is downloading it is by opening up the task manager, which shows an increased network activity for nwjs.exe.

I think there must exist a separate screen, such as a **download manager** for downloads, for both ongoing and completed, is a must.

**Comment by dutchy1001** [comment]
when I download there is a "orange" progress bar in the right bottom corner (see red arrow)
![download](https://user-images.githubusercontent.com/5569980/88295644-99f14080-ccf5-11ea-8ecc-e81006545703.png)

At the green arrow you can see the download and upload speed and you can pause or delete the file too.
I do agree that this is not very clear when using the "black/yellow" theme, other theme's might have a better colours.

As soon the file is downloaded it will remove itself from the "seedbox" which then is very confusing if it's downloaded or not. 
If this can be changed it would make it a lot more clear. 
Also when downloading the files should go to a separate location as when you have "clear Tmp folder after closing app?" ticked it will then also delete the downloaded file, the reason to download is to watch it later I presume.

**Comment by ze0ss** [comment]
Oh ok, I understand, but I do not see this bar or screen whatsoever, like, ever, even if I click the seedbox button, it is empty (even while a download is going on), so I really can't see any progress at all, I think it is a bug(?)


>Also when downloading the files should go to a separate location as when you have "clear Tmp folder after closing app?" ticked it will then also delete the downloaded file, the reason to download is to watch it later I presume.

Yeah, I also think there must be an option in settings to set a separate folder location for downloads.

**Comment by ze0ss** [comment]
> when I download there is a "orange" progress bar in the right bottom corner (see red arrow)
> ![download](https://user-images.githubusercontent.com/5569980/88295644-99f14080-ccf5-11ea-8ecc-e81006545703.png)
> 
> At the green arrow you can see the download and upload speed and you can pause or delete the file too.
> I do agree that this is not very clear when using the "black/yellow" theme, other theme's might have a better colours.
> 
> As soon the file is downloaded it will remove itself from the "seedbox" which then is very confusing if it's downloaded or not. 
> If this can be changed it would make it a lot more clear. 
> Also when downloading the files should go to a separate location as when you have "clear Tmp folder after closing app?" ticked it will then also delete the downloaded file, the reason to download is to watch it later I presume.

I cannot open the seedbox, I click it several times, even the Watchlist is empty while downloading, like I said, the only way I know something is being downloading is by looking in the task manager. which shows high network usage for nwjs when it is downloading something.
Please also add the separate folder setting for downloads, other than cache directory.

Can you please take this as a bug?

**Comment by dutchy1001** [comment]
I don't code myself, just help answering common mistakes that are easy to solve without the need of coding. 
Make sure you have a clean install as sometimes "overwriting" the files could leave behind old files.

I have changed the default Tmp folder to an other drive for easy access and turned off the "clear Tmp folder after closing app?".
This way I can keep everything I watch or download and delete them when I want (also save redownloading when other family members want to watch it).
Try these settings I did and see if the seedbox will appear then.

I did create a new issue with the feature request and bug report.

**EDIT:** 
You mention you downloaded on 21/07/2020. Where did you download from? The main website has an older version then the dev builds.
Update your version from this link **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by ze0ss** [comment]
Ok I will surely try what you said, I'll turn off auto clearing of cache, and I'll do an uninstall and a clean install again.

Yes, I download the updates only from the site you mentioned, since the stable version on the main site is old and buggy.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
