### ISSUE TITLE
Stream URL missing

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1567]
The stream/source URL is not shown below the progress of download while streaming any movie, series, etc.

Expected behaviour: The source/stream URL must be shown and user should be able to copy the URL (for if he decides to paste it in a relevant torrent downloader for downloading the content).

OS: Win10 x64
PT: 0.4.4 Dev/CI build 21 july 2020

**Comment by kiriles90** [comment]
I have it fixed in a branch I have including some other stuff. Need to make the css -> styl for them then make a pull request.

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/1571 done the PR. It will fix the stream url once merged.
Close the issue if you can and thank you for reporting this!

**Comment by ze0ss** [comment]
Thank you so much!

**Comment by kiriles90** [comment]
@abh-oss01 You're very welcome, thank you too for reporting it :) New build (427) available in ci.popcorntime.app too if you want (thank you @team-pct)

_*Btw, this was a fix for the stream url (you can paste it in video players or browsers etc in the same device or other devices on the same network and it will play whatever Popcorn Time is downloading, like an external player)
If your original comment above ment the magnet link for loading a specific torrent in other torrent clients thats also available but in the movie/episode detail screen. Just click the little magnet icon on the top right and it will open it with your default torrent client or right click it and it will copy it in your clipboard._

**Comment by abh-oss01** [comment]
@kiriles90 the new build is deleting everything in my D drive, windows, I had to close the installer using task manager so it doesn't erase my whole drive, what is this new drastic issue now??
It's so unexpected, it got rid of almost 5 GB worth of files before I closed it using task manager.

I downloaded the latest build 407 from ci site, and did a fresh install, I uninstalled the older version, and started to install 407, but it did this, I use the D drive path always, not the first time.


![20200728_100929.jpg](https://user-images.githubusercontent.com/56572179/88619971-709c3000-d0ba-11ea-909a-ba263579d148.jpg)

**Comment by dutchy1001** [comment]
If this is an issue that it "**deletes everything**" on a drive then please make a new issue report. 

@abh-oss01 I hope you could recover the 5G that has been deleted.

**Comment by ze0ss** [comment]
> @abh-oss01 I hope you could recover the 5G that has been deleted.

Umm, nope, it's deleted forever :)

**Comment by ravish0007** [comment]
@ze0ss
 Are you able to see stream url now ?
 
It doesn't display stream url while download in progress and I assigned a port manually, it lists the files but fails to stream them in my cloud computer  but works perfectly good in my local workstation.

How to fix this ?

**Comment by ze0ss** [comment]
>Are you able to see  stream url now ?


@ravish0007 yep

**Comment by ravish0007** [comment]
@ze0ss How did you fix it ?

**Comment by ze0ss** [comment]
> How did you fix it ?

update the app
