### ISSUE TITLE
[Feature request/bug report] Separate location for when using the download button

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1568]
With the newer versions having the function to download a movie/serie it would be great if they are downloaded to a separate location then the "Default Temp" folder. 
This way it wont be cleared when having the "clear Tmp folder after closing app?" ticked which is normally set as default.

Also when a movie is downloaded it disapears from the "seedbox" tab which makes it confusing if it is downloaded. If you want to watch it later you have to search for it (there are still a lot of people that don't know how to get to the "AppData" folders in windows).
While in the seedbox tab you can see a little folder that lights up when hovering over, clicking this (or the file name) will not open the file location, I presume as it lights up this should be the case.
![seedbox](https://user-images.githubusercontent.com/5569980/88307493-ed6a8b00-cd03-11ea-856c-069d3d69d13a.png)

As long you keep the seedbox open it will show, but as soon you go back to "movies/series" tab and reopen the seedbox, the seedbox is empty. 
Can there be a "tab" added for the downloaded movies/series with play button or/and linked to file location?

**Comment by test2a** [comment]
I would add to this feature, if we are doing a separate folder for "downloads", what about at the end of the movie, because the stream was 100% downloaded already, it should "ask" if you want to keep the copy or not.

**Comment by dutchy1001** [comment]
I dont think that is relevant, you use the download button to keep the movie to watch at a later date, meaning you already want to keep it.
If you want this (keep the copy) added to the "watch now" button then that is a different feature request which I think is unnecessary as you can opt out of "clear Tmp folder after closing app?" which then keeps all streamed movies/series.
