### ISSUE TITLE
Stuck on the loading page

### ISSUE THREAD

**Issue by theodiablo** [popcorntime/popcorntime#157]
Operating System Version: Windows 10

Popcorn Time Version: 0.3.9

Download date: April 02 2016
#### Actual Behaviour

The program is stuck on the loading page.

![popcorntime-stuck](https://cloud.githubusercontent.com/assets/8282971/14964100/1a8d9d16-10a7-11e6-88f9-ad40138a4c61.PNG)
#### Steps to repoduce the behaviour
1. Run the project with npm start
2. Wait...

**Comment by Noxeus** [comment]
Same issue after running `make_popcorn`

**Comment by VitorVRS** [comment]
Try download the latest version: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/ (Latest build was 4 days ago)
