### ISSUE TITLE
Where are news videos on popcorn time??? For 11 days there are no new videos...

### ISSUE THREAD

**Issue by bojansimonovic** [popcorntime/popcorntime#1572]
Operating System Version:
Win10 64x

Popcorn Time Version:
Latest

Download date:
When latest version appeared

Download url (optional):
https://getpopcorntime.is/

#### Expected Behaviour
To work and have regulary new videos as always
...

#### Actual Behaviour
11 days there are no new videos. No any topic about it here. So please take that in consider before you blame me again "read topics" that there are topics about it...
...

#### Steps to reproduce the behaviour
Try watch any new video...

1. ... Turn on popcorn time
2. ... Check is there any new video
3. ... Close popcorn time

#### Screenshot of error from developer console (optional)
You can see it by yourselvers... No need for SS.

**Comment by dutchy1001** [comment]
>So please take that in consider before you blame me again "read topics" that there are topics about it...

Ofcourse we can blame you, and indeed you won't find any topic about it here. This is a different version of PCT then where you got it from (how can we **"blame you again"** if this is your **first** post on github??? lol).

> Download url (optional):
https://getpopcorntime.is/

This link is not the correct one for the version talked about here, on that site is no link to this github page which might have given it away that it's not the same.

Also PCT has no control on what's been added, these things are depending on some torrent sites.

**Comment by Persei08** [comment]
lol, i close because user is reporting error for another popcorntime fork
