### ISSUE TITLE
Subtitles are not working again. Can you fix it please

### ISSUE THREAD

**Issue by cinyunis** [popcorntime/popcorntime#1577]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
There's nothing to fix. Opensubtitles.org is doing maintenance, subtitles will work again when they finish.

Close this please.
