### ISSUE TITLE
Latest Dev build deletes everything in a Directory

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1579]
The new dev build is deleting everything in my D drive, windows 10 x64, and I had to force close the PT installer using task manager so it doesn't erase my whole drive, what is this new drastic issue now??

It's so unexpected, it got rid of almost 5 GB worth of files before I closed it using task manager.

I downloaded the latest build 427 from ci site, and did a fresh install, I uninstalled the older version, and started to install 407, but it did this, I use the D drive path always, not the first time.

A possible "workaround" is to **Choose the `Popcorn-Time` folder (if it already exists) for the installation** 

OR

**We have to create a new folder named `Popcorn-Time` wherever you want to install PT.**

![20200728_100929.jpg](https://user-images.githubusercontent.com/56572179/88619971-709c3000-d0ba-11ea-909a-ba263579d148.jpg)

_Originally posted by @abh-oss01 in https://github.com/popcorn-official/popcorn-desktop/issues/1567#issuecomment-664772450_

**Comment by dutchy1001** [comment]
>I downloaded the latest build **407** from ci site

I presume you mean build 4**2**7

As build 427 has only a tiny code change it could be started in build 426.

I do not have a separate drive to test/confirm this on ATM but will try to find an old desktop pc to try this.

**Comment by ze0ss** [comment]
Yes, it's 427, a proofing error, I'll **try** reproducing it, and send a video.

**Comment by dutchy1001** [comment]
I have tried to reproduce it on a spare pc but what I do it won't delete any other file then the PCT folder.

I installed build 426 upto build 428 both 32 and 64 bit, but nothing gets deleted then the files from the PCT folder.
I have let the installer create the folder to install PCT and updated without that version to the same folder.
I will try some more...

I've updated my main pc now to build 428 with no hassle (besides database import always going wrong)

**Comment by kiriles90** [comment]
Same here installed 424 up to 428. I have a D: and E: drives, also tried to change the install directory. It didnt try to delete any files. Also nothing related to the installer was changed from 424 to 428..

**Comment by ze0ss** [comment]
I know you won't be able to reproduce this, there is a thing you must do:

Delete the `Popcorn-Time` folder, as in when someone is installing PT the very first time, when PT makes the folder itself.

But for the reproduction of this bug, you must change the default directory "out" of `Popcorn-Time` folder, it must be something else, just not `Popcorn-Time`.
I can't explain it this way, it's quite hard for me, like I said, I will _try_ sending a video soon.

There's just one thing you gotta do, the install folder must not be `Popcorn-Time`,

Here's what I did today:

For example, the default path PT chose is in C drive, but I always change it to D and it never has had any such issues until today.

Since I wanted to make a fresh installation, I uninstalled the 426 build, and downloaded build 427 from CI site, and started the installation, and as always selected the D drive path, where the previous build had always been (I had chosen to delete caches and databases too, for a fully fresh installation).

But I just .... chose the directory with one slight change, I chose D/Mystuff/
which means PT did **not** get a chance to create the `Popcorn-Time` folder which it does if it's installed in C drive users (that is, if  the install path option is **not** touched while installing.

So, in my D/Mystuff there is literally everything on the drive, it's literally the whole drive, I have about 400 GB data here, and remember, there isn't a `Popcorn-Time` folder here.... the install path is D/Mystuff 
and then I click OK, and what followed after costed me 5 GBs of irrecoverable data loss, which could have been more if I had not force stopped the installation using the task manager :)

**Comment by kiriles90** [comment]
@abh-oss01 I understand. But thats not the installers error. Its a bit.. user error :) VLC's installer e.g will do the same in many updates, clear its install dir, if that install dir is the base of your D: drive, or D:\My stuff\, it will clear that.  

Why not just install Popcorn Time in D:\My Stuff\Popcorn-Time like it was ment to (programs like their own install directories) and not fear this happening again? Like I said it could have happened with a number of other installers/apps.

**Comment by ze0ss** [comment]
It literally just went "Deleting D/Mystuff/flutter........ “

and just like that, it permanently deleted the WHOLE flutter folder, about 3.5 GB and about 1.2 GB data from some game folder, which has made the game unplayable now.

What I mean to say is, there does exist some serious bug, very serious one, and it's a Dev build, hence it must be **isolated and fixed** asap, before (if) this build is released as stable for thousands of unsuspecting people, and I considered this a humble duty from my side, to report this bug to the team as soon as I encountered it.

Hope this helps, and like I said earlier, I will try reproducing it again, and make a screen record too, and post here.

**Comment by kiriles90** [comment]
> Its not a bug.. its user error. If you are going to change apps install directory (not just Popcorn Time) at least the directory path should be D:\My stuff\Popcorn-Time not D:\My stuff\ and shared with a thousand other apps and documents. Ofc you are looking for trouble when you do that, and basically relying on luck that something wont clear what it thinks is its own install dir out..

**Comment by ze0ss** [comment]
>If yes then thats why it tried to delete everything in what it though it was its own install directory even though its D drive's base.. Older versions\builds will do the same.

Yes I always do that, nothing really new, but I mostly just update, and not do uninstall and reinstall, like this time.

Also, why must it delete anything which exists in the folder anyway? It must not even touch anything else, right?
Can it be made to **not** touch anything if `Popcorn-Time` doesn't exist??

I mean, I assumed the installer  create the `Popcorn-Time` folder itself, why didn't it?
It's expected to, if it doesn't exist.

Why should it touch something which is not of it's concern at all??

**Comment by kiriles90** [comment]
The default install path once you open the installer is `C:\Users\username\AppData\Local\Popcorn-Time`  

Now you went and manually edited that to `D:\My stuff` what did you expect it would happen :)  
Pay attention to things like that when you edit them, it wanted to create a 'Popcorn Time' folder, but you told it not to. Or else your path should have been D:\My stuff\Popcorn-Time

**Comment by dutchy1001** [comment]
Hense the reason I could not reproduce this as I never install a program in a general location but always in a folder on it's own (this also then keeps clarity in your folders) .

I'm not sure if the installer can be "forced" to create a folder for install like the "cache directory" does, when you change that to D:\ or E:\ it would automatic change it to D:\Popcorn-Time or E:\Popcorn-Time. 
I mean no matter what location you give it, the installer will add "**\Popcorn-Time**" to it. It might be overkill but it prevent mistakes like what happend to _abh-oss01_ . 

Well atleast we know now "what not to do"

**Comment by ze0ss** [comment]
>I'm not sure if the installer can be "forced" to create a folder for install like the "cache directory" does.

Why not?


>when you change that to D:\ or E:\ it would automatic change it to D:\Popcorn-Time or E:\Popcorn-Time. 

It didn't.

> I mean no matter what location you give it, the installer will add "**\Popcorn-Time**" to it.

It didn't do it.

**Comment by ze0ss** [comment]
>Its non-shared clearable `\Popcorn-Time` dir. It believed you.

Why is it clearable for the installer? It shouldn't be clearable at all, right?

>P.s Sorry if I'm sounding like I'm trying to add insult to injury, I'm not. Just explaining what happened and why..

Oh I know, it's fine.

**Comment by kiriles90** [comment]
@abh-oss01 many apps clean out their install dirs (in all version or specific ones) to avoid conflicts with older files & to remove any ones that are no more needed.

To avoid this happening again since from what I understand you install many things in a custom dir, and since you cant rely on if the specific installer has a safeguard in place against this specific situation (e.g Popcorn Time didnt), pay attention to the default path before you modify it. If it has a \Popcorn-Time or a \Videolan or \Google Chrome or whatever at the end, make sure you add it in the end of your custom path too. 

Other installers might not delete stuff but do other things e.g drop a couple of thousand random files and folders in your D:\My Stuff base dir and create a huge mess..

**Comment by dutchy1001** [comment]
> I'm not sure if the installer can be "forced" to create a folder for install like the "cache directory" does.
>> Why not?

I can't answer that as I don't do coding

>when you change that to D:\ or E:\ it would automatic change it to D:\Popcorn-Time or E:\Popcorn-Time.
>>It didn't.

When I click on the "cache directory" in settings a "windows explorer" pops up, I only select, on the left side, 1 of my drives (then click "Select Folder") and it automatic adds then "\Popcorn-Time" for me (this happens on all windows machines I install PCT on). 

>I mean no matter what location you give it, the installer will add "\Popcorn-Time" to it.
>>It didn't do it.

This is a sugestion to be implemented in a later version if possible to avoid the issue you had.

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?

**Comment by ze0ss** [comment]
@Persei08 there's a suggestion in this. The last comment from @dutchy1001

**Comment by Persei08** [comment]
hmm.. I reopen, I think it could be the bug I mention in #1712
