### ISSUE TITLE
Favorites do not load 

### ISSUE THREAD

**Issue by e1ecandy** [popcorntime/popcorntime#1586]
Operating System Version:
OSX

Popcorn Time Version:
0.4.4-0

Download date:
Feb 2020

Download url (optional):

#### Expected Behaviour
Open favorites 
...

#### Actual Behaviour
Shows spinning loading circles indefinitely 
...

#### Steps to reproduce the behaviour
Unknown, seemed to have happened after a movie was favourited. Uncertain which one

1. ...Seemed to disappear when all database were flushed 
2. ...
3. ...

**Comment by dutchy1001** [comment]
You need to update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

If you use subtitles then please read the pinned (#1318 )  topic about it.
If the problem is still there comment back or close if it's solved.

**Comment by Persei08** [comment]
@e1ecandy 

> #### Steps to reproduce the behaviour
> Unknown, seemed to have happened after a movie was favourited. Uncertain which one
> 
> 1. ...Seemed to disappear when all database were flushed 
> 2. ...
> 3. ...

If you flushed all databases, then it's definitively gone :confused:

So else if ~~everyone~~ **someone** have a step by step guide to reproduce (with BTW a specifc title to bookmark), i will be greatly appreciate :wink:

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
