### ISSUE TITLE
none of my tv shows will play 

### ISSUE THREAD

**Issue by gigigurl** [popcorntime/popcorntime#1587]
I've re installed it, ended the program and restarted my computer yet no tv show will play

**Comment by dutchy1001** [comment]
Please fill in the form with the info asked when you opened this issue. Without this info there will be no help to solve your issue.

```
Operating System Version:
<!-- OS X 10.11? Windows 10? Linux?-->

Popcorn Time Version:
<!-- What version of Popcorn Time are you running? -->

Download date:
<!-- When did you install Popcorn Time? -->

Download url (optional):
<!-- Since there are pre-release builds and it's difficult to track if download is a release or just random build from jenkins. -->

#### Expected Behaviour
<!-- What did you think the app was going to do? -->
...

#### Actual Behaviour
<!-- What does the app do instead? -->
...

#### Steps to reproduce the behaviour
<!-- What steps do we need to take to find the same bug that you found? -->

1. ...
2. ...
3. ...

#### Screenshot of error from developer console (optional)
<!-- Screenshot helps with finding why stuff breaks -->
```

**Comment by McKush** [comment]
Operating System:
<Mac OS Catalina 10.15.6>

Popcorntime Version:
<0.4.4-0>

Download Date:
<Downloaded about a month ago, just reinstalled today 8/4/20>

Download URL:
<popcorntime.app>

#### Problem Behavior:
<Problem first started yesterday, 8/3/20, when I was in the middle of the first season of Brooklyn 99 episode 16. I had just finished episode 15 and went to watch the 16th but when I clicked on "watch now" button nothing happened. PT wouldn't play any episode anymore and would act the same way for several other TV shows, not all; this also did not happen with movies. I checked if the episode had seeds and it did.>
<img width="1280" alt="Screen Shot 2020-08-04 at 9 10 31 PM" src="https://user-images.githubusercontent.com/69223974/89357470-f3168800-d696-11ea-893b-3b99d7a040e1.png">

**Comment by dutchy1001** [comment]
@McKush 
If you downloaded a month ago then I advice to get the latest dev build (**[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**) and try again then.

I also checked the series availability but many episodes are very low in seeds which doesn't help either.

**Comment by Persei08** [comment]
@McKush try the last dev build as @dutchy1001 suggested to you.

I close the issue because, it was opened by @gigigurl and then you completed with your report which seem a different bug (he said "none", you said "several, not all" :/

Feel free to reopen your own issue eventually if dev build don't improve things. Thx
