### ISSUE TITLE
PT not updating with latest eztv content

### ISSUE THREAD

**Issue by ricnunes** [popcorntime/popcorntime#1588]
Operating System Version:
Windos 10

Popcorn Time Version:
0.4.4 - HEAD (18e3e426)

Download date:
01/07/2020

Download url (optional):
https://ci.popcorntime.app/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

#### Expected Behaviour
Update Series with newest content from eztv

#### Actual Behaviour
Most series seem to be "locked" from the 20th of July

#### Steps to reproduce the behaviour

1. Open eztv and search for Agents of SHIELD (or any current TV show)
2. Open popcornTime and search for Agents of SHIELD (or any current TV show)
3. Latest episode on PopcornTime is from July 16th (ep. 8)
4. Latest episode on eztv is from July 30th (ep. 10)

This appears to be happening for a while now. I'm able to open the .torrent if I download it manually, but checking out the subreddit, there are more people facing this issue. Is this an eztv or a popcorntime issue?

![image](https://user-images.githubusercontent.com/2053111/89094850-49967480-d3c0-11ea-8512-dca33daab78f.png)

**Comment by dutchy1001** [comment]
Trying to go to the ezty website is very buggy for me, it shows me "offline" pages or it won't connect at all. Either they have issue's or the ISP is blocking access.

**EDIT**
I can access eztv through vpn but not through my normal ISP. Not sure this has consequences for PCT accessing their content.

**Comment by ricnunes** [comment]
@dutchy1001 It's the same for me. I can only access it trough VPN. But I've locked PT to only work trough the VPN and on my gf's country eztv isn't blocked and she has the same issue, so I didn't included that info.

**Comment by dutchy1001** [comment]
PCT itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents. I can't confirm if eztv is in this list aswell.
If not then we are depending on what the other torrent site(s) post.

**Comment by Persei08** [comment]
Popcorn-api is supposed to parse "show list" page from eztv and recursively get all new episodes for each show (or at least the ones it founds metadata for).

Marvel's agents of S.H.I.E.L.D, Season 07 episodes 09 and 10 should appear in PT too but it seem something happened :/

**Comment by ricnunes** [comment]
Seems to be working now. Since I kept the same version of PT, I would assume there was an issue with eztv api.
