### ISSUE TITLE
Popcorn time to choose best rated subtitle on yify subtitles site

### ISSUE THREAD

**Issue by bokiroki** [popcorntime/popcorntime#159]
Operating System Version: Windows 10

Popcorn Time Version: 0.3.9

Download date:

#### Expected Behaviour

... It should choose best rated subtitle when downloading from yify subtitles
#### Actual Behaviour

... If i play Deadpool movie, and i choose serbian language, subtitle are out of sync.. and if i go to yify subtitles i can see that there are 3 different serbian subtitles for that movie. First one have rarbg in its name, and its out of sync, and it have zero likes. Second and third one have yts in their names they are synced and have 1 and 3 likes.. why popcorn time choose to use srt file with 0 likes over the one with 3 likes and with proper names?
#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by bokiroki** [comment]
I tried again after one user from reddit pointed me that different subtitles are used for different resolutions of movie. So i played Deadpool 720p and choose serbian language.. subtitles was out of sync, after that i went to yify subtitles site and downloaded all 3 available serbian subtitles for Deadpool movie, and tried all 3 subtitles with custom options on popcorn time.. all of them was in sync with movie, they were good..after that i again tried serbian language at popcorn time, and that subtitles are out of sync. How is that possible? where popcorn time is downloading subtitles for movies?

**Comment by NoGRo** [comment]
in fact always go to opensubtitle api

**Comment by ChrisAlderson** [comment]
We'll be using the Opensubtitle API for the subtitles.
