### ISSUE TITLE
In Favorite Tab the Type TV doesn't work properly.

### ISSUE THREAD

**Issue by Devologger** [popcorntime/popcorntime#1597]
Operating System Version: 
**Windows 10**

Popcorn Time Version:
**Popcorn-Time-0.4.4 Build [#428](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/428/) from ci.popcorntime.app HEAD ([18e3e426](https://github.com/popcorn-official/popcorn-desktop/commit/18e3e42627e81f45923a681f6262da1d4d144d98))**

Download date:
**Aug 4, 2020**

Download url (optional):
[#428 Build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/428/) 
[Popcorn-Time-0.4.4-win64-Setup.exe](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/428/artifact/build/Popcorn-Time-0.4.4-win64-Setup.exe)

#### Expected Behaviour
While I favorite a lot of movies and tv shows. I would like the feature to Favorite a TV Show and finding it in the Favorite tab with the Type "TV" selected to work, so I can find easily the TV shows that I favorited without going through all the movies too.

#### Actual Behaviour
You can favorite a TV Show just fine, and you can actually find it on the Favorites Tab, on Type "All", but if you try to filter out the movies by selecting Type "TV" nothing shows up.

#### Steps to reproduce the behaviour
1. Favorite a TV Show
2. Go on Favorite Tab
3. Select from the top bar from Type All to Type TV
4. You cant find the TV show that you favorited.

**Sorry my bad English.**

**Comment by dutchy1001** [comment]
I can confirm that this feature is not working using the same build and OS.

**Comment by dutchy1001** [comment]
This is still not working with the last build (429)

**Comment by Devologger** [comment]
This is happening too with "Anime" Selected also.

**Comment by dutchy1001** [comment]
fixed in build 431 for shows and movies, but as soon you add an anime show to the fav folder the fav folder won't load.
