### ISSUE TITLE
Chromecast suddenly not showing

### ISSUE THREAD

**Issue by Sambami** [popcorntime/popcorntime#161]
Operating System Version:
Windows 10

Popcorn Time Version:
pt.sh 0.3.9-0

Download date:
4-5-2016
#### Expected Behaviour

Show name of Chromecast in the "watch now" pop-up
#### Actual Behaviour

Only shows VLC and Butter
#### Steps to repoduce the behaviour

NA

**Comment by JPFALv** [comment]
Operating System Version:
Windows 10

Popcorn Time Version:
pt.sh 0.3.9-0

Download date:
3-15-2016

I´ve the same problem.

Someone can help us?

**Comment by mmenzyns** [comment]
Operating System Version:
Windows 10

Popcorn Time Version:
pt.sh 0.3.9-0

Download date:
4-15-2016

I have similar problem. Not chromecast, but all TV's at home dissapeared. Smartphone can see them normally.

**Comment by kscd95** [comment]
Operating System Version:
 Windows 10

Popcorn Time Version:
 pt.sh 0.3.9-0

Download date:
 4-25-2016

I'm having the same problem, the difference is that mine just shows butter. How do I fix this? It was working perfectly a few days ago.
