### ISSUE TITLE
VPN trouble

### ISSUE THREAD

**Issue by bunnykins007** [popcorntime/popcorntime#1619]
Operating System Version:
 Windows 10
Popcorn Time Version:

Download date:

#### Expected Behaviour
<bypass the vpn

#### Actual Behaviour
<keeps going and going not doing anything but the little circle keeps going on and the page will not appear -->
...

#### Steps to reproduce the behaviour

1. ...basically, I have my own VPN and tried to bypass the apply for a vpn, as I have one already.
2. ...
3. ...

**Comment by dutchy1001** [comment]
You can turn disable the VPN in the advanced settings and use your own one (to get the advance setting showing tic the box on top of the settings screen).

**Comment by Persei08** [comment]
If you get the spinning loader endlessly, you have a network issue. Maybe your vpn use a DNS which block popcorn-api domain or maybe your system use the DNS defined on OS side... or maybe it's something else related to network.

You don't have to bypass the vpn in PT, PT don't use it by default, it's an ad. You can ignore it, or disable the ad in settings by unticking "enable VPN" (yeah the label is confusing too)

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
