### ISSUE TITLE
Sort by number of unseen elements

### ISSUE THREAD

**Issue by wischi-chr** [popcorntime/popcorntime#162]
Operating System Version: Win7
Popcorn Time Version: 0.3.9 (80e3fc19)
#### Expected Behaviour

A button to sort series by the number of unseen episodes
#### Actual Behaviour

It is only possible to sort by actual number of seen elements and therefore not possible to sort series with most unseen episodes first.
#### Steps to repoduce the behaviour
1. Mark some series as fav.
2. Tag some episodes as seen
3. Try to sort the list so that the series with the most unseen items is first

**Comment by vzamanillo** [comment]
I propose a `pending` and `activity` filters.

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/sort-by-number-of-unseen-elements/102
