### ISSUE TITLE
No new releases since v0.4.4 (April 2020)?

### ISSUE THREAD

**Issue by schweini** [popcorntime/popcorntime#1635]
It seems that there's been a lot of welcome bug-fixing going on in the last months, but the latest downloadable release is still 0.4.4 from April 2020.

Is there any way of downloading a more recent binary or nightly build anywhere?

**Comment by pcenta** [comment]
You can download latest build from [Jenkins](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/).
Updating will purge your local database with watched movies and favourites so be sure to export it if you want to keep data.

**Comment by longnd** [comment]
how about releasing a new version, e.g. `0.4.5` for normal users which they can download it from the website since not everybody knows about the CI?

**Comment by pcenta** [comment]
I agree, we should probably wait so all the new minor issues are ironed out and there's no new release that brings new bugs but rather one that fixes some of existing issues.

Also if I remember correctly, one of the biggest problems regarding releasing new version is that users will get prompted to install new version and their local database will be deleted.

**Comment by ivan1986** [comment]
Yes, 0.4.4 was first wave of corona, 0.4.5 - second

**Comment by kiriles90** [comment]
@Persei08 close since its not an actual issue?
