### ISSUE TITLE
The Flash season six(6) episodes: One (Into the Void), Two (A Flash of the Lightning), Three (Dead Man Running) and fifteen (The Exorcism of Nash Wells),doesn't work( aren't downloading or being able to watch).

### ISSUE THREAD

**Issue by Tubilas** [popcorntime/popcorntime#1637]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Asking here to add movies or series (or missing episodes) is not the right place as they have no control over what's added and not.
