### ISSUE TITLE
[Feature Request] player mvp.net (mpvnet.exe)

### ISSUE THREAD

**Issue by ze0ss** [popcorntime/popcorntime#1639]
In the "Watch now" menu for choosing preferred player, both in movie and series tab, mpv.net player cannot be found listed, and as a result, I can't select it.
Yes, mpv.net is installed in "`C:\\Program Files\\`",  where other players like VLC are installed, and are selectable in the menu.

**Comment by Persei08** [comment]
mpv.net isn't supported.

I'll edit this issue title and mark it as a feature request

**Comment by Persei08** [comment]
project page: https://github.com/stax76/mpv.net

**Comment by ze0ss** [comment]
thank you :)
