### ISSUE TITLE
Nothing loads with or without VPN.

### ISSUE THREAD

**Issue by BlueNinjaX** [popcorntime/popcorntime#1640]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4 win32

Download date:
18/08/2020

Download url (optional):
https://get.popcorntime.app/build/Popcorn-Time-0.4.4-win32-Setup.exe

#### Expected Behaviour
I should have loaded all movies and shows.

#### Actual Behaviour
It didn't do anything. Except for endless loading

#### Steps to reproduce the behavior

1. open Popcorn-Time
2. Waiting for things to load...
3. Nothing happens

**Comment by dutchy1001** [comment]
Try updating with the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. 
If the issue is solved please close this post.

**Comment by BlueNinjaX** [comment]
> 
> 
> Try updating with the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.
> If the issue is solved please close this post.

**Comment by BlueNinjaX** [comment]
I'm on the latest dev build and still, this is happening. 
version is 0.4.4 win64
