### ISSUE TITLE
chromecast doesn't start

### ISSUE THREAD

**Issue by anamarijas** [popcorntime/popcorntime#1641]
Operating System Version:
OSX 10.15

Popcorn Time Version:
0.4.4

Download date:
in April

#### Expected Behaviour
chrome cast works

#### Actual Behaviour

chrome cast blue icon appears on TV, but nothing else happens

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Please provide more details.

Which video ?

Can be because the video format isn't supported by the chromecast :/

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
