### ISSUE TITLE
i cant watch anime or series on 4.4 version

### ISSUE THREAD

**Issue by pedzito** [popcorntime/popcorntime#1642]
Operating System Version: windows 10

Popcorn Time Version: 4.4 

Download date: 3 days ago 

Download url (optional):

#### Expected Behaviour

...
i thought I could watch any program it offered, movies, anime or series
#### Actual Behaviour

...i cant specifically watch anime or series, movies work fine

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Try updating with the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. 
If the issue is solved please close this post.

**Comment by pedzito** [comment]
it worked thank you very much!

**Comment by pedzito** [comment]
it worked on the first time on jojo, but after I tried on other shows just to be sure it stopped working again

**Comment by dutchy1001** [comment]
Many episodes are having a bad "magnet link" in the anime tab, meaning the availability is poor, this could be a reason.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
