### ISSUE TITLE
I can see anything,i click on episodes and nothig happened

### ISSUE THREAD

**Issue by lucs503** [popcorntime/popcorntime#1643]
Operating System Version:
WIndows 10

Popcorn Time Version:
4,4

Download date:
yesterday

**Comment by dutchy1001** [comment]
Try updating with the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. 
If the issue is solved please close this post.

**Comment by lucs503** [comment]
I choose the Windows 64 bit? Just that?

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:quinta-feira, 20 de agosto de 2020 18:44
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


Try updating with the latest dev build here<https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/>.
If the issue is solved please close this post.

**Comment by dutchy1001** [comment]
if your system runs 64bit then you can choose that setup

**Comment by lucs503** [comment]
Dont work for me

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:quinta-feira, 20 de agosto de 2020 19:32
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


if your system runs 64bit then you can choose that setup

**Comment by dutchy1001** [comment]
Uninstall popcorn and make sure all left over folders are deleted (check C:\Users\your name\AppData\Local\Temp\) and delete the folder there too.
(re)Download the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/434/)** and install it again. Choose the right one for your system.

To check your system if it's 32 or 64 bit right click on "**this pc**" in your explorer and choose "**properties**" this will open a popup which tells you what bit system you are using

**Comment by lucs503** [comment]
I think that work

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sexta-feira, 21 de agosto de 2020 11:55
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


Uninstall popcorn and make sure all left over folders are deleted (check C:\Users\your name\AppData\Local\Temp) and delete the folder there too.
(re)Download the latest dev build here<https://ci.popcorntime.app/job/Popcorn-Time-Desktop/434/> and install it again. Choose the right one for your system.

To check your system if it's 32 or 64 bit right click on "this pc" in your explorer and choose "properties" this will open a popup which tells you what bit system you are using

**Comment by dutchy1001** [comment]
If the issue is resolved please close this topic

**Comment by lucs503** [comment]
No, started again,not work

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sexta-feira, 21 de agosto de 2020 16:21
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


If the issue is resolved please close this topic

**Comment by dutchy1001** [comment]
When opening PCT click the F12 button on your keyboard. A pop-up will come on your screen, on the top of this pop-up click the "console" tab. If there is any error message there, copy it and post it here, this way a dev can see where there "could" be an issue.

**Comment by lucs503** [comment]
[cid:image003.png@01D677FC.49B2B200]

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sexta-feira, 21 de agosto de 2020 20:27
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


When opening PCT click the F12 button on your keyboard. A pop-up will come on your screen, on the top of this pop-up click the "console" tab. If there is any error message there, copy it and post it here, this way a dev can see where there "could" be an issue.

**Comment by dutchy1001** [comment]
can't see that image, not a valid link

**Comment by lucs503** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sexta-feira, 21 de agosto de 2020 20:51
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


can't see that image, not a valid link

**Comment by lucs503** [comment]
The swat season 2 is not working

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sexta-feira, 21 de agosto de 2020 20:51
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


can't see that image, not a valid link

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
On the right side of the screen in a movie/serie page is a coloured dot (green, yellow, red or gray), this tells you the availability of the torrent(s) were green is good and red or gray is not good. If the dot is red or gray your most likely will have issues, lots of buffering or not playing at all.
Depending on how many ppl are online "sharing" the torrent it will go up or down with the availability.

**Comment by lucs503** [comment]
How can i watch so?

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dutchy1001<mailto:notifications@github.com>
Enviado:sábado, 22 de agosto de 2020 19:13
Para: popcorn-official/popcorn-desktop<mailto:popcorn-desktop@noreply.github.com>
Cc:lucs503<mailto:lucasperobelli2004@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [popcorn-official/popcorn-desktop] I can see anything,i click on episodes and nothig happened (#1643)


Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
On the right side of the screen in a movie/serie page is a coloured dot (green, yellow, red or gray), this tells you the availability of the torrent(s) were green is good and red or gray is not good. If the dot is red or gray your most likely will have issues, lots of buffering or not playing at all.
Depending on how many ppl are online "sharing" the torrent it will go up or down with the availability.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
