### ISSUE TITLE
popcorn nao esta a funcionar correctamente

### ISSUE THREAD

**Issue by Maeiana** [popcorntime/popcorntime#1648]
Operating System Version:

Windows 
Popcorn Time Version:

 0.4.4
Download date:

13‎ de ‎agosto
Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...
ele nao me deixa desligar a app tenho que forçar fechamento e demora muito tempo para carregar um filme ou serie e tambem os filmes que meto para assistir travam sempre.
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Please read the pinned topic on top "popcorn time wont close"
Por favor, leia o tópico fixado no topo "popcorn time wont close"

Atualize para a versão de desenvolvimento mais recente **[aqui](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
