### ISSUE TITLE
Smart TV

### ISSUE THREAD

**Issue by Sipylos** [popcorntime/popcorntime#1651]
Operating System Version:
 WIN 10

Popcorn Time Version:
 0440

Download date:
 0824

Download url (optional):

#### Expected Behaviour
 playback on (Smart TV) device
...

#### Actual Behaviour
 The Smart TV (Sony KDL-50WF665) start to playback and after 10 sec it stops.
...

#### Steps to reproduce the behaviour
 

1. ...
2. ...
3. ...

**Comment by Sipylos** [comment]
The downloading on computer screen still running but the picture on the TV froze.

**Comment by dutchy1001** [comment]
Does the tv have enough storage for a movie or serie to download?

**Comment by Sipylos** [comment]
Thx for replying. Isn't that mirror casting or streaming via wifi?

**Comment by dutchy1001** [comment]
As far I know PCT downloads the file to the device. Like the on the pc it has a "temp" folder were the file is stored and then deleted when the program closes (in default setting). 

If anyone knows different please correct me.

**Comment by Sipylos** [comment]
If that's the case this TV doesn't have any storage space built-in. So probably the only solution will be an HDMI cable. Thx.

**Comment by dutchy1001** [comment]
> [Most Smart TVs allow USB connectivity. Utilise these ports to attach an external storage drive. With offline content offered as an option, added storage seems like a smart idea.](https://guide.servify.in/smart-tv-owners-tips/)

When going into the "advanced" settings set the "cache directory" to the attached usb storage, this is a possible fix for limited storage.

**Comment by Persei08** [comment]
@dutchy1001, to simplify, when casting PT works as usual. It make the downloaded video file available via http on the local network and send the url to the player. Here the smart TV instead of the bundled PT player.

You can see that easily by choosing VLC (in the dropdown menu of watch now button) as external player and then display the playlist of VLC to find the url of the video file 

@Sipylos can you plz retry and provides console logs (F12 key > console tab). Thx

**Comment by Sipylos** [comment]
[hecfofbbdfadifpemejbbdcjmfmboohj-1598987978275.log](https://github.com/popcorn-official/popcorn-desktop/files/5158352/hecfofbbdfadifpemejbbdcjmfmboohj-1598987978275.log)

Thanks for the aid. I hope you can see it.

**Comment by Persei08** [comment]
@Sipylos , just watched your logs

You have some errors related to opensubtitles, you can always create an account on opensubtiles.org and fill your login details in PT advanced settings to avoid thoses one... but your playback issue is something else, i see nothing wrong related to that in your logs :/
