### ISSUE TITLE
No subtitles shown in built-in player

### ISSUE THREAD

**Issue by MinionAttack** [popcorntime/popcorntime#166]
Operating System Version:
Windows 10 Pro 64 bits

Popcorn Time Version:
Popcorn #105 (21-abr-2016 14:09:53)

Download date:
21-abr-2016
#### Expected Behaviour

Show subtitles on butter player
#### Actual Behaviour

Subtitles are not shown, you need to use the external players to see it.
#### Steps to repoduce the behaviour

1 - Select a movie and the butter player.
2 - Select subtitles
3 - Subtitles aren't shown

**Comment by llopv** [comment]
Same here, with Linux

**Comment by VitorVRS** [comment]
OpentSubtitles are responding with different data.
It returns and html page instead of srt file.
