### ISSUE TITLE
No audio at all

### ISSUE THREAD

**Issue by Heb7540** [popcorntime/popcorntime#1660]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
28.08.2020

Download url (optional):

#### Expected Behaviour
Play sound
...

#### Actual Behaviour
No sound on any film (tried about 10 different ones)
...

#### Steps to reproduce the behaviour

I just went to play a movie,

**Comment by dutchy1001** [comment]
Have you tried an external movie player like **[SMplayer](https://www.smplayer.info/)** or **[VLC](https://www.videolan.org/vlc/index.en-GB.html)**?
This could solve the sound issue.
If solved please close the issue, if not let us know.
