### ISSUE TITLE
Downloads servers are down?

### ISSUE THREAD

**Issue by Roko131** [popcorntime/popcorntime#1661]
Downloads are down?
Tried a few of them, same error message.

none of our mirrors are able to handle your request, please try again later

![image](https://user-images.githubusercontent.com/3532929/91609192-9ea5b600-e97f-11ea-9b16-e7335dd0830a.png)

**Comment by dutchy1001** [comment]
Not sure what's going on, but if your looking for an update you can get the latest (dev) build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

**Comment by pabloga265** [comment]
> Not sure what's going on, but if your looking for an update you can get the latest (dev) build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

It's giving me a 522 error too in that link.

**Comment by dutchy1001** [comment]
brings me to the dev builds download page. 522 error could be a cloudflare issue.

> Code 522 stands for 'Connection timed out', which occurs whenever the TCP handshake between the web server and Cloudflare fails. ... Due to the high usage of Cloudflare, the 522 connection timed out error is one of the most common browser error messages.

**Comment by saxobroko** [comment]
There was a cloudflare issue which should be resolved now.

**Comment by Roko131** [comment]
Issue still occurring for me

**Comment by dutchy1001** [comment]
You better of lately to be using the dev builds as there less bugs in it. 
The site is working again so this topic can be closed.
