### ISSUE TITLE
Can't find working API url

### ISSUE THREAD

**Issue by Arno989** [popcorntime/popcorntime#1663]
This is probably the wrong place to ask but I can't find a working api url for my app that I made a while ago, I just wanted to try to fix the link to show people what I made but https://tv-v2.api-fetch.website/movies has seemed to be offline for a while

**Comment by kiriles90** [comment]
@Arno989 That's the old url. It got shutdown back in April. For the new one just replace _'.website'_ with _'.sh'_

**Comment by Arno989** [comment]
Ah yes, thanks a lot man, maybe the API docs should be updated then, the old URL is still described on https://popcorntime.api-docs.io/api/welcome and on https://popcornofficial.docs.apiary.io/#reference/movie/get-random/random

**Comment by kiriles90** [comment]
No worries and yeah you are right, they do need an update..  

For future reference though, you can always find the current urls in `\node_modules\butter-settings-popcorntime.io\index.js` in Popcorn Time's installation dir or just lookup said module in npmjs.com/package/butter-settings-popcorntime.io ('Try on Runkit' then 'Browse Files' > index.js)
