### ISSUE TITLE
No se cargan los Subtítulos en español aunque esté predeterminado 

### ISSUE THREAD

**Issue by Sonssytaz** [popcorntime/popcorntime#1668]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
**English:**
Opensubtitles.org now require users to be registered on their site to download subtiles.

Create an account on opensubtitles.org (not .com), then in PopcornTime advanced settings at opensubtitles section, fill your username and password so your account will be used to download your subtitlles.

**Spanish (via Deepl translate):**
Opensubtitles.org ahora requiere que los usuarios se registren en su sitio para descargar subtiles.

Cree una cuenta en opensubtitles.org (no .com), luego en la configuración avanzada de PopcornTime en la sección de opensubtitles, llene su nombre de usuario y contraseña para que su cuenta sea utilizada para descargar sus subtítulos.

**Comment by Sonssytaz** [comment]
Ok, Gracias voy a registrarme para que se carguen los subtítulos.
