### ISSUE TITLE
Change OpenSubtitles User Agent

### ISSUE THREAD

**Issue by VitorVRS** [popcorntime/popcorntime#167]
There are some issues created: #165 and #166 about not showing subtitles.

The problem is that OpenSubtitles are not acceptiong TestUserAgend anymore.
So, @team-pct  should add PCT user agent on jenkins build or commit direct on file.

To get an user agent from Open Subtitles you should send an email to them, as documented here: https://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst

And add new user agent here: https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/opensubtitles.js#L8

**Comment by team-pct** [comment]
Waiting to hear back from OpenSub , i have made my request as they asked

**Comment by bokiroki** [comment]
@team-pct, i'm happy that you gonna fix subtitle problem, but i must ask, why opensubtitle provider for movies? Opensubtitiles have to many subtitles and 99% of time subtitles with wrong timing are downloaded from them..why team changed subtitle provider from yify subtitles to opensubtitles? Before every subtitle was in good sync, now they are not..

**Comment by team-pct** [comment]
I understand , but all this is a preparation for the roll out of the Movies Popcorn Time Compatible API 
http://github.com/popcorn-official/popcorn-api

**Comment by bokiroki** [comment]
@team-pct ok i understand, can i than suggest few things if team want opensubtitles to be a provider..
first one: i think that this is already implemented, can program read movie file name, than look for subtitle that have same letters in its name.
second one: if i choose subtitle language in menu can popcorn time display me a popup window or something and let me choose what subtitle i want. (problem with curent system is that popcorn time detect 20-30 subtitles for one movie and choose one file and thats it, i dont have any control over it)
third and best solution: 5 or 10 minutes before movie end, display a popup for first 100-200 users who watched movie, and ask them if subtitles was ok, if they click yes, flag that subtitle or store it on some server for later use..
These are just sugestion, i believe that you guys have some solutions to this problems..

**Comment by VitorVRS** [comment]
@bokiroki @team-pct  PCT uses opensubtitles-api to fetch srt files from opensubtitles server... The search are made with "filename" parameters, which brings many matches.
I suggest to change this implementation to search by "hash" (https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes) like this: https://github.com/VitorVRS/peerflix-subtitles/blob/master/index.js#L27
but, this change only work for OpensSubtitles API and if the provider will be change in the future, can turn into a problem...

**Comment by ChrisAlderson** [comment]
This issue should be fixed with #223
