### ISSUE TITLE
there's no subtitle choices, they're not appearing 

### ISSUE THREAD

**Issue by adryavasc** [popcorntime/popcorntime#1672]
Operating System Version:
 Windows 10

Popcorn Time Version:
4.4

Download date:
05/09/2020

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot of error from developer console (optional)
![image](https://user-images.githubusercontent.com/70789857/92297741-b699ae80-ef18-11ea-91b6-bbec15277108.png)

**Comment by dutchy1001** [comment]
Have you created a account at [opensubtitles.org](https://www.opensubtitles.org/en/search/subs) and linked it in the "Advanced Setings" of PCT? 
If not do so and try again. Also see #1668
