### ISSUE TITLE
A legenda não está funcionando.

### ISSUE THREAD

**Issue by maryy31** [popcorntime/popcorntime#1673]
A legenda não funciona de jeito nenhum. Já desinstalei o programa e instalei e nada da legenda funcionar. 

Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Leia a edição #1318 , se você ainda tiver problemas, relate ou feche (ambos) o problema;

(translated with google)

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
