### ISSUE TITLE
Issue with one of the movies

### ISSUE THREAD

**Issue by CrazyJoey99** [popcorntime/popcorntime#1675]
The movie "i spit on your grave 2" is the wrong movie... when it plays it plays a different movie called I am Vengeance

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents. There is nothing they can do about this as they don't control those sites.

**Comment by kadhirumasankar** [comment]
Please close this issue. Thanks
