### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by fufa00001** [popcorntime/popcorntime#1676]
Operating System Version:
Windows 7

Popcorn Time Version:
4.4

Download date:
08/09/2020

Download url (optional):

#### Expected Behaviour
work?
...

#### Actual Behaviour
not loading at all
...

#### Steps to reproduce the behaviour
none, just installed it. Is not loeading

1. ...
2. ...
3. ...

#### Screenshot of error from developer console (optional)

![image](https://user-images.githubusercontent.com/54214943/92509460-e7efd400-f1cf-11ea-9c2e-3386fe6e677a.png)

**Comment by dutchy1001** [comment]
If you have downloaded this version from the main PCT page I can suggest to update to the latest dev build, you can get it **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/
)**. 
If solved close the issue or report back please.

**Comment by fufa00001** [comment]
Yes, i actually already found out and is all working.

**Comment by dutchy1001** [comment]
Just need to close this topic now.

**Comment by Persei08** [comment]
>Just need to close this topic now.

:D
