### ISSUE TITLE
Cannot open downloaded folder

### ISSUE THREAD

**Issue by lekhakmv39** [popcorntime/popcorntime#1678]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Update to latest dev build

**Comment by Persei08** [comment]
empty report, i close
