### ISSUE TITLE
Close button not working even in latest version

### ISSUE THREAD

**Issue by lekhakmv39** [popcorntime/popcorntime#1679]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
why create a new issue while your other one is still open?
No info given so no help can be expected....

**Comment by Persei08** [comment]
I close it, See @dutchy1001 comment. He said everything
