### ISSUE TITLE
Watchlist not working correctly

### ISSUE THREAD

**Issue by flumpiey** [popcorntime/popcorntime#168]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9.0
Download date:
Reinstalled 16 May 2016
#### Expected Behavior

Displays recently updated series i am currently watching
#### Actual Behavior

opens all items added to my trakt watch list including movies.
#### Steps to reproduce the behavior

Not sure what steps need to be taken but I don't  think the current issue is all bad. I would like to see categories within the watch list. one for series i am currently watching; one for movies i have not finished; one for series i want to watch and one for movies i want to watch.

**Comment by team-pct** [comment]
Duplicate
