### ISSUE TITLE
Watch now issue

### ISSUE THREAD

**Issue by MTcookiedoug** [popcorntime/popcorntime#1680]
Operating System Version:

Linux, Ubuntu 20.04
Popcorn Time Version:

4.4
Download date:

10 Sept. 2020
Download url (optional):

#### Expected Behaviour

...I thought I would be able to press the watch now button under movies or a series and be able to start watching the show.

#### Actual Behaviour

...When I press watch now nothing happens.

#### Steps to reproduce the behaviour

1. ...Find any show
2. ...Press watch now
3. ...Nothing happens

**Comment by dutchy1001** [comment]
have you tried the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**?
Try this and if issue still happens report back or close topic please.
