### ISSUE TITLE
Local folder as a content source

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#1683]
Torrent trackers are'nt the only possible source of videos.
Other programs can be getting asked movies by user, through other protocols.

My proposal is to add an option to select 1 or more folders to include video files in intercace's catalog and be able to run them on application player.

**Comment by Persei08** [comment]
So your feature request is more or less to add a media player feature.

Actually, you can drag and drop a video file into PCT window and it should start to play it

**Comment by narcisgarcia** [comment]
Is Popcorn a simple media player? No: Popcorn is useful to collect media catalog and present it well ordered on a nice interface. And it allows to select language track, etc.

**Comment by Persei08** [comment]
So, more a media library feature. 

Actually the media details (at least imdb id) are collected from torrent websites and then details are requested to other apis, but a folder can be parsed to detect video files, then the video filenames can be parsed too to detect year and title (expecting they have correctly formatted filename) and some apis could be requested to find corresponding movie details... it's what Kodi does i think.

it isn't a little feature.
How should it works, should local movies being integrated to movies tab and episodes to show tab ? Or maybe just adding another tab named "Local" or something with ability to filter by "movies" or "shows" (like favourites tab) will do the job.

It's a good idea, but pretty huge task :/

**Comment by narcisgarcia** [comment]
What does it mean "completed" ?
I don't see this feature.

**Comment by kiriles90** [comment]
Github always closes it as completed. I closed it because it cannot be implemented. We already have issues with APIs that dont have imdb ids and cannot be added, this has the same issue and even worse since its not even an API and can give no metadata we can trust.

**Comment by narcisgarcia** [comment]
If no metadata, then don't use the (no) metadata. Don't use same API to browse a local media folder: Only list files with thubnails, same as a filemanager does.

Popcorn-Time should one of two options at least:
a) Integrate in a wider environment (such as within Kodi, etc.)
b) Integrate other content sources (like kodi does)

Users they often acquire content with other methods (such as direct download, USB storage, ed2k, etc.), and it can't be assumed that Popcorn-Time is the first one in their history.

**Comment by kiriles90** [comment]
> If no metadata, then don't use the (no) metadata. Don't use same API to browse a local media folder: Only list files with thubnails, same as a filemanager does.  

And what is the point in that? Just open an explorer window and play whatever you want.  

> a) Integrate in a wider environment (such as within Kodi, etc.)
> b) Integrate other content sources (like kodi does)  

Popcorn Time is not kodi nor tries to be. If people wanted kodi they would have installed kodi.

**Comment by narcisgarcia** [comment]
> > If no metadata, then don't use the (no) metadata. Don't use same API to browse a local media folder: Only list files with thubnails, same as a filemanager does.
> 
> And what is the point in that? Just open an explorer window and play whatever you want.
> 
The point is to be able to use a single GUI with (p.e.) a single remote to watch contents.

> > a) Integrate in a wider environment (such as within Kodi, etc.)
> > b) Integrate other content sources (like kodi does)
> 
> Popcorn Time is not kodi nor tries to be. People who wanted kodi could have just installed kodi.
> 
I was just comparing to explain that user's world in a cinema session is not a single application or source.
Neither Kodi nor any plugin has features Popcorn-Time has.

**Comment by kiriles90** [comment]
I understand but this feature has issues. Like I said we wont be able to index anything, or fetch any metadata, covers, accurate subtitles etc. Even the thumbnails that you mentioned have issues. Nodejs and Chromium don't have anything like that natively, its a browser not an explorer window. If this was straightforward to implement and could be implemented in a good way that made sense, it would probably have been done back in 2014..

**Comment by narcisgarcia** [comment]
I read some like:
"It's too complicated to make something too simple".

**Comment by kiriles90** [comment]
Not my issue how you interpret things @narcisgarcia.
I read.. "I want it and I don't care about the reasons why this isn't in the scope of this app, practical or even possible with this framework, its not me who has to make it anyway..".

**Comment by narcisgarcia** [comment]
It's okay.

**Comment by dutchy1001** [comment]
@narcisgarcia 
> I read some like:
"It's too complicated to make something too simple".

If it that simple to you then why dont you code it...
