### ISSUE TITLE
titles will not load beyond start screen. also vpn will not work

### ISSUE THREAD

**Issue by lol2jz** [popcorntime/popcorntime#1688]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Invalid report, no info given.

**Comment by Persei08** [comment]
If you are asking a question rather than filing a bug, try one of these instead:
- Reddit /r/PopCornTime's FAQs (https://www.reddit.com/r/PopCornTime/wiki/faq)
- Reddit /r/PopCornTime (https://www.reddit.com/r/PopCornTime/)
- PopCornTime Forum (https://discuss.popcorntime.app/)

Invalid report.
