### ISSUE TITLE
Video stream freezes every few seconds, despite good internet connectivity

### ISSUE THREAD

**Issue by metteemo** [popcorntime/popcorntime#169]
Operating System Version:
Windows 10

Popcorn Time Version:
Latest version from Jenkins (105)

Download date:
5/15/16
#### Expected Behaviour

Video should not freeze and buffer after initial buffering
...
#### Actual Behaviour

The video plays for a few seconds, but then freezes consistently. Video is unwatchable.
#### Steps to repoduce the behaviour
1. Select any movie
2. Press play

**Comment by luizpicolo** [comment]
I have this problem too, but, my operation system is Ubuntu 16.04 LTS.
