### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by eli600** [popcorntime/popcorntime#1692]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
I sometimes wonder why they make an issue report like this, a 5 year old can do it better then this.

**Comment by Persei08** [comment]
@dutchy1001 lol, they spend more time registering on github than filling the report :/
