### ISSUE TITLE
Movies RTS.SH service down?

### ISSUE THREAD

**Issue by Chrometastic** [popcorntime/popcorntime#1694]
Operating System Version: W10 1809 LTSC ENTERPRISE N

Popcorn Time Version: 0.4.4.0 "love in the time of corona" beta - HEAD (b20007344)

Download date: About a month ago
 
Download url (optional): https://popcorntime.app/

Expected Behaviour

I open the movies tab to find a movie, click on it, and it works. 

Actual Behaviour

Movies page is not present at all

Steps to reproduce the behaviour
1. Open popcorntime. 
2. Go to Movies tab.
3. Be Dissapointed

**Comment by Persei08** [comment]
It's working here.

Can you try to open https://movies-v2.api-fetch.sh/status in a web browser (on the same machine running popcorntime)
it should display some json string looking similar to : 

```json
{"repo":"https://github.com/popcorn-official/popcorn-api.git","server":"serv01","status":"Idle","totalAnimes":704,"totalMovies":20361,"totalShows":4469,"updated":1600866000,"uptime":337307,"version":"2.2.3","commit":"6c8a9a4"}
```
try and tell us the result. We will know if your ISP is blocking the popcorn-api domain.

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close this please?
