### ISSUE TITLE
The SORT function shows random results.  "sort by last added" should display the latest entry by year/month/day.

### ISSUE THREAD

**Issue by ram54ram** [popcorntime/popcorntime#1699]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
What?

**Comment by dutchy1001** [comment]
guess an other invalid report.....

**Comment by kiriles90** [comment]
@Persei08 close this pls
