### ISSUE TITLE
Can't change cache folder

### ISSUE THREAD

**Issue by manwholikestothink** [popcorntime/popcorntime#17]
OS: Windows 10 x64
App version: 3.9

**How to repeat the problem:**
1. Open Settings
2. Click on Show advanced settings
3. Scroll til Cache directory
4. Click on text box and choose different folder
5. Click OK
6. NOTHING CHANGED

**Comment by brianardiles** [comment]
You try press F11? or restarting the app?

**Comment by raphcool12** [comment]
Hi guys is there a way to change the database directory because I also install the 2 popcorn time CE and  they both use the appdata folder so is anyone know how to change directory?

**Comment by manwholikestothink** [comment]
Yep, doesn't help. I even recorded this, if this can help: [link](http://1drv.ms/20QguHt).

**Comment by raphcool12** [comment]
wow a little me complicated for but thanks for trying to help :p in my case I'm talking the folder beleow the temporary folder the database folder is it the same steps as the temp folder?

sorry for my bad english :P

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/33/

**Comment by asaidi** [comment]
Still getting this issue with version 5.6.
OS: Windows 8.1
App version : 5.6

Cache folder path gets updated when closing the setting and reopen it again. Once the app is restarted the new path is overritten by the older one.

**Comment by Breaking1** [comment]
@asaidi this is for people who download their version from here https://popcorntime.sh/ 

You are using a different version.

**Comment by TheBlackKoala** [comment]
*I'm using arch-linux but it might be relevant.
I have found the error - in popcorntime/app/src/settings.js line 172 it uses os.tmpDir() instead of importing any saved settings.
What i did to change the cache-folder was simply to change it to this:
`Settings.tmpLocation = path.join("/home/tor/Desktop/Omit" /*os.tmpDir()*/, Settings.projectName);`

Because i wanted the temp folder to be in the "Omit" directory on my desktop. Change your filepath accordingly.

**Comment by peasead** [comment]
> *I'm using arch-linux but it might be relevant.
> I have found the error - in popcorntime/app/src/settings.js line 172 it uses os.tmpDir() instead of importing any saved settings.
> What i did to change the cache-folder was simply to change it to this:
> `Settings.tmpLocation = path.join("/home/tor/Desktop/Omit" /*os.tmpDir()*/, Settings.projectName);`
> 
> Because i wanted the temp folder to be in the "Omit" directory on my desktop. Change your filepath accordingly.

I did this for macOS (the file is located in `/Applications/Popcorn-Time.app/Contents/Resources/app.nw/src/app/settings.js`). Worked great.

Popcorn Time `Version 0.4.0 (0.4.0)`
