### ISSUE TITLE
Movies and Series thumbnails not working

### ISSUE THREAD

**Issue by lkhn** [popcorntime/popcorntime#170]
Operating System Version:
Linux (Arch Linux 64-bit)

Popcorn Time Version:
Github version - r5929.1815690-1 - https://github.com/popcorn-official/popcorn-desktop.git#branch=master

Download date:
May 23 16:52:20 AZT 2016
#### Expected Behaviour

Show all thumbnails.
#### Actual Behaviour

Movies and Series thumbnails not working but Anime and Indie section is working.
#### Steps to repoduce the behaviour
1. Install here - https://aur.archlinux.org/packages/popcorntime-git
2. Just Open it
   ![issue](https://cloud.githubusercontent.com/assets/10092215/15472383/46442330-2114-11e6-9b1a-08ea1c640735.png)

**Comment by miggs97** [comment]
From the looks of it the cause is an unknown SSL error 

`[19324:0523/172508:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

**Comment by lkhn** [comment]
I have this error too

`[6269:0524/020559:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

**Comment by Gabriel-p** [comment]
Same here, many of these:

```
[1319:0527/000213:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by DGEAPerez** [comment]
Same here, downloaded just a moment ago (May 30, 2016) Ubuntu 14.04 LTS

**Comment by alm69** [comment]
in movie and series tabs i have this issue! anime and India tabs they just fine.

**Comment by c-fains** [comment]
Same here with Ubuntu 14.04.1 LTS and Ubuntu 16.04 LTS (alter distro update)

Linux 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Clavos-Studios** [comment]
Same here, Ubuntu 15.10 and 16.04

**Comment by KernelFreeze** [comment]
Same here, I'm on arch Linux with xfce

**Comment by zach-ls** [comment]
Same here on Fedora 24.

**Comment by greg0ire** [comment]
@zach-ls : I'm using the latest Fedora and it works since yesterday or the day before.

**Comment by Gabriel-p** [comment]
@greg0ire which version of PT are you using?

**Comment by greg0ire** [comment]
I'm using 80e3fc1942efe7e4d6c9a1aa2066d917b33ba310 (version 0.3.9-0)

**Comment by Gabriel-p** [comment]
@ChrisAlderson why was this issue closed? Is it fixed in an upcoming release? I'm running version [0.3.9-80e3fc19](https://github.com/popcorn-official/popcorn-desktop/commit/80e3fc1942efe7e4d6c9a1aa2066d917b33ba310) and thumbnails still don't show.

**Comment by ChrisAlderson** [comment]
This was fixed by @VitorVRS with his #203 PR.

**Comment by Gabriel-p** [comment]
Thanks. Will PT auto-update at some point or must I download a recent build? I can't remember the last time PT updated itself...

**Comment by ChrisAlderson** [comment]
It should auto update at some point yea, but as always if you want to run the latest build you can go to ci.popcorntime.sh.

**Comment by lkhn** [comment]
I have using ci.popcorntime.sh build now and i can confirm everything is working fine about all of thumbnails. Thanks for attention!

**Comment by christianbueno1** [comment]
hello pals, I just downloaded Popcorn-Time-0.3.10-Linux-64.tar.xz  from [here https://popcorntime.sh/en ](https://popcorntime.sh/en) , I have to say that the thumbnails and posters are displayed with delay. 
I think that is odd because some time ago either windows10 or Ubuntu 15.10(Linux) the thumbnails and poster was appearing quick. 
One by one in disordely way they are appearing.
But once all pictures are shown that is about 10 minutes in average all run fine. If I search a movie happens exactly, tha movie searched  appears but the thumbnail take a time to be displayed.

**Comment by christianbueno1** [comment]
And, who are Jenkis  [ci.popcorntime.sh ](ci.popcorntime.sh) ?

**Comment by christianbueno1** [comment]
in what circumstances can i install popcorn-time-legacy? you let me  learn about it<br>
[https://ci.popcorntime.sh/](url)
