### ISSUE TITLE
Sort Aphabetically, jump to letter of alphabet.

### ISSUE THREAD

**Issue by mirddes** [popcorntime/popcorntime#1700]
when scrolling through the massive list of content it is easy to get lost.
when sorting alphabetically it would be of great assistance if in the scroll bar  we've got the whole alphabet as commonly seen on android/iOS lists allowing you to skip straight to movies starting with the letter x without 10 minutes of scrolling/loading the entire list.

visually there are certainly several ways to implement this feature.

whilst it is very easy to type in a search term it's not always gonna find exactly what you're looking for when you don't know exactly what you're looking for but you know it starts with X

skipping to arbitrary letters of the alphabet would be amazing

**Comment by kiriles90** [comment]
After looking into this a bit it isnt really possible at the moment the way the app and more importantly the API work, for a number of reasons. E.g there is no 'get movies that start with X char' functionality, so the only client based solution to this would imply that entire list of movies is loaded so you can jump to 'X'. (which would require hundreds of basically simultaneous API calls each time so ofc it could never work)

I guess maybe open an issue at [github.com/popcorn-official/popcorn-api](https://github.com/popcorn-official/popcorn-api) and if something like this is ever implemented the client/app part of it should be fairly simple. Closing this for now.
