### ISSUE TITLE
the movie "followed" is actually "babyteeth" is it possible to fix it please? thanks :) 

### ISSUE THREAD

**Issue by shunhashigaki** [popcorntime/popcorntime#1701]
The app don't manage the content. Results comes from third parties APIs.

This is useless to open an issue here for those kind of issues.

**Comment by kiriles90** [comment]
did you open an issue, replied to yourself (correctly) then added a wontfix label? why? :smile:

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
