### ISSUE TITLE
Button See Now/Download don't execute  

### ISSUE THREAD

**Issue by Villelmo** [popcorntime/popcorntime#1702]
Operating System Version:
Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

Popcorn Time Version:
Popcorn-Time-0.4.4-linux64

Download date:
vie sep 25 20:01:00 CST 2020

Download url (optional):
https://get.popcorntime.app/build/Popcorn-Time-0.4.4-linux64.zip

#### Expected Behaviour
Exact execution 

#### Actual Behaviour
The button don't execute your funcionality

#### Steps to reproduce the behaviour

1. Execute program
2. Select movie
3. Play movie

#### Screenshot(s) of issue or error(s) logs of developer console (F12 or ⌘+⌥+i , then 'console' tab) (optional)
`Uncaught (in promise) Error: 401 Unauthorized
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/home/lulu/Descargas/node_modules/opensubtitles-api/index.js:58
    at processTicksAndRejections (internal/process/task_queues.js:97)
22app.js:36 [ERROR] TypeError: Cannot read property 'path' of undefined
win.error @ app.js:36
app.js:17 [INFO] Watching: Ad Astra
www.youtube.com/iframe_api:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app.js:36 [ERROR] video.js error code: 0 vjs.MediaError
win.error @ app.js:36
video.dev.js:1409 VIDEOJS: ERROR: (CODE:0 MEDIA_ERR_CUSTOM)  vjs.MediaError
_logType @ video.dev.js:1409
0.jpg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app.js:17 [INFO] Watching: Ad Astra
app.js:17 [INFO] Player closed
app.js:17 [INFO] Streaming cancelled
6app.js:36 [ERROR] TypeError: Cannot read property 'path' of undefined
win.error @ app.js:36
app.js:17 [INFO] Show movie detail (tt7550000)
app.js:17 [INFO] hideunused (tt7550000)
app.js:17 [INFO] Returning cached provider OpenSubtitles
lang_dropdown.js:48 en
play_control.js:194 Audios: en
quality-selector.js:79 Select quality:  720p
play_control.js:182 Subtitles: none
/home/lulu/Descargas/node_modules/opensubtitles-api/index.js:58 Uncaught (in promise) Error: 401 Unauthorized
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/home/lulu/Descargas/node_modules/opensubtitles-api/index.js:58
    at processTicksAndRejections (internal/process/task_queues.js:97)`

**Comment by kiriles90** [comment]
Clean install build 437 from ci.popcorntime.app I think this is fixed

**Comment by dutchy1001** [comment]
Use this link **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**  to download the latest dev build

**Comment by kiriles90** [comment]
@Persei08 close this please

**Comment by Villelmo** [comment]
> Use this link **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** to download the latest dev build

Ready.
