### ISSUE TITLE
No option to load custom subtitle

### ISSUE THREAD

**Issue by marcusvnac** [popcorntime/popcorntime#171]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9-0

Download date:
20/04/2016
#### Expected Behaviour

I guess that it is loading subtitles from opensubtitles, but sometimes the subtitles are incorrect.
...
#### Actual Behaviour

There is no option to load a srt file to be used as subtitle
...
#### Steps to repoduce the behaviour
1. Find a TV Show
2. Try to find how to load an external subtitle

**Comment by VitorVRS** [comment]
If you are using default PCT player, there is a button (right after time bar) to select subtitle language, the last option is to load an external file labeled as "Customize" (?)

This option only appear when the movie/serie are playing.

**Comment by marcusvnac** [comment]
I would like to do this while streaming to Chromecast.

2016-05-24 21:58 GMT-03:00 Vitor Rocha da Silva notifications@github.com:

**Comment by MrRory** [comment]
that's technically impossible

**Comment by marcusvnac** [comment]
OK, but http://popcorn-time.to/ does :D

**Comment by MrRory** [comment]
then why not use their app?

**Comment by marcusvnac** [comment]
I thought that you're looking for improve your app, sorry.

**Comment by MrRory** [comment]
oh yes we do, but i dont like to be compared to them
