### ISSUE TITLE
Feature request: Advanced Filter Options

### ISSUE THREAD

**Issue by paivaandeerson** [popcorntime/popcorntime#1710]
- As a user I miss multiple genre selection filters to find specific movies.
 Ex: the program shows movies that is categorized in 'thriller' **and** 'mystery'

- I also miss a second 'sort' filter for the same reason.
Ex: Order By: 'trending'; Then By: 'title'

**Comment by Persei08** [comment]
Hi,

PopCornTime ask results to popcorn-api servers (which scrap torrents sites and third parties apis itself).

Popcorn-api don't support requesting multiple genres or sorting in same request, so in other words, you should open this feature request on popcorn-api project to begin with (https://github.com/popcorn-official/popcorn-api/issues)
