### ISSUE TITLE
Big bug on Cleopatra (1963) movie.

### ISSUE THREAD

**Issue by PandaLat** [popcorntime/popcorntime#1711]
Hi guys,

The classical "Cleopatra" movie (1963) has a big bug. The movie crashes down by minute 39:00 Could you fix this? Classical film fans as I will appreciate. Thanks!

Chihon Ley

**Comment by kiriles90** [comment]
The app doesn't manage the content. Results come from third party APIs.
Its useless to open an issue here for these kind of issues.

*Just find a different torrent somewhere and drag&drop the magnet link in Popcorn Time.
Also update to the latest dev build (438 at the moment) from ci.popcorntime.app for the above to go smoother

@PandaLat @Persei08 Please close this
