### ISSUE TITLE
Warning when episode sequence is missing an episode

### ISSUE THREAD

**Issue by Franck78** [popcorntime/popcorntime#1714]
**Is your feature request related to a problem? Please describe.**
Sometimes, the episode list is incomplete.
You get the list ok, 1,2,3,4,5,7,8,9,10,11,12 and start the bingewatching.
You press "watch next episode" as a reflex
Then you feal euh what are they talking about...

well, simply ep6 was not indexed in the torrent source. Exceptional but present.

**Describe the idea you'd like**

Just issue a warning if clearly the sequence numbering shows a hole (eg don't test for ep13). 

Example of a show 

"Impossible Engineering"
* season 5
* season 6
* season 8

have holes. Specific to this show, you will never notice ;)

I now, I should test under 4.4 before posting.

**Comment by Persei08** [comment]
Wait, which version niumber are you using ? Does "play next episode" feature is really working ?

there is issue #1352 which said it don't :/

**Comment by Franck78** [comment]
ah ah, I apply the rule "if it's working, don't update"

Yes still with 3.10 until I see some of my suggestions implemented
* preload next
* subtitles priority (english then french then nothing)
* this one (which is not very very important)

I have tried 4.4 two or three times but not until the "read next episode" popup, sorry.

**Comment by Persei08** [comment]
oh ok np.

I don't think there is a plan for subtitles priority. For now PCT return multiples subtitles per languages (when possible... there are even too much sometimes...but still better than just one) ![Screenshot_2020-10-22_15-32-00](https://user-images.githubusercontent.com/22459458/96878982-c430d680-147b-11eb-97cd-13ce93405a6c.png)

But I understand the need i though of it too since long time... Well now I have to create the feature request for it i guess :)

**Comment by Franck78** [comment]
Do your best, the important is being able to watch, my requests are 'convinience' only ;)

One thing that makes me crazy : syncing sound/subtitles. Never now the direction ;)

Thank you

**Comment by dutchy1001** [comment]
> One thing that makes me crazy : syncing sound/subtitles. Never now the direction ;)

This is indeed very annoying, I have the same issue sometimes and I use English the subs only.

Unfortunately this is probably an issue that is hard to combat as you need the same source from were the subtitle is made from to get the best results. 
As the subs come from a third party site (opensubtitles.org) it's finding the best synchronised source names for both files might only give the best result it can find. 

Having the option then to choose different files might fix the sync  for some then.

**Comment by Franck78** [comment]
Most of the time they are correct. Just need a shift 2sec 20secondes or -30 s. Sometime it takes me a lot of time to find the direction (+ or -) then how much. 

A thing  would be 'mark' that video frame, and when the correct text appear , another key to jump to the marked frame.

So "G & H" for easy small adjustment
And the mark method to invent when >30seconds

**Comment by Persei08** [comment]
>One thing that makes me crazy : syncing sound/subtitles. Never now the direction ;)

same, i never know if the offset need to be negative or positive
