### ISSUE TITLE
Peninsula (2020) English Subtitles not present

### ISSUE THREAD

**Issue by Pcolle** [popcorntime/popcorntime#1718]
Operating System Version:

Popcorn Time Version:

popcorntime 0.4.4

Download date:

2 months ago

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

... no subtitles appear but apparently are there.

#### Steps to reproduce the behaviour

1. ... select streaming Peninsula (2020)
2. ... Select the English subtitles
3. ... observe no subtitles appearing

**Comment by Persei08** [comment]
It's working here. but sub probably need to be sync.

![Screenshot_2020-10-02_15-03-35](https://user-images.githubusercontent.com/22459458/94926079-81a15d00-04c0-11eb-809c-cc0293de6485.png)

**Comment by Pcolle** [comment]
> It's working here. but sub probably need to be sync.
> 
> ![Screenshot_2020-10-02_15-03-35](https://user-images.githubusercontent.com/22459458/94926079-81a15d00-04c0-11eb-809c-cc0293de6485.png)

Whats the best way to do that? :o

**Comment by Persei08** [comment]
Try last dev build (438) eventually it works a bit better.

Then when you select subtitle, you can sync with g and h keys.
