### ISSUE TITLE
Scifi category appears empty.

### ISSUE THREAD

**Issue by SilverCory** [popcorntime/popcorntime#172]
Operating System Version:
Windows 8.1

Popcorn Time Version:
0.3.9

Download date:
3 weeks ago, but redownloaded via the ci today.
#### Expected Behaviour

Show movies relevant to the scifi category.
...
#### Actual Behaviour

"No movies found..."
...
#### Steps to repoduce the behaviour
1. Change category to scifi
2. cry because there's no scifi films.
#### Additional information.

Works on none of the "sort by" options either.

**Comment by VitorVRS** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/160

**Comment by SilverCory** [comment]
Duplicate issue, thanks, I did take a skim over before I created this. Missed it obviously.
