### ISSUE TITLE
No voice audio

### ISSUE THREAD

**Issue by spukiss** [popcorntime/popcorntime#1721]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date: 3.10.2020

Download url (optional): https://ci.popcorntime.app/job/Popcorn-Time-Desktop/

#### Expected Behaviour
 Have voice audio
...

#### Actual Behaviour
 No voice audio
...

#### Steps to reproduce the behaviour
 
1. Play any video
2. ...
3. ...

**Comment by kiriles90** [comment]
Its something specific to your system, you can either hunt it down, or use a supported external player.
Either way please close this, its not an issue with Popcorn Time.
