### ISSUE TITLE
Unable to recommence download after closing and reopening movie/series

### ISSUE THREAD

**Issue by dizzluk** [popcorntime/popcorntime#1722]
Operating System Version:
Win 10 (multiple systems, including 1 fresh install of W10)

Popcorn Time Version:
0.4.4 438 (been happening since 0.4 release)

Download date:
3/10/2020

Download url (optional):
ci.popcorntime.app/job/popcorn-time-desktop/

#### Expected Behaviour
recommence download of file

#### Actual Behaviour
Doesnt reconnect to peers/seeds and resume downloading

#### Steps to reproduce the behaviour

1. ... start watching a film/series
2. ... close the playing file
3. ... click 'Watch Now'
4. ... mouseover the 'eye' file will not download

![image](https://user-images.githubusercontent.com/72318552/95002399-6707da80-05cb-11eb-95ac-06773a395ace.png)
![image](https://user-images.githubusercontent.com/72318552/95002417-a0d8e100-05cb-11eb-90f5-4088db49d3db.png)

The only way to fix this error is close Popcorn and reopen

**Comment by dutchy1001** [comment]
It takes a good 30 seconds for me but the download will resume for me, but at a lot (less the 5% of the original speed) slower past. If I close PCT off totally and then restart the process of the same movie it will go back to full speed download.

**Comment by dizzluk** [comment]
I tried it on a couple of files. With high seeds/peers like new movies, you're correct, but testing with lower popularity files, it stays at 0 eg, 90 day fiancee, before the 90 days S04E01 initial download was 2.7 MB/s 3 Active Peers, after resuming and 5 mins 0MB/s and 0 AP's.
I only noticed this because of sketchy wifi dropping off, and having to close and resume a downloading file to reconnect to the peers.

**Comment by kiriles90** [comment]
Thats the way the seedbox feature works. It removes the peers and pauses the torrent. Then you'll have to wait a bit like @dutchy1001 said for new peers to be resolved. If you want you can just disable the Seedbox in the settings then Popcorn Time will return to the old, 'torrent destroy' behavior (ofc wont delete your cache files so you'll start from the same %)

**Comment by dutchy1001** [comment]
If you have set PCT to NOT clear TMP folder in the settings then the best way is to close of PCT then restart the whole process. This gave me the best results. 
Don't forget then to manual clear the TMP folder to prevent your HDD/SSD from filling up.

**Comment by dizzluk** [comment]
I turned off Seedbox, and full speed returns after restarting the file... thanks!

**Comment by dizzluk** [comment]
close this issue?

**Comment by kiriles90** [comment]
@dizzluk yep go for it, for now this is a byproduct of how the seedbox feature works, if a better solution is found it will be surely implemented

**Comment by dizzluk** [comment]
thanks guys!
