### ISSUE TITLE
Favorites - Limited Number

### ISSUE THREAD

**Issue by gericb** [popcorntime/popcorntime#1727]
macOS 10.15.7
Popcorn: 0.4.4-0
Installed:  6-20-2020

Can only save 6 FAVORITES.  Despite being able to select several SERIES, and click the heart to add to bookmarks, when actually clicking the ❤️ for favorites, or the favorites category, it only is showing 6, though I should have 8 or 9 total.

Thank You,
Greg

**Comment by kiriles90** [comment]
You are not limited to 6 favorites.. Something is bugged in your installation. Clean install the latest dev build from ci.popcorntime.app (438 at the moment) and please close this issue.

**Comment by Persei08** [comment]
Can't reproduce
