### ISSUE TITLE
THEME EDIT! (not an issue)

### ISSUE THREAD

**Issue by BNX070** [popcorntime/popcorntime#1735]
I just edited the css file for Sebastian Red & Black theme to Blue and Black and wanted to share it. To install you will have to add the theme in "C:\Users\USERNAME\AppData\Local\Popcorn-Time\src\app\themes".  the devs can decide to add it if they see fit. All the credit goes to the original author, I just changed it to my liking. Devs are free to remove this post if this is wrong... I didn't know where else to post this.

Download the zip file and add the .css file into the directory mentioned above. 
[Sebastiaans Blue n Black.zip](https://github.com/popcorn-official/popcorn-desktop/files/5360659/Sebastiaans.Blue.n.Black.zip)

**Comment by kiriles90** [comment]
> DO NOT CHANGE THE NAME or it won't work!  

You can change the name. I changed it to _Sebastiaans_-_Black_&_Blue_theme_ and it works fine. Btw why not make this a PR so it can be merged?

**Comment by BNX070** [comment]
> 
> 
> You can change the name. I changed it to `Sebastiaans_-_Black_&_Blue_theme.css` and it works fine. Btw why not make this a PR so it can be merged?

Oh, just checked it myself after updating popcorn time to the latest release and renaming works, somehow it wasn't working a few versions back. Edited the post & file accordingly now. BTW I'm not that familiar with github, I'll look into making this a pull request. Thanks

**Comment by kiriles90** [comment]
To help you get started, just fork the main repo(top right), duplicate `/src/app/styl/Sebastiaans_-_Black_&_Red_theme.styl` and rename it to blue, then edit and replace

    rgba(243,22,22,0.15)	->	rgba(22,188,243,0.15)
    #f31616			->	#1681f3
    #d40000			->	#0081d6
    #f4a460			->	#6295f4
    #fc6			->	#66b2ff
    #e32020			->	#2182e4
    #fc5753			->	#5489fc
    #fdbc40			->	#3f88fd
    #df2d37			->	#2e99e0
    #d9534f			->	#4fabd8
    #d43f3a			->	#3a8ad4
    #d2322d			->	#2d74d2
    #ac2925			->	#257fad

..and save it, then just create a pull request.

**Comment by BNX070** [comment]
> 
> 
> To help you get started, just fork the main repo(top right), duplicate `/src/app/styl/Sebastiaans_-_Black_&_Red_theme.styl` and rename it to blue, then edit and replace
> 
> ```
> rgba(243,22,22,0.15)	->	rgba(22,188,243,0.15) (this is the 'RedL' color variable)
> #f31616			->	#1681f3 (also 'RedL')
> #d40000			->	#0081d6 ('RedD')
> #f4a460			->	#6295f4
> #fc6			->	#66b2ff
> #e32020			->	#2182e4 ('RedM')
> #fc5753			->	#5489fc
> #fdbc40			->	#3f88fd
> #df2d37			->	#2e99e0
> #d9534f			->	#4fabd8
> #d43f3a			->	#3a8ad4
> #d2322d			->	#2d74d2
> #ac2925			->	#257fad
> ```
> 
> ..and save it, then just create a pull request.

I made a pull request by going to fork and directly adding the .css file to "styl" then made a pull request don't know if that's the right way to do it.....

**Comment by kiriles90** [comment]
Nop, you cant do it like that. The styl is what generates the css but they arent the same.

**Comment by BNX070** [comment]
> Nop, you cant do it like that. The styl is what generates the css but they arent the same.

I see, I'll try your method. Deleted the pr. Thanks

**Comment by kiriles90** [comment]
Edited above. The first 5 which are basically the main colors are very easy to replace and would only take a couple of minutes. The rest, if they are important might require some more digging and declaring/adding them in the .styl since the red theme wasnt modifying them to begin with, they were getting their values from the app's main .styl's which we cannot (should not) modify directly.

**Comment by BNX070** [comment]
> 
> 
> Edited above. The first 4 which are basically the main colors are very easy to replace and would only take a couple of minutes. The rest, will require some more digging and declaring/adding them in your .styl and maybe other styl's since the red theme wasnt modifying them to begin with, they were getting their values from the app's main .styl's which we cannot (should not) modify directly in this case.
> 
> Tbh.. I'd suggest leaving those alone and just do with the main ones and anything else inside the red theme's styl you'd like to modify, it would save you A LOT of trouble and potential issues.

I'm not finding a way to duplicate the file inside the repository, are there any commands? Do I clone it to.my desktop,edit then reupload? sorry I'm a total noob :P

**Comment by kiriles90** [comment]
> I'm not finding a way to duplicate the file inside the repository, are there any commands?  

Yeah, there is no way to duplicate it from the web interface afaik. There is an easier way though than using git.
Just download the entire repo in a .zip file (the green 'code' button, top right) then get the red theme from it, rename it into blue and upload it in the styl dir in your cloned repo. Then edit, make any changes you want, save it and make a PR.

**Comment by BNX070** [comment]
> 
> 
> > I'm not finding a way to duplicate the file inside the repository, are there any commands?
> 
> Yeah, there is no way to duplicate it from the web interface afaik. There is an easier way though than using git.
> Just download the entire repo in a .zip file (the green 'code' button, top right) then get the red theme .styl from it, rename it into blue and upload it in the styl dir in your forked repo. Then edit, make any changes you want, save it and make a PR.

Thank You, that's what I was initially thinking of doing but I thought there was a way through the web interface.

**Comment by Axe090** [comment]
@kiriles90 Made the changes and created a pull request. Only edited the Hex for the three you mentioned, hopefully it works fine I had made more changes to the css but Ill find and edit them later. Thanks for all the help, Cheers! (might edit a few different colors if this works)

**Comment by kiriles90** [comment]
Nice. You can add `#DF2D37 -> #2E99E0` too btw, its in there its just not declared as a variable.
Edit as much as you want, the more the better so its distinctly a new theme. If you edit the file in you repo now the PR will be automatically updated you dont need to do anything else. Just let people know when you are done so it can be reviewed/merged. Add a [WIP] or something (work in progress) in your PR's title, then just remove it when you are done.
