### ISSUE TITLE
480p only - the video could not be loaded

### ISSUE THREAD

**Issue by dizzluk** [popcorntime/popcorntime#1742]
Operating System Version: Win 10

Popcorn Time Version: 438

Download date: 1 week ago

Download url (optional): https://ci.popcorntime.app/job/popcorn-time-desktop/

#### Expected Behaviour

... trying to watch series in 480p

#### Actual Behaviour

... fails to load, have to watch in VLC, or play in 720p

#### Steps to reproduce the behaviour

1. ... try any 480p series - dexter, 90 day fiancee etc
2. ... (tried it on several computers running latest)
3. ... (tried installing k-lite pack)

**Comment by dizzluk** [comment]
with Dexter Season 1, only avaliable in 480p, so have to download in PCT, and then open file in VLC, then able to watch the file when its downloading, rather than downloading via torrent program, and waiting for complete and then watching

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (YIFY Torrents) or similar torrent agents.
Asking here to add movies or series is not the right place as they have no control over what's added and not.

**Comment by dutchy1001** [comment]
I have the same issue with Dexter S01E01 (and E02), most other episodes wont start due to availabilty. Seems it got not a "standard" file extention which might cause the issue with PCT (file name: dexter.102.hdtv.xvid-kyr.[VTV] ). PCT doen't know the extention
**.[VTV]** I presume.

Other "older" serie's working fine (depending on the availability ofcourse)

**Comment by dizzluk** [comment]
hi,
The dexter files download with .avi extension, as does 90 day fiancee: happily ever after, S05E18 480P. 

they save in the temp folder all as .avi

the 720p versions are .mkv

so PCT has problems displaying .avi files?

P

**Comment by dutchy1001** [comment]
It seems that .avi is giving issue's with playback on the PCT player, I have tried a few more serie's were an episode is in .avi format and all do the same. they do play fine on the external players (VLC or SMPlayer)

![no play](https://user-images.githubusercontent.com/5569980/95994565-5e639f80-0e28-11eb-8847-2360eb0bcfd1.png)

They all download when using the download button

**Comment by dizzluk** [comment]
yep, usually i skip to 720p, but with 480p only files i watch with vlc (as PCT downloads sequentially), i just need to manually find working subs (for the non fluent english people around me).

**Comment by Persei08** [comment]
Those are Xvid encoded videos. Xvid codec support was removed... i think because there were some issues with it, so it was better for users to play in an external player.

Installing a codec pack don't help here because PCT bundled player codecs are in the app (it's how nwjs works).

Also you should be able to watch the video in VLC even if not completely downloaded.

There is no plan concerning Xvid support in PCT as far as i know. So you should better rely on VLC or another external player for those files.


codecs infos of dexter S01E01... (because i checked :P) :

```
General
Complete name                            : /tmp/Popcorn-Time/dexter.s01e01.hdtv.xvid-hv.[VTV].avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 350 MiB
Duration                                 : 51 min 22 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 952 kb/s
Writing application                      : VirtualDubMod 1.5.10.1 (build 2424/release)
Writing library                          : VirtualDubMod build 2424/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings                          : BVOP2
Format settings, BVOP                    : 2
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Muxing mode                              : Packed bitstream
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 51 min 22 s
Bit rate                                 : 807 kb/s
Width                                    : 640 pixels
Height                                   : 368 pixels
Display aspect ratio                     : 1.739
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.143
Stream size                              : 296 MiB (85%)
Writing library                          : XviD 1.2.0SMP (UTC 2006-01-08)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 51 min 22 s
Bit rate mode                            : Variable
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 41.667 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 48.7 MiB (14%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 24  ms (0.58 video frame)
Interleave, preload duration             : 217  ms
Writing library                          : LAME3.90.
Encoding settings                        : -m j -V 4 -q 2 -lowpass 17.6 --abr 128
```

**Comment by dutchy1001** [comment]
@dizzluk 
There is already an issue made about the subs when using the download button (#1686 ), this will hopefully be fixed in later releases.
In the mean time you can use:
https://www.opensubtitles.org/en/search/subs
http://www.moviesubtitles.org/
https://subscene.com/

**Comment by dizzluk** [comment]
oh, i didnt know that it would (or should) download the subs to the same folder too!

thanks for the heads-up!

Really good support system and response on issues guys.

if avi's wont be supported in future ill close this issue... Thanks!

**Comment by dutchy1001** [comment]
If you have the subtitles set in the settings it should automatic download the correct one for the series, in movies you will have the option to keep default (from the settings) or choose a different language (I haven't seen any audio options then english).

PS.
You have to have an account at https://www.opensubtitles.org to let subtitles automatic be downloaded. You can then add the credentials into the settings of PCT.
