### ISSUE TITLE
NEW VERSION

### ISSUE THREAD

**Issue by rdisystem** [popcorntime/popcorntime#1745]
onde baixo a nova versão para PC atualizada ?

**Comment by helenapaixao** [comment]
Qual SO é o seu?

**Comment by dutchy1001** [comment]
Você pode baixar a última compilação de desenvolvimento **[aqui](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

you can donwload the latest dev build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by rdisystem** [comment]
WI10

Em sex, 16 de out de 2020 22:04, Helena Paixão <notifications@github.com>
escreveu:

**Comment by Persei08** [comment]
not an issue and answered, i close
