### ISSUE TITLE
Watch Now button unresponsive 

### ISSUE THREAD

**Issue by danusiak11** [popcorntime/popcorntime#1749]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...Find a series/movie click the watch now button, see if it works, for me it mostly doesn't
2. ...
3. ...

**Comment by kiriles90** [comment]
This has been fixed. Clean install the latest build from ci.popcorntime.app (439 at the moment, 0.4.4 is 413) and please close this issue.
