### ISSUE TITLE
Multiple preferred subtitle languages

### ISSUE THREAD

**Issue by Persei08** [popcorntime/popcorntime#1752]
**Is your feature request related to a problem? Please describe.**
When default subtitles language's subtitles aren't found, no alternative subtitles language is used.

**Describe the idea you'd like**
We should be able to define multiple preferred subtitles languages, so when subtitles aren't found for the 1rst preferred one, it try the next one, and then if not found again the 2nd next one, and continue like that...
Maybe could be great to be able to define a list of 3 (or even more) preferred subtitles languages

**Describe alternatives you've considered**
- keep doing it manually
- use external players which can auto download the subs and eventually do that too.

**Additional context**
Foreign speakers default subtitles language subtitles don't always exist. 
Myself I almost always use subtitles and will often prefer French then English subs as fallback.
I imagine a Brazilian can prefer PT-BR, then PT, then English.
I guess depending the number of language people are able to understand, this list should have the ability to be more or less long.
3 languages sound great, but maybe 5 or more could be useful to some people too

**Comment by sorin-costea** [comment]
See also #1990 ?
