### ISSUE TITLE
timeing delye in hebrow 

### ISSUE THREAD

**Issue by wiliplili** [popcorntime/popcorntime#1753]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
???

**Comment by Persei08** [comment]
timing delay in hebrew ?

**Comment by Persei08** [comment]
@wiliplili maybe use google translate if you're not comfortable enough.

But provides technical details, else we will not care of it and just assume it's an issue with subtitles or your pc

**Comment by dutchy1001** [comment]
just "delye" the support
