### ISSUE TITLE
kid mode

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1758]
**Is your feature request related to a problem? Please describe.**
there should be a setting to set PCT to a "kid mode" under a password at least. entering this mode, only animated and "G" or at most "PG" rated movies, shows or anime should show up to prevent kids from seeing naughty things.
**Describe the idea you'd like**
There has been attempts by other forks on a kid mode but i never used those and this feature is lacking in our version so here i am requesting adding here.
The material for this is already here, the parental rating is already coming from the API and that is displayed fine. Now just enforce "G" or "PG" rated content and we are golden. We could force content to "genre=animation" but that can be done via checkbox so this should be doable.

mpa_rating | "PG"
something like this api url from yts 
https://yts.mx/api/v2/list_movies.json&genre=animation&mpa_rating=g

**Comment by kiriles90** [comment]
This will never work as it is to be honest. A simple implementation might work vs a 6 year old, but a 12 year old will have a million ways to bypass to block. (just going and deleting your library + saved settings manually would be an easy one)

**Comment by test2a** [comment]
@kiriles90 ok. i will add a request there but how are we adding the rating on screen?

**Comment by test2a** [comment]
closing this for now until rating is added to api

**Comment by kiriles90** [comment]
There is the &mpa_rating parameter in the data the API returns. It just wont use it if you try to add it in a query. The ones it uses are the ones in https://popcorntime.api-docs.io/api/movie/FugRpgn5f3wjWSduF (sort, order, genre, keywords)

Just check the your example from above where you added it in the URL. It didnt matter it returned movies not G too as if it wasnt there.

**Comment by test2a** [comment]
there is one "certification"  but that is only in the response which is suspect is what is being currently used. hmm. so certification needs to be added in the query for this to work. right?

**Comment by kiriles90** [comment]
Yep
