### ISSUE TITLE
PT not working with nVIDIA Shield(Android 6.0)

### ISSUE THREAD

**Issue by somnathjk** [popcorntime/popcorntime#176]
Operating System Version:
<Android TV 6.0>

Popcorn Time Version:
 Beta 1.3 ARMv7a

Download date:
 2 days ago
#### Expected Behaviour

...Work correctly
#### Actual Behaviour

...
![nvidia_shield_pt_issue](https://cloud.githubusercontent.com/assets/19702404/15735272/ec8392c4-28b4-11e6-81cc-ab6e2e8b7029.jpg)
#### Steps to repoduce the behaviour

1. ... Sideload the above Beta 1.3 for ARMv7a APK file by copying from/to a USB stick and ES File Explorer
2. ...Try to run the installation using ES File Explorer , select 'Install' when the pop-up shows up to select between 'Market  | Install' 
3. See this issue 
4. Infact yesterday when i logged into my Shield, i even saw PopCornTime icon prompting me to see a movie (Zootopia) , when i clicked again i get the same Pop-up Error as attached.
5. ...

**Comment by VitorVRS** [comment]
@somnathjk maybe you want to create this issue on: https://github.com/popcorn-official/popcorn-android ?

**Comment by somnathjk** [comment]
Thanks for looking in . Sure .. Done!

https://github.com/popcorn-official/popcorn-android/issues/37

**Comment by brazucao** [comment]
I installed and is working properly PCTV version 1.3 ARM64-V8A > https://ci.popcorntime.sh/job/Popcorn-Time-Android/80/artifact/tv/build/outputs/apk/tv-arm64-v8a-development-80.apk

**Comment by VitorVRS** [comment]
This issue was closed on popcorn-android repo.
Closing issue here too.
