### ISSUE TITLE
Completely hide titles marked as seen

### ISSUE THREAD

**Issue by ppo** [popcorntime/popcorntime#1760]
Please add a toggle button/checkbox in the filter bar allowing to hide titles that I've marked as seen (not just faded as currently).
This should be on (=hide) by default, or as defined in settings.

**Comment by kiriles90** [comment]
Some people might not want to change this to 'hide' by default. Just go and change this for yourself in the settings whats the need for a filterbar button?

**Comment by ppo** [comment]
Sorry, I didn't saw the "watched items" option in the settings. So that's OK.  

My usual use case…
First, I'm looking for a new movie to watch. So movies that I've already seen are just noise in the list, I don't want to see them.
Often I don't find one so, as a fallback, I want the movies I've seen to appear in the list anyways… actually I would like to see only them (like the "favorites" screen but for "seen").
