### ISSUE TITLE
Mark a title as "trashed"

### ISSUE THREAD

**Issue by ppo** [popcorntime/popcorntime#1764]
Please allow to "trash" a title from the list/search results so that it doesn't appear in the list anymore.
It could probably still appear in the search results (faded), or ideally only if a checkbox "show trashed titles" is on.

There should be a way to list all trashed item. Maybe on a special screen like favorites with tabs like favorites / seen / trashed.

**Comment by dutchy1001** [comment]
this can be set in the settings.
![trashed](https://user-images.githubusercontent.com/5569980/97070573-3ff06780-15d1-11eb-8c03-7af7a712055d.png)

Default is set to "fade", change it to "hide" and they should be gone from your list (you still need to "mark as seen" yourself first).

**Comment by kiriles90** [comment]
@ppo This is basically the same thing as your https://github.com/popcorn-official/popcorn-desktop/issues/1760 which both can be easily done by changing the default value like @dutchy1001 showed above. Please close both..

**Comment by ppo** [comment]
It's not the same, I want to discard movies I know I'll never want to watch.  
Currently, I saw a lot of movies over and over again in the list while knowing that I don't want to see them, so pure unnecessary noise.

As you may make a mistake, or change your mind, there should be a way to see them. Hence the idea of a special multipurpose screen for "flagged" items (favorites, seen, trashed).

PS: As said in #1760, I didn't saw that setting.

**Comment by dutchy1001** [comment]
Any movie you don't wanna see you can mark "as seen" should do the trick (you have to click them 1 way or another). 

I understand that if you make a mistake it's hard to get that one back unless you get all the movies out of "hide" mode. 
If they have to add an other "don't wanna see/seen" tab then that would be an other database added to the program which could impact the speed, ram, disk use, etc etc. 
While the hide/fade is already in place it isn't a big issue to turn on/off to get a movie back into the list.

**Comment by kiriles90** [comment]
@ppo So basically you want a second 'Seen' and this one to be named 'Trashed' and a tab favorites-style where both of them can be visible? Well can you close both issues and open one issue with this?

**Comment by ppo** [comment]
@dutchy1001 No, seen is whether I saw it or not 😛 Like favorite is for those I really liked, not for those I want to see later 😉 

@kiriles90 I'll think about that and create a new issue with a better thought-out proposal. (sorry, insomnia/brain-dead yesterday and just flushed my brain)
