### ISSUE TITLE
Setting default subtitles not taken into account

### ISSUE THREAD

**Issue by ppo** [popcorntime/popcorntime#1765]
Operating System Version: macOS 10.15.7  
Popcorn Time Version: 0.4.4  
Download date: ???  
Download url (optional): installed via homebrew

#### Expected Behaviour
The default subtitle language should be selected by default in the detail view of a movie/serie.

#### Actual Behaviour
No subtitle language is selected by default.

#### Steps to reproduce the behaviour

1. Open a title (movie or TV show) to open the detail screen.
2. Look at the subtitle dropdown.

**Comment by dutchy1001** [comment]
As far I know when the default subs are set in the settings tab it will show. I'm not sure you have an "opensubtitles.org" account linked to your PCT but that should help.
![subs](https://user-images.githubusercontent.com/5569980/97049575-d857ff00-1573-11eb-9238-219dff8a5fa8.png)
When selecting a movie you have the option, as shown on the picture, to choose a different language sub if you want. When choosing a serie the subs will only be the default set in the settings.
I'm not sure what version you have of PCT 0.4.4 but there are many dev builds after the one on the main website.
The latest dev build you can find **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

**Comment by ppo** [comment]
Well, what I'm saying is that what you explain doesn't work for me 😉  
The default subtitles language configured in the settings (French) is not selected by default. (Subtitles were available in French)

I don't have an OpenSubtitles account… but that shouldn't change anything as subtitles are anyway available in my default language.

I've always had that problem. I started using PCT a few months ago.

I've the latest version installed via brew cask. (I'll check on my computer later)

**Comment by dutchy1001** [comment]
> I don't have an OpenSubtitles account… but that shouldn't change anything as subtitles are anyway available in my default language.

After opensubtitle.org had changed their API you need an account there to have the subtitles working, this is explained here in issue #1318 .
Create  an account at opensubtitle.org and fill in the credentials in the PCT settings then try again to see if it works for you, if so close this issue, if not report back here.

**Comment by kiriles90** [comment]
@ppo you are using an old version. This is fixed. Update to the latest dev build from ci.popcorntime.app (or build from the development branch here) and close this issue please.

**Comment by Persei08** [comment]
Already done in latests dev build.

**Comment by dutchy1001** [comment]
Does this mean we don't need an account at opensubtitle.org anymore?

**Comment by kiriles90** [comment]
@dutchy1001 Yeah most of the time, except when opensubtitles "forgets" they excluded Popcorn Time's useragent. Either way, login in is a good suggestion to whoever is having issues with the subtitles.
