### ISSUE TITLE
Volume bar not full when on 100% and not empty on 0%

### ISSUE THREAD

**Issue by FadilSmajilbasic** [popcorntime/popcorntime#1766]
Operating System Version:
Windows 10-2004

Popcorn Time Version:
Popcorn time 0.4.4 build #439

Download date:
23.10.2020

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/439/

#### Expected Behaviour

When I set the volume to 100%, the volume bar should be full.
When I set the volume to 0% the volume bar should be empty
...

#### Actual Behaviour

The blue bar of the volume bar fills just ~90% of the bar when on 100%
The blue bar of the volume bar fills ~10% of the bar when on 0%
...

#### Steps to reproduce the behaviour

1. Start watching a movie/series
2. Increase the volume to 100%
3. Look at bar
3. Decrease the volume to 0%
4. Look at bar

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![Screenshot 2020-10-23 222838](https://user-images.githubusercontent.com/37296353/97051260-258d9e00-157f-11eb-9837-d0ccf8698a24.png)

![Screenshot 2020-10-23 222930](https://user-images.githubusercontent.com/37296353/97051315-3b02c800-157f-11eb-8cde-de1327e004ee.png)

**Comment by dutchy1001** [comment]
This is only a cosmetic issue and will not affect the movie or serie your watching.
Hopefully 1 of the devs will fix this but I don't think it will have a priority

**Comment by dutchy1001** [comment]
This should be fixed in the next (dev) build
