### ISSUE TITLE
New Update is causing troubles playing certain episodes

### ISSUE THREAD

**Issue by iMansoorAliKhan** [popcorntime/popcorntime#1780]
Operating System Version:

windows 10 2004

Popcorn Time Version:

Most recent on this gig hub

Download date:

don't remember

Download url (optional):

#### Expected Behaviour

...

Should be playing the 480P quality but its not

![image](https://user-images.githubusercontent.com/11312949/97794965-5f674000-1c22-11eb-8652-a288160eaedc.png)

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ... Open star track new season
2. ... open any of the 3 episodes avail and click on play for 480P or any quality
3. ... first 2 click would not open the player but 3rd will. but in console there is an error.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/11312949/97794986-8faede80-1c22-11eb-9f90-24335b1700a6.png)

Log of console attached for your kind reference
hecfofbbdfadifpemejbbdcjmfmboohj-1604154852218.log

**Comment by dutchy1001** [comment]
This is because there Xvid format which is not supported by PCT
See #1742

**Comment by kiriles90** [comment]
Doesnt really have anything to do with the new update. They are xvid like @dutchy1001 said which never played, as for the rest of the errors looks like its because opensubtitles was down when you were doing this.

Use a supported external player or select a different quality, 720p/1080p play fine.
