### ISSUE TITLE
search movies bug

### ISSUE THREAD

**Issue by despinasar** [popcorntime/popcorntime#179]
Operating System Version:
OS X 10.11

Popcorn Time Version:

Download date:
 June 12,2016
#### Expected Behaviour

find the movie I asked for,which has found in windows in another pc earlier
...
#### Actual Behaviour

it wasn't showing me the movie I wanted
...
#### Steps to repoduce the behaviour

1.open search and look for the movie 6 years ...
2. ...
3. ...

**Comment by Breaking1** [comment]
It works just fine when i search for movies in my version, sure you are using the version from https://popcorntime.sh/? (0.3.9.0)

It doesn't find the movie 6 years but a lot of other movies with 6 and years in it which probably means that it doesn't exist in the DB. You van always use Torrent collection(The folder next to your favourites) and search for any missing movie/series with Kickass or Rarbg.

**Comment by MrRory** [comment]
this aint a bug
