### ISSUE TITLE
Chromecast problem

### ISSUE THREAD

**Issue by FMisplon** [popcorntime/popcorntime#18]
Having problems with Popcorntime.sh & Chromecast (v1).
It starts well if i press 'play on chromecast'. I'm getting this screen then on my tv...
![1](https://cloud.githubusercontent.com/assets/13984363/13203913/b1676f5e-d8c2-11e5-93c9-552e51360946.JPG)
On my  laptop I see this:
![2](https://cloud.githubusercontent.com/assets/13984363/13203914/b92834a8-d8c2-11e5-8dfd-da92c81f6982.JPG)
It stays for ages likes in the first two pics, and after a few minutes on my tv i'm getting this...
![3](https://cloud.githubusercontent.com/assets/13984363/13203915/c7fa32c4-d8c2-11e5-8cb8-90f1eaedaa5f.JPG)

Anybody knows how to solve this?

**Comment by brunobsouzac** [comment]
this has happened to me too, to solve I turned off the TV, took the chromecast and after a few seconds I returned the call. Popcorn closed and then reopened and started the normal process of streaming and it worked.

Chromecast sometimes crash

**Comment by brunobsouzac** [comment]
The real problem is NOT to see television shows in 720p with audio!
or watch 720p movies with subtitles!
or you can select a caption after streaming!
