### ISSUE TITLE
No images appearing

### ISSUE THREAD

**Issue by DoNotSpamPls** [popcorntime/popcorntime#180]
Operating System Version: Ubuntu 16.04 (64 bit)

Popcorn Time Version: 0.3.9.0

Download date: 12/06/2016
#### Expected Behaviour

I expect the program to show images of the movies I search. (note that it only happens in the Movies and Series tab, Anime and Indie work just fine)
#### Actual Behaviour

It shows the default picture and when I open a movie, it shows up as a broken picture.

**Comment by juanmacio** [comment]
@DoNotSpamPls Did you got it working?

I'm having the same issue today with version 0.3.9-0 on Ubuntu 16.04 (32-bit) downloaded from website.

**Comment by DoNotSpamPls** [comment]
Closed the issue because there it was already reported [here](https://github.com/popcorn-official/popcorn-desktop/issues/115), [here](https://github.com/popcorn-official/popcorn-desktop/issues/49) and (possibly) fixed [here](https://github.com/popcorn-official/popcorn-desktop/pull/203)

**Comment by ghost** [comment]
I wouldn't call going back in time from SSL to unencrypted connections a fix, at all. It's by far the most stupid pull request I've ever seen, and the Popcorn developers are even more stupid to have actually merged it.

**Comment by DoNotSpamPls** [comment]
¯_(ツ)_/¯. even if that's the case, this is not the issue to complain in.
