### ISSUE TITLE
watch now and download not working

### ISSUE THREAD

**Issue by CharlotteRicca** [popcorntime/popcorntime#1802]
I have been using popcorn time for ages, but now it wont' let me play or download anything. I have reinstalled and also set up a VPN. But still not working

Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...Hel
2. ...
3. ...

**Comment by dutchy1001** [comment]
As you didn't fill in all fields required to help us help you there is nothing much we can tell you how to fix this. Only thing I can say is to update to the latest build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. 
If the issue isn't fix after this please report back with all fiels filled in.

**Comment by CharlotteRicca** [comment]
ok I found the system really confusing to fill in, will try again now
