### ISSUE TITLE
Custom Proxy Support

### ISSUE THREAD

**Issue by lucasdcrk** [popcorntime/popcorntime#181]
Please add in-app proxy server support, to avoid HADOPI in france.

**Comment by VitorVRS** [comment]
Don't you need a VPN instead?

**Comment by MrRory** [comment]
you should use a vpn

**Comment by silanea** [comment]
I would like to ask that the devs re-evaluate this request. I run a dedicated server on my LAN which provides VPN access for selected services, and I'd really like to run Popcorn Time on my workstation through this server. PT is one of the very few Torrent-based applications I know that lacks a configuration option for a proxy.
