### ISSUE TITLE
[Windows 10] UI stuck at loading content with very high GPU and power usage

### ISSUE THREAD

**Issue by rexmtorres** [popcorntime/popcorntime#1816]
The problem is intermittent.  Usually it just happens upon launch or some time after when switching between tabs (e.g. Movies to Series).

The UI would get stuck in loading contents and would just show the circular progress indicator indefinitely as shown below.
![image](https://user-images.githubusercontent.com/17244755/98678678-e7bfb080-2399-11eb-8de1-ae245c73a16b.png)

Once this happens, the app cannot be closed.  You will have to kill it through Task Manager.  And, when you look at Task Manager, you will see that it has a very high GPU usage, sometimes getting to 100% (my machine has NVIDIA GTX 1060), and a very high power usage.
![image](https://user-images.githubusercontent.com/17244755/98678698-ec846480-2399-11eb-9480-85237ab7e3e0.png)

Version used is 0.4.4, but I remember encountering this issue with an older version too.

**Comment by dutchy1001** [comment]
You didn't fill in the issue form with the details we need, this way we cant help as we don't know what we have to work with . For all we know your still on windows 95

**Comment by kiriles90** [comment]
Have you tried using the latest dev build from ci.popcorntime.app?

**Comment by Persei08** [comment]
0.4.4 is too old, lot of things have been improved and fixed here and there. You should test with latest dev build.
