### ISSUE TITLE
any news about possible update? even if it is a  nor one?

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#1817]
I am longing to see any new fixes on popcorn, lately the app takes too much time to load sometimes

**Comment by kiriles90** [comment]
There are plenty of commits almost everyday. Get the latest dev build from ci.popcorntime.app

Closing this since not an actual issue but you can still comment below if you need something else.

**Comment by fisforfaheem** [comment]
Thanks )
