### ISSUE TITLE
Bookmarked [:heart:] list Button is missing from the menu

### ISSUE THREAD

**Issue by tanvir-kx** [popcorntime/popcorntime#1818]
Operating System Version:
Linux/Debian (Deepin v20)

Popcorn Time Version:
In PT app shows 0.4.4-0 "Love in the time of corona" Beta. But I have used November 9, 2020 **build #441** from PT Jenkins.  

Download date: November 10, 2020.

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/

#### Expected Behaviour
Show a Bookmarked [:heart:] list Button on the right hand side of the menu.
...

#### Actual Behaviour
No Bookmarked [:heart:] list Button on the right hand side of the menu.
...

#### Steps to reproduce the behavior
Install and run the dev build #441 from PT Jenkins.

![Screen Capture_select-area_20201111142153](https://user-images.githubusercontent.com/68131844/98788505-2e112000-242b-11eb-8723-1413ac6995b9.png)

**Comment by kiriles90** [comment]
It moved on the left and became the Favorites tab long time now.

Closing this since now an actual issue.
