### ISSUE TITLE
Create a new official release

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#1829]
It's been over half a year since the latest release and there's been almost 500 new commits. Most people don't know how to build the version of popcorn time and are stuck using the old version. It'll be good if all those users could get an official update that fixes bugs and improves things for them.

**Comment by kiriles90** [comment]
You don't need to build it, you can get the latest dev build from ci.popcorntime.app  
But I somewhat agree, its time for a new release version.

Closing this since not an issue with the app but feel free to still comment below.
