### ISSUE TITLE
[Feature] Intelligent preloading of series episodes

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#183]
A cool feature to save buffering time could be to start preloading the next episode if less than 5 peers are available, doing some calculations on average swarm speed to decide when to start downloading (after reaching half of the playback).

**Comment by VitorVRS** [comment]
There is an preload already, on the last 60 seconds of the show its started an background streaming (but without any calculations).
I guess there are some configuration for this  (like autoplay next episode).

**Comment by beppe9000** [comment]
Ok so this will only be for the calculations part, then

**Comment by ChrisAlderson** [comment]
Is this issue/feature
