### ISSUE TITLE
Copy/Paste in search bar

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1841]
_**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This is not related to an issue or caused by an issue (as far I'm aware off).

_**Describe the idea you'd like**
A clear and concise description of what you want to happen._

Adding the right mouse button click to copy/past in the search field.
(find a movie name online and just paste it into the search bar).

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._

You could use ctrl V but with the mouse it's easier done.

_**Additional context**
Add any other context or screenshots about the feature request here._

N/A

**Comment by kiriles90** [comment]
Done! Nice catch :)

**Comment by dutchy1001** [comment]
Fastest fix I ever seen 😛

thx m8
