### ISSUE TITLE
Limit download speed

### ISSUE THREAD

**Issue by dizzluk** [popcorntime/popcorntime#1846]
**Is your feature request related to a problem? Please describe.**
Is it possible to throttle download speed (without using external program) PCT has problems on playback when downloading at 13MB/s, stutters and stalls.

**Describe the idea you'd like**
Global download speed limit

**Describe alternatives you've considered**
Looked at TP software, but dont want to limit global speed on machine, just PCT

**Additional context**

**Comment by kiriles90** [comment]
This isnt possible at least at the moment since WebTorrent doesnt have a way to limit/throttle the upload/download speed. This needs to change first then Popcorn Time can maybe update it and implement something. 

Closing this for now.

**Comment by kiriles90** [comment]
#2265 merged
