### ISSUE TITLE
Global subs, changing to another language

### ISSUE THREAD

**Issue by dizzluk** [popcorntime/popcorntime#1847]
Operating System Version:
Win 10

Popcorn Time Version:
Latest from repository, downloaded 3 days ago (stable build)

Download date:
Latest from repository, downloaded 3 days ago

Download url (optional):

#### Expected Behaviour
Set global default sub to English, before upgrade to latest would automatically play english subs
...

#### Actual Behaviour
system is choosing Espagnol instead, have to manually change to english (esp is selected blue on bottom right box)
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Any specific movie/serie this happens? 
Just checked 3 movies and 2 series all getting the right subs for me. My default is EN subs set in the setting.

**Comment by dizzluk** [comment]
*Embarassed*

Someone changed the default global subs to spanish (probably to mess with me)

Apologies, thanks for speedy response as always 

P

**Comment by dutchy1001** [comment]
np, stay save and watch what ya can
