### ISSUE TITLE
Mandalorian 4K

### ISSUE THREAD

**Issue by 123Olairy** [popcorntime/popcorntime#1848]
Hey Folks
First time so forgive mistakes. 
Popcorn has kept us all entertained through Covid Lockdown Thank you all. 
One bug I have found is that Mandalorian 4K has now been added for Series 2. 
However, after downloading episode 9 on a few different occasions each download has the same problem. The whole programme has a green colour cast? Normally this is a sign of an encoding problem. We have many other HEVC videos that play okay. Surprised this was not exported as a 4K .mkv bit guess it was .mp4 so that it kept down size.
Has anybody downloaded the 4K version and found the colour to be okay. The HD version is fine. 

Operating System Version:
MacOS 10.14.6

Popcorn Time Version:
0.4.4
Download date:
April 2020

Expected Behaviour
play Mandalorian in 4K better resolution with colour cast

Many thanks Adrian

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS ([YIFY Torrents](https://yts.mx/)) or similar torrent agents (series comes from a different site).
They have no control over what's added and not.
If your able to find your own torrent(s), from any torrent site, you can add them to your PCT dragging them into "Torrent Collection" tab. This will then only for you local to watch, it wont be added to PCT in general.

**Comment by 123Olairy** [comment]
Apologies
Understand
Thank you

**Comment by dutchy1001** [comment]
Please use the close button for this issue
