### ISSUE TITLE
Closedown in Windows 10 not working

### ISSUE THREAD

**Issue by geoffrey5239** [popcorntime/popcorntime#1851]
On my Windows 10 computer I can only close Popcorn Time by going to Task Manager,  The X does nothing.

**Comment by dutchy1001** [comment]
Again you didnt't fill the requested fields in the issue form, read the pinned topic on top

**Comment by kiriles90** [comment]
Duplicate of #1280

**Comment by Persei08** [comment]
This is already fixed in latest dev builds.
