### ISSUE TITLE
New project for next release version?

### ISSUE THREAD

**Issue by pcenta** [popcorntime/popcorntime#1854]
I think that since a lot has changed (mainly fixes) since last release (0.4.4.) there should be a project that contains prioritized issues required to release new version (fixes of app breaking issues). So we can focus more on those and then release new version to other people than github users.

My 2 cents about game breaking issues or those that are need attention are #1579, #1457.
Maybe #1720 but since this is apparently old this can slip through as nothing will change?
Dependency updates to address additional security issues reported by Github?
Bump to latest nwjs (bringing latest Chromium features, fixes and maybe a new bug or two)?.

**Comment by kiriles90** [comment]
I think we can already release a new version. It would be a lot better than 0.4.4 either way. Ofc if we had 1579, 1457, 1720 (tbh I dont think these 3 are app breaking) and the other 11 ones tagged as bugs fixed too it would be better but some of those arent so straightforward. As for bumbing deps and nwjs.. personally I'm a little weary of that when its done for no reason. Half if not more of the mess we were in with v0.4.0+ was caused by that. But if something is tested 100% and doesnt break 20 obscure things that it will take us 6 more months to track down.. I'm all for it, bumb it.

**Comment by pcenta** [comment]
I think at least #1579 should be somehow addressed. At least with some warning for users to backup their data.

**Comment by dutchy1001** [comment]
#1579 is more an user error then a PCT error.
If you want to change the install directory then you should always give it it's own folder, installing this in a "general folder" with many other files/programs in it is asking for trouble.

As said in that post:
When changing the "cache" directory in the settings to E.G. my F: drive it automatic adds **F:\Popcorn-Time** adding "\Popcorn-Time" to the location, it would be good if that happens whenever you change the install directory to add "\Popcorn-Time" no matter were they put it.

#1457 As so many changes have been committed sinse then it's hard to catch up with this, maybe start afresh from version 0.4.5.

**Comment by pcenta** [comment]
Yeah I meant more that all user data will be deleted (bookmarks, watched movies...).

**Comment by Persei08** [comment]
We can also set `milestone` tags and use filters on the existing project board, no ?

**Comment by kiriles90** [comment]
@pcenta According to [/dist/windows/installer_makensis.nsi](https://github.com/popcorn-official/popcorn-desktop/blob/development/dist/windows/installer_makensis.nsi#L364) they should be copied to a temp dir before the install dir gets cleared, then moved back to the install dir. Not sure whats going on and they dont but will try to investigated further. If anyone else wants to do the same, even better.

**Comment by pcenta** [comment]
I think so yes. So on L367 we need to copy actual user DB to temp location and then adjust L374 and L376 to correctly copy data back.

Then #1712 can remain open for a bit? Although maybe it's a quick fix with one conditon?

**Comment by kiriles90** [comment]
Yeah seems it was this and went unnoticed all this time. It works too, the installer already does what it thinks its supposed to do.. (just backs up `\data` and `\TorrentCollection` instead of `\User Data` and `\TorrentCollection`...)

**Comment by kiriles90** [comment]
@pcenta Ok, so I've added a `0.4.5` milestone so we can additionally tag critical issues that need to be fixed before next release.  
@everyone can tag someone who can set them if they want and ask

Closing this to keep things tidy but we can keep the conversation going about 0.4.5 or just open a different issue if needed.

**Comment by Persei08** [comment]
I will look at PR #1858
