### ISSUE TITLE
Stuck on the loading page - Last build (#119)

### ISSUE THREAD

**Issue by Camis** [popcorntime/popcorntime#186]
Operating System Version: Windows 10 x64

Popcorn Time Version: 0.3.9 Last build (#119)

Download date: June 16 2016

Actual Behaviour

The program is stuck on the loading page.

**Comment by VitorVRS** [comment]
Actually this build is erroneous due to some dependencies (thisissue: https://github.com/popcorn-official/popcorn-desktop/issues/184).
@team-pct should verify CI and remove the build 119.

**Comment by IOAyman** [comment]
Same problem here! Using a clone of the master branch.

Popcorn ver: 0.3.9
OS: Fedora 23

**Comment by fedorzh** [comment]
Stuck too. After "Status:Done".
Tried build 121, same
Build 116 works
