### ISSUE TITLE
Trakt TV syncing issue causes app to close.

### ISSUE THREAD

**Issue by Aky96** [popcorntime/popcorntime#1863]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4 build version 443

Download date:
26/11/20

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

#### Expected Behaviour
Connect Trakt TV account and app to respond as normal.
...

#### Actual Behaviour
On initial connection of Trakt account the app will close/crash. After restarting the app and trying to sync Trakt again the app will keep crashing. (This has been happening for me since updating to 0.4.4) 

Edit: Also I'm not sure if any syncing takes place as anything I've marked as watched in the app has been cleared when I restart the app. 
...

#### Steps to reproduce the behaviour

1. Connect Trakt TV account.
2. In settings 'Sync' Trakt account.
3. App will close/crash with no input from user.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
The developer console closes when the app closes/crashes and I'm just left with a chrome 'Aw shucks' webpage instead.

**Comment by Persei08** [comment]
you should be able to access the developer console web interface by opening a browser tab on http://127.0.0.1:9222 and it will stay displayed even after the crash

**Comment by Aky96** [comment]
Thanks for the help and info. I've attached one screenshot from when I put the code into the Trakt website to connect my account and the second screenshot is when I click 'Sync with Trakt' from within the app. 

![PCT Console (Trakt)](https://user-images.githubusercontent.com/65768313/100454371-ab3bc680-30b4-11eb-8b7b-472610c9511a.png)
![PCT Console (App)](https://user-images.githubusercontent.com/65768313/100454382-b0007a80-30b4-11eb-9246-d07ebcbd2a6c.png)

**Comment by kiriles90** [comment]
Weird I cant replicate. Have you tried with a clean install and not importing any saved databases?

**Comment by Aky96** [comment]
The previous screenshots show what happened to the app when initially connecting my account through the Trakt website and after restarting then using the 'Sync with Trakt' option in settings.

This build wasn't clean installed, as you've now fixed the installer issue :), but I've clean installed many times previously and always have the same issue with Trakt TV.

Below is the screenshot of the errors showing on the console.

![PCT Console](https://user-images.githubusercontent.com/65768313/100459860-1047ea00-30be-11eb-9c79-da9d0b32eed7.png)

**Comment by kiriles90** [comment]
I see. Then if it also happens with a clean install its probably something that gets synced from the specific traktv account that Popcorn Time doesnt like and crashes. If you want try syncing a different profile just to confirm the theory. But I guess either way its something that should be addressed on Popcorn Time's side. Maybe @Persei08 has some ideas?

**Comment by Persei08** [comment]
@Aky96 can you retry and enable "all" debug levels (in the console tab.. on the right of the filter field)... It will eventually show some interesting things.
Also you can close this "Debugging connection was closed" popup by clicking its cross, so it allow you to select text or what.

for 3rd screenshot the error is related to chromecast-api, it isn't important here.

**Comment by Aky96** [comment]
@Persei08 @kiriles90 I've tried a clean install 5 times with 5 different Trakt profiles. 4 of them had the same issue straight away but the last one was working until I closed/restarted the app then it crashed as soon as 'Sync with Trakt' was selected. The app now crashes everytime 'Sync with Trakt' is selected however it does seem to remember the movies I've got 'marked as seen' but clears all the series I've had 'marked as seen'.

I've also added a screenshot with 'All' debug levels set.

![PCT](https://user-images.githubusercontent.com/65768313/100477293-cff96380-30df-11eb-9901-4c9505675d56.png)

**Comment by Aky96** [comment]
I've also added this screenshot from the inspectable page titled 'generated background page'.

Edit: Sorry for all the comments just trying to pass on the information. Don't know if this helps but with my Trakt account connected when I click on the Watchlist tab the app also crashes/closes. With the account disconnected the app stays open showing 'No Watchlist found...'

![PCT](https://user-images.githubusercontent.com/65768313/100480640-bf4deb00-30e9-11eb-86f7-cbc306a08ed6.png)

**Comment by Persei08** [comment]
Works for me too. Here this is what what you're supposed to get in console :/ :

![Screenshot_2020-11-27_23-46-34](https://user-images.githubusercontent.com/22459458/100487807-d6e99b80-310a-11eb-8341-9c9c858bec8e.png)

**Comment by dutchy1001** [comment]
Not sure if helps but I get these errors in console

![Untitled](https://user-images.githubusercontent.com/5569980/100489319-773fc000-310b-11eb-8f65-0c2e04d3e78b.png)

**Comment by Persei08** [comment]
@dutchy1001 Not sure, maybe try to disconnect and reconnect to trakt... Maybe there is a issue with trakt api/server

**Comment by dutchy1001** [comment]
After reconnect there was no error

**Comment by Aky96** [comment]
I'm determined to get to the bottom of this!!

I've now fully uninstalled the app, removed all traces of PCT in the registry, restarted my laptop, created a new Trakt account, clean installed the app, applied my preferred settings and connected my Trakt account. I've then gone adding individual movies/series and syncing after each addition. Everything worked perfectly until I tried to add 'The Undoing S01E05' and then the app crashed/closed (see screenshot). I've tried numerous times marking that episode as unseen/app works and seen/app crashes/closes. I've also added more individual episodes/series after restarting the app (leaving the suspect episode marked as unseen) and it worked as expected. As soon as you add this epsisode as seen again the app will crash. This has got me baffled!

Edit: Still trying random series to see if anything else will recreate this issue. I marked all of the seasons of 'This Is Us' as seen and this causes the app to crash/close. I then tried individual episodes from random seasons (S01E01/02, S02E02, S03E02, S05E01) and these all caused the app to crash/close each time. One thing different this time was that this cleared all of the previous 'marked as seen' from the app and each time I clicked 'Sync With Trakt' the app would crash/close and the only way to get the app working correctly again was to remove any reference to 'This Is Us' from my Trakt account. This issue appears to be very random.  

![PCT2](https://user-images.githubusercontent.com/65768313/100499148-2659b700-315f-11eb-95ab-482a512a479a.png)

**Comment by kiriles90** [comment]
Nice! I'll try to reproduce it with that episode later, gives us something to start tracking this down so at least it doesnt crash PCT when this (whatever this is) happens.

**Comment by Persei08** [comment]
Can't reproduce. 

i can mark/unmark as seen Undoing S01E05 without issue and can sync before, between , after... something weird here.

**Comment by Aky96** [comment]
I've tried PCT with my Trakt account on another laptop & a desktop over the last couple of days and the app worked as expected with no errors at all. I now have a sneaking feeling that the issue is with my ageing laptop (10 y/o Compaq!) somehow especially as no one can recreate this issue or has added a comment to say they have the same issue. Thanks for all your help but I'll close this now as I believe this is just a one-off problem.
