### ISSUE TITLE
Build 443 "marked as seen" data is gone

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1866]
Operating System Version:
Windows 10 build 2004

Popcorn Time Version:
dev build 443

Download date:
today (27-11-2020)

#### Expected Behaviour
After updating all settings, favourites and watched movie/series marked as seen (#1858)

#### Actual Behaviour
it takes the settings and favourites but doesn't add the "marked as seen" movies/series

#### Steps to reproduce the behaviour

1. download dev build 443
2. install
3. open PCT to see all "marked as seen" are gone

**Comment by kiriles90** [comment]
Hmm cant reproduce. Can you try mark some more items then reinstall 443 on top?

**Comment by dutchy1001** [comment]
Can't reproduce it either now. 
I did re-connect track.tv yesterday and solved some errors what was showing in console. Maybe it was linked 

( PS:
see #1863 the last 3 errors still come up when force sync with track.tv )

Closing for now unless someone else can reproduce it.

**Comment by kiriles90** [comment]
Yeah saw them. Trakttv integration and the watchlist are a bit of a mess to be honest. None has had a chance to have a look at them for a long time afaik. Its something that should be checked at some point.

**Comment by dutchy1001** [comment]
After opening today PCT again all "watched" movies/series have been reset. Opened it a few times to see if it was a glitch not reading the "watched db" but with no success.
Manual checking the "watched db" and the file is empty. (I have a backup, Pheww)
All my series in the favourite are present but it has cleared the "seen" icon, this is also the case in the movie tab.
![Untitled](https://user-images.githubusercontent.com/5569980/100521484-d0573480-319b-11eb-83f2-bf610bcdd11b.png)
1 Example from the favourite folder that I 100% have watched.

**Comment by kiriles90** [comment]
So its not the installer whatever it is. I suspect trakttv to be honest but havent looked at it more because I wasnt able to reproduce it.

**Comment by dutchy1001** [comment]
Looks like it need some time before it "clears" the "watched" db. 
I will leave PCT till tomorrow and see if it deletes it again then.
I will do the same again then with Track.tv disabled

**Comment by dutchy1001** [comment]
Not sure why this happened 2 times now but can't reproduce it again. I did made a new backup and compared them.
Differance can be seen here:
https://www.diffchecker.com/TRqKuLU4

Deleted lines on left side are added to the bottom of the right side.
Left is from before build 442, right side is made with build 443 (strait after install)

**Comment by dutchy1001** [comment]
Updated to build 444 with no loss of "seen" movie's or series. 

closing this now. If issue occurs again we'll see to reopen or make a new post.

**Comment by kiriles90** [comment]
:+1:
Get 445 btw, 444 is [a bit broken](https://github.com/popcorn-official/popcorn-desktop/pull/1884).

**Comment by ppo** [comment]
I had the same problem several time with different versions (on Mac) over the last months.  
Had it again today.

PS: Can I see the build version somewhere?

**Comment by dutchy1001** [comment]
To find the build number is indeed a bit confusing.

Open PCT and click on the info tab, the _**i**_ right top corner
![info 1](https://user-images.githubusercontent.com/5569980/103381699-73290880-4ae4-11eb-8d76-be907d0ce999.png)
When on this page you can see on the right bottom corner:
0.4.4 "Love in the Time of Corona" Beta - HEAD (xxxxxxx)
![info](https://user-images.githubusercontent.com/5569980/103381798-bbe0c180-4ae4-11eb-976b-912eed44573b.png)
The xx will be the same first  8 digits on the download page were it says **Revision:**.
![info 2](https://user-images.githubusercontent.com/5569980/103381866-f5b1c800-4ae4-11eb-913f-3168c7f96dc1.png)
This is the only way to verify what (dev)build your using

**Comment by ppo** [comment]
Thanks @dutchy1001 but I don't have the `- HEAD (…)` part (I just installed the build 450, osx64).

<img width="310" alt="Screen Shot 2020-12-30 at 22 32 22" src="https://user-images.githubusercontent.com/117100/103382363-12eb9400-4aef-11eb-8703-3962416e03ae.png">

**Comment by dutchy1001** [comment]
I use a windows 10 pc, not sure it should be any different on a mac
