### ISSUE TITLE
Looking for contributors for Electron fork

### ISSUE THREAD

**Issue by amilajack** [popcorntime/popcorntime#187]
I am working on a new version of the popcorn-desktop client with the goal of it being merged into this repository.

I am working on an implementation from scratch, featuring **ES6, React, Webpack, Electron**, and other new technologies:

[https://github.com/amilajack/popcorn-desktop-experimental](https://github.com/amilajack/popcorn-desktop-experimental)

It also has significant performance improvements over all the current clients. However, the project is very early stage and needs work!

Let me know if you are interested in contributing!

**Comment by VitorVRS** [comment]
Just for you know that we have an strong dependency on NW, which is compiled PCT team.
PCT NW are compiled with anothers video codecs (something like that).
Maybe you should know this.

**Comment by amilajack** [comment]
My experimental version doesn't have a heavy dependency on electron. We'll probably figure out a way to provide support for both electron and NW.

**Comment by MrRory** [comment]
thats not what the problem is really, the codecs are compiled into the nwjs version we use. AVI, H264, H265, AC3, OGG etc. need all to be supported and electron nor nwjs have support for all codecs in the world (which we want to have). Another solution would be using something like https://github.com/RSATom/WebChimera.js though

**Comment by amilajack** [comment]
@cannnon Sorry for late response. How do butter-desktop and popcorn-desktop handle these formats?

**Comment by amilajack** [comment]
@cannnon Sorry for late response. I've tried

**Comment by MrRory** [comment]
the codecs are compiled into the nwjs version we use, its a special build
