### ISSUE TITLE
Issue with Automatic Update

### ISSUE THREAD

**Issue by pol505050** [popcorntime/popcorntime#1875]
Operating System Version:
 I have Windows 10

Popcorn Time Version:
 0.4.4 "Love in the Time of Corona" Beta

Download date:
 2 weeks

Download url (optional):

#### Expected Behaviour
 Saved Setting

#### Actual Behaviour
 The settings are not saved when the program is updated (I think it happens after updating because after 2 or 3 days after configuring the app, it returns to its initial default state) The settings such as Opensubtitles acount, language preference, etc. are not saved .

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Did you download from the main Popcorn time website or did you get a dev build?

**Comment by kiriles90** [comment]
What did 0.4.4 automatically update to? There is no newer release version to trigger the automatic update.
