### ISSUE TITLE
Incorrect search

### ISSUE THREAD

**Issue by rohinarora** [popcorntime/popcorntime#188]
Operating System Version:
Ubuntu 14.04

Download date:
a week ago

For some particular search query, the results don't show

For eg- the tv series better call saul

When i search "better" no result comes up. However when i search "saul" the correct tv show comes up. I find this behavior strange

**Comment by 03eltond** [comment]
Also noticing strange search behavior - when I search "silicon valley" I don't get the show, but searching only "silicon" gives a match.  Same with "south park".  I may try and work on this myself sometime after the holiday.

**Comment by rohinarora** [comment]
@03eltond even I faced that

**Comment by ChrisAlderson** [comment]
It's an issue with the popcorn-api that should be fixed with [fa662b4](https://github.com/popcorn-official/popcorn-api/commit/fa662b450b84a4fc5e776abc67eb1ab072fcbf23).

**Comment by ChrisAlderson** [comment]
A version of the popcorn-api which fixes this issue should be in production atm so I'm closing this issue.
