### ISSUE TITLE
x265 torrents

### ISSUE THREAD

**Issue by rohinarora** [popcorntime/popcorntime#190]
Why aren't the torrents used hevc x265? I can see that not all movies/series would have x265 available, but for most of them it available is nowadays. And they take a lot less bandwidth, same quality

**Comment by ChrisAlderson** [comment]
The reason why (I think) is because the HEVC codec is pretty new and some devices/players will not support this codec. For instance the [chromecast](https://developers.google.com/cast/docs/media) does not support the codec.

**Comment by rohinarora** [comment]
Cool. I have used it successfully with VLC in windows. 
In Ubuntu VLC, it works fine, but i have faced some issues. For eg- when i fast forward a video, the audio is often lost. I need to randomly change timestamp to restore the audio. Don't know if this is specific to me. Especially the 10 bit format stucks the most. (not so in windows)
