### ISSUE TITLE
App keeps updating itself

### ISSUE THREAD

**Issue by zephyrdaz** [popcorntime/popcorntime#1904]
Operating System Version:
Windows 10 - Multiple updates from MS since this started.

Popcorn Time Version:
0.3.10 -  this has been happening for about a year.

Download date:
I don't know

Download url (optional):
N/A

#### Expected Behaviour
When I unselect "Activate automatic updating" it should stay unselected and doesn't update itself without my knowledge or permission.
...

#### Actual Behaviour
When I unselect "Activate automatic updating" at some point, it enables "Activate automatic updating" and updates itself without my knowledge or permission.
...

#### Steps to reproduce the behaviour

1. Unselect "Activate automatic updating"
2. wait until you release a new beta
3. see a terms and conditions popup and enjoy a new version you didn't expect.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
Not something a screenshot will help with.

**Comment by dutchy1001** [comment]
I don't think that can be fixed unless you update to the latest **[dev build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

**Comment by kiriles90** [comment]
Like @dutchy1001 said you are using a 5 year old version which can not magically fix itself one morning. Update to the latest dev build from ci.popcorntime.app
