### ISSUE TITLE
Movie tab sort by title stucks with no error in console

### ISSUE THREAD

**Issue by urbandroid** [popcorntime/popcorntime#1905]
Operating System Version:

ubuntu xenial
Popcorn Time Version:

build 446
Download date:

 2020 december 10
Download url (optional):

#### Expected Behaviour

sort movies by title 
#### Actual Behaviour

infinite loading screen

#### Steps to reproduce the behaviour

1. open movies tab 
2. click sort by title

**Comment by kiriles90** [comment]
@urbandroid fixed with #1907, thank you for reporting the issue :+1:
