### ISSUE TITLE
sort by Last added doesn't work as intended 

### ISSUE THREAD

**Issue by urbandroid** [popcorntime/popcorntime#1906]
Operating System Version:

Popcorn Time Version:

build 446
Download date:

2020 december 10
Download url (optional):

https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastSuccessfulBuild/
#### Expected Behaviour

...
Sort movies with date of them added to index. 
#### Actual Behaviour

...
it sorts movies by release year. which is same with sort by year function. (There should be a ledger which keeps track of when they added to popcorn index,  ) 

#### Steps to reproduce the behaviour

1. Open movies tab
2. click sort by Last added 2 times
3. realize it sorts by release date not by added date.

**Comment by dutchy1001** [comment]
basically a duplicate from #1905

**Comment by kiriles90** [comment]
This is how the API delivers this data. If you check YTS's API and you go by last added it does exactly what you said but as a result you get movies from 1940 in last added. Popcorn Time's API works differently on this and returns 'last added' based on the metadata it gets from trakttv.  

Closing this because it has nothing to do with the app but you can open an issue in the API repo if you'd like this API behavior to be reconsidered.

**Comment by urbandroid** [comment]
> basically a duplicate from #1905

wanna read it before tagging duplicate next time?



> This is how the API delivers this data. If you check YTS's API and you go by last added it does exactly what you said but as a result you get movies from 1940 in last added. Popcorn Time's API works differently on this and returns 'last added' based on the metadata it gets from trakttv.
> 
> Closing this because it has nothing to do with the app but you can open an issue in the API repo if you think this API behavior should be reconsidered.

@kiriles90 just run these two queries 
https://yts.mx/api/v2/list_movies.json?sort_by=year&limit=15
https://yts.mx/api/v2/list_movies.json?sort_by=date_added&limit=15

As you can see they give different results and second one returns with date_added. 5 element was a movie from 2008 so it return with date added.

**Comment by urbandroid** [comment]
> Who said they return the same results? But this doesnt change the fact that 'date added' in YTS returns movies from 1940 or that it has nothing to do with the app and its how Popcorn Time's API works.

I implied it with original report. With Popcorn desktop sorting by Last added or Year gives same result except for some data which doesn't have year attribute for some reason.  

yts index working as it should, while popcorn uses year query results for both sorting with last added and year. 

can you kindly give me a link to source where results unmarshalled or queried?

**Comment by kiriles90** [comment]
Its at https://github.com/popcorn-official/popcorn-api

**Comment by kiriles90** [comment]
@urbandroid Build 450 is out at ci.popcorntime.app. Includes #1939 so you can set `https://yts.mx/` as a custom movies server where their 'last added' works the way you wanted and also #1932 so you can set any filters you want as the default ones.

Should help a bit towards what you were looking for?

**Comment by dutchy1001** [comment]
Adding a new "Custom Movie Server" (https://yts.mx/) does not save for me inn that field (using build 450).

**Comment by kiriles90** [comment]
Sometimes right click>paste is bugged. Use ctrl+v or just write in it then click out of the text box.

**Comment by dutchy1001** [comment]
after typing it in it did work

**Comment by kiriles90** [comment]
@dutchy1001 #1943 fixed

**Comment by urbandroid** [comment]
great job, thanks.

**Comment by urbandroid** [comment]
I know it is not a place to ask but you guys know a decent custom series server?
