### ISSUE TITLE
Allow Audio Language Preference/Audio Change Option

### ISSUE THREAD

**Issue by nandhudroid** [popcorntime/popcorntime#1915]
Hi,

First of thanks alot for a such a wonderful App. Great work, much appreciate all your efforts. Keep it up please.

I have found Queen's Gambit series available for streaming. However, when I start streaming, the audio language was defaulted to French. Upon checking the Downloads tab, I could see the 1080p torrent is French however it has Multi Audio Option as per the torrent name.  Though the 720p option torrent is default in English, it's not pleasant to watch 720p in Big screen monitor. 

It would be very great if there is option to Select Audio stream in Multi audio stream torrents / set English as default Audio streaming Language preference for all torrents.

Thanks in Advance
![Screenshot 2020-12-20 013404](https://user-images.githubusercontent.com/63871350/102698476-9d1c3880-4263-11eb-814d-ef0aac67cf9a.png)
.

**Comment by dutchy1001** [comment]
It's how that torrent is uploaded with French as default. Popcorn Time is not responsible for what is uploaded to the torrent sites.

Saying that,
if you use an external player to watch movies/series then you often have more options from that player. I use [SMPlayer](https://www.smplayer.info/)  and could choose from about 8 different languages. In this case (The Queens Gambit) I was able to change it back to English. Also remember this serie does start off in French, also for the English version.

**Comment by kiriles90** [comment]
What @dutchy1001 said and also that last time I checked html5 video and videojs have issues with multiple audio tracks. Unless you encode them in a specific 'web friendly' format (which obviously cant be the solution in this case, those are torrent files and not under Popcorn Time's control) the current implementations for everything else are far from perfect. Causing desyncing of audio/video, need to restart the stream, etc etc. I guess its the reason why none has tried to add this feature so far.

That being said, moving this to 'Verifying' to be rechecked because if it somehow gets implemented it will be a nice feature to have.

**Comment by nandhudroid** [comment]
I totally agree with your point. Popcorn Time cannot do anything about default Audio stream implementation in torrents. It's beyond the scope.

May be I'll rephrase my request this way, 

I personally use KMPlayer which has this feature to select Audio stream in Multi Audio encoded videos.  It would be awesome if it's possible to add this feature to select audio streams in Popcorn Time's internal media player itself; like how the external players offers it. 

I would understand if it's technically not possible to implement this for instant streaming video players like Popcorn Time . I would rather happily settle for an option to choose any other the external player installed in my system for playback. I know for fact that the Android version of Popcorn Time offers such auto detection of external media players and allows to chose one from it for playback. I know PC version is still in beta, that's why I even decided to put in this request.

@dutchy1001, Just curios since you mentioned the use of external players. Does Popcorn Time PC version already have any option to stream the videos from it's platform on to external players ? I couldn't find any options in the menu; 
I'm sure the video is stored somewhere in my HDD and I could also see the folder icon in Dowloads section. But unfortunately clicking on the Icon or on the name of the video doesn't do anything.  It doesn't opens the video or the folder. 

![Screenshot 2020-12-20 160450](https://user-images.githubusercontent.com/63871350/102711172-ba8de880-42dd-11eb-801d-9099d3ff5a3b.jpg)

I guess if I could open the directory in explorer, I could directly play it on any external player like any other video.  It would be a nice workaround; but then it becomes more like downloading torrent using any other torrent app and watching offline. It breaks away from the experience Popcorn Time tries to offer.  So, I still believe the option to at least choose the external player and launch the stream directly from Popcorn Time platform on to external player like Android implementation is close to the original idea of Popcorn Time.

But hey, I'm new to this, I could be totally naive here.

**Comment by dutchy1001** [comment]
> Does Popcorn Time PC version already have any option to stream the videos from it's platform on to external players ?

![externalplayer](https://user-images.githubusercontent.com/5569980/102711978-98807000-42b5-11eb-9531-37fcb513e620.png)

When on the movie or series page you will see the little arrow on the "Watch Now". If you click there you will have the option to play through an external player. 
You only have to do this ones as it remembers it after for any movie or serie until you change it again (Not sure if KMPlayer is on this list, SMPlayer is).

>I'm sure the video is stored somewhere in my HDD

As for opening the folder were all the movies and series are stored you have to open your (hidden) "AppData/Local/Temp/Popcorn Time" folder.
An easier way (I think) is to change the location were PCT stores the temporally files so you have easy access to them (untick "Clear Tmp Folder after closing app?" to keep movies/series but remember to delete them yourself or your hdd will get full)

![location](https://user-images.githubusercontent.com/5569980/102712152-af739200-42b6-11eb-966f-f46403eeef66.png)
(you have to tick show the advance settings on top of the settings page)

> It doesn't opens the video or the folder.

![](https://user-images.githubusercontent.com/63871350/102711172-ba8de880-42dd-11eb-801d-9099d3ff5a3b.jpg)

As far I know clicking on the folder icon should open the location of were the file is stored, this could be a bug that needs attention.

**Comment by nandhudroid** [comment]
Thanks @dutchy1001 for the quick response. Your answers are really helpful; I did found the downloaded video "..\AppData\Local\Temp\Popcorn-Time" directory. Thanks alot. 

Good to note that support for external players are already implemented. Unfortunately, I don't see any other external players in the dropdown list; I'm just seeing Popcorn Time option only.

![Screenshot 2020-12-20 174129](https://user-images.githubusercontent.com/63871350/102713045-35a9cb80-42eb-11eb-9a4c-3d02fdcce2f4.png)

And a correction, I actually have Pot player installed in my PC, got it confused with KMPlayer, but still it's not showing up in the "Watch Now" dropdown list. 

![Screenshot 2020-12-20 175104](https://user-images.githubusercontent.com/63871350/102713164-17909b00-42ec-11eb-9e9e-6e0993dae480.jpg)

Could it be also a bug or is it limited support for few selective external players ?
Should I try installing SMPlayer and see if it shows up ?

Thanks again for the help!

**Comment by Persei08** [comment]
@nandhudroid PCT cannot detect all players just like that. It use a list of defined players and on launch, search if they are installed in usual programs folder.

See this file https://github.com/popcorn-official/popcorn-desktop/blob/25691da285ae45f5c3205048b0545efa4579f841/src/app/lib/device/ext-player.js#L7-L107 for the list of supported players

**Comment by dutchy1001** [comment]
@nandhudroid
 I can recommend [SMPlayer](https://www.smplayer.info/) as I have used it for years, an other good external player is the well known  [VLC player](https://www.videolan.org/vlc/index.en-GB.html).

**Comment by kiriles90** [comment]
@nandhudroid Cant believe all of us forgot to mention this but if you havent already, update to the latest dev build from ci.popcorntime.app (build 447 at the moment). It has nothing to do with this issue but solves a great number of other.  

@Persei08 we should really put that list somewhere where people can find it but without spamming the UI (which poses the question.. where?:)

**Comment by dutchy1001** [comment]
latest dev build can be found **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by nandhudroid** [comment]
I've downloaded and installed latest dev build (447) from the link shared. Like you said I notice one other bug (filter option in Favorites Tabs) is fixed and also see some changes in settings, Big picture mode is gone, instead custom UI scaling is added. Hope the close button issue (not able to close app after a while) also resolved in this.

Back to my original request, 
Thanks to @Persei08, I could see that PotPlayer is not available in supported external players list at the moment. Hope it'll be added in future release. It's really a good player, forked from KMPlayer. Simple UI and loads of features under the hood. If you could please include support for it would be great.

This may sound dumb, just wondering if you can provide the Key/Value data for PotPlayer that I could add in the ext-player.js file in my Install folder; would it work ?  I've had some experience with JS and JSON long back, so can edit that file without breaking it. It's alright if it's not as simple as just adding an entry under the player variable there. I get it.

For now, I'll go with SMPlayer or VLC as suggested by @dutchy1001. Thanks all for the great response and support. Definitely one of the responsive and active dev community I've seen. I'll continue to use PCT and try to post here any bugs/new feature requests I come across. 

Keep up the great work.!! Thanks again!

**Comment by kiriles90** [comment]
@nandhudroid You can add external players by editing /src/app/lib/device/ext-player.js but I have no idea about PotPlayer and if it has any issues or if it needs some special command line switches or treatment. I'll comment below if I find out more.

**Comment by nandhudroid** [comment]
Thanks alot

**Comment by kiriles90** [comment]
@nandhudroid https://github.com/popcorn-official/popcorn-desktop/pull/1923 merged.

From next build Popcorn Time will have PotPlayer support (build 448, probably a week or so)
Or just manually edit in the PR above to build 447 if you are up for a little manual edit.

**Comment by kiriles90** [comment]
So, after rechecking the multiple audio tracks in the native player issue, the situation hasnt changed. Multiple issues still exist towards implementing this. Closing for now though I guess it should/will be revised at some point and hopefully by then something has changed.

**Comment by nandhudroid** [comment]
> @nandhudroid #1923 merged.
> Or just manually edit in the PR above to build 447 if you are up for a little manual edit.

Update:
I manually copied the updated files from PR and now able to view Potplayer in the dropdown and video streaming perfectly fine in Potplayer. 👍 

![Screenshot 2020-12-22 162129](https://user-images.githubusercontent.com/63871350/102880707-c5798200-4471-11eb-93da-e94fae9d857d.jpg)

Now I could select the eng audio from the same video stream. :)

Thanks alot!
