### ISSUE TITLE
OS Windows 10, running the latest version of the app (I think). Problem is, I was watching P.S. I love you and it shuts down at 1:46 and a few seconds. I actually remember it happening once before at the exact same moment, and I had to watch the end at another server. By that time it was an older version of the app and I was on Windows 8, so it's probably just a problem with the movie, but please please fix it! I absolutely love it and would love to watch it multiple times using popcorn time. Thank you!

### ISSUE THREAD

**Issue by cbfnks** [popcorntime/popcorntime#192]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...
#### Actual Behaviour

...
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Breaking1** [comment]
What version of popcorntime are you using?

> and I had to watch the end at another server.

This makes me believe you are using time4popcorn and not the version supported here from popcorntime.sh

It works perfectly fine in my version as you can see here:

http://imgur.com/DJZwH9S

**Comment by cbfnks** [comment]
Version 2.7.5.3 of popcorn time. What I meant by another server is I had to close popcorn time and google somewhere to watch the ending online... 

Obter o Outlook para Android

De: Breaking1

Enviado: quinta, 23 de junho 09:18

Assunto: Re: [popcorn-official/popcorn-desktop] OS Windows 10, running the latest version of the app (I think). Problem is, I was watching P.S. I love you and it shuts down at 1:46 and a few seconds. I actually remember it happening once before at the exact same moment, and I had to watch the end at another server. By that time it was an older version of the app and I was on Windows 8, so it's probably just a problem with the movie, but please please fix it! I absolutely love it and would love to watch it multiple times using popcorn time. Thank you! (#192)

Para: popcorn-official/popcorn-desktop

Cc: cbfnks, Author

What version of popcorntime are you using?

and I had to watch the end at another server.

This makes me believe you are using time4popcorn and not the version supported here from popcorntime.sh

**Comment by Breaking1** [comment]
Version 2.7.5.3 is indeed time4popcorns Android version, the version supported here is https://popcorntime.sh/

**Comment by cbfnks** [comment]
I'm sorry, I mixed things up. I was watching it at the PC when I had the issue, while I checked the version in my phone. The installed version in my PC, as stated on the bottom left corner of the information page (clicked on the i icon at the top left corner)  is 0.3.9-0 "there's nothing on TV" beta (1c51a7fa)

Obter o Outlook para Android

On Thu, Jun 23, 2016 at 11:27 AM -0300, "Breaking1" notifications@github.com wrote:

Version 2.7.5.3 is indeed time4popcorns Android version, the version supported here is https://popcorntime.sh/

---

**Comment by Breaking1** [comment]
Then you have the correct version installed on your computer, can you try to play the movie in an external player like VLC or MPC HC and see if it works then.

But it works fine in my version, i can play the hole movie without problems. But they don't have any control over the content, popcorntime just uses API's to fetch content from different sites so if it is a problem with the movie/torrent there's little they can do to solve it.

**Comment by adambh** [comment]
I confirm, it happens even with an external player.
