### ISSUE TITLE
Cannot download any build from Jenkins since yesterday

### ISSUE THREAD

**Issue by dacriso** [popcorntime/popcorntime#1921]
Hi.

First of all thanks for all your great work, much appreciate all your efforts.

Been trying to download build #447 (macOS build) since yesterday and I keep getting disconnected every single time after the first 15MB of the file. Same with both Safari and Google Chrome.

Hope this is the wright place to post this.

**Comment by dutchy1001** [comment]
My download failed as well and says "network error" (same for some linux files too), normal windows x32/x64 file downloads normal.

**Comment by dutchy1001** [comment]
Looks like a hit or miss with the downloads, this might be due to server maintenance or ISP hiccups. Few minutes later I did manage to download the Mac version.

**Comment by dacriso** [comment]
Still doesn't work for me. And I've tried many times. :D

**Comment by dutchy1001** [comment]
make sure you have the right link
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/

Just incase to make sure

**Comment by kiriles90** [comment]
Probably some server issues. For now just click the 'resume download' in chrome, eventually it will download it. 
This doesnt have much to do with the app though so closing but you can still keep the conversation going below if you want.
