### ISSUE TITLE
no new movies

### ISSUE THREAD

**Issue by bewakertje** [popcorntime/popcorntime#1935]
Hey,can anyone help me out here,please?

why does pct don't show's me new movies?
In lockdown I would like to watch movies,but there are no new ones for over than a month????
Please is there something that I can do or is it normal?
Thanks,I'm waiting for a answer.

**Comment by dutchy1001** [comment]
Please read issue #1690

**Comment by bewakertje** [comment]
I already did,but I don't understand what he did?

**Comment by dutchy1001** [comment]
To get some new movies watched through PCT you can add a torrent link yourself.
Depending on what build your using you should be able ta add a (torrent) links in the "torrent collection" tab  (3 dots and 3 stripes icon on the right top).
To get the latest dev build go **[HERE](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** (this will not fix the new movie issue).
To get torrent links you can go **[HERE](https://yts.mx/)** or use other torrent sites your familiar with.
