### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1936]
To all devs and users I would like to wish you all a MERRY CHRISTMAS and all the best for 2021. 

Lets hope for a better year then we had.

dutchy

**Comment by kiriles90** [comment]
Merry Christmas!

**Comment by Persei08** [comment]
Dear Santa,

please end all this covid chaos as fast as possible :D

Merry Xmas everyone :)

**Comment by ivan1986** [comment]
Merry Christmas!
And happy new year!
