### ISSUE TITLE
Search plugins importer

### ISSUE THREAD

**Issue by Maikhi** [popcorntime/popcorntime#1949]
The possibility to add servers for torrent search would ease the finding and viewing of movies in different languages.

A plugin importer as existing in Qbittorrent would do the job, maybe completed with a converter to enable PorcornTime to import directly the plugins available in github.com/qbittorrent/search-plugins.

**Comment by pcenta** [comment]
Qbittorrent is Python based as far as I know and that goes for its plugins. PCT is JS. Not sure if anything can be done to implement given plugins into existing codebase.

**Comment by kiriles90** [comment]
@Maikhi @pcenta That is my understanding too. There are ways to automatically convert python to javascript but most have some caveats, require human intervention or just arent suited for this specific implementation.
Leaving this issue open for now though in case someone who knows more on the subject or has some other (relevant) idea passes by.
