### ISSUE TITLE
#120 Initializing popcorn stuck

### ISSUE THREAD

**Issue by LaMpiR** [popcorntime/popcorntime#195]
Hi people. So I've had some version of 0.3.9 and my DLNA didn't work to my LG TV Webos 2.0, so I've decided to update to the latest one.
I choose the tv before, clicked the view but nothing on the tv happened, even though it started streaming to my tv according to popcorn. Latest version won't load.

![popcorn](https://cloud.githubusercontent.com/assets/851778/16348374/7375b204-3a52-11e6-8c98-f85ed40cfb3e.JPG)

Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9 build #120

Download date:
24.06.2016
#### Expected Behaviour

Load...
#### Actual Behaviour

Got stuck
...

**Comment by zen0x90** [comment]
Hi,

I got the same issue. I clone the github and then "npm start". Popcorn get stuck...So, I download the package at the following location : https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

But the issue remains the same.

Windows 10

**Comment by tr0yspradling** [comment]
I'm getting this issue on Antergos/Arch Linux 64 bit. Tried running with elevated privileges, no dice.
