### ISSUE TITLE
Homebrew instructions not valid

### ISSUE THREAD

**Issue by benjavalero** [popcorntime/popcorntime#1952]
It seems the instructions to install in macOS with Homebrew are not valid anymore because of changes of the last one.

I have found that the same can be achieved with:
```
brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time
```

Regards,

**Comment by kiriles90** [comment]
@benjavalero Thank you

Can someone confirm this?

**Comment by sandrosimas** [comment]
it worked for me the command mentioned by @benjavalero.

**Comment by kiriles90** [comment]
@sandrocsimas Thank you

**Comment by jacogasp** [comment]
Hello, I also confirm the instructions provided by @benjavalero work perfectly.
