### ISSUE TITLE
Rating Filter for movies for YTS provider

### ISSUE THREAD

**Issue by sativ01** [popcorntime/popcorntime#1953]
I am frustrated that I cannot skip movies with low rating in the list.

Since now there's a new provider for YTS api, which supports filtering by rating,
I would like to have an additional filter that allows me to filter based on movie rating

**Comment by kiriles90** [comment]
@sativ01 Didnt you have a PR ready for this? It doesnt need an issue just close this and make the PR anytime you want.

**Comment by sativ01** [comment]
@kiriles90 ok, I thought it's better to follow the common practice so that it's clear what's the feature

**Comment by kiriles90** [comment]
@sativ01 Yy, just add it in the PR's description.
