### ISSUE TITLE
superstore bug

### ISSUE THREAD

**Issue by danalevin** [popcorntime/popcorntime#1958]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.4.4

Download date:
 1.21.21 (install it a month ago but reinstalled it today because I thought it will solve it)

Download url (optional):

#### Expected Behaviour
 the app had to open the episodes of the show as usual when I pressed "watch now" 

#### Actual Behaviour
 nothing, the button doesn't react and even don't want to download the episodes of the entire show.  

#### Steps to reproduce the behaviour

1.  go to series
2.  search for a show called "superstore"
3. that's it, none of the episodes of this show open up or react to download

**Comment by dutchy1001** [comment]
Search works for me with that serie.
Not sure about your download date but if you downloaded/installed this last month then I suggest to redownload the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

If the issue still exists then report back or close this issue.

PS:
PCT is not responsible for the content, this comes from 3rd party torrent site(s), any missing or wrong info/movie or series is out of PCT's control.
