### ISSUE TITLE
Option to choose a custom subtitle for Chromecast

### ISSUE THREAD

**Issue by GuiChevis** [popcorntime/popcorntime#196]
**Operating System Version:**
Windows 10

**Popcorn Time Version:**
Popcorn-Time-0.3.9 - Build 116

**Download date:**
06/26/2016
#### Expected Behaviour

Let me choose a custom subtitle (.srt) when playing on Chromecast.
#### Actual Behaviour

I Can only choose custom subtitles when playing in Butter player or external players like VLC.
#### Steps to reproduce the behaviour

1.Open PopcornTime
2. Choose a Movie/Serie
3. Choose Chromecast
4. (Don't) Choose custom subtitles

**Comment by Breaking1** [comment]
Not so strange since this feature isn't implemented yet, hopefully it will be an option in the future.

**Comment by dan-dr** [comment]
workaround i found: https://www.reddit.com/r/PopCornTime/comments/4ruvxo/found_a_way_to_stream_to_chromecast_with_custom/

**Comment by ancho85** [comment]
Why this Issue was closed? I think that for most international users this feature is a must-have! Even knowing that in previous version it was available.

**Comment by Breaking1** [comment]
@ancho85 this feature has never been present in the version supported here.

**Comment by gabrielbc** [comment]
@ancho85 is right.. this is a big deal for international and hearing-impaired users

**Comment by ghost** [comment]
Huge +1 !

**Comment by aluzardo** [comment]
+1

**Comment by RaidForums** [comment]
+1 Please implement this.
It's been a year come on. Can someone link me a pull with this feature?

**Comment by kinduff** [comment]
+1 and bumping the issue

**Comment by Dulb26** [comment]
+1 Bump!

**Comment by charlesreitz** [comment]
+1 Bump!

**Comment by OrDuan** [comment]
+1 Bump!

**Comment by pedromoraesh** [comment]
+1 Bump!

**Comment by almeidamarcell** [comment]
+1

**Comment by juuuuuu** [comment]
+1

**Comment by Dpaz92** [comment]
+1
