### ISSUE TITLE
The settings to change directory of cache or database not work

### ISSUE THREAD

**Issue by Madnek** [popcorntime/popcorntime#1965]
Operating System Version:
 Windows 10

Popcorn Time Version:

Download date:
03/01/2021

Download url (optional):
release of github 0.4.4

#### Expected Behaviour
Change the cache directory
Change the DB directory

#### Actual Behaviour
Can't validatate the setting, there is no ok button

#### Steps to reproduce the behaviour
go to settings >advance >cache or db settings

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab)
![Capture](https://user-images.githubusercontent.com/76921466/103489582-e9e04180-4e15-11eb-9fc8-8c643c37bdbe.PNG)

**Comment by dutchy1001** [comment]
before we start, can you tell us were you downloaded from?
Is it the latest dev build or from the main website?

**Comment by kiriles90** [comment]
You cant change the database directory (from the settings anyway)
And for the cache directory you need to click on the text box, not the folder icon next to it.
