### ISSUE TITLE
Bind to network interface to make sure no connections if VPN not active

### ISSUE THREAD

**Issue by Madnek** [popcorntime/popcorntime#1968]
I pay an other VPN than the one provided by popcorn time, and with the actual settings  I have not the security that popcorn time is working only when my VPN is active

So my idea is to have option to bind popcorn time to a network interface, in this case popcorn time will work only if my private VPN is active. End I will not ave problem with the tracker of torrent

sorry for my grammar errors i'm not english.

**Comment by dutchy1001** [comment]
First off, PCT doesn't provide a VPN. This is a suggested VPN advertisement which can be disabled in the "advanced" settings.

I'm not sure your suggestion is viable as many users still do not have a VPN or do not know how a VPN works.
I would suggest to leave your private VPN on at all the times and only disconnect when needed (only some websites do not allow VPN's, e.g. banks and lotto to name a few). This way you never have to worry about torrents and trackers and you can watch what you like.

**Comment by Persei08** [comment]
If you use another VPN you should not give too much attention to VPN message saying your connection isn't secure because it will only say it's seure if you use the suggested VPN... but In fact you can use another VPn provider, and it will be "secure" too

**Comment by nsomaru** [comment]
You can bind an app to a network interface in [linux](https://unix.stackexchange.com/questions/210982/bind-unix-program-to-specific-network-interface) and [windows](https://www.raymond.cc/blog/bind-windows-application-to-specific-network-adapter-with-forcebindip/)

**Comment by adiso06** [comment]
^ Is there a clear way to bind an app to a network interface in macos
