### ISSUE TITLE
Watchlist and Favourites just keep loading.

### ISSUE THREAD

**Issue by weker0** [popcorntime/popcorntime#197]
Operating System Version:
Windows 10

Popcorn Time Version:
Recently downloaded so I assume the main 

Download date:
A week, max two weeks ago.
#### Expected Behaviour

Display my watch list or bookmarks once they had loaded
#### Actual Behaviour

For my bookmarks or watched films to be displayed
#### Steps to reproduce the behaviour

I cannot say, I just came on one day to have issue. It seems that flushing the system fixes it but I'm trying to find out how I can get my bookmarks back in a faster manner then just searching for them all again.

**Comment by VitorVRS** [comment]
Can you open dev tools (F12) and print console messages?
Are your Trakt.tv/TV ShowTime synced?

**Comment by Breaking1** [comment]
@weker0 just a little tip to how you can save your bookmarks so if they disappear for some reason you can just add the hole bookmark folder instead of having to search for them all, it will save you some time if shit like this happens.

When you have all your bookmarks go to settings and make sure the "show advanced settings" box is checked, then scroll down to database directory and press the folder behind it. There you will find your bookmarks/movies/shows/settings/watched folders so you can save them manually and just add them yourself if they disappear for some reason.

**Comment by weker0** [comment]
@VitorVRS How do I print the console messages exactly and as for Trakt.tv I don't use it, I've just been using the heart button to record what I want to watch.

@Breaking1 I was aware of this and recently tried to recall previous versions which seems to be the main cause of the error. For some reason the code for the file reads different when refreshed. Like right now at the end of the file it reads: 
{"$$indexCreated":{"fieldName":"imdb_id","unique":true,"sparse":false}}
If I flush the bookmarks and save a new one this appears at the start however of the bookmarks file.
 {"$$indexCreated":{"fieldName":"imdb_id","unique":true,"sparse":false}}

**Comment by VitorVRS** [comment]
@weker0 On PCT you can press F12 on your keyboard, it will open a new window with dev tools.
In this dev tools there is a tab named "Console", click on it.
In "Console" tab will show many logs and probably some "red" messages (errors), if there are erros you can print them and post here.
Will be better if you print whole log.

**Comment by weker0** [comment]
@VitorVRS Nothing came up red apart from /butter-settings-/ which I assume isn't an issue

database.js:6 Database path: C:\Users\User\AppData\Local\Popcorn-Time
app.js:11 [INFO] Scanning: Local Network for Airplay devices
app.js:11 [INFO] Scanning: Local Network for DLNA devices
app.js:11 [INFO] Scanning: C:\Program Files
app.js:11 [INFO] Scanning: C:\Program Files (x86)
app.js:11 [INFO] Scanning: C:\Users\User\AppData\Local\Apps\2.0
app.js:11 [INFO] Found External Player: SMPlayer in C:\Program Files (x86)\SMPlayer
app.js:11 [INFO] Found External Player: mplayer in C:\Program Files (x86)\SMPlayer\mplayer
app.js:11 [INFO] Found External Player: VLC in C:\Program Files (x86)\VideoLAN\VLC
app.js:11 [INFO] External Players: scan finished
bootstrap.js:61 loading npm /butter-settings-/ butter-settings-popcorntime.io
bootstrap.js:24 loading local provider cache_provider.js
bootstrap.js:24 loading local provider cache_providerv2.js
bootstrap.js:24 loading local provider favorites.js
bootstrap.js:24 loading local provider opensubtitles.js
bootstrap.js:24 loading local provider torrent_cache.js
bootstrap.js:24 loading local provider trakttv.js
bootstrap.js:24 loading local provider tvshowtime.js
bootstrap.js:24 loading local provider watchlist.js
bootstrap.js:24 loading local provider ysubs.js
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-yts
generic.js:27 added yts to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-tvapi
generic.js:27 added TVApi to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-haruhichan
generic.js:27 added haruhichan to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-vodo
generic.js:27 added vodo to provider registry
app.js:11 [INFO] Loading DB
bootstrap.js:35 loaded cache_provider.js
bootstrap.js:35 loaded cache_providerv2.js
generic.js:27 added Favorites to provider registry
bootstrap.js:35 loaded favorites.js
generic.js:27 added OpenSubtitles to provider registry
bootstrap.js:35 loaded opensubtitles.js
generic.js:27 added TorrentCache to provider registry
bootstrap.js:35 loaded torrent_cache.js
generic.js:27 added Trakttv to provider registry
bootstrap.js:35 loaded trakttv.js
generic.js:27 added TVShowTime to provider registry
bootstrap.js:35 loaded tvshowtime.js
generic.js:27 added Watchlist to provider registry
bootstrap.js:35 loaded watchlist.js
generic.js:27 added ysubs to provider registry
bootstrap.js:35 loaded ysubs.js
app.js:11 [INFO] Spawning new provider yts?&apiURL=https://movies.api-fetch.website/, Object
app.js:11 [INFO] Spawning new provider TVApi?&apiURL=https://tv.api-fetch.website/, Object
app.js:11 [INFO] Spawning new provider haruhichan Object
app.js:11 [INFO] Spawning new provider vodo Object
app.js:11 [INFO] Spawning new provider OpenSubtitles Object
app.js:11 [INFO] Spawning new provider Trakttv Object
app.js:11 [INFO] Spawning new provider TVShowTime Object
app.js:11 [INFO] Spawning new provider TorrentCache Object
app.js:11 [INFO] Spawning new provider ysubs Object
bootstrap.js:107 loaded Array[9]
app.js:11 [INFO] Initializing HTTP API server
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider TVShowTime
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://movies.api-fetch.website/,
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider OpenSubtitles
app.js:11 [INFO] Returning cached provider ysubs
generic_collection.js:146 pre--- YSubs undefined TraktTv Array[1]
generic_collection.js:21 pre all Array[3]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://movies.api-fetch.website/,
app.js:11 [INFO] Returning cached provider TVApi?&apiURL=https://tv.api-fetch.website/,
app.js:11 [INFO] Returning cached provider haruhichan
app.js:11 [INFO] Returning cached provider vodo
app.js:6 [DEBUG] Butter 0.3.9 startup time: 6541.702ms
app.js:6 [DEBUG] Not updating because we are running the latest version
app.js:6 [DEBUG] 46 cached subtitle
app.js:6 [DEBUG] Cache 0 subtitle
generic_collection.js:26 post all Object Object Array[50]
app.js:11 [INFO] Spawning new provider Favorites Object
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://movies.api-fetch.website/,
app.js:11 [INFO] Returning cached provider TVApi?&apiURL=https://tv.api-fetch.website/,
app.js:11 [INFO] Returning cached provider haruhichan
app.js:11 [INFO] Returning cached provider vodo

**Comment by VitorVRS** [comment]
It seems there is nothing wrong with PCT.
I was reading previous comments here e noticed that the file which saves your bookmarks was deleted.

**Comment by weker0** [comment]
@VitorVRS How would I restore that?

**Comment by ChrisAlderson** [comment]
Moved to #121
