### ISSUE TITLE
macOS Version needs compiled in Universal for  M1 

### ISSUE THREAD

**Issue by tehfalcon-vw** [popcorntime/popcorntime#1971]
Current x86-64 Build very buggy in rosetta, needs a native compile for ARM64

**Comment by kiriles90** [comment]
Other reports say it runs just fine.
But either way this is in none's plans as far as I know so closing this for now. Better ask apple to fix rosetta.

**Comment by tehfalcon-vw** [comment]
> But other reports say it runs just fine.. Either way the idea to make a desktop ARM build has been thrown around a long time (check closed issues) but its in none's plans as far as I know and doesnt really depend on Popcorn Time, more on nwjs on which Popcorn Time runs on, so.. closing this too for now.
> 
> (also imho better ask apple to fix rosetta than asking all the x86 apps to become native)

x86 apps need to become native. It is a future requirement. There is nothing wrong with Rosetta, it’s common sense there will be hiccups translating x86 to ARM. Apple isn’t going to continue making a translation platform work better for every single app they get a bug report about, it’s the developers responsibility to update their apps not apples. 

I suggest the developers research into Apple’s easy universal compiling program to make the App Universal (native binaries for both architectures).

**Comment by kiriles90** [comment]
Like I said, Popcorn Time runs on nwjs, which at the moment of writing this has no official M1 or ARM support.
Also its a future requirement for who? How many people use M1's at the moment? 5% of iOS 7% market share? So thats what? 0.35% of desktops out there? Apple will dig in its pockets and influence and pressure big companies to immediately support M1 with native apps but for everyone else you can see how its not a priority..

**Comment by tehfalcon-vw** [comment]
NW.js is absolutely working on M1 already. There are already OSX ARM64 builds. 

https://github.com/nwjs/nw.js/issues/7620

**Comment by kiriles90** [comment]
As evident by the open issue you just linked, no they dont. Those are just test builds with a lot of errors.

**Comment by kiriles90** [comment]
As evident by the open issue you just linked (and ofc their releases/downloads pages and documentation) no they dont. Those are just test builds with a lot of errors at the moment.

There is still a long way until they iron them out and release official, not test, beta or bugged arm versions and even longer until Popcorn Time that still uses a custom compiled 0.44.5 version can update to it.

That being said, you can try and build it for yourself with those builds if you are feeling confident they wont be even worse than the translation, but breaking the app for everyone with them is not a realistic option at the moment.

**Comment by Persei08** [comment]
@tehfalcon-vw you are a bit too fast. 
First we will need a stable silicon build of nwjs and then we will need to make a custom build of nwjs to include the extra codecs and test things. Not sure how much time it will take for all that, but not all contributors have a macbook M1. Else we aren't against, but contributions from M1 owners will be more than welcome.

**Comment by ghost** [comment]
looks like it should soon be possible? 🤞  https://github.com/nwjs/nw.js/issues/7620#issuecomment-957794983

**Comment by ghost** [comment]
FYI this is now working here: https://github.com/berard/popcorn-desktop

**Comment by sammcj** [comment]
I know this issue is closed but this is still an issue:

```
Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
```

I see there is a WIP PR: https://github.com/popcorn-time-ru/popcorn-desktop/pull/11

**Comment by arvinio** [comment]
> FYI this is now working here: https://github.com/berard/popcorn-desktop

@berard tried it out but it crashes after a few minutes of running
