### ISSUE TITLE
Not Updating Movies

### ISSUE THREAD

**Issue by jakescown** [popcorntime/popcorntime#1981]
Hi there, I've used Popcorn time for a number of years now. I'm currently using 0.4.4-0 "Love in the time of Corona" Beta for macOS, running version 11.1 of macOS Big Sur. For a few months now the Movies section has not updated at all, with any new titles. I've tried re-downloading and install Popcorn time multiple times, but nothing seems to work. Any suggestions please? Thanks, Jake.

**Comment by ivan1986** [comment]
see https://github.com/popcorn-official/popcorn-desktop/issues/1690
