### ISSUE TITLE
Wrong subtitle when casting to an external player

### ISSUE THREAD

**Issue by titolini72** [popcorntime/popcorntime#1986]
Operating System Version: OS X 10.14

Popcorn Time Version: 0.4.4

Download date: 2018

Download url (optional): Got from official page

#### Expected Behaviour
Chosen subtitles is not the one displayed when casting upon an external player

#### Actual Behaviour
If I select a Fr subs and casting to an external player I got English instead

#### Steps to reproduce the behaviour
1. Select a subtitle and play using PopcornTime player ==> Subtitles are correct
2. With the same selected subtitle then cast onto an external player (other than Popcorntime) ==> Not the proper subtitle.

**Comment by kiriles90** [comment]
Cant replicate. Download the latest dev build from ci.popcorntime.app, set the correct subtitle language as default in the settings and try again.
