### ISSUE TITLE
Rush 

### ISSUE THREAD

**Issue by Hannes004** [popcorntime/popcorntime#1994]
When I try to watch the 2013 movie Rush (about F1 drivers Niki Lauda and James Hunt) another movie always comes up (Rush 1991).  Is it possible to check this so that the movie about Niki Lauda can be watched again? thanks in advance!

**Comment by dutchy1001** [comment]
Popcorn Time is not responsible for the content, this is done through 3rd party API's that fetch the movies/series. 
Popcorn Time can't do anything about that as they don't control those API's
