### ISSUE TITLE
Feature request: Add music section, focusing on lossless quality🎵

### ISSUE THREAD

**Issue by Beastmastah64** [popcorntime/popcorntime#1996]
Hi

It would be great, if it would be able to stream/download lossless quality music 🎵 available from torrent etc 
add music section with quality filters and language etc
thank you

**Comment by dutchy1001** [comment]
I like the idea but I think that would be a totally different "app" altogether. 
It will probably have the same effect as Napster that's forcefully been taken down too.

**Comment by kiriles90** [comment]
@Beastmastah64 This is somewhat out of the scope of the app and its already covered by others apps better than what would be with torrents (e.g Deezloader). Also like @dutchy1001 said, it will only serve as adding another major target on Popcorn Time even with a half-working implementation.
