### ISSUE TITLE
Série sem imagem.

### ISSUE THREAD

**Issue by henrike1902** [popcorntime/popcorntime#2007]
A série **The Mentalist** está sem imagem em todos os episódios das temporadas 1 até a 6.

**Comment by dutchy1001** [comment]
When opening a issue for missing episodes the template already gives you the answer, editing this out doesn't make a difference for a fix.

> The app don't manage the content. Results comes from third parties APIs.
This is useless to open an issue here for those kind of issues.

Please close this issue


Ao abrir um problema para episódios ausentes, o modelo já fornece a resposta, editá-lo não faz diferença para uma correção.

O aplicativo não gerencia o conteúdo. Os resultados vêm de APIs de terceiros.
Isso é inútil para abrir um problema aqui para esse tipo de problema.

Por favor, feche este problema
