### ISSUE TITLE
Popcorn Time loading forever

### ISSUE THREAD

**Issue by PyrowX** [popcorntime/popcorntime#2009]
Operating System Version:
Pop!_OS 20.10

Popcorn Time Version:
Version 3.2

Download date:
28/01

Download url (optional):
https://getpopcorntime.is/linux.html

#### Expected Behaviour
Load each category normally
...

#### Actual Behaviour
Movies, Anime and Indie load eternally, while Series pops out the screen shown below
...

#### Steps to reproduce the behaviour

1. Install the program
2. ...?
3. Profit

![image](https://user-images.githubusercontent.com/78209606/106269031-9aced600-6234-11eb-8ee5-b5608c97d453.png)
![image](https://user-images.githubusercontent.com/78209606/106269048-a1f5e400-6234-11eb-9cef-da1d822abd51.png)

**Comment by kiriles90** [comment]
Wrong place. This repo is for the official Popcorn Time (.app)

**Comment by PyrowX** [comment]
what do you mean? Isn't this the official app?

**Comment by kiriles90** [comment]
No

**Comment by PyrowX** [comment]
I downloaded the official, from here and it works! Thank you!

**Comment by kiriles90** [comment]
You are welcome. Btw I probably should have mentioned this earlier but, get the latest one from ci.popcorntime.app (build 452 at the moment). If you got 0.4.4 from the frontpage is build 413 and many thing were fixed/added since then.

**Comment by Galixte** [comment]
> You are welcome. Btw I probably should have mentioned this earlier but, get the latest one from ci.popcorntime.app (build 452 at the moment). If you got release version 0.4.4 from the frontpage you got build 413 and many thing were fixed/added since then.

I recommend you to notice this information. Moreover, on Wikipedia getpopcorntime.is is not mentioned as suspect because popcorn-time.to redirects to getpopcorntime.is.

https://github.com/popcorn-official/popcorn-site/issues/14
