### ISSUE TITLE
403 on nw:build?

### ISSUE THREAD

**Issue by OmarShehata** [popcorntime/popcorntime#202]
I just downloaded the **master** branch on Windows 8, ran `npm install` and got all the dependencies. When I run `gulp build` everything works until it hits an error saying

`Received status code 403: https://get.popcorntime.sh/repo/nw/`

Here's the full output: 

http://puu.sh/pQmHW/bf0825f47b.png

Is anyone else getting this error? It looks like just opening https://get.popcorntime.sh/repo/nw/ in the browser shows a broken nginx page. How long has this been down? Is there anything I can do to work around this?

**Comment by VitorVRS** [comment]
You should use the main branch (development).

**Comment by Ekinoks** [comment]
Same error on Ubuntu 16.04 with development branch

**Comment by OmarShehata** [comment]
Switched to development, same error. Can anyone confirm they can run it?

**Comment by pellaeon** [comment]
I'm also getting this error on development branch.

**Comment by deercoder** [comment]
same error on MAC, and also on development branch

**Comment by pellaeon** [comment]
I figured out a way to extract the required files from the packages, I wrote the [note here](https://nyllep.wordpress.com/2016/07/11/fix-building-github-compopcorn-officialpopcorn-desktop/) (also includes some steps to make it start without error, I will file bug reports later.)

**Comment by OmarShehata** [comment]
Temporary fix: Go into Gruntfile.js and comment out this line:

`download_url: 'https://get.popcorntime.sh/repo/nw'`

And gulpfile.js and comment out:

`downloadUrl: 'https://get.popcorntime.sh/repo/nw/',`

**Comment by VitorVRS** [comment]
You should not comment this line, because on another point in gulpfile it is use to concat to the NW file corresponding to your machine (e.g linux32, linux64, windows...)

**Comment by OmarShehata** [comment]
@VitorVRS do you know how to fix this so it builds? Is there a mirror out there to https://get.popcorntime.sh/repo/nw/ ? Or another way? @pellaeon 's fix looks promising but I'm not sure if it will work on Windows, since I'm not sure how to extract the binaries like that.

**Comment by ItachiSan** [comment]
I would suggest, instead of removing the line, of using Butter's NW.JS.
The _downloadUrl_ sets the path where there's the needed NW.JS release tarball; removing it falls back on official NW.JS runtime, which does not provide the codecs that the PCT NWJS do.
As Butter also uses the same tarball of PopcornTime (I suppose, for sure is closer to PCT one that the official one), I suggest to all the builders to use
https://raw.githubusercontent.com/butterproject/nwjs-prebuilt/master/
as download URL.
Cheers :smile:

**Comment by OmarShehata** [comment]
Thanks @ItachiSan ! I'll give that a shot. I assume that's why I was able to build, I could not get any videos to actually play.

**Comment by Rudloff** [comment]
@ItachiSan The URL you suggested fails with this error:

```
Received status code 400: https://raw.githubusercontent.com/butterproject/nwjs-prebuilt/master/
```

**Comment by ChrisAlderson** [comment]
https://get.popcorntime.sh/repo/nw/ should be accessible, so I'm closing this issue.
