### ISSUE TITLE
Allow JavaScript from Apple events issue

### ISSUE THREAD

**Issue by null-unknown** [popcorntime/popcorntime#2020]
Hello reader,

I am trying to make my Popcorn-Time interact with my touch bar on my MacBook Pro as a new project. In order to make this work I need to be able to execute JavaScript through AppleScript.

Does anyone know how I can enable this?
<img width="698" alt="Screen Shot 2021-02-13 at 18 53 14" src="https://user-images.githubusercontent.com/76119380/107859185-0a011880-6e38-11eb-9a31-da6d9378d77e.png">

And in the com.nw-builder.popcorn-time.plist property "AllowJavascriptFromAppleEvents" is already set to 1.
<img width="577" alt="Screen Shot 2021-02-13 at 18 52 20" src="https://user-images.githubusercontent.com/76119380/107859183-09688200-6e38-11eb-8cf4-0ed026730ce7.png">

I am not sure if this is a bug because it seems to be enabled already in the .plist, but hopefully I am wrong.

Best regards.

**Comment by kiriles90** [comment]
Hi, this isnt really something specific to Popcorn Time. It has more to do with [nwjs](https://github.com/nwjs/nw.js) on which Popcorn Time runs on so you'll probably have better luck asking there.

**Comment by null-unknown** [comment]
thanks for your replay I finally manage to get it work by a lot of searching and trying, I found the right "JSON" file where I had to put property named "allow_javascript_apple_events"! 
![Screen Shot 2021-02-15 at 01 38 30](https://user-images.githubusercontent.com/76119380/107894116-d6ed8080-6f2e-11eb-9482-81ea8fa91deb.png)

**Comment by kiriles90** [comment]
@Unknown-IDs Thank you too for reporting back the solution in case someone else comes looking for it.

**Comment by null-unknown** [comment]
no problem :)

I successfully made my touch bar interact with popcorn-time, here are some few controls that I have implemented :
![thumbnail_IMG_3083](https://user-images.githubusercontent.com/76119380/107958466-50728680-6fa2-11eb-91ee-359bb90b50e2.jpg)
