### ISSUE TITLE
shameless series won't stream 

### ISSUE THREAD

**Issue by fmylife42** [popcorntime/popcorntime#2021]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour
  I was trying to watch shameless 
...

#### Actual Behaviour
 the entire series (shameless) wouldn't stream 
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
PCT is not responsible for the content, this comes from 3rd party torrent site(s), any missing or wrong info/movie or series is out of PCT's control.
