### ISSUE TITLE
Content not playing on VLC player nor streaming on TV

### ISSUE THREAD

**Issue by NumberUNO1** [popcorntime/popcorntime#2023]

**Comment by dutchy1001** [comment]
if you have downloaded the version from the official website you can have issue's indeed. Update to the latest "dev" build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** and try again. if the issue still exist report back, otherwise please close this topic.

**Comment by NumberUNO1** [comment]
Thats worked - thanks!
