### ISSUE TITLE
Unable to Play Some Shows on Desktop Application

### ISSUE THREAD

**Issue by TiggaBiscuit** [popcorntime/popcorntime#2024]
When trying to watch any shows on Popcorn Time using the Desktop application on Windows 10, I click on the Watch Now button and nothing happens. 

It appears to only happen on TV shows and it only happens for some of them. The show I was trying to watch was The Rookie Season 3 Episode 5; it doesn't seem to load any shows in either VLC or the build in player; however when I tested again with WandaVision and The Simpsons; and they both worked normally, and 9-1-1 did not work. It also happens over every resolution type (480p, 720p, 1080p).

### Environment:
OS: Windows 10 
Build: 19041.804 
Version: 2004

### Steps to Reproduce:
1) Open Application Normally.
2) Navigate to The Rookie Season 3 Episode 5
3) Click on Watch Now

### Technical Details:
Popcorn Time Version: 0.4.4-0 "Love in the Time of Corona"
Downloaded From: get.popcorntime.app
OS: Windows 10 (2004)
Connection Speed: 25Mbps
Connection Type: WiFi

### Troubleshooting:
Flushed All Databases.
Uninstalled and Re-Installed Application.
Restarted PC multiple times.
Tested on another Windows 10 Device with the same Operating System Build and on the same WiFi and the issue persisted.
Tried with both the 32Bit and 64Bit version of the application.

### Notes:
I've also tested this on another Windows 10 Device running the same windows build; and the issue persisted. 
The issue appears to be happening with specific TV shows and not all of them (I'm experiencing it with 'The Rookie').
Downloading works normally.
When it does work on TV shows there's sometimes a several second delay before anything happens on the screen, this delay also seems to happen on the movies.

**Comment by kiriles90** [comment]
Popcorn Time uses torrents which need to have at least some available seeds to connect and start downloading (it automatically indexes those torrents from 3rd party providers, for series its eztv)  

That being said, update to the latest build from ci.popcorntime.app (build 452 at the moment), it fixes the 'Watch now' button causing no change in the UI until it has connected issue.
