### ISSUE TITLE
Watch now button not working

### ISSUE THREAD

**Issue by Jaammeesss** [popcorntime/popcorntime#2030]
### Steps to Reproduce

1. Open Popcorn time
2. Select film or tv show
3. Click "Watch Now"

### Technical details:

* Popcorn Time Version: stable 0.4.4
* Downloaded from: popcorntime.sh
![image](https://user-images.githubusercontent.com/19493246/108825742-4c0a2700-75bb-11eb-9ad3-b9bf0993fa4b.png)

**Comment by dutchy1001** [comment]
Update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. If issue is still there report back if not plz close this.
