### ISSUE TITLE
Torrent list item extends to second line sometime due to varying width of down/up rate

### ISSUE THREAD

**Issue by tkSimon** [popcorntime/popcorntime#2035]
Operating System Version:
Linux, Fedora 33

Popcorn Time Version:
git/development

Download date:
6c32f152b4e901bb40dd562d34ebcee6169bbcd3

#### Expected Behaviour
List items should be contained in a single line.

#### Actual Behaviour
As the down/up speed changes, sometime one of the speed indicating elements moves to a second line.

#### Steps to reproduce the behaviour
I suppose this really depends on the font used, and on the OS.
1. Start download
2. Observe varying speed
3. Observe up/download element sometimes moves to second line, extending the torrent list entry to two lines

#### Screenshot(s) of issue
![torrent_list_wrap](https://user-images.githubusercontent.com/484513/109051297-a948ca00-76da-11eb-8313-acb3b1ba25f5.png)

**Comment by kiriles90** [comment]
Thank you for reporting. I think its good now after https://github.com/popcorn-official/popcorn-desktop/commit/527f53604571858cbe53ff2a1f5d589539fcd4b5 but try it and let me know what you think if you want.

**Comment by tkSimon** [comment]
Thanks for looking into this. While it's now longer line breaking, there's now some unused space between titel and the d/u rate indicators. Maybe something using flex boxes would be the best fit? Check this out: https://css-tricks.com/flexbox-truncated-text/
What do you think?

**Comment by kiriles90** [comment]
No worries. Hmm there is some space since the width for those indicators varies and because some things resize a bit different when using other fonts or scaling so I tried to account for that too (up until 200% anw) but I'll look into it and see if we can get a bit more accurate title cropping without messing anything up.

**Comment by tkSimon** [comment]
I fiddled around a bit and came up with this: https://github.com/tkSimon/popcorn-desktop/tree/seedbox-felxbox
Seems to work fine. Dynamically sizing the title based on available space, depending on width of d/u rate and window size.

**Comment by kiriles90** [comment]
Thanks, I'll check it as soon as possible.
