### ISSUE TITLE
Randomly it take time close application

### ISSUE THREAD

**Issue by Kishanpatel29** [popcorntime/popcorntime#2039]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Its not randomly, its when you have active torrents in the Seedbox and it takes some time (1-2 seconds?) to stop them then delete and exit the app. Closing this since the alternative would be not deleting the cache on exit and that wouldn't be a desired behavior.
