### ISSUE TITLE
bates motel season 4

### ISSUE THREAD

**Issue by poehazen1920** [popcorntime/popcorntime#204]
Operating System Version:
OS X 10.11

Popcorn Time Version:
 popcorntime.to

Download date:
 within six months
#### Expected Behaviour

subtiles fit in with the on screen dialogues  
#### Actual Behaviour

subtitles are behind by 30 seconds or more

captions are very important to me as a deaf person, its crucial for me to receive access to understanding the movies and shows. thanks for doing this! we all owe you our arm or leg :)

**Comment by ChrisAlderson** [comment]
This is the .sh version not the .to version. Can't help you with this one, sorry mate.
