### ISSUE TITLE
[Request] Keep Movies in disk drive while watching by Default + Save feature for its .Torrent file

### ISSUE THREAD

**Issue by calvinvalerian** [popcorntime/popcorntime#2046]
There's this feature:
Clear Tmp Folder after closing app?

**I feel from consumer side, this feature is inconvenient to be set as Default.**

Why? Because we lose seeders.

Sadly there's lack of Seeding in Movie Series (imagine there's only 1 seeder for 2160p) while Anime series (the 9 star rated one has 0 torrent seeder and I couldn't watch at all).

There's one more thing I like to request which is the .torrent file.

I'm a Long Term Seeder myself with high internet bandwidth and I keep whatever .torrent file I can get to be stored in my hard drive if something bad happen to my computer like reinstallation of OS and I have to re-add all the downloaded .torrent files of Movies or PC Games all over again to μTorrent.

I'm aware I can download the .torrent file from [https://yifytorrent.vip](url) but this method is inconvenient for Popcorntime lovers. I like the main interface of the app, it blends well with the theme and it was such a pain to go to https://yifytorrent.vip to see pictures of old movies everytime I wanna seed a movie.

I really really do hope the developer team will push this feature into the app.

**Comment by dutchy1001** [comment]
> There's this feature:
Clear Tmp Folder after closing app?
I feel from consumer side, this feature is inconvenient to be set as Default.
Why? Because we lose seeders.

Not everybody has the hard drive size to keep many files on it. With "Clear` Tmp Folder after closing" set to "keep" at default it can accumulate very quick to fill up that hard drive. This will then create problems with the whole PC when the hard drive is to full and OS's will struggle  to function properly. Not many will change the "default" location were the files are stored, meaning it will go to the same drive as your OS.

I do understand were your coming from but it would create more problems.

**Comment by kiriles90** [comment]
You are seeding back whatever torrent(s) you have active. Setting the option to not clear the cache by default isnt a good idea, like @dutchy1001 said not everyone is into becoming (or can become) a seedbox.

About the .torrent files, most of the time Popcorn Time uses magnet links not torrents files, which you can get by by right-clicking the magnet icon in the detail view of the specific movie or episode, or doing the same in the Seedbox tab after you've added it and it will copy the link in your clipboard. Then you can save them as you like if you want something more than just adding them to your Favorites in Popcorn Time. (you could also copy them then re-add them in the Torrent Collection to save there, then just backup the whole Torrent Collection folder somewhere after you are done saving everything, just note that those extension-less files arent .torrents, they are basically like text files with the magnet link inside)

P.s Popcorn Time doesnt use yifitorrent.vip, that's a fake website that just mirrors yts.mx's releases which is what Popcorn Time actually uses for movies.

**Comment by calvinvalerian** [comment]
What about by default installation Popcorn Time asks user where they want to store their downloaded movies? We can change it to another disk drive (D:) aside the Temp directory. This way to increase life span of a torrent movie and the life span of Popcorn Time. If Popcorn Time is not reliable in terms of streaming movie, I am pretty sure the community will abandon the app. I genuinely think Popcorn Time is a very good app and like to use it from time to time and I do not want it to die off.

**Comment by dutchy1001** [comment]
If ppl will abandon the PCT app because of the availability (of movies or series) then they would have done this long ago.  
If ppl want to share and have the "know how" how (like you) then they can, that is great, but most ppl come for the easy use click and play no fuzz.
