### ISSUE TITLE
in GNOME-Software: shows as proprietary license

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2049]
OS: Debian GNU/Linux bullseye/sid
Popcorn Time Version: 0.4.4 build 454, installed as **Debian package .deb**
Download url: https://ci.popcorntime.app/job/Popcorn-Time-Desktop/454/artifact/build/popcorn-time_0.4.4-amd64.deb

#### Expected Behaviour
It should show 'Free' because it's GPL instead of 'Proprietary' under License in the GNOME-Software description.

**Comment by kiriles90** [comment]
Not sure what can be done about this. It looks like there in an open bug in gnome-software and a lot of apps facing this issue (incl Chromium at some point) but no clear answers as to what needs to be done (and by who).
