### ISSUE TITLE
A helping hand

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2058]
> dutchy anybody help me , or email me please shot_kall@hotmail.com so i aint watched movies for 14 months and now i got my laptop back last month but there was a update i guess and now my screen is black without my favorite likes movies i cant press any button im really sad, i watched you dutchy on other sites i saw you commenting helping people, how do i fix this problem ? my laptop is also full of space do i have to delete popcorn time and download it again and all my liked movies come back with the heart logo on popcorn time ??

First off I'll presume you are have a Windows OS.
As you said nothing works you need to make sure your databases are save in case anything goes wrong.
To do this you need to go to "C:\Users\Your-User-Name\AppData\Local\Popcorn-Time\User Data\Default\data" and copy this folder to a save location (you might need to show "hidden files" ).
After youy done this you download the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** (click link).
Install this build and start PCT as normal. If your favourites and watched movies are present you don't have to do anything, if not, copy the folder you made a copy from back into the same location.
let me know how you get on.
Hope this helps

**Comment by Soldierkid** [comment]
> > dutchy anybody help me , or email me please [shot_kall@hotmail.com](mailto:shot_kall@hotmail.com) so i aint watched movies for 14 months and now i got my laptop back last month but there was a update i guess and now my screen is black without my favorite likes movies i cant press any button im really sad, i watched you dutchy on other sites i saw you commenting helping people, how do i fix this problem ? my laptop is also full of space do i have to delete popcorn time and download it again and all my liked movies come back with the heart logo on popcorn time ??
> 
> First off I'll presume you are have a Windows OS.
> As you said nothing works you need to make sure your databases are save in case anything goes wrong.
> To do this you need to go to "C:\Users\Your-User-Name\AppData\Local\Popcorn-Time\User Data\Default\data" and copy this folder to a save location (you might need to show "hidden files" ).
> After youy done this you download the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** (click link).
> Install this build and start PCT as normal. If your favourites and watched movies are present you don't have to do anything, if not, copy the folder you made a copy from back into the same location.
> let me know how you get on.
> Hope this helps

Yes i have a windows a HP laptop the one popcorn time version before the update came is it possible for you to film it ? because i dont got the files only the popcorn time app im gonna let my uncle do this cause i dont understand it quit bit

**Comment by dutchy1001** [comment]
I can't film this. Maybe let your uncle read this and he will understand then what to do, or just click the link (for the update), update and hope for the best

**Comment by Soldierkid** [comment]
> I can't film this. Maybe let your uncle read this and he will understand then what to do, or just click the link (for the update), update and hope for the best

welke is het er zijn zoveel is het die eerste van boven ? welke moet ik downloaden er zijn er zoveel

**Comment by Soldierkid** [comment]
> I can't film this. Maybe let your uncle read this and he will understand then what to do, or just click the link (for the update), update and hope for the best

which one do i have to press ? there are alot of options on the link you send me

**Comment by dutchy1001** [comment]
depending on your system 32 or 64 bit, get the correct exe file (first or second of the top)

**Comment by Soldierkid** [comment]
> depending on your system 32 or 64 bit, get the correct exe file (first or second of the top)

so it dont cares if its 32 or 64 ? what is a system ? system for my laptop ? popcorn time?

**Comment by dutchy1001** [comment]
link I send has an issue, download this version 
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/454/

When talking about "system" it's always your OS (operating system)
a 32 bit will work on both but a 64 bit will NOT work on a 32 bit system
