### ISSUE TITLE
 build #455 hangs on installation. Is there an install or runtime log somewhere?

### ISSUE THREAD

**Issue by JonDotExe** [popcorntime/popcorntime#2059]
Operating System Version:

win10

Popcorn Time Version:

Download date:

3.15.21 @6pm
Download url (optional):

ci build 255 released 3 days ago. 64 bit and 32 bit
#### Expected Behaviour

...
Open

#### Actual Behaviour

...
open 5-8 nwjs executables and hangs (no popcorntime exe)

#### Steps to reproduce the behaviour

install the 64 bit version and try to open it.

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Build 455 is bugged even if ci. shows it completed successfully. (https://github.com/popcorn-official/popcorn-desktop/pull/2051 is what broke it afaik)

Just skip it and keep build 454 until 456 is out.
