### ISSUE TITLE
"Watch Now" button doesn't respond

### ISSUE THREAD

**Issue by DorartD** [popcorntime/popcorntime#2063]
Operating System Version:
OS Catalina 10.15.7

Popcorn Time Version:
0.4.4

Download date:
March 17, 2021

#### Expected Behaviour
Start the movie

#### Actual Behaviour
It was working fine, I started a movie but I decided to stop and it and start another one, when I tried starting the other movie it just did nothing and I couldn't even start the first movie that started first or any other movies.

#### Steps to reproduce the behaviour
Just try starting a movie, I tried downloading as well but nothing happened.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
<img width="788" alt="Screen Shot 2021-03-17 at 00 31 42" src="https://user-images.githubusercontent.com/80795651/111393156-77fb6280-86b8-11eb-8a78-efaf982114f7.png">

https://imgur.com/WrPqux3

**Comment by dutchy1001** [comment]
Update to the (second) last build 454 from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/454/)**. issue should be fixed then.
Please close.
