### ISSUE TITLE
Multiple sources for custom movies server api field 

### ISSUE THREAD

**Issue by JonDotExe** [popcorntime/popcorntime#2064]
**Is your feature request related to a problem? Please describe.**

Constantly changing between https://yts.mx/ and https://popcorn-ru.tk/

**Describe the idea you'd like**

Would like to be able to add multiple sources in the Apie > Custom movies server field both https://yts.mx/ and https://popcorn-ru.tk/

**Describe alternatives you've considered**

Changing manually every time.

**Additional context**

Selecting which source to use for sorting and which to use for seeding. Aka, https://popcorn-ru.tk/ for sorting popular/trending and https://yts.mx/ for seeiding.

**Comment by kiriles90** [comment]
This cant be done. Not only it will confuse everything/everyone but what does even sorting Popular/Treding with ru and seeiding with yts.mx even means? If you want something that looks like Trending with the YTS API and that was why you created these two issues then the closest thing to it that you can get is just sort by Popularity or Trending (they are they same for that API as you noticed) then add the year in your search terms.

**Comment by JonDotExe** [comment]
> then the closest thing to it is just sorting by Popularity or Trending (they are they same for this API like you mentioned) then add the year in your search terms.

Not even close at all. Adding the year in and then searching by trending or popularity on yts.mx will discard search results from other years and not differentiate between trending and popularity. So, searching on yts.mx by year only shows the most downloaded recently by year when doing this. Whereas searching by default on ru.tk shows mostly movies from 2021, 2020, and even some from 2019 as you scroll down, because of whatever search parameters they are using. 

An easy alternative could be to have one api for search and one api for filling seeds, just call the second class when download is clicked and leave the first for everything else. But you know, I only have 10 years under my belt as a software pm and you said it's too hard. So what do I know right?

My currently solution to this is to clone popcorn time into two different apps: 1st app to browse, and 2nd app to download. It's quicker than constantly changing the api field.

**Comment by kiriles90** [comment]
I didnt say it was hard I said is a very bad way to so things. I'd expect someone with 10 years experiencee as pm to know this..
