### ISSUE TITLE
YTS.mx custom api doesn't differentiate between popular or trending in any category.

### ISSUE THREAD

**Issue by JonDotExe** [popcorntime/popcorntime#2065]
Operating System Version:

win 10 

Popcorn Time Version:

build 4.5.4

Download date:

3.16.21

Download url (optional):

#### Expected Behaviour

...
custom api on yts.mx - Sorting by trending or popular should sort in semi-chronological order by those constraints like they do while using hpopcorn-ru.tk/

#### Actual Behaviour

...

Popular and trending are the same, and are the exact same old triple A movie titles from 2014-2017

#### Steps to reproduce the behaviour

1. change custom api to yts.mx
2. sort by popular or trending in any category
3. change custom api to popcorn-ru.tk/

**Comment by dutchy1001** [comment]
As far I know the custom API doesn't have that option so it cant show the difference in PCT.

**Comment by kiriles90** [comment]
What @dutchy1001 said. That's what the API has/does when you make those queries and its not something that is up to Popcorn Time to fix.
