### ISSUE TITLE
Build #454 opens the previous movie file in vlc instead of the currently selected.

### ISSUE THREAD

**Issue by JonDotExe** [popcorntime/popcorntime#2066]
Operating System Version:

win10

Popcorn Time Version:

build #454

Download date:

3.16.21

Download url (optional):

https://ci.popcorntime.app/job/Popcorn-Time-Desktop/454/

win64

#### Expected Behaviour

...

Clicking on a movie should load it in vlc when selected

#### Actual Behaviour

...

Clicking on a movie loads the last played movie in vlc, with the currently selected movie title.

#### Steps to reproduce the behaviour

0. restart popcorn time from fully closed
1. Choose any movie
2. Change delivery method to VLC
3. Start downloading movie
4. Wait until vlc loads
5. allow a few minutes of a movie to load, but not the entire torrent to finish, then close vlc
6. Popcorntime automatically stops downloading movie (Expected)
7. Click on a different movie
8. Make sure delivery method is stil on vlc (normally it is, I do not have to change this here)
9. Click start and wait for the torrent to start downloading
10. Watch as vlc opens
11. VLC will now have the title of the current filename you downloaded, but will load the cache file from the previous file and start playing that movie instead. 
12. Fully close and restart VLC
13. Select the second movie you were attempting to play. 
14. That movie will usually load correctly, though sometimes it won't (may not be fully shutdown or may not be clearing cache)

**Comment by dutchy1001** [comment]
Only when I stop the movie and don't close off VLC completely it goes wrong, If I close of VLC the next movie just plays.
This is when "allow only one instance" is ticked , if un-ticked each movie plays fine.

My PCT is dev build 454 and VLC version 3.0.11 vetinari

**Comment by kiriles90** [comment]
I followed your instructions and cant replicate it. Isn't 1 to 11 basically just.. playing a second movie? (yes without completing playback or download so just following the instructions). Wouldn't anyone else have noticed so far that the second movie they try to play is always the first one again..?
