### ISSUE TITLE
I can't close the application

### ISSUE THREAD

**Issue by tya-rai2107** [popcorntime/popcorntime#2070]
Operating System Version: 10

Popcorn Time Version: Latest

Download date: 2018

Download url (optional):

#### Expected Behaviour:  I mean, close it when i press the button

...

#### Actual Behaviour: not close, even when i closed it from task manager, it's just always there and always on

...

#### Steps to reproduce the behaviour: 

1. ... open it
2. ... see if it does the same thing
3. ...

**Comment by kiriles90** [comment]
Duplicate of fixed and closed https://github.com/popcorn-official/popcorn-desktop/issues/1280

Update to the latest build from ci.popcorntime.app and the issue will be resolved.
