### ISSUE TITLE
Watch Now button not working [Win 10]

### ISSUE THREAD

**Issue by eavilaes** [popcorntime/popcorntime#2072]
I'm on version 0.4.4.0 (HEAD b2007344), Windows 10.
"Watch now" button is not working, when I open the console on F12 an error appears and the player does not start:

![image](https://user-images.githubusercontent.com/34559457/112228862-3f1c3a00-8c32-11eb-9d36-c6dc3df98d25.png)

That seems to happen with **"Play next episode automatically" enabled** on settings.
![image](https://user-images.githubusercontent.com/34559457/112228953-5f4bf900-8c32-11eb-9bce-ec184cf1b7df.png)

When I disable "Play next episode automatically" the player seems to load fine.

**Comment by dutchy1001** [comment]
Update to latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.

Please close if issue is fixed.
