### ISSUE TITLE
Wrong Movie Titles

### ISSUE THREAD

**Issue by Martinhos** [popcorntime/popcorntime#2082]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4 "Love in the Time of Corona" Beta

Download date:
02/10/2020 (dd/mm/yyyy)

#### Expected Behaviour
Display actual movie Titles
...

#### Actual Behaviour
Instead of "The Martian", displayed "The Popcorn Time",
"Fantastic Beasts and Where to Find Them" - "Fantastic Popcorn Time and Where to Find Them",
"Suicide Squad" - "Popcorn Time Squad",
and many more...
...

#### Steps to reproduce the behaviour

1. Start Watching a Movie
2. Stop watching the Movie
4. There will be some movies (not necessarily the ones I referenced) that have the wrong name - even if I restart the app

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
These are from the second attempt I made to make sure I could recreate it

![image](https://user-images.githubusercontent.com/27227689/113226539-5e494600-9288-11eb-99ea-50fb923cd7f4.png)
![image](https://user-images.githubusercontent.com/27227689/113226598-7de06e80-9288-11eb-8fa5-f6d296389114.png)
![image](https://user-images.githubusercontent.com/27227689/113226612-889b0380-9288-11eb-8313-d4f97d065e6b.png)

**Comment by kiriles90** [comment]
Its April Fools' day :smile:

If it annoys you you can disable it by unchecking the 'Celebrate various events' option in the settings.
