### ISSUE TITLE
After playing a series program will not respond to "X" close button.

### ISSUE THREAD

**Issue by oreleraki** [popcorntime/popcorntime#2084]
Operating System Version:

Windows 10

Popcorn Time Version:

0.4.4-0

Download date:

A month ago

Download url (optional):

#### Expected Behaviour

When clicking on X it should close the application.

#### Actual Behaviour

The application doesn't close but hangs, until i "End Task" in windows task manager

#### Steps to reproduce the behaviour

1. Open the application
2. Choose a series and "Watch Now", wait for it to load and play.
3. Try closing the application.

**Comment by dutchy1001** [comment]
update to last dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

Please close this topic as this will fix your issue
