### ISSUE TITLE
Auto and manual update check option

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#2085]
Add an option to automatically and manually check for Popcorn Time updates and install them

**Comment by kiriles90** [comment]
There is such an option in the settings. It will automatically update you if you have it enabled when there is a new release version.  

If you mean there should be one for dev builds too.. that wouldn't be a good idea. 1 bad dev build and you just broke Popcorn Time for everyone because they got autoupdated..

**Comment by GKid94** [comment]
@kiriles90 I have that option enabled and it didn't show any updates for new builds, and I don't mean developer builds I mean the stable ones

**Comment by GKid94** [comment]
Like the ones here on Github

**Comment by kiriles90** [comment]
There was no 0.4.5 release version yet. The last one is 0.4.4 from April 2020 (build 413)  

You can download the latest dev build (458) from ci.popcorntime.app its good, we cant just autoupdate people to them because they aren't always good (e.g build 455 that got broken by a dependency bump)

**Comment by GKid94** [comment]
@kiriles90 I know but the 0.4.4 version here on Github is getting fixes so that's what I mean about updating, not only when a new version is available, builds too

**Comment by kiriles90** [comment]
> I know but the 0.4.4 version here on GitHub is getting fixes  

And those fixes are available in ci. in the latest dev build. Update to it! (again, we cant make an autoupdate option because they arent always good, they need to be tested first by someone, and with an autoupdate feature, until that happens it will be too late for everyone who got autoupdated)

**Comment by GKid94** [comment]
@kiriles90 You didn't understand what I said, it clearly says here and on the website that the developer builds are for testers and they should get auto updates to test the new versions and report bugs and crashes, the stable versions of the app shouldn't get the developer updates only the stable tested ones, two different versions two different updates

**Comment by dutchy1001** [comment]
All (known) testers know where or when there is a new dev build and will download/install them accordingly to test, they also know how to revert to a previous build if things didn't work out as they should and report that. 
No need to make that an auto "dev build" update feature as more code can bring more issue's.

**Comment by GKid94** [comment]
@dutchy1001 That's what I mean the testers know all the info already, then maybe add the update option in the stable version?

**Comment by kiriles90** [comment]
> can bring more issue's

@dutchy1001 And it will... people will be like, 450 good, 451 good, 452 good, ok enable autoupdate to dev builds to save me the trouble of checking (like @GKid94 wants it for) then.. 455 or some future broken build breaks their installation, and possibly their databases. Then they all rightfully come raging here why we even added such a feature to auto-break the app, then we should send them all to @GKid94 :D

**Comment by dutchy1001** [comment]
@GKid94  
To update the official web download of PCT is a complex issue. As the legality in some countries are different, this has to be done with the utmost care (if you get my drift).

**Comment by GKid94** [comment]
@kiriles90 @dutchy1001 I don't mean the developer builds, I mean to have update checks for the official stable version

**Comment by GKid94** [comment]
The testers already know where to find the developer builds

**Comment by kiriles90** [comment]
> I mean to have update checks for the official stable version

@GKid94 It has..  
![Capture](https://user-images.githubusercontent.com/38388670/113447137-eacb4400-9401-11eb-9516-ff174f94afab.PNG)

**Comment by dutchy1001** [comment]
As there hasn't been an "official" update since April 2020 and the update issue for PCT I just mentioned you should understand why you don't have an official update.

**Comment by GKid94** [comment]
@dutchy1001 @kiriles90 Ok but what about build fixes that the current stable version is getting, it has been updated since last year

**Comment by GKid94** [comment]
There are no update notifications for that...

**Comment by kiriles90** [comment]
There is no 0.4.5 yet...

**Comment by GKid94** [comment]
@kiriles90 No not the developer builds, the stable builds that are added in the current stable 0.4.4 version here on Github, it got updates from the developer builds since the last year as you can see here https://github.com/popcorn-official/popcorn-desktop/compare/v0.4.4...development

**Comment by kiriles90** [comment]
> "stable" in ci. means nothing, it only means that the build was successful building, it doesnt mean its also good, e.g 455 is "stable", but its also broken to the point where it doesnt even launch.

**Comment by dutchy1001** [comment]
@GKid94 
>  it has been updated since last year

No, official it hasn't been updated, only updates are made to dev builds. 

this treat is repeating over and over the same thing, no point keep talking here....

**Comment by GKid94** [comment]
@kiriles90 @dutchy1001 Then what are those commits in the link that I sent?

**Comment by kiriles90** [comment]
Build 413 (0.4.4 release version) to build 458 (latest dev build)

**Comment by GKid94** [comment]
So those commits are just showing what's happening the developer versions?

**Comment by kiriles90** [comment]
Well yes you compared the developer channel didnt you?

**Comment by GKid94** [comment]
I thought that those where successful build updates from the developer version added to the current version

**Comment by GKid94** [comment]
Sorry my bad, it shows here that the latest master update is from last year https://github.com/popcorn-official/popcorn-desktop/compare/master...master

**Comment by kiriles90** [comment]
There is nothing in that comparison, you compared the master branch to the master branch.

**Comment by GKid94** [comment]
Yes but it shows the latest master update which is from last year as you said, can you maybe release the master official version more often, for example every month or a couple of months and name them 0.4.4 (458) for example

**Comment by GKid94** [comment]
But only the stable tested ones

**Comment by kiriles90** [comment]
When the master branch gets updated we should bump the version to 0.4.5, 0.4.6, 0.4.7 etc. Why not bump? As for releasing a new release version every month, its not up to me..

Anyway, dont be afraid of dev builds that people have confirmed are good, I think you understood by now that the only difference between them and a hypothetical same release version is someone going to https://github.com/popcorn-official/popcorn-desktop/blob/development/package.json#L14 and bumping that version, not much else.

**Comment by GKid94** [comment]
@kiriles90 @dutchy1001 No I mean like Stremio to release the stable developer builds as the official ones so that users get new updates more often

https://www.stremio.com/
https://github.com/Stremio/stremio-shell/releases

**Comment by kiriles90** [comment]
Those are basically release versions even if the major version number stays the same. In Popcorn Time is pretty much the same even if the first digit is 0. Anyway, so basically more frequent release versions. Ok.

**Comment by GKid94** [comment]
@kiriles90 Yes, thx

**Comment by GKid94** [comment]
@dutchy1001 @kiriles90 You can also try Stremio and see what features it has and you can add something similar in Popcorn Time
