### ISSUE TITLE
Movies from other regions

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#2086]
Add movies from other regions for example European, Russian and Asian movies

**Comment by kiriles90** [comment]
You already know Popcorn Time uses third party providers @GKid94  
What they have Popcorn Time automatically indexes (they do have European, Russian and Asian movies btw)

**Comment by GKid94** [comment]
Weird, I can't find some European and Russian movies like these

https://www.imdb.com/title/tt5966602/
https://www.imdb.com/title/tt0082096/
https://www.imdb.com/title/tt8228288/
https://www.imdb.com/title/tt8161166/
https://www.imdb.com/title/tt10554232/
https://www.imdb.com/title/tt5951188/

**Comment by kiriles90** [comment]
Das Boot, The Platform and The Balkan Line are there. The rest, it means the movies provider doesnt have them so you'll have to find a torrent somewhere yourself and drag&drop it to Popcorn Time.  

Btw like I said in your other issue, update to the latest dev build from ci. and check the settings for how to change your API urls.

**Comment by GKid94** [comment]
@kiriles90 Can you maybe add more torrent sources for the movies and series?

**Comment by kiriles90** [comment]
Update to the latest dev build and switch to the .ru API in the settings, it indexes more providers.

**Comment by GKid94** [comment]
![Screenshot 2021-04-02 201931](https://user-images.githubusercontent.com/18757054/113442705-d894da00-93f0-11eb-9620-2b3c1161ea6e.jpg)

**Comment by kiriles90** [comment]
> check the settings for how to change your API urls.

**Comment by GKid94** [comment]
@kiriles90 The covers are still broken in the developer build

![Screenshot 2021-04-02 202606](https://user-images.githubusercontent.com/18757054/113443178-bc456d00-93f1-11eb-9eaf-5368633f04a3.jpg)

**Comment by kiriles90** [comment]
Give them some time to load. 99% of them are there, ones that arent it means the API has no poster (or link is broken), traktv has no poster, and tmdb has no poster.

**Comment by GKid94** [comment]
@kiriles90 I did wait for a few minutes

**Comment by dutchy1001** [comment]
The missing covers is a 3dr party issue and can not be fixed by PCT devs as they don't control the API's used to fetch all the info. If YTS or the .ru  cant get a cover then that is unfortunate.

**Comment by GKid94** [comment]
@dutchy1001 Ok
