### ISSUE TITLE
Missing covers

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#2087]
A lot of movies and series are missing covers

![Screenshot 2021-04-02 173940](https://user-images.githubusercontent.com/18757054/113430479-89dc4580-93da-11eb-9e0b-057c0db310e3.jpg)

**Comment by kiriles90** [comment]
You are using the old 0.4.4 release version. Update to the latest build from ci.popcorntime.app this has been fixed.

**Comment by GKid94** [comment]
@kiriles90 Those are unstable developer builds, I'm talking about the stable version

**Comment by kiriles90** [comment]
They arent unstable. What separates them from a release version is a human saying this build is good, it will be the new release version. So.. update..

**Comment by GKid94** [comment]
@kiriles90 Ok but still can you add the auto and manual update check for both stable and developer versions of the app?

**Comment by kiriles90** [comment]
@GKid94 no because some dev builds arent good, 458 is good, 454 is good, 455 is broken. If people had this option and got autoupdated from 454 to 455 -> everyone's Popcorn Time would be broken and would need a reinstall.

**Comment by GKid94** [comment]
@kiriles90 Ok then only for stable builds

**Comment by GKid94** [comment]
And that's what I'm saying, the developers builds are unstable because they get broken

**Comment by kiriles90** [comment]
> And that's what I'm saying, the developers builds are unstable because they get broken  

Developer builds aren't inherently unstable or broken. They just arent tested.. until someone(s) tests them. Thats why we cant autoupdate to them and thats how I know 458 is good.

**Comment by GKid94** [comment]
@kiriles90 If they aren't tested it means that they are unstable and not safe to use, it clearly says that it's a tester version

**Comment by GKid94** [comment]
@kiriles90 To be honest it's better to also have the auto update option for the developer build versions and if the app get's broken they can report the bug so that it can get fixed, that's what testing versions are for

**Comment by GKid94** [comment]
It's to be expected that the testing versions of the app would get broken, and if it does the bug should be reported to get fixed

**Comment by kiriles90** [comment]
Popcorn Time does nothing different than the huge majority of the apps out there. They dont autoupdate to dev version for the simple reason not many users want their apps to autoupdate themselves into a broken state with a reinstall needed every now and then. With a manual dev build install a) you know what you are doing, you know how to roll back b) you can ask if a build is good before updating to it if you dont want to be the tester

**Comment by GKid94** [comment]
@kiriles90 That's the problem, the non testers shouldn't use the developer builds and then complain about bugs and crashes, they should use the stable versions and wait for stable tested updates

**Comment by kiriles90** [comment]
Does VLC e.g autoupdate you to nightly builds? No, their release version doesnt, and if you manually install a nightly build that wont autoupdate you to the next one when its released either. Its a common convention apps use. The only model that is different is apps that have beta or alpha channels, which I dont see Popcorn Time having anytime soon.  

Right now the release versions and everyone other build are part of the same channel. E.g build 410, 411, 412, 413 (this becomes 0.4.4), 414, 415, ... 457, 458 etc. At some point one of these will become 0.4.5. It doesnt say anything about if build 436 or whatever is good or not, it just says 4xx was deemed good enough and enough changes and times has passed to release a new version.

**Comment by GKid94** [comment]
@kiriles90 I don't know about the beta VLC but the stable one has a auto update check

**Comment by kiriles90** [comment]
Autoupdate check for release versions not nightly builds..

**Comment by GKid94** [comment]
@kiriles90 Ok that's what I mean, but what about new stable builds of the same version?

**Comment by dutchy1001** [comment]
@GKid94 see my answer in the other post about updating PCT

**Comment by GKid94** [comment]
@dutchy1001 I've seen it
