### ISSUE TITLE
Spanish subtitles are out of sync with the video in various shows and movies

### ISSUE THREAD

**Issue by Nicolasarc** [popcorntime/popcorntime#2088]
Operating System Version:
 Windows 10

Popcorn Time Version:
 

Download date:
Three months ago

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Subtitles are 3rd party (opensubtitles.org) added to the movie or serie you watch, you can adjust the sync with the H and G on your keyboard, if you use an external player it should have same option to sync but probably different keys.
As it's a 3rd party addon PCT cant do anything about this.
