### ISSUE TITLE
Watch Now button not working on certain series

### ISSUE THREAD

**Issue by snrjon** [popcorntime/popcorntime#2089]
All of a sudden I don't seem to be able to watch certain shows. I click on Watch Now and it does nothing. I've tried un-installing, re-installing but no luck.

I haven't done any updates on my Mac, literally changed nothing since I last used it last week. 

Operating System Version:
OS X 10.15.6

Popcorn Time Version:
4.4

**Comment by dutchy1001** [comment]
Were did you download it from?

**Comment by snrjon** [comment]
> Were did you download it from?

Here:
https://popcorntime.app/mac

I’m hoping that’s the right place? 🤦🏼‍♀️😂

**Comment by dutchy1001** [comment]
yes that is the right place indeed, as the dev builds have many improvements and fixes I would suggest to update to the latest dev build from  **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. and choose the "Popcorn-Time-0.4.4_osx64.zip" download for your system.
