### ISSUE TITLE
favourites disappear

### ISSUE THREAD

**Issue by elmonoperezoso** [popcorntime/popcorntime#209]
First of all, congrats for your great proyect.

From time to time, when I start the program I have to agree the TOS and so all favourites are gone.

Operating System Version: Windows 10

Popcorn Time Version: 0.3.9.0 1c51a7fa

Download date: several months ago

**Comment by Breaking1** [comment]
Can you please try this build and see if the problem is fixed.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/116/

**Comment by elmonoperezoso** [comment]
Sure, I update and test.

BTW, which is the best way to update it under Windows?.

Do you plan to incorporate an option to update it, via, for instance, your ftp?

**Comment by Breaking1** [comment]
For now you need to re-download from the web site to get the latest version, the internal auto updater is not activated an needs a little work as you can see here:

https://github.com/popcorn-official/popcorn-desktop/issues/82

**Comment by Enchufadoo** [comment]
I just lost all my bookmarks + seen movie history auto updating to the latest version.

Plus when I click on the seen icon on movies thumbnails it doesn't work.

(Windows 7 64 + v0.3.9-0 (80e3fc19))

**Comment by Breaking1** [comment]
Try this build and see if it works properly.

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/116/

**Comment by elmonoperezoso** [comment]
It just happened again; today once starting the app I have to agree to the TOS and all favourites were gone

**Comment by Breaking1** [comment]
Next time this happens try to just restart it instead of accepting TOS like with a fresh install and see if it works.

**Comment by elmonoperezoso** [comment]
It did not work. At frist time, the app hanged, I have to cancel and run again

**Comment by Enchufadoo** [comment]
@Breaking1 I've tried it for a couple of days and it works as expected, my favs and config are gone but everything runs as usual. Thanks.

**Comment by fadster** [comment]
I don't know why this issue was closed, it's still present 4 years later!

**Comment by dutchy1001** [comment]
Why necro an issue after 4 years?
If this was also an issue for you then you should have either answered here (4 years ago) or created a new issue report (in 2020).

Fair play to check the issue's as you should, but this count for "open" issue's". When closed you can create a new issue and refer to the closed one with a hashtag ( #209 ).
As for now, update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** and create a new issue if it still happens.

**Comment by fadster** [comment]
I posted my comment here because I believe 0.3.10 should be revived and further development and fixes made there. 0.4 would be best abandoned as it has introduced several problems, a loss of functionality, unnecessary and undesired changes, and annoyances degrading the user experience (eg. VPN ads).

**Comment by dutchy1001** [comment]
what is stopping you to do so then?

**Comment by fadster** [comment]
I may not have the time to work on the project but I can offer a suggestion.
