### ISSUE TITLE
media not opening.

### ISSUE THREAD

**Issue by hcnsola** [popcorntime/popcorntime#2092]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
some weeks ago

#### Expected Behaviour
it should open the downloading screen right after I click on the watch button.

#### Actual Behaviour
when I try clicking the watch button nothing happens, and that goes for both tv shows and movies.

#### Steps to reproduce the behaviour
go to any media and try to watch it

**Comment by dutchy1001** [comment]
due to some technical issue's our Jenkins dev repo is down for downloading the latest dev builds (which would have fixed your issue)

**Comment by kiriles90** [comment]
What @dutchy1001 said. You need to update to the latest build but the website was taken down a couple of days ago. You could either build Popcorn Time yourself from source or try the subreddit, they might be able to help you with a mirror or something.
