### ISSUE TITLE
Installation not working - Mac OS X 11.2

### ISSUE THREAD

**Issue by adityas129** [popcorntime/popcorntime#2100]
Operating System Version:
 OS X 11.2

Popcorn Time Version:
Tried the most recent version and older versions for Mac 

Download url (optional):
Tried to run the command ```brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time``` and tried to download by going on ```master ``` and going to the older versions and pressing the old OS X link. 
<img width="734" alt="Screen Shot 2021-04-15 at 4 36 10 PM" src="https://user-images.githubusercontent.com/20564453/114946582-b182d300-9e08-11eb-9d3d-12a62b1c67ec.png">

#### Expected Behaviour
Should download

#### Actual Behaviour
the command download using command line yields this 
<img width="986" alt="Screen Shot 2021-04-15 at 4 34 31 PM" src="https://user-images.githubusercontent.com/20564453/114946471-76809f80-9e08-11eb-9e92-9987aac3ecc3.png">
and the link download redirects to this page for whatever reason (found this in the 
<img width="992" alt="Screen Shot 2021-04-15 at 4 35 55 PM" src="https://user-images.githubusercontent.com/20564453/114946560-a7f96b00-9e08-11eb-9e93-a8f7a185298d.png">

Not sure what's up

**Comment by adityas129** [comment]
just realized -> popcorntime.app also redirects to the Medium Page above with the 410

**Comment by kiriles90** [comment]
The website and everything under the .app domain got taken down last week. There was briefly a notice but that got taken down too. Only thing we can do now is wait and see what happens. In the meantime you can check the torrentfreak articles as to more info on what happened and the subreddit for any mirrors for the app. Closing this issue but feel free to comment below if you are still running into issues.
