### ISSUE TITLE
Websites disappeared

### ISSUE THREAD

**Issue by reenieh** [popcorntime/popcorntime#2103]
I get a 404 error when trying to access the website.  I am missing the latest patch to version 4.4 and wondered if it was located somewhere else.

**Comment by kiriles90** [comment]
Yes the website and everything under the .app domain got taken down last week due to legal issues. Read the torrentfreak articles and/or check the subreddit for more info. Closing this since its not an issue with the app but feel free to comment below if you are still running into issues.
