### ISSUE TITLE
Doesn't load any content

### ISSUE THREAD

**Issue by dutchxarms** [popcorntime/popcorntime#2105]
keeps loading loading and loading removed popcorn time beta and reinstalled it.
this version always had the fasted updated shows... the popcorn time regular just never have updated shows...
how to fix?? takes popcorn time beta 1 day to add an episode where regular version doesnt even have the season yet..
https://prnt.sc/11qwi01

**Comment by dutchy1001** [comment]
I cant figure out from your message if you have a dev build or from the PCT website (which is currently down). 
If you have the latest dev build you can add a server in the "advanced" settings page (see #1690 pinned on top)
If you have the version from the website then your out of luck for now as there is a legal issue atm to download (see some "closed" issue's).

**Comment by dutchxarms** [comment]
i got the latest from https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.4
its not loading any progams or shows

**Comment by talassar** [comment]
Hi, I have the same problem and the same version.

**Comment by GiancarloJSantos** [comment]
All domains are out. 

popcorntime.sh and popcorntime.app

Maybe that is the main problem.

**Comment by dutchy1001** [comment]
@dutchxarms 
That release is build 413 and very outdated compared to the dev builds (latest is 458). 
There are some mirrors that might have the latest dev build but I don't know for sure. 
As your version wont allow to change the API to fetch info there is nothing we can do atm.

@GiancarloJSantos 
Your correct, due to a legal action from a lawyer in Hawaii (he always gets bored around Easter) most sites are down.  

As far I know the .ru api still works for series (which can be used in the latest builds)

**Comment by dutchxarms** [comment]
i rather have this build i always use its better its better menu overall the shows are on there where on other one the shows new seasons dont show up i just dont like that one.

**Comment by dutchy1001** [comment]
@dutchxarms 
In that case there is not much we can do.

You can close this issue.

**Comment by dutchxarms** [comment]
> @dutchxarms
> In that case there is not much we can do.
> 
> You can close this issue.

who is we? you made popcorntime?

**Comment by dutchy1001** [comment]
WE as in the support team

And NO, I didn't make PCT

**Comment by kiriles90** [comment]
@dutchxarms You rather have the broken build 413 that everyone is complaining about for years instead of the latest one that fixes most of this issues. Then like @dutchy1001 said, not much we can do about it. Old builds dont get updates and when something breaks, remains broken. Closing.

**Comment by fitzchevalrick** [comment]
would it be possible      to put a link here   where we can download again a good version of PCT?

**Comment by dutchy1001** [comment]
@fitzchevalrick 
If we posts links here were to download we will risk that this will be taken down as well. At least this way we can still communicate and devs still can add/fix things (even when we can't download them) in the hope that the download page will be reopened at some point.

**Comment by kiriles90** [comment]
If you also want to get hunted by whoever sued .app, go for it :) If not, visit the subreddit and check the pinned posts they have all the answers you need.

**Comment by fitzchevalrick** [comment]
thank you for your advice

**Comment by princessa12** [comment]
> ou also want to get hunted by the ones who sued .app, go for it :) If not, visit r/popcorntimeapp and check the pinned posts they have all the answers you need.

i entered there and downloaded the PCT 0.4.4 , HEAD 739AD0AC, and there is still a problem.. wanted to know if it will get fixed or should i do something to fix it?

**Comment by kiriles90** [comment]
@princessa12 go in the settings and set a custom movies/series/anime server. There are some set suggestions but any compatible API will work.

**Comment by suelinosaba** [comment]
Doesn't load any content

**Comment by tingspain** [comment]
> @princessa12 go in the settings and set a 'Custom movies/series/anime server'. There are some set suggestions but any compatible API will work. If at any point you what to check what the default API is doing just clear the relevant text box and restart the app.

@kiriles90, I tried that, I was looking for the API server settings but it doesn't show up in the advance settings. I tried several versions of PCT  0.4.2 - 0.4.3 and 0.4.4. And nothing. Is there any way to show the API Server settings?

**Comment by epadua** [comment]
Just set https://popcorn-ru.tk/ as api server in original client and you get fresh movies and serials

**Comment by tingspain** [comment]
> Just set https://popcorn-ru.tk/ as API server in original client and you get fresh movies and serials

I am using the PCT 0.4.4 MACOS version (and tested the 3 previous versions as stated before) and the API Server doesn't appear at the advanced settings.

**Comment by dutchy1001** [comment]
@tingspain 
You obvious do not have the latest dev build or you would be able to add a custom server (version from the website doesn't have that option). 
As far I know the custom servers were added in build 450 and the latest build is 458.

**Comment by tingspain** [comment]
Just in case, anyone is looking for the[ build #458](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/458/)

**Comment by kiriles90** [comment]
@tingspain we dont know what is going on with ci. atm. Everything .app got taken down last week then the forum reappeared 2 days ago as well as ci. but ci. uses a bad certificate right now. So.. for now I'd use the mirrors everyone else mentioned instead until this thing clears. Might be nothing, but better safe than sorry.

**Comment by MattBxxxx** [comment]
Keeps loading and loading. Bummer. Any update on solutions?

**Comment by kiriles90** [comment]
@MattBxxxx the solution is above

**Comment by MattBxxxx** [comment]
Thx. I ended up downloading the new version and it's working fine.

**Comment by diegogarciar** [comment]
Hello, as I understand we need to use a dev release for now as a workaround so we can change the api server.
Is there a way to download the latest dev release?

I tried using brew for my Mac but it seems that `https://ci.popcorntime.app/job/Popcorn-Time-Desktop/` certificate has expired so I can't run `brew install --cask popcorn-time-beta`

**Comment by Saphyel** [comment]
@dutchy1001 would be possible that you make a release soonish?

**Comment by dutchy1001** [comment]
I'm only support, I dot do any of the coding or releasing.

**Comment by diegogarciar** [comment]
@dutchy1001 do you have a link for a dev release?

**Comment by dutchy1001** [comment]
to be on the save side we cant link any builds here, but if you read back in the post you will get some info how and were.

**Comment by fitzchevalrick** [comment]
Hey,

Could you provide thise computer analphbet the link of the new pct version please?

Regards, Fitzchevalrick


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: ***@***.***>
Verzonden: donderdag 22 april 2021 5:26
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [popcorn-official/popcorn-desktop] Doesn't load any content (#2105)


Thx. I ended up downloading the new version and it's working fine.

**Comment by diegogarciar** [comment]
Found answer here
https://www.reddit.com/r/PopCornTimeApp/comments/lykcdc/windows_macos_linux_users_please_read_before_you/

**Comment by fitzchevalrick** [comment]
Dont have that API section.
It goes from “remote control” to “connection”

“API” is missing

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Diego ***@***.***>
Verzonden: donderdag 22 april 2021 21:45
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [popcorn-official/popcorn-desktop] Doesn't load any content (#2105)


Found it here
https://www.reddit.com/r/PopCornTimeApp/comments/lykcdc/windows_macos_linux_users_please_read_before_you/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.reddit.com%2Fr%2FPopCornTimeApp%2Fcomments%2Flykcdc%2Fwindows_macos_linux_users_please_read_before_you%2F&data=04%7C01%7C%7Ce515cc9cd8b9496a0d1008d905c72fd4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637547175314299429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JKixxcauszHKCRoRWvLrUc0uxjQDZSn8p9BMkNv4sSk%3D&reserved=0>

**Comment by kiriles90** [comment]
> would be possible that you make a release soonish?

@Saphyel a bit problematic since .app got taken down until further notice

**Comment by kiriles90** [comment]
@fitzchevalrick download from the links people mentioned above, make sure that's what you are installing afterwards, and change the custom servers in the settings. Nothing more to it.

**Comment by dutchxarms** [comment]
> Just set https://popcorn-ru.tk/ as api server in original client and you get fresh movies and serials

even tho it loads it does not include newest shows..

**Comment by dutchy1001** [comment]
A different API will have a different algorithm to "fetch" data. it might take a few days longer or  those series you talk about are not available from where the API fetches the data.
Nothing we can do, at least the .ru-tk still works for most other stuff.

**Comment by mbjunqueiraweb** [comment]
I solved my problem installing from here: http://popcorn-ru.tk/build/, in the advance settings API server used https://yts.mx/ for movies and https://popcorn-ru.tk/ for the series. Restarted Popcorn e buuum, worked!

**Comment by Villelmo** [comment]
I have the same problem!

**Comment by ghost** [comment]
The problem still persists and the issue is with the popcorntime.app DNS. The website, if you check it, doesn't work either and everything it is trying to fetch is from this domain which doesn't seem to work.
![image](https://user-images.githubusercontent.com/53082621/116344011-295ae100-a7ab-11eb-858c-078ab6ad2e49.png)

**Comment by thejoker3000** [comment]
@kiriles90 Can you reopen this issue since it still persists and no solution has been found? Check my comment above

**Comment by kiriles90** [comment]
@thejoker3000 The website and everything under the .app domain got taken down due to legal issues. If/when they come back great but in the meantime there is nothing to fix (or is an issue with the app). Use a custom API for now.

**Comment by thejoker3000** [comment]
@kiriles90 OK, I wasn't aware of that. 
What API can I use if you know any? Or would that be like Trak.tv for example?

**Comment by kiriles90** [comment]
If you have updated to the latest build there are some suggestions when you click the Custom API fields. Ofc if you know of (or setup) any other compatible APIs, they will also work.

**Comment by kounelios13** [comment]
@kiriles90 hello. I have updated to the latest version (0.4.4) and in the settings section i cannot see anything remotely related to API server

**Comment by dutchy1001** [comment]
@kounelios13 
from were have you updated?
The version that was on the website is outdated compared to the dev builds. You need at least dev build 458 to add custom API servers (you might need to tic the "show advanced setting" on top of the settings tab)

**Comment by kounelios13** [comment]
@dutchy1001 I used the releases section from this repository .Isn't that the correct place?

**Comment by brawaru** [comment]
@kounelios13 na-ah, last release is from the previous year, use artifacts from the last successful CI build — https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154.

**Comment by kounelios13** [comment]
@Brawaru 

> @kounelios13 na-ah, last release is from the previous year, use artifacts from the last successful CI build — https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154.

Thank you i wasn't aware of that . I actually ended using the link from the previous comments that pointed to some builds and it worked. I will now be aware for the future

**Comment by FlameFractal** [comment]
For anyone still landing on this issue from search... As of 1 May 2021 - this is the latest build (https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154) and this is the working api server (https://popcorn-ru.tk/)

**Comment by Kakadu** [comment]
> All domains are out.
> 
> popcorntime.sh and popcorntime.app
> 

It looks like domains being out preventing compilation of PopcornTime. 
Does anybody know how to workaround it?

```
 ✗ gulp build                     
[18:03:06] Using gulpfile /media/oldhome/kakadu/prog/popcorn-desktop/gulpfile.js
[18:03:06] Starting 'build'...
[18:03:06] Starting 'injectgit'...
Branch: development
Commit: f9437d1f
[18:03:06] Finished 'injectgit' after 23 ms
[18:03:06] Starting 'css'...
Stylus files compiled in ............................../src/app/themes/
[18:03:09] Finished 'css' after 3.59 s
[18:03:09] Starting 'nwjs'...
{ Error: getaddrinfo EAI_AGAIN popcorntime.app popcorntime.app:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'popcorntime.app',
  host: 'popcorntime.app',
  port: 443 }
[18:03:32] Finished 'nwjs' after 23 s
...
```

**Comment by ivan1986** [comment]
@Kakadu 
https://github.com/popcorn-official/popcorn-desktop/compare/development...popcorn-time-ru:nw-location

**Comment by dutchxarms** [comment]
> For anyone still landing on this issue from search... As of 1 May 2021 - this is the latest build (https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154) and this is the working api server (https://popcorn-ru.tk/)

still not with updated fast series. like before.

**Comment by Kakadu** [comment]
> @Kakadu
> [development...popcorn-time-ru:nw-location](https://github.com/popcorn-official/popcorn-desktop/compare/development...popcorn-time-ru:nw-location)

Thanks!

**Comment by dutchy1001** [comment]
> still not with updated fast series. like before.

For those that are looking for a movie/series episode you can search for them even if there not listed on the main pages.

Goto "torrent Collection" tab (on right side top of screen)
Select "Movie" or "Series" or "Anime"
Type the name of the serie in (it will take a few before results are shown)
Pick the file you want (again, this might take a few)
When "Please select a file to play" appears on screen click it
The movie or episode will start to play (again, this might take a few)

This way I watched "line of duty S06E07" while it wasn't listed yet on the main series page.
(PS, it's listed now)

**Comment by dutchxarms** [comment]
> > still not with updated fast series. like before.
> 
> For those that are looking for a movie/series episode you can search for them even if there not listed on the main pages.
> 
> Goto "torrent Collection" tab (on right side top of screen)
> Select "Movie" or "Series" or "Anime"
> Type the name of the serie in (it will take a few before results are shown)
> Pick the file you want (again, this might take a few)
> When "Please select a file to play" appears on screen click it
> The movie or episode will start to play (again, this might take a few)
> 
> This way I watched "line of duty S06E07" while it wasn't listed yet on the main series page.
> (PS, it's listed now)

yeah.. that is not an option everytime i seach says nothing found :)

**Comment by dutchy1001** [comment]
@dutchxarms 
is your series API set to the ru.tk?

**Comment by kiriles90** [comment]
@dutchxarms If the Torrent Collection always says nothing found then it means all 3 rarbg, 1337x and omgtorrent (thepiratebay is broken) are blocked from your location. Use a VPN or something because it works when those sites are accesible.

**Comment by Umeaboy** [comment]
Ping! I also experience this and I used the official instructions. I'll try with the dev release.

**Comment by leenpaws** [comment]
> Just set https://popcorn-ru.tk/ as api server in original client and you get fresh movies and serials

thank you, this solved it :)

**Comment by smac89** [comment]
I just want to clarify something and I would appreciate it if one of the popcorn devs gave an answer to this:

1. Is it ok to switch to the `https://popcorn-ru.tk/` server for dev builds?
2. If so, why hasn't the dev branch switched to this server yet?

Thanks

**Comment by kiriles90** [comment]
1. Ofc, its just an API why would it be an issue? You could always do that with Popcorn Time, just now it can also be done via the settings page for easy access. Think of it as a feature that was always there but couldn't be called that in the past since it required editing .js files that many people aren't comfortable doing. Its also not something that's limited to the Ru API, if you know (or setup) any other compatible APIs they are also a valid option. Even incompatible ones can be made to work if someone makes a wrapper for them so Popcorn Time can understand what they are 'saying' (e.g like the YTS one).
2. Because that was never the goal with this. The goal was to give people multiple options to choose from in case they prefer one over the other, or one is inaccessible from their location (not everyone uses a VPN) or one of them is down like the official API is right now. Makes for a better user experience and the app much harder to kill. Eventually though, if the old API isn't coming back (last update about it says it will but it might take time) a new default will have to be set so the app works out of the box. Or maybe not.. This last option seems to work well for other apps (I'll avoid naming them but its pretty easy to figure out which ones I mean) and makes them harder to hunt and blame for their users using APIs and addons that include copyrighted content.

**Comment by ghost** [comment]
Where to get dev build for windows?

**Comment by ghost** [comment]
> Where to get dev build for windows?

Why post that here? What's that have anything to do with popcorn not working?

**Comment by kiriles90** [comment]
@joootdooot At the -ru.tk url above.

**Comment by GNSubrahmanyam** [comment]
@dutchy1001 How to fix it. Still i am facing this issue. 
![Screenshot from 2021-06-06 11-56-02](https://user-images.githubusercontent.com/18217008/120914835-30381600-c6be-11eb-9ec4-fdd72b798adc.png)
Node version: v12.20.2
Ubuntu: 20

**Comment by dutchy1001** [comment]
@GNSubrahmanyam I'm sorry but I don't have a clue for Ubuntu, I'm only familiar with windows machines.
If you have the latest dev build you should be able to add custom servers. These servers are mentioned above in some posts.

**Comment by losl2** [comment]
Doesn't load any content.
The app opens but does not load. I already uninstalled, installed and still does not load.
I use the app on windows 10.
Can someone help me?
![pop corn](https://user-images.githubusercontent.com/85513484/121090076-6957af80-c7be-11eb-9b45-e88969ac6be5.jpg)

**Comment by sailinggalaxians** [comment]
> Doesn't load any content.
> The app opens but does not load. I already uninstalled, installed and still does not load.
> I use the app on windows 10.
> Can someone help me?
> ![pop corn](https://user-images.githubusercontent.com/85513484/121090076-6957af80-c7be-11eb-9b45-e88969ac6be5.jpg)

Did you install the dev build?
Only the dev build has an option to add custom servers to get the list to load properly.
Download the dev build and install it, open it and click the Settings icon at the top right corner in the UI.
Tick the box that says "Show advanced settings"
Scroll down until you see the part for API server.
Then copy and paste https://popcorn-ru.tk/ on all the fields and then scroll up to the top and click Save.
Now close the UI and open Popcorn Time again.
It works for me.

**Comment by losl2** [comment]
Thank you for your help @sailinggalaxians;
But for movie it worked with the link: https://yts.mx/
![image](https://user-images.githubusercontent.com/85513484/121258239-0b41cf80-c885-11eb-9c6a-dfb08b7008db.png)

**Comment by aldobelus0** [comment]
The address ci.popcorntime.app doesn't work, at least not for me today. You can obtain a package for your operative system, where include the address from ru.tk needed to load series and movies,  here:

https://popcorn-ru.tk/build/

;-)

**Comment by davidzuluaga5** [comment]
> > Doesn't load any content.
> > The app opens but does not load. I already uninstalled, installed and still does not load.
> > I use the app on windows 10.
> > Can someone help me?
> > ![pop corn](https://user-images.githubusercontent.com/85513484/121090076-6957af80-c7be-11eb-9b45-e88969ac6be5.jpg)
> 
> Did you install the dev build?
> Only the dev build has an option to add custom servers to get the list to load properly.
> Download the dev build and install it, open it and click the Settings icon at the top right corner in the UI.
> Tick the box that says "Show advanced settings"
> Scroll down until you see the part for API server.
> Then copy and paste https://popcorn-ru.tk/ on all the fields and then scroll up to the top and click Save.
> Now close the UI and open Popcorn Time again.
> It works for me.

HI, where is the dev build link to download? The official documentation mentiones the .app domain, which is down.. so it does not work.

**Comment by aldobelus0** [comment]
> The address ci.popcorntime.app doesn't work, at least not for me today. You can obtain a package for your operative system, where include the address from ru.tk needed to load series and movies, here:
> 
> https://popcorn-ru.tk/build/

I forgot to remind you the trick named at the code section of this repository. There, you are advertised that, if your Popcorn-Time doesn't start, you must install several packages more. 

http://i.imgur.com/siqOW3f.png

The packages are: `libatomic1 libgconf-2-4 libcanberra-gtk-module`

You must be working with a Debian/Ubuntu based distros, like I do. I have a Trisquel Etiona, an Ubuntu without proprietary software, and no access to them in its repositories, nor recommendations to install them anywhere at the system. A 100% free software system, saying it altogether…

And then, you put the repositories addresses of your preference in the window reserved to it. 

http://i.imgur.com/CEX9mrT.png

That's all! (If I didn't forget anything again!). Good luck!

**Comment by lordjack** [comment]
> 
> 
> > Doesn't load any content.
> > The app opens but does not load. I already uninstalled, installed and still does not load.
> > I use the app on windows 10.
> > Can someone help me?
> > ![pop corn](https://user-images.githubusercontent.com/85513484/121090076-6957af80-c7be-11eb-9b45-e88969ac6be5.jpg)
> 
> Did you install the dev build?
> Only the dev build has an option to add custom servers to get the list to load properly.
> Download the dev build and install it, open it and click the Settings icon at the top right corner in the UI.
> Tick the box that says "Show advanced settings"
> Scroll down until you see the part for API server.
> Then copy and paste https://popcorn-ru.tk/ on all the fields and then scroll up to the top and click Save.
> Now close the UI and open Popcorn Time again.
> It works for me.


It works for me with https://popcorn-ru.tk/. Thank you so much.

**Comment by iMansoorAliKhan** [comment]
https://popcorn-ru.tk/build/
this is not working any more.
Please provide updated link for movies and series

**Comment by dutchy1001** [comment]
@iMansoorAliKhan 
Link (https://popcorn-ru.tk/build/) still works for me. Download with no problem after clicking on the version you want. 
I do use a VPN (set to The Netherlands) so it could be due to your country's allow list of websites

**Comment by franco-ibanez** [comment]
> https://popcorn-ru.tk/build/
> this is not working any more.
> Please provide updated link for movies and series

Check your DNS, I had that problem too and it was solved by changing my DNS to 8.8.8.8 (Google)

**Comment by neotechgamer** [comment]
https://popcorn-ru.tk/ 
Not working anymore, please help

**Comment by franco-ibanez** [comment]
It is working for me ATM. Check your DNS

**Comment by kiriles90** [comment]
@neotechgamer Check if you can access the site in your browser. If not then its either that your ISP has blocked it, in which case a DNS change or a VPN will help bypassing the block, or its some temporary connectivity issue from your end to it (and anything in between). In either case both website and API of popcorn-ru.tk are up and working.

**Comment by neotechgamer** [comment]
I can
![image](https://user-images.githubusercontent.com/2421244/128722781-6db4870f-45fc-41aa-8a69-248bea7b7a6e.png)

**Comment by neotechgamer** [comment]
@kiriles90 I have access to the site, I get this error now
![image](https://user-images.githubusercontent.com/2421244/128924715-06152e0f-5a9c-4df1-ab53-27eeee6c5d59.png)

**Comment by dutchy1001** [comment]
@neotechgamer 
looks to me you need a vpn. This happens to me if I turn my VPN off

**Comment by neotechgamer** [comment]
> @neotechgamer
> looks to me you need a vpn. This happens to me if I turn my VPN off

do you have a preferred VPN, I was using PrivateVpn, but end up Crap not getting all the speed I needed

**Comment by dutchy1001** [comment]
It's all about what your budget allows (read wife/partner lol) you to spend. Mine comes with my newsnet provider so I have no experiance with other "payed" VPN's.

**Comment by kiriles90** [comment]
@neotechgamer You didn't change the API in the settings.. It says status.popcorntime.app meaning its trying to reach the (down for months now) official API. Also from the looks of it you aren't even using the latest version (0.4.5). Uninstall whatever version you have, install 0.4.5 from https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.5 start the APP and you'll see a similar screen as this with a change API button. Press it, it will take you in the relevant options in the settings and change the API(s) to one of the suggested ones.

**Comment by eddskt** [comment]
> > Doesn't load any content.
> > The app opens but does not load. I already uninstalled, installed and still does not load.
> > I use the app on windows 10.
> > Can someone help me?
> > ![pop corn](https://user-images.githubusercontent.com/85513484/121090076-6957af80-c7be-11eb-9b45-e88969ac6be5.jpg)
> 
> Did you install the dev build?
> Only the dev build has an option to add custom servers to get the list to load properly.
> Download the dev build and install it, open it and click the Settings icon at the top right corner in the UI.
> Tick the box that says "Show advanced settings"
> Scroll down until you see the part for API server.
> Then copy and paste https://popcorn-ru.tk/ on all the fields and then scroll up to the top and click Save.
> Now close the UI and open Popcorn Time again.
> It works for me.

08/10/2021 Working Fine, thanks for this solution!

**Comment by neotechgamer** [comment]
boom that did the trick THANK YOU, Just the ANIME is not working now

**Comment by Jany-M** [comment]
Anyone has an alternative for the **Series** API?
