### ISSUE TITLE
popcorntime doesn't start propperly. it continues to load

### ISSUE THREAD

**Issue by fitzchevalrick** [popcorntime/popcorntime#2106]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by DreadKnight** [comment]
Came here to look for this issue or ideally new release, sigh...
It gives the loading spinner for movies/series/anime for a day or two now I think...

**Comment by fitzchevalrick** [comment]
maybe someone on this platform can help us out here.

**Comment by kiriles90** [comment]
Check https://github.com/popcorn-official/popcorn-desktop/issues/2105. Closing since duplicate but you can comment in the other issue if you need more help.

**Comment by benkaiser** [comment]
@kiriles90 why was this closed?

**Comment by dutchy1001** [comment]
@benkaiser 
if you read the pinned topic #2105 you understand why this was closed

**Comment by kiriles90** [comment]
@benkaiser Its an issue with the API not the app, which is down due to legal issues. Its also duplicate of pinned #2105 like @dutchy1001 said.
