### ISSUE TITLE
Popcorn Time will not load completely, only get the spinning wheels of nothing

### ISSUE THREAD

**Issue by jimsuev** [popcorntime/popcorntime#2107]
![Screenshot 2021-04-20 170413](https://user-images.githubusercontent.com/63857454/115464087-89291900-a1fa-11eb-8e6e-394848d55fb4.jpg)

Operating System Version:
 Windows 10

Popcorn Time Version:
 4.4

Download date:
Reinstalled on  19 April 2021

Download url (optional):

#### Expected Behaviour
 Open 
...

#### Actual Behaviour
 Only loads to the spinning wheels of nothing.
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Same thing like I told you in the other issue. Check https://github.com/popcorn-official/popcorn-desktop/issues/2105.

**Comment by kiriles90** [comment]
Check https://github.com/popcorn-official/popcorn-desktop/issues/2105. Closing since duplicate but you can comment in the other issue if you need more help.
