### ISSUE TITLE
Hi I've been trying to load the content for hours now I have a windows 10 and a lot of space free also I am unable to open the site kindly help me out

### ISSUE THREAD

**Issue by LiamChanning** [popcorntime/popcorntime#2110]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4
Download date:
23rd february

Download url (optional):
https://mirror06.popcorntime.app/build/Popcorn-Time-0.4.4-win32-Setup.exe

#### Expected Behaviour
Open the series page and give search results
...

#### Actual Behaviour
None of the pages opened and it was stuck on load
#### Steps to reproduce the behaviour

I do not know I just opened the app and it just kept buffering

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/75932773/115517954-52f4a380-a2a5-11eb-8e8f-399b1fabbcab.png)

![image](https://user-images.githubusercontent.com/75932773/115518013-5ee06580-a2a5-11eb-8b32-7a5b295f4ebc.png)

**Comment by hbomb79** [comment]
I'm experiencing this issue as well; also running Windows 10 and downloaded using the 64-bit setup.exe found in the Releases (assets of v0.4.4)

**Comment by suji2763** [comment]
Same issue faced by me

**Comment by princessa12** [comment]
yep, same here, downloaded a new version today and still have that problem

**Comment by kiriles90** [comment]
Check https://github.com/popcorn-official/popcorn-desktop/issues/2105. Closing since duplicate but you can comment in the other issue if you need more help.
