### ISSUE TITLE
PCT app wont load

### ISSUE THREAD

**Issue by princessa12** [popcorntime/popcorntime#2111]
I know there are closed topics like this. but i have the latest version. 

PCT 0.4.4
HEAD 739ad0ac

wanted to know if it will be fixed alone or there is something i need to do in order to fix it

**Comment by kiriles90** [comment]
Check pinned https://github.com/popcorn-official/popcorn-desktop/issues/2105. Closing since duplicate but you can comment in the other issue if you need more help.
