### ISSUE TITLE
Problem loading the film and series film

### ISSUE THREAD

**Issue by ihameli** [popcorntime/popcorntime#2114]
Operating System Version:

OS X 11.2.3

Popcorn Time Version:

Version 0.4.4 (0.4.4)
Download date:

2021
Download url (optional):

#### Expected Behaviour

When it starts, it show the films or the series 

#### Actual Behaviour

It continues with a black window and the loading in progress gif image

#### Steps to reproduce the behaviour

1. Start a the application

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

Not error is displayed.

**Comment by kiriles90** [comment]
Check pinned https://github.com/popcorn-official/popcorn-desktop/issues/2105. Closing since duplicate but you can comment in the other issue if you need more help.
