### ISSUE TITLE
Doesn't load any content

### ISSUE THREAD

**Issue by HA1962** [popcorntime/popcorntime#2115]
from some days ago no way to connect movies or series in Australia

**Comment by diegogarciar** [comment]
Same here

**Comment by diegogarciar** [comment]
@HA1962 check #2114

**Comment by HA1962** [comment]
it does.t work either- I've installed 64 bits and upgrade
________________________________
De: kiriles90 ***@***.***>
Enviado: jueves, 22 de abril de 2021 01:09 p. m.
Para: popcorn-official/popcorn-desktop ***@***.***>
CC: HA1962 ***@***.***>; Mention ***@***.***>
Asunto: Re: [popcorn-official/popcorn-desktop] Doesn't load any content (#2115)


Closed #2115<https://github.com/popcorn-official/popcorn-desktop/issues/2115>.

**Comment by HA1962** [comment]
[cid:6cbaa018-4a32-4909-8b30-6e0f55d5fa58]
________________________________
De: kiriles90 ***@***.***>
Enviado: jueves, 22 de abril de 2021 01:09 p. m.
Para: popcorn-official/popcorn-desktop ***@***.***>
CC: HA1962 ***@***.***>; Mention ***@***.***>
Asunto: Re: [popcorn-official/popcorn-desktop] Doesn't load any content (#2115)


Closed #2115<https://github.com/popcorn-official/popcorn-desktop/issues/2115>.

**Comment by kiriles90** [comment]
@HA1962 go in the settings and set a 'Custom movies/series/anime server'. There are some set suggestions but any compatible API will work. If at any point you what to check what the default API is doing just clear the relevant text box and restart the app.

**Comment by HA1962** [comment]
no sorry no success
________________________________
De: kiriles90 ***@***.***>
Enviado: jueves, 22 de abril de 2021 01:15 p. m.
Para: popcorn-official/popcorn-desktop ***@***.***>
CC: HA1962 ***@***.***>; Mention ***@***.***>
Asunto: Re: [popcorn-official/popcorn-desktop] Doesn't load any content (#2115)


@HA1962<https://github.com/HA1962> go in the settings and set a 'Custom movies/series/anime server'. There are some set suggestions but any compatible API will work. If at any point you what to check what the default API is doing just clear the relevant text box and restart the app.

**Comment by kiriles90** [comment]
Works for everyone else so you must be doing something wrong. Just update to the latest build (458) go in the settings, set custom servers and restart the app.
