### ISSUE TITLE
Where can I get the new version of Popcorn Time?

### ISSUE THREAD

**Issue by BP2405** [popcorntime/popcorntime#2118]
I have been looking for the version mentioned in different threads, but I can't find it anywhere. I am referring to version 0.4.5. Does anyone know where I would be able to find it?

**Comment by dutchy1001** [comment]
version 0.4.5 doesnt exist yet. dev build 458 is the latest you should be able to find

**Comment by BP2405** [comment]
Where can I find build 458 then? Because I have the 044 version

**Comment by dutchy1001** [comment]
dev build 458 is also a 0.4.4 version with many updated features. I think it's mentioned in issue #2105 (the pinned one on top) how to get it.

**Comment by BP2405** [comment]
I found it thanks for the help, I am sorry for the inconvenience

**Comment by diegogarciar** [comment]
@BP2405 where was it?

**Comment by dutchy1001** [comment]
@diegogarciar 
Please read issue #2105 and you will find answers there.
