### ISSUE TITLE
It's not loading

### ISSUE THREAD

**Issue by Tati-Fidelis** [popcorntime/popcorntime#2119]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...Not loading movies and series
2. ...When I was uploading and showing the catalog of films and series, I couldn't watch some episodes because they didn't even load or show up on the screen

**Comment by kiriles90** [comment]
Check pinned issue #2105. Closing this since duplicate but feel free to comment in the other issue if you need any help.
