### ISSUE TITLE
popcorn time doesnt load

### ISSUE THREAD

**Issue by PropTopper** [popcorntime/popcorntime#2120]
i try to go either to series or to movies and neither of them load it just keeps playing the loading animation for an indefinite time

and its not the internet ive tried different sources of internet and none of them work every other thing that requires internet works perfeclty othee than this one  my pc is windows 10 home 64 bit

**Comment by kiriles90** [comment]
Check pinned issue #2105. Closing this since duplicate but feel free to comment in the other issue if you need any help.
