### ISSUE TITLE
popcorn dev broke

### ISSUE THREAD

**Issue by riclas** [popcorntime/popcorntime#2121]
ran a regression test on the dev build on windows 10
commit  8b2ef81369f1b3f377045ed54069e39163e942ff broke the dev runtime. screen shows grey and doesn't load
@ivan1986 could you take a look?

**Comment by ivan1986** [comment]
do you run yarn install after switch? because last build correct work on win10 - tested many times

**Comment by riclas** [comment]
no, simply build and start

**Comment by ivan1986** [comment]
in this commit lib updated, need `yarn install` befor build

**Comment by riclas** [comment]
yeah, my bad. thanks for looking into it
