### ISSUE TITLE
Popcorn Time Not Working

### ISSUE THREAD

**Issue by FrenchTomatoPotato** [popcorntime/popcorntime#2124]
Guys, sorry if this has already been discussed before but im new to github and just want an answer. I've downloaded popcorn and used it for the past 1-2 years without issue but for some reason, pt is loading indefinitely and is not showing me anything (My version is 0.4.4). People have suggested to use https://popcorn-ru.tk/ but this does not update tv shows like the one i am used to using. Is there a way that I can go back to the way it was. And does anyone know how long it will take for the default api to work?

Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
> Is there a way that I can go back to the way it was.  

Not unless the default API goes online again or you know some other one that doesn't have whatever is the issue you're having with the RU API

> And does anyone know how long it will take for the default api to work?

No, but should be soon-ish enough
