### ISSUE TITLE
I cant uninstall popcorn time

### ISSUE THREAD

**Issue by moretmeul** [popcorntime/popcorntime#2125]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

... I try to uninstall from settings 

#### Actual Behaviour

... launches download folder only, doesnt uninstall the programe

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Operating system? Popcorn Time version?
Closing this since its not an issue with the app but comment below with some details if you still need help.

**Comment by moretmeul** [comment]
Windows 10,
version 0.4.4
 
yes i need help with trying to uninstall the app, it wont let me

**Comment by kiriles90** [comment]
Restart your device, go to `%localappdata%` find the `Popcorn-Time` and delete it then go to Apps & features and uninstall it. It might say 'files missing..etc do you want to remove this entry' click yes and you are done.

**Comment by moretmeul** [comment]
when i click unistall it opens my download folder and popcorn is still there

**Comment by kiriles90** [comment]
I dont understand what you mean.. post a screenshot.

**Comment by moretmeul** [comment]
![image](https://user-images.githubusercontent.com/83128475/115966717-c0fbcd80-a526-11eb-82c4-c0db3e21307c.png)


I dont know how to explain it further. Upon pressing unistall in the settings it just opens the downloads folder (same folder where i downloaded popcorn) it doesnt do anything else, popcorn is still there and if i repeat it does the same thing again

**Comment by kiriles90** [comment]
I don't see Popcorn Time in that folder? Did you do what I told you in the step above? If yes, its uninstalled, its just the registry entry remaining for the uninstaller for some reason. You can remove it with a registry cleaner or an easier solution install Popcorn Time again in its default location (not in D:\Downloads..) and uninstall it.

**Comment by dutchy1001** [comment]
Go to your "USERNAME"\AppData\local\Popcorn-Time. If the folder exist then uninstall from there. If there isn't a folder called Popcorn-Time you reinstall PCT and then use the uninstaller in that folder.
If you used a "different" location for install you have to go there.
Do not use the "Apps & features" from windows 10, this will only open a folder location or in some cases the Control Panel/Programmes & Features.
