### ISSUE TITLE
Nothing Loads

### ISSUE THREAD

**Issue by NumberUNO1** [popcorntime/popcorntime#2129]
Operating System Version:
Mac OS Catalina 10.15.7

Popcorn Time Version:
v0.4.4

Download date:
~4 months ago

>

#### Expected Behaviour
Movies, Series etc to load
...

#### Actual Behaviour
Nothing happens at all in Movies, Series etc. Stuck in loading loop and keeps trying to load
...

#### Steps to reproduce the behaviour
Downloads same version of Popcorn time
Open app

**Comment by Superbal00** [comment]
Stuck also

**Comment by dutchy1001** [comment]
please read the pinned topic #2105 

Duplicate issue

**Comment by Mardak62** [comment]
Hello, Solutions in #2105 also stopped partially working. The Database in https://popcorn-ru.tk/ are 2 weeks old and they have not beed updated in two weeks.

**Comment by dutchy1001** [comment]
@Mardak62 
Posting the same text in different issue's is not gonna help and only will be annoying. 
The API's used to "fetch" the databases are NOT controlled by the dev team here therefor there is nothing we can do.

**Comment by Mardak62** [comment]
Apologies!
     On Sunday, April 25, 2021, 12:38:38 PM EDT, dutchy1001 ***@***.***> wrote:  
 
 


@Mardak62
Posting the same text in different issue's is not gonna help and only will be annoying.
The API's used to "fetch" the databases are NOT controlled by the dev team here therefor there is nothing we can do.
