### ISSUE TITLE
not loading anything

### ISSUE THREAD

**Issue by love0354** [popcorntime/popcorntime#2130]
when i start popcorn time it does not load anything i tried everything, but issue is not fixed. what should i do now ?

**Comment by dutchy1001** [comment]
please read the pinned topic #2105 

duplicate issue

**Comment by NumberUNO1** [comment]
@dutchy1001  Hello - i followed the steps and updated API servers, however, some shows like shark tank have missing episodes e.g. it was up to date as of last week. Please help

**Comment by dutchy1001** [comment]
The original API has been taken offline due to legal reasons which non of us can do anything about.
As you are using a different API then the original from PCT the results what it finds can be different then, which again we can't do anything about.

**Comment by Mardak62** [comment]
Hello, Solutions in #2105 also stopped partially working. The Database in https://popcorn-ru.tk/ are 2 weeks old and they have not beed updated in two weeks.
