### ISSUE TITLE
not loading the movie content or anything

### ISSUE THREAD

**Issue by bigfrog** [popcorntime/popcorntime#2131]
for the last couple days I tried continuous but the content does not load ..

**Comment by dutchy1001** [comment]
duplicate issue

Not even gonna explain no more as ppl do not read

**Comment by Mardak62** [comment]
Hello, Solutions in #2105 also stopped partially working. The Database in https://popcorn-ru.tk/ are 2 weeks old and they have not beed updated in two weeks.

**Comment by kiriles90** [comment]
@Mardak62 The ru API database updates daily. If that doesnt work for you use the yts one.
