### ISSUE TITLE
Unable to download through HomeBrew

### ISSUE THREAD

**Issue by Dylan-Bollard** [popcorntime/popcorntime#2134]
Operating System Version:

OS X 10.15.7

Popcorn Time Version:

Was trying to download version 0.4.4.

Download date:

Haven't been able to install yet.

Download url (optional):

Did not download. 

#### Expected Behaviour

I thought it was going to install with Homebrew. 

#### Actual Behaviour

~~~
dylan@dylan ~ % brew install --cask popcorn-time
==> Downloading https://get.popcorntime.app/build/Popcorn-Time-0.4.4.pkg
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.  
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.  
##O=#  #                                                                      
curl: (6) Could not resolve host: get.popcorntime.app
Error: Download failed on Cask 'popcorn-time' with message: Download failed: https://get.popcorntime.app/build/Popcorn-Time-0.4.4.pkg
~~~

#### Steps to reproduce the behaviour

1. I would imagine you would try downloading. 

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

[popcorn.pdf](https://github.com/popcorn-official/popcorn-desktop/files/6375313/popcorn.pdf)

**Comment by kiriles90** [comment]
The website has been taken down. Check issue #2105

**Comment by lavelle96** [comment]
I'm experiencing the same issue... is there a known fix for this?

**Comment by kiriles90** [comment]
Its because .app is down, Wait until https://github.com/popcorn-official/popcorn-desktop/pull/2215 is merged and try again.

**Comment by hzandi** [comment]
I have same issue.. Homebrew 3.2.9 and macOS Catalina 10.15.7
