### ISSUE TITLE
Keyboard shortcut for search does not work after switching tab

### ISSUE THREAD

**Issue by Mystery2002** [popcorntime/popcorntime#2139]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.4.4-win64-Setup

Expected Behaviour
Should be able to open the search box with the keyboard shortcut: ctrl-f

Actual Behaviour
Nothing happens.

Steps to reproduce the behaviour
Switch tabs by either clicking on "series", "anime", etc. or use the shortcut ctrl-2. 
The search bar will then not open up with the ctrl-f shortcut.

Is a minor issue but since I use Unified Remote, it would be convenient to have this working.

**Comment by dutchy1001** [comment]
I can confirm this bug too

**Comment by kiriles90** [comment]
Fixed. Thank you for reporting.
