### ISSUE TITLE
Feature Request: change database location

### ISSUE THREAD

**Issue by radujica** [popcorntime/popcorntime#214]
Operating System Version: Windows 10
Popcorn Time Version: 0.4.1-2
Download date: 26.07.2016
#### Expected Behaviour

Be able to select where you want your favorites (folder) to be stored so that it can be synced across multiple devices using e.g. Dropbox.
#### Actual Behaviour

Not possible.
#### Steps to reproduce the behaviour
1. Click Settings
2. Check advanced options
3. Scroll down to database
4. Click path to select another -> not possible

Note that it works to select the temporary download folder by clicking the path, just not the database folder.

**Comment by Breaking1** [comment]
I think you are in the wrong place, the version supported here comes from https://popcorntime.sh and the version number should be 0.3.9

**Comment by radujica** [comment]
@Breaking1 Thought it is the .ag. My apologies.
