### ISSUE TITLE
popcorn not loading pages at all

### ISSUE THREAD

**Issue by Nebukanazer** [popcorntime/popcorntime#2140]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date: 29.10.2020.

Download url (optional):

#### Expected Behaviour

Open Movies/series/favourites

#### Actual Behaviour

did not open Movies/series/favourites

#### Steps to reproduce the behaviour

1. Start popcorn from "Start" menu
2. Main window opens and loading starts
3. nothing is loaded

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/76470884/116355075-a0b76180-a7f9-11eb-98c7-5d7a7982061e.png)
![image](https://user-images.githubusercontent.com/76470884/116355118-ae6ce700-a7f9-11eb-934d-7318403f76c1.png)
![image](https://user-images.githubusercontent.com/76470884/116355139-b62c8b80-a7f9-11eb-840a-30573f9b280e.png)
![image](https://user-images.githubusercontent.com/76470884/116355161-be84c680-a7f9-11eb-944e-2ac1febc1575.png)

**Comment by kiriles90** [comment]
Check pinned issue #2105
