### ISSUE TITLE
Not loading moview or tv series

### ISSUE THREAD

**Issue by DomnicAmalan** [popcorntime/popcorntime#2144]
Operating System Version:
OS X 10.11

Popcorn Time Version:
0.4.4

Download date:
29/04/2021

Download url (optional):
macupdate

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Check pinned issue #2105
