### ISSUE TITLE
Popcorn time is not loading any movies

### ISSUE THREAD

**Issue by rech2yogesh** [popcorntime/popcorntime#2146]
Operating System Version:

WIndows 10

Popcorn Time Version:

4.4

Download date:

Yesterday

Download url (optional):

https://popcorn-time.en.uptodown.com/windows

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by rech2yogesh** [comment]
![image](https://user-images.githubusercontent.com/83526505/116801791-84cdfb80-ab2a-11eb-91ef-9193ef30fbe9.png)

Tried uninstalling and deleting all the files and reinstalling them but still no use. issue still persists.

**Comment by dutchy1001** [comment]
Please read issue #2105 (pinned on top)
