### ISSUE TITLE
None of the movies are loading. 

### ISSUE THREAD

**Issue by Po05buzo** [popcorntime/popcorntime#2147]
Operating System Version:
iOS 11.2.3

Popcorn Time Version:
0.4.4

Download date:
10 April 2021 at 2:28 PM

Download url (optional):
https://doc-10-6o-docs.googleusercontent.com/docs/securesc/3odig62hvgn5sotqk8i6an5th113a6qa/ob05gu4tss6nkr5buusvg2qt1p68mkb5/1618045050000/06992595133864305089/06992595133864305089/1rpOgvz_FszS3flJEVuhKF02YLZODc-rd?e=download&authuser=1&nonce=vet1f9hrmrnj0&user=06992595133864305089&hash=q5pcgblbl4k0pqva24hhgcuav25ts09s

![Screenshot 2021-05-02 at 12 52 50 PM](https://user-images.githubusercontent.com/83531254/116805636-645f6a80-ab45-11eb-98b5-46a6f30850b5.png)

**Comment by dutchy1001** [comment]
Please read issue #2105 (pinned on top)
