### ISSUE TITLE
doesn't load

### ISSUE THREAD

**Issue by naomixquackson** [popcorntime/popcorntime#2148]
Operating System Version:

Popcorn Time Version:

0.4.4
Download date:

idk like a year ago and i rea installed it last week friday
Download url (optional):

#### Expected Behaviour

...
let me watch movies without having to pay
#### Actual Behaviour

...
well, it doesn't want to load anymore
#### Steps to reproduce the behaviour

1. ... open popcorn time
2. ... watch how keeps loading.. forever and ever..
3. ... give up and close popcorn time

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

i don't have a screenshot but it's just the loading screen that keeps loading

**Comment by dutchy1001** [comment]
FFS can nobody read a PINNED topic??????
