### ISSUE TITLE
Not Loading thumbnails just spinning 

### ISSUE THREAD

**Issue by neotechgamer** [popcorntime/popcorntime#2149]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.4.4-win32-Setup

Download date:
March 2021

#### Expected Behaviour
load all movies Thumbnails and access to movies

#### Actual Behaviour
not loading, just a spinning wheel 
...

#### Steps to reproduce the behavior
Double click icon

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) ![image](https://user-images.githubusercontent.com/2421244/116841802-81bd2480-ab97-11eb-9ae4-80f29e31ddc2.png)

**Comment by Joshua-Twente** [comment]
You have to go to settings custom movie server, change it to
 https://popcorn-ru.tk/

**Comment by dutchy1001** [comment]
Please read the pinned issue #2105 

ffs
