### ISSUE TITLE
app quits unexpectedly, then win7 reboots

### ISSUE THREAD

**Issue by jonjamcam** [popcorntime/popcorntime#215]
Operating System Version:
Windows 7 x64 4Gb memory no memory swap file

Popcorn Time Version:
0.3.9

Download date:
2016-7-27
#### Expected Behaviour

should play the whole movie (batman begins 2005) 
...
#### Actual Behaviour

first time the app just quit around 1h32m. Launched again then my system rebooted when movie was about 2h
#### Steps to reproduce the behaviour
1. launch app
2. search for "batman begins 2005 movie 720p"
3. watch in full screen mode. make sveral pauses for a snack :smile: 

4.- at some point past 1h30m the app could quit or reboot windows.

I really don't know if the movie has a bug.

Some additional info: I do not use a swap file for virtual memory and the app is constantly eating up all my resources.  It starts using about 200 MB but this amount is always increasing and decreasing using at least 300 MB most of the time. It's just a matter of time until it gets to the 2GB limit I have.

should it use so much memory?

I wasn't monitoring my resources when this happened. I'll pay more attention in the future.

Cheers.

**Comment by ChrisAlderson** [comment]
Cannot reproduce
