### ISSUE TITLE
Can't compile source code

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#2153]
Operating System Version:
Windows 10

Popcorn Time Version:
Latest development branch

Download date:
Mai 4th 2021

Hello Guys.
As your application doesn't work anymore 
Nothing in Movie, TV Shows or Anime and nothing from Torrent Collections search,
I try to download and compile latest development branch.

I tried to follow your instructions to compile and start:
when I run "yarn build":
I get this error:

> $ gulp build
> (node:46748) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:46748) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:46748) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> (node:46748) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (node:46748) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:46748) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> [17:50:01] Using gulpfile D:\MediaTools\popcorn-desktop\gulpfile.js
> [17:50:01] Starting 'build'...
> [17:50:01] Starting 'injectgit'...
> Branch: development
> Commit: aa8b8b07
> [17:50:01] Finished 'injectgit' after 55 ms
> [17:50:01] Starting 'css'...
> Stylus files compiled in D:\MediaTools\popcorn-desktop\src\app\themes\
> [17:50:06] Finished 'css' after 4.17 s
> [17:50:06] Starting 'nwjs'...
> Error: Command failed: npm ls --production=true --parseable=true
> npm ERR! code ELSPROBLEMS
> npm ERR! invalid: webtorrent@0.118.0 D:\MediaTools\popcorn-desktop\node_modules\webtorrent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\vrith\AppData\Local\npm-cache\_logs\2021-05-04T15_50_08_050Z-debug.log
> 
>     at ChildProcess.exithandler (node:child_process:326:12)
>     at ChildProcess.emit (node:events:365:28)
>     at ChildProcess.emit (node:domain:532:15)
>     at maybeClose (node:internal/child_process:1067:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
>     at Process.callbackTrampoline (node:internal/async_hooks:131:17) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: 'npm ls --production=true --parseable=true'
> }
> Error: getaddrinfo EAI_AGAIN popcorntime.app
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)
>     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:131:17) {
>   errno: -3001,
>   code: 'EAI_AGAIN',
>   syscall: 'getaddrinfo',
>   hostname: 'popcorntime.app'
> }
> [17:50:27] Finished 'nwjs' after 21 s
> [17:50:27] Starting '<anonymous>'...
> [17:50:27] Finished '<anonymous>' after 527 μs
> [17:50:27] Finished 'build' after 25 s

**Comment by kiriles90** [comment]
Hi, its because popcorntime.app is down and it fails to get the custom nwjs build. Check Ivan's reply to https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830823755

**Comment by TSTsankov** [comment]
1 - Update the gulpfile.js
https://github.com/popcorn-official/popcorn-desktop/compare/development...popcorn-time-ru:nw-location
2 - npm install
3 - npm build
4 - npm start
5 - update the api server url
