### ISSUE TITLE
Subtitles size on mac version

### ISSUE THREAD

**Issue by LuluLCZ** [popcorntime/popcorntime#2156]
Hi there, i’m running popcorn time on mac os big sur and it seems that the changes made to the subtitles in the settings are not applied. 
Step to reproduce : i change the size in settings it doesn’t change the size in the movie, is that me doing something wrong ?

Version: latest download on popcorn time website 
Mac Os big sur

**Comment by kiriles90** [comment]
> Version: latest download on popcorn time website

Which website/version would that be?

**Comment by dutchy1001** [comment]
The web version is way outdated compared to the latest dev builds (I presume you downloaded it before the takedown). 
If you read in issue #2105 (pinned on top) you will find some solutions to update your version, also take note of the "not loading issue" and how to solve that then.

**Comment by LuluLCZ** [comment]
Oh okay sorry i’ll do that right away thanks and sorry for the duplicate.

**Comment by dutchy1001** [comment]
I only mentioned issue #2105 as there is a solution to get an updated version that might fix the subtitle issue you have.

I don't class this as a duplicate issue.

**Comment by LuluLCZ** [comment]
Ok i’ll just get the updated version when i can and if indeed it resolves it then i will close the issue

**Comment by kiriles90** [comment]
@LuluLCZ can you post a screenshot of your version since it was never mention what you're actually using?
