### ISSUE TITLE
Option to stream to tv no longer available

### ISSUE THREAD

**Issue by NumberUNO1** [popcorntime/popcorntime#2158]
Operating System Version:
Mac OS Big Sur 11.3.1

Popcorn Time Version:

Download date:
v0.4.4

>

#### Expected Behaviour
Ability to stream from Macbook to Samsung TV
...

#### Actual Behaviour
When i click on 'Watch Now' > i only see options for VLC and Popcorn time, there is no longer an option to stream to TV  
 
Can you please help? Thanks

**Comment by kiriles90** [comment]
Nothing related to this was changed in the app. Whatever the issue is its on your end. Anything that you might have changed that caused it? Do you use a VPN?

**Comment by NumberUNO1** [comment]
I dont use VPN. The only  major change my end has been upgrading to Big Sur. Before this, everything worked well.

Any ideas please?

**Comment by NumberUNO1** [comment]
@kiriles90 Needed to adjust Security & Privacy. Thanks for replying

**Comment by kiriles90** [comment]
Nice, thank you for reporting back the solution in case anyone else has the same issue.

**Comment by danielbayley** [comment]
@NumberUNO1 I have the same problem… Did you resolve it?
