### ISSUE TITLE
after system os update problems with Buffer.alloc()

### ISSUE THREAD

**Issue by jorigel** [popcorntime/popcorntime#2159]
Hi,
popcorn desktop refuses to show content while turning the spindle. Started in terminal shows following error:

DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Is there a function used in the program that is meanwhile depricated?

test surrounding is:
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Thanks for Your attention

**Comment by kiriles90** [comment]
Have you checked the pinned issue, updated, and set a custom API?

**Comment by jorigel** [comment]
Hi,
I'm not that much into details as Your are obviously. I followed what was mentioned in the 'readme' like :

sudo apt install libatomic1 libgconf-2-4 libcanberra-gtk-module
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libatomic1 ist schon die neueste Version (10.2.0-5ubuntu1~20.04).
libcanberra-gtk-module ist schon die neueste Version (0.30-7ubuntu1).
libgconf-2-4 ist schon die neueste Version (3.2.6-6ubuntu1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

to insure the dependencies and I reinstalled the latest version of the software  as far as I concern.

If this is not what You meant, I would please You to put me more detailed onto the track.
. . . a pinned issue is for me a forum post stuck to the top of the list without being overwritten  by newer posts. Obviously a fault of mine because I did not notice something like that. I read a lot, but unfortunately couldn't find anything to this theme.

Thanks for trying to help me

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/2105 this one, its pinned on the top of the issues list.

In short, the .app domain got taken down a month ago, you'll need to update to the latest build. Meaning version 0.4.4 build 458 not release version 0.4.4 aka build 413. Follow the links in the post I mentioned above. Then after you've installed it go in the settings and set a custom API. (you can use any of the pre-set ones or if you know/or setup any other compatible one that will also work)
