### ISSUE TITLE
Not loading files from Zamunda.net

### ISSUE THREAD

**Issue by lZzozZl** [popcorntime/popcorntime#216]
Operating System Version:
Windows 7 Ultimate 64-bit

Popcorn Time Version:
0.3.9-0 (90e3fc19)

Download date:
1 min before i write this post
#### Expected Behaviour

Play torrents from Zamunda.net
#### Actual Behaviour

Stays in Resolving...
#### Steps to reproduce the behaviour

1. Make a registration in Zamunda.net ( i think now you can use it free up to 3 torrent downloads )
2. Pick a movie.
3. Drag and drop torrent link or magnet link over Popcorn

**Comment by TheSparrowLenz** [comment]
This happens with several other torrent providers. The magnet links don't get parsed correctly and when they do, it doesn't go past the screen 'connecting'.
