### ISSUE TITLE
0.4.4 deletes everything in install folder

### ISSUE THREAD

**Issue by popcorntimebug** [popcorntime/popcorntime#2161]
Operating System Version:
Windows 10.0.19042.0

Popcorn Time Version:
Release 0.4.4

Download date:
20210512

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.4/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
Uninstall nothing as no popcorn time files are present in the folder, then install popcorn time in the folder specified OR
Uninstall the previous installation of popcorn time at a different file path, then install popcorn time in the folder specified.

#### Actual Behaviour
Started deleting everything in the directory I pointed it at, that accidentally being my user folder, thankfully starting with irrelevant files and folders (.m2) and not My Documents or AppData

#### Steps to reproduce the behaviour

1. Install popcorn time somewhere proper.
2. Point it at a directory with popcorn time _not_ installed in it i.e. $UserProfile$\definitely_a_test_folder with stuff in it.
3. The uninstaller will apparently delete everything.

**Comment by dutchy1001** [comment]
If you dont give popcorntime a separate folder to install it will delete all what is in that folder. Any program that needs to be installed needs it's own folder it can NOT be in a "shared" folder with other files/programs.

There has been a previous topic about this and I will try and find it then edit this post with a link.

**Comment by dutchy1001** [comment]
the issue were this is explained is #1579
