### ISSUE TITLE
its not loading any progams or shows

### ISSUE THREAD

**Issue by Miguelcastel121** [popcorntime/popcorntime#2162]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by leenpaws** [comment]
same issue
popcorn-time verison: .44(latest release
download date: 5/14
expected behavior: load stuff
actual behavior: loads nothing
steps to reproduce: download master branch, yarn-> yarn start using nvm and version 10.18.0 also same issue with v12

**Comment by dutchy1001** [comment]
read the pinned issue #2105
