### ISSUE TITLE
loads nothing

### ISSUE THREAD

**Issue by leenpaws** [popcorntime/popcorntime#2163]
Operating System Version:
linux v 20

Popcorn Time Version:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

same issue
popcorn-time verison: .44(latest release
download date: 5/14
expected behavior: load stuff
actual behavior: loads nothing
steps to reproduce: download master branch, yarn-> yarn start using nvm and version 10.18.0 also same issue with v12

**Comment by leenpaws** [comment]
solved in pinned issue by changing api server

**Comment by NIU1526414** [comment]
how do you change the api server?

**Comment by dutchy1001** [comment]
There is a setting in the settings tab for this. 
If it's not there you got an older build were it hasn't been implemented. In the pinned topic #2105 are solutions to get the latest dev build and an API that can be used.
