### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by redkurn** [popcorntime/popcorntime#2165]
running the sh, it fails to build.

Operating System Version:
Debian 10

Popcorn Time Version:
git clone

#### Expected Behaviour
build

#### Actual Behaviour
fail

#### Steps to reproduce the behaviour

1. run the sh file

**Comment by dutchy1001** [comment]
due to some pages that have been taken down it will not build properly, nothing we can do about ATM.

**Comment by kiriles90** [comment]
Check Ivan's reply to https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830823755
