### ISSUE TITLE
Sort by note not working

### ISSUE THREAD

**Issue by MecMada** [popcorntime/popcorntime#2167]
Operating System Version:
Windows10

Popcorn Time Version:
0.4.4

Download date:
16/05/2021

Download url (optional):
http://popcorn-ru.tk/build/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
When sorted by note, the first film should have the best note.

#### Actual Behaviour
When sorted by note, I have "The fast and Furious Tokyo Drift" in choice 1 (6.3/10 IMDb note) and "Blood diamond" in choice 2 (7.5/10 IMDb score)

#### Steps to reproduce the behaviour
Sort by note

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) 
![image](https://user-images.githubusercontent.com/66328163/118392320-5d525500-b639-11eb-8352-2dc10d740acd.png)

**Comment by dutchy1001** [comment]
As far I know this is a different fork from Popcorn-time (looking at your link). It can use the same API's only.
The dev from .ru.tk is active here but I presume you need to make an issue at his own repo for a fix.

**Comment by kiriles90** [comment]
What @dutchy1001 said. Open an issue in the RU API repo or use a different API for movies (e.g YTS)

**Comment by kiriles90** [comment]
That's the latest official build (458) that the RU fork hosts temporarily but for the rest what @dutchy1001 said.
Its an API issue. Open an issue in the RU API repo or use a different API for movies (e.g YTS)
