### ISSUE TITLE
no stream url  while downloading

### ISSUE THREAD

**Issue by ravish0007** [popcorntime/popcorntime#2169]
Operating System Version: Linux, Debian 10 Buster

Popcorn Time Version: 0.4.4

Download date: May-2021 

Download url: http://popcorn-ru.tk/build/Popcorn-Time-0.4.4_linux64.zip

Actual Behavior:
When downloading is in progress, stream url is missing.

The stuff works just fine in my local workstation running arch linux. I'm able to see stream url. What i'm trying to achieve is that, streaming from a cloud computer.
Specifically,  I install novnc to google cloud shell, (https://gist.github.com/ravish0007/c9884cdd90e8cc2ffaacacd658cc05d8).
after getting started, I'm unable to see stream url in remote computer. help me to fix this.

**Comment by kiriles90** [comment]
That's your local IP. So the stream url is a local url. It will only work on devices on the same network. Not sure how you can make it available outside your network but it would surely require replacing the local IP with your public IP and probably also opening/forwarding those ports at your router.

**Comment by ravish0007** [comment]
@kiriles90  Totally  !!!
I made a video on explaining my issue. some  trouble while playing video on browser. I request you to watch it and possibly we might fix it. Thanks

https://youtu.be/lHXgltBiPkU

**Comment by ravish0007** [comment]
I used Firefox and it was able to stream properly. Thanks.
