### ISSUE TITLE
Chromecast streaming not starting

### ISSUE THREAD

**Issue by alexpouliquen** [popcorntime/popcorntime#217]
Operating System Version:
Windows 10

Popcorn Time Version:
3.9.0

Download date:
today
#### Expected Behaviour

Playing movie on chromecast 
#### Actual Behaviour

nothing launch on chromecast

Hello,

I launch streming to my chromecast on popcorn-time and my chromecast do nothing. On your software it display a progress bar (empty) information about the movie and the controlers.
I tried with many differents video and not a single work :(. My chromecast is up to date and I have a great internet connection (I can watch the movie on my laptop).

If you want I can clone the repo and tried to debug that (do the code is minified on packaged app ?).

**Comment by GuilleDF** [comment]
I get the same on 64-bit linux with a samsung smart TV, not sure if it's related

**Comment by ChrisAlderson** [comment]
Try the latest build at ci.popcorntime.sh
