### ISSUE TITLE
nothing is loading

### ISSUE THREAD

**Issue by joshuasol** [popcorntime/popcorntime#2170]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by joshuasol** [comment]
![image_2021-05-18_21-44-46](https://user-images.githubusercontent.com/80572448/118706667-52a6e400-b822-11eb-9326-fdf4741379f0.png)
it's been doing this for at least 15 min

**Comment by kiriles90** [comment]
Check the pinned issue (#2105) and update to the latest build (0.4.4-458) then change the API urls in the settings.
