### ISSUE TITLE
Latest build website is down

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#2171]
The [website](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastSuccessfulBuild/) from the README pointing to the latest dev build is down.

**Comment by dutchy1001** [comment]
it's been down for over a month due to legal issue's

**Comment by kiriles90** [comment]
Check the pinned issue (#2105)

**Comment by kiriles90** [comment]
No new official website atm so nothing to point to for now. We wait and see.

**Comment by rebroad** [comment]
@kiriles90 We need to keep at least one issue open regarding this, and have all other issues raised (in error) pointing to it, otherwise issues will keep being opened.

**Comment by dutchy1001** [comment]
@rebroad
there is a pinned topic (#2105) on the top of the issue page that explains about this and some workaround solutions for a long time already. If ppl are to lazy to read or research a bit further then their nose is long they dont need to open new issue's about it.

No need to go through all closed issue's
