### ISSUE TITLE
Movies don't loading, server down??

### ISSUE THREAD

**Issue by her4z** [popcorntime/popcorntime#2172]
Hey, I've been trying to use the popcorn's desktop software for a few days and it keeps getting stuck when loading the movies list, I've tried a clean re-install of the last version available and also searching the movies and changing between categories in case it was a bug but none of these things worked. 
I looked up the recent issues to see if someone it's having the same problem as me but nothing. I'm starting to think that the project was thrown away and it just stops being maintained because the web pages are also down. Any information is well received.

Operating System Version:
Windows 10 64 bits

Popcorn Time Version:
v0.4.4

Download date:
19th May 2021

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.4

The issue:
https://user-images.githubusercontent.com/55901563/118799141-c70a7300-b874-11eb-9d00-317376596a09.mp4

**Comment by syedusmanali** [comment]
Same thing happening for me for more than a month now.
Looks like the website is down as well https://popcorntime.app/ , i have tried accessing the website with VPN for several countries and it didn't load for any.

**Comment by dutchy1001** [comment]
maybe read the pinned topic #2105

**Comment by syedusmanali** [comment]
Basically use the latest build which you can download from here => https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.4
Once the installation is done add this https://popcorn-ru.tk/ in Settings=>API Servers => Custom Movie Server

**Comment by mandeep-vratesh** [comment]
I am facing the same with v0.4.4

@syedusmanali I don't see that option even after enabling advanced settings.
![image](https://user-images.githubusercontent.com/17480259/118857021-358f1580-b8f5-11eb-8286-365cd94af565.png)

**Comment by dutchy1001** [comment]
If the custom server API setting isn't in the settings tab then you have an older version. It should just be above "Miscellaneous" section

**Comment by mandeep-vratesh** [comment]
@dutchy1001 Not even in Misc
![image](https://user-images.githubusercontent.com/17480259/118857232-7129df80-b8f5-11eb-987e-e67784a5f5df.png)
![image](https://user-images.githubusercontent.com/17480259/118857566-cfef5900-b8f5-11eb-990d-5dae3605e864.png)

**Comment by dutchy1001** [comment]
Like I said "it should be ABOVE" Miscellaneous (with a separate header).
Clearly it's not there so you have an older version and need to update to the latest dev build. There are some links in the pinned topic how to get that latest version.

![API](https://user-images.githubusercontent.com/5569980/118857951-84768400-b8d0-11eb-9064-76ab3936591d.png)

**Comment by mandeep-vratesh** [comment]
@dutchy1001 My bad. But above Misc I see "Database", "Cache Directory", "Connection", "Remote Control" etc options but not "API Server". I tried both windows 32-bit and 64-bit of v0.4.4. I tried using installer and downloading zip version as well.

**Comment by kiriles90** [comment]
Everyone read the pin post please.. you are all downloading the old release version 0.4.4 (build 413, master branch) from last year, not the latest build 0.4.4 build 458 everyone is saying to do. (dev branch, up to the point of the specific build)  

You can download either from popcorn-ru.tk/build, or from github.com/popcorn-official/popcorn-desktop/actions/runs/709245154 or you can build it urself by changing the nwjs location in the gulp file to a valid one (e.g github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830843524). P.s you can also ofc use the official nwjs location to build but you are missing on the proprietary codecs that arent enabled in that

**Comment by her4z** [comment]
> Everyone read the pinned issue please (#2105).. You are downloading the old release version 0.4.4 (build 413, master branch) from last year, not the latest 0.4.4 build 458 everyone is saying to do. (dev branch, up to the the specific build/commit)
> 
> You can download either from [popcorn-ru.tk/build](http://popcorn-ru.tk/build/) or from [github.com/popcorn-official/popcorn-desktop/actions/runs/709245154](https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154) or you can build it urself by changing the nwjs location in the gulp file to a valid one (e.g [github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830843524](https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830843524) or ofc the official nwjs location -up to version 0.49 afaik- but you'll be missing on the extra proprietary video codecs that [arent enabled in the prebuild nwjs binary](https://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs-in-nwjs))

Thanks mate, crystal clear!
