### ISSUE TITLE
Will not load anything?

### ISSUE THREAD

**Issue by Disastra** [popcorntime/popcorntime#2173]
For several days now the app simply never loads anything even when left for ages. The loading circles spin forever. T__T
Any idea why? Servers cannot ALL be down?

**Comment by dutchy1001** [comment]
please read the pinned topic #2105

**Comment by Disastra** [comment]
THANK YOU!!! 🙏🙇


Artist - 2D Animator - Motion Designer | Danielle Astra Loubser

LinkedIn <https://za.linkedin.com/in/danielle-astra-loubser-b0901542>
Website <http://danielleastra.wixsite.com/danianimator>    IMDB Credits
<http://www.imdb.com/name/nm4002143/>
