### ISSUE TITLE
Popcorn time stuck on loading when starting the app

### ISSUE THREAD

**Issue by JonatanSchor** [popcorntime/popcorntime#2176]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4 (also happened to me at a prior version, which was solved by installing the latest version - 0.4.4)

Download date: March 10th 2021

#### Expected Behavior: The app was supposed to open and show all movies available, as always

...

#### Actual Behavior: It just kept "loading" for several minutes 

...

#### Steps to reproduce the behavior

1. Just start the app

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://user-images.githubusercontent.com/42185329/119163123-c8e65900-ba63-11eb-8044-a37a70ceaee9.png)

**Comment by kiriles90** [comment]
Check the pinned issue (#2105)
