### ISSUE TITLE
Popcorn does not load

### ISSUE THREAD

**Issue by turkiwm** [popcorntime/popcorntime#2178]

**Comment by turkiwm** [comment]
when open popcorn it does not load any films

**Comment by turkiwm** [comment]
![popcorn](https://user-images.githubusercontent.com/41674892/119202798-42993980-ba9a-11eb-8371-04d0e79f2100.JPG)

**Comment by turkiwm** [comment]
Please help, I removed it and downloaded it again but still no films

**Comment by dutchy1001** [comment]
ffs read the pinned topic  #2105

**Comment by turkiwm** [comment]
Thanks
