### ISSUE TITLE
popcorntime.app is down

### ISSUE THREAD

**Issue by danielzzz** [popcorntime/popcorntime#2179]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
we know

**Comment by rebroad** [comment]
@kiriles90 I think it's best to leave this issue open until the issue is resolved, otherwise it risks people opening new issues for this (this appears to already be the 3rd issue raised in the last month for this issue).

**Comment by dutchy1001** [comment]
@rebroad 
there is a pinned topic (#2105) on the top of the issue page that explains about this and some workaround solutions for a long time already. If ppl are to lazy to read or research a bit further then their nose is long they dont need to open new issue's about it.
