### ISSUE TITLE
It Does Not Load any content ... 

### ISSUE THREAD

**Issue by SuperTechz** [popcorntime/popcorntime#2183]
Operating System Version: Windows 10 x64

Popcorn Time Version: 0.4.4 x64

Download date: 27 May 2021

Download url (optional): From This site (githup.com)

#### Expected Behaviour

... It should Load the Movies and the Series

#### Actual Behaviour

... Nothing, Just a black screen and the roling curson doing rounds and rounds ...

#### Steps to reproduce the behaviour

1. ... Download the software
2. ...Run it and you will see what I mean ...
3. ...

**Comment by dutchy1001** [comment]
please read the pinned topic #2105
