### ISSUE TITLE
PopcornTime doesnt download movies in mac Big Sur 11.4

### ISSUE THREAD

**Issue by skvsky** [popcorntime/popcorntime#2184]
PopcornTime doesnt download movies in mac Big Sur 11.4

Operating System Version:
mac Big Sur 11.4

Popcorn Time Version:
6.2.1.17

Download date:
29/05/2021

#### Expected Behaviour
Stream movies once selected.

#### Actual Behaviour
Doesnt stream movies once selected.

#### Steps to reproduce the behaviour
1. Open popcorn time 
2. Select any movie.
3. No streaming

#### Screenshot(s) of issue or error(s) logs of developer console (MacOS: ⌘ + 0 ... then 'console' 
<img width="1792" alt="Screenshot 2021-05-30 at 1 07 16 AM" src="https://user-images.githubusercontent.com/16475426/120082989-97b0fd00-c0e3-11eb-8b8a-1880edbd40d3.png">

**Comment by kiriles90** [comment]
That's not the official app its Time4Popcorn. You'll need to find their own forum.
