### ISSUE TITLE
Need build instructions for Windows that don't depend on popcorntime.app

### ISSUE THREAD

**Issue by rebroad** [popcorntime/popcorntime#2186]
Given that popcorntime.app is down, the build instructions for Windows need to be changed to remove this dependency.

**Comment by kiriles90** [comment]
No official server for us to add atm. As a temporary workaround check Ivan's repply to https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830823755 (or ofc you could build using the default nwjs binaries but you'll be missing out on the proprietary codecs that arent activated in those builds)
