### ISSUE TITLE
Doesnt load content

### ISSUE THREAD

**Issue by CydneyD** [popcorntime/popcorntime#2187]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
CydneyD doesn't read pinned topics

**Comment by CydneyD** [comment]
Actually I do but as i continued to read everyones response it got a little confusing with the talk of versions because apparently a version is working?  or there is another place i can go to get the correct version? I don't know.. i thought Id asked again and maybe I would get a clearer response but instead i got a rude response. Thanks anyway
