### ISSUE TITLE
Publish weekly/monthly build in github release

### ISSUE THREAD

**Issue by tanvir-kx** [popcorntime/popcorntime#2188]
As the official domain for the project is down hence there aren't any public access to the latest successful builds on ci.popcorntime.app. It would be nice to have access to latest successful Weekly/monthly builds in github release.

**Comment by dutchy1001** [comment]
Due to some legal issue's this is not possible ATM.

**Comment by kiriles90** [comment]
GitHub actions are an option, but one that is avoided so far so as to not put a target on the repo too. The future will show what will happen but for now we wait. You can still easily do that yourself though, just clone the repo, enable actions on the cloned repo then create and merge a PR named CI that changes the nwjs location in the gulp file to a valid one (e.g https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830843524), wait 10-15 minutes and the installers for all OS will be ready in said workflow.
