### ISSUE TITLE
Segmentation fault on Macbook M1

### ISSUE THREAD

**Issue by jonas-sk** [popcorntime/popcorntime#2189]
Operating System Version:
MacOS 11.3.1 (20E241)

Popcorn Time Version:
[this one](https://github.com/popcorn-official/popcorn-desktop/actions/runs/709245154)

#### Expected Behaviour
Not crash

#### Actual Behaviour
It always crashes but time till crash differs

#### Steps to reproduce the behaviour

1. Start it
2. Wait
3. Crash

#### Logs

```/Applications/Popcorn-Time.app/Contents/MacOS/nwjs ; exit;
(node:58428) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Received signal 11 SEGV_MAPERR 000000000000
 [0x00010c37bba9]
 [0x00010c2aa383]
 [0x00010c37bac1]
 [0x7fff20423d7d]
 [0x000000000000]
 [0x7fff203da4ac]
[end of stack trace]
zsh: segmentation fault  /Applications/Popcorn-Time.app/Contents/MacOS/nwjs
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]```

**Comment by kiriles90** [comment]
M1 devices aren't  natively supported at the moment. They only work via translation. There is already an open feature request to update the nwjs version we are using, that will (provided we update to a recent enough version) solve the M1 support issue too. It will create other issues though, almost all major jumps in nwjs version do, so its not really a top priority right now. If someone wants to have a go at it and fix all the issues that will arise, just clone the repo, update nwjs, fix the bugs that this will create, and make a PR. After that someone will have to compile that new version to enable the extra codecs, and upload it somewhere for Popcorn Time to build with.
