### ISSUE TITLE
Opensubtitles 401 Unauthorized

### ISSUE THREAD

**Issue by m-savary** [popcorntime/popcorntime#219]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
reinstall 4th August
#### Expected Behaviour

Load TV show subtitles from opensubtitles-api
#### Actual Behaviour

No subtitles on any tv shows
get an error on console
[ERROR] subtitleProvider.fetch() 401 Unauthorized
#### Steps to reproduce the behaviour

try to do fresh install several time,
just select any episode of a tv show and got the error.

![popc_sub_error](https://cloud.githubusercontent.com/assets/11076152/17410411/ddb240b0-5a73-11e6-9c5c-a389099df8e7.PNG)

**Comment by ChrisAlderson** [comment]
Cannot reproduce
