### ISSUE TITLE
no content loading

### ISSUE THREAD

**Issue by elbert7516** [popcorntime/popcorntime#2191]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
It seems the pinned topic isn't clear enough "Doesn't load any content".
 Maybe we should rename it to:
## **Doesn't load any content**

**Comment by losl2** [comment]
Doesn't load any content.
The app opens but does not load. I already uninstalled, installed and still does not load.
I use the app on windows 10. 
Can someone help me?
![pop corn](https://user-images.githubusercontent.com/85513484/121064702-4a492580-c79e-11eb-81d2-e1bd903bd19d.jpg)
