### ISSUE TITLE
should popcorntime-official sources get updated with popcorn-time-ru, or should popcorn-time-ru be the official sources instead?

### ISSUE THREAD

**Issue by je-vv** [popcorntime/popcorntime#2196]
It seems the popcorn-official/popcorn-desktop requires changes already available on popcorn-time-ru/popcorn-desktop.  And actually the sub-reddit FAQ indicates the official popcorntime has moved to [popcorn-ru.tk](https://popcorn-ru.tk), since the original [popcorntime](https://popcorntime.app) site has been blocked.

Right now what seems required from popcorn-time-ru is:

https://github.com/popcorn-official/popcorn-desktop/compare/development...popcorn-time-ru:nw-location

Is this popcorn-official planned to be maintained up to date, so it gets to build and what gets built keeps working?  Or should the popcorn-time-ru be considered now the official sources?

I ask mainly because if official development is happening on the popcorn-time-ru version, then besides those minor changes about which site to grab stuff from, the popcorn-official can get out of date an out of sync quickly.

Actually as their sources are right now, the popcorn-desktop doesn't even build, and past builds do't work.  Changes from popcorn-time-ru are already required...

**Comment by kiriles90** [comment]
The subreddit FAQ doesnt indicate the official Popcorn Time has moved to popcorn-ru.tk, it says that it just hosts the last available official builds (and the custom nwjs) due to the server issues. The official development is still happening here.

**Comment by je-vv** [comment]
@kiriles90, thanks for clarifying, sorry for my misinterpretation...

**Comment by kiriles90** [comment]
No worries. For now I guess we need to wait a bit more and see what happens with the server issues. Btw, we could easily build the app here using github actions or something even without ci. and point everything/everyone here to download but.. that might have undesired results e.g painting a much bigger target on the repo too and eventually having it taken down, which will cause a lot more issues, especially right now. So.. the RU fork graciously helped with whatever it could. These days the two repos btw arent too far apart, @ivan1986 pretty much PRed most of his important changes/commits here too :smile:  Only localization remaining afaik (PR is ready just needs to be tested a bit more)

**Comment by ivan1986** [comment]
@kiriles90 I real ton understand what we wait? We may release version and put it on any domain name on any free hosting. after that we may add dht config storage and update from torrent and dynamic change api server url.
code is ready, and we can put it somewere and not call it official server

**Comment by kiriles90** [comment]
@ivan1986 you know who we wait why are you asking me.. :smile:

**Comment by je-vv** [comment]
ohh, no binaries here please, as you mentioned, that's dangerous (getting the repos down is really bad).  I was meaning just the ability to build (and of course use the built applications).  And I do prefer to build any ways...

thanks for clarifying there won't be practical differences between the 2 repos.  Hopefully whether the official server domain gets resolved soon, or we get the repo updated with a new site to grab the custom nwjs from eventually...

closing from my point of view.  You guys can keep chatting or reopen it if in need, :)

Thanks a lot !  Very insightful answers !

**Comment by ivan1986** [comment]
@kiriles90 yes, i know, who we wait, i not understand why :)

**Comment by kiriles90** [comment]
@je-vv Sorry edited after you replied, yeah you are right about the gulp file issue. I'll see what I can do.

**Comment by je-vv** [comment]
@kiriles90 If you do so, please let us know when done, and on which commit, so we know...  Thanks again !

**Comment by kiriles90** [comment]
@je-vv https://github.com/popcorn-official/popcorn-desktop/pull/2199 merged

**Comment by je-vv** [comment]
Thanks a lot
