### ISSUE TITLE
Configurations in distributed technologies

### ISSUE THREAD

**Issue by jrc-dev** [popcorntime/popcorntime#2198]
We all have problems when an API server goes down, most of those servers return JSON data. Today we can start experimenting new technologies. I want to suggest some as a probable solution by using GunDB and/or Iota instead of these servers.

GunDB is an extremely intelligent distributed database, which means that changes are not controlled by a centralized server. A server can be just another point on the network. You save the data on a machine and it synchronizes it with other points without needing a complex consensus protocol. It just works. Using a small Javascript library, very powerfull! It will be probably the choice of a new decentralized 'Twitter'...
[GUNDB] (https://gun.eco/)

IOTA is consistent distributed ledger technology(DLT), I'm not here to shill any crypto, but with Iota we have a public ledger where we can send data(JSON), use it as DNS, it's feeles, that's no mine, run a node is cheap(a notebook can run a node), no fees to send or read data, for the purpose of availability, looks interesting.
Following is a link to a very simple project to send and read data in this DLT using Javascript and React.
https://github.com/mpagels/iota-react
https://v2.iota.org/visualizer

I would start to study if any of this technology would fit in this project, but I would like to hear from the most experienced developers about these possibilities. Thank you.

**Comment by kiriles90** [comment]
Personally I need to read up a bit more to get a better understanding of how these can be implemented but the idea sounds good. @team-pct @Persei08 @ivan1986 and everyone else, your thoughts?

**Comment by ivan1986** [comment]
Ok - gun can not use - it's interface for storage backends - they plans ipfs - it's only one possible storage
https://gun.eco/docs/Storage#ipfs
other it's not decentralised storages

**Comment by ivan1986** [comment]
main issue it's a search
if we use external api for films we just may store decentralize base of `imdb -> torrent list`

**Comment by ivan1986** [comment]
and one more - Configurations - no, we need store database of films and serials and torrents for it's
for configuration of api endpoints we have solution
