### ISSUE TITLE
Singular Bob error when try to build nwjs

### ISSUE THREAD

**Issue by tpw1314** [popcorntime/popcorntime#2206]
Operating System Version:
Windows 10

Popcorn Time Version:
try to build development (5 June 2021)

Download date:
5 June 2021

Download url (optional):
cloned from git.

#### Expected Behaviour
Build successfully
...

#### Actual Behaviour
Commented here, please check https://github.com/popcorn-official/popcorn-desktop/issues/1704#issuecomment-855177880
![image](https://user-images.githubusercontent.com/20537849/121763924-44728c00-cb72-11eb-959e-9f298453f40b.png)

...

#### Steps to reproduce the behaviour
1. Clone from Development branch
2. 
```
yarn config set yarn-offline-mirror ./node_modules/
yarn install --ignore-engines
yarn dist --platforms=win64
```

**Comment by kiriles90** [comment]
Do you have NSIS installed?

**Comment by ivan1986** [comment]
Yes - error can not find nsis maker, just install it and run build again

**Comment by tpw1314** [comment]
@ivan1986  @kiriles90  I am sorry but did you look at my screenshots ? I mentioned that I installed NSIS but still fail. What other NSIS do I need to install ?

**Comment by tpw1314** [comment]
I followed the instruction on read me main page on how to build, but yet missing this and that dependencies.
Can anyone please update building instruction for redistribution package ?
For example, pre-requisite is to run npm add makensis first or etc ?
