### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by imbakar** [popcorntime/popcorntime#2207]
Operating System Version:
Ubuntu 20.04
Node v14.17.0

Popcorn Time Version:
0.4.4

Download date:
June 14, 2021

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.4/Popcorn-Time-0.4.4-linux64.zip

#### Actual Behaviour
DevTools listening on ws://127.0.0.1:9222/devtools/browser/72aabfb5-424d-4b1d-bab5-093099866f5e
[158116:158116:0614/014500.473102:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:158135) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

#### Steps to reproduce the behaviour
1. chmod +x Popcorn-Time 
2. ./Popcorn-Time 

![Screenshot from 2021-06-14 01-56-44](https://user-images.githubusercontent.com/11833526/121820276-cddda780-ccb3-11eb-8600-4a0e847d2507.png)

**Comment by kiriles90** [comment]
If that's the url you downloaded from then you are using the old release version. Have you tried the latest build? You can download artifacts from https://github.com/popcorn-official/popcorn-desktop/actions/runs/930274849 or build it yourself using the dev branch.

Btw, is this issue about the devtools warning only or..? Because I see your movie list seems to be not loading.

**Comment by imbakar** [comment]
Hello,
Sorry for the delay.

I was downloaded the new version, that not work for me, then build from `dev` branch but no luck.
But after manually using `https://popcorn-ru.tk/` or `https://yts.mx/` under custom server it work.

Thanks for the reply

**Comment by Umeaboy** [comment]
I still see this in the latest code as well.

**Comment by kirisakow** [comment]
* **Not so good news:** I confirm the [latest release of the `popcorn-official/popcorn-desktop`](https://github.com/popcorn-official/popcorn-desktop/releases) project has not fixed the `[DEP0005] DeprecationWarning` issue. Also, quite strangely changelog dates back to 2016.

* **Good news:** Meanwhile, I tried installing the [latest release of the `popcorn-time-ru/popcorn-desktop`](https://github.com/popcorn-time-ru/popcorn-desktop/releases) project — and it works fine.

**Comment by Umeaboy** [comment]
0.5.1 shows this when running yarn install using the Source archive:

(node:778455) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
