### ISSUE TITLE
VPN selectively blocking chromecast

### ISSUE THREAD

**Issue by leethax666** [popcorntime/popcorntime#221]
Operating System Version:
Linux Mint

Popcorn Time Version:
0.3.9

Download date:
#### Expected Behaviour

Allow chromecast streaming
...
#### Actual Behaviour

No chromecast option available 
...
#### Steps to reproduce the behaviour

Start Bitmask VPN. Launch Popcorntime. No Chromecast option. 

If I quit the VPN app, launch popcorntime, it works normally, even if I restart the VPN app.

**Comment by Breaking1** [comment]
If you start popcorntime before you connect to the VPN service it will detect your Chromecast.

When you see the Chromecast in the players menu you can start the VPN service and you will be protected, just make sure to connect to the VPN service before you press watch now or do any streaming/downloading in popcorntime.

**Comment by leethax666** [comment]
will this be fixed? my vpn doesn't effect chromecast on any other app

**Comment by Breaking1** [comment]
I do hope it get fixed, but it's probably not first on their to do list since you can easily get around it with connecting the VPN service after you start popcorntime.

Here is what it says on their Blog when it comes to GitHub and bugs/issues.

> What's the plan?
> After the "MPAA incident", we're a little diminished, and we've chosen a new direction: we're shifting from an active development of Popcorn Time to a more or less resilience-driven development. We will keep an eye on the bug tracker (Github) and fix the most urgent ones

You can read the full Blog post here..

https://blog.popcorntime.sh/official-statement/

**Comment by tchristofferson** [comment]
if your forced to use vpn delete popcorn time and make sure you download it from popcorntime.sh not .io or any other ones it doesnt require you to use vpn
