### ISSUE TITLE
Update anime url

### ISSUE THREAD

**Issue by superbonaci** [popcorntime/popcorntime#2213]
My popcorn-time says `The remote anime API failed to respond, please check https://anime.api-fetch.sh and try again later`

**Comment by kiriles90** [comment]
There is no compatible anime API to substitute the currently down official API. If you know of one you can set it in the settings.

**Comment by Kr3m** [comment]
Why is this closed without comment on the same day it was created?

**Comment by dutchy1001** [comment]
Because it's a known fact that there is not a working Anime API for some time now.
