### ISSUE TITLE
Popcorn-Time continues to crash with macOS 12

### ISSUE THREAD

**Issue by jamesf-hub** [popcorntime/popcorntime#2222]
Operating System Version:

macOS 12 DB1

Popcorn Time Version:

Latest Build using GitHub Actions

Download date:

Today

Download url (optional):

#### Expected Behaviour

Launch
...

#### Actual Behaviour

Closes
...

#### Steps to reproduce the behaviour

1. Launch app on mid-2015 MBP.
2. Crashes.

**Comment by kiriles90** [comment]
Same reason as before. No nwjs update yet that might solve the issue. Closing this since there is already an open issue about it.
