### ISSUE TITLE
Owncast Setting Integration

### ISSUE THREAD

**Issue by rastaval** [popcorntime/popcorntime#2227]
I would like to request that the stream capability of Popcorn time can be stream towards Owncast. I have had used the stream feature of Popcorntime however, I cannot select a specific port to be used by Popcorntime. 

In this regard, if only Popcorn time can have a setting where we can set the streaming (RTMP) url and streaming key to stream the media to Owncast it would be very helpful. My family in the Philippines is having trouble with their internet connection, so what I do is to stream the movie from popcorn time to them with the help of VLC. However I need to adjust my router configuration everytime another movie will be broadcasted, because every movie has a different port generated by Popcorn Time.

I would like to thank you all (Developers) for the opportunity to extend and share good kiddy movies to my kids back home in the Philippines. Best regards, more power and thank you.

**Comment by kiriles90** [comment]
Hi, you can set the 'Port to stream on' in the settings to something other than 0, then that will be the port for the stream url.

Closing this but comment below if you are still having issues.

**Comment by rastaval** [comment]
the thing is I wish to use Popcorntime to stream data to Owncast. Owncast requires rtmp url (rtmp://domain.com/mount/) and a streaming key. is there anyway that we can use popcorntime? TIA

**Comment by rastaval** [comment]
I am using the latest version of PopcornTime however I cannot find the "Port to stream on" in the settings. Under what category is that setting if you don't mind me asking?

**Comment by kiriles90** [comment]
Enable advanced settings then its in the 'Connection' section.
