### ISSUE TITLE
Popcorn to RTMP server

### ISSUE THREAD

**Issue by rastaval** [popcorntime/popcorntime#2228]
Hi, I apologize if this annoys you, but is there anyway that popcorn time could stream a video to an rtmp server? the rtmp server requires rtmp url with the format (rtmp://domain/live) and a stream key? Thank you.

**Comment by kiriles90** [comment]
No such ability to do this directly right now afaik. You might be able to do something using a supported external player that might have this feature. Does setting the port to a specific one so you dont have to forward it everytime and using the http stream url not work?

**Comment by rastaval** [comment]
Hi, thank you for the patience and the help in walking me through how to set the port and it did worked. Since, as you have said, the ability of streaming to rtmp server is not yet possible right now, this could be a partial solution of my issues. The people back home are not computer savvy so I'd really wish to spoon-feed them. With your brilliant help, I only have to set the VLC configuration to their computer just once. Thank you and have a good day.

**Comment by kiriles90** [comment]
Glad I could help :) Btw, if you want, keep an eye on https://github.com/popcorn-official/popcorn-desktop/issues/2229, if/when it gets implemented it might provide a better way for you to share a stream, ..hopefully without port forwarding and third party apps.

**Comment by kiriles90** [comment]
Glad I could help :) Btw, if you want, keep an eye on https://github.com/popcorn-official/popcorn-desktop/issues/2226 from time to time. If/when it gets implemented it might provide a better way for you to share a stream, ..hopefully without port forwarding and third party apps.
