### ISSUE TITLE
Dependence on a closed source server at "popcorn-ru.tk" for binaries

### ISSUE THREAD

**Issue by timebite** [popcorntime/popcorntime#2229]
I was looking through the contributing document and trying to get my own local build of PCT when I saw 

![223qdfqws qwe](https://user-images.githubusercontent.com/86923801/124391853-1cf58600-dd10-11eb-84f9-03f2c629156e.png)

Isn't this a big security issue? I mean we're downloading a binary from a random source(no offence to the person hosting it). Can't we have a build process written into the workflow, building just the ffmpeg library into a dll/dylib and adding it to the nwjs SDK downloaded from the official site seems very simple as well, [source](https://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs-in-nwjs).

Or we could even set up something like [this](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases) ? I feel like there are a lot of options we could exhaust before relying on a server that has binaries that we have no way of verifying.

**Comment by ivan1986** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/2062

**Comment by ivan1986** [comment]
yes, need build with proprietary codecs, https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases not works - many codecs not exist
i try to build new nwjs by this manual, but do something wrong

**Comment by timebite** [comment]
@ivan1986 I've made it work with the CI builds from https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/tag/0.44.6 on a fork here https://github.com/timebite/popcorn-desktop. It uses 0.44.6 instead of 0.44.5 from the official nwjs sources, I wasn't able to make a PR because for some reason the CI build tests on that repo kept failing, I'd be happy to get some pointers on that.

**Comment by ivan1986** [comment]
1) and now more then half of films in internal player play without sound
2) we wait this https://github.com/webtorrent/webtorrent/pull/1820

**Comment by kiriles90** [comment]
Can this conversation be moved over at #2062? Closing this just to keep things tidy but its a good suggestion @timebite so lets continue this at the other issue (more people might notice it too and contribute ideas or code)
