### ISSUE TITLE
Auto update option

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#2243]
Add a auto update to a new version option and popup in Popcorn Time

**Comment by dutchy1001** [comment]
This option is already available in the settings.

It just won't update to a new dev build which is understandable due to there not properly tested yet

**Comment by GKid94** [comment]
@dutchy1001 It doesn't work, I had to install the new 0.4.5 version manually

**Comment by dutchy1001** [comment]
@GKid94  It doesnt work atm due to the takedown of the website/software host. The version you installed is a different fork (ru.tk) which obvious does not recognise this repo. Both version are working close together to keep PCT alive.

**Comment by kiriles90** [comment]
@dutchy1001 its this version that he installed not the RU fork, 0.4.5 was released in this repo. But everything else is as you said, the old domain is down, the updater throws an error, no automatic update.

**Comment by dutchy1001** [comment]
@kiriles90 thx for correcting that

**Comment by GKid94** [comment]
@dutchy1001 @kiriles90 Ok thx, maybe you can try Stremio and see what he has, I see that it doesn't have takedowns

**Comment by dutchy1001** [comment]
@GKid94 that is just a matter of time before they will get to Stremio (Ugh nasty word lol) if he is doing simular as PCT.

**Comment by kiriles90** [comment]
@GKid94 What they are doing so far is having addons that you manually go and enable, so no copyrighted content by default. I dont see you complaining about that but you complain that Popcorn Time has a custom API(s) option..

**Comment by GKid94** [comment]
@kiriles90 But you still need to reinstall the program from the current version because it won't update to the new version on the new link
