### ISSUE TITLE
Não carrega

### ISSUE THREAD

**Issue by Larafo** [popcorntime/popcorntime#2247]
Instalei a versão 4.4 do popcorn time no meu winsdows 10, porem não carrega nada!
ele so fica atualizando o tempo todo e não sai disso.

o que devo fazer?

**Comment by dutchy1001** [comment]
Você precisa ler a edição # 2105, que explicará por que e como obter uma versão funcional.

(Por favor, mantenha os tópicos em inglês para que qualquer pessoa possa / pudesse ajudá-lo) 
Translated with Google translate.

You need to read issue #2105, this will explain why and how to get a working version.
