### ISSUE TITLE
[Linux] No minimize/exit buttons when a movie is playing not in fullscreen

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2249]
**Is your feature request related to a problem? Please describe.**
When i start playing a movie, and it's not yet in fullscreen, there are no options for minimizing or exiting the PCT app.

**Describe the idea you'd like**
Add options to Minimize/Maximize/Exit the PCT when the movie is already being played but not in fullscreen mode.

**Comment by kiriles90** [comment]
Its like that by design. To close the app exit the movie player first, to minimize do it from the taskbar.

**Comment by aha999** [comment]
but what if i want to minimize popcorn time when i'm playing it ? like with other apps

**Comment by kiriles90** [comment]
@aha999 Click on the taskbar and minimize it. As for close, that's the one that isn't there on purpose so you stop streaming/downloading before exiting the app.

**Comment by kiriles90** [comment]
@aha999 Just click on the taskbar and minimize it. As for close, that's the one that isn't there on purpose so you stop streaming/downloading prior to exiting the app. I do understand that those functions could be coded into that exit button but on most systems there will be a noticeable delay exiting which will be perceived as bad performance/ui lag from most users even though its basically the app stopping the download, deleting caches and anything else it has to do to properly close which (just my opinion) would result in "worse" user experience. I just know that a big percentage of users noticed it and were commenting/asking about it the last time the app had this issue with version 0.4.0 and the then newly added Seedbox feature.

**Comment by aha999** [comment]
understandable, but in Linux i'm using - Pop!OS you can't minimize apps by clicking their icons in taskbar, so the only way to minimize popcorn is by going to deskop, which minimizes all apps... 

On the delay issue... is it possible that Popcorn would first close the UI, then all the processes in the background ?

Edit: changed "Mumble" to "Popcorn", idk what was going through my head.

**Comment by kiriles90** [comment]
> is it possible that Mumble would first close the UI

To be honest.. that's a great idea! https://github.com/popcorn-official/popcorn-desktop/commit/f8040af72d40818c26b99fad32f23a26f350e18f merged and seems to work great. Thanks, that should solve the slight delay that exists in some occasions (e.g active torrents in the Seedbox). Personally though I'm still a bit on the fence about what is basically two close buttons in the player. (one for exiting the player, one for exiting the app). Even if we switch the exit player one for something else (e.g a `<-`) we are still guarantied to confuse many people at this point.

I'll see what I can do about the minimize button or if you want make a PR and I can merge it.

**Comment by aha999** [comment]
Sorry i don't know programming, so i can't make a PR, but it's great that you solved the issue that's been bothering you :)

Maybe a bigger exit button in the player ? or something boxy like "close player" ?
