### ISSUE TITLE
subtle subtitle file error

### ISSUE THREAD

**Issue by Franck78** [popcorntime/popcorntime#2259]
Operating System Version: linux

Popcorn Time Version: 0.4.5

Download date:july 20

Download url (optional):git

#### Steps to reproduce the behaviour

Sorry, no steps, it's just what I think happened

It involves two movies. M1, M2.

1/
I selected M1 and after 2 or 3 three minutes 'Cancel'. Popcorn was at the "Connecting" stage.

2/
I selected M2 wich started immedialtly. Connecting.. Downloading initial buffer OK.
Subtitles are activated (english), no worries

3/
After some time (30 minutes ) I noticed subtiltle completly not synced. 
I disabled them

4/
At some point I saw or received a notification: movieA download complete !?:?
well, why not,  it was 'canceled'

5/
I went to /tmp/Popcorn to save MovieA from erasing when closing Popcorn
MovieA.avi
MovieA.srt copied

6/
The bug: MovieA.srt contains subtitles from MovieB
I think I was reading MovieA subtitles when I disabled them (step 3)

Something is not reentrant with filenames for subtitles ;)

Franck

**Comment by kiriles90** [comment]
Tried to replicate this a couple of times but couldn't. Also some other issues with it is that there is no 'download complete' notification and that subtitles aren't being fetched for the 'Download' function anyway, that only happens for the 'Watch now'. (open issue about it at https://github.com/popcorn-official/popcorn-desktop/issues/1686)

**Comment by Franck78** [comment]
Yep I have tried again to remember what I was doing and sure I didn't use the "cancel" button.

I used the top right "minimize" then close the movie panel to select another one.

This doesn't stop the connecting/downloading process

For me the "bug" is when you start watching another movie while the initial try is still in "connecting" .

About the notification, "something" tiped me about MovieA complete download (remember I was not expecting it at all).
If not, I would just have close Popcorn and go to bed instead of saving the download.  Then finding the subtitle contain mismatch, remembering the lost of subs sync, after 24 hours ;)

**Comment by kiriles90** [comment]
@Franck78 but if you just minimize the loading screen while its at 'connecting'... you cant select another movie, the buttons are disabled/greyed out.

**Comment by Franck78** [comment]
Yes I can close while "connecting" and still see the download progress in seedbox.

1. Goto Movies
2. Select something old that maybe will take time before effectivly download
3. "Watch now" Use minimize (while Popcorn displays "connecting")
4. Back to the movie pane, just close it (X)
5. Check seedbox
6. Back to movie list, start another one

No grayed buttons.

**Comment by kiriles90** [comment]
> 6. Back to movie list, start another one  

I cant, 'Watch now' is grayed out/disabled.

**Comment by dutchy1001** [comment]
Tried this on a windows pc but I cant either choose  a "next" movie to play. The "Watch Now" button is greyed out also. I can search other movies and click the "Download" button only.

Could you provide a link were you got the version from, just to be sure it's from the right repo

**Comment by Franck78** [comment]
ok, I totally agree with the grayed button.
But it dosn't stay grayed for long.

1. the connecting/download is started and I minimize it, returning to movie list, OK
2. everything watch now is grayed 
3. at some point, download starts and popcorn starts the movie.
4. you can "pause it" , and close
5. back to movie list, now nothing is grayed

notice the little popup notification ;)

I can't say it's a bug or not (grayed or not). The point is, it is possible to have some download started with "watch now" , watch something else and at some point having a srt file containting data from another movie.

In this video, I launch "pirate of the caribean", have grayed button, then no grayed buttons.

https://user-images.githubusercontent.com/1778884/128017307-937168fe-0337-4479-8436-26dfe6a6272e.mp4

**Comment by kiriles90** [comment]
@Franck78 at 1:33 you close the player, that's not minimizing, that stops the streaming. Yes the download still remains in the Seedbox page (forcefully removing it and deleting cache would be counter productive/intuitive) but that stream is stopped so ofc you can start another movie..

**Comment by kiriles90** [comment]
@Franck78 at 1:33 you close the player, that's not minimizing, that stops the streaming. The download still remains in the Seedbox page (forcefully removing it and deleting cache would be counter-productive/intuitive) but that stream is stopped so ofc you can start another movie, why wouldn't you?

> notice the little popup notification ;)

That's the minimized loading screen but as you see it goes away once the player is launched (so not minimized anymore) and isn't there once you exited the player in 1:33 (so that stream is stopped). The download is still in the Seedbox, and you can resume downloading from there if you want, but it wont start streaming/playing it too. To do that you have to find the same movie and press 'Watch now' again (after that ofc if you have some % in your cache already downloaded the app can see it and not need to re-download it so it looks like its resuming but its not, its basically restarting that stream)

So, I guess these resolve the grayed out buttons and 'completed notification' issues but still leave the subtitle one. Were you able to replicate it doing the above or it was it just once?

**Comment by Franck78** [comment]
I will try to replicate it. Not easy because,
- I was trying latest official (eg clicking everywhere)
- a lot of time between discovering mixed srt
- was not expecting a bug track while whatching movie B. When I cannot readjust subtitle with F/G I just deactivate them.
- must find a very 'long' source stuck on "connecting"
- cannot tell if movieB download was completed before during or  after movieA started

About 'connecting+minimize" => grayed button, that is a strange idea ! Speaking for me, I wait between 30 to 90 seconds the connecting phase. After that, I select another movie or quit.
With the grayed button, you assume I want to see it asap, which is false.

Cancel should just as it says, this never happened (no download queueing)
Minimize should just be the strict equivalent of adding  the movie to the Download queue(seedbox).
