### ISSUE TITLE
Torrent Collection stopped working again

### ISSUE THREAD

**Issue by HekutoruMAC** [popcorntime/popcorntime#226]
Operating System Version:
Windows 8

Popcorn Time Version:
HEAD 43D3386B

Download date:
About a month ago.
#### Expected Behaviour

Open, edit or remove torrents from the collection.
#### Actual Behaviour

Nothing, the buttons do not work.
#### Steps to reproduce the behaviour

Just click on Torrent Collection.

**Comment by ChrisAlderson** [comment]
Try [build #138](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/) and see if it fixes it, it's based on 25f7589ca3d85b932807c11fa0e50a1a54b28e24

Only rarbg will work, because kat has been down for a while now.

**Comment by HekutoruMAC** [comment]
Nope. Clicking the torrent title or the pencil/bin icons still has no effect.
Already flushed the collection, it made no difference.

**Comment by HekutoruMAC** [comment]
Build [#139](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/) fixed the issue. Thanks!

**Comment by HekutoruMAC** [comment]
**Torrent collection not working again, same behaviour.**
Problem handled previously by removing several currently present `$( ... ).context` from the openFileSelector function on the file [torrent_collection.js](https://github.com/popcorn-official/popcorn-desktop/commits/development/src/app/lib/views/torrent_collection.js)
[Here](https://github.com/popcorn-official/popcorn-desktop/commit/ef9d50708661d0b6aab5ff30ea6eb4ee04b5e541?diff=unified#diff-f7847d725e4a233b43d20b518bc499ce) is the old fix.
