### ISSUE TITLE
Composite filters for what are now sorting criteria only

### ISSUE THREAD

**Issue by eyalroz** [popcorntime/popcorntime#2262]
**Is your feature request related to a problem? Please describe.**
I am often interested in sorting by a certain order, like Last Added, but tend to dislike items with low review rating. I could, instead, sort by review rating - but then I can get titles which have been on Popcorn for years next to titles just added.

**Describe the idea you'd like**
The should be UI for setting ranges (for numbers) or regular expressions (for strings) for each of the sort-order axes: Trending, Popularity, Last Added, Year, Review Rating -  simultaneously

**Describe alternatives you've considered**
At the minimum, it should be possible, in addition to filtering by genre, to filter by minimum review rating (or review rating range), or by release year range.

**Additional context**
I'm looking at v0.4.5b.

**Comment by kiriles90** [comment]
Filters depend on the API mostly. What filters are available in the current APIs are also used by Popcorn Time. E.g if you use the yts API for movies, you'll see a minimum rating filter appear, and that you are also able to include the year in the search terms to see only movies from that year. No year range, no such filter API-side.

**Comment by eyalroz** [comment]
> Filters depend on the API mostly.

Do they, though? If the app downloads information about certain films - unfiltered - that naturally includes the relevant values for them (rating, year, last added etc) - it can then proceed to filter them. I don't quite see why this would be a problem.

**Comment by kiriles90** [comment]
Because making 150 general API calls of 25 movies each to filter out 3 movies locally is not the way to go? :smile: 
This is ment to be handled API-side for various reasons.

**Comment by eyalroz** [comment]
> Because making 150 general API calls of 25 movies each to filter out 3 movies locally is not the way to go?

I don't know the API. But if you can get information about 25 films at a time, and you have 4 or 5 criteria, wouldn't that be 8 or 10 calls for what would normally be a window's worth of films? ... and if those are whittled down to three films, then - just be slower in filling up the window, to limit the number of API calls per second if you're worried about hammering the server.

I agree that API support for filtering would be better, but still.

**Comment by kiriles90** [comment]
You get a window's worth of films with 1-2 API calls. If you use local filters then it depends, you might filter out a couple of movies, or you might filter them all of them out depending on the criteria you've added, in which case.. you'll need a great number of calls to fill the window. Those calls would also need to be automatic because fetching 2 movies then waiting for user input (e.g scroll down) is really bad when you test it. And even like that it doesnt solve the issue of excessive API calls, just adds some delay to them. In short, and because this local filtering issue has come up a number of times over the years, it really isnt the way to go. (you dont have to take my word for it, the source is open you can fork it, code something quick and test it and see)

**Comment by eyalroz** [comment]
> in which case.. you'll need a great number of calls to fill the window.

Yes, this is true. But - it is up to the PopCorn client to decide where the limit is in terms of API calls / second. So you could set that low, and still get this effect, albeit slower.

> And even like that it doesnt solve the issue of excessive API calls, just adds some delay to them. 

If you define acceptable API calls in terms of rate - which I'm sure you do - then it's not "just" adding delay - it resolves the problem/.

> In short, and because this local filtering issue has come up a number of times over the years, it really isnt the way to go.

I'm sure API support is a much better way to do this. But - isn't the API more difficult to cheange?

**Comment by kiriles90** [comment]
Closing this until someone has a valid solution for using filters not available at the API. (see #2263 too for more info as to why)

**Comment by eyalroz** [comment]
Well, I guess it's fair to wait for the API to change.
