### ISSUE TITLE
Not launching on MacOS Mojave (10.14.3)

### ISSUE THREAD

**Issue by vdias38** [popcorntime/popcorntime#2266]
It works fine on 0.4.4 and suddenly during navigation it crashes. I've tried to restart it but without success, so I've decided to upgrade to 0.4.5 via brew but continue not launching. Tried night build from download site but observed same result.
I'd like to remove all files (settings, favorites, etc.) from my desktop to try a clean re-install but don't know path of config files, 

1. **can anyone tell me how to do a clean uninstall ?** 
2. **where are saved logs ?**

Operating System Version:
MacOS Mojave (10.14.3)

Popcorn Time Version:
0.4.4+

Download date:
Brew and https://popcorn-ru.tk/build/dev/

Download url (optional):
Popcorn-Time-0.4.5+92.g69533f74_osx64.zip

#### Expected Behaviour

...

#### Actual Behaviour

When I launch app the window doesn't open, nothing happen.
...

#### Steps to reproduce the behaviour

1. Download
2. Unzip and launch
3. ...

**Comment by kiriles90** [comment]
There are issues with newer macOS versions that a clean install wont solve. The nwjs version we are using has to be updated to hopefully resolve them. There is already an open issue about it so closing this one but if you need something else just comment below.
