### ISSUE TITLE
All episodes load, not just the one I pick.

### ISSUE THREAD

**Issue by FireFox53** [popcorntime/popcorntime#2276]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
Not enough info .  Can't help here

**Comment by FireFox53** [comment]
When I click on an episode to down load it auto starts to down load all episodes. I only wish to down load one at a time. How can I sop this.

**Comment by FireFox53** [comment]
When I click on an episode to down load it auto starts to down load all
episodes. I only wish to down load one at a time. How can I sop this.

**Comment by dutchy1001** [comment]
just fill in the questions aske when submitting an issue or no help will be given. Those questions are there for a reason.

**Comment by FireFox53** [comment]
sorry first time doing this
