### ISSUE TITLE
not work Zorin os

### ISSUE THREAD

**Issue by cjbs69** [popcorntime/popcorntime#2278]
Operating System Version:
Zorin Os

Popcorn Time Version:
0.4.5
Download date:
28 august

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
What do you mean by not working?

**Comment by tanvir-kx** [comment]
If the app don't start for you on a linux system, to be sure your system have the required dependencies. try 
sudo apt update && sudo apt install libatomic1 libgconf-2-4 libcanberra-gtk-module
