### ISSUE TITLE
Subtitles synchronization on Chromecast

### ISSUE THREAD

**Issue by ChristopheCVB** [popcorntime/popcorntime#228]
Operating System Version:
OS X 10.11.6 (15G1004) and Windows 10

Popcorn Time Version:
0.3.9-0 "There's nothing on TV" (80e3fc19)

Download date:
15 September 2016
#### Expected Behaviour

When launching a film/tv show on Chromecast, subtitles have to be synchronized and I should be able to change the subtitles offset.
...
#### Actual Behaviour

The subtitles are not synchronized and I am not able to change the subtitles offset
...
#### Steps to reproduce the behaviour
1. Open Popcorn Time
2. Choose a film/tv show
3. Launch it on a Chromecast with a subtitle ON
4. Press (CTRL or SHIFT)"G" or (CTRL or SHIFT)"H"

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/subtitles-synchronization-on-chromecast/103
