### ISSUE TITLE
 nwjs.exe makes Windows 11 insider preview to crash the Explorer process in a unending loop

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#2290]
Operating System Version:
Windows 11 insider 
Popcorn Time Version:
0.4.5 "The next wave" Beta (c5d38112)

Download date:
I run it from Github source code because the download version don't work anymore

#### Expected Behaviour
Run smoothly
...

#### Actual Behaviour
after some minutes or hours, randomly, the **nwjs.exe** process makes Windows 11 explorer to crash and restart in a unending loop
If I end the process from task explorer, the explorer is restarting and the loop is ending and the process is stable again.
...

#### Steps to reproduce the behaviour
just launch Popcorn desktop with 'yarn start'

**Comment by kiriles90** [comment]
Hi, there is already an open issue about updating our nwjs version but there are some issues to overcome first. Linking this issue to https://github.com/popcorn-official/popcorn-desktop/issues/2062 and closing so we dont have duplicates but if you want we can continue the conversation there where there are also more people following.
