### ISSUE TITLE
API failed

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2298]
Hi! I just installed popcorn time on my pc, I am using an arch based os. I did all the installation process correct and now I can launch the application from the application menu. But I am getting this error when Popcorn time opens:

![Screenshot__5](https://user-images.githubusercontent.com/76535242/135007776-cdfbc669-2fc8-4fe1-9afa-5c8a3d184a5c.png)

How am I supposed to fix this?

**Comment by dutchy1001** [comment]
This can have a few causes 
1 - Not set the right API (I don't recognise "movies-v2.api-fetch.am" and won't for me either)
2 - the API was down
3 - your country is blocking the API

try to use https://popcorn-ru.tk/ and see if that works.

**Comment by tuxayo** [comment]
I got the same issue and https://popcorn-ru.tk/ worked.
