### ISSUE TITLE
Extremely slow loading on Nexus Player

### ISSUE THREAD

**Issue by asaddon** [popcorntime/popcorntime#230]
Operating System Version:
Nexus Player ( Android 7.0 )

Popcorn Time Version:
Latest Version

Download date:
15 September 
#### Expected Behaviour

Video should stream fast and without slow loading on Nexus player as it does on the windows computer on the same network.
...
#### Actual Behaviour

Its extremely slow in loading
...
#### Steps to reproduce the behaviour

No Steps needed its just slow on Nexus player.

**Comment by ChrisAlderson** [comment]
This is an issue for [popcorn-android](https://github.com/popcorn-official/popcorn-android/) not the desktop version.
