### ISSUE TITLE
Crashes while watching a video

### ISSUE THREAD

**Issue by juanvisbal** [popcorntime/popcorntime#231]
Operating System Version:
MacOS 10.12

Popcorn Time Version:
3.9

Download date:
September 3, 2016
#### Expected Behaviour

Let me watch Steven Universe
#### Actual Behaviour

Crash while watching.
#### Steps to reproduce the behaviour

1. Select Steven Universe s04e05, start watching (default: 720p, built-in viewer)
2. Start watching until it crashes.

**Comment by Chriz007** [comment]
SHOWS ALWAYS CRASH ON ME. WHY?? PLEASE FIX THIS

**Comment by ChrisAlderson** [comment]
The codec in some content the API provides can be faulty. If an episode or movie does not work with the internal player of Popcorn Time, you can try to play it in an external player like VLC.

**Comment by benju69** [comment]
Same here : crash on macOS Sierra

**Comment by juanvisbal** [comment]
@ChrisAlderson when selecting another player, it doesn't crash, it freezes.

**Comment by ChrisAlderson** [comment]
@juanscv What version of Popcorn Time are you using and which external player are you using?

**Comment by juanvisbal** [comment]
@ChrisAlderson 0.3.9 from website, VLC as external player.

**Comment by jmsalcido** [comment]
same here

**Comment by munoz** [comment]
I'm experiencing this too, running version 3.9 on macOS 10.12. I tried watching a show and a movie both in PT and on VLC.

**Comment by papipurro** [comment]
me too when I'm watching series and movies

**Comment by f-bone** [comment]
crashes in macOS Sierra -

**Comment by VitorVRS** [comment]
Are PCT logging an warning/error?

**Comment by Frankenmint** [comment]
```
Crashed Thread: 0 CrRendererMain Dispatch queue: com.apple.main-thread
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
```

from [here](https://discuss.popcorntimece.ch/t/macos-sierra-gm-still-crashing-despite-the-update/195)

**Comment by ipoznyak** [comment]
0.3.9 crashes in macOS Sierra

**Comment by NE03N** [comment]
same thing here! it used to crash while playing but now it crashes during loading... frustrating!

**Comment by zagahlo** [comment]
It always crashes everytime in my Macbook pro mid 2012 with macOS Sierra

**Comment by rkj1515** [comment]
+1

**Comment by NE03N** [comment]
Is there any news on the fix?... please don't make me downgrade to El Capitan...

**Comment by team-pct** [comment]
Please test https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/150/

**Comment by NE03N** [comment]
OMG it's working again!!! and the best version of popcorn time none the less (faster tvshows uploads, mplayerX support, Anime, working smart TV streaming...etc.). You guys are the real deal !!! keep up the good work (y) Godspeed...

**Comment by jmsalcido** [comment]
thanks.

**Comment by papipurro** [comment]
still crashing for me, i'm in macOS sierra

**Comment by jmsalcido** [comment]
@papipurro try using the build that @team-pct used there. https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/150/artifact/build/Popcorn-Time-0.3.9_osx64.tar.xz
