### ISSUE TITLE
Is it possible to add other languages like "HINDI" for some supported movies and showS?

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#2314]
**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kiriles90** [comment]
It probably is given there are good sources and parsers available but all this has to be done API-side, it doesnt have much to do with the app so closing this issue (one of the API admins has already seen this so now we wait and see)

**Comment by ivan1986** [comment]
it's list issue, fixed

**Comment by fisforfaheem** [comment]
Ok! I hope the admins work on API



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/12/21,
05:31:11 PM
