### ISSUE TITLE
SHA256 Mismatch on brew install

### ISSUE THREAD

**Issue by ebarojas** [popcorntime/popcorntime#2329]
OS X 11.6 installed on 1-nov-2021 following the commands on readme.md I get an Error: SHA256 mismatch

![image](https://user-images.githubusercontent.com/8750702/139775308-9f48edf8-d273-4583-aae6-7dd7cd764fae.png)

Expected to be able to install PT, instead I got this error.

**Comment by kiriles90** [comment]
You are right, that was the hash of version 0.4.5. The version number got bumped with https://github.com/popcorn-official/popcorn-desktop/commit/6a6c6d4894991eab653457c5d21f7e9c4cd18c90#diff-b725efcbcbeb2209730112c012e1d967f3df16f8473e82761bc773a5737103cc but the hash was never changed. Fixing now.
