### ISSUE TITLE
Stuck on Starting Download

### ISSUE THREAD

**Issue by sulaimanob** [popcorntime/popcorntime#233]
Operating System Version:
 Windows 10

Popcorn Time Version:
3.9

Download date:
 22/09/2016
#### Expected Behaviour

 to start downloading
...
#### Actual Behaviour

 stuck
...
#### Steps to reproduce the behaviour

1. Run the app
2. select a movie
3. press watch

Note: When F10 button is pushed to show butter temp folder, it shows an error 

'
Windows cannot find C:/users/username/AppData/Local/Temp; ; <path-to-sdk>/platform-tools/Popcorn Time' Make sure you've typed the name correctly then try again
'
Plus, here is the log

app.js:11 [INFO] Returning cached provider yts?&apiURL=https://movies.api-fetch.website/,
app.js:11 [INFO] Returning cached provider TVApi?&apiURL=https://tv.api-fetch.website/,
app.js:11 [INFO] Returning cached provider haruhichan
app.js:11 [INFO] Returning cached provider vodo
app.js:6 [DEBUG] Butter false startup time: 3998.907ms
app.js:21 [ERROR] Error: ENOENT: no such file or directory, mkdir 'C:\Users\username\AppData\Local\Temp; ;<path-to-sdk>\platform-tools\Popcorn Time' Error: ENOENT: no such file or directory, mkdir 'C:\Users\username\AppData\Local\Temp; ;<path-to-sdk>\platform-tools\Popcorn Time'
    at Error (native)
fs.js:55 Uncaught Error: ENOENT: no such file or directory, mkdir 'C:\Users\username\AppData\Local\Temp; ;<path-to-sdk>\platform-tools\Popcorn Time'
app.js:6 [DEBUG] Not updating because we are running the latest version
app.js:6 [DEBUG] 0 cached subtitle
app.js:6 [DEBUG] Cache 44 subtitle
generic_collection.js:26 post all Object Object Array[50]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://movies.api-fetch.website/,
item.js:241 Object "Movie"
app.js:11 [INFO] Show movie detail (tt4094724)
app.js:11 [INFO] Subtitles: none
app.js:6 [DEBUG] Opening: C:\Users\username\AppData\Local\Temp; ;<path-to-sdk>\platform-tools\Popcorn Time

**Comment by ChrisAlderson** [comment]
Looks like Popcorn Time cannot find any files in the `AppData` folder. Please delete any folders relating to Popcorn Time from the `AppData` folder and try reinstalling the application.

**Comment by sulaimanob** [comment]
I deleted butter folder and reinstall the app, but I got the same error.

**Comment by RomainSauvaire** [comment]
Got the same issue here on macOS Sierra (10.12) and popcorn time 3.9.

As soon as it downloads for 10 seconds, it crashes. If I start again, it resumes where it stopped (meaning: if I do it for 10 times, my movie starts to play... then crash).

**Comment by ChrisAlderson** [comment]
@RomainSauvaire your issue has nothing to do with this issue, for more information check #236 

@sulaimanob From the logs it seems like your temp folder has a bit of a weird name. The logs show `Temp;;`, but the correct name should be just `Temp`. Could you please check the name of the folder in `C:\Users\username\AppData\Local`

**Comment by team-pct** [comment]
You seem to have messed a lot your Environment
please check that first
