### ISSUE TITLE
Doesn't show any movies, series or anime

### ISSUE THREAD

**Issue by AcceleRacerz** [popcorntime/popcorntime#2332]
Operating System Version:
 Windows 7

Popcorn Time Version:
 0.4.6

Download date:
 3/11/2021

Download url (optional): 
 https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.6/Popcorn-Time-0.4.6-win64-Setup.exe

#### Expected Behaviour
 I expected to see in each section the movies, series and anime so i can choose which one to download
...

#### Actual Behaviour
 I can't see anything and shows the message : the remote movies API failed to respond, please check and try again later.
...

#### Steps to reproduce the behaviour

1. Download the asset from realeses Popcorn-Time-0.4.6-win64-Setup.exe
2. Install the app
3. Run the app

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
 
![popcorntime](https://user-images.githubusercontent.com/93624027/139964008-edb70bca-464a-4762-bc90-80f3162584ca.PNG)

**Comment by dutchy1001** [comment]
Your ISP could block those listed API's or they are down). You might want to change your API settings to "https://popcorn-ru.tk/" .
The anime section will not work on any API you try to use as far I know.

**Comment by Vrcingetorixs** [comment]
> Your ISP could block those listed API's or they are down). You might want to change your API settings to "https://popcorn-ru.tk/" . The anime section will not work on any API you try to use as far I know.

Thanks, at least the movies are on with the new API
