### ISSUE TITLE
Native window frame option doesn't work

### ISSUE THREAD

**Issue by emmatebibyte** [popcorntime/popcorntime#2334]
Operating System Version:

KDE Plasma on Artix GNU/Linux
Popcorn Time Version:

nwjs 80.0.3987.132 
Download date:

not certain
Download url (optional):

AUR ( https://aur.archlinux.org/packages/popcorntime )
#### Expected Behaviour

...
Display my window decorations from Plasma
#### Actual Behaviour

...
Nothing changed about the window decorations
#### Steps to reproduce the behaviour

1.Open the settings
2. Check the Advanced Settings box
3. Check the Native Window Frame option

**Comment by kiriles90** [comment]
The window titlebar doesnt change at all? Have you restarted the app? Any errors in the console? (F12)

**Comment by emmatebibyte** [comment]
@kiriles90 Correct. I have restarted the application many times.
In the console, I have two errors:
```Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at main_window.js:625```
and
```[ERROR] updater.update() Error: getaddrinfo EAI_AGAIN popcorntime.app
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64)```

**Comment by kiriles90** [comment]
Hmm the second error is not an issue, its just because the .app domain is down. The second one though shows some old/corrupted settings values. Try flushing all your databases and settings (it will clear your bookmarks.db too so back them up first if you have stuff there that you want). If that doesn't help try a clean install of the latest release version (0.4.6)

**Comment by emmatebibyte** [comment]
Flushing database and settings didn't work, and neither did reinstalling the binary from the AUR or the regular package.

**Comment by kiriles90** [comment]
Does the `Uncaught (in promise) TypeError: Cannot read property 'value' of null at main_window.js:625` error still show up too or was this resolved?

**Comment by emmatebibyte** [comment]
> Does the `Uncaught (in promise) TypeError: Cannot read property 'value' of null at main_window.js:625` error still show up too or was this resolved?

It is still unresolved. Apologies for not including that in the last comment.
