### ISSUE TITLE
Building installers/executables that install Popcorntime but it won't launch the application

### ISSUE THREAD

**Issue by ArneAmeye** [popcorntime/popcorntime#2342]
Hello,

I've been following the Github docs as how to run and build PT by myself.
Locally I've been able to use the` yarn build` and `yarn start` commands successfully.

After that I've built a windows 64bit installer with `yarn dist --platforms=win64` and installed it.
It shows the App as installed however when launching it, nothing happens.
I checked windows task manager: There are some instances of "nwjs" running in windows background processes.

Anyone knows what could be wrong? What am I missing here?
If it matters: I have been out of touch for a while, I do come from a really old version if that matters (I did uninstall first).

**Comment by kiriles90** [comment]
Have you tried deleting the `%localappdata%\Popcorn-Time` folder first? It will clear all your settings, bookmarks and marked as watched but that might be necessary since an old/bugged settings value is probably the issue (provided all went well with building)

**Comment by ArneAmeye** [comment]
I did. I found 2 popcorn-time folders, probably from 2 different versions since the very early beginning. Deleted both of them. Didn't make a difference so far. 
During uninstall I also let it delete the settings, preferences and database when it asks for it.

I also started from the master branch, guess that's fine since it's the release branch.

**Comment by kiriles90** [comment]
I see, then the only other reason it would fail to start normally from a clean install is if it didn't build correctly. Not really sure what but if you want you can find the latest dev build in the actions page and compare what you download with what you build from the development branch and hopefully is holds some clues as to what is missing/different.

@ivan1986 any ideas or something we are missing?

**Comment by ivan1986** [comment]
Have not some good ideas
only add error logging in package.json ad see errors
and need check and kill other nw process, may conflict with other

**Comment by ArneAmeye** [comment]
I tried building (win64) from development branch without any code changes, straight from Github (latest commit). Still not working. It launches a bunch of nwjs processes, after like 10min I do kill them before trying again.

Then I built for win32 just for checking. Didn't work either.

My steps after cloning from Github:
1. `yarn config set yarn-offline-mirror ./node_modules/`
2. `yarn install --ignore-engines`
3. `yarn dist --platforms=<platform>`

Output from terminal:
https://pastebin.com/CxmEvUvG

Can't think of anything I'm missing...

**Comment by kiriles90** [comment]
To be honest I'm stumped as well. The only thing I can suggest right now is to compare the contents (modules included) of your build with the same one built by github actions, it might hold some clues (something like WinMerge will do, or just upload your build somewhere and I can check it if you prefer)

**Comment by ArneAmeye** [comment]
Great suggestion, I should've checked the ZIP files in the /build directory first. It seems the "node_modules" in those builded ZIP files only contains the "webtorrent" module. All the rest have not been included. Which makes a lot of sense that it'll fail to run.

Why is it that they don't get included when using the readme build steps? I must forget something simple...
Everything is done through yarn right, no npm install?

**Comment by kiriles90** [comment]
Yeah you need `npm install`

**Comment by kiriles90** [comment]
Yeah try with `npm install`
