### ISSUE TITLE
Favorites tab loading threshold maxed out at 50

### ISSUE THREAD

**Issue by RetroAJ** [popcorntime/popcorntime#2344]
Operating System Version: Windows 11

Popcorn Time Version: 0.4.6

Download date: 11/10/21

#### Expected Behavior
The app loads favorites up until 50 titles.

#### Actual Behavior
Upon scrolling down, it loads more favorites, but at the wrong filter.

#### Steps to reproduce the behavior

1. Have more than 50 favorites.
2. Scroll down, and upon scrolling the year, title, etc will load after the last 50th title.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) 
![Untitled11](https://user-images.githubusercontent.com/5528743/141195153-eb9865fd-8f2a-4990-be02-e27a45d0963e.jpg)
![Untitled22](https://user-images.githubusercontent.com/5528743/141195155-059c5cc3-eedf-4794-beb9-3969e8ea97d6.jpg)

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/2fe168506ee6805cf6d338f84f30cb8aaa8b3b3b fixed that. Update to a newer build.
