### ISSUE TITLE
nothing loads up after the app is launched in windows, even after waiting for a considerable time.

### ISSUE THREAD

**Issue by kamranazam22** [popcorntime/popcorntime#2346]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
<!-- Screenshot helps with finding why stuff breaks --
![Capture](https://user-images.githubusercontent.com/59294607/141510374-28d65291-f0ea-4208-9d05-ea3313fe13f2.PNG)
>

**Comment by dutchy1001** [comment]
First off, this is not a valid issue report.

You should find this API address in the settings under "API Server(s) > https://popcorn-ru.tk/" this should be filled in the the top 2 fields, the Anime will not work with this API (so far they haven't found a working one for Anime yet)
Make sure your ISP isn't blocking the API 
If your ISP does block the API then I suggest to use a VPN.
