### ISSUE TITLE
Butter player's estimated time for download should show time in hours, minutes and seconds

### ISSUE THREAD

**Issue by svineet** [popcorntime/popcorntime#235]
Operating System Version:
Linux

Popcorn Time Version:
3.9

Download date:
About two weeks ago

#### Expected Behaviour

In the Butter player, hovering on the eye icon shows status of the download. The estimated download time should show time in hours minutes and seconds, so that I can let it buffer for some time before I start watching (eg if an episode is 1hr 5min long, I will let the timer run down to 1hr 5min before I start watching it so that it doesn't stutter in between)
#### Actual Behaviour

The time shown is only in hours, and minutes/seconds details are not shown, so I cannot guess what time I should actually start watching.
#### Steps to reproduce the behaviour

1. Start a download, and use butter player.
2. Hover on the eye icon on the butter player
3. See "X hour(s) remaining" portion.

**Comment by TakenKing** [comment]
I will look into this
