### ISSUE TITLE
sorting by stars

### ISSUE THREAD

**Issue by vpicouet** [popcorntime/popcorntime#2350]
Would it be possible to add the possibility to sort movies by grades (stars)?
Thanks for the work!

**Comment by dutchy1001** [comment]
isn't that the "rating" option you have by "sort by"??

Click it once it's high to low, click again it's low to high.

**Comment by vpicouet** [comment]
Well I can only sort by popularity/date/title...
But popularity is not the estimated based on the stars (maybe on the views?).
Anyway, as every movie as an associated number of stars, I feel it would be very interesting to be able to sort the movies by stars.

![image](https://user-images.githubusercontent.com/37241971/143784023-34d05edb-044f-4168-94ff-b112b89a0450.jpeg)

**Comment by dutchy1001** [comment]
in that case you should have mentioned (filled in the form that comes with the request) what version and/or what device you use.

I cant help you any further with this as I only do windows.

**Comment by vpicouet** [comment]
Sorry! version 6.1.2 on Mac OSX Monterey

**Comment by dutchy1001** [comment]
this is why I prefer windows over mac :)

**Comment by kiriles90** [comment]
> version 6.1.2

@vpicouet You are using a different app, this one only goes up to version 0.4.6 :)
Closing this issue but feel free to continue the conversation below if you need something else or a better explanation etc.
