### ISSUE TITLE
Bug - PopcornTime requesting none existent update

### ISSUE THREAD

**Issue by LegendsShallDie** [popcorntime/popcorntime#2351]
Hi, I've encountered a new problem, I currently have popcorn time 6.2.1
as I stated, popcorn time is requesting a none existent update for a newer version.

So far I've tried:
restarting the computer.
uninstalling and reinstalling the program.
changing DNS server to google to see if it's country limits for some reason.

I have no results so far and the problem remains the same, any idea what can I do?
Adding a photo of the problem -

![308550442c0a1751f1daa51aa9f0bce4](https://user-images.githubusercontent.com/69143109/143950492-58a4c75d-dbd6-4e4d-9454-bfd92d4c13d2.jpg)
![308550442c0a1751f1daa51aa9f0bce4](https://user-images.githubusercontent.com/69143109/143951187-c2bcf404-1898-4152-a6e5-a5414d23b11f.jpg)

forgive me for not putting labels correctly, I don't use GIT often

**Comment by dutchy1001** [comment]
I think you have the wrong Popcorn GitHub page, this version only goes as far as version 0.4.6.
