### ISSUE TITLE
Cannot open any version of Popcorn Time on MacOS 12.0.1 

### ISSUE THREAD

**Issue by Cheenybaba** [popcorntime/popcorntime#2352]
Operating System Version: MacOS 12.0.1 

Popcorn Time Version: 0.4.6

Download date: September 2021

Download url (optional): 

#### Expected Behaviour: Should have opened like it did on Big Sur

...

#### Actual Behaviour: Instead it would pop up on my app dock at the bottom then disappear. 

...

#### Steps to reproduce the behavior

1. ...Open it in MacOS Montery 
2. ...See if it loads
3. ...

**Comment by dutchy1001** [comment]
invalid report
