### ISSUE TITLE
 I use popcorntime socks5 proxy like this in archlinux

### ISSUE THREAD

**Issue by kindusmithkindu** [popcorntime/popcorntime#2353]
I hope it's useful for you:

Edit the "/usr/share/applications/popcorntime.desktop" file 
Add "--proxy-server="socks5://127.0.0.1:1080" %U " at the end of the line with "Exec=popcorntime"

**Comment by kiriles90** [comment]
Thank you for sharing. If you want you can create a Wiki page for it and any other related info.

Closing this since its not an open issue.
