### ISSUE TITLE
Can't seem to cast content any more.

### ISSUE THREAD

**Issue by miltoid19** [popcorntime/popcorntime#2357]
Hello. 
I don't seem to be able to cast my content on the TV. It worked just fine a few days ago but suddenly it stopped.
So far I have tried re-installing the app, running as an administrator, and stopping any other app from opening before popcorn time but still nothing,
Any help would be greatly appreciated.

Operating System Version:
Windows 11

Popcorn Time Version:
v0.4.6 (Fresh install)

Download date:
5-12-2021

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.6/Popcorn-Time-0.4.6-win64-Setup.exe
(official download link for the last release)

#### Expected Behaviour
Cast movies/episodes on my TV

#### Actual Behaviour
Nothing happens 

#### Steps to reproduce the behavior

1. Open popcorn time on desktop
2. Select the icon to stream the content on the TV and then hit play
3. wait in vain as the app says it's streaming that the TV does nothing 

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![Logs](https://user-images.githubusercontent.com/40575135/144746311-019307c3-3506-4620-9539-6f7cb4d2f9e8.png)

**Comment by kiriles90** [comment]
Delete the `%localappdata%\Popcorn-Time` folder and reinstall 0.4.6. Also try restarting all the devices involved (tv,pc,router)

**Comment by kiriles90** [comment]
Closing this issue since its not an issue with the app (nothing changed) but feel free to reply below if it continues.
