### ISSUE TITLE
Popcorn time quits on mac os 10.12 when downloading/viewing a movie

### ISSUE THREAD

**Issue by jellever** [popcorntime/popcorntime#236]
Operating System Version:
OS X 10.12

Popcorn Time Version:
0.3.9

Download date:
25-09-2016
#### Expected Behaviour

Play movies through torrents
#### Actual Behaviour

Quit without warning! When streaming to Chromecast it doesn't even start playing, it just quits when the initial download finishes. When streaming to the popcorn time video app or VLC it plays a bit and than quits.. Didn't have this behaviour on mac os 10.11
#### Steps to reproduce the behaviour
1. Get mac os Serria 10.12. 
2. Play any movie with popcorn time video app/ vlc or chrome cast

**Comment by ipoznyak** [comment]
Yep. It does quits unexpectedly every time. Is there a fix for that?

**Comment by Mariamhb** [comment]
I have the same problem

**Comment by mosbid** [comment]
I have the problem too

**Comment by ArtsiomSadyryn** [comment]
I also have this problem. But if i stream video file from torrent file (not from built-in library) problem in most cases don't appear (after i reinstall app).

**Comment by asadyryn** [comment]
I also have this problem. But if i play movies/TV series through torrents app still quit without warning in first time. After that i open app back and play though torrents and app already doesn't quit (in most cases).

**Comment by pbassut** [comment]
Same problem here.

**Comment by pbassut** [comment]
#231 is related

**Comment by chuan-su** [comment]
+1

**Comment by jajacobs** [comment]
Hi, i had the same problem. I just went to the settings page and flushed the database and everything works fine now.

**Comment by NE03N** [comment]
it's been too long! why is no one looking into this?

**Comment by fihsar** [comment]
I'm waiting XD

**Comment by aersoares81** [comment]
It also crashes for me. I decided to build it myself so I could see the errors it spits on the prompt when you 'grunt start' it. It spits A LOT of errors. The first one is
`>> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
`
But I'm not sure some of them might be due to me building the app myself, considering Sierra is not very mess-with-usr/local friendly.
Some other errors:

```
>> [14460:1013/115819:INFO:CONSOLE(5)] "Uncaught SyntaxError: /Users/xxx/popcorn-desktop-development/popcorn/node_modules/unzip-response/index.js:5
>> module.exports = res => {
>>                      ^^
>> Unexpected token =>", source: /Users/xxx/popcorn-desktop-development/popcorn/node_modules/unzip-response/index.js (5)
```

`>> [14460:1013/115827:INFO:CONSOLE(16)] ""[%cWARNING%c] Unable to find %s (%s) on Trakt.tv" "color: orange;" "color: black;" "tt0903747" "Breaking Bad"", source: app://host/src/app/app.js (16)
`
(This happens for all series it pre-opens on the Series screen)

```
>> Exited with code: 11.
Warning: Task "exec:osx32" failed. Used --force, continuing.

Done, but with warnings.
```

**Comment by mauscoelho** [comment]
+1

**Comment by team-pct** [comment]
Please test https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/150/

**Comment by fihsar** [comment]
How about the subtitles for chromecast?

**Comment by ChrisAlderson** [comment]
This issue should be fixed with #223

**Comment by Liupigo** [comment]
same problem +1

**Comment by pbassut** [comment]
@ChrisAlderson It's not merged yet tho, right? Shouldn't we close this only when the it gets merged?

**Comment by ChrisAlderson** [comment]
A CI build is up with the fix, which I consider good enough to close this issue.
