### ISSUE TITLE
popcorn pge will not load anything!!!! it just shows blank page with loading   circle

### ISSUE THREAD

**Issue by natluv4u** [popcorntime/popcorntime#2360]
![Screenshot (4)](https://user-images.githubusercontent.com/76500132/145116594-78325809-7b07-49f4-9548-e9631ab4c3b4.png)

**Comment by natluv4u** [comment]
PLEASE FIX THIS ASAP!!!! PLEASE

**Comment by dutchy1001** [comment]
First off, this is not a valid report.

Update your api sources in the settings to the ru.tk and it should work.

If that doesn't fix it the your ISP might be blocking the app. 
you need a VPN then

**Comment by Kief5555** [comment]
> ![Screenshot (4)](https://user-images.githubusercontent.com/76500132/145116594-78325809-7b07-49f4-9548-e9631ab4c3b4.png)

That is not how you open an issue on github. No developers are going to respond.
