### ISSUE TITLE
Incorrect streaming of episodes

### ISSUE THREAD

**Issue by perryaa** [popcorntime/popcorntime#2363]
With the TV shows, Hanna and Alex Rider, The Beatles Get Back, they all fail to download any episode past episode 1, even though, you may click on the third episode to watch, it will say you are in the header, but if you look at what is actually streaming down it states E1 or episode 1. The link from what is wanted is either corrupt or misaligned to episode 1 and that is what actually downloads! Maybe there is no episode 2 etc available from 3rd party and it just links back to E1? Who is the 3rd party that downloads movies and TV series?

Any answers?

**Comment by kiriles90** [comment]
Hi, which version are you using and what resolution are you trying these with? I just tried all of them running version 0.4.7 and 1080p selected and they all download episode 1 & 2 normally.
