### ISSUE TITLE
App crashing when trying to open on Mac

### ISSUE THREAD

**Issue by seran-shan** [popcorntime/popcorntime#2366]
Operating System Version: macOS Monterey 12.0.1

Popcorn Time Version: 0.4.6

Download date: 20.12.21

Download url (optional): With brew

#### Expected Behaviour
Open as normal

#### Actual Behaviour
Crashing when opening

#### Steps to reproduce the behaviour

1. Try opening app on Mac

**Comment by kiriles90** [comment]
Closing because duplicate of #2365 (and of many others). Also needs #2062 to be resolved like I mentioned in the rest.

**Comment by Kief5555** [comment]
https://youtu.be/3IZid6lBMJM I have a fix, you can watch from the link.

**Comment by saintpepsicola** [comment]
thanks @Kief5555 . This should be built in

**Comment by jlrodriguezdev** [comment]
@Kief5555 Thanks you, Is working, good tutorial but need to delete old version from Applications folder 🙏🏽

**Comment by Kief5555** [comment]
@saintpepsicola @jlrodriguezdev Your most welcome.

**Comment by icavot** [comment]
I have similar problem from a few days
In my case I have the last update of Monterrey and v04.7. Popcorn-Time
¿Do you have any solution on this? ¿Can I test this solution for these versions?
Thanks!

**Comment by fulcus** [comment]
@Kief5555 video has been removed

**Comment by Kief5555** [comment]
> @Kief5555 video has been removed

Read the wiki then
