### ISSUE TITLE
App does not working

### ISSUE THREAD

**Issue by fariasmateuss** [popcorntime/popcorntime#2367]
Operating System Version:
Ubuntu 20.04 LTS

Popcorn Time Version:
Latest

Download date:
21/12/2021

Description: Right after installing and running it gives error: "the remote movies API failed to respond".

![image](https://user-images.githubusercontent.com/55674918/147158166-4a0c2eee-9dce-4b5e-b3e0-950e5c280faa.png)

And I searched too and no other address and the site is responding... are there any other alternatives?

**Comment by kiriles90** [comment]
Click the 'Change API Server' button and input and different server (or select one of the currently suggested ones)

**Comment by Umeaboy** [comment]
@fariasmateuss Is it working when you change to the other in the list when you click on "Change API Server"?

**Comment by kiriles90** [comment]
@Umeaboy yours isn't? Is the custom API server also blocked by your ISP?

**Comment by fariasmateuss** [comment]
Yep cc @Umeaboy

**Comment by Umeaboy** [comment]
> @Umeaboy yours isn't? Is the custom API server also blocked by your ISP?

Nope. If something's blocked I use VPN.

**Comment by Umeaboy** [comment]
> Yep cc @Umeaboy

I guess we can close this then.

**Comment by Umeaboy** [comment]
> Yep cc @Umeaboy

Good. :)
