### ISSUE TITLE
Trakt authentification don't work

### ISSUE THREAD

**Issue by Persei08** [popcorntime/popcorntime#237]
Operating System Version:
Linux Ubuntu 15.10 64bits

Popcorn Time Version:
[build 139 from ci.popcorntime.sh](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/139/)

Download date:
Just now
#### Expected Behaviour

A window should open where i can submit my trakt authentification informations and then being authentified
#### Actual Behaviour

A window appear and instantly close itself
#### Steps to reproduce the behaviour
1. open PCT
2. go to settings
3. click "Connect to Trakt" button
#### Developer Tools messages

[DEBUG] Trakt sent back no token

Also, it seem it's happened to other users on reddit:
https://www.reddit.com/r/PopCornTime/comments/4d8ea6/trakttv_bug_on_linux/
https://www.reddit.com/r/PopCornTime/comments/3ylraf/error_connecting_to_trakt_linux/

Thanks

**Comment by BrUn3y** [comment]
I have five months to try fixed and search the solution but i can't. I think anyone is working in this part. We hope someone has the solution, My operating system is ubuntu 16.04 64-bits and is the same problem

**Comment by ChrisAlderson** [comment]
Should be fixed with #223

**Comment by kemelzaidan** [comment]
I'm having this exact bug right now, on version 0.4.1-4

**Comment by ChrisAlderson** [comment]
Not our version, not our problem.
