### ISSUE TITLE
remote movies API failed to respond.

### ISSUE THREAD

**Issue by alb277** [popcorntime/popcorntime#2371]
Operating System Version: 
 OS Big Sur 11.6.1.
Popcorn Time Version: 
 6.1

Download date: 
 25/12.21 new version as the older one could not be updated

Download url (optional): 
  http://popcorn-ru.tk/build/dev/

#### Expected Behaviour
 load movies
...

#### Actual Behaviour
 didn't load anything
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
change API server in the settings.
If that doesn't help your ISP might block it

Edit:
After seeing your version of 6.1 I think you have the wrong popcorn page. The latest version on here is 0.4.6
