### ISSUE TITLE
Add a my video for NWJS in readme.md

### ISSUE THREAD

**Issue by Kief5555** [popcorntime/popcorntime#2373]
I made a video for crashing fix. https://youtu.be/3IZid6lBMJM Please add it to readme.md so people can fix it

**Comment by kiriles90** [comment]
I hope you werent the one who kept defacing the wiki home by adding the readme file below and altering the links. I'll create a wiki page later for it and you can add whatever you want in it (as long as its helpful info :) and tell you.

**Comment by Kief5555** [comment]
Hi, just published page. No, I wasn't the one that kept defacing the wiki home by adding the readme file below it and altering the links.

**Comment by kiriles90** [comment]
Nice! Sorry for being suspicious btw, nothing personal it was just that you posted this a couple of hours after I locked the Wiki (guy altered it for the 4th time this month with 4 different accounts..)

**Comment by Kief5555** [comment]
Oh, I see lol, atleast the guy tried, can you link the page to the readme btw?
