### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by florisdipt** [popcorntime/popcorntime#2374]
Operating System Version:
macOS 12.1

Popcorn Time Version:

Latest as of Jan 1 2022(Post date)

Download date:

Post time

Download url (optional):

Instructions on repo:
brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time

#### Expected Behaviour

Installs application

#### Actual Behaviour

Fails with:
Error: No such file or directory @ rb_sysopen - /Users/floris/Library/Application Support/Popcorn-Time/Default/data/settings.db

#### Steps to reproduce the behaviour

1. Use brew to install popcorn time

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/55819399/147857381-675266b6-40a4-444c-868c-c2cd9fedad4b.png)

**Comment by kiriles90** [comment]
How about now? (cant test it, not a macOS user..)

**Comment by kiriles90** [comment]
How about now? (merged https://github.com/popcorn-official/popcorn-desktop/commit/ed6d58a9fa07c727bc1969c47e5b50eb3f03492e but cant test it, not a macOS user..)

**Comment by florisdipt** [comment]
> How about now? (merged [ed6d58a](https://github.com/popcorn-official/popcorn-desktop/commit/ed6d58a9fa07c727bc1969c47e5b50eb3f03492e) but cant test it, not a macOS user..)

That was quick!
Thanks

I had already installed using the .dmg/.app way of installing, so i removed that and then removed the file that we saw in the error.

Reinstall using brew worked. 
For me this is solved!
Might still be worth investigating using a fresh install of MacOS which popcorn time hasn't touched yet because maybe there's some other files that could create a simular issue.
All my Apple blessed PC's have already got popcorn time and I do not have a macOS VM setup at this time, so i wont be able to do it with a fresh install of the OS.
If someone could let me know all the places popcorn time saves data I can remove it all and verify fully.

![image](https://user-images.githubusercontent.com/55819399/147861199-00366103-6cce-45a1-8353-537f9e88f5d4.png)

**Comment by kiriles90** [comment]
I think we should be ok even with a completely fresh install, that error was specific about settings.db and that's also the only one mentioned in that section of [/casks/popcorn-time.rb](https://github.com/popcorn-official/popcorn-desktop/blob/development/casks/popcorn-time.rb)

Closing this for now but will keep an eye out in case someone re-opens the same issue.
Thank you for verifying!
