### ISSUE TITLE
API Servers and Website down

### ISSUE THREAD

**Issue by Nycz-lab** [popcorntime/popcorntime#2377]
The default API Servers as well as the Website seem to be down:

- https://movies-v2.api-fetch.sh
- https://tv-v2.api-fetch.sh
- https://anime.api-fetch.sh

[These are the default Servers. The other options for the API Servers seem to be working but there is no other option for Anime]

Operating System Version:
Win10

Popcorn Time Version:
0.4.6

Download date:
06/01/2022

Download url (optional):
GitHub Releases: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.6/update-0.4.6_win64.zip

#### Expected Behaviour
Contact Api servers and retrieves information
...

#### Actual Behaviour
Telling me a connection couldnt be established since servers are down
...

#### Steps to reproduce the behaviour
Download from Releases then start the app and see for yourself

**Comment by kiriles90** [comment]
Yes we know, this isn't an issue with the app its an issue with the default API (its down..)
Use one of the other APIs. As for Anime when an API server exists it will also be added in that list in the app (or if support is added for an existing but incompatible API).

**Comment by Leoxur** [comment]
![image](https://user-images.githubusercontent.com/9626769/150874523-96fced41-4168-4e10-9035-064bc87c011e.png)

I've got same issue with 0.4.6 version

**Comment by veselipastir** [comment]
I have issue with servers now for everything , tried alternate api servers suggested for movies and no luck .
none of these work now :(
https://movies-v2.api-fetch.sh/
https://movies-v2.api-fetch.am/
https://movies-v2.api-fetch.website/

**Comment by dutchy1001** [comment]
If both of you did some research on these pages here you would have found that you should change it to "https://popcorn-ru.tk/" (without the quotes).

This is the reason it's closed as the answer is already given many times...

**Comment by veselipastir** [comment]
Thanks on the answer :)

**Comment by AndroidDeveloperLB** [comment]
@dutchy1001 Where did you read it? For anime, I still don't see it working.
v0.4.8 with https://popcorn-ru.tk/ set for anime.

**Comment by dutchy1001** [comment]
@AndroidDeveloperLB 
Anime has not been working for a long time, as far I know this is an API issue that is out of our hands.

**Comment by AndroidDeveloperLB** [comment]
@dutchy1001 Oh ok. Thanks
