### ISSUE TITLE
Improved caching system

### ISSUE THREAD

**Issue by SeDemal** [popcorntime/popcorntime#2379]
Some of us use the app alone on PC, some of also use other services when watching with family or friends.
As the same spirit of popcorn, we have plex, and as much as popcorn time downloads and caches content, plex could use it.
 
Now plex rose the problem that it needs multiple directories for effective filtering of ones library even if just movies and TV shows.
I like to keep everything I download from popcorn time, so that I or someone else could watch it later on.
But if not accessing from popcorn time directly, navigating the files is a pain.

The saving/caching system is simple, too simple.
Everything goes in one folder, popcorn time knows what everything is and where to find it.
But don't you dare changing anything otherwise popcorn time won't recognize it and will download it again.
Other apps might have a hard time navigating it and so do I.

Even in the case that you don't think you'll need to access it from popcorn time anymore afterwards, you still do need to arrange and clean everything by yourself.

Now my idea is to have a better caching system with subfolders.

Movies into a movies folder and TV shows into a shows folder to begin with.
From that point on, Plex is already smart enough to just do it by itself.

But in reality, it could be improved further.
On the tv show side, each tv show gets its own folder named after the show, and all season would be inside that one.
That could also be applied to the movies, so that we are not left with the very long folder names that torrent usually gives you.

Further improvements in the caching system could be thought of but in my opinion, having those 2 options would massively improve the manageability of the files without taking it away from popcorn time and taking the users time.

Quite frankly, I thought of ditching popcorn time for a custom NAS system but it would be much better if those kind of system could just coexist.

Although I have talked a lot about Plex, this is not only about both apps being compatible but also just so that my collection isn't a total mess.

**Comment by dutchy1001** [comment]
> But if not accessing from popcorn time directly, navigating the files is a pain.

You can change the location (in the settings) to a more convenient location to make access easier or place a shortcut on your desktop.

> But don't you dare changing anything otherwise popcorn time won't recognize it and will download it again.

Use the folder you set and watch the movie/series with a 3rd party player like VLC or SM player.
If doing it that way it wont download again or even need popcorn time running.

I like the idea that movies and series go in there own folder but as I'm not a coder I don't know how much work this will create and if it's even possible as this can be depending on the API's that they are using.

> Quite frankly, I thought of ditching popcorn time for a custom NAS system but it would be much better if those kind of system could just coexist.

Even with a NAS you have to get the files from somewhere.
I have set my "watch" and "download" location to my NAS, this way other family members (wherever they are in the world) can watch what ever I have watched, they even ask me to "download" movies/series they like.

Who needs PLEX lol

**Comment by SeDemal** [comment]
The location isn't the problem, like explained it's that all the files are chucked into **one** folder completely unorganized,
and unorganizable if you want to continue using those files on popcorntime.

The point is to have it be organized and automatically.
Without the need to use popcorn time as just a downloader and then another service.

As to how to programmatically implement it, whenever you have to handle files you point to it with a path, this can be implemented by adding a few steps in the path composition. Simply do :
Cache directory path + "\\" + \<movie> or \<shows> + "\\" + \<name of show or movie> + "\\" 
Usually that's all you need to do.

My point about the NAS exactly is that you can get it from somewhere else, I just which for popcorn time to complement it along with the app just having a clean caching.
Just to say that I could go around and just put popcorn time away, but I'd rather try improving it first.

And also, if I'm watching on my TV, I do need plex. It's available everywhere easily since it's legal (Android, Apple, Fire stick, really almost anything).
Popcorn time is mostly a desktop app, personally it crashes on all my android devices, android TV included.
Casting isn't the best, and not just from popcorn time.

I'd like it all to coexist rather to be one or the other.

**Comment by kiriles90** [comment]
So all this is to basically say you want seperate directories for movies and series? Seems to me that plex is the one having the issue if it cant recognize what whatever its indexing is (based on imdb code etc) and requires seperate directories for something like this..

**Comment by SeDemal** [comment]
I want the file to be ordered instead of everything in a mess in 1 folder.
Plex is just an example of why it would otherwise be useful too.

"all this" explained exactly what I wanted, which isn't just separating cache for movies and tv shows.
I also agree that on Plex's part, needing it is a bit stupid when it's already capable of so much. But as explained earlier, this just made me aware of how messy the caching system is and how it could be improved.

**Comment by kiriles90** [comment]
Movies already go in their own subfolders with covers, subtitles, etc for both the 'Watch now' and 'Download' functions. Most series do too though this part is inherently a bit messy due to some being full season(s) torrents and some singular episode ones. I don't see how just separating these two will untangle some terrible mess we currently have.. (also some might not want them separated? they are both 'media' after all..)

**Comment by SeDemal** [comment]
I feel like we're going in circles there, the point is to organize a completely non organized cache folder.
Not just for the ease of use for other platforms but to allow the user to have an organized database.
It's not about "watch now" and "downloads" being separated.

I've tried to illustrate what I mean, first is how it currently is (movies and shows mixed up), and second is organized tree version:
![image](https://user-images.githubusercontent.com/26098587/149425723-b4648f87-6929-4883-979c-cad65cf43dda.png)
![image](https://user-images.githubusercontent.com/26098587/149425662-2df09076-40bd-49b0-8d43-b7bab0a76140.png)

I understand that the torrents themselves bring a folder structure that ultimately makes things messy anyway, but this way there is at least some amount of order.

And as for the last point, that's true, maybe some people won't want it. I don't see reasons why but there might.
So it could be optional. A tick box the same way there is one to separate "watch now" from "downloads" for those who want that.

**Comment by SeDemal** [comment]
It wouldn't just be separating the movies from the series but also providing a sub folder structure for series too.
Like shown in the screen shot, all the files for one tv show would be under a folder that harbors the tv show's name.
Then even adding seasons sub folders.

I'm trying to look at the code myself but I'm not really familiar with the code nor with the language.
If I find the way I'll post about it but I it shouldn't add too much to it.
