### ISSUE TITLE
Subtitles in two languages?

### ISSUE THREAD

**Issue by le9i0nx** [popcorntime/popcorntime#238]
#### Feature Requests

I would be glad.
if there would be an opportunity to display subtitles in two languages simultaneously.
I need it for the study of another language.

**Comment by MeiLinLee** [comment]
I will look into this.

**Comment by thomasbrodusch** [comment]
That's a great idea @le9i0nx !
@MeiLinLee you can get some inspiration for the behavior and UI/UX of that feature from [Fleex](http://fleex.tv) , a PopCornTime like.

![capture d ecran 2016-10-25 a 16 29 53](https://cloud.githubusercontent.com/assets/3238312/19690237/490d40e8-9ad0-11e6-873a-4dd8b4934ab7.png)

If you need someone to work with you, I'm here :)

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/subtitles-in-two-languages/100

**Comment by RyanPaulMcKenna** [comment]
I can help with this if you like as I would love to see this future too. I don't know you UX but I have decent web programming experience.
