### ISSUE TITLE
A toggle - Continue downloading when movie is paused

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2385]
**Is your feature request related to a problem? Please describe.**
Sometimes we have issues with connection, either because of number of seeds or our own internet connection issues. 

When connection drops and we minimize the player to do something else in the meantime, the player doesn't continue caching the video and there is no toggle to enable or disable this. 

In other cases there might be people that want to pause downloading when they pause a video, because they have other programs requiring connection, and in that case pausing a video does should also pause a caching/downloading in advance.

**Describe the idea you'd like**
A toggle in the settings "Continue caching when paused?" [x]
This could be enabled by default and unchecked if anyone needed it to pause.

**Additional context**
This way, both sides of the issues would be fixed, if we had the option to change this preference in my opinion.

**Comment by kiriles90** [comment]
The player does continue caching the video even when the movie is paused. Try it with one that has good health to avoid the issue being no seeds and see. Closing this.
