### ISSUE TITLE
Retry button for "A network error caused the video download to fail part-way."

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2386]
**Is your feature request related to a problem? Please describe.**
When some sort of network error occurs, it pauses the video and shows the following message: ""A network error caused the video download to fail part-way."
If we want to continue watching the video, we have to close it first and then reopen it, which starts caching again from the start.

**Describe the idea you'd like**
A visible button below the error message, named "Retry connection" or something between those lines, that would try to establish the connection again from that point, that would try to continue the video without needing you to close the video, and restart it. This would be especially useful if we're having a bad connection already, or low seed count.

**Comment by kiriles90** [comment]
It does not start caching from the start. If you exit the player and open the same movie again you will find it continues from the % it was before. (ofc without exiting the app if you have 'clear cache on exit' enabled)
