### ISSUE TITLE
Text is not visible enough: "A network error caused the video download to fail part-way."

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2387]
**Is your feature request related to a problem? Please describe.**
If network connection error occurs, you get a pop-up message window saying ""A network error caused the video download to fail part-way." This message in in such a font and background, that the font is very hard to read and you have to focus closely to be able to read what it says. The text is in grey color, while the background is in dark transparent grey.

**Describe the idea you'd like**
Make the error text more visible in front of that background.

**Comment by kiriles90** [comment]
Select a diffent theme. This is not an app issue its a s
