### ISSUE TITLE
Toggle in settings - start caching next episode [series] automatically

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2388]
**Is your feature request related to a problem? Please describe.**
If we have a bad connection or the seed count is low, the episodes may be loading slowly and you have to wait again when watching the next episode, for example.

**Describe the idea you'd like**
A toggle in settings that would enable caching/downloading the next episode automatically after the one you are watching is downloaded/cached.

**Comment by kiriles90** [comment]
So basically the 'Download' button instead of 'Watch now'. Also this might do more harm than good if impemented like you want. (e.g someone has a bad internet connection, or its a full season torrent with low seeds.. now it has to download 2 episodes with that at the same time, not just the one you're watching)

**Comment by aha999** [comment]
Not at the same time... First it could download the one you are currently watching, THEN it would download the next one that you haven't seen yet. This would go up to 1 next episode.

**Comment by dutchy1001** [comment]
The most simple solution is just to hit the download button for (E.G.) for episode 2, hit "backspace" button on your keyboard and start "watch now" episode 1, etc etc for the coming episodes.
No coding needed  😅 😅

**Comment by kiriles90** [comment]
Basically what @dutchy1001 said. You can also uncheck the 'Show the Seedbox when a new download is added' option in the settings and you wont even have to hit 'backspace'. Then this can be extended for any number of episodes that you want not just the next one, or none.

**Comment by dutchy1001** [comment]
> 'Show the Seedbox when a new download is added'

Even I learned some today 😅 😅

**Comment by kiriles90** [comment]
Its a somewhat recent option https://github.com/popcorn-official/popcorn-desktop/pull/2203 :smile:

**Comment by kiriles90** [comment]
@aha999 Btw, now that I think about this, there is a way to add a bit more (good imo) automation. The 'Play next episode automatically' option in the settings. By default if you have it enabled it starts preloading the next episode 60 seconds before the one you are watching ends ([/src/app/lib/views/player/player.js#L261](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/player/player.js#L261)). How about if we change that value to a variable and expose it in the settings page for the user to change to any value? Then you could e.g start preloading the next episode 10minutes before the current one finishes. Or from the start (30 seconds from the start) if the value you have is bigger than the episode's runtime. Thoughts?

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/2389 merged.
New builds will be ready in the 'Actions' page in 10-15 minutes.

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/2389 merged.
New builds in the 'Actions' page in 10-15 minutes.
