### ISSUE TITLE
Video/Audio gradually out of sync as movie plays

### ISSUE THREAD

**Issue by tiffanyhaltom** [popcorntime/popcorntime#239]
Operating System Version:

Mac - experienced it on Yosemite and El Capitan 

Popcorn Time Version:

3.9

Download date:

August
#### Expected Behaviour

Audio and video stay synced throughout movies/tv
#### Actual Behaviour

Begins to become out of sync around halfway through any movie/tv show. 
#### Steps to reproduce the behaviour

1. Watch any movie - begin to notice video ahead of audio, gets worse throughout movie

**Comment by MeiLinLee** [comment]
I'd been checking into the forums and most bugs are Mac related, hopefully we can fix all of these issues :+1:

**Comment by juanmacio** [comment]
I have the same problem on Ubuntu 16.04.

**Comment by ChrisAlderson** [comment]
Cannot reproduce

**Comment by juanmacio** [comment]
WTF

**Comment by Fort01** [comment]
still a problem at version 3.10. 
I am running windows 10 pro
