### ISSUE TITLE
Why not keep the search textbox open?

### ISSUE THREAD

**Issue by joeytwiddle** [popcorntime/popcorntime#2391]
**Is your feature request related to a problem? Please describe.**
I don't use the keyboard shortcuts yet.
When I want to search for something, I have to click the search icon to open the Search box.
That icon is small. But this is such a common feature, I would prefer a larger target to click on: the textbox itself!

**Describe the idea you'd like**
I suggest we just keep the Search textbox open at all times.

Is there any reason to keep it closed?

Services like Netflix and even GitHub have the search box open and ready to use, most of the time. (Edit: Actually I was mistaken. Netflix doesn't!)

I think most displays have enough width, and those that don't will have a problem opening the search box anyway!

![Screenshot_20220204_161445](https://user-images.githubusercontent.com/911799/152494716-b4bd00f7-6b91-4f63-a50f-5c4866d21e04.png)

#ux

**Comment by kiriles90** [comment]
Some users with less than full hd resolution or UI scalling on will have issues. The filterbar is already crowed enough and one extra click isnt such a chore imho.
