### ISSUE TITLE
Urgent - move rarbg to api

### ISSUE THREAD

**Issue by rarbg** [popcorntime/popcorntime#24]
Hello
We got thousands of reports of users being blocked from accessing your site because of our bot protection blocking them after using your popcorn time.
I see that your app is not using our api but rarbgunblock to perform the search queries in the torrent collection
Please switch to our official api asap. Docs here http://torrentapi.org/apidocs_v2.txt

**Comment by talas9** [comment]
This is the addon should be edited:[https://github.com/team-pct/rarbg-api](https://github.com/team-pct/rarbg-api)
And this is a fork of the modified one: [https://github.com/talas9/rarbg-api](https://github.com/talas9/rarbg-api), I'm not so familier with GitHub, but i hope what i did is correct by creating the pull request :)
