### ISSUE TITLE
Popcorn time no longer works on new mac os(Sierra)

### ISSUE THREAD

**Issue by tchristofferson** [popcorntime/popcorntime#240]
Operating System Version:

macos sierra
Popcorn Time Version:

3.9
Download date:

not long ago was still most recent version
#### Expected Behaviour

...play the video without crashing
#### Actual Behaviour

...crashes loading video
#### Steps to reproduce the behaviour

1. ...open popcorntime
2. ...click movie and click watch now
3. ...as it downloads or start watching it crashes

**Comment by ChrisAlderson** [comment]
Fixed in 0.3.10
