### ISSUE TITLE
TV Shows "Health Unknown" and Unable to Connect

### ISSUE THREAD

**Issue by benjaminalgreen** [popcorntime/popcorntime#241]
Operating System Version: OSX 10.10

Popcorn Time Version: Newest

Download date: Oct. 3

#### Expected Behaviour

Expected the app to show torrent status for TV Show, and Connect when playing it. 
#### Actual Behaviour

On some shows (about half) the torrent status shows "health unknown" and it fails to connect to the file when trying to open it. 
#### Steps to reproduce the behaviour

Open Poldark (as an example), view any of the files in Season 2 and check the torrent health or try to connect.

**Comment by ChrisAlderson** [comment]
The health unknown is a non-issue. The issue with the connection failure might be because you don't have access to [extratorrent](https://extratorrent.cc/).
