### ISSUE TITLE
Homebrew "Error: Cask 'popcorn-time' is unavailable: No Cask with this name exists."

### ISSUE THREAD

**Issue by AdrienM76** [popcorntime/popcorntime#2410]
Operating System Version:
MacOS 11.6.3 BigSur

Popcorn Time Version:
was 0.4.4, removed trying to upgrade to 0.4.6

Download date:
2/9/22 15:15 CST-US

#### Expected Behaviour
Homebrew would install v0.4.6

#### Actual Behaviour
Homebrew reports:
Error: Cask 'popcorn-time' is unavailable: No Cask with this name exists.

#### Steps to reproduce the behaviour
Follow steps in Readme for MacOS install:
1. brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
2. brew install --cask popcorn-time
3. get error returned

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![Screen Shot 2022-02-09 at 3 24 06 PM](https://user-images.githubusercontent.com/19876193/153292775-6aec58ed-8535-437d-b837-d7440f77b469.png)

**Comment by kiriles90** [comment]
But it does. Check https://github.com/Homebrew/homebrew-cask/issues/71221 in case you find something there but this is a brew issue not Popcorn Time's.

**Comment by 13singhjaskirat** [comment]
Same for me I can't install popcorn-time from homebrew. Please open this thread again.
