### ISSUE TITLE
Mac Crashing

### ISSUE THREAD

**Issue by ber33** [popcorntime/popcorntime#243]
Operating System Version:

os x 10.11
Popcorn Time Version:

0.3.9
Download date:

month ago
#### Expected Behaviour

play the movie/ series normally
#### Actual Behaviour

 keeps crashing on some point of almost every movie/series
#### Steps to reproduce the behaviour

1. Open any movie/series
2. Let it play
3. At some point, it will crash

**Comment by ChrisAlderson** [comment]
Dupe #236
