### ISSUE TITLE
Minor: Keyboard help not visible when in fullscreen

### ISSUE THREAD

**Issue by joeytwiddle** [popcorntime/popcorntime#2430]
Operating System Version:
Manjaro Linux

Popcorn Time Version:
Latest development 03205b426

#### Issue
When watching in fullscreen, and we press `?` to show the keyboard help page, it does not appear!

#### Steps to reproduce the behaviour

1. Watch a video
2. Go fullscreen
3. Press `?`
4. Note that the keyboard help is  not visible
5. Go out of fullscreen
6. Note that now the keyboard help IS visible!

This indicates that there is nothing wrong with the toggle behaviour on the `?` keystroke.

The problem is more like layout/CSS. When in fullscreen, the player appears in front of the keyboard help div. When we leave fullscreen, now the player is behind the keyboard help div.

I took a look at the CSS, but couldn't work out why.

If this is something that cannot be fixed easily, then never mind. 🙂

**Comment by kiriles90** [comment]
Hi, you are right its not about the CSS. I think the way it works the fullscreen vjs-player becomes a sibling in the DOM so if visible its always on top of everything else no matter the z-index values etc. The only way I found to workaround it so far (other than the very messy and probably not recommended  trying to re-arrange everything in the DOM) is setting `display = none` to it. This is also what's being used for its minimize function.

So.. having said that what do you think about https://github.com/popcorn-official/popcorn-desktop/pull/2431? Also takes care of the mouse scrolling/vol. adjust when some other view is on top of the player (happened independently of the fullscreen status even on the non-fullscreen player)
