### ISSUE TITLE
Minor: Missing X button in Movies/Series when using Native window frame

### ISSUE THREAD

**Issue by Blixtmen** [popcorntime/popcorntime#2444]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.7

#### Expected Behaviour
You can go back to where you were, top right X button is there
![2022-02-24_01-07-03](https://user-images.githubusercontent.com/20008760/155431942-15138f27-b00c-430d-8d5a-3facc9252c6c.png)

#### Actual Behaviour
Missing, in Native window
![2022-02-24_01-07-25](https://user-images.githubusercontent.com/20008760/155432049-11a624d9-b0d8-462f-a020-1ac4615ce0c6.png)

**Comment by kiriles90** [comment]
Fixed, thank you for finding and reporting the bug.
