### ISSUE TITLE
When hovering over play progress, show a thumbnail of that part

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2446]
**Is your feature request related to a problem? Please describe.**
Currently we have no way of knowing which part we are skipping to if we move the progress slider.

**Describe the idea you'd like**
Implement a thumbnail preview above of the part we're sliding the playing progress bar to, like in youtube

![image](https://user-images.githubusercontent.com/50620416/155603177-00f7c8e6-30a6-45f8-946d-854b2daa51ce.png)

**Comment by kiriles90** [comment]
Youtube preloads thumbnails. In Popcorn Time's case these are third party torrents that we're talking about so its not possible.
