### ISSUE TITLE
Popcorntime  Black screen No results found.

### ISSUE THREAD

**Issue by 1Stev** [popcorntime/popcorntime#2456]
Popcorntime was working perfectly yesterday. As of today 03-02-2022, The program loads but all tabs Movies/TV /Annim are all empty. Just black screen that says No results found. I reinstalled latest version and even restarted my PC I'm running Windows11 But same results.

**Comment by kiriles90** [comment]
The domain of the API the app was using went down. Version 0.4.7 should be out shortly (probably later today) to address the issue as well as try to prevent similar future ones from happening.
