### ISSUE TITLE
[TVShows] double episode title (bug or "feature"?)

### ISSUE THREAD

**Issue by ThaBrad** [popcorntime/popcorntime#2459]
Operating System Version:
OS X 10.15.7

Popcorn Time Version:
0.4.7 (probably in earlier versions too?)

Download date:
20:05 - 02.03.2020 (GitHub)

#### Expected Behaviour
Episode: "Title"

#### Actual Behaviour
Episode: "Title (Title)"

#### Screenshot
<img width="1435" alt="Screenshot 2022-03-02 at 20 22 32" src="https://user-images.githubusercontent.com/18183189/156433768-7df3fd9f-3308-43dc-8a36-fb3f4b054c60.png">

**Comment by dutchy1001** [comment]
you might need to update to latest release, I dont have the double names and checked a good few other titles.
![Untitled](https://user-images.githubusercontent.com/5569980/156439067-b08b6c5a-aadf-40ae-9998-14ca6940cf7f.png)

Unless it's a mac issue (not going there :) )

**Comment by kiriles90** [comment]
You have Settings -> Localisation -> Title translation set to original+translation

**Comment by ThaBrad** [comment]
oooohhh, yup @kiriles90 
So it IS **feature** 😜
Maybe make it more obvious that it's translation or make original default or give a little hint of the new "feature" 😏

**Comment by kiriles90** [comment]
@ThaBrad all valid suggestions :)
