### ISSUE TITLE
Remote API for movies and shows fails to respond

### ISSUE THREAD

**Issue by jimsuev** [popcorntime/popcorntime#2461]
Operating System Version:
 Windows 11

Popcorn Time Version:
 0.4.5
Download date: Dec 2021
 December 2021

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Update to the latest version
