### ISSUE TITLE
Popcorn time : Movie API server failed

### ISSUE THREAD

**Issue by gastontancredi** [popcorntime/popcorntime#2464]
Hi, I´ve been using https://popcorn-ru.tk/ and since a couple of weeks ago it is not working anymore . Does anybody know what API server is working? Thanks! 
![image](https://user-images.githubusercontent.com/67171481/157774205-b8a70b11-0d60-4c7b-accc-da5be560c537.png)
![image](https://user-images.githubusercontent.com/67171481/157774249-fa3e9c32-1b55-437d-81fc-20c21853cc53.png)

**Comment by jefponte** [comment]
Try this one: https://popcorn-time.ga/

**Comment by diegogarciar** [comment]
Just tried @jefponte's suggestion and it works!

**Comment by gastontancredi** [comment]
Thank you so much @jefponte ! It works! :)
