### ISSUE TITLE
Brew install not working anymore

### ISSUE THREAD

**Issue by bdrnglm** [popcorntime/popcorntime#2466]
Operating System Version:
macOS Big Sur 10.6.4

Popcorn Time Version:
None

Download date:
None

Download url (optional):
GitHub: Brew Command

#### Expected Behaviour
Being able to download and install popcorn-time through brew cask

#### Actual Behaviour
It fails and you get an error 403

#### Steps to reproduce the behaviour
Just follow the steps of the README.md at [this section](https://github.com/popcorn-official/popcorn-desktop#macos)

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![Screenshot 2022-03-12 at 10 19 51](https://user-images.githubusercontent.com/3275493/158012220-166adde4-adc7-49e1-a9b2-764d56204cf0.png)

**Comment by kiriles90** [comment]
We are supposedly waiting on #2439 but the author seems to have disappeared again.
Merging https://github.com/popcorn-official/popcorn-desktop/commit/2a074f2aabafca1253e8e7428f7b7bac3bf984ab to at least have it work again until the PR above is finished
