### ISSUE TITLE
Add download buttons to Seedbox

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2468]
**Is your feature request related to a problem? Please describe.**
When you press download now for a certain episode, it opens your Seedbox/Downloads menu, where it shows which episodes from that series you have downloaded, but it doesn't show "download" buttons for other episodes if we want to download them with one click, so we have to go back to the series to download each episode again.

**Describe the idea you'd like**
Add single download buttons for episodes that haven't been downloaded yet (in the seedbox menu). Example of download button placement (red squares on the right):
![image](https://user-images.githubusercontent.com/50620416/158072770-427683b6-78f0-40ec-b628-9b2a3e638eb3.png)

**Comment by kiriles90** [comment]
![Untitled](https://user-images.githubusercontent.com/38388670/158074500-f489c5dd-ec8a-407a-8554-8c13e6a11e7e.png)

Its already there.
