### ISSUE TITLE
Remove Category Filtered Searching

### ISSUE THREAD

**Issue by alecacres** [popcorntime/popcorntime#247]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9-0

Searching only brings up results from the chosen tab, even though there are often very few results. Eg. searching for 'Breaking Bad' while the "Series" tab is selected brings up the correct result, but not if the "Movies" tab is selected. There doesn't seem to be any need to filter results like this, given that most searches should bring up very few results.

**Comment by ChrisAlderson** [comment]
I cannot see how removing a working feature is an issue.
