### ISSUE TITLE
Subtitle menu empty

### ISSUE THREAD

**Issue by SkullRunnerGR** [popcorntime/popcorntime#2470]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.7

Download date: 02-03-22

Download url (optional): https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.7

#### Expected Behaviour

The subtitle menu to show different languages to choose from.

#### Actual Behaviour

It doesn't show any language but, I found a temp fix that changing the DNS server to 1.1.1.1 and re-installing the app fixes it. After re-opening it the subs don't work once again

#### Steps to reproduce the behaviour

1. Change DNS server to 1.1.1.1
2. Re-install app (Delete %localappdata%/popcorn-time BE AWARE ALL SETTINGS WILL BE ERASED)
3. Check the sub menu

https://prnt.sc/ARMBsb348hnS not working (now)
https://prnt.sc/uZvP6JohlXoe working (first time after fresh install)

P.S. The opensubtitles login thing in settings doesn't work and I haven't seen it working in a long time so update your FAQ I guess

**Comment by kiriles90** [comment]
Using a different DNS than the one of your ISP isnt a temp fix. Popcorn Time fetches subtitles from opensubtitles.org which Greece has blocked a couple of months ago. To bypass the block you need a DNS change or a VPN. Cloudflare's DNS (the one you use, 1.1.1.1, works). Just clean install Popcorn Time, make sure that wherever you changed the DNS at also applies to Popcorn Time (e.g from windows connection settings) and you should be good to go not just for the first run after this but in general.

**Comment by SkullRunnerGR** [comment]
Yes. My DNS is 1.1.1.1 in general (via IPv4 settings in Windows). I never removed it but PopCorn-Time doesn't work now for some reason of course I can re-install it but that's not a process I want to repeat everytime I want to watch a movie :(
https://prnt.sc/JXWxRue7exAp (wi-fi settings)

I fixed it again but as soon as I toggle other settings it stops working

**Comment by kiriles90** [comment]
Yes ofc reinstalling every time isnt a solution. So even if you toggle unrelated settings it stops working. Do you by any chance import settings?

**Comment by blackPantherOS** [comment]
Subtitles does not work usually, list is empty sometime on movie's description page. This is  not a DNS error! Opensubtitles free available directly, Stremio and previous PT (ru fork) working fine
If i clicking to "Subtitle" menu many times, show all subtitles immediately
 (Linux - blackPanther OS)
