### ISSUE TITLE
Custom git Branch for customization & a Debian Package

### ISSUE THREAD

**Issue by eskinderg** [popcorntime/popcorntime#2471]
I recently forked this repository to my own git and worked on some customization.
Development branch being the default branch, I did all my customization on a different branch which i created from Development branch.

The issue i am having is that the application wont run on the new branch i created but is able to run on development branch. the command i used to run the application on the new branch is 
`gulp run`.
Works on development branch but not on the new branch i created.

Also, how do i run packaging for Debian `(*.deb)`. I used the command `yarn gulp dist --platforms=linux64` but all i get is a ZIP file that kind of look like an AppImage but i needed an installable `(*.deb)` file.

Thanks.

**Comment by ivan1986** [comment]
exist gulp deb
also you broken something in this commit https://github.com/eskinderg/popcorn-desktop/commit/0b3b7260e181ea5e5db547bc5bb9fce77af3d35d on 256 files

**Comment by eskinderg** [comment]
I am still not able to get Debian package after running `gulp deb`
