### ISSUE TITLE
Subtitles sometimes not shown

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2472]
Operating System Version:

EndeavourOS, KDE 5.24.3
Popcorn Time Version:

0.4.7
Download date:

4.3.2022
Download url (optional):

release
#### Expected Behaviour

Display 

#### Actual Behaviour

Sometimes in subtitles options of a video, there isn't any subtitles. For example, i watched a video and there weren't any subtitles options in it... when i restarted pc (for other reasons) and came back to the same video, the subtitles were visible to be selected.

#### Steps to reproduce the behaviour

1. See a video and if it doesn't have subtitles proceed to # 2
2. restart the program
3. The subtitle options will maybe be back in the same video.

**Comment by kiriles90** [comment]
I've already explained this has to do with your connection to opensubtitles.. stop reoppening the same non-issue there is nothing to fix.
