### ISSUE TITLE
Optional Record / Screenshot function

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2475]
**Is your feature request related to a problem? Please describe.**
Currently there is no record / screenshot function, which would enable us to, for example, record small clips or take screenshots of the full screen of the scene. If we want to take a screenshot we first need to play the video so playing controls disappear, so the screenshot can be taken full screen, same for video.

**Describe the idea you'd like**
An optional toggle in settings, which would enable a display of the record button when playing movies. Pressing a record button would start recording, and pressing it again would stop it.
Pressing a screenshot button would take a full resolution screen shot.

**Additional context**
This could be very useful if we want to record small sections of the videos, instead of downloading an entire movie/episode just to cut a small part out, use cases: sharing clips with friends/on social media, youtube...

**Comment by kiriles90** [comment]
This PR is not straightforward at all to implement and way out of the scope of this app. There are even fully fledged media players that dont have it.. Just find one that does and record with that..
