### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by carrelagewc** [popcorntime/popcorntime#2476]
Hi :)

My VPN in on (Avast SecureLine), but Popcorn Time still report a not secured connection & I 
 can't search any movie or serie 😢

**Comment by dutchy1001** [comment]
You can turn the vpn notification off in the (show advanced settings) settings->connection.
Your Avast VPN should be sufficient.
Reason you might not be able to search movies and series is because you need to update the API (you can also find this in the settings)

**Comment by carrelagewc** [comment]
Thank you!
I had to update my popcorn time version AND the API.

Better now!

Le lun. 21 mars 2022 à 13:20, dutchy1001 ***@***.***> a
écrit :
