### ISSUE TITLE
Show api not loading

### ISSUE THREAD

**Issue by PsycloneTM** [popcorntime/popcorntime#2480]
Operating System Version:
Windows 10

Popcorn Time Version:
 v0.4.7 Latest

Download date:
like 10 days ago

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases

#### Expected Behaviour
load the shows

#### Actual Behaviour
says it failed to respond

#### Steps to reproduce the behaviour

1. Open the app
2. Click the show tab

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) 
https://i.imgur.com/rPq1j4u.png

**Comment by dutchy1001** [comment]
Make sure your ISP doesn't block the API. If you have/use a VPN try a different country.
Also you can check the settings and choose a different API from the dropdown menu.

**Comment by kiriles90** [comment]
Those urls are dead for almost a year now. Download the latest release version if you havent already (0.4.7 atm) and update the API urls when asked. If you dont see a popup you can trigger the update at any time manually by pressing the refresh button next to the API fields in the settings. Then once you have the latest list.. select an API that works (if your settings dont allow the app to automatically do it for you)
