### ISSUE TITLE
why can't we find the latest seasons of some of the shows for example sex education season 4Do not open an issue

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#2482]
Can you please see if the issue is from API or could you have the latest one I don't understand why can I find the sex education season 4 it's been out for about a year nowcan you please see if the issue is from API or could you have the latest one I don't understand why can I find the sex education season 4 it's been out for about a year now

**Comment by kiriles90** [comment]
No API has absolutely everything. Find it somewhere else and drag&drop the magnet link in the app. (also this is an API 'issue' to begin with, this repo is just for the app)
