### ISSUE TITLE
No Subs for  v0.4.7 

### ISSUE THREAD

**Issue by central4all** [popcorntime/popcorntime#2487]
Operating System Version:

11
Popcorn Time Version:

 v0.4.7
Download date:

15 days ago
Download url (optional):

#### Expected Behaviour

...
show subs to choose
#### Actual Behaviour

...
Finds zero subs
#### Steps to reproduce the behaviour

1. ...Just start a film that you are sure that there are subs
2. ...
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

i have 2 laptops with same antivirus (symantec end point protection), same windows 11 updated and same version of popcorn  v0.4.7, the one never loads subs the other always load subs, cant find the problem.

**Comment by dutchy1001** [comment]
If you haven't already done, make an account at [Opensubtitles.org](https://www.opensubtitles.org/en/search/subs) and fill this in the settings tab on both laptops. This will help with getting subs for movies and series but isn't a must as far I understand.
If the subs work on one PC/laptop they should then work on the other (I never have issue's with the subs besides sometimes the timings), this indicates that it's not a Popcorn Time issue.
Does 1 laptop have a VPN and the other not (just thinking out loud here for problem solving). 
Do you use the default player or do you use a 3rd party player like VLC or SMPlayer? Are they both the same on the laptops and same versions?
Have you tried to disable the Anti Virus to see if that helped?

**Comment by kiriles90** [comment]
@central4all closing this because its not an issue with the app since the rest of us have subs but do continue the conversation below if you want after you've tried @dutchy1001 suggestions, though his reply pretty much covered everything.
