### ISSUE TITLE
Can't open app with MacOS Monterey

### ISSUE THREAD

**Issue by itsmelyzo** [popcorntime/popcorntime#2492]
Operating System Version:

Popcorn Time Version:

latest version 0.4.7
Download date:

May 1 2022
Download url (optional):

from GitHub  https://github.com/popcorn-official/popcorn-desktop/releases
#### Expected Behaviour

... it didn't open; it says app cannot be opened

#### Actual Behaviour

... in Previous macOS versions the fix was to right click and click open, but its not working now

#### Steps to reproduce the behaviour

1. ... download
2. ... open app
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

<img width="260" alt="Screen Shot 2022-05-01 at 11 36 42 PM" src="https://user-images.githubusercontent.com/104736919/166163664-a6096432-8d70-4127-b8d0-c1bea5c0528b.png">

**Comment by kiriles90** [comment]
Related to https://github.com/popcorn-official/popcorn-desktop/issues/2062. Closing this issue but do comment in the other one if you have anything to add.

**Comment by Kief5555** [comment]
https://github.com/popcorn-official/popcorn-desktop/wiki/Fix-crashing-on-macOS-%5E12
