### ISSUE TITLE
Popcorn just loading not displaying anything.

### ISSUE THREAD

**Issue by Hulu49** [popcorntime/popcorntime#2494]
Operating System Version: windows 11

Popcorn Time Version: 4.0

Download date: 05/01/2022

Download url (optional):

#### Expected Behaviour
 display movies and searched movies when opened .
...

#### Actual Behaviour
 Just loads and not displays anything.
...

#### Steps to reproduce the behaviour

1. ... open the app and wait
2. ... search for any movies
3. ...

**Comment by dutchy1001** [comment]
Plz close this as no info is given.

The form is to give us better understanding what could be wrong

**Comment by Hulu49** [comment]
<img width="672" alt="popcorn issue" src="https://user-images.githubusercontent.com/104850749/166490493-9e4dc9fe-baeb-405e-8714-a18bd5a9e9dc.png">

**Comment by Hulu49** [comment]
> dutchy1001

I updated the required fields.

**Comment by dutchy1001** [comment]
You need to update your version to 0.4.7 .
This will allow you to update the API's either automatic (in the settings) or manual if that is what you prefer.
For an update Click [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/2229839397) and choose the windows option.
After update see if it works again. Let us know by posting back here or close this topic.

**Comment by Hulu49** [comment]
Thanks for your response.

**Comment by Hulu49** [comment]
Closing the issue as this is working, Thank you.
