### ISSUE TITLE
problem to connect popcorn app in Macbook Osx10.12.6

### ISSUE THREAD

**Issue by jaz1281** [popcorntime/popcorntime#2496]
Operating System Version: OS X 10.12.6

Popcorn Time Version:0.4.4

Download date:May 8th 2022

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour
the app open lunch however doesn't connect and stay in connection mode.
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment]
I wonder where you download v0.4.4 as this is an old version and the main website has been down for over 2 years now?

**Comment by jaz1281** [comment]
Well ... I suspected it was old, but all app that I could download were connected or open... I was using one so good (I diidn't remember the version), anyway just stops to connect and work. Maybe you could give my a good link for the newest one for OSX

**Comment by dutchy1001** [comment]
I Just wanted to know what site you used so we could let ppl know they have an outdated (possible altered) version there. 
This is also a reason the questions asked when you submit an issue when/where you download from (a help us to help you system).

To point you to the right version you have to go [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/2287643059)

**Comment by DomnicAmalan** [comment]
There is release page in girhub

**Comment by dutchy1001** [comment]
@DomnicAmalan  didn't I just do that??
This page changes every time when there is a new build made. There is NO static release page we can point to.

**Comment by jaz1281** [comment]
> There is release page in girhub

Yea I did see it ... I will try later. Thks!

**Comment by jaz1281** [comment]
> @DomnicAmalan didn't I just do that?? This page changes every time when there is a new build made. There is NO static release page we can point to.

I understood... so I just did try to get a new app and download from several sources until I get here. Thks.

**Comment by dutchy1001** [comment]
@jaz1281 just click the link I posted and choose "macOS-latest" 507mb. 
This is the latest "build" (4 days old at time of writing here) for Mac, Ubuntu and Windows, just download the one for your system.

**Comment by jaz1281** [comment]
> @jaz1281 just click the link I posted and choose "macOS-latest" 507mb. This is the latest "build" (4 days old at time of writing here) for Mac, Ubuntu and Windows, just download the one for your system.

Thanks!!

**Comment by dutchy1001** [comment]
There has just been a new build made, I have been told that "[here](https://github.com/popcorn-official/popcorn-desktop/releases)" is the best way to get a new version. This will not be the latest builds but this will be a stable build.

@jaz1281 If you updated with the link I gave before you dont have to redo this.
