### ISSUE TITLE
synopsis translation bug and randomize bouton bug

### ISSUE THREAD

**Issue by raphcool12** [popcorntime/popcorntime#25]
Hi I notice that the synopsis traduction didn't work it's only in english and I'm set to french translation also the randomize bouton is broken He didn't any random movie it's just showing the circle who is turning indifinitly

thanks in advance and sorry again for my bad english :)

**Comment by team-pct** [comment]
Random fixed on b7e8dbd77eef382a54fa77b2283a319419bcdc52
Build # 40 on ci.popcorntime.sh

We will look into synopsis translation ASAP

**Comment by raphcool12** [comment]
ok good it's good to know when I repport an issue can labels mark it me too as bug and help wanted or it's only you who can do this?

**Comment by raphcool12** [comment]
Hi did you forgot to fix this because all the synopsis is still in english after 12 days and randomize button still broken :) I know youare busy it's just a reminder

thanks in advance

**Comment by VitorVRS** [comment]
I think synopsis come from IMDB and dont have any translate there :/

**Comment by raphcool12** [comment]
your right it's came from IMDB but  I know @team-pct  made a translator in every language and it's working very well with the version 3.8.6 the version they have made to celebrate their come back on feb. 24 and on feb 25 they have integrate butter platform by removing api and made version 3.9 the current version since that all is in english so I'm sure they can fix this easly It's just because some modification have been made to the language file between these two version  I also have the popcorn time community edition and translation is a little broken here too but work sometime with some api

and by the way in the advanced setting you still have the option synopsis translation they you can still check box but as I say earlier nothing of that work for now :)

**Comment by raphcool12** [comment]
so @team-pct any progress on that I know you very busy but it sould be cool to fix translation for the upcoming version 0.4.0

thanks in advance :)

**Comment by ChrisAlderson** [comment]
Closing this issue because it should be split into a 'synopsis translation bug' and an issue about 'randomized movies not working' issue.
