### ISSUE TITLE
Manual subtitles sync speed buttons, so they match with video better.

### ISSUE THREAD

**Issue by aha999** [popcorntime/popcorntime#2503]
**Is your feature request related to a problem? Please describe.**
Subtitles are commonly not syncronized with the video, so they're "off" by seconds or more...

**Describe the idea you'd like**
Add an option to enable changing the speed manually in the player with 2 buttons, one for speeding up and one for slowing down the subtitle time by milliseconds, so they could be adjusted to match with the video.

**Describe alternatives you've considered**
This could be a toggle in the settings to turn this feature on/off, or it could be visible when clicking on subtitles, even by default i think it would be pretty convenient.

**Additional context**
I think that this feature would be easy to implement and would solve a problem that is big sometimes, when none of the selected languages match the video's time.

Example:
![image](https://user-images.githubusercontent.com/50620416/169713928-c6ee6271-035b-40d7-9e17-7edb8f3872d7.png)

**Comment by dutchy1001** [comment]
This is already possible with the 
_H key for +0.1s 
H key plus Shift for +1s
H key plus CTRL for +5s_
and
_G key for -0.1s 
G key plus Shift for -1s 
G key plus CTRL for -5s_

Also if you use an external player they mostly will have similar options depending on the program.
Hope this helps so you can close this issue..

If you want to see all keyboard commands use the /  to open that tab.

**Comment by aha999** [comment]
@dutchy1001 oh my science thanks for this answer, i didn't even know this feature existed on popcorn... is this hint available in the software ?

**Comment by dutchy1001** [comment]
use the "forward slash" / 
and you will see all the keyboard commands

**Comment by aha999** [comment]
Also, after a bit of looking, it's at the top of the settings page 
![image](https://user-images.githubusercontent.com/50620416/170142760-05e61ec7-6cc6-4b4b-9486-7819d5483aa1.png)
