### ISSUE TITLE
Popcorn keeps crashing on Xiaomi Mi SmartTV P1 43"

### ISSUE THREAD

**Issue by MetaLimit** [popcorntime/popcorntime#2504]
Operating System Version:

Popcorn Time Version:
[mobile-arm-release-0.2.13.apk](https://popcorn-time.ga/build/mobile-arm-release-0.2.13.apk)

Download date:
20/05/2022

Download url:
(https://popcorn-time.ga/build/)

#### Expected Behaviour
Play movies and series on TV
...

#### Actual Behaviour
It let's me install but when I open a start to select any content it crashs not giving any information

**Comment by kiriles90** [comment]
Wrong place, you need the android repo.
