### ISSUE TITLE
Source name of movie on main film page

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2505]
**Is your feature request related to a problem? Please describe.**

Each film or series have a file name that will be streamed/downloaded to your device. 
Reveal of the source name to determent the "base" quality of the film.
No matter of the 480P to 2160P picture, quality is often upgraded to a higher "P" then the film is, special when the film is cropped to hide some subtitles or an upgraded cam version (like the bad example posted below)

**Describe the idea you'd like**

An extra line to inform what the file name is.
Good Example:
Fantastic Beasts The Secrets Of Dumbledore 2022 HDR 2160p WEB H265-NAISU
Bad Example:
Fantastic Beasts The Secrets Of Dumbledore 2022 720p Cam X264 AC3 Will1869
(how can a cam version be 720P imho)
I understand that file names not always say what it is, but you have some extra info to decide to watch it or not.

I know this can be seen already when using the download option or when you start to stream this, but it would be nice to know before you start the film (there is nothing worse then to look forward to a film and then finding out the quality is crap).

**Comment by dutchy1001** [comment]
What isn't possible due to the API is something you cant help, it's worth a try to find out, if not then tough 😜😜

**Comment by kiriles90** [comment]
@ivan1986 any of the sources provide this function? Any ideas to do this without loading the torrent everytime when opening movie detail?

**Comment by ivan1986** [comment]
I may add title field in torrent dto, not only in all torrents list, which use for more button
done
