### ISSUE TITLE
Touch bar using default chrome

### ISSUE THREAD

**Issue by Kief5555** [popcorntime/popcorntime#2508]
**Is your feature request related to a problem? Please describe.**
Kinda like both.
The touch bar on the macs (the electronic ones) show the exact same buttons like on chrome. Enter url, reload, favorite site, etc. 

**Describe the idea you'd like**
Replace these with play or stop buttons, search button, downloads button, etc.

**Describe alternatives you've considered**
Maybe not change it??

**Additional context**
N/A

**Comment by kiriles90** [comment]
@Kief5555 github.com/nwjs/nw.js/issues/5501 not possible afaik. NW.js will just show the default chrome/chromium configuration at the moment.

**Comment by Kief5555** [comment]
Ah ok.
