### ISSUE TITLE
Subtitles Not Available

### ISSUE THREAD

**Issue by Notacertainuser** [popcorntime/popcorntime#2509]
Operating System Version:
Windows 11

Popcorn Time Version:
 0.4.7

Download date:
24 May 2022

Download url:
from .ga, 

#### Expected Behaviour
 Provide me with options to choose between different subtitles 
...

#### Actual Behaviour
 There is a light grey ''X'' where the button of subtitles options used to be, meaning no subtitles available, or something not working properly. 

From the beginning it wasn't able to connect to my Opensubtitles account through popcorn, so I edited the src/app/settings.js, filling my credentials and giving a true value to authenticated. After doing so, app settings shows I am connected to Opensubtitles account but still no subtitles available.

Also I tried to edit the src/app/lib/providers/opensubtitles.js, replacing the whole ''Popcorn Time NodeJS'' with Butter or Butter V1, but still nothing changed.

I don't know if it matters, but I have installed the app in a different drive than C

Any suggestions, please?

Thank you
 
...

#### Steps to reproduce the behaviour
Just open a movie or an episode and go to subtitles options, instead of a button there is an ''X'' that you cannot press or anything  

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![1](https://user-images.githubusercontent.com/106931026/172069471-5f1263ca-6d45-4d99-bf6c-9ed8c6d524e9.jpg)
![2](https://user-images.githubusercontent.com/106931026/172069474-6ab85e48-2434-41b0-a1ee-e5006f74c3ca.jpg)
![3](https://user-images.githubusercontent.com/106931026/172069475-e7d2c34b-b865-4fd7-9959-5c44bafc608a.jpg)

**Comment by dutchy1001** [comment]
> Download url:
from .ga,

This doesn't make sense to me were you got it from.

>I don't know if it matters, but I have installed the app in a different drive than C

I don't think it matters where you install PCT, this will not cause that the subtitles not work.

Changing anything in the code shouldn't be necessary as it will work strait out the box. 

- Have you set the "default" subtitles in the settings?
- It could be that Openbubtitles.org was down.
- There might be a chance that the subs you want isn't in your language.
- Do you have an account with Openbubtitles.org? (If not, create one and add it in the PCT settings)
- If PCT works with or without a VPN then the subs should work too.

All movies you mentioned above do have multiple subs for me.

**Comment by kiriles90** [comment]
> Do you have an account with Openbubtitles.org? (If not, create one and add it in the PCT settings)

**Comment by Notacertainuser** [comment]
I download it from here: https://popcorn-time.ga/

I do have an opensubtitles account, but as I already mentioned I wasn't able to connect to it through the PCT menu settings. I only manage to do so by adding my credentials manualy in the Js file. Open subs wasn't down all this time I had PCT, it doesn't make any sense.

I do have set the default settings in subtitles, it is just that subtitles function doesn't work!! As for the languages, I am telling you again, It isn't operating, it only shows an X. So there is not any language not even english and that apply to all the movies and episodes in the PCT. 

It is the first time I am encountering such an issue since I had previous version of PCT working fine.

With all that being said the movies working just fine!

**Comment by kiriles90** [comment]
@Notacertainuser Do not edit the .js files, its probably the reason why you cant login and why your subtitles dont work. Clean install the latest version, that means uninstall Popcorn Time, delete the %localappdata%\Popcorn-Time folder and reinstall. Then start the app, let it update the APIs, then go in the settings connect with your opensubtitles.**org** account and restart the app.

**Comment by kiriles90** [comment]
@Notacertainuser I feel like you dont read something. There is no reason not to work for you when the same procedure works for everyone else.

**Comment by dutchy1001** [comment]
Do you have an other pc/laptop that you could test this on?

**Comment by dutchy1001** [comment]
@Notacertainuser this is very well possible. I don't know your country but as far I know the UK and Netherlands work fine for me with opensubtitle.org. 
Your ISP should have a list of sites that are blocked.
I presume you do not have a VPN then?

EDIT: Norway and Denmark are blocking Opensubtitle.org

**Comment by Notacertainuser** [comment]
Yes, the provider has blocked opensubtitles, thats for sure. You presume right. Is it definite then, without vpn, no subtitles?  

Btw this is what I am always getting, no matter what. 

![1](https://user-images.githubusercontent.com/106931026/173676412-a6c8ef75-fb2e-46a3-afbf-3c8ce0744b33.jpg)

**Comment by dutchy1001** [comment]
I guess not then. There are a few other sites that have subtitles but you need to use a 3rd party player then to add them manual.

**Comment by kiriles90** [comment]
@Notacertainuser I answered in the exact same words you had just answered me. And they were all true. Provided you clean installed the latest version correctly.. its your ISP/DNS/VPN. Do with it as you please..

**Comment by Notacertainuser** [comment]
@dutchy1001 Yes I know, but I am using pct for years and I am kinda used to it. Anyway thank you and if you come up with anything else please let me know

**Comment by Notacertainuser** [comment]
Okay now we know for sure there is something else going on. I changed DNS and I could access Opensubtitles via browser but no luck signing in my account through pct settings. Then I reinstall again pct, deleting all the temp folders etc and signing in to opensubtitles still doesn't work. I have downloaded from https://popcorn-time.ga/, is it legit?

**Comment by kiriles90** [comment]
@Notacertainuser if you are willing to read it this time and not ignore the answer for 4 days just to come up with the same one then be hostile again.. and since you dont want a VPN.. change your DNS to cloudflare not googl

**Comment by Notacertainuser** [comment]
You are right I had Google as first option and when opening your link I was getting the picture below. I switched google to be second and cloudflare first, then I restart the pc, I am still getting the same image. And I still cannot login to my opensubtitles account from pct settings

![1](https://user-images.githubusercontent.com/106931026/173693960-b16487ae-b289-4cda-ba8c-52365addbcfa.jpg)

**Comment by kiriles90** [comment]
Some people had issues with google but cloudflare worked for them. It was specific to only when using port 443 in the url though, I guess the dns didnt forward that or something. No idea why you still cant login. You're inputing a username and not the associated email right? Try downloading and clean installing the latest dev builds from the actions page here (still 0.4.7 but about 50 commits newer than the relese version and one you are using). The opensubtitles section got merged into the subtitles one since login in is mandatory now.

**Comment by Notacertainuser** [comment]
I did download it again from action page as you suggested and now everything works like a charm, whithout removing google or flushing anything!! So maybe there is indeed something going on with the other version, because no matter how many times I was reinstalling it, subtitle function was broken. Thanks for the support, cheers!

**Comment by Notacertainuser** [comment]
Hi just an update, every some movies I watch I am getting the same issue. Subtitles dissapears, e.g they are not available. If I try disconnecting and reconnecting to Opensubtitles most of the times it wont even allow me to connect again. This means I would get an red X as if I am entering wrong credentials -which I am not. A temporary fix is everytime to download the newest version deleting previous and reinstalling, then magically everything is working fine but again it doesn't last to much. Just to watch a couple of movies, then I will be getting the same issue all over again. Any ideas what that might be ? Peace

**Comment by dutchy1001** [comment]
This looks to me like a local issue, I swap between languages for the subtitles and have no issue what so ever.
I use a VPN through "The Netherlands" while being in the UK choosing both (by redownloading the movie/series) UK and NL subs.

Subs are depending on availability and best match for a file. they are from 3rd party sources so this could affect you.

**Comment by Notacertainuser** [comment]
One moment everything is working fine and then boom nothing will have subtitles. It is not about language availability, subtitles are completely disabled. Any suggestions then? Every time I reinstall the app I get it to work but after seeing a movie or an episode, subtitles go unavailable 
 
Also If I reset app to default settings then I cannot get the API updates, they fail

**Comment by Notacertainuser** [comment]
Also If I reset app to default settings then I cannot get the API updates, they fail

**Comment by dutchy1001** [comment]
For me sometimes it takes 10-25 seconds before the subs show on the title page of a movie, the box stays then grey with an X in it. After that the flag of my default language will show.

Have you ever tried a clean install? 
Uninstall Popcorn-Time, then check locations written below and delete both.
C:\Users\YOURNAME\AppData\Local\Popcorn-Time
C:\Users\YOURNAME\AppData\Local\Temp\Popcorn Time

If you want to keep your watched/favourite list then copy the files out of this location before you uninstall Popcorn-Time
C:\Users\YOURNAME\AppData\Local\Popcorn-Time\User Data\Default\data.

From those 5 database files I would skip the "settings" file and fill the subs logon in manual again (and the other settings you like)
Obvious you put the files back after a clean install at the same place

**Comment by Notacertainuser** [comment]
When subtitles work, they appear instantly in every movie or series. I have pretty good internet connection. When the bug or whatever it is happens, they appear as they are disabled in every movie etc and forever.

As I am writing this I am reistaling the app 3rd time today. After uninstalling popcorn, I checked the paths you specified and there isn't any popcorn folder left in them. Must have been deleted automatically with uninstallation.

I am not keep anything like favourites, I have uninstalled the app so many times that there isn't any point in keeping favourites

I am not sure I got you right about 5 database files, but every time I am filling the login manualy in the settings. Choosign subtitles language etc.. 

***EDIT: I installed it and again the subtitles work just fine. Right now I don't have the time to watch anything but when I do I will let you know if something is changed

**Comment by dutchy1001** [comment]
> I am not sure I got you right about 5 database files

If you don't want to keep your watched list or favourites then you can skip that.

Make sure you download a new version from [here](https://popcorn-time.ga/build/) if you haven't done so far.
