### ISSUE TITLE
 All series are without the option of subtitles

### ISSUE THREAD

**Issue by LuMagalhaes** [popcorntime/popcorntime#251]
Operating System Version: Windows 10
Popcorn Time Version: 0.3.9 
Download date: 15102016
Expected Behaviour:
Subtitle Default Settings selected but not playing automatic in the player.
Even making all settings, subtitles appear as disabled.
Please Fix

**Comment by TheSparrowLenz** [comment]
Confirmed.
Subtitles are showing as Disabled.

**Comment by MinionAttack** [comment]
Also in movies. No subs available.

**Comment by giuligi** [comment]
what we have to do?

**Comment by ChrisAlderson** [comment]
Shows should be fixed in build ([159](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/159/)), we're still looking into the movies.

**Comment by MinionAttack** [comment]
Ah ok, thanks for all your efforts!

**Comment by ChrisAlderson** [comment]
Discussion about the movie subtitles should move to #227

**Comment by LuMagalhaes** [comment]
Could you tell us where the problem is solved? Thank you in advance!

**Comment by ChrisAlderson** [comment]
Already provided that information.

**Comment by LuMagalhaes** [comment]
I did a fresh install, but after downloading the episode of any series appears the warning: The video Could Not Be loaded, either because the server or network failed or because the format is not supported. 
I made the changes to the format and all respond with the same answer above.

**Comment by gimantoani** [comment]
Windows 10; Popcorn Time Version: 0.3.9 
Subtitle Default Settings selected but not playing automatic in the player of series.
Even making all settings, subtitles appear as disabled.

**Comment by LuMagalhaes** [comment]
I made the following changes to orientate Chris: "Shows should be fixed in build (159), we're still looking into the movies". I uninstalled the program and installed.
 Now you can only watch movies and series with VLC. I look forward to solve the problem to go back to watching the PopCorn. Thanks
