### ISSUE TITLE
Support for Lokinet low-latency onion routing for enhanced privacy

### ISSUE THREAD

**Issue by jan-kleks** [popcorntime/popcorntime#2510]
I have recently been reading about an interesting WIP alternative to Tor -- Lokinet. It looks like it might be possible to use it for streaming due to their focus on low-latency. Maybe it is something that could potentially be integrated into PT in the future for higher anonymity? Either with an exit node to "clearnet" or maybe PT could even run inside Lokinet?

Lokinet on GitHub: https://github.com/oxen-io/lokinet

[Blog post about Lokinet's speed](https://www.oxen.io/blog/lokinet-speed-and-scale)

**Comment by kiriles90** [comment]
@jan-kleks I guess this falls into the tor or other direct streaming proposals but no plans, consensus or someone working on this exists. Closing this since its not a priority or a planned feature and its somewhat out of the scope of the app but if someone is willing to work on it we can reopen.
