### ISSUE TITLE
Every episode is playing Spanish audio all of a sudden

### ISSUE THREAD

**Issue by grandslammer** [popcorntime/popcorntime#2511]
I have just tried watching episodes from 3 separate shows and the audio is all in Spanish for some reason.

I have checked my settings and everything is set to English, including the audio language setting for each show. I have not changed any settings since the last time I used the application.

What is going on?

**Comment by dutchy1001** [comment]
The issue form has some questions that needs to be filled in so we can see what we have to work with, we cant help you if you don't help us with the basic info we need.

Also it would be handy to know what series you tried so we can check them. 
This said, Popcorn Time is not responsible for the content and has no say in what you can choose from.

I have tried "Obi-Wan Kenobi" and it starts in Italian but my default settings are also English. As I use an external player I can then choose in the (external players) settings a different audio track. Obi-Wan Kenobi had 3 languages Italian, Spanish and English. 
The default PCT player does not have the option to choose a language track like most external players do.

Also tried "The Boys" which also starts in Italian. To me this looks like the API that searches for the files is not set to default English, but I could be wrong there as I don't know how the API works.

EDIT: 
Same seems to be happening in the movie section too.

**Comment by grandslammer** [comment]
> 

I have tried The Orville season 3 episode 1, Obi-Wan Kenobi episode 1, and The Boys season 3 episode 1.

I have just tried Stranger Things season 4 episode 1 and that seems to be in English, so it probably is the internal PCT player that's causing it.

The PCT Player should be updated to include this functionality as it would be much cleaner than having to use an external player and having everything included in one application.

**Comment by kiriles90** [comment]
> so it probably is the internal PCT player that's causing it  

Its media files with multiple audio tracks that have the spanish one as default.

> The PCT Player should be updated to include this functionality

Easier said than done when talking about an html5 player, they dont like multiple audio tracks nor there is a solid support for them. This is also the reason why this wasn't implemented so far.

Closing as this is an API issue but @ivan1986 if you can take a look at this, you might need to block some uploader/release group, I'm willing to bet its the same one in all occurrences of this spanish audio issue..

**Comment by dutchy1001** [comment]
> The PCT Player should be updated to include this functionality

>Easier said than done when talking about an html5 player, they dont like multiple audio tracks nor there is a solid support for them. This is also the reason why this wasn't implemented so far.

As I said It can be fixed while using external players like [SMplayer](https://www.smplayer.info/) or [VLC player](https://www.videolan.org/vlc/) (not sure which other players are supported by PCT), they give you the option to change the audio track. Were the "Watch Now" button is click the little arrow and choose a different player (you have to install the external player first of course 😉).

**Comment by ivan1986** [comment]
mmm, ok, i hate it too, and looks like one stuped release group, which can not correct fill torrent information
updated

**Comment by dutchy1001** [comment]
I think @ivan1986 has explained it all so no need to discus this any further.
