### ISSUE TITLE
subtitles not working

### ISSUE THREAD

**Issue by YIDA-king** [popcorntime/popcorntime#2512]
Popcorn Time Version:
0.4.7
i think it can't get the subtitles from opensubtitles
and the subtitles always show disable

**Comment by dutchy1001** [comment]
Do you have an account with Opensubtitle.org? If not create one and add it in the settings.

**Comment by YIDA-king** [comment]
i have one, not working . i also try to download the subtitled from Opensubtitles.org . Try to put it into the film . But not work ,either. it seems that something wrong in subtitle api ? i change the Time version. 0.4.5 sometimes show the subtitles, but when i change the other film or tv show. Problem happen sometimes . By the way . i found that there is a web is more stabler.  https://popcorntimeonline.xyz/



> 您有 Opensubtitle.org 帐户吗？如果没有，请创建一个并将其添加到设置中。

**Comment by dutchy1001** [comment]
I use version 0.4.7 and my subtitles work as expected. 
If you want to add manual sub to a movie or series then I suggest to use a 3rd party player which has more options to do so.

**Comment by YIDA-king** [comment]
> I use version 0.4.7 and my subtitles work as expected. If you want to add manual sub to a movie or series then I suggest to use a 3rd party player which has more options to do so.

Have you ever changed the code? i use it in windows. by the way , In setting , subtitle language is English and but it shows disable in film. in code it never change ,either

**Comment by kiriles90** [comment]
Login to opensubtitles.org in Popcorn Time settings with the latest version and they will work. Older versions and random websites like the one you linked above are not supported here.
