### ISSUE TITLE
tmdb imdb movies series sources

### ISSUE THREAD

**Issue by madrid2022ok** [popcorntime/popcorntime#2515]
Hello, you can put the series of movies with tmdb and imdb sources in English and Spanish 
yts.mx is down

**Comment by madrid2022ok** [comment]
and it doesn't work well with airplay videos with apple tv

**Comment by kiriles90** [comment]
Sorry but what you said doesn't make much sense. Say it in spanish. Also yts.mx isnt down your ISP probably blocked it. Closing this as its not an issue with the app.
