### ISSUE TITLE
No results found 

### ISSUE THREAD

**Issue by madrid2022ok** [popcorntime/popcorntime#2517]
![57558158-64BA-4A4F-B56A-5FA7DFA8462C](https://user-images.githubusercontent.com/105641464/175045390-448c1877-dc15-48f2-8e9e-0ffdf9680dc9.jpeg)

I get this message no results  found in torrent collection in thepiratebay and 1337x and rarbg omgtorrent

**Comment by kiriles90** [comment]
Tpb and omgtorrent dont work for anyone and your ISP probably blocks 1337x and rarbg, Try a VPN or a DNS change.

**Comment by dutchy1001** [comment]
the issue page starts off with a few simple questions, this helps us to help you. No info no help
