### ISSUE TITLE
Can I use PT-Android subtitle provider with PT-Desktop ?

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#252]
I think the former has some shows that the latter lacks. I would like to use both on desktop.

**Comment by ChrisAlderson** [comment]
Popcorn Time uses Opensubtitles and YSubs for both the android and the desktop platform. 

`src/app/lib/providers/`

Correction: YSubs is down, so we cannot use them.

**Comment by beppe9000** [comment]
This is creepy... the other day I tried the desktop app and it didn't find some subtitles. Five minutes later the android version instantly found them. Desktop still doesn't find them.
