### ISSUE TITLE
Not working: Connection to services (Trakt.tv, TVShow Time and Opensubtitles.org)

### ISSUE THREAD

**Issue by NE03N** [popcorntime/popcorntime#253]
Operating System Version:
OS X 10.12

Popcorn Time Version:
Version 0.3.9 Last build (#151)

Download date:
October 19th, 2016
#### Expected Behavior

successfully connect to services: Trakt.tv, TVShow Time and Opensubtitles.org
#### Actual Behavior

Trakt.tv:
     - pop up window/Redirection to the Trakt.tv website
     - Input password (sign in successful)
     - Asks to return to the app and add a "PIN" to connect the account
     - Nothing else happens, the window just stays there.
Opensubtitles.org:
     - Shows a red "x" as if the email/password are incorrect.
TVShow Time:
     - pop up window
     - authentification
     - succesful authorization of the app
     - the service keeps loading in Popcorn Time but nothing else happens
#### Steps to reproduce the behavior
1. install and open Popcorn time
2. go to settings
3. try to connect to any of the services

**Comment by ChrisAlderson** [comment]
Opensubtitles should be fixed in [#151](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/151/).

**Comment by ChrisAlderson** [comment]
Fix for this should soon be on ci.popcorntime.sh

**Comment by ChrisAlderson** [comment]
Should be fixed with the latest build (159).
