### ISSUE TITLE
trakt.tv not there in build 267

### ISSUE THREAD

**Issue by ahmedzeeee** [popcorntime/popcorntime#2547]
Operating System Version:

windows 11

Popcorn Time Version:

0.4.7 build 267

Download date:

8 July 2022

Download url:

https://popcorn-time.ga/build-ru/dev/Popcorn-Time-0.4.7+267.gac19b675-win64-Setup.exe

#### Expected Behaviour

...

#### Actual Behaviour

I don't see the trakt tv sync option in the settings anymore

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ivan1986** [comment]
![image](https://user-images.githubusercontent.com/156418/177985407-465f1ca4-04e9-4f18-a962-e609a7fdca7f.png)

**Comment by kiriles90** [comment]
It moved, also these are dev builds which means things are in progress, no use opening issues about them..

**Comment by kiriles90** [comment]
@ahmedzeeee https://github.com/popcorn-official/popcorn-desktop/commit/0a0ccd83691a438700519d0c6ec2da2fa126d9b0 merged, should make it a bit more obvious why the merge of the two options happened. Try the behavior with the latest dev build and let us know what you think.
