### ISSUE TITLE
Can't reproduce any movie or show

### ISSUE THREAD

**Issue by MinionAttack** [popcorntime/popcorntime#255]
Operating System Version: Windows 10 Pro 64-bit up to date.

Popcorn Time Version: 0.3.9 (Compilation 159 on Jenkins)

Download date: 20 - October - 2016
#### Expected Behaviour

Select a movie or show and watch it.
#### Actual Behaviour

I get the error: **The video could not be loaded, either because the server or network failed or beacuse the format it's not supported.**
#### Steps to reproduce the behaviour
1. Open Popcorn.
2. Select a movie or show episode.
3. Select Butter or VLC reproductor.
4. Press "Play"
5. You will get a black window also the video it's downloading and the error described above.

**Comment by ChrisAlderson** [comment]
Known issue, not every NWJS aspect of PT has been build, but playing in VLC will work.

**Comment by LuMagalhaes** [comment]
Same!

**Comment by spazioricci** [comment]
Same, it works also with chromecast...but not in butter mode
