### ISSUE TITLE
Chromecast Issues Casting

### ISSUE THREAD

**Issue by edwardcid** [popcorntime/popcorntime#2552]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.4.7

Download date:

Download url:

#### Expected Behaviour
 Casting video 

#### Actual Behaviour
 No casting, only connect to chromecast, but dont start casting.

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
Popcorn Time doesnt do re-encoding. If the Chromecast doesnt support the original codec the video wont play.

**Comment by edwardcid** [comment]
Stremio can do it with the sames torrents, please make an investigation!
