### ISSUE TITLE
downdload is going into cache foder 

### ISSUE THREAD

**Issue by Macintosh98** [popcorntime/popcorntime#2561]
Operating System Version:

linux

Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

downdload should be in downdload folder that i selected
...

#### Actual Behaviour

it is going in the cache folder that i given AND also i have checked on seperate folder checkbox
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
What version are you using? If its 0.4.7 try resetting your settings, setting the alternative download directory again and restarting the app. Then it should save to that folder when you click 'Download' and in the cache folder when you click 'Watch now'.
