### ISSUE TITLE
A "passthrough" option for audio decoding

### ISSUE THREAD

**Issue by SirBabou** [popcorntime/popcorntime#2563]
**Is your feature request related to a problem? Please describe.**
The Popcorn app doesn't seem to be able to decode 5.1 audio. That's too bad considering that there are a number of movie files with great audio.

**Describe the idea you'd like**
A passthrough option for audio decoding would remedy that.
That way the audio is not decoded by the Popcorn app but by another device down the line (an amplifier for exemple).
This passthrough option can be found on a number of softwares, like VLC or KODI.

**Additional context**
I'm neither a dev nor an audio expert so I'm not even sure this request makes sense, but it would be a great addition to Popcorn Time if it was feasible.

**Comment by kiriles90** [comment]
I think this is a driver issue. Either way Popcorn Time has nwjs handle these things, which is basically chromium + node, so like the fix for chrome that is still working (and necessary sometimes since 2014 as far as I can tell) is running the app with the `--disable-audio-output-resampler` flag. For Popcorn Time you can do that via `package.json` in the `"chromium-args":` line.

**Comment by SirBabou** [comment]
It worked like a charm ! I'm getting the full audio data.
Indeed an option in the settings would be handy.
Thanks a lot for the answer !

**Comment by kiriles90** [comment]
@SirBabou #2565 merged. You can try it if you want by downloading the latest dev build from the [Actions](https://github.com/popcorn-official/popcorn-desktop/actions) page or just wait for release version 0.4.8, it should be released soon.

**Comment by Nowa-Ammerlaan** [comment]
It doesn't seem to work on my Linux system with pipewire version 0.3.70. Or maybe I'm doing something wrong on my end? Passthrough works just fine in VLC.

**Comment by kiriles90** [comment]
@AndrewAmmerlaan Linux wont allow chromium flags if installed the normal way and https://github.com/popcorn-official/popcorn-desktop/pull/2565/files#diff-eef8304c1d310f0a355ad1691ba9d459a134a15d344edf895ddc5d89a80d44aeR629 is needed for the audio passthrough to work.

**Comment by Nowa-Ammerlaan** [comment]
> @Nowa-Ammerlaan Linux wont allow chromium flags if installed the normal way and https://github.com/popcorn-official/popcorn-desktop/pull/2565/files#diff-eef8304c1d310f0a355ad1691ba9d459a134a15d344edf895ddc5d89a80d44aeR629 is needed for the audio passthrough to work.

I have tried launching with this argument: `Popcorn-Time --disable-audio-output-resampler`. And I have also tried editing `/opt/Popcorn-Time/package.json` manually to include this argument on the `chromium-args` line. But this makes no difference for me. Playing the exact same file through VLC automatically passes through the ac3 audio via an optical cable.

**Comment by kiriles90** [comment]
@AndrewAmmerlaan it works when the flag is executed. @ivan1986 can probably explain it better.
