### ISSUE TITLE
Download all available subtitles when using the VLC Player

### ISSUE THREAD

**Issue by SirBabou** [popcorntime/popcorntime#2564]
**Is your feature request related to a problem? Please describe.**
When using the VLC Player, the Popcorn app only downloads 1 subtitle of the selected language.
Therefore this subtitle is rarely in sync with the movie file.

**Describe the idea you'd like**
The idea is to download all the available subtitles of the selected language from OpenSubtitles.
That way we could easily choose a synced subtitle on the VLC player, just like we can currently do on the Popcorn player.

**Conclusion**
This feature would be a fairly simple one and it would make choosing the VLC player a more viable option

**Comment by kiriles90** [comment]
You cant load multiple subtitles through the VLC command line nor most of the other media players afaik.

**Comment by SirBabou** [comment]
I see, I did not know that.
Thank you for the answer !
