### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by ivan1986** [popcorntime/popcorntime#2569]
Let's stick to what we wrote

https://github.com/popcorn-official/popcorn-desktop#versioning

or remove this part

0.4.8 - support more torrents
0.4.7 - support DHT
0.4.6 - support localization
0.4.5 - seedbox + custom server

we need remove first 0

0.3 -> 0.4 - total rewrite code

**Comment by ivan1986** [comment]
And then we may make bugfix releases

**Comment by yyyoh2021** [comment]
Ipa TVos Apple TV 
Can you help me to get the popcorn time file?

**Comment by ivan1986** [comment]
@yyyoh2021 ask this question to ios developers, not here
