### ISSUE TITLE
ETA for new version update?

### ISSUE THREAD

**Issue by Gabriel-p** [popcorntime/popcorntime#257]
Operating System Version:
elementary OS Loki (0.4), 64 bit

Popcorn Time Version:
[0.3.9-0 (80e3fc19)](https://github.com/popcorn-official/popcorn-desktop/commit/80e3fc1942efe7e4d6c9a1aa2066d917b33ba310)

Download date:
Months ago.
#### Expected Behaviour

Update itself at some point.
#### Actual Behaviour

Hasn't updated for months.
#### Steps to reproduce the behaviour

Not a bug (i think?) I'm just wondering when will the new version be released, since the current one was released 7 months ago.

**Comment by ChrisAlderson** [comment]
Latest build can be found here: ci.popcorntime.sh

**Comment by Gabriel-p** [comment]
Thank you @ChrisAlderson, I know where I can find the latest build. I'm inquiring about when will the app _auto-update itself_, as it used to do. It hasn't done this since March, and I'm starting to question whether this is expected or an issue in 0.3.9.

**Comment by ChrisAlderson** [comment]
We haven't updated since March, but we are working an update which should be available through the auto-updater when it's done.

**Comment by kim0** [comment]
@ChrisAlderson .. That is great news. I get new builds from ci as well, however in many cases they are too unstable (which is understandable) .. Any rough estimates when a new stable version can be pushed out (and hopefully used by the auto-updater as well) ? Thanks for your work!

**Comment by Gabriel-p** [comment]
So I get the old "when it's done". That's ok.

Thanks for the hard work Chris!

**Comment by ChrisAlderson** [comment]
It's hard for me to estimate, there are 4 more things we want to solve before pushing an update and 3 out of the 4 things are out of my hand. So I'm staying with the crappy answer **Soon<sup>TM</sup>**.

**Comment by ChrisAlderson** [comment]
Thanks for closing, also just pushed meaning 3 more issues to resolve.
