### ISSUE TITLE
On the release page, can there be added a summary of new features of main fixes?

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#2574]
This could help us understand what has changed

**Comment by kiriles90** [comment]
We dont manage this layout github does. You can either check CHANGELOG.md in the base dir of the repo or your installation or click the version number (bottom right) in the About page (top left of the settings page) in the app.

**Comment by fisforfaheem** [comment]
Thanks, if possible atleast add a link in Github Readme file to the change
logs
