### ISSUE TITLE
Native Window decorations do not work on Linux Arch + XFCE

### ISSUE THREAD

**Issue by tio-trom** [popcorntime/popcorntime#2578]
Please allow for native window decorations. On Linux this is important and provides a lot of functionalities. I can not right click the window bar and have any system options, like sending the window to another workspace, have it stay on top, and so forth. Thanks!

EDIT: There is an option in Popcorntime to use native window decorations but on Arch Linux + XFCE it does not work.

**Comment by kiriles90** [comment]
Check the settings there is a 'Native window frame' option.

**Comment by tio-trom** [comment]
Ah ok, maybe you should make this as default...makes a lot more sense.

However I have enabled that and doesn't work. I am using Arch + XFCE. I even restarted popcorntime. Nothing changes. How to debug?

**Comment by kiriles90** [comment]
Not everyone uses linux or wants a non-skinned titlebar so no this wont be made the default option.  

> However I have enabled that and doesn't work

This is all handled by NW.js. The option just edits the window.frame option in package.json from false to true and requires restarting the app to apply.

**Comment by tio-trom** [comment]
> Not everyone uses linux or wants a non-skinned titlebar so this wont be made the default option.

This is about respecting the system. Since you already have this option the sane way is to let the system decide how to handle the window. Regardless if it is MacOS, Windows or Linux. Why would you force your own window decoration as default?

> This is all handled by NW.js. The option just edits the window.frame option in package.json from false to true and requires restarting the app to apply.

As said, I did that.  And it does not work. Did you test it on Linux for example?

Cheers

**Comment by kiriles90** [comment]
Popcorn Time always was and still is a skinned app. Everything is skinned from the window frame down to the individual UI elements. The native frame option was added somewhat recently by a contributor who wanted to use the Windows 10 titlebar. As for the option not working in a specific OS, like I said, all that is handled by NW.js, if the flag doesn't work it doesn't have much to do with Popcorn Time code.

**Comment by tio-trom** [comment]
But all applications work and I test thousands for a library that we have for our own operating linux system. Popcorntime is the only one, out of thousands, that does not work to have a native window decoration. Based on that I would say that it is an issue with Popcorntime rather than the OS. Can we please let this issue open? I will change the title to better reflect the issue and see if others can test it on other OSes and confirm it.

**Comment by kiriles90** [comment]
Leaving the issue open wont change the fact that this wont be made into the default option nor that the issue you are facing with the flag not working on your specific OS is not due to Popcorn Time code. If you believe otherwise debug it, the app is open-source, then if it is indeed an issue with the app we can re-open it.

**Comment by tio-trom** [comment]
Dear friend I have tested your app on a Linux distro and one of the app's settings does not work on this distro. As simple as that. If you leave it open, maybe others can test it on different operating systems. I can also do that on other Linux distros. The fact that 1 app out of one thousand has this issue on the same OS, is likely to come from the app itself. 

Please be wise and leave this specific issue open so that we can test it more on other Linux distros.

> Leaving the issue open wont change the fact that this wont be made into the default option

Is there a good reason for not respecting the system's theme?

**Comment by kiriles90** [comment]
> Is there a good reason for not respecting the system's theme

Yes, messing with app aesthetics. Is there a reason for acting like its too much trouble toggling an option and trying to enforce your preferences on everyone?  

As for the issue I wont leave it open when there's nothing to be done about it in Popcorn Time code without overcoming the nwjs update issues for which there is already an open issue about.

**Comment by tio-trom** [comment]
> Yes, messing with established app aesthetics.

But operating systems handle the windows in different ways for practical reasons. For example some systems have the window buttons in the left side, some have them integrated into a top panel, and overall one can right click the top bar of a window and get a lot more options that are even necessary for people with disabilities. 

>  Is there a reason for acting like its too much trouble toggling an option and instead trying to enforce your preferences on everyone?

It is beyond me why you take this so personal. I told you it does not work on my system and it is very likely an issue with PopCorn Time itself. But you refuse to leave this issue open so we can try and debug it and test further. This is one of the most disappointing conversation I am having on github, and I report and debug a ton (a ton) of apps for many years now. I am trying to help out here. Please relax and let us fix this.

>  fork it and do whatever you like.

Please don't use that to close this conversation. I will ask some friends to test Popcorn Time on other systems and see if the native window decoration thing works or not.

**Comment by kiriles90** [comment]
Man.. do you understand what a package.json flag is? You can bring 20 people to test it, that doesnt change who handles which code. Its NOT Popcorn Time code in there, THE END. Set the damn flag manually, bypass Popcorn Time's settings, and see if it works, nothing else to be done about it. As for your personal preference of doing the native frame the default option, no, like I said fork the app and do whatever you want with it if toggling an option once(!!) is too much trouble for you.

**Comment by tio-trom** [comment]
> Man.. do you understand what a package.json flag is?

If this is not a Popcorn Time related issue where should I submit this issue?

> Set the damn flag manually, bypass Popcorn Time's settings, and see if it works, nothing else to be done about it. 

Why are you so angry? I took my time to report this so that we can find a solution. If you were to explain to me where the issue might be and where to report this, then we would not have chatted so much here. Calm down a bit.

> As for your personal preference of doing the native frame the default option, no, like I said fork the app and do whatever you want with it if toggling an option once(!!) is too much trouble.

There is an objective argument that you should enable it by default. Systems' preferences (dark theme, window buttons and the position, window settings - right click menu) are there for a reason. If your app ignores them by default then it enforces your preferences over the user's preferences. You know there are people with disabilities that may not be able to see Popcorn Times little right side window buttons. Even I struggle to use them on my 17inch laptop. 

You should try to be more friendly so we can understand each other.

**Comment by tio-trom** [comment]
Look how small and different your built-in window buttons are:
![2022-07-19_14-01](https://user-images.githubusercontent.com/38043315/179745308-d57a800d-e495-4a59-ba30-ea3f8449c48e.png)

**Comment by kiriles90** [comment]
> I took my time to report this so that we can find a solution.  

It would have helped trying to understand also instead of just "reporting". I told you the answer from my first comment. 

> Why are you so angry? 

The subsequent 10 repeated answers in case you believe me.  

>  You know there are people with disabilities that may not be able to see Popcorn Times little right side window buttons. Even I struggle to use them on my 17inch laptop.  

People with disabilities have the UI scalling option and they can make UI elements as big as they like. People with OCD on the otherhand.. can go and toggle the option themselves instead of trying to force it on everyone. Other than the guy who merged this native frame option, you are n2 that comes around over multiple years with this "terrible issue"..

> You should try to be more friendly so we can understand each other.

You should try not to bust people's ... until you get your way and instead read some/comprehend more, then people might also be more friendly and more understanding.

**Comment by tio-trom** [comment]
> It would have helped trying to understand also instead of just "reporting". I told you the answer from my first comment.

Friend this is your app, so you should help me figure this out in case I do not understand. As a user, I click one of the options, and it does not work. As simple as that. So I try to report it to you. We are not all programmers. That being said, is this where I should report it https://github.com/nwjs/nw.js ?

> People with OCD on the otherhand.. can go and toggle the option themselves instead of trying to force it on everyone.

Are you aware of your attitude or you need others to remind you that this is not a good way of engaging with people? These things like respecting the system's options, go far beyond just "look" or OCD as you call it. They are part of usability. Maybe you are used to Windows that is all a mess, but Linux is designed better in terms of usability so it is important to respect that. This is not "my way" this is usability 101.

**Comment by kiriles90** [comment]
From my second comment:

> **This is all handled by NW.js. The option just edits the window.frame option in package.json from false to true** and requires restarting the app to apply.  

Did you even try to understand it or just skipped over all my answers trying to get an 'ok' in an issue you cant get one? I don't think you did because then even if you didn't know what I meant with the above you'd have asked for further explanation.

> Are you aware of your attitude or you need others to remind you that this is not a good way of engaging with people? 

I don't engage people like this, you are a special occasion. (you figure the 'why' out, I shouldn't judge others as you've said..)

> They are part of usability. Maybe you are used to Windows that is all a mess, but Linux is designed better in terms of usability so it is important to respect that. This is not "my way" this is usability 101.

Again.., you are the second person that came over with this issue over the span of.. 5 years.

P.s this is not my app, but because I know more about it and did more for it, I decide more about it in the official repo. Again though, this is an open-source app, though your options atm is to fork it do what you want with it, we cant give you access to the official repo out of nowhere to merge stuff obviously. Just dont ask me to fix something for you that I tell you cant be fixed unless.. etc etc. I don't work for you nor I'm getting payed by anyone. My reward is the (hopefully not so frequent) people like you that show their appreciation.

**Comment by tio-trom** [comment]
> Did you even try to understand them or just skipped over all my answers trying to get an 'ok' in an issue you cant get one? I don't think you did because then even if you didn't know what I meant with the above you'd have asked for further explanation, its usually how it goes.

I apologize I didn't understand your correctly when you talked about NW.js and sent me to open an issue somewhere else. I think your attitude made me not understand that you also said some useful things about NW.js. I will look into that. Again, I apologize for that but you should definitely be more friendly. 

> I don't work for you nor I'm getting payed by anyone. My reward is the (hopefully not so frequent) people like you that show their sincere appreciation.

Friend I appreciate your work. I never worked for money and I am doing free projects since 2007. Thousands of people use them. I know how it is to work for the sake of the work and not to make money. I appreciate that you do it the same and I am sorry that I didn't pay enough attention to your comment about NW.js and the specific issue you linked.

We, as humans, can always change and approach things differently. 

Now, do you think it is ok to open a new issue here about making the native window decorations as default and leave that as a friendly discussion to see what othes have to say about it?

**Comment by kiriles90** [comment]
Friend, why do you want to unskin the UI/parts of it so desperately for everyone? Is it not enough toggling the option once for you and forgetting about it? You want it to match with the OS, the majority want it to match with the app. Different philosophies so the guy who wrote that option went to great lengths to make it possible to be exactly that, an option (had to find a way to edit package.json from the app). With your thinking where does it stop? What do you want to unskin next to match the OS? Checkboxes, radio buttons, menu's, fonts, colors or all of the above? Just respect that Popcorn Time is a top to bottom skinned app that looks/always looked a certain way and even with that it still gave you an option to use the native frame (not working in your OS like I said isnt our fault) instead of asking us to respect Linux..

**Comment by tio-trom** [comment]
> Friend, why do you want to unskin the UI/parts of it so desperately for everyone?

This is not desperate at all. I wanted to suggest that to you from a usability perspective. Now that you asked, and I answered a few times before, let me list you the motives again:

1. Many people work at night, like me, so a dark theme is always useful to not burn your eyes. Therefore apps should respect the system's theme for that reason. I understand that some do not and is fine, and PopcornTime already has different themes to choose from, but this is one very good reason to make apps respect the system's theme. Usability and not just look.

2. Respect the window decoration. The titlebar and window buttons are an essential part of an OS. They provide functionality and familiarity. Imagine if all apps put the window buttons (that are essential) in any side of the window, and with different designs. It will become a mess. More to that, you are disabling the right click actions that allow users to minimize, close, move to a different workspace, add a window on top, and so forth. Basically with your own app window decoration you are removing features for users. For example for our TROMjaro OS we allow the merging of the top bar with the top bar of the system, to create more working space. With yours won't work as default of course, so you remove more functionalities.

> Maybe the lesson here is to listen/read a bit more, especially when we know we don't know much about the subject.

You also made me repeat the above but is fine, I am nice and friendly and I can repeat.

And look, I really don't care. Popcorn Time is one of the thousands of apps I am testing. But I hoped that you can listen to the reasons why you should respect the system's theme by default, as 95% of apps on Linux do. If you choose to be different for subjective (design/style) reasons, there is no way I can convince you otherwise. I hope that at least the native window decoration will be fixed for Linux. We tested on other desktop environments in Linux and it does not work.

**Comment by kiriles90** [comment]
Like I said before.. "skinned top to bottom" and "where does it stop"? What do we unskin next because "linux does it better"? Thing is.. with all these customisations, builds, different window managers etc, its a lot more difficult for apps to respect you than e.g Windows. (and yes userbase size is also a concern before deciding one way or the other)

**Comment by tio-trom** [comment]
> "where does it stop"? What do we unskin next because "linux does it better"? 

Simple. You can stop at the native window decoration. The easiest and perhaps most impactful. You already added that but doesn't seem to work with Linux. It is ok, I commented on the thread you suggested. Maybe it will be fixed some day. 

> Thing is.. with all these customisations, builds, different window managers etc, its a lot more difficult for apps to respect you than e.g Windows. 

I have tested thousands of apps on Linux and somehow they seem to do just fine at respecting the system's theme. I hope they keep on doing that so that we have a sane desktop environment.

Anyway. We can leave it at this. I never meant to be rude to you or anything like that. I appreciate the work people put in such pieces of software. Take care.

**Comment by cghislai** [comment]
When toggling that option, the app tries to write to package.json on startup, which is installed on my arch distribution at /usr/share/popcorntime/package.json.

Unfortunately, its not writable. You can edit as root to make the change:  set window.frame to true.

See https://github.com/popcorn-official/popcorn-desktop/blob/77db9e30b1b2bbd51b03f111b586fbe4f2319cf7/src/app/lib/views/main_window.js#L333
and https://github.com/popcorn-official/popcorn-desktop/blob/77db9e30b1b2bbd51b03f111b586fbe4f2319cf7/src/app/lib/views/settings_container.js#L648
