### ISSUE TITLE
Streaming through Smart TV not working

### ISSUE THREAD

**Issue by NE03N** [popcorntime/popcorntime#258]
Operating System Version:
OS X 10.12

Popcorn Time Version:
0.3.9 build #161 

Download date:
22 October 2016
#### Expected Behavior

stream to smart tv
#### Actual Behavior

the smart tv is detected and was working in the previous versions before i update to OSX Sierra but now the streaming breaks after a few seconds or minutes saying "check your network connection" on the tv but on popcorn time it keeps streaming as if everything was fine.
#### Steps to reproduce the behavior
1. turn on smart tv
2. launch popcorn time
3. choose smart tv in streaming options and then Watch.

**Comment by team-pct** [comment]
When trying to cast press CMD+0 you will have a console please past any logs

**Comment by NE03N** [comment]
i guess i need to report another bug... can't call the console with CMD+0... any other way to do it?

**Comment by team-pct** [comment]
Try restart the app and open console on opening then keep it on background

**Comment by NE03N** [comment]
the console showed no errors (first log) so i've tried a second time and it only showed an error when i turned the tv off after the streaming stopped and it gave me the message "check your internet connection" (second log)

[hecfofbbdfadifpemejbbdcjmfmboohj-1477125924813.txt](https://github.com/popcorn-official/popcorn-desktop/files/545690/hecfofbbdfadifpemejbbdcjmfmboohj-1477125924813.txt)

[hecfofbbdfadifpemejbbdcjmfmboohj-1477126147392.txt](https://github.com/popcorn-official/popcorn-desktop/files/545691/hecfofbbdfadifpemejbbdcjmfmboohj-1477126147392.txt)

**Comment by team-pct** [comment]
Yes , i have the same issue  , but it is related to your TV , Samsung isn't able to read MKV trough Streaming only via DLNA Server 
If you try a movie ( Most of them are still mp4 ) it will work

**Comment by NE03N** [comment]
i don't think it's the case coz i've been playing all kinds of files even .mkv through popcorn time on my smart tv before without a single issue until i upgraded to this stupid OSX Sierra. plus i've just tried right now streaming an .mp4 and it made no difference, same result...

**Comment by team-pct** [comment]
I was testing again with a Samsung TV , and yet the same result as before , Samsung TV are unable to read MKV from Popcorn Time but do read Movies from YTS

**Comment by NE03N** [comment]
not all Samsung TVs are unable to read MKV as a matter of fact mine reads them without a problem and if you don't believe me i can upload a video showing everything but i'm telling you as i said before; i used to stream EVERYTHING with no issues whatsoever through popcorntime before the stupid OSX Sierra update but now neither mp4 nor mkv are working anymore...

**Comment by MrSolverMaybe** [comment]
So, listen up. I MIGHT have a solution to your problem which should be easy to try. Turns out the web feature of Youtube - to stream to your TV without a chromecast - can actually prevent Popcorntime of connecting to your TV. I guess when your computer is on without technically disconnection properly from Youtube, Youtube simply doesn't allow other (Popcorntime) connections. Via Youtube you can disconnect this connection by hand easily. Just reconnect to you TV with Youtube - like, just watch something again - by clicking the disconnect button on the web feature again. Of course this solution holds for any other possible active outgoing connection on you computer. Good luck!

**Comment by AntonioVentilii** [comment]
any news on this?

**Comment by chlebta** [comment]
Have some issue, some movies are working via Samsung Serie 6 but for series and some movies this not working, even if the full episode or film was downloaded nothing it's not played on TV.

**Comment by lginq** [comment]
TV: Sony KD-49XE7077
Tried both macOS and Windows, I'm able to find TV and to start streaming but the picture on tv freezes after 20sec. 
in the console it just says "streaming to <tv_name>".

Anyone else has the same issue, any help?
