### ISSUE TITLE
Favorites art not updating

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2581]
Operating System Version:
Windows 10  (21H1)

Popcorn Time Version:
dev build b926405c

Download date:
18-07-20

Download url:
Github

#### Expected Behaviour
update art in "Favorites" folder

#### Actual Behaviour
Art stay's the same from when it's added to the "Favorites" tab

#### Steps to reproduce the behaviour
Add a series to the "Favorites" tab and wait till art is changed in the "Series" tab

**Comment by dutchy1001** [comment]
that fixed it for now, not sure you want to change it as you said

**Comment by kiriles90** [comment]
> Nevertheless.. maybe it should apply to favorites too.  

I leave the final call on this on @ivan1986 since he knows the internals better.

**Comment by dutchy1001** [comment]
I'll reopen it then so Ivan can see

**Comment by ivan1986** [comment]
favs save in local base all media object
it not update after you save
for change this need maybe change movie details page (we get it from list) and batch update favs list - store in favs only minimum as we have in show list

**Comment by ivan1986** [comment]
for now it may be fix by "rebuild favorites database" button

**Comment by dutchy1001** [comment]
that's a nice option, is this something that can be triggered as soon they click on the "Favorites" tab? then it's solved for good.

**Comment by kiriles90** [comment]
Might be a bit excessive triggering a database rebuild everytime you open the tab? :smile:

**Comment by ivan1986** [comment]
ios client make some about it and get ban on nginx
no, it's bad solution - it's many requests and it's not need
not need update more 1 time in month, maybe add last update date and add 
select `where last <now()-30 days limit 3`

**Comment by dutchy1001** [comment]
might be the heat that gets to my head 🥵🥵🥵
