### ISSUE TITLE
Separate Cache folders 

### ISSUE THREAD

**Issue by juantinazzo** [popcorntime/popcorntime#2585]
The idea is to have separate Cache folders for Movies, Series and Anime. I use Popcorn with Jellyfin a lot, and it would make it almost trivial to point the cache directories to where I store the content "long term" (actually a couple of hours). 
If all the content is in one folder Jellyfin gets confused about what is a "movie" and what is a "TV show", so having the option to choose 3 different places would be great.
Thanks!

**Comment by kiriles90** [comment]
Not sure if this would make any sense in most use cases but tagging it as a feature request for now.
