### ISSUE TITLE
Constant restart

### ISSUE THREAD

**Issue by darcsa** [popcorntime/popcorntime#2586]
I download 0.4.8 and install for Mac. I choose enable automatic updating otherwise it doesn’t open or opens and doesn’t load any movies or series. I update the API servers, change to the new URLs and restart. It is a constant cycle where it’s the same series of repetition and nothing ever loads. Pictures attached.

![FF7DF7DF-4A08-41E6-9647-066B9C63C150](https://user-images.githubusercontent.com/109919838/180661394-c95121be-e2f6-40c1-87db-dbbc76ef6f98.jpeg)
![5D516853-CDDA-42C6-A6B1-B4AA0918EDC7](https://user-images.githubusercontent.com/109919838/180661397-fd5dc8f7-3bdf-43f8-94af-e8bb09cad8e6.jpeg)
![Uploading 27CCA77F-397A-422E-BC9F-3728B8AAADA3.jpeg…](
![AFA2B261-48A7-4C7A-933E-E0794A3914CB](https://user-images.githubusercontent.com/109919838/180661384-ba8a99a4-72bf-495e-886d-4334ce961048.jpeg)

Operating System Version:

Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by darcsa** [comment]
![Uploading 8D9798E8-33A6-4407-98E9-40BD4B25360D.jpeg…]()

**Comment by kiriles90** [comment]
Not sure if I understand correctly, but once you accept the terms of service and complete updating the api and click 'yes' to change them and restart.. you see get the terms of service again? If yes, something is bugged in your user data from previous installations, clear them and reinstall.

**Comment by darcsa** [comment]
I have reinstalled three times and the setting icon is inaccessible. How do I clear there or somewhere else?

Sent from my iPhone

On 24 Jul 2022, at 11:48 PM, kiriles90 ***@***.***> wrote:

﻿

Not sure if I understand correctly, but once you accept the terms of service and complete updating the api and click 'yes' to change them and restart.. you see get the terms of service again? If yes, something is bugged in your user data from previous installations, clear them and reinstall.

**Comment by darcsa** [comment]
I have reinstalled three times and the setting icon is inaccessible. How do I clear there or somewhere else?

Sent from my iPhone

On 24 Jul 2022, at 11:56 PM, kiriles90 ***@***.***> wrote:

﻿

Closed #2586<https://github.com/popcorn-official/popcorn-desktop/issues/2586> as completed.

**Comment by kiriles90** [comment]
Uninstall everything, then delete
`~/Library/Application Support/Popcorn-Time`
`~/Library/Cache/Popcorn-Time`
`~/Library/Saved Application State/com.nw-builder.popcorn-time.savedState`
`~/Library/Preferences/com.nw-builder.popcorn-time.plist`
and restart. Then re-download the 0.4.8 .zip from here in the releases page (for good measure) and reinstall.

**Comment by darcsa** [comment]
This worked outstandingly. Thanks so much. I know it got a little detailed with your instructions but they worked. I appreciate it.

Sent from my iPhone

On 25 Jul 2022, at 1:34 AM, kiriles90 ***@***.***> wrote:

﻿

Uninstall everything, then delete
~/Library/Application Support/Popcorn-Time
~/Library/Cache/Popcorn-Time
~/Library/Saved Application State/com.nw-builder.popcorn-time.savedState
~/Library/Preferences/com.nw-builder.popcorn-time.plist
and restart. Then re-download the 0.4.8 .zip from here in the releases page (for good measure) and reinstall.
