### ISSUE TITLE
How to use a different VPN

### ISSUE THREAD

**Issue by Beaconmember** [popcorntime/popcorntime#2587]
I downloaded IP Vanish VPN to use with Popcorn Time but I don't know how to select IP Vanish VPN from the Popcorn Time App. Can someone get back to me on this? I am unable to view movies or anything on Popcorn Time. Popcorn Time wants me to purchase their VPN but I rather use the IP Vanish VPN that I downloaded.

**Comment by kiriles90** [comment]
Requested details are there for a reason. Closing this since we have no idea what you use but as a general rule for your question.. its just an ad, whatever system wide VPN you use will work for Popcorn Time too. Just make sure you select a server that supports p2p.

**Comment by dutchy1001** [comment]
You don't need to select the VPN for Popcorn Time. If the VPN is running on your PC it should then be OK. You can turn the VPN message of in the Settings tab

**Comment by Beaconmember** [comment]
I did have a vpn running before I opened Popcorn time but no movies came up. I have a iMac. I’m not home right now so I can’t tell you the version. It keeps giving me a unsecured message

**Comment by dutchy1001** [comment]
Make sure the country you choose with the VPN doesn't block Popcorn time. I don't know iMac's as I'm a Windows user, but in general the VPN should work the same. 
If no movies/series are showing then you might need to update the API, this can be set in the settings to automatic (this is recommended)

**Comment by Beaconmember** [comment]
I download another Popcorn Time app package and this time it worked. It was the third app I tried. Thank you.

**Comment by Beaconmember** [comment]
Thank you everyone. Great information about the settings that I didn’t know. God bless you all. 😃👍
