### ISSUE TITLE
[Windows] [v0.4.8] Subtitles are stuck in one position.

### ISSUE THREAD

**Issue by CortexReaver** [popcorntime/popcorntime#2590]
Sometimes subtitles are stuck in one position, and you need to cancel watching and then start it again. After 2 or more restarts it might help and they work again as intended.
Seems like this is an issue when movie is not fully loaded, when its 100% subtitles are perfectly fine.

**Comment by kiriles90** [comment]
When they are stuck check your CPU/Ram usage. It should be sky-high (on a bit of a slow pc or one with very high internet speed) its the torrent.., try the latest dev build from the actions page, it might help.

**Comment by CortexReaver** [comment]
No, CPU\RAM is fine (12% of CPU max and RAM is always 25%). Maybe we are talking about different bugs? Because in my case they are not stuck permanently, if you rewind a bit with arrowkeys or a seekbar subtitles will change. So to change them you need be rewinding constantly.

**Comment by dutchy1001** [comment]
Is there a chance that when this happens you can do a debug using F12 and post any errors?

**Comment by kiriles90** [comment]
@CortexReaver no same bug. 12% is 100% of the one core of your 8 core cpu. Webtorrent can only run on mai thread/core.

**Comment by CortexReaver** [comment]
@dutchy1001 Ok, I will try to do this next time I watch something.
