### ISSUE TITLE
brew install appears to be for intel only

### ISSUE THREAD

**Issue by fulcus** [popcorntime/popcorntime#2593]
Operating System Version: macOS 12.4
M1 arch

#### Steps to reproduce the behaviour

1. `brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git`
2. `brew install --cask popcorn-time`

#### Output
```
==> Downloading https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/downloa
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################## 100.0%
Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
```

**Comment by kiriles90** [comment]
There is no M1 native version of Popcorn Time at the moment. It requires updating the version of NW.js we use for which there is already an open issue about along with all the issues with doing so. (https://github.com/popcorn-official/popcorn-desktop/issues/2062)

@danielbayley had tried to modify the brew install to present an option between the normal-old NW.js with all the codecs and a newer NW.js version lacking some codecs but that runs better on Monterey and later, not sure what happens with apple silicon though. Closing this but join the NW.js issue for M1 updates, as for casks, realistically.. unless @danielbayley takes a look at it none else will. (if there is something to be changed/fixed there)

**Comment by fulcus** [comment]
It should be mentioned in the readme that the brew version is only for Intel-based macs

**Comment by Kief5555** [comment]
@kiriles90 Can you unlock again so I can edit docs please?

**Comment by kiriles90** [comment]
@Kief5555 yep, done

**Comment by kiriles90** [comment]
@Kief5555 no worries, just let me know when you are done so I can re-lock them. (a bit to lazy to check them everyday in case someone defaced them or trying to redirect users to a virus or something, better be locked and just unlocked for whoever wants to edit them)
