### ISSUE TITLE
Gulpfile and Gruntfile?

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#26]
A little weird that there is both a gruntfile and gulpfile. It should be one or the other. The gulpfile seems to only holds the build process of the binary.

It would be better to have everything in gulp instead, it is considerably faster than grunt.

**Comment by micopiira** [comment]
:+1:

**Comment by giacomocerquone** [comment]
I don't even get why people need to use grunt or gulp and here you're even using both of them.
This is a mess.
If someone help me understanding what grunt is needed for, I'd be more than happy to help you!

The thing that I don't understand properly is that in the README grunt isn't mentioned and to build the project we just need to give a gulp start or an npm start (which launch gulp again).

The only parts where I read that grunt is requested are: postinstall, postupdate and test. I get the test, but what about `grunt setup` of postinstall and postupdate? What do they do?

**Comment by VitorVRS** [comment]
What i know is that gruny is legacy and they are slowly removing it.

**Comment by ChrisAlderson** [comment]
This issue should be fixed with #223
