### ISSUE TITLE
Filter movies by a specific year e.g. 1992

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2601]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I want to watch movies from a specific year and the only option available is to sort by year and scroll through all the movies till I get to the year I want. For example, If I wanted to see a movie list of all the movies made in the year 1992.  The scrolling down option takes a long time and progress is lost if the app is closed. 

**Describe the idea you'd like**
I would like to be able to sort movies or shows by year and then be able to choose a specific year (e.g. 1992) from a scroll down and see a list of movies/shows from that year. 

**Describe alternatives you've considered**
Current alternative is to sort by year and scroll down until movies/shows from that year appear. 

**Additional context**
<img width="355" alt="Screen Shot 2022-08-09 at 6 58 42 PM" src="https://user-images.githubusercontent.com/110923598/183701326-ac7d4072-a2c1-4968-9969-6ceceb128541.png">

**Comment by kiriles90** [comment]
This depends on the API not the app. E.g if using the YTS API you can add the year in your search query. Closing this but if you want since from what I understood your issue is with the RU API open an issue at its repo. (the one for the API not the RU app)

**Comment by ghost** [comment]
Thanks for your help resolving the issue, I was indeed able to change the movie API to YTS and search by a specified year. For anyone else facing a similar issue, go to settings > API Server(s) > Movies API Servers(s) > https://yts.mx/. Although this example is for movies you could do the same thing for series and anime. Once you've made those changes go back to the movies tab and search for a specific year.

<img width="1017" alt="Screen Shot 2022-08-10 at 4 13 06 AM" src="https://user-images.githubusercontent.com/110923598/183788899-7f09aca8-2c1a-41e0-af46-42eaf40d017e.png">
