### ISSUE TITLE
IMDB rating support.

### ISSUE THREAD

**Issue by KAGEYAM4** [popcorntime/popcorntime#2602]
**Is your feature request related to a problem? Please describe.**
currently i don't know where the rating is fetched from - maybe tvdb but even then it feels IMDB is more correct . for example this --

![image](https://user-images.githubusercontent.com/75798544/183741916-3e7256f5-536c-4084-9194-88c7d7bbe538.png)

**Describe the idea you'd like**
if possible support for imdb rating or more real rating.
![image](https://user-images.githubusercontent.com/75798544/183742094-40edded9-39e1-4d79-988a-73b9aff2c517.png)
![image](https://user-images.githubusercontent.com/75798544/183742458-204240f0-6311-488d-9c16-397e04d45d98.png)

**Comment by dutchy1001** [comment]
I think it has to do with the API and what fields it can fetch. 
As far I can find out the API for IMDB will bring costs with it, considering this is an open source project money is then not an option.

To be honest I personally don't look/care at the ratings as each person likes different things. What you might think is a 5 star movie I might not give it 1 star or visa versa.

**Comment by kiriles90** [comment]
What @dutchy1001 said. The rating comes from the API with the rest of the metadata in a single call. Whatever a specific API uses, Popcorn Time shows. There is also already an open feature request for multiple/alternative rating providers so closing this one.
