### ISSUE TITLE
Ability to clip and record parts of the movies or tv shows.

### ISSUE THREAD

**Issue by julianbrasse** [popcorntime/popcorntime#2603]
It would be really cool if the ability to clip key moments and take screenshots of some movies or tv shows and have them exported as .mp4 or .mov files and make them shareable, like in this example.
![Popcorn Time](https://user-images.githubusercontent.com/97521959/184242833-7363c06f-eb5a-4cd6-9ea3-451b9a66a552.gif)

**Comment by kiriles90** [comment]
This has been mentioned a couple of times before but exceeds the scope of this app a bit and might even add more legal issues for everyone. You can use the external player option and select one of the supported external players that has the record option if you'd like though.
