### ISSUE TITLE
The subtitle languages flags were disappeared.

### ISSUE THREAD

**Issue by lkhn** [popcorntime/popcorntime#261]
Operating System Version:
Arch Linux 64-Bit on GNOME 3.22.1 Wayland

Popcorn Time Version:
ci.popcorntime.sh version: # 166 

Download date:
2016-10-23 03:44:33 +04 
#### Expected Behaviour

To show subtitle languages as the flags as usual when entering any movies. (to checking which languages is available for current movie.)
#### Actual Behaviour

Do not any show subtitle languages as the flags as usual when entering any movies. (Cannot checking any languages is available for current movie.)
#### Steps to reproduce the behaviour

1. Click to any movie on Movies section.

Then: From ( https://get.popcorntime.sh/build/Popcorn-Time-0.3.9-Linux-64.tar.xz )

![screenshot from 2016-10-23 04-16-06](https://cloud.githubusercontent.com/assets/10092215/19623351/93ccd3f0-98d7-11e6-898c-bcfa50338b6d.png)

Now: From (https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastSuccessfulBuild/artifact/build/Popcorn-Time-0.3.9_linux64.tar.xz)
![screenshot from 2016-10-23 04-11-52](https://cloud.githubusercontent.com/assets/10092215/19623362/de3a5246-98d7-11e6-8a4d-bbd59d0cf1d8.png)

**Comment by carlosnpz** [comment]
Greatest bug ever. Not solved in a long time...

**Comment by team-pct** [comment]
Try Settings - Default Subtitle

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/227#issuecomment-255477682

**Comment by lkhn** [comment]
@team-pct @ChrisAlderson I selected my Default subtitle of course( LOL). Just a question a want to ask. What is the point to deleting this awesome feature? It is useful feature checking which subtitles is available for new movies before launch it. Please bring back it everyone wanting this feature.

**Comment by Gogy** [comment]
So now you need to open the movie if you wan't to see if the subtitles in your language are available. Doesn't make any sense. Please, please bring it back. Thank you.
