### ISSUE TITLE
Chromecast: no audio when casting a video

### ISSUE THREAD

**Issue by guidaccio** [popcorntime/popcorntime#262]
Operating System Version:
Windows 10 Home (V.1607)

Popcorn Time Version:
0.3.9-0
Download date:
23th october 2016
#### Expected Behaviour

Play to Chromecast at 720p.
#### Actual Behaviour

Play to Chromecast at 720p without audio
#### Steps to reproduce the behaviour
1. play to chromecast at 720p

This problem was in the the last build, too...

**Comment by team-pct** [comment]
Chromecast do not Support AC3 
We do not Transcode videos 

Please use 480p or No AC3 Video File

**Comment by khaledali1001** [comment]
when casting movie on 720p it works, but when casting series n 720pp audio doesn't work!
what is the resolution ?

**Comment by bronestly** [comment]
same issue

**Comment by ghost** [comment]
same issue too :(

**Comment by visualdensity** [comment]
Same issue too

**Comment by Jonyx4** [comment]
Same issue here!
