### ISSUE TITLE
Aspect Ratio Option Missing

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#263]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
10/22/2016
#### Expected Behaviour

I want to change the Aspect Ratio but there's no option for that
#### Actual Behaviour

It has no Aspect Ratio option
#### Steps to reproduce the behaviour

Add the Aspect Ratio option

**Comment by ChrisAlderson** [comment]
If you really want to change the aspect ratio you can always use an external player.

**Comment by GKid94** [comment]
What external player?

**Comment by ChrisAlderson** [comment]
VLC, MPC those are two popular video players.

**Comment by GKid94** [comment]
Why do i need that if i have PopcornTime?

**Comment by ChrisAlderson** [comment]
And Popcorn Time has the options to play videos in an external video player. The option is right next to the 'Watch Now' button.

**Comment by GKid94** [comment]
Yeah but that player sucks it's just the Windows Media Player the PopcornTime one is much better can you please add the option please? :/
