### ISSUE TITLE
VLC not added to list of players on Fedora 36

### ISSUE THREAD

**Issue by BaktashGorgani** [popcorntime/popcorntime#2633]
Operating System Version:

Fedora 36

Popcorn Time Version:

.4.8

Download date:

Two days ago

Download url:

https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.8/Popcorn-Time-0.4.8-linux64.zip

#### Expected Behaviour

...
On Windows, VLC is added to the list of players automatically

#### Actual Behaviour

...
Does not show up, chromecast devices still show up

#### Steps to reproduce the behaviour

1. ... download the .zip file
2. ... install using instructions from readme
3. ...check list of players when selecting a movie

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/17418270/188368098-0013fdbb-487f-4063-b3de-07ed53174f2d.png)

![image](https://user-images.githubusercontent.com/17418270/188368516-dfaf1855-24fe-4170-b1c8-b4df45a59315.png)

**Comment by kiriles90** [comment]
How did you install VLC? Normal install from official source? Is the path that it ends up in not listed in https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js#L231-L236 ?  

As for that error below, is not related. Its because the 'Native frame' and 'Audio passthrough' options require the app to have write access to package.json, which Linux by default does not allow. There is a closed issue somewhere but afaik other than various workarounds there is no real solution. Linux just doesnt give write access to package.json to the app, I guess for security purposes. The simplest workaround imho rather than trying to install the app with weird ways is to just set those flags in package.json manually. And I guess a note should be added next to them for future reference for linux users.

**Comment by BaktashGorgani** [comment]
Thanks for the info, I manually edited the package.json file to full rw access for everyone.

> How did you install VLC? Normal install from official source?

I installed it through a flatpak on fedora so it is an official source. Flatpaks are essentially isolated environments (which makes more sense now why it cannot be found). They are similar to snap packages.

> Is the path that it ends up in not listed in https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js#L231-L236 ?

It is installed in `/var/lib/flatpak/app/org.videolan.VLC/x86_64/stable/e737adfbdb87e287835209fb7defc1ecfe71974adbfec6fadead7c5699e72a83`, so, no it is not listed in the ext-player.js file.

I tried to manually add the line `addPath('/var/lib/flatpak/app'); // Fedora flatpak` but that didn't seem to help.
I added `addPath('/var/lib/flatpak/app/org.videolan.VLC/x86_64/stable/e737adfbdb87e287835209fb7defc1ecfe71974adbfec6fadead7c5699e72a83'); // Fedora Flatpak VLC` which seemed to get VLC to add to the list, but when I try to run it, the video does not load and I'm brought back to the movies page.

**Comment by kiriles90** [comment]
Hmm something weird is going on. If it managed to detect VLC with the second path it should have done so with the first one as well since it scans all subdirectories too. Maybe @ivan1986 knows more?

**Comment by BaktashGorgani** [comment]
I did not get any errors but I did get two informational messages that you may care to see:

![image](https://user-images.githubusercontent.com/17418270/188507153-08af2034-b4c0-4c39-8205-c06f322f3d43.png)

It's possible it is an issue with VLC. I am going to try on Ubuntu and see if it is the same issue because Ubuntu uses a snap package version of VLC instead.

**Comment by BaktashGorgani** [comment]
Works perfectly fine on Ubuntu using v.0.4.9 installed via .deb file and VLC snap package

**Comment by kiriles90** [comment]
Hmm, then my best guess is that something weird with access and flatpacks is going on. Also explains the force close and the console log above. Its just Popcorn Time that cant get VLC's status, then assumes its closed and stops the stream like its supposed to. You can verify this by changing
https://github.com/popcorn-official/popcorn-desktop/blob/f268afc151dd0275a2a2f6834cb6fe1a84155fef/src/app/lib/device/ext-player.js#L197
to `if (streamModel.attributes.device.id === 'Bomi' || streamModel.attributes.device.id === 'VLC') {` so it also ignores VLC's status along with Bomi's or.. just quote out https://github.com/popcorn-official/popcorn-desktop/blob/f268afc151dd0275a2a2f6834cb6fe1a84155fef/src/app/lib/device/ext-player.js#L201-L203 and it will ignore it for all external players.

**Comment by BaktashGorgani** [comment]
So when I do that it doesn't close the movie, but the movie never opens either. So I'm just looking at a screen of the movie loading lol.

I did figure something out though that will probably help you. The way that VLC needs to be started via flatpak is different then normal. From the .desktop file I can see this is the command that is run:

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/vlc org.videolan.VLC`

So it is actually run via the flatpak application. It can take any of the regular additional arguments at the end of the command as well.

**Comment by kiriles90** [comment]
Ok so from looking a bit more into it, and similar issues in github and in general, its the flatpacks. They are Sandboxed so they cant really talk with each other or with anything else other than the use of some portals for specific applications. There seems to be a number of workarounds, not sure which work adequately if any but the bottom line I'm getting from almost everyone is that flatpacks are ment to be like this, sandboxed and all..

**Comment by BaktashGorgani** [comment]
I was able to get it to work by adding a line to the ext-player.js file.

I added this at line 195:
`            cmd = '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/vlc org.videolan.VLC ' + cmdSwitch + cmdSub + cmdFs + cmdFilename + cmdUrl;`

Obviously not a perfect solution but it did get the stream to be pushed to VLC

**Comment by BaktashGorgani** [comment]
How does popcorn time determine the OS? If you determine it is fedora you can have it change the cmdPath variable to '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/vlc org.videolan.VLC '

**Comment by kiriles90** [comment]
Hmm, so now we just need a way to distinguish when a flatpak version of VLC is the one detected and use it to conditional add those above in the command (I guess its location could be the indicator?). Not sure if it matters if Fedora or not. But.. if I'm missing something there is also the issue of VLC not even getting detected unless you pinpoint the install directory exactly, which from the looks of it includes a hash that wont be the same for anyone else.

**Comment by BaktashGorgani** [comment]
So I have a fix that i think should work for everyone. I submitted this pull request #2635 

You were right about the hashes but luckily there were was also symbolic links created already (by VLC or flatpak) that linked the folders together in a much better way
