### ISSUE TITLE
we need picture in picture support 

### ISSUE THREAD

**Issue by ofry1** [popcorntime/popcorntime#2639]

**Comment by danielbayley** [comment]
@kiriles90 Is this planned?

**Comment by kiriles90** [comment]
Not really, I'm not even sure if its possible and many things will have to be figured out also that go with it not just the player ui part. Also tbh.. who would use this? Its not live tv where you have to watch something at the same time. Its on demand video, just decide what you want to watch and watch it :smile:

**Comment by ofry1** [comment]
i use pic in pic to watch stuff while doing something else i dont have 2
displays


‫בתאריך יום ג׳, 18 באוק׳ 2022 ב-20:33 מאת ‪kiriles90‬‏ <‪
***@***.***‬‏>:‬

**Comment by kiriles90** [comment]
@ofry1 I didnt mean two displays I ment two different videos at the same time for the first paragraph, and one video and the desktop for the second.
