### ISSUE TITLE
Performance And Bugs

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#264]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
22/10/2016
#### Expected Behaviour

To run smooth and without bugs
#### Actual Behaviour

It freezes sometimes and loads pages very slowy and movies stutter when i skip them and there's bugs where movies pictures won't display on Loading Screen or don't show at all
#### Steps to reproduce the behaviour

Fix all the above mentioned problems

**Comment by ChrisAlderson** [comment]
Create seperate issues for this.

**Comment by GKid94** [comment]
How do i do that?

**Comment by ChrisAlderson** [comment]
Separate the bugs, create a different issue for each bug.
