### ISSUE TITLE
Sort by Popularity isn't functioning properly

### ISSUE THREAD

**Issue by V8-AMG** [popcorntime/popcorntime#2640]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.9

Download date: 23.09.2022

Download url: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-win64-Setup.exe

#### Expected Behaviour

Before (months/years) when you sorted by popularity you were showed movies from different years based on popularity.

#### Actual Behaviour

Now it mostly (99%) shows movies from the year 2022-2021.

#### Steps to reproduce the behaviour

1. Open Popcorn Time
2. Sort by Popularity

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![Popularity](https://user-images.githubusercontent.com/114194720/191866132-9d3e8a38-37f2-477b-b67a-aaacea9fbceb.jpg)

**Comment by kiriles90** [comment]
Its functioning fine, these are the most downloaded movies.
Also this is an API issue to begin with, not an issue with the app so closing this.
