### ISSUE TITLE
Popcorn time in the browser (on an VPS or similar)

### ISSUE THREAD

**Issue by jkaberg** [popcorntime/popcorntime#2641]
I'd like to run Popcorn time as an server/VPS accessible remotely instead of locally on my desktop, this could pave way for easy access to untechnical famil., Where I/someone would be able to cast to local TV or play in the browser.

Ideally this would be set up as an docker container where one could deploy the container along with Caddy/Traefik for easy TLS certificates etc.

If this is already possible let me know, eg by running an local (dev) web server or similar.

**Comment by kiriles90** [comment]
Hmm I really cant see where this is going.. What would change for nontechnical users if running in a browser or not? The double click to start the app? As for casting.. it already works?  

> If this is already possible let me know, eg by running an local (dev) web server or similar.

Its possible, set up a VM..

**Comment by jkaberg** [comment]
@kiriles90 it lowers the bar, consider these two;

- Scenario 1 (current PT) involves finding Popcorn time and installing it, preferably with an VPN. While for an technical person this is not hard, but consider telling an none techie born in the 60's or 70's (it'd be a nightmare) :-)
- Scenario 2 involves an (technical) person setting up an VPS/VM with "popcorn time server" where they later can point none technical user to url x,y, obviously for the non technical user its a big upside

With scenario 2 you also don't necessarily need to setup VPN (or in some cases an LAN wide VPN at router level depending on network topology). This obviously depends on the VPS provider and their terms.

Ah right so there's an API, but no frontend accessible through an web service? The API is fine I suppose, however without an user friendly frontend consuming it.

There is no way to expose the frontend at an HTTP endpoint which I can point my browser towards? Like a dev sever or similar..

**Comment by kiriles90** [comment]
@jkaberg so basically turn Popcorn Time into a website? There are already similar projects, none of which work that great considering browser limitations and the unknown of what browser and OS a user might use. As for a VM you can already do that.  

About the API.. there is a friendly frontend.. its the app :) No dev server website frontend exists either. What would be the use of that? Debugging and development is being done either app or API side.  

Anyway... imho opinion installing the app isn't an issue for non-technical people. Worst case they can get someone to do it for them once. Its actually using the app that its the issue, and the fact that it simplifies things too much, to the point where people with no knowledge of what torrents are, what seeds/peers are, where to find more, what a VPN or an ISP block is, or even how to check if something is down or its just them having the issue. From my experience these are the issues these users face, none of which will change with what you are suggesting.
