### ISSUE TITLE
Hide/Fade button

### ISSUE THREAD

**Issue by isaamos** [popcorntime/popcorntime#2642]
Hide/Fade button would make the ui more user friendly. Some shows i finished or some shows i would **definitely** won't watch are always show up on top.

It can be like Windows's hidden file mechanic. I thought about it and it made sense to me, i'm open to better ideas

**Comment by dutchy1001** [comment]
there is an option in the settings, in the first paragraph, called "watched Items"
You got the options to "show" "fade" and "hide"
Not sure how this will work with series but watched movies are not in the list anymore when set to "hide".

**Comment by isaamos** [comment]
The shows/series i finished still show up as solid. 
And i'm trying to say that i won't watch a spesific show like got or something ever and it still shows up in the tab.

Edit: Maybe something like, right click hide/unhide/fade button would help

**Comment by kiriles90** [comment]
@isaamos like @dutchy1001 said..

![Untitled](https://user-images.githubusercontent.com/38388670/192549068-7fdbef11-b4a6-421e-b2d4-d1cdcdc44c67.png)

You can only do this with movies though, you cant mark whole series as watched, only their individual episodes.
