### ISSUE TITLE
Subtitle timing offset

### ISSUE THREAD

**Issue by 678GUY** [popcorntime/popcorntime#2643]
A basic subtittle timing offset to be able to sync it right

most subtitles arent synced right by only a few seconds but theres no way to offset it within the client, it would make the opensub integration better, since i wont need to manually download and offset the subtitles

**Comment by dutchy1001** [comment]
goto settings and click the little keyboard on the left top corner, there you will find the key's to adjust the subtitle timings (the H and G keys on your keyboard).

**Comment by 678GUY** [comment]
oh thanks, though it might be worth it to put some buttons in the player like the increase and decrease sub buttons
and thank you for your work!

**Comment by dutchy1001** [comment]
None of the players (like VLC or SMPlayer and many others) have them on show, all players have those in the settings with hotkeys like PCT has them as H and G.

**Comment by 678GUY** [comment]
i guess im just used to the other popcorn time client which has it directly in it.
