### ISSUE TITLE
nwjs quit unexpectedly on Mac

### ISSUE THREAD

**Issue by rrz** [popcorntime/popcorntime#2645]
Operating System Version:
mac os monterey 12.6 on macbook air m1

Popcorn Time Version:
0.4.9

Sometimes when I start app, or in the middle of watching movie I get an **error nwjs quit unexpectedly** 
full trace is attached in the file
[nwjs.txt](https://github.com/popcorn-official/popcorn-desktop/files/9727263/nwjs.txt)

**Comment by kiriles90** [comment]
Known issue. Open issue about updating NW.js at #2062

**Comment by fulcus** [comment]
Also happens to me quite often. Both on Monterey and now on Ventura too. Also on PT 0.4.9.

[nwjs_quit_unexpectedly.txt](https://github.com/popcorn-official/popcorn-desktop/files/9928269/nwjs_quit_unexpectedly.txt)
