### ISSUE TITLE
Possible memory leak when trying to play a clip using VLC

### ISSUE THREAD

**Issue by Umeaboy** [popcorntime/popcorntime#2646]
Operating System Version: Mageia 8 64 bit with 5.15.65-desktop-1.mga8 as kernel.

Popcorn Time Version:
0.4.9

Download date:
During the night.

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-linux64.zip

#### Expected Behaviour
Not getting a possible memory leak during the download process.
...

#### Actual Behaviour
It does download, but the exe process uses 150% of my CPU and almost 3 GB of memory is used when the program downloads.
...

#### Steps to reproduce the behaviour

1. Open Popcorn-Time from terminal.
2. Go to Series.
3. Search for any episode of The Walking Dead.
4. Click the button to play it with VLC and wait for it to start downloading.
5. In the terminal you'll see this output: (node:19801) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
This is repeated several times.

**Comment by kiriles90** [comment]
Memory usage issues like it was proven many times are due to WebTorrent. Nothing we can do about it here. Unless proven otherwise.. closing this for now.

**Comment by Umeaboy** [comment]
I still see this. Any chance to get it fixed?

**Comment by dutchy1001** [comment]
Have you updated since the first post you made?

**Comment by Umeaboy** [comment]
Yes, I did. I have set it to automatically update once a new release is out.

**Comment by dutchy1001** [comment]
The automatic update is for the main releases only, not the dev builds in between. Update from [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5496485657) and see if the issue then still exists
