### ISSUE TITLE
Freezing Problem

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#265]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
22/10/2016
#### Expected Behaviour

To open a page that i clicked faster
#### Actual Behaviour

The program freezes and takes a long time to open pages
#### Steps to reproduce the behaviour

Fix the above mentioned problem

**Comment by team-pct** [comment]
Please past relevant logs

**Comment by GKid94** [comment]
What do you mean?

**Comment by GKid94** [comment]
I said whats the problem in "Actual Behaviour", the program really needs some performance and bugs fixing
