### ISSUE TITLE
Antivirus detects Scan.Generic.PortScan.UDP repeatedly after opening Popcorn Time

### ISSUE THREAD

**Issue by Abernecio** [popcorntime/popcorntime#2650]
Hi everyone!

Today I decided to use Popcorn Time again. Since the website is down, I ended up download the least release on this repo (Windows x64 no installer)

But since I've opened Popcorn Time, Kasperky is repeatedly notifying me of a possible network attack (Scan.Generic.PortScan.UDP), which supposedly means that some software is scanning and enumerating possibly open UDP ports.

Is this related to Popcorn Time?

**Comment by kiriles90** [comment]
Its a torrent client so it opens udp ports. Check webtorrent's repo for more.
