### ISSUE TITLE
More Languages Movies Support

### ISSUE THREAD

**Issue by aka-0x4C3DD** [popcorntime/popcorntime#2652]
**Is your feature request related to a problem? Please describe.**
I cannot find movies in languages like Bengali, Tamil, Telugu, Malayalam etc. I want to watch those too, but don't know where to get those from.

**Describe the idea you'd like**
I want such that IMDB listed movies when ever I search those, in popcorn time app, I get to watch / download those.

**Describe alternatives you've considered**
Maybe after searching, redirect me to some external site where I can watch / download the same.

**Additional context**
There are old movies from 2005s, 2010s era which aren't available anywhere in Torrents or for Direct Downloads or Watch Online, except Prime Video / Netflix, which I don't have the money to pay for.

**Comment by dutchy1001** [comment]
Unfortunately Popcorn-Time can only display movies that are found through the API's it uses. These API's  get them from torrents that are available, if these API's don't find movies with/in the language you want then it's not possible to get them to show. 

To, after a search, to be redirected to an external site is afaik not possible.
