### ISSUE TITLE
List of genres meaning amount of genres are not the same if used localised app

### ISSUE THREAD

**Issue by slsimic** [popcorntime/popcorntime#2655]
Operating System Version:
Linux debian based

Popcorn Time Version:
0.4.9 linux amd64

Download date:
12 nov 2022

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-linux64.zip

#### Expected Behaviour
list of genres should contain all genres available regardless of localisation of the app, both movies and series
non-translated genres should appear on english but none should be missing

#### Actual Behaviour
shows some instead of all genres
strangely enough, it's not just english/localised version problem. Different localisation have different genres list.
For example, in Serbian, series, I get only two genres shown, when using German, there is 12, on Croatian 26, but on English there is only 20 

#### Steps to reproduce the behaviour
Click on genres drop-down, movies and series, count the items on the lists.
Go to settings and change the application language. Wait for restart. 
Click again on genres drop-down, movies and series, count the items on the lists. Number of items are not the same.
Try few languages. I tried Serbian, German, Bulgarian, Croatian

#### Screenshot(s) of issue or error(s) logs of developer console

![MovBUL](https://user-images.githubusercontent.com/12166655/201493300-375c15ba-b137-475f-be7f-c1ede520a365.png)![MovCRO](https://user-images.githubusercontent.com/12166655/201493303-147e4a42-e7fd-49d3-aab7-c400b5a4ff69.png)![MovENG](https://user-images.githubusercontent.com/12166655/201493305-0f5ebd69-a451-4e3f-a56c-5f22f71800d8.png)![MovGER](https://user-images.githubusercontent.com/12166655/201493307-044529d6-cd58-4a6e-8977-d05b2e97f840.png)![MovSER](https://user-images.githubusercontent.com/12166655/201493308-8cc2f0d7-a95d-481f-a153-224d258a4142.png)
![SerBUL](https://user-images.githubusercontent.com/12166655/201493309-4a7dc9fe-a599-4896-ae06-7de2af8765a7.png)![SerCRO](https://user-images.githubusercontent.com/12166655/201493310-8931b2ce-1d4f-4a83-b823-4b28e9a78774.png)![SerENG](https://user-images.githubusercontent.com/12166655/201493311-38022e12-261b-476f-8690-c76692fb8af2.png)![SerGER](https://user-images.githubusercontent.com/12166655/201493312-34b3dbc9-6e47-4161-916e-377f1fa9802d.png)![SerSER](https://user-images.githubusercontent.com/12166655/201493313-e59e68d4-ead9-4d82-9f05-8b685b79bc38.png)

**Comment by dutchy1001** [comment]
As far I know it can only list what the API can fetch, if there isn't a translation for it then it can not be shown.

**Comment by kiriles90** [comment]
Not sure if this is even a bug or its how things are supposed to work or you have some option like "only show content in default language" selected. Nevetheless.. its an API not an app issue so closing this. Open an issue in the RU API repo.
