### ISSUE TITLE
Handle subtitles after launching movie

### ISSUE THREAD

**Issue by RolandVrignon** [popcorntime/popcorntime#2656]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I cast a movie from popcorn time and the subtitle track isn't precise. I'm frustrated because once I lauch the movie I cannot change the delay anymore.

I tried ton change .srt and  .vtt file with the correct delay but when i lauch back the movie it don't use the last modified file but a new one that has the same delay => I cannot watch the movie on my TV if subtitle file isn't perfect.

**Describe the idea you'd like**

I would like to be able to manage subtitles file directly from my desktop when casting a movie.

**Describe alternatives you've considered**

I watched movies on VLC but i can't cast movie + subtitles on my chromecast..

**Additional context**

Please make possible to manage subtitles from this page !

![Screenshot from 2022-11-13 01-16-35](https://user-images.githubusercontent.com/22148876/201499723-b9cd149e-5638-41a5-be93-15128f3ba0f7.png)

**Comment by kiriles90** [comment]
Not possible. External players (e.g VLC that you mentioned) dont have the ability to load subtitles using the command line once the video is started so whatever Popcorn Time could try would be pointless.
