### ISSUE TITLE
Stuttering Problems

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#266]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
22/10/2016
#### Expected Behaviour

To skip the scene normally
#### Actual Behaviour

The movie plays but it stutters
#### Steps to reproduce the behaviour

Fix the above mentioned problem so the move doesn't stutter anymore

**Comment by team-pct** [comment]
Duplicate

**Comment by GKid94** [comment]
What do you mean by duplicate?
