### ISSUE TITLE
Will there be a build for Apple silicon chip?

### ISSUE THREAD

**Issue by samxl001** [popcorntime/popcorntime#2664]
Hi, I am using the latest version of Popcorntime on my Macbook air M1 which is run through rosetta. It runs fine but sometimes it crashes repeatedly. I don't know if the crash is due to njws or rosetta. Will there be a build for Apple silicon chips (M1, M2, etc.)?

**Comment by kiriles90** [comment]
Its due to NW.js. For an apple silicon build it needs to be updated to a newer version but there are some not so simple issues to overcome first. Follow #2062 for more on this.

Also, you might want to check https://github.com/popcorn-official/popcorn-desktop/wiki/Fix-crashing-on-macOS-%5E12 it helps with the crashes though be warned that like the last line says, one of the side-effects of this is that some of the audio codecs will not work with the native player (one of the issues I mentioned above). You can always use a supported external player for those though so.. its up to you what you prefer.

Closing this but comment below if you need help with this or some other issue.

**Comment by bouachalazhar** [comment]
When I build with `yarn build` :
```
yarn build
yarn run v1.22.19
$ gulp build
(node:4309) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:4309) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:4309) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:4309) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:4309) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:4309) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Error: No platform to build!
    at new NwBuilder (/usr/local/Homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/nw-builder/lib/index.cjs:94:11)
    at Object.<anonymous> (/usr/local/Homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/gulpfile.js:171:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requireOrImport (/usr/local/Homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/usr/local/Homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
How install in M2 ?

**Comment by ChristianF88** [comment]
Hi there, same problem here. I have a Macbook Air with an M2 chip in it. When I try building with yarn:

1) 
```sh
git clone https://github.com/popcorn-official/popcorn-desktop.git 
```
2)
```sh
cd popcorn-desktop
yarn install
```
3)
```sh
➜  popcorn-desktop git:(development) sh make_popcorn.sh
You appear to be inside of a Popcorn Time repository already, not cloning
Switched to /Users/hildi/repos/popcorn-desktop
yarn run v1.22.19
$ gulp build
(node:16831) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16831) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:16831) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:16831) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:16831) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:16831) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Error: No platform to build!
    at new NwBuilder (/Users/hildi/repos/popcorn-desktop/node_modules/nw-builder/lib/index.cjs:94:11)
    at Object.<anonymous> (/Users/hildi/repos/popcorn-desktop/gulpfile.js:171:12)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at requireOrImport (/Users/hildi/repos/popcorn-desktop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/hildi/repos/popcorn-desktop/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Popcorn Time encountered an error and couldn't be built
```

I also tried the install via homebrew: 

```sh
➜  popcorn-desktop git:(development) brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
#export HOMEBREW_POPCORN_TIME_BUILD=false
brew install --cask popcorn-time #--no-quarantine
==> Downloading https://formulae.brew.sh/api/cask.json

==> Downloading https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.64.0/0.64.0-osx-x64.zip
Already downloaded: /Users/hildi/Library/Caches/Homebrew/downloads/b4d98f1f431841ecd31529ae752965bb1953c21e3683590c3fc316ce84937f8a--0.64.0-osx-x64.zip
Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
➜  popcorn-desktop git:(development)

```

**Comment by bouachalazhar** [comment]
> Hi there, same problem here. I have a Macbook Air with an M2 chip in it. When I try building with yarn:
> 
> 
> ```shell
> git clone https://github.com/popcorn-official/popcorn-desktop.git 
> ```
> 
> 
> ```shell
> cd popcorn-desktop
> yarn install
> ```
> 
> 
> ```shell
> ➜  popcorn-desktop git:(development) sh make_popcorn.sh
> You appear to be inside of a Popcorn Time repository already, not cloning
> Switched to /Users/hildi/repos/popcorn-desktop
> yarn run v1.22.19
> $ gulp build
> (node:16831) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:16831) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:16831) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> (node:16831) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (node:16831) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:16831) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> Error: No platform to build!
>     at new NwBuilder (/Users/hildi/repos/popcorn-desktop/node_modules/nw-builder/lib/index.cjs:94:11)
>     at Object.<anonymous> (/Users/hildi/repos/popcorn-desktop/gulpfile.js:171:12)
>     at Module._compile (node:internal/modules/cjs/loader:1275:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
>     at Module.load (node:internal/modules/cjs/loader:1133:32)
>     at Module._load (node:internal/modules/cjs/loader:972:12)
>     at Module.require (node:internal/modules/cjs/loader:1157:19)
>     at require (node:internal/modules/helpers:119:18)
>     at requireOrImport (/Users/hildi/repos/popcorn-desktop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
>     at execute (/Users/hildi/repos/popcorn-desktop/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Popcorn Time encountered an error and couldn't be built
> ```
> 
> I also tried the install via homebrew:
> 
> ```shell
> ➜  popcorn-desktop git:(development) brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
> #export HOMEBREW_POPCORN_TIME_BUILD=false
> brew install --cask popcorn-time #--no-quarantine
> ==> Downloading https://formulae.brew.sh/api/cask.json
> 
> ==> Downloading https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.64.0/0.64.0-osx-x64.zip
> Already downloaded: /Users/hildi/Library/Caches/Homebrew/downloads/b4d98f1f431841ecd31529ae752965bb1953c21e3683590c3fc316ce84937f8a--0.64.0-osx-x64.zip
> Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
> ➜  popcorn-desktop git:(development)
> ```

If you resolve it send me. I can help you if you need.
