### ISSUE TITLE
popcorn time working on the background 

### ISSUE THREAD

**Issue by gogalral** [popcorntime/popcorntime#2667]
Operating System Version:
OS X 13.0.1 

Popcorn Time Version:
0.4.9

Download date:
I have popcorn-time for about 5 years but I install the latest version 1/12/2022 

Download url:
GitHub

#### Expected Behaviour
when closing the application to terminate all activities and not to drain battery
...

#### Actual Behaviour
keeps working in the back ground and I have to go to activity monitor in order to find and terminate any unnecessary activity / task from the background.
...

#### Steps to reproduce the behaviour
happens every time I reopen popcorn time 
1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
You have something bugged either on your OS or app installation or you're using something else or else more people on macOS would be experiencing the same behavior. Start by clean installing the app then if the issue continues you'll have to hunt it down in the OS settings.
