### ISSUE TITLE
Subtitles account login doesn't work except Windows 11

### ISSUE THREAD

**Issue by Vicro2821** [popcorntime/popcorntime#2668]
Operating System Version:
Ubuntu 22.04/22.10 - Windows 10

Popcorn Time Version:
0.4.9

![Screenshot (2)](https://user-images.githubusercontent.com/40027582/205505984-c56559f6-875e-40cd-868a-c9f7a4b7016d.png)

Hello. I found something weird cause i can't login on opensub account even tho the username and password is correct. It happens on Ubuntu and Windows 10 but i never got issue on Windows 11

**Comment by dutchy1001** [comment]
This could be a glitch on opensubtitles.org side. I just logged in with PCT and on the website itself with same credentials.
Try the website itself to make sure it works.

**Comment by Vicro2821** [comment]
i actually went throught website right now and im able to log in successfully. i even try to create a fresh new account with new username and password and again it makes the same issue. maybe it is a glitch through opensubtitle.org but i've notice on many machines with Windows 10 having the same issue on that.

**Comment by dutchy1001** [comment]
I use w10 and in a rare occasions it takes 10/20 seconds before the subtitle icon changes to the language I have mine set on. Never has it happened that it didn't log into opensubs. 
Do you use a VPN? If so, change the location to see if that might help (mine is always set to "The Netherlands").

**Comment by dutchy1001** [comment]
I presume after 2 days no more comments this has fixed itself.

Closing this.
