### ISSUE TITLE
How do I use this api in popcorntime?

### ISSUE THREAD

**Issue by PsycloneTM** [popcorntime/popcorntime#2669]
Wondering if i can use this api in popcorn time if anyone can help that'd be great,
https://github.com/Thanatoslayer6/Himovies-Unofficial-API

**Comment by kiriles90** [comment]
You'll need to setup the API somewhere per the author's instructions then try the url in Popcorn Time. In all likelyhood it wont be 100% compatible though (dont quote me on this, I havent checked so there's still a chance you get lucky) in which case you'll also need an API wrapper for Popcorn Time to use. If you get one working PR it here if you want to get it merged. @ivan1986 might know more. Closing the issue but do continue the conversation below freely.
