### ISSUE TITLE
Movies Picture Bug

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#267]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
22/10/2016
#### Expected Behaviour

Show the pictures normally
#### Actual Behaviour

The movie picture doesn't show on the Downloading page and there is just a black background
#### Steps to reproduce the behaviour

Fix the above mentioned problem

**Comment by ChrisAlderson** [comment]
Cannot reproduce.

**Comment by GKid94** [comment]
Why not?
