### ISSUE TITLE
MPC-BE64 player option in Watch Now menu has a broken icon

### ISSUE THREAD

**Issue by shtefko** [popcorntime/popcorntime#2672]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.9

Download date: Sometime in September 2022

Download url: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-win64-Setup.exe

#### Expected Behaviour

I would expect to see a monochrome version of the MPC-BE64 icon

#### Actual Behaviour

I see a broken icon. I have this reproed on 3 different (Windows) systems.

#### Steps to reproduce the behaviour

1. Install an MPC-BE player - https://github.com/Aleksoid1978/MPC-BE/releases/download/1.6.5.3/MPC-BE.1.6.5.3.x64-installer.zip
2. Open PopcornTime app and open Watch Now menu
3. Observe that it has a broken icon

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/1898211/206854648-1b525c43-b75c-492d-9767-0fb4dd6fdb20.png)

Observe MPC-BE's icon:
![image](https://user-images.githubusercontent.com/1898211/206854710-0417e689-b178-47b6-99a9-dec6dab11887.png)

**Comment by dutchy1001** [comment]
I presume this is just a missing icon in a library, not a big issue as long the program works as intended.
