### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#2673]
Operating System Version:
macOS 13.0.1

Popcorn Time Version:
v0.4.9

Download date:
Months ago, probably on the release date or 1-2 days later.

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-osx64.zip

#### Expected Behaviour
The app initiates normally.

#### Actual Behaviour
The app crashes. Here's the macOS log: https://pastebin.com/F5Mi0vLd

#### Steps to reproduce the behaviour
1. Open the app
2. Crash

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
https://pastebin.com/F5Mi0vLd

**Comment by kiriles90** [comment]
Yes, the issue has been opened many times. Its related to NW.js and will be solved when we can solve the issues of upgrading it to a newer version. For more open issue at https://github.com/popcorn-official/popcorn-desktop/issues/2062
