### ISSUE TITLE
Add how to get involved to the wiki

### ISSUE THREAD

**Issue by codecowboy** [popcorntime/popcorntime#2685]
I'd like to contribute and would be grateful if someone could contact me. Is there a discord server or slack channel / IRC?

**Comment by kiriles90** [comment]
Hi, do you mean you want to contribute to the wiki or with code? (or both?) For the former it can be unlocked for you for as long as you need, its locked to stop random hit and runs that kept defacing it not to stop anyone wanting to add good info. For the latter.. just make a PR so it can be reviewed & merged or make a post about it before hand if you'd like some input before starting to code it. But, if these don't cover it let me know so I can see what can be done.

**Comment by codecowboy** [comment]
I mean code but am rusty as I haven't coded for a while. I'm recovering from illness and using the app alot. It crashes quite alot on my m1pro macbook so I wondered if I could look into fixing that. It's actually usable but the crashes get annoying. The wiki workaround for monterey states that it's not for M1/M2. I would need help setting up the latest build. Github actions are new to me so I would need a bit of help via some kind of chat channel.

**Comment by kiriles90** [comment]
@codecowboy are you also on reddit? :eyes:

**Comment by codecowboy** [comment]
Yep sorry thats me too.

**Comment by kiriles90** [comment]
@codecowboy :+1: check your chat there
