### ISSUE TITLE
Background process nwjs stays open after closing Popcorn Time

### ISSUE THREAD

**Issue by nikolic-milan** [popcorntime/popcorntime#2686]
Operating System Version:
Currently OS Ventura 13.01 also on Windows 10

Popcorn Time Version:
Version 0.4.7

Download date:
2 March 2022

Download url:
From github, the latest that was at the above date. I can't remember exactly.

#### Expected Behaviour
Everything to close.

#### Actual Behaviour
Service nwjs remains open, and uses a lot of resources, nearly 100% CPU. 

#### Steps to reproduce the behaviour
I can't exactly tell you the steps, sometimes it shuts down properly, sometimes not.

**Comment by dutchy1001** [comment]
The NWjs has more issue's for some systems (mostly MAC's), see topic #2062 
NWjs is not written by PCT we need to wait for them to update/fix it.

**Comment by kiriles90** [comment]
..and also update to the most recent version before opening new issues. How do you know this wasn't fixed in a later version? (not saying its fixed, or even that is it a bug in Popcorn Time's side, just that if you don't update you cant know)
