### ISSUE TITLE
Subtitles disabled

### ISSUE THREAD

**Issue by mariwer** [popcorntime/popcorntime#269]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9.0

Download date:
September 25, 2016
#### Expected Behaviour

I expected subtitles to appear. They are disabled in all the series and movies (including the ones I've already watched with subs before) even if I select English as the default language. 
...
#### Actual Behaviour

It says the subtitles are deactivated, and only the option "Custom..." appears
...
#### Steps to reproduce the behaviour
1. Select a series/movie
2. Go to the subtitles icon 
   ![image](https://cloud.githubusercontent.com/assets/23016034/19628288/baa8be20-995a-11e6-8713-2a6cfed022f7.png)
   ![image](https://cloud.githubusercontent.com/assets/23016034/19628274/78fa9368-995a-11e6-849d-412c2b06d2e4.png)

**Comment by kim0** [comment]
Try opening settings, double check your subtitles language is chosen, save and exit .. Then try launching again! For me, subtitles only worked on the second try like that

**Comment by mariwer** [comment]
Hi! I already did that lots of times...still not working. 
The app was working fine but suddenly they disappeared. At first I thought it was because the episodes were new and the subs weren't there yet, but I went back to episodes I'd watched with subs and they're still deactivated. Really weird.

**Comment by mariwer** [comment]
I fixed it by downloading the app again.
