### ISSUE TITLE
TV Intro Detection/Skip

### ISSUE THREAD

**Issue by PsycloneTM** [popcorntime/popcorntime#2696]
**Is your feature request related to a problem? Please describe.**
Not really a problem more of an inconvenience, but the fact that I have to sit through tv intros every episode.  

**Describe the idea you'd like**
A Toggle Setting that would either add button to skip the intro or the ability for you to auto skip intro always.

**Describe alternatives you've considered**
A few example of this are on Plex or Netflix.

**Additional context**
This are some links to work people have already done to making intro detection not sure if they can be used:
https://github.com/garrit-schroeder/tv-show-skipper
https://github.com/mueslimak3r/tv-intro-detection
https://github.com/ConfusedPolarBear/intro-skipper
![HwXo8sk](https://user-images.githubusercontent.com/27637025/215896979-67f67162-2fcd-4252-83b2-36551c190991.png)

**Comment by kiriles90** [comment]
Afaik these work with analyzing the content and guessing where the intro is and have the potential to cause more issues than good. As for going the netflix way, netflix hosts, uploads and checks their own content and know where the intro is. Popcorn Time doesn't, it uses torrents it automatically indexes from 3rd party providers that don't provide intro metadata.
