### ISSUE TITLE
proxy settings fail

### ISSUE THREAD

**Issue by mrbrklyn** [popcorntime/popcorntime#2700]
We have an ssh proxy to a remote ISP created as follows

/usr/bin/ssh -L 9000:127.0.0.1:8008 users@hostname.host.com 

It works with firefox but popcorn time is not accepting it

Proxy Server 127.0.0.0:9000

Is shows up for firefox but not popcorntime or any of its child processes (such as exe)

 sudo ss -taenp|grep 9000
LISTEN    0       0                127.0.0.1:9000             0.0.0.0:*     users:(("ssh",pid=2424,fd=5)) uid:1000 ino:16317286 sk:7000abbe                                           
ESTAB     0       0                127.0.0.1:58300          127.0.0.1:9000  users:(("firefox",pid=16877,fd=23)) uid:1000 ino:25763145 sk:5a008e3f                                     
ESTAB     0       0                127.0.0.1:38682          127.0.0.1:9000  users:(("firefox",pid=16877,fd=109)) timer:(keepalive,7min20sec,0) uid:1000 ino:25750875 sk:82306326      
ESTAB     0       0                127.0.0.1:9000           127.0.0.1:58300 users:(("ssh",pid=2424,fd=11)) uid:1000 ino:25765261 sk:7cfecef0                                          
ESTAB     0       0                127.0.0.1:9000           127.0.0.1:46526 users:(("ssh",pid=2424,fd=23)) uid:1000 ino:25522567 sk:d2bd2b9a 

flatbush:[ruben]:~$ sudo ss -taenp|grep exe
SYN-SENT  0       1                10.0.0.62:52474      72.65.109.104:19499 users:(("exe",pid=8975,fd=129)) timer:(on,740ms,1) uid:1000 ino:25771321 sk:7005bf5d                      
ESTAB     0       0                10.0.0.62:44492       104.21.31.24:443   users:(("exe",pid=8975,fd=422)) uid:1000 ino:25702894 sk:3184bd14                                         
SYN-SENT  0       1                10.0.0.62:54888       5.189.185.57:6882  users:(("exe",pid=8975,fd=275)) timer:(on,2.820ms,2) uid:1000 ino:25773268 sk:ec1bdf7c                    

checking pid 8975

 ps -auxw|grep 8975
ruben     8975 47.4  5.7 10475216 1873512 ?    Sl   15:17  35:10 /proc/self/exe --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias=/gen=/home/ruben/src/popcorn-desktop/cache/0.44.5-sdk/linux64/gen --no-zygote --field-trial-handle=3879535507527497822,14231748833541997080,131072 --lang=en-US --enable-crash-reporter=, --user-data-dir=/home/ruben/.config/Popcorn-Time --nwapp-path=. --nwjs --extension-process --disable-client-side-phishing-detection --enable-auto-reload --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --shared-files
ruben    14431  0.0  0.0   6568  2620 pts/17   S+   16:31   0:00 grep --colour=auto 8975

It still is attaching to 10.0.0.62 

Operating System Version:
Artix Linux (same on thumbleweed SuSE)
6.1.8-artix1-1 #1 SMP PREEMPT_DYNAMIC Sun, 29 Jan 2023 17:17:21 +0000 x86_64 GNU/Linux

Popcorn Time Version:

0.4.6 the good varient

Download date:

a few weeks ago

![pcproxy](https://user-images.githubusercontent.com/16446720/219900624-0ec4e3d9-3083-4977-88b0-4e50b3ac223a.jpg)

**Comment by kiriles90** [comment]
Hi, can you please check if you can replicate this with the latest build? (or at least the latest version, 0.4.9 at the moment)  
It might be there still but we cant debug this based on 3 major versions back.

**Comment by kiriles90** [comment]
@mrbrklyn Hi, can you please check if you can replicate this with the latest build? (or at least the latest version, 0.4.9 at the moment)  
It might be there still but we cant debug this based on 3 major versions back.
