### ISSUE TITLE
Update OpenSubtitles account feature to use new api

### ISSUE THREAD

**Issue by martin-bundgaard** [popcorntime/popcorntime#2702]
Update OpenSubtitles account feature to use their new api at OpenSubtitles.com
It's no longer possible to log into Open Subtitles in popcorn time to fetch subtitles automatically.

**Comment by dutchy1001** [comment]
I still get the subtitles automatically, it sometimes takes a few seconds longer.

**Comment by martin-bundgaard** [comment]
Ok... I have not been able to log in to Open Subtitles on desktop popcorn for months.

Have tried to create several new Open Subtitles accounts, both in their new and old website. None of them works in popcorn.

________________________________
Fra: dutchy1001 ***@***.***>
Sendt: lørdag den 4. marts 2023 18.56
Til: popcorn-official/popcorn-desktop ***@***.***>
Cc: martin-bundgaard ***@***.***>; Author ***@***.***>
Emne: Re: [popcorn-official/popcorn-desktop] Update OpenSubtitles account feature to use new api (Issue #2702)


I still get the subtitles automatically, it sometimes takes a few seconds longer.

**Comment by dutchy1001** [comment]
I think I found your issue, you said "_opensubtitles.com_", this is a different site then the subtitle site PCT uses, no wonder that you have issue's.
Try and create a site at "[opensubtitles.org/](https://www.opensubtitles.org/en/search/subs)" and fill those credentials in at the "settings" page of PCT.

Let us know how you get on then.

**Comment by martin-bundgaard** [comment]
I have tried with both websites.

Since .com is their new website i tried that one too. The .org api ends this year, and only the .com api will work in the future.
________________________________

**Comment by kiriles90** [comment]
Opensubtitles .com and .org are two different websites. They are supposedly owned by the same people but .org is the one used by the vast majority of people and the most updated one/one with most subtitles. Use the correct one, if when support for it ends, or if it ever becomes equal to or better than .org we see. For the moment its creators dont seem to take it seriously and the majority of people sees it and doesnt use it. As for .org it works fine in the app. If it doesnt for you you'll need to troubleshoot and find the reason. Closing this.
