### ISSUE TITLE
I do not have any boxes for translation, what is the solution and why in the main interface, and it has been updated to the latest version

### ISSUE THREAD

**Issue by meke910** [popcorntime/popcorntime#2704]
Operating System Version:

Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by meke910** [comment]
I do not have any boxes for translation, what is the solution and why in the main interface, and it has been updated to the latest version

**Comment by dutchy1001** [comment]
I'm sorry but I dont get you with "I do not have any boxes for translation". Do you mean in the code here on Github or in the actual program?
In the settings there is a setting to what language you can have Popcorn Time (PCT), other then that I don't know what you mean.
