### ISSUE TITLE
Popcorn Time TV app (arm) keeps crashing

### ISSUE THREAD

**Issue by nusbe-54** [popcorntime/popcorntime#2705]
App opens fine, but when I am in the middle of searching something, all of a sudden, the app will just close on itself! It happens every time and idk why, as my TV is well-maintained and I don't have a lot of apps installed, as well as I regularly make sure my background apps are closed properly or force stopped. It doesn't mention this issue anywhere in the FAQ or in the issues list: https://github.com/popcorn-official/popcorn-desktop/wiki/FAQ

Android TV: JVC LT-40CA790

got it from the official place as of now: [popcorn-time.ga/build](https://popcorn-time.ga/build)

**Comment by kiriles90** [comment]
You need to open this in the android repo though to be honest its a known issue on specific devices. The android and android tv apps are in need of a regular maintainer but none seems to want to take this up. You could try the mobile version and see if the experience is better. The UI isn't designed for a big screen but it should work all the same, android is android.
