### ISSUE TITLE
Turn off pc after download finishes

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2710]
When choosing a download instead of watching you will have the option to turn the pc off. 
This is (as example) an option in SABnzbd and hope this same kind of system can be implemented in PCT.

This way you can then have a few movies. series episodes ready for the next time you want to watch them.
Obvious this should then disable the "clear cache folder after closing app".

**Comment by kiriles90** [comment]
Option to exit the app when all downloads complete added with #2792. Shutting down the pc would bring bugs/issues with multiple OSes and javascript/node permissions and will also require launching external commands.
