### ISSUE TITLE
Mac M series support

### ISSUE THREAD

**Issue by shayar-ghafour** [popcorntime/popcorntime#2711]
Hello, i get this error while using Brew to install popcorn time,

Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.

i tried to use the release osx app but it keeps crashing.

thanks

**Comment by u2ix** [comment]
I'm as well facing this issue with a M1 MacBook and it might not be resolved.
`~ brew install --cask popcorn-time
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=-#    #
==> Downloading https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.64.0/0.64.0-osx-x64.zip
Already downloaded: b4d98f1f431841ecd31529ae752965bb1953c21e3683590c3fc316ce84937f8a--0.64.0-osx-x64.zip
Error: Cask popcorn-time depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.`

**Comment by mibrahimdev** [comment]
➕1

**Comment by Mayurifag** [comment]
Why is this issue closed?

**Comment by rsozdance** [comment]
It sounds like the popcorn app is not the issue, but rather an application
or library they are using. Unfortunately, they are not responsible for this
issue and cannot provide assistance.

**Comment by shayar-ghafour** [comment]
It sounds like the popcorn app is not the issue, but rather an application
or library they are using. Unfortunately, they are not responsible for this
issue and cannot provide assistance.
