### ISSUE TITLE
Self host popcorn time on the web?

### ISSUE THREAD

**Issue by LagBug** [popcorntime/popcorntime#2712]
**Is your feature request related to a problem? Please describe.**
No

**Describe the idea you'd like**
I was wondering first of all whether it'd be possible to self-host the current application on a VPS as is. If not, it'd be nice to be implemented.

**Comment by kiriles90** [comment]
Hmm you can run the app on a VPS yes but I'm not sure if the host will like it. I dont think I'm getting the point of this though. Is it to serve multiple users from a web app or something? Or just an alternative to using a VPN? Or..?

P.s closing this since not an issue with the app but we can continue the conversation below.

**Comment by LagBug** [comment]
So basically just serve the app on my domain, under some sort of password protected page, to give around for friends and family to have access to popcorn time through any device/location without needing to individually download the app or use a VPN.
Any idea on how I would go about doing this? Thanks!

**Comment by kiriles90** [comment]
Hmm you could set the "Port to stream on" to a set port so its not random every time and make it accessible outside the local network, then by using the stream url people could open that in their media players (and browser). But this leaves something out, how to select content and initiate the stream.. This could either be done by having remote desktop access in the VPS and doing it directly or some configuration of the remote control of Popcorn Time ([../src/app/httpapi.js](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/httpapi.js)). Afaik though no ready code exists to do exactly what you want so you'll have to look into that or edit one of the existing third party remotes to your needs.  

Ofc.. you could bypass the app all together and deal with (or fork and host yourself) the API directly ([github.com/popcorn-time-ru/popcorn-ru](https://github.com/popcorn-time-ru/popcorn-ru)). Again though you'll need to write your own website's code to work with the API (or whatever other API you select) but you can get an idea of how to do that by looking at the current API wrappers the app uses ([../src/app/butter-provider/](https://github.com/popcorn-official/popcorn-desktop/tree/development/src/app/butter-provider)) and whatever other documentation you can find for that API.

**Comment by LagBug** [comment]
Great, that look like a fun project to do & the API/wrapper quite a useful start. If/when I end up doing it I'll make it open source for everyone to use.  Thanks!
