### ISSUE TITLE
Episode not loading

### ISSUE THREAD

**Issue by thibaudvanwilde** [popcorntime/popcorntime#2713]
Operating System Version:

Windows 10 22H2

Popcorn Time Version:

Version 6.2.0.13

Download date:

Last week or so

Download url:

[techspot.com](https://www.techspot.com/downloads/6450-popcorn-time.html)

#### Expected Behaviour

Load S1E4 of the series Succession.
...

#### Actual Behaviour

"Video file can't be downloaded for now. Please try again later"
...

#### Steps to reproduce the behaviour

1. Open popcorn time
2. Try to watch Succession in 1080p 
3. Error comes up

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![afbeelding](https://user-images.githubusercontent.com/59932612/232133116-5648375e-1d66-40c1-bc83-32f3b48a6dc9.png)

**Comment by dutchy1001** [comment]
Sorry but this is a different popcorn version, nothing we can do about that. 
Download and install our version from [here](https://popcorn-time.ga/build/).

Closing this but feel free to ask any other question if needed.
