### ISSUE TITLE
Support for Music

### ISSUE THREAD

**Issue by praveenpenumaka** [popcorntime/popcorntime#2715]
**Is your feature request related to a problem? Please describe.**
It would be great if all media can be maintained in one place. Can we add support to music?

**Describe the idea you'd like**
Along with the movies, music is listed based on album/artist etc. A simple music player can be integrated to play the music as well. 

**Describe alternatives you've considered**
Have tried plex server for the same, but would love see all my media in one place. 

**Additional context**

**Comment by kiriles90** [comment]
Somewhat out of the scope of this app but even if it wasnt this is mainly a lack of API and content issue. Not much good content in torrent form nor there is a convinient metadata API to help index it (like imdb and tmdb but for music). 

Sorry but closing this for now. If someone wants to work on it and solve the issues to make a working PR, then that can be reviewed and we see if it can be merged or not.. depending on how it works.
