### ISSUE TITLE
AirPlay2 password

### ISSUE THREAD

**Issue by pe4enko** [popcorntime/popcorntime#2718]
Hi.
LG WebOs allow connect to AirPlay  only with password.
Is it possible to set password in Popcorn-Time to connect to TV by AirPlay2?
Thanks!!!

**Comment by kiriles90** [comment]
Hi, Airplay support is mostly broken since apple changed the authentication/handshake methods. See https://github.com/popcorn-official/popcorn-desktop/issues/1433 for more. For LG TVs you can use DLNA though.
