### ISSUE TITLE
No subtitle choice for Series

### ISSUE THREAD

**Issue by lainiwa** [popcorntime/popcorntime#2719]
Operating System Version:
Ubuntu 22.04

Popcorn Time Version:

Download date:
2023-05-21

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-amd64.deb

#### Expected Behaviour
Subtitles available for Series just like they are available for Movies

#### Actual Behaviour
No button for subtitle choice in the right-bottom corner of selected Series

#### Steps to reproduce the behaviour

1. Download and install Popcorn Time
2. Go to settings and switch API's to https://popcorn-time.ga/ and restart
3. (Optionally; doesn't seem to affect the issue) In settings: login in to opensubtitles.org
4. Go to Series and pick any
5. See that there is no choice for subtitles in the right-bottom corner

(no errors in the developer console)

**Comment by dutchy1001** [comment]
There are still subtitles for the series when you use an external player like SMPlayer or VLC player, not sure they are available on your OS.
You can choose an external player (when installed) from the little arrow on the "Watch Now" button.
As this has already been mentioned [here](https://github.com/popcorn-official/popcorn-desktop/issues/1990) and has the tag of "feature" I will close this issue
Feel free to add your comments there
