### ISSUE TITLE
Compile as UWP for Xbox?

### ISSUE THREAD

**Issue by kanadgodse** [popcorntime/popcorntime#2720]
**Is your feature request related to a problem? Please describe.**
Is it possible to compile for Xbox UWP?

**Describe the idea you'd like**
Ability to compile a Xbox compatible UWP that can be side loaded

**Describe alternatives you've considered**
Streaming to Xbox, but it does not work properly

**Additional context**
Since Xbox apps can be PWAs, but I'm not sure if they can run SPAs.

**Comment by dutchy1001** [comment]
I like the idea that PCT is available for consoles but I doubt if this is going to happen in the near future. 
As our devs are already busy with the current versions I don't think they have the time to port it for other devises then there already are.
If any "new developer" will/can take on the job then they are more then welcome to write the code for this.

I leave this topic open for now so 1 of our devs can react to give a final answer.

**Comment by kiriles90** [comment]
The desktop app runs on NW.js (basically node + chromium) but I'm pretty sure there isn't support for it for xbox. If that's the case just simply compiling it isn't possible and this would most likely require an almost complete rewrite of the app. Kind of like the android app (which as far as I know also cant run on xbox, yet, though I remember microsoft announcing support for android apps along with when it did for win11 which did came so who knows.. maybe in the future)

Closing this for now but if someone has a actual way of how this can be done without a rewrite of the app or requiring the users to do extremely complicated procedures and mods on their xbox'es to install we can re-open it.
