### ISSUE TITLE
streaming/casting causes blank screen on mi box 4k 

### ISSUE THREAD

**Issue by harshalchaudhari35** [popcorntime/popcorntime#2721]
I am using popcorn time on linux mint, and when I try to cast from popcorn-time to my mi box 4k device. The screen on my TV remains stuck on a blank/black screen. While the video is downloading and streaming as per popcorn-time, the video on the TV is still stuck.

I'm using popcorn-time desktop on linux mint 21.1

**Comment by harshalchaudhari35** [comment]
The solution to this problem in case in the future anyone is struggling like me, was because of `ufw` firewall on linux mint is enabled by default. The default firewall rule is to deny any incoming connections on all ports to linux mint. 

Turns out as per my understanding, mi box 4k needs to have a way talk back to the streaming device/machine and that device should let incoming connections connect to popcorn-time

I got around this by adding an application profile for popcorn-time to ufw and allowing TCP/UDP ports in the range of 1024-65000 as I couldn't find a way to specify which port popcorn-time selects to stream in advance. 

A good guide to add application profile is available on arch linux wiki: [Adding_other_applications](https://wiki.archlinux.org/title/Uncomplicated_Firewall#Adding_other_applications)

**Comment by kiriles90** [comment]
> was because of ufw firewall on linux mint is enabled by default. The default firewall rule is to deny any incoming connections on all ports to linux mint.  

That would do it 😄 
Also thank you for posting the solution.
Closing this since its not really an issue with the app.

**Comment by zalahditto** [comment]
> The solution to this problem in case in the future anyone is struggling like me, was because of `ufw` firewall on linux mint is enabled by default. The default firewall rule is to deny any incoming connections on all ports to linux mint.
> 
> Turns out as per my understanding, mi box 4k needs to have a way talk back to the streaming device/machine and that device should let incoming connections connect to popcorn-time
> 
> I got around this by adding an application profile for popcorn-time to ufw and allowing TCP/UDP ports in the range of 1024-65000 as I couldn't find a way to specify which port popcorn-time selects to stream in advance.
> 
> A good guide to add application profile is available on arch linux wiki: [Adding_other_applications](https://wiki.archlinux.org/title/Uncomplicated_Firewall#Adding_other_applications)

Same with me but am using windows 10 with sony android Tv.. Any ideas ?
