### ISSUE TITLE
Movies API failed to respond

### ISSUE THREAD

**Issue by luiziurk** [popcorntime/popcorntime#2726]
Operating System Version:

Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ... Open up the app
2. ... Wait for the load
3. ... Gets the error

**Comment by kiriles90** [comment]
Update the API urls so you get all the mirrors too instead of manually editing in the .ga domain then select something else. Its in the settings just below the API fields. Also maybe enable automatic updating if you don't want to manually deal with this again in the future.
