### ISSUE TITLE
Can not watch movies or tv show, only with VLC.

### ISSUE THREAD

**Issue by LuMagalhaes** [popcorntime/popcorntime#274]
Operating System Version: Windows 10
Popcorn Time Version: 0.3.9 
Download date: 10/ 21/2016
Expected Behaviour:
Watching movies or tv show after downloading
Actual Behaviour:
You can not watch movies or tv show, only with VLC.

**Comment by team-pct** [comment]
What version you are using , if the CI WIN32 you should keep using the normal build

**Comment by LuMagalhaes** [comment]
The problem started when he could not put subtitles. I asked for help to Chris who sent the proble solution in build  # 159.   I uninstalled the program and reinstalled following the guidance and after that, returned subtitles, but you can not watch the series and movies on PopCorn. I ask you to send me the updated version to which you refer.

**Comment by LuMagalhaes** [comment]
This is the message I get after doing the downloading: " The video could not be loaded, either because the server or network failed or because the format is not supported". 
**Only allows you to watch for VLC

**Comment by team-pct** [comment]
If you have Windows 64Bit try the Win 64 Bit it should work correctly if not please be patient we will release a working WIn32 version ASAP

**Comment by LuMagalhaes** [comment]
Please, you can leave me the link to install popcorn time. I uninstalled the program and the site does not allow me to open the settings, I tried several times and I can not do the installation. Thanks

**Comment by LuMagalhaes** [comment]
the normal build, I have subtitles available
