### ISSUE TITLE
Do not see subtitles for selecting

### ISSUE THREAD

**Issue by gerarins** [popcorntime/popcorntime#2741]
Operating System Version:

Windows 11

Popcorn Time Version:

4.9

Download date:

4-9-2022

Download url:

https://github.com/popcorn-official/popcorn-desktop/

#### Expected Behaviour

see flag subtitle
...

#### Actual Behaviour

...Nothing 

#### Steps to reproduce the behaviour

1. ... Verify subtitle flag
2. ... reinstall already done, still the same
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://github.com/popcorn-official/popcorn-desktop/assets/6976549/ce54e875-d290-48d6-87b2-a2a6be72a965)

**Comment by dutchy1001** [comment]
Do you have an [opensubtitle](https://www.opensubtitles.org) account and if yes filled in your logon details in the settings?

**Comment by gerarins** [comment]
yes,  my count is open

![image](https://github.com/popcorn-official/popcorn-desktop/assets/6976549/64ce3686-257f-4230-8ad2-4035f93e2330)

**Comment by dutchy1001** [comment]
It could be a glitch as when I tried (using same movie as your screenshot) it all works. 
It is also possible that you ISP blocks opensubs, or that opensubs isn't available in your region (but I doubt that).

I will close this issue as it's not a PCT issue. Feel free to continue here to hopefully sort it.

**Comment by gerarins** [comment]
Thanks for the response dutchy1001, however the problem persists with VPN, and I don't have opensubtitulos.org blocked in media player and VLC.
For your knowledge, in case another user raises it.

**Comment by dutchy1001** [comment]
If you like to try the latest dev build go "[here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5305459024)" and download the "windows" version, see if that helps.

**Comment by gerarins** [comment]
Total genius, solved with the recommended update, thank you very much !!!

![image](https://github.com/popcorn-official/popcorn-desktop/assets/6976549/e05c34e2-0b8d-4b3f-8a84-c7711ea3aed9)
