### ISSUE TITLE
Issue with Trakt synch.Doesn't working at all.

### ISSUE THREAD

**Issue by PsyDominicToRReto** [popcorntime/popcorntime#2744]
-->Hello everyone!
So, Trakt synching is my issue, 
Windows 7 Ultimate
 Popcorn-Time-0.4.9-win64
Re-downloaded and installed in the beginning of 2023 from the link bellow:

https://github.com/popcorn-official/popcorn-desktop/releases

i had downloaded and installed before that date above, but while i was trying to fix it with remove and re-instal with fresh setup.exe i noticed the same behaviour.Now i will try to remove again and instal the win32 version to see if it will be fixed... i don't know what else to do except the upgrade that it's impossible for now at least...!
Also two more things to say... first is while i go in settings tab and try to manually synch with trakt, it says in a very short period (2-3 secs) that it's done but it doesn't when i return in movies tab.All movies i have seen are there as unseen and series too in series tab.
Second thing is that i tried successfully to re-authorise Popcorn with Trakt and i realised repeatedly that unfortunately nothing changed with this issue.
Thanks in advance to all who helped for all these years so i have this way to entertain me and my family and friends at all these movie nights!

**Comment by dutchy1001** [comment]
I never seen the Trakt add-on working for me. 
If you press your function key F12 a web screen will come up, click on "console" (on the top) and you will see an error code from Trakt with a "sync failed HTTPError: Response code 401 (Unauthorized)". To me this looks like that PCT is not allowed to interact with Trakt.
As far I know the devs are aware of this but does not have any priority for now.

Personally I don't see the point of Trakt as you can "hide" and "fade" watched movies and series in PCT.
