### ISSUE TITLE
Torrent Collection searches yield no results

### ISSUE THREAD

**Issue by H00NN** [popcorntime/popcorntime#2745]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.9

Download date: 18/06/2023

Download url: https://shows.cf/build/

#### Expected Behaviour

Expected for the search function in Torrent Collection to get a result even if it wasn't an accurate file. 

#### Actual Behaviour

Tested by searching "Venom", "John", "Flash", no results for any of these when there definitely should be some. (Search function in Movies tab worked no issues)

#### Steps to reproduce the behaviour

1. Navigate to torrent collection
2. Type desired movie 
3. Click Search

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/138299556/88781e9e-44c3-4113-969b-1c13ec64fee5)

Tried different API servers, using these 3 at the moment for reference. Uninstall/Reinstall also did not change anything
![image](https://github.com/popcorn-official/popcorn-desktop/assets/138299556/2f7d19d6-0e70-402d-8c2b-20c1a6e5bd37)

**Comment by dutchy1001** [comment]
As you can see from the picture below it's working for me, but I use a dev build which you can get from [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5366752795)

![venom](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/6c7fdf76-2fe9-48c1-b413-e00338c099f9)

if this fixes your issue then let us know so we can close this topic

**Comment by H00NN** [comment]
dev build provided fixed, thanks
