### ISSUE TITLE
Waiting for subtitle error message in the latest build #169 Popcorn Time Desktop-32/64 

### ISSUE THREAD

**Issue by Jonnathanjons** [popcorntime/popcorntime#275]
Operating System Version:
Windows 10 64 bit

Popcorn Time Version:
PopCorn TIme Desk Top 0.3.19. ( 64 )

Download date:
Oct 27,2016
#### Expected Behaviour

Showing Waiting for Subtitle error and not downloading or casting to DLNA
...
#### Actual Behaviour

Should continue the download and cast to DLNA Device.
...
#### Steps to reproduce the behaviour

 Don't know..
1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Fixed on last Build
