### ISSUE TITLE
Allow searching for movies/shows based on an actors name

### ISSUE THREAD

**Issue by sailinggalaxians** [popcorntime/popcorntime#2756]
**Is your feature request related to a problem? Please describe.**
Whenever I use the search field to find movies that stars a perticular actor in it to get fewer hits I find it strange that it's not possible to filter out movies and/or shows that doesn't have that actor in them.

**Describe the idea you'd like**
My idea is as follows:

Lets say that you want to watch movies that stars Robin Williams and you only want to see movies that he's in.
When you click and type Robin Williams you should be prompted with a question like:
Do you want to see movies that Robin Williams stars in?

**Describe alternatives you've considered**
One alternative would be to make the search more advanced so that one could choose Robin Williams from a list of known actors and then hit Search.

**Comment by kiriles90** [comment]
That's an API issue. If the API supports it, Popcorn Time does too. YIFY used to support it, YTS doesnt and so does the RU API.  

Try opening an issue in the RU API's repo and see if possible.
