### ISSUE TITLE
Need a filter on rating

### ISSUE THREAD

**Issue by sushantgupta** [popcorntime/popcorntime#2758]
**Is your feature request related to a problem? Please describe.**
Need a filter on rating, lets user select the rating from 7.4 to 8.2 then UI should only show filtered items.

**Describe the idea you'd like**
Looking a filter like this
<img width="325" alt="image" src="https://github.com/popcorn-official/popcorn-desktop/assets/7961084/628f549c-871b-469c-b39e-66657fbd7188">

**Comment by kiriles90** [comment]
Or like this
![capture](https://github.com/popcorn-official/popcorn-desktop/assets/38388670/7e1f4e0a-7364-4f0a-844b-cdd0147738d9)

Its there already. But the API has to support it (e.g the YTS API does, the RU one doesn't, if you want that maybe open an issue in the RU API's repo)
