### ISSUE TITLE
Please Tmdb movies series implement api

### ISSUE THREAD

**Issue by Doctor2023** [popcorntime/popcorntime#2759]
hello can you put the tmdb api in the movies and series pocorntime desktop thank you very much and in the version of android tv and android mobile popcorntime

**Comment by dutchy1001** [comment]
The TMDB is already implemented in the desktop version (I don't use the android so don't know for that), the "yellow stars" (on a movie page) are taken from the TMDB api. 
When clicking on the the stars it will change into numerals. When hovering on the stars or numerals a pencell appears. Clicking the pencell it will take you to the TMBD website but unfortunately we/you don't have have permission to access this page. This should  take you to the film page instead would be a better option in my opinion.
