### ISSUE TITLE
Unable to stream subtitles to DLNA devices such as Panasonic Smart LEDs . This is currently lacking in popcorn time.

### ISSUE THREAD

**Issue by Jonnathanjons** [popcorntime/popcorntime#276]
Operating System Version:
Windows 10 64 

Popcorn Time Version:
Popcorn Time Desktop -0.3.9  64 version

Download date:
Oct 27,2016
#### Expected Behaviour

Expecting to stream to DLNA device with subtitle..like kodi or any other application does. This is currently lacking in popcorn time ..
I guess this currently working only for people use chromecast. but wanted this feature to extend to direct DLNA devices.
...
#### Actual Behaviour

...
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Dupe #158
