### ISSUE TITLE
Latest installer was deleted by antivirus windows

### ISSUE THREAD

**Issue by jeltedeproft** [popcorntime/popcorntime#2760]
Operating System Version:
windows11

Popcorn Time Version:
latest build at 26/07/2023

Download date:
26/07/2023

Download url:
(https://github.com/popcorn-official/popcorn-desktop/actions/runs/5496482437)

#### Expected Behaviour
just install without problems

#### Actual Behaviour
antivirus gives a warning that there is a trojan during the installation and removes the startup executable and some other files

#### Steps to reproduce the behaviour
just install on windows 11? the latest build

**Comment by dutchy1001** [comment]
My anti-virus (Avast) didn't find anything. 
As this software has features that are frowned upon too it's most likely a false positive
