### ISSUE TITLE
selectNextEpisode naively selects the next episode selected in the list, and not the next episode of the one being closed

### ISSUE THREAD

**Issue by zacholade** [popcorntime/popcorntime#2761]
Operating System Version:

OS X

Popcorn Time Version:

0.4.9 Beta 64553fa7

Download date:

6 months ago, but going to settings -> (i) -> check for updates -> it says "Success. Already using the latest version"

#### Expected Behaviour

1. Watching episode `i` in a series.
2. I choose to minimise (not close) the currently playing episode, `i` to reveal other episodes.
3. I then select on an episode, `j` which is != `i`
4. I reopen the minimised player for episode `i`, finish watching the episode and now fully close it.
5. I expect the newly selected episode to be `i+1`

#### Actual Behaviour

The selected episode is now `j+1`

#### Steps to reproduce the behaviour

1. Find a series to watch with many episodes.
2. Click Watch now on e.g. episode 1.
3. Minimise the player to reveal all episodes in the series.
4. click on episode 5, but do not play it (maybe you got curious in the title).
5. Reopen the minimised episode 1 player, finish watching it, and now click close.
6. The currently selected episode is now 6. Not 2.

I had a look at the code in function `selectNextEpisode` and its current logic is just to increment the selected episode by 1.

**Comment by dutchy1001** [comment]
Your PCT version is not the latest beta version build. The "check for updates" function only checks for the latest release (v0.4.9). 
All beta's are also v0.4.9 it thinks you use the latest version (64553fa was released on 22 September 2022).

Your issue with playing "the next" episode has (as far I know) always been buggy and not working 100%.

This is not a priority issue so fixing might be postponed till the devs have time. 

If you update to the latest dev [build](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5496485657) you have to option to make multiple downloads.

**Comment by kiriles90** [comment]
@zacholade just tried with the latest season of family guy and cant replicate it tbh. @dutchy1001 can you?

**Comment by dutchy1001** [comment]
With the latest dev build (build 89aaf93a from about 3 weeks ago) the next episodes work for me (as it was buggy before I never used this function again till todays test)

![next episode](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/8106566c-2ce3-4a41-a89d-dfba4c2c74a0)
As you can see from the screenshot you now  have the option to a "No thank you" and "Play Now" buttons or you let the counter  (Playing Next) run down and your next episode will start then.

After all this, it also will depend if the API finds all episodes, for example, if the API finds episode 1,2,3,4,6,8 then it will go from episode 4 to 6 and skips 5 as it can't find it. Hope that makes sense....

**Comment by kiriles90** [comment]
@dutchy1001 plays the correct episode right? I mean if you have s21e13 playing it continues with 14 (or the next available) no matter what episode/season you have selected in the show detail screen? Because as I understand it this is the issue @zacholade is describing but I cant replicate it.

**Comment by dutchy1001** [comment]
Yes I was watching episode 13. 
When checking the "download" folder it was also starting to download episode 15 as 14 was complete downloaded.

**Comment by kiriles90** [comment]
Thanks. Ok so closing this for now but if anyone (OP incl) can provide a way this can be replicated on the latest build we can re-open it.
