### ISSUE TITLE
Crash/Close on Linux while downloading movies

### ISSUE THREAD

**Issue by gustavomassa** [popcorntime/popcorntime#2763]
Operating System Version:
Linux Mint 21.2

Popcorn Time Version:
Latest Official Release 0.4.9
![image](https://github.com/popcorn-official/popcorn-desktop/assets/16235598/56f2371e-9cda-4d1c-95a9-291c96342dc0)

#### Expected Behaviour
Keep downloading files without crashing/closing the application
...

#### Actual Behaviour
After some time, sometimes 2 minutes, sometimes 15/30, while downloading 2 movies at the same time, the application suddenly close
...

#### Steps to reproduce the behavior
Download 2 movies at the same time and wait

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
Two different crash outputs:

![image](https://github.com/popcorn-official/popcorn-desktop/assets/16235598/9230ec4e-2e2a-4fc0-8494-3f2e382a4d84)
```
<--- Last few GCs --->
on[12151:0x190500000000]    75734 ms: Mark-sweep 1022.8 (1025.6) -> 1022.8 (1025.6) MB, 314.2 / 0.1 ms  (+ 0.2 ms in 1 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 1038 ms) (average mu = 0.800, current mu = 0.838) alloc[12151:0x190500000000]    78914 ms: Mark-sweep 1126.2 (1129.1) -> 1126.2 (1129.1) MB, 875.2 / 0.1 ms  (+ 1.0 ms in 4 steps since start of marking, biggest step 0.3 ms, walltime since start of marking 1440 ms) (average mu = 0.749, current mu = 0.724) alloc

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1905082f6939 <String[8]: nw-token>
    0: builtin exit frame: fill(this=0x19050b5e836d <JSArray[4110417926]>,0,0x19050b5e836d <JSArray[4110417926]>)

    1: recalculate [0x19050a263479] [/opt/Popcorn-Time/node_modules/webtorrent/lib/rarity-map.js:91] [bytecode=0x19050a7a6a41 offset=16](this=0x19050b5e4559 <RarityMap map = 0x19050a9597f9>)
    2: /* anonymous */ [0x19050b841a65] [/opt/Popcorn-Time/node_modules/webtorren...
```

![image](https://github.com/popcorn-official/popcorn-desktop/assets/16235598/cdca2d39-7dd7-4353-9b48-bee0f2a1231f)
```
<--- Last few GCs --->
on[12151:0x190500000000]    75734 ms: Mark-sweep 1022.8 (1025.6) -> 1022.8 (1025.6) MB, 314.2 / 0.1 ms  (+ 0.2 ms in 1 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 1038 ms) (average mu = 0.800, current mu = 0.838) alloc[12151:0x190500000000]    78914 ms: Mark-sweep 1126.2 (1129.1) -> 1126.2 (1129.1) MB, 875.2 / 0.1 ms  (+ 1.0 ms in 4 steps since start of marking, biggest step 0.3 ms, walltime since start of marking 1440 ms) (average mu = 0.749, current mu = 0.724) alloc

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1905082f6939 <String[8]: nw-token>
    0: builtin exit frame: fill(this=0x19050b5e836d <JSArray[4110417926]>,0,0x19050b5e836d <JSArray[4110417926]>)

    1: recalculate [0x19050a263479] [/opt/Popcorn-Time/node_modules/webtorrent/lib/rarity-map.js:91] [bytecode=0x19050a7a6a41 offset=16](this=0x19050b5e4559 <RarityMap map = 0x19050a9597f9>)
    2: /* anonymous */ [0x19050b841a65] [/opt/Popcorn-Time/node_modules/webtorren...
```

Maybe OOM? How can I increase the max memory allocation for popcorn time?
I also noticed these warnings during execution:
```
[11087:11147:0805/203725.864434:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:53547
[11087:11147:0805/203725.864729:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:54461
[11087:11147:0805/203725.864747:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:54461
[11087:11147:0805/203725.867632:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:53264 
[11087:11147:0805/203725.867652:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:53264 
(node:11087) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:11087) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:11087) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
[11087:11147:0805/203735.700648:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:36481 
[11087:11147:0805/203735.700704:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:36481 
[11087:11147:0805/203735.700749:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:40343 
[11087:11147:0805/203735.700770:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:40343
[11087:11147:0805/203735.700806:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:54612 
[11087:11147:0805/203735.700826:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.0.x:54612 
```

**Comment by dutchy1001** [comment]
Are you using the latest 0.4.9 "Official Release" or do you use a "dev build"?
It would be handy to know the exact version. You can see this by going to the "setings" tab and then click on the i for info. It will say something like "Ogres are not like cake. Beta-89aaf93a".
 89aaf93a is then your build version, plz post that number then.

**Comment by gustavomassa** [comment]
I'm using the latest version downloaded through github releases (.deb package)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/16235598/56f2371e-9cda-4d1c-95a9-291c96342dc0)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/16235598/92ee9d78-e35f-4e50-b7d1-6422a9054660)

The commit hash is different, I'm using the "Official Release", I will build directly from the source and let you know if I face the same issue.

**Comment by dutchy1001** [comment]
Your build is from  4 September 2022, so many fixes and features have been added since.
If you update from [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5496485657) and then see if it still happens

**Comment by kiriles90** [comment]
@gustavomassa @dutchy1001 is this still relevant with the development branch / latest build ?

**Comment by dutchy1001** [comment]
I dont have a linux machine so was waiting for OP to answer. 
If no answer in the next few days I presume it is solved and can be closed then.
