### ISSUE TITLE
Wrong movie

### ISSUE THREAD

**Issue by cat-lady37** [popcorntime/popcorntime#2764]
The movie Sound of Freedom is not the actual movie. It is something totally different.

**Comment by dutchy1001** [comment]
This is not an Popcorn-Time issue. 
The API just shows what it finds, nothing our devs can do about that. 

If using the latest [dev build](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5776714718) you can click on the "more..." button to choose an other version (looks like there are 3 versions atm).

Closing this but feel free to answer.

**Comment by cat-lady37** [comment]
Thank you for your answer. I do not have idea how to do that...I do not see 3 dots and the movie gets downloaded automatically. Sadly, seems like I wont be able to watch it here.

**Comment by dutchy1001** [comment]
By your comment I presume you have an older build. 
If you click on the "blue" writing in my previous post you will be directed to the latest dev build. Click on "windows-latest" (if you have a windows OS ofcourse) and it will download the the latest version. 
Extract (winrar,7zip or windows10/11) this file to a folder and it will have 4 files in it, double click on  the "win64-Setup" and the setup will begin. When done click "finish" and your updated PCT is ready to go.
