### ISSUE TITLE
Flash movie is not the Flash movie

### ISSUE THREAD

**Issue by AndykaySverige** [popcorntime/popcorntime#2765]
Flash movie is not the Flash movie

**Comment by dutchy1001** [comment]
This is not an Popcorn-Time issue. 
The API just shows what it finds, nothing our devs can do about that. 

If using the latest [dev build](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5776714718) you can click on the "more..." button to choose an other version.

Closing this but feel free to answer.
