### ISSUE TITLE
Immeaditely crashing after opening on macos ventura

### ISSUE THREAD

**Issue by HmSultan02** [popcorntime/popcorntime#2766]
The app for popcorn time immediately crashes and shows error message when opening on macos, tried reinstalling that didn't fix the issue.

**Comment by HmSultan02** [comment]
v0.4.9

**Comment by dutchy1001** [comment]
Opening a new bug report has a few questions wich  we use to help you. Just saying it crashes and shows an error is not helping us.
Help us to help you to fix this and fill in the details we use to help (this include the error message and/or screenshot of it)

I close this issue as we cant help you without the info. 
Feel free to open a new issue with the correct questions answerd.
