### ISSUE TITLE
Set dependencies in the .deb package

### ISSUE THREAD

**Issue by rany2** [popcorntime/popcorntime#2768]
Currently the Debian package does not set the dependencies it requires, instead users are asked in the ReadMe to manually install the dependencies for the .deb package.

This leads to some problems including making it such that when the user wants to uninstall, Popcorn Time's dependencies won't be marked as "unneeded" and removed when running `apt autoremove`. Also it causes user that did not read the ReadMe to be unable to troubleshoot the issue without somewhat novice Linux skills.

I propose that the known dependencies of Popcorn Time be set here https://github.com/popcorn-official/popcorn-desktop/blob/development/dist/linux/deb-maker.sh#L67 so that the user doesn't need to manually install them. I have found that only `libatomic1` is needed, the other dependencies mentioned in the ReadMe, `libgconf-2-4` & `libcanberra-gtk-module` are not needed for Popcorn Time's operation.

**Comment by kiriles90** [comment]
Are you sure the rest of the packages aren't needed or they aren't needed for you/your distro/installation? I remember various comments with people requiring those too, and some not requiring anything from the above. But anyway, on the bigger issue at hand... ReadMe's are meant to be read if you ask me. Same thing as the FAQs that some people refuse to read then go and create 10 posts a day with questions already answered there. Either way, if someone wants to make a PR about this I'll merge it.

**Comment by ivan1986** [comment]
yes, we have a strange method of build deb package, it is old code and not change
ok, need change it to normal package build

**Comment by kiriles90** [comment]
@rany2 @ivan1986 could someone make a PR when they can? (Ivan no need to rewrite everything just the dep, but.. if you want to go for it.. all yours 😄)
