### ISSUE TITLE
Crash while reading movie description

### ISSUE THREAD

**Issue by AI-NERON** [popcorntime/popcorntime#2770]
Operating System Version: Mac OS Ventura (13.5.1)

Popcorn Time Version: 0.4.9

Download date: 08/24/2023

Download url: https://shows.cf/build/Popcorn-Time-0.4.9.pkg

#### Expected Behaviour
Being able to read movie description, selected from home page

#### Actual Behaviour
The app crashes

#### Steps to reproduce the behaviour
Open the app, select the first movie available

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
Full stacktrace : https://pastebin.com/UHS7umuL

**Comment by kiriles90** [comment]
Has nothing to do with reading or not the movie description. This is due to NW.js. The release version uses an older version which has issues with newer macOS versions. To fix it just get the latest build from the Actions page, it uses a much newer version (0.44.5 vs 0.77.0)
