### ISSUE TITLE
Anime tab not working - The remote anime API failed to respond

### ISSUE THREAD

**Issue by jazir555** [popcorntime/popcorntime#2771]
Operating System Version:

Windows 11

Popcorn Time Version:

0.4.9

Download date:

Today

Download url:

github releases page

#### Expected Behaviour

...

Loading a tab with anime in the same way it loads on the movies and tv tab card style, with options for dub or sub once you click into the card.

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. Click the anime tab
2. Nothing will load

**Comment by kiriles90** [comment]
Download the latest build (development branch) from the Actions page, not the latest release version (master branch) from last year.

**Comment by jazir555** [comment]
> Download the latest build (development branch) from the Actions page, not the latest release version (master branch) from last year.

The YML file? How do I build it?

**Comment by dutchy1001** [comment]
no, you need to click on "update NW.js" and then choose "windows-latest"

**Comment by jazir555** [comment]
> no, you need to click on "update NW.js" and then choose "windows-latest"

I got it installed and working. The anime tab loads now, but every series is missing episodes. Many of them contain just 1, and some have zero episodes listed.

Just as an example, Fairy Tale has 8 seasons, and tons of missing episodes.

Is that due to where it's pulling from in the API?

Edit: Another few things I notice is that there are no paginated tabs for multiple seasons for the anime section when you click into a show. There also seems to be missing languages from some titles. One title only had Russian audio, and no options for English dub or the original Japanese dub.

**Comment by dutchy1001** [comment]
Yes , this is depending what the API finds. The API is out of our control so we cant do anything about this.

> Edit: Another few things I notice is that there are no paginated tabs for multiple seasons for the anime section when you click into a show. There also seems to be missing languages from some titles. One title only had Russian audio, and no options for English dub or the original Japanese dub.

Sometimes when using a 3rd party payer you can choose different build-in languages or/and subs. I use SMPlayer for PCT which works brilliant. You can then also add your own audio/subs (if you know where to get those).

**Comment by jazir555** [comment]
Is there another API you can add additionally to pull more episodes? Good sources if they're usable are https://nyaa.si or https://animetosho.org

Edit: Here's an unofficial Nyaa API: https://github.com/Kylart/Nyaapi

Edit: I believe animetosho's API is located here: https://feed.animetosho.org/ or here: https://feed.animetosho.org/rss2

More on Animetosho's API here: https://animetosho.org/about

**Comment by dutchy1001** [comment]
I'm sure our devs will look into these API links to see if they will be beneficial for PCT.
Thx for sharing them.

**Comment by jazir555** [comment]
@dutchy1001 

Would you mind alerting the devs about these APIs? This thread is closed, so I'm not sure if they will see this issue.

**Comment by kiriles90** [comment]
@m-meadow these are API issues not app issues but from what I know there were issues adding nyaa as an API source because their API doent provide an id (imdb, tmdb, trakt, something..) or some other means of tagging an entry. There is nyaa search in the Torrent Collection tab though which doesnt need an id.

**Comment by jazir555** [comment]
Would you be able to add the Animetosho API? Animetosho has pretty much every episode of every anime that's been released, in multiple languages(subtitles and audio).

If you can add the Animetosho API, it basically solves the missing episode issues entirely in one fell swoop.

**Comment by kiriles90** [comment]
I dont know like I said these are API issues. Our current main API is the RU one so open an issue there (https://github.com/popcorn-time-ru/popcorn-ru) and @ivan1986 will surely know more which sources can be added without issues. 

Failing that, if there already is an anime API with torrents out there and we want to use it directly (e.g like the yts one for movies) chances are it wont be compatible with Popcorn Time so a wrapper will have to be coded for it if possible and the API provides all the necessary data.

**Comment by jazir555** [comment]
> I dont know like I said these are API issues. Our current main API is the RU one so open an issue there (https://github.com/popcorn-time-ru/popcorn-ru) and @ivan1986 will surely know more about which sources can be added without issues.
> 
> Failing that, if there already is an anime torrent API out there and we want to use it directly (e.g like the yts one for movies) most chances are it wont be compatible with Popcorn Time so a wrapper will have to be coded for it if possible and if the API provides all the necessary data.

Animetosho has an API rss feed, and they have anime torrents, with magnet links.  https://feed.animetosho.org/rss2

There's also this one: https://feed.animetosho.org/

**Comment by kiriles90** [comment]
Same problem as with nyaa as far as I can see. No id or something that can be used as one whatsoever. But.. if you want to be sure open this issue in the API repo.

**Comment by reynoldyehezkiel** [comment]
> I got it installed and working. The anime tab loads now, but every series is missing episodes. Many of them contain just 1, and some have zero episodes listed.

How did you do it? Would you like to give tutorial of it?

**Comment by dutchy1001** [comment]
@reynoldyehezkiel
make sure you got one of the latest [dev builds](https://github.com/popcorn-official/popcorn-desktop/actions/runs/6994272141).
