### ISSUE TITLE
When will you see improvements and changes PopcornTime desktop

### ISSUE THREAD

**Issue by Doctor2023** [popcorntime/popcorntime#2772]
When will you see improvements and changes popcorn time desktop is only version v0.4.9 will you see an update year 2023

**Comment by dutchy1001** [comment]
Improvements are constantly made and can be found in the "action" tab. If you have a specific issue that you would like our devs to into then you have to explain this (in a new post).
As of now this will be closed as it has no value to "fix" issues.
