### ISSUE TITLE
MacOS Sonoma Compatibility 

### ISSUE THREAD

**Issue by ronydebnath** [popcorntime/popcorntime#2775]
Operating System Version:
MacOS Sonoma 14.0

Popcorn Time Version:
0.4.9

Download date:
22 September 2023

Download URL:
Downloaded both from here: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9.pkg

and also from the actions artifact: https://github.com/popcorn-official/popcorn-desktop/suites/14156694614/artifacts/793192783

#### Expected Behaviour
The MacOS desktop application should run normally. 

#### Actual Behaviour
Closes with showing an nwjs library error

#### Steps to reproduce the behaviour
Update the MacOS to the latest version 14.0 and try running the popcorn desktop app.

**Comment by kiriles90** [comment]
Download and install the new NW.js (0.79.0) dev build from the actions page, not the old one (0.44.5)
Closing this as its a known issue with the old NW.js builds but comment below if you are still having any issues.
