### ISSUE TITLE
`gulp` command does not exist, "gulp: command not found..."

### ISSUE THREAD

**Issue by elvisisvan** [popcorntime/popcorntime#2777]
Operating System Version: Linux, Fedora 38

Popcorn Time Version: development build 0.79.1

Download date: October 16th 2023

Download url: commit hash [7b7c8e0](https://github.com/popcorn-official/popcorn-desktop/commit/7b7c8e06d0d3fd67010cf3dee3bb74e553707c74)

#### Expected Behaviour

`gulp run` command will launch Popcorn-Time 

#### Actual Behaviour

terminal error output: "gulp: command not found..."

#### Steps to reproduce the behaviour

1. build Popcorn-Time with `./make_popcorn.sh` command
2. input "Y" when asked "Create a desktop entry for Popcorn Time for the current user ? (Y)es/(N)o: "
3. `gulp run`

#### Screenshot(s) of issue or error(s) logs of developer console 

![gulp command not found](https://github.com/popcorn-official/popcorn-desktop/assets/69122770/f2a3ac75-590e-429b-91b3-7363ed590854)

**Comment by kiriles90** [comment]
@ivan1986 should be able to help

**Comment by ivan1986** [comment]
ok, need rewrite this text
all build, not need to run gulp, and now it local

**Comment by ivan1986** [comment]
hm, after `yarn build` we have ready to use popcorn

**Comment by kiriles90** [comment]
Can I leave it to you to make a PR whenever you are not busy please? Cant really test linux and dont want to merge a breaking change.

**Comment by ivan1986** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/2778

**Comment by elvisisvan** [comment]
actually this is partly my fault, i realized `gulp` is an npm package and i didn't have it installed, so i `npm i gulp -g` installed it and `gulp run` executed successfully
![image](https://github.com/popcorn-official/popcorn-desktop/assets/69122770/1483efbb-3438-44e0-b58c-4f0dcad348ff)

![image](https://github.com/popcorn-official/popcorn-desktop/assets/69122770/31ad1aaf-6fe6-4e5a-845c-cf2751011b73)

**Comment by elvisisvan** [comment]
actually this is partly my fault, i realized `gulp` is an npm package and i didn't have it installed, so i `npm i gulp -g` installed it and `gulp run` executed successfully

![image](https://github.com/popcorn-official/popcorn-desktop/assets/69122770/b8587cf6-14e1-451d-9213-070d9ef7c040)
