### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by drahgon55** [popcorntime/popcorntime#278]
Operating System Version:

OS X 10.11.6

Popcorn Time Version:

build 159
dd2fe432e9f127d7366aaa4d46074aa77fb9821f

I also tried the latest build same thing

Download date:

today
#### Expected Behaviour

... stream over chromecast
#### Actual Behaviour

... immediately fails streaming. The console log has this message

app.js:21 [ERROR] Streamer: unable to verify the first certificatewin.error @ app.js:21
app.js:11 [INFO] Streaming cancelled
#### Steps to reproduce the behaviour

1. ... try to stream to chromecast
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Which movie, show or anime did you try and in which quality?

**Comment by drahgon55** [comment]
both qualities gave the same issue

**Comment by ChrisAlderson** [comment]
Short story: a script is running on the server which should resolve this issue.

Long story: don't feel like writing it atm, but I can if you want to.

**Comment by drahgon55** [comment]
nope short story works.
