### ISSUE TITLE
opensubtitles Cloudflare protection

### ISSUE THREAD

**Issue by SebastianSava** [popcorntime/popcorntime#2780]
Hello!

You can find more info here - https://www.reddit.com/r/Stremio/comments/17df82j/subtitles_issues/

IK the subreddit is from Stremio, but this is a general issue. Seems opensubtitles added CF protection.

**Comment by dutchy1001** [comment]
Subs still working with the latest builds, I don't see what the problem is.

I can't see this as an issue (for now). 
Feel free to continue here, but I will close this topic.

**Comment by SebastianSava** [comment]
@dutchy1001 - Try to watch a movie with some subtitle. You will see that the translation file has the extension [region]undefined.

![image](https://github.com/popcorn-official/popcorn-desktop/assets/67977875/543322aa-3fba-47b1-88a9-d3700d7c6e95)

Also, it's content it's a html page served from Cloudflare.

![image](https://github.com/popcorn-official/popcorn-desktop/assets/67977875/59b6701f-95df-4302-aa82-9d5cdf51cce9)

This happens with any other translation language. This issue should be reopened as it affects all users.

Thanks :)

**Comment by merseyV** [comment]
@dutchy1001 
Reported on subreddit, as well:

(https://www.reddit.com/r/PopCornTimeApp/comments/17dq30b/subtitles_not_working/)

**Comment by kiriles90** [comment]
OpenSubtitles and/or Cloudflare seems to have messed something up and broken all apps that relied on their XML-RPC API. They have announced it will reach end of life soon, but that date hasn't arrived yet afaik (there is a post somewhere in their forum) so we should just wait a bit for now. Switching to the REST API should happen eventually but will require some time and then everyone will have to update their clients which I dont see as a quick solution at the moment for the issue at hand.

**Comment by merseyV** [comment]
Uh Oh! .. MacCat just found out his subs are down

![giphy](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/5a62e72c-8b1e-409c-98d2-f610057060f0)

**Comment by merseyV** [comment]
![giphy](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/94dcd18c-c4d9-476d-86f8-a3578a434253)

**Comment by merseyV** [comment]
@dutchy1001

Have we done something? - subs are working again here! How about you two?

<img width="1157" alt="Screenshot 2023-10-23 at 19 10 05" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/37829739-a3fb-442e-889f-ebb5965b123a">

**Comment by dutchy1001** [comment]
Looks like they disabled the cloudflare again. 
I think they have realised they broke many API's this way

**Comment by merseyV** [comment]
@Breaking1
And where have you been hiding!

.... out drinking with the isbjørn?
![960x0](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/999d5d82-e382-401b-90ca-939a06892a9a)

**Comment by merseyV** [comment]
> merseyV, dutchy1001, iKenshu, and Breaking1 reacted with thumbs up emoji

@Breaking1
Step out of the shadows! ... You are "Lobby Lud" and I claim my £5!

Where have "you" been hiding ... boozing with the isbjørn, again?

![960x0 copy](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/99db6b24-4562-41d8-95f0-44903151a98c)
