### ISSUE TITLE
No audio on any TV show or Film

### ISSUE THREAD

**Issue by joshua-bouv** [popcorntime/popcorntime#2782]
Operating System Version: Windows 11 22H2

Popcorn Time Version: 0.4.9 - 2e334809

Download date: 04/11/2023

Download url: https://github.com/popcorn-official/popcorn-desktop/suites/17505099206/artifacts/1000071208

#### Expected Behaviour
Play audio

#### Actual Behaviour
No audio seems to be present when watching any TV show or movie. I've tried different TV shows and moves, but they all have no sound.

Popcorn Time doesn't appear in my volume mixer:
![image](https://github.com/popcorn-official/popcorn-desktop/assets/17968553/89988810-ac44-4868-ba07-a251ed60c265)

My default device is also correctly set:
![image](https://github.com/popcorn-official/popcorn-desktop/assets/17968553/7050886a-f17c-4f85-9084-c88b3eab89ee)

Audio Passthrough is not ticked:
![image](https://github.com/popcorn-official/popcorn-desktop/assets/17968553/c5e7d578-c30c-456a-ab65-2a1a024fe376)

My sound is working for other apps (ie spotify).

I've done a clean install of popcorn time and reset everything to default settings, but it still persists.

#### Steps to reproduce the behaviour

1. Play anything

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/17968553/d7ee72bd-dbb1-47a5-b160-d8b8f1dfd987)

**Comment by kiriles90** [comment]
Its most likely missing codecs. Some movies/series should have sound but others not. That's the issue with the new NW.js build and we are forced to keep the old one also alive for now. Check https://github.com/popcorn-official/popcorn-desktop/issues/2062 for more and either downgrade to an old NW.js build, e.g (0.4.9 release version or the latest 0.4.9 old NW.js dev build) or use a supported external player for playback (e.g VLC etc)
