### ISSUE TITLE
a button to choose a video player from pc manually

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2788]
It would be great to have a button in UI where you can choose a video player installed on your pc if popcorn doesnt show it on the list.
or an option to select default player in settings.
Thank you.

**Comment by kiriles90** [comment]
This will cause a lot more issues than it solves. People will select unsupported players or players installed in non default locations then will come open issues when it doesn't work. As for selecting a default player, you can do it in the player menu, whichever player you select there becomes the default one (except cast devices for obvious reasons)
