### ISSUE TITLE
the movies app is not working

### ISSUE THREAD

**Issue by kim1410** [popcorntime/popcorntime#279]
Operating System Version:
 windows 10

Popcorn Time Version:
0.3.9-0

Download date:

#### Expected Behaviour

 when i clicked on the movies API app, i expected it to show the movie collection.
...
#### Actual Behaviour

 it wont show the movie collection, instead it reads " the remote movies API failed to respond, please check https://status.popcorntime.sh and try again later. but the before mentioned site says " all systems operational" but the movies app has been like that for a few days now.
...
#### Steps to reproduce the behaviour

1. ... start up popcorntime
2. ... click on the movies app
3. ... and there you have it, the remote movies app failed to respond.

**Comment by team-pct** [comment]
Try https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

We do not have any issue on our side

**Comment by kim1410** [comment]
do you reccomend win32 or 64?

**Comment by team-pct** [comment]
Win64 would have full codecs
