### ISSUE TITLE
Is there a vpn built in?

### ISSUE THREAD

**Issue by samomar** [popcorntime/popcorntime#28]
If so, I can't seem to find a module for it in the source I have

**Comment by Breaking1** [comment]
That's correct because there isn't a built in vpn option anymore. You could only use it with vpn.ht, that's probably why it got removed.

If they will add the option to log on with multiple vpn's in the future only time will tell.

**Comment by team-pct** [comment]
NO buit-in VPN yet , we are working on general VPN client ( Multi-VPN provider)
