### ISSUE TITLE
Anime Tab Problem

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#280]
![2016-10-29](https://cloud.githubusercontent.com/assets/18757054/19828988/0b04a814-9dd6-11e6-96f0-da85d353be90.png)
Operating System Version:
Windwos 10

Popcorn Time Version:
0.3.9

Download date:
22/10/2016
#### Expected Behaviour

To show the Anime tab
#### Actual Behaviour

Shows an error
#### Steps to reproduce the behaviour

Fix the Anime tab problem

**Comment by ChrisAlderson** [comment]
Try the latest build on ci.popcorntime.sh

**Comment by GKid94** [comment]
You mean the Experimental one?
