### ISSUE TITLE
"Your profile cannot be used because it is from a newer version of NW.js"

### ISSUE THREAD

**Issue by elvisisvan** [popcorntime/popcorntime#2800]
Operating System Version: Linux, Fedora 38
 

Popcorn Time Version: 0.4.9

Download date: August 14th 2023
 

Download url: https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.9

#### Expected Behaviour

popcorn-time opens without error alert

#### Actual Behaviour

pop-up error alert appears for about 1 second then disappear, then popcorn-time opens

#### Steps to reproduce the behaviour

1. run `popcorn-time` in bash
2. error pop-up appears

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://github.com/popcorn-official/popcorn-desktop/assets/69122770/395a2993-28d0-4994-b1ae-241bb1db7d03)

**Comment by dutchy1001** [comment]
plz update to a dev build from [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/6994272141), If the problem is still there report back or close if it's solved.

**Comment by kiriles90** [comment]
like @dutchy1001 said update to the latest dev build. If it continues clean install the app instead of installing in on top of whatever old version you had and it will resolve itself (you can backup your database in the settings and restore it once you clean install)
