### ISSUE TITLE
Editing the database folder location 

### ISSUE THREAD

**Issue by medmek** [popcorntime/popcorntime#2801]
Editing the database folder or directory location in the advanced settings

The location folder of the database seems to be locked to MyUserName\AppData\Local\Popcorn-Time\User Data\Default\data 
(maybe for reasons that I don't know yet)

I want to be able to specify a location that a cloud based file sharing service is handling (like Onedrive, Google Drive ...)
And maybe changing the folder can even start an export/import of the DB to the new location.

I changed my working environment many times, and most of it was sudden, I didn't have time, or the foresight of exporting my database beforehand, making a lot of features useless to me.
Sometimes I switch back and forth (Windows <> Linux) and I would like to keep my data (bookmarks, seens...) synced.

Related issue [#1965 ](https://github.com/popcorn-official/popcorn-desktop/issues/1965) (not completed)

Operating System Version:
Windows 10, Linux

Popcorn Time Version:
64553fa7

**Comment by kiriles90** [comment]
The reason previous issues were closed and this was never possible in the settings is that `\User Data\Default\` is the Chromium profile directory. Messing with internals like that with janky solutions, if even possible to begin with without breaking stuff for many users right away, never went well for long. Never mind the security implications which some might actually care about.
