### ISSUE TITLE
Debian requirements

### ISSUE THREAD

**Issue by RandomAct5** [popcorntime/popcorntime#2805]
Hi,

I thought I'd share this in case anyone else hits missing requirement issue(s) for Debian-based system.

Initially update your repo database.
`sudo apt update`

**Issue:**
_libnss3.so.1d: cannot open shared object file: No such file or directory:_

**Resolution:** 
`sudo apt install libnss3`

**Issue:**
_libXtst.so.6: cannot open shared object file: No such file or directory:_

**Resolution:**
`sudo apt install libxtst6`

**Issue:**
_libXss.so.1: cannot open shared object file: No such file or directory:_

**Resolution:**
`sudo apt install libxss1`

**Issue:**
_libatspi.so.0: cannot open shared object file: No such file or directory:_

**Resolution:**
`sudo apt install libatspi2.0-0`

**Issue:**
_libgtk-3.so.0: cannot open shared object file: No such file or directory:_

**Resolution:**
`sudo apt install libgtk-3-0`

**Comment by kiriles90** [comment]
Hi, would you like to make this into a PR for the (README.md)[https://github.com/popcorn-official/popcorn-desktop/blob/development/README.md] file? There are already some dependencies for linux there so I guess add these too with any other info you'd like to add? If yes just let me know and I can merge it whenever you say its ready.
