### ISSUE TITLE
Freeze / Crash when download speed is too fast.

### ISSUE THREAD

**Issue by frozenicex88** [popcorntime/popcorntime#2808]
Operating System Version:
Windows 11 pro

Popcorn Time Version:
0.49

Download date:
25 Dec 2023

**Comment by merseyV** [comment]
Have you tried the latest Dev build? Should be an improvement over the old versions.
**https://github.com/popcorn-official/popcorn-desktop/actions/** ... you'll need to be signed in to GitHub before downloading is active.
