### ISSUE TITLE
popcorn closes out 

### ISSUE THREAD

**Issue by alaalma** [popcorntime/popcorntime#282]
Operating System Version:
 OS Sierra 10.12

Popcorn Time Version:
 beta 3.9

Download date:
 28/10/16
#### Expected Behaviour

...
#### Actual Behaviour

 app closes out automatically while buffering the movie or in the very first few seconds of the movie
...
#### Steps to reproduce the behaviour

 
1. ... open popcorn
2. ... open a movie (i.e. Mr. Church)
3. ... wait buffering and while the movie reproduces it should close the app.

**Comment by ChrisAlderson** [comment]
Please check for open and closed issues first before opening an issue. Your issue should have been resolved and is discussed in #236.
