### ISSUE TITLE
The watchlist could be in a more accessible location

### ISSUE THREAD

**Issue by emirhandev** [popcorntime/popcorntime#2826]
It will be more useful for the user to have the watch list in a location where the user can access it more easily. For example, a separate tab can be created for the watch list next to the favorites instead of using a filter inside the favourite tab.

Thank you for your interest and wish you good work.
![Ekran görüntüsü 2024-01-10 231356](https://github.com/popcorn-official/popcorn-desktop/assets/97605841/c2a0ab9b-a4e1-4dfe-8993-1401ad9bb1b9)

**Comment by merseyV** [comment]
@emirhandev 

Feature already in 'New Build' on GitHub ...

**Comment by dutchy1001** [comment]
The "watched" tab has already been moved so I will close this topic.
