### ISSUE TITLE
Automatic Client Update

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#283]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
31/10/2016

#### Expected Behaviour
I want to leave a suggestion if you guys can make an automatic update option in client so that we don't have to download a new client every time a new update comes out

#### Actual Behaviour
I have to download the client manually

#### Steps to reproduce the behaviour
Make an auto client update option

**Comment by team-pct** [comment]
No Infrastructure for a large scale deployment of an update , 
Maybe once @VitorVRS Will finish implement web torrent we will be able to use it to release Updates

http://status.popcorntime.sh
