### ISSUE TITLE
Other OS Implementations

### ISSUE THREAD

**Issue by julianbrasse** [popcorntime/popcorntime#2840]
We love popcorntime, yet pulling out a windows laptop while sitting in the subway for the duration of three stops is quite useless and difficult. This is why it would be great if:

- The android app gets updated, since the last time anyone seemingly touched it was 2022 (maybe a download button would be nice too)

Thank you!

**Comment by julianbrasse** [comment]
Hey so I do apologize for doing this at the wrong place, but as specified in my original "issue" I did say the android app exists, but as issues or comments about it go mostly ignored I hoped to indicate how important the Android app is to many in a different place where it might be given more "attention" and perhaps visibility.

Unfortunately I lack even the basics of anything other than web development so I can't really help with it, but would love to see an updated app, or even signs of a change.

**Comment by julianbrasse** [comment]
Ok I gotta apologize as I did just realize the stupidity behind my statement complaining about the outdated popcorntime mobile app, when the desktop version hasn't been updated for a year. Sad to see a great torrent viewer loose contributers :/

**Comment by dutchy1001** [comment]
@JulianBrasse 
the official release hasn't indeed been updated for a good while, this does not mean the development branch is still in full swing.
As we are waiting to make a new official release (which isn't far off) you can still get updated versions from [here](https://github.com/popcorn-official/popcorn-desktop/actions). As you can see this is just over a week old.
Many issue's and features have been added since the last official update.

**Comment by merseyV** [comment]
@JulianBrasse 
> ... when the desktop version hasn't been updated for a year. Sad to see a great torrent viewer loose contributers :/

I think you might have missed something: [**193 commits from the "Master" release?**](https://github.com/popcorn-official/popcorn-desktop/compare/master...development).

Try not upsetting our @ his latest [**"stress check-up"**](https://www.youtube-nocookie.com/embed/p6BEdKTGhNg?playlist=p6BEdKTGhNg&autoplay=1&iv_load_policy=3&loop=0&start=) didn't go well?

**Comment by julianbrasse** [comment]
@dutchy1001 and @merseyV 

Whoops y'all are absolutely right I in fact seem to have done a stupid. My bad totally didn't see those commits which is on me. (Just wanted to talk about the android app actually 🥺)

Anyway keep doing a great job :)

**Comment by merseyV** [comment]
Subreddit is a pain in the proverbial ... they've suspended my account. Tried a "spare account" and they suspended that too! :D 
.... never liked them, anyway - they can stick it where the sun doesn't shine!!

If you need me to test something - send up the mersey-signal: `@merseyV`.  (Other than that I'll just follow the git.)

**Comment by dutchy1001** [comment]
Might need to create a room on slack then to have fun

**Comment by merseyV** [comment]
>Might need to create a room on slack then to have fun

Nice try! 

There's no way I'm getting locked into a room with you lot!! 🤣 🤣 🤣

**Comment by dutchy1001** [comment]
never knew slack has cam options, besides that, I don't even have a cam.

**Comment by dutchy1001** [comment]
> personally if I ask him one more time he might (with some reason:) send people to "find" me so I stop 😄

should I start asking then??

@merseyV can you join slack.......

**Comment by merseyV** [comment]
>never knew slack has cam options .....

The mind boggles ... what are you lot getting up to? No! don't tell me .. I'd rather not Know!!! 🤣 🤣 🤣

**Comment by merseyV** [comment]
>I don't see anything in the log, none banned you

Can't reset my accounts: My e-mails are Micky and Donald @Disney.com?

**Comment by dutchy1001** [comment]
I can't even get on reddit due to my vpn

Could it be the (EDIT)🤪🤪 guy 🤣 🤣 🤣

**Comment by dutchy1001** [comment]
So back to @merseyV  joining
![father-ted-mrs-doyle](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/d01b8f2c-b289-4ca9-bce6-beb7c1136846)

**Comment by merseyV** [comment]
lol ... so is this what it's like in slack?

I'm almost tempted to rejoin Reddit ... no! I'll just fade into the GitHub and remain merseyV. :)

.. you two'd make a great vaudeville double-act? 🤣 🤣 🤣

**Comment by merseyV** [comment]
>Yes, I found support now, not scared anymore!

... pfft !!😆

**Comment by dutchy1001** [comment]
Might start an anti reddit issue then to saves the OP's mailbox

**Comment by merseyV** [comment]
Probably too late? Mine's already rammed! And I only cleaned it this morning. ☹️

**Comment by merseyV** [comment]
It's out then?  ... https://nwjs.io

**Comment by merseyV** [comment]
> Yep but we also need `https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases` :) Wont be long.. but I think we should also test it for a couple of days before we release?

Bummer! ... they come in pairs? I thought ffmpeg was a standalone patch?

.... I'd better go get that hat back, then!
