### ISSUE TITLE
Always crashing on macOS

### ISSUE THREAD

**Issue by albertputinjobs** [popcorntime/popcorntime#2842]
I am attaching a crash report pls check macOS Sonoma
[Untitled 2.docx](https://github.com/popcorn-official/popcorn-desktop/files/13998553/Untitled.2.docx)

**Comment by merseyV** [comment]
@albertputinjobs 

Which version are you using: The "official build" from the "releases link" or the 'New Build' from GitHub?

**Comment by merseyV** [comment]
@albertputinjobs 
Which version are you using: The "official build" from the "Releases" link or the 'New Build' from Actions/Workflows ... you didn't say?

M1 Mac requires the new updated NW.js 0.82.0 version: The "official build" uses old NW.js 0.44.5. Will be fixed with an 0.4.10 release (sometime soon). If you want, download pre-release version from: [ here!](https://github.com/popcorn-official/popcorn-desktop/actions/runs/7559071395)

You will need to sign-in (and sign-up) to GitHub for downloading option ... osx-0.82.0 from the  'Artefacts'.

**Comment by albertputinjobs** [comment]
.pkg didn't work, but the zip file worked

**Comment by albertputinjobs** [comment]
image loading is slow

**Comment by merseyV** [comment]
@albertputinjobs 
>.pkg didn't work, but the zip file worked

Yeah, never works! Stick with .zip.

>image loading is slow

Not sure what you mean, there. If it's the Popcorntime (app) icon bouncing in the dock for a minute, or so? That's normal (for me) when first opening a new download. Should get less after a few starts (mine settles to about 6 bounces).

... unless you're referring to something else.

**Comment by albertputinjobs** [comment]
movie images loaded faster with the prev version

**Comment by merseyV** [comment]
@albertputinjobs 

 >movie images loaded faster with the prev version

If you mean 0.4.9 (official) release, I haven't used it for a while (crashing?). However, I tried both on my MBPro (and disregarding the crashes) .. the "official" release is definitely faster opening, to the default window. I'd say (roughly) 4s compared to 8s.

So, not sure why? - that would be something for a Dev to explain (I'm just a user). It doesn't outweigh the crashing on launch, for me (I can live with it).

If you want a definitive answer, you can always raise it as a new issue - if you want?

**Comment by albertputinjobs** [comment]
How do I download the latest artifact can u just post it here ?

**Comment by merseyV** [comment]
>How do I download the latest artifact can u just post it here ?

[Here!!](https://github.com/popcorn-official/popcorn-desktop/releases) ... these are the latest releases, there have been no Dev builds (Actions/workflow runs), since.

**Comment by albertputinjobs** [comment]
latest build 0.5.1 also crashing but your version 0.82.0 never crashed

**Comment by merseyV** [comment]
>latest build 0.5.1 also crashing

I can't use that with Mac Silicon, either ... crashes for me too. Luckily there's now an Arm64 version  - so not an issue for me going forward. 

You're a macIntel user - if I remember right? Just stick with 0.5.0 release as that worked ok, for you before? 0.5.0 osx64 used to work on macSilicon - through Rosetta 2. Obviously something changed with the new 0.86.0 runtime release, that now affects both of us.

**Comment by merseyV** [comment]
>latest build 0.5.1 also crashing

I can't use that with Mac Silicon, either ... crashes for me too. Luckily there's an Arm64 version  - so not an issue for me going forward. 

You're a macIntel user - if I remember right? Just stick with 0.5.0 release as that worked ok for you, before? 0.5.0 osx64 works with macSilicon, through Rosetta 2. Obviously something changed with the new 0.86.0 runtime release, that now affects both of us. I can't test it any more?
