### ISSUE TITLE
Exiting PT 0.3.10 crashes every time

### ISSUE THREAD

**Issue by ChristopheCVB** [popcorntime/popcorntime#285]
#### Operating System Version:
OS X 10.11.6

#### Popcorn Time Version:
0.3.10

#### Download date:
Today

#### Expected Behaviour
Quit without crashing

#### Actual Behaviour
Every time I hit Cmd+Q, the app crashes

#### Steps to reproduce the behaviour

1. Open Popcorn Time
2. Quit Popcorn Time

[pt.txt](https://github.com/popcorn-official/popcorn-desktop/files/562761/pt.txt)

**Comment by team-pct** [comment]
NWJS related , if you Disable frame you won't have this issue on MAC

**Comment by thewoz** [comment]
Why you don't official release the new version?
