### ISSUE TITLE
Integrate with Jackett

### ISSUE THREAD

**Issue by 9acca9** [popcorntime/popcorntime#2859]
I like to see movies not some well know. 
For example https://en.wikipedia.org/wiki/Female_Prisoner_701:_Scorpion
I see this just a few days ago without problem with a torrent.
You dont find this movie in popcorntime.

So, it will be nice have the possibility to integrate with jackett, so, if it is not found in Popcorntime, the search return the jackett responses.

Thanks!

edit: mmmm, i noticed that if i search for "sasori" the movie appears. but anyway, i think the idea is good.

**Comment by dutchy1001** [comment]
PCT is depended on API's. If a movie isn't known to the API then it will not show up in the lists. 
For that reason the torrent option is added.
I'ts always better to search for a movie with the original name.
