### ISSUE TITLE
Release a new version its been 2 years... all u do is commits

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#2862]
why?

**Comment by dutchy1001** [comment]
Concidering there is no website anymore due to takedowns it really doesn't matter. Everyone that knows how Github works can get the updated versions.

Feel free to discuse further here but closing this topic as it's not an issue.

**Comment by merseyV** [comment]
Latest 0.84.0 (nightly build) doesn't look promising if this quote from [nwjs](https://github.com/nwjs/nw.js/issues/8163#issuecomment-1927238212) applies to us?

**Comment by merseyV** [comment]
If tripl3inf [comment](https://github.com/nwjs/nw.js/issues/8163) about 0.84.0 (nightly build) is correct, maybe it's time for the guys to ramp up production ... with 0.82.0?

**Comment by fisforfaheem** [comment]
i just want .exe or .dmg files

**Comment by dutchy1001** [comment]
Just go [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/7791403141) then and dl the version you want (the 0.82 of each OS is what you need).

**Comment by fisforfaheem** [comment]
This link should be given i the homepage( github repo)

**Comment by dutchy1001** [comment]
> This link should be given i the homepage( github repo)

this link will change every time a new build has been made, no point to add it to the "homepage",
but the action link is there.

**Comment by merseyV** [comment]
>This link should be given i the homepage( github repo)

This is the homepage repo for: **https://github.com/popcorn-official/popcorn-desktop**

The link for "latest Dev build" is there .... under Install?

**Comment by merseyV** [comment]
Not needed anymore (I guess) but [0.84.0 ffmpeg ](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases) prebuilt is out.

**Comment by merseyV** [comment]
@dutchy1001  when you've got a minute: can you do a Torrent Collection search. Anything will do .. I just wanted to see how many of the sites respond, for you? I'm already assuming SolidTorrents won't ... it seems to be down?

Thanks!!

**Comment by merseyV** [comment]
*"The world is changed. I feel it in the water. I feel it in the earth. I smell it in the air."*
*"Much that once was - is lost, for none now remember it."* 
*"It began with the forging of the official release."*

*"In the Land of GitHub, in the Fires of Code, the Dark Devs forged in secret"*
*"A Master App to surpass all others. And into this app they poured, their guile, their dark arts,"*
*"and the will to dominate all Torrents .... One App to rule them all, and in the darkness find them."*

**.... version 0.5.0**

**Comment by dutchy1001** [comment]
@merseyV 
I've answerd your request (with screenshot) for checking the torrent collection search but for some reason their gone (Am I going mad??) PS dont answer that 😁

Search only gave me result back from 1 priovider (not sure mention them is the reason it's gone), 2 other providers had 0 result

**Comment by merseyV** [comment]
@dutchy1001 Thanks for that! I thought that earlier thread might have driven it out of your mind! (lol).

I've been getting just Pirate Bay so, that kinda fits? 1337x and galaxytorrents take turns or both don't turn up? Can Captcha's interfere do you think ... I visited their websites on different servers (VPN) and a captcha appeared nearly every time?

**Comment by dutchy1001** [comment]
@merseyV 
galaxytorrents gave me 1 torrent on their site, after that blank page no captcha either
1337 get to main page choose something but then "This site can’t be reached" (few different vpn's)
nyaa is to confusing

non of them gave me a captcha

**Comment by merseyV** [comment]
Just tried again:

<img width="1483" alt="Torrent Collection" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/e6c1efd6-27c0-4638-8eed-4d47b7d88d4e">

Back to normal ... so maybe not related to my captchas in browser, then. Just a coincidence. Solidtorrents is definitely down atm?
