### ISSUE TITLE
And the covers are not displayed, please return them.

### ISSUE THREAD

**Issue by Podberezovik34** [popcorntime/popcorntime#2866]
And the covers are not displayed, please return them.

**Comment by Ravshanovich** [comment]
It's very sad to choose films without covers. Please fix this error.

**Comment by dutchy1001** [comment]
I'm not sure what you mean with "covers are not displayed", could you make a screenshot and post it here. 
I've not seen covers not displayed in my lists.

There was an issue with some api's but if you have the setting "ticked" to "Automatically update the API server URLs" then it should fix itself (Settings > API Server(s)) .  You can also manual click on the update button next to it.

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/3c384066-5064-4c8b-8e21-7b1583307534)

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/ec7dffb3-8572-43d7-925b-436208d72597)

**Comment by dutchy1001** [comment]
@Ravshanovich 
what version are you using?
When was your last update?

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/bd035ba4-859a-4189-a35c-9d4743c4106c)

**Comment by dutchy1001** [comment]
right, think you might need an updated version from [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/7838380594) choose the right (0.82.0) file for your system. 
After install plz let me know.

**Comment by Ravshanovich** [comment]
There is no way to download 700mb of speed at all, the result is in 7 hours.   Is there no other server?

**Comment by dutchy1001** [comment]
not sure what else you can do than to update first to a new version.

**Comment by Ravshanovich** [comment]
wget https://github.com/popcorn-official/popcorn-desktop/actions/runs/7838380594/artifacts/1232085807
--2024-02-09 20:11:27--  https://github.com/popcorn-official/popcorn-desktop/actions/runs/7838380594/artifacts/1232085807
Recognized github.com (github.com )... 140.82.121.4
Connections to github.com (github.com )|140.82.121.4|:443... connection is established.
The HTTP request has been sent. Waiting for a response... 307 Temporary Redirect
Address: https://github.com/popcorn-official/popcorn-desktop/suites/20594954382/artifacts/1232085807 [transition]
--2024-02-09 20:11:28--  https://github.com/popcorn-official/popcorn-desktop/suites/20594954382/artifacts/1232085807
Reusing the connection with github.com:443.
HTTP request has been sent. Waiting for a response... 404 Not Found
2024-02-09 20:11:28 ERROR 404: Not Found.

**Comment by Ravshanovich** [comment]
wget https://github.com/popcorn-official/popcorn-desktop/actions/runs/7838380594/artifacts/1232085807
--2024-02-09 20:11:27--  https://github.com/popcorn-official/popcorn-desktop/actions/runs/7838380594/artifacts/1232085807
Recognized github.com (github.com )... 140.82.121.4
Connections to github.com (github.com )|140.82.121.4|:443... connection is established.
The HTTP request has been sent. Waiting for a response... 307 Temporary Redirect
Address: https://github.com/popcorn-official/popcorn-desktop/suites/20594954382/artifacts/1232085807 [transition]
--2024-02-09 20:11:28--  https://github.com/popcorn-official/popcorn-desktop/suites/20594954382/artifacts/1232085807
Reusing the connection with github.com:443.
HTTP request has been sent. Waiting for a response... 404 Not Found
2024-02-09 20:11:28 ERROR 404: Not Found.

**Comment by Ravshanovich** [comment]
My provider's speed is good, but github does not allow me to download quickly.

**Comment by dutchy1001** [comment]
Git is slow for me to ATM, my normal downloads are fine (maybe try different location with your VPN). 
This is out of our hands but an update is needed to fix your issue.

**Comment by Ravshanovich** [comment]
Understood.  I keep trying to download the archive.

**Comment by merseyV** [comment]
I've just downloaded in about 8 minutes ... are you using a VPN? I turn it off before downloading?

**Comment by Ravshanovich** [comment]
Yes, I disabled the vpn

**Comment by dutchy1001** [comment]
with my vpn disabled it's done in less then 4 minutes.
My normal dl's (nzb's)are not that much effected by my VPN, weird

**Comment by merseyV** [comment]
@dutchy1001  ... show off ! :P

**Comment by Ravshanovich** [comment]
I'm trying with and without vpn. The download is interrupted

**Comment by merseyV** [comment]
>I can download all 6 packages simultaneously in 3-4 minutes.

I hate you!!! 😆

**Comment by merseyV** [comment]
> And it stuck with me.. :p Now I do it every couple of builds as a backup.., download all of them, mass upload to mega, you never know it will come in handy, again..

I haven't forgot? I still use it ... just don't advertise the fact in case everyone jumps in and "breaks it" 
... mum's the word? ( you might have to look that up :)

( see someone's already looking? :)

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/2774e635-b5d7-4645-9f75-6d1aab651a6b)
This archive?

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/5f15181e-de9d-4812-9cff-73896c0952c9)
:(

**Comment by dutchy1001** [comment]
plz go to settings and on top click the "info" icon. on your right bottom you will see version numbers... plz post those to see if the update worked.

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/1a7ac6bc-620b-4e81-bc1a-b5c47d7e1f8f)

**Comment by Ravshanovich** [comment]
No

**Comment by dutchy1001** [comment]
do you got any other device to test it on? (windows/ mac)

**Comment by Ravshanovich** [comment]
Windows

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/e1939c19-f43a-4769-a074-6467d8bb68de)

**Comment by merseyV** [comment]
> > I still use it ...
> 
> lol why?

I meant: I still check (now and then) to see if it's still there (and updated :) ... It's my precious!! :D

**Comment by Ravshanovich** [comment]
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/a9ebd491-9f4c-4c49-8345-f21a24cffb28)
hooray

**Comment by dutchy1001** [comment]
so are the new API's not accesable everywhere then?

**Comment by Ravshanovich** [comment]
Thanks

**Comment by dutchy1001** [comment]
> you know he took his blanket and went back to reddit..

he got his blanket, we got alcohol🍺🍻🥂🍷

**Comment by dutchy1001** [comment]
how about we ignore @merseyV till he gives in..
![father-ted-mrs-doyle](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/76277e13-4099-41a8-a3d2-676b49019efb)

**Comment by merseyV** [comment]
lol ... I'm gone!!!

**Comment by Ravshanovich** [comment]
The covers appeared, which is good, but now movies can only be watched in the original voiceover, the translation is gone :(

**Comment by dutchy1001** [comment]
It seems that YTS doesn't support different audio tracks, so only original will be available

**Comment by Ravshanovich** [comment]
Is there any way to fix this? Or is it also out of your control?

**Comment by dutchy1001** [comment]
All API's are out of our control, just a matter of finding the "better" ones to use.
have you tried your vpn to different countries?

**Comment by Ravshanovich** [comment]
I'm not particularly gifted to find it myself.

**Comment by dutchy1001** [comment]
same here unfortunatelly

**Comment by Ravshanovich** [comment]
Thank you, I will use it without covers

**Comment by dutchy1001** [comment]
so I presume it still works but without the covers then to watch a movie/serie?

**Comment by Ravshanovich** [comment]
Yes, translations work, but without covers

**Comment by dutchy1001** [comment]
Atleast you can watch then, this issue will be looked into by our (wonderful) devs 😁

I'm off now laters

**Comment by Ravshanovich** [comment]
ОК

**Comment by merseyV** [comment]
[**👀**](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/14326196-a0f6-4bf7-b1f7-f953a81d8893) .... looks quiet, now?

**Comment by Ravshanovich** [comment]
> Btw did you get a recaptcha or something when trying to view the image link I send above?
No


> Also.. when you first start the app and the images don't load, what error do you get in the console (F12)? Should be a repeated one, 50+ times

![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/fb4cd672-8eb4-487d-ba99-0c70536c25b7)

**Comment by Ravshanovich** [comment]
> Btw did you get a recaptcha or something when trying to view the image link I send above?

No



> Also.. when you first start the app and the images don't load, what error do you get in the console (F12)? Should be a repeated one, 50+ times

![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/f6c87663-9c55-4b0f-88ce-041052c3faf7)

**Comment by Ravshanovich** [comment]
> do you got any other device to test it on? (windows/ mac) 


Everything works on windows covers and supports different sound tracks.
![photo_2024-02-10_07-28-24 (3)](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/5d6aa7bf-c183-4c46-9878-5b89af527237)
![photo_2024-02-10_07-31-10](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/66869376-263e-4cec-b4e0-307d1079ce22)
![photo_2024-02-10_07-28-24](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/528756aa-0611-49fe-9b9d-c650c7459f3e)
![photo_2024-02-10_07-28-24 (2)](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/b888a944-3eb7-43a8-a8dd-6a04e833480f)
But it doesn't work on Linux. :(

**Comment by ivan1986** [comment]
@Ravshanovich images not load issue may be if you live in russia, tmdb block requests

**Comment by Ravshanovich** [comment]
@ivan1986 This works on Windows, but not on Linux.

**Comment by Ravshanovich** [comment]
> изображения не загружаются, проблема может быть в том, что если вы живете в России, tmdb блокирует запросы

This works on Windows, but not on Linux.

**Comment by ivan1986** [comment]
@Ravshanovich i use linux and images perfect load for me, on last release and on last build, in deb and tar.gz and on arch linux too
Look by error - it's network issue, same issue for me, when i turn off vpn and tmdb block me.

**Comment by Ravshanovich** [comment]
@ivan1986 
Here's what I found online:
Usually, resources are blocked at the level of firewalls and similar solutions. But The Movie Database (IMDB) decided to act more cunningly and blocked access to its resource for the Russian segment of the Internet at the DNS level. The solution is very simple. You need to register on the server where the request to this service is being made api.themoviedb.org other DNS servers. Here it should be noted that Yandex DNS, Google and CloudFire not suitable because they all use the same source DNS. We need an alternative one. I have been using Adguard for a long time and therefore immediately chose this DNS provider on my server. " I'll try it myself now.
And it works  ;)

**Comment by Ravshanovich** [comment]
@ivan1986 
 That is, it was necessary to change the default DNS
There are covers and different voiceovers.
![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/82e439be-b6e3-4b75-bd2c-add398897fe4)

![image](https://github.com/popcorn-official/popcorn-desktop/assets/43450281/29f6109f-59f1-469e-ae52-aa0afb709aa9)

**Comment by Ravshanovich** [comment]
The case is closed. Thank you all.
