### ISSUE TITLE
Correct API server address

### ISSUE THREAD

**Issue by jimsuev** [popcorntime/popcorntime#2873]
Followed the link to update to newest version, after completion, message "The remote movies/shows API failed to respond, please check popcornsayzvav2ouwl2iussmgcmfw6wuat7gnoldwfjupfcea5tnyad.onion Link does not work. How do I get the correct API server address's?

**Comment by ivan1986** [comment]
this is the address of the tor server, you need to install a proxy separately, default servers are automatically updated

**Comment by jimsuev** [comment]
I am a casual computer user, I have no idea how to install a proxy.
________________________________

**Comment by ivan1986** [comment]
you not need install proxy, just use default servers
just clean this options

**Comment by kiahwilson99-commits** [comment]
> Followed the link to update to newest version, after completion, message "The remote movies/shows API failed to respond, please check popcornsayzvav2ouwl2iussmgcmfw6wuat7gnoldwfjupfcea5tnyad.onion Link does not work. How do I get the correct API server address's?

**Comment by merseyV** [comment]
>How do I get the correct API server address's?

copy/paste: `https://fusme.link/,https://jfper.link/,https://uxert.link/,https://yrkde.link/` (for movies, series, anime)

`https://yts.gg/` for movies only (if you don't like the excessive Ru (none English) content offered-up by  the Popcorntime movie API)

For series, you're best alternative is to use the 'Torrent Collection' search (3 line icon, top right). Basically these days it's a TPBay.org search .. but you'll get a wider choice in various bitrates for most searches. (Easy playback in the same window.) Obviously, you can also use it for movies (if you prefer?).

**n.b.** 
The app no longer auto-updates the (default) API's, any more.
