### ISSUE TITLE
Using mesh network as server api

### ISSUE THREAD

**Issue by immartian** [popcorntime/popcorntime#2874]
It'd be very hard to maintain a domain-name-reliant service if there are constant crackdowns. 
I would suggest PT's using #YggdrasiNetwork as service API providers and distribute the api's to all clients. 

FYI. https://github.com/yggdrasil-network/yggdrasil-go

**Comment by ivan1986** [comment]
We already have a tor configured in case of loss of domains, but for a typical user this is very difficult - go to reddit and see - there are a lot of requests for what to do here and even the current interface for them is very complicated.
What's the point of changing tor to yggdrasil if you need to install a separate client in both places? Now we have automatic address updating from the torrent network and all users who didn't mess around with the settings received the update and everything works.
When it will be possible to add it simply by installing an NPM package without configuring a separate proxy service, then it will make sense to enable it.
