### ISSUE TITLE
Movies Fail to load!

### ISSUE THREAD

**Issue by Not-Chur-Architect** [popcorntime/popcorntime#2875]
Operating System Version:
Windows 11

Popcorn Time Version:
0.5.0

Download date:
2/13/24

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.5.0

#### Expected Behavior
Play the movie or tv show Episode. 

#### Actual Behavior

first, the "watch now" button freezes for around 45 to 60 seconds, and then the program will stall at the "connecting" page, failing to load any content.

#### Steps to reproduce the behavior
1. Open Popcorn time
2. Pick a movie
3. try to play a movie with the "play now" button
4. Fail to play movie

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image_2024-02-13_201116218](https://github.com/popcorn-official/popcorn-desktop/assets/1156512/27e083c7-f01f-4e23-9baa-53a4470fd07d)
<img width="1527" alt="image" src="https://github.com/popcorn-official/popcorn-desktop/assets/1156512/e4e486da-1f20-451d-8298-e9431a299d91">

**Comment by dutchy1001** [comment]
you can also try to click the "more..." button and choose a different torrent. In the top right corner you see a "Gray (unknown healt, Red (bad healt) or Green (good healt)" dot. This is how you see if the "default"  movie is available through those torrent sites. Movies from the "more..." button do not update the coloured dot.
