### ISSUE TITLE
No sound with the Popcorn player

### ISSUE THREAD

**Issue by th3v4n** [popcorntime/popcorntime#2876]
Operating System Version: Windows 10/11

Popcorn Time Version: 4.9 & 5.0

Download date: 02.12.24

Download url: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.0/Popcorn-Time-0.5.0-win64-Setup.exe

#### Expected Behaviour

Sound

#### Actual Behaviour

No sound

#### Steps to reproduce the behaviour

1. Open Popcorn Time
2. Stream a show (any show) using the built-in player.
3. No sound.

It seems be across the board on multiple devices ever since updating to 5.0. If I set it to an external player (MPC-BE in this case) the sound is fine.
Was surprised it hadn't already been reported! Can't just be me can it?

**Comment by merseyV** [comment]
@th3v4n 
Try the Popcorn-Time-0.5.0-win64-0.44.5-Setup.exe version .. it has more audio codecs (same as previous 0.4.9 official release).

You're using the Newer NW.js build which doesn't have the Dolby/licensed codecs. It's known and is unlikely to be fixed any time soon. Relies on 3rd party binaries.

Or you can carry on using your own alternative player?

There's also general support at [**the subreddit**](https://www.reddit.com/r/PopCornTimeApp/)

**https://www.reddit.com/r/PopCornTimeApp/comments/17sged2/newest_update_no_sound/**

**Comment by alejandrocastrejon** [comment]
I have the same issue with Popcorn-Time-0.5.0-win64-Setup.exe installer so 

1. I download  Popcorn-Time-0.5.0-win64-0.44.5-Setup.exe 
2. Install over 
3. RESTART 

windows and WORKS fine!

**Comment by th3v4n** [comment]
> @th3v4n Try the Popcorn-Time-0.5.0-win64-0.44.5-Setup.exe version .. it has more audio codecs (same as previous 0.4.9 official release).
> 
> You're using the Newer NW.js build which doesn't have the Dolby/licensed codecs. It's known and is unlikely to be fixed any time soon. Relies on 3rd party binaries.
> 
> Or you can carry on using your own alternative player?
> 
> There's also general support at [**the subreddit**](https://www.reddit.com/r/PopCornTimeApp/)
> 
> **https://www.reddit.com/r/PopCornTimeApp/comments/17sged2/newest_update_no_sound/**

Yeah, I'm installing now. Assume it will fix it. Thanks!
I was wondering what the difference was in the two releases though and it didn't seem all that clear to me (and I'm a pretty big Github geek lol).
