### ISSUE TITLE
Put back the subtitles dropdown

### ISSUE THREAD

**Issue by Sufrostico** [popcorntime/popcorntime#288]
Operating System Version:
Linux

Popcorn Time Version:
0.3.10

Download date:
31 Oct, 2016

#### Expected Behaviour
Get a drop down for subtitles, I usually change the subtitles between Spanish/English/French/Portuguese  multiple times depending on the movie.

#### Actual Behavior
Subtitles according to the language of the application

**Comment by JimiC** [comment]
There was no point in maintaining that option. You can select your preferred subs language once the movie starts.
