### ISSUE TITLE
NWJS helper process memory leak

### ISSUE THREAD

**Issue by jswhisperer** [popcorntime/popcorntime#2880]
NWJS helper process got up to 438gb of memory 
I got the out put here https://gist.github.com/gregpalaci/b6693e1189d20bf10da2867dc35a55f3

I'm on macos m1 14.3 (23D56)
and Popcorn-Time-0.5.0-osxarm64

Thanks for solving this https://github.com/Ecks1337/RyuSAK/issues/37#issuecomment-1545289902
I figgured that out before I saw the solve 😆 another step to try on macos btw is hitting control click when opening

Downloaded today, from releases.

Homebrew install is currently broken btw I was working on a patch mostly just hacking it for myself https://github.com/gregpalaci/popcorn-desktop/blob/development/casks/popcorn-time.rb

not crash my system

just opening it sometimes

These numbers seem resonable now but were over 400gb before 
<img width="442" alt="image" src="https://github.com/popcorn-official/popcorn-desktop/assets/1177690/83e58dd3-f751-4ff4-903f-752128dfc3c8">

**Comment by jswhisperer** [comment]
I think this CPU is high too for the nwjs helper 
![image](https://github.com/popcorn-official/popcorn-desktop/assets/1177690/365e1800-9f8b-4a58-804b-c9605066e7de)

Only devtools error I saw was about trakt getting a 401, I reset my connection to it

**Comment by jswhisperer** [comment]
Not sure there's will help because I need to process up NW.js, but in case they are helpful 

https://www.npmjs.com/package/toobusy-js
and maybe createProcessFamily they are quite stale libraries though 
[from this security sheet](https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#monitor-the-event-loop)

This library looks iinteresting for figuring out what process is blocked maybe https://github.com/adamrecsko/block-event

**Comment by merseyV** [comment]
I'm using Popcorntime arm64 (beta) not seeing any memory leak ... what have you done to it and why?

<img width="810" alt="Downloading" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/8fdbb3f8-6077-4809-83cb-774f280c6c92">

**Comment by jswhisperer** [comment]
Ah thanks roger that!
