### ISSUE TITLE
0.5.0 compile failure

### ISSUE THREAD

**Issue by faveoled** [popcorntime/popcorntime#2889]
```
$ yarn install --ignore-engines
yarn install v1.22.19
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/gkatsev/vtt.js.git
Directory: /home/user/Downloads/popcorn-desktop-0.5.0
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Ubuntu 22.04. Any ideas?

**Comment by Franck78** [comment]
same output here ;)
registering to the bug

**For info only:
usually, I decompress the built package in /opt/popX.X and go ;)**

This time, it requires GLIBC 2.25 and I'm under GLIBC2.23 (opensuse need update).
I just wanted to see I building on my 'old' system was sufficient.

**Comment by Franck78** [comment]
maybe renamed to 'webvtt'

https://github.com/gkatsev/webvtt

**Comment by faveoled** [comment]
The workaround would likely look similar to this:

https://github.com/popcorn-official/popcorn-desktop/blob/dee27a961e88f8e55f5c3a0eb4df40dfc0ca93b1/.github/workflows/build.yml#L31C1-L35C1

**Comment by vageliskatsiotis** [comment]
In my case, I get the error for other package

 `yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/adam-lynch/node-temp.git
Directory: /home/vagelis/GitRepos/popcorn-desktop
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`
Found workaround for this. Download the required node module package manually (or search the node_modules directory, it might be there already) and remove the fault entry from yarn.lock file. Build ok after that.

**Comment by Franck78** [comment]
The error seems (according to error message) related to git wanting to use a correctly generated ssh setup
https://stackoverflow.com/questions/23546865/how-to-configure-command-line-git-to-use-ssh-key

**Comment by squgeim** [comment]
This happens when you use Git to connect to Github for the first time.

The fix is to manually run the following command and allow connecting to Github.

```
git ls-remote --tags --heads ssh://git@github.com/gkatsev/vtt.js.git
```

**Comment by cheof** [comment]
https://github.com/yarnpkg/yarn/issues/3303#issuecomment-529343139 

you need remove yarn.lock which is in the source 

rm -f yarn.lock
