### ISSUE TITLE
Airplay not streaming

### ISSUE THREAD

**Issue by dthoro2** [popcorntime/popcorntime#289]
Operating System Version:
OS X 10.11

Popcorn Time Version:
3.10

Download date:
10/31/16

#### Expected Behaviour
Expected Airplay to stream to Apple TV 3rd gen
...

#### Actual Behaviour
The app says it is streaming to Apple TV, but no streaming happens

#### Steps to reproduce the behaviour

1. ... Attempt to Airplay to Apple TV 3rd Gen

**Comment by du-song** [comment]
same on 4th gen: new Apple TV

**Comment by team-pct** [comment]
fixed on a1de8a4da40e553e8617bac990dc0dc1064e8fab
