### ISSUE TITLE
Add the ability to customize BitTorrent Tracker lists。

### ISSUE THREAD

**Issue by maxwell-feng** [popcorntime/popcorntime#2894]
I hope that the function of customizing the BitTorrent Tracker list can be added, as many torrents cannot be found using software search engines.

**Comment by maxwell-feng** [comment]
Where can I add it?

**Comment by merseyV** [comment]
I'm close to my (runaway-peers) all-time record (304, long time ago) on standard settings:

<img width="827" alt="Peers" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/bbf1d17b-e112-4a04-bb17-b146ffa6dee5">



The only difference being (new) Popcorntime download doesn't freeze and crash at <50% of download.  It sails through to the end, indomitably!! .... beat that??

**Comment by merseyV** [comment]
Don't think anyone's going to beat this!  😃  

<img width="735" alt="Peers - 404" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/21026979-9e93-447c-8326-d390217045db">

New, all-time record!!!
