### ISSUE TITLE
AVG Antivirus free mark the file as infected of FileRepMalware

### ISSUE THREAD

**Issue by BugliL** [popcorntime/popcorntime#2902]
Operating System Version: Windows 11

Popcorn Time Version: v0.5.0 0.44.5-Setup

Download date: 2024-02-25

Download url: https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.0/Popcorn-Time-0.5.0-win64-0.44.5-Setup.exe

#### Expected Behaviour
The file is not reported as infected and the software install correctly

#### Actual Behaviour
AVG Antivirus free mark the file as infected of FileRepMalware

#### Steps to reproduce the behaviour

1. Download and install AVG Antivirus Free
2. Download the exe file
3. Try to run it as admin to install

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
It won't just start and crashes with a message that "could not edit files", than the AVG screen appears

**Comment by dutchy1001** [comment]
this is a false positive due to what you can watch with it.

**Comment by BugliL** [comment]
If is always the same thing I will wait for the antivirus update and try to reinstall it again.

**Comment by merseyV** [comment]
Nice detail in this online antivirus check:

![Popcorn-Time-0 5 0-win64-0 44 5-Setup](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/79efbf19-416e-404c-aa31-80981ed3cb0d)
