### ISSUE TITLE
Enforce VPN connexion or warn user

### ISSUE THREAD

**Issue by cookkydn** [popcorntime/popcorntime#2905]
**Is your feature request related to a problem? Please describe.**
I just received a warning email from the **ARCOM** (french audiovisual regulation authority) telling me they caught me using a torrent to download a protected movie (dune) and that I could be fined 1500€ for that, and this was the first movie I downloaded from your app.

**Describe the idea you'd like**
The only way I think about to prevent being caught is to use a VPN, so when the user is not using one it would be nice to display a warning message

**Describe alternatives you've considered**
A more brutal way is to enforce having a vpn connexion, but it's maybe too restrictive

**Additional context**
here is a screenshot of the mail (in french)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/57495614/a00a45b2-817a-42af-a71d-642173a34494)

**Comment by merseyV** [comment]
I don't think it's something the devs should want to add to the basic app. It might strip the only fig-leaf that is left, to cover their ... exposure! (plausible deniability).

When you use anything to freely download copyrighted content, it always has the potential to come back and bite you! It's not like piracy is a new/novel phenomena .. the consequences (however slim) are widely known and discussed. Even if you display a warning message, or people like yourself share their experience ...  problem is, the majority think it won't happen to them? And statistically speaking, the odds agree!

We (regulars) always recommend using a VPN, whenever the opportunity presents itself. And if you want to share your experience -  maybe, post it on the subreddit? They need it more!!

 I definitely wouldn't do it with a permanent notice connected to the  app ... but that kind of decision belongs to the devs, well beyond my pay-grade?
