### ISSUE TITLE
Genre filter not working

### ISSUE THREAD

**Issue by heathcliffr** [popcorntime/popcorntime#291]
Operating System Version:
Windows 10, Android 4

Popcorn Time Version:
2.9 for Android, 3.10 iOS

Download date:
Oct 31

#### Expected Behaviour
Categorize by genre
...

#### Actual Behaviour
Nothing happens when you click on genre tabs
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
This is the desktop version, not the android version and we do not have an iOS version.

**Comment by heathcliffr** [comment]
While I wasn't concentrating when I wrote the comment, (including iOS), the Android 2.9 beta version on my Galaxy Note 3 which replaced the previous version (2.7?) no longer filters genres.  When you click the tabs, eg Film Noir, nothing happens.  Similarly, on the desktop version, 3.10, clicking on Film Noir says "No movies found."
