### ISSUE TITLE
Faulty fullscreen subtitles

### ISSUE THREAD

**Issue by mummra** [popcorntime/popcorntime#2911]
When in fullscreen mode and the trackbar is hidden one-liner subtitles don't show up

Operating System Version:
Windows 10 Pro

Popcorn Time Version:
0.5.0

Download date:
2024-02-20

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.0/Popcorn-Time-0.5.0-win64-Setup.exe

It doesn't show the line of text that is in the sub file.

#### Steps to reproduce the behaviour

1. Load Red Right Hand movie
2. Set Spanish subtitles
3. Switch to fullscreen mode
4. Go to the 1:45:28 mark
5. Once the trackbar hides at 1:45:31 the subtitle should read "¿Cómo está ella?" but it doesn't
6. It works if you exit fullscreen mode

**Comment by dutchy1001** [comment]
Subtitles are a 3rd party issue, nothing to do with PCT. 
You can try and use the "more..." button and pick an other resourse from the list;
You can try to use an external player and see if this fixes it;
Or go online and try to find an other subtitle file.

Feel free to comment any further but I'm closing this as it's not a PCT issue.

**Comment by mummra** [comment]
Is PCT in charge of showing the subtitles on top of the video? If so, it's not working correctly.
If an external player "fixes it", then PCT is not working.
If not in fullscreen mode, the subtitle is visible, so is not a problem with the subtitle file.
Closing the issue doesn't make the bug go away.

**Comment by dutchy1001** [comment]
After testing some more movies it appears that it happens to more then only the movie you mentioned.
We will look into this when our devs have the time for it.

**Comment by merseyV** [comment]
>Go to the 1:45:28 mark ... Once the trackbar hides at 1:45:31 the subtitle should read "¿Cómo está ella?" but it doesn't

Strange you'd pick something about 1 minute from the end ... but here goes. (Yes, screenshot is fullscreen).  

<img width="1680" alt="Subtitles" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/4ada5031-a073-4812-9933-0d6701bf98c4">

**Comment by dutchy1001** [comment]
@merseyV looks like is "Windows" issue (as far I know your not a windows user 😜🤪).
In full screen mode the track bar disapears (yours still showing it) that's when the subs disapear too.
I tried 2 movies were this happens, not only spanish subs but GB too.

**Comment by merseyV** [comment]
@dutchy1001 
>In full screen mode the track bar disapears (yours still showing it) that's when the subs disapear too. 

That was just me taking the screenshot? It ran perfectly (I tried it more than once) if I just  let it run through (no track 
bar)? Tried a few more ... no issue?

Chalk that one point  for Macs!! :P

n.b. I'll delete the screenshot before your GitHub's "ninja" does his shadow-work (again!) .. 🤣 🤣

**Comment by dutchy1001** [comment]
@merseyV 
> Chalk that one point for Macs!! :P

One of the only few then 😅😂🤣

to get back to an old issue:
![father-ted-mrs-doyle](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/091ce6a2-3b42-4217-8607-83d0faad1514)
you know what it means

**Comment by merseyV** [comment]
Riposte!! 😅😂🤣

![many-times-no-icegif](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/ad2fdb64-c2a8-49b8-a64d-3355ee2ff782)
