### ISSUE TITLE
Audio Not Working

### ISSUE THREAD

**Issue by billyb9999** [popcorntime/popcorntime#2916]
Audio stopped working in version 5.0 and 4.9 on Windows 10.

Tried reinstall with the same issue.

All other apps on NUC work

Movies trailer preview audio works

**Comment by dutchy1001** [comment]
This is due to the new NW.js, it missing some of the codecs. You could try the vesion from the "[old NW.js](https://popcorntimeapp.netlify.app/)" folder.
Or, you could use an external player (like VLC or SMplayer).

**Comment by billyb9999** [comment]
Hi,
Thanks, yes this fixed the problem.
