### ISSUE TITLE
Include PATH env. variable when searching for external players

### ISSUE THREAD

**Issue by teto** [popcorntime/popcorntime#2926]
#### Operating System Version:

linux/ nixos 
#### Download date:

nwjs 119.0.6045.105

#### Expected Behaviour:

First description of the issue here https://discourse.nixos.org/t/no-sound-on-popcorntime/41095/3
I had issues with audio on some videos, checked the FAQ that mentioned it was possible due to some new library and the workaround 
was to use an alternative player (until then I had no idea you could use an external player, so that was a good news :) ). 

To my surprise, popcorntime could not find my VLC player even though it was in PATH.  I digged a bit in the source code and found out that the paths are hardcoded 
https://github.com/popcorn-official/popcorn-desktop/pull/2635/files#diff-ca1b95b1c36992d38e3a83b4278a881511a4b41b529f1ebff9edc07ef7435492L236
and I assume PATH is ignored ?

I am curious as to why popcorntime seemingly ignore $PATH and if this could be changed to just look at it and remove all those hardcoded path (if people really need a player not in PATH, it's easier for them to add wrap popcorntime with a shellscript that adds to PATH the path to their player).

NB: I had no idea about this software before and it's beautiful and really impressive. Kudos to the maintainers

**Comment by teto** [comment]
that's the thing I dont understand, my understanding is that popcorntime does the opposite of what you are saying: instead of looking at what is possible in PATH, it hardcodes a lot of non-standard paths that just makes things more complex, I know no other software that hardcodes paths like that :/

**Comment by teto** [comment]
https://en.wikipedia.org/wiki/PATH_(variable) it's anvironment variable on linux/windows to tell programs where they can find other programs

**Comment by ivan1986** [comment]
hm, real, why we not search in PATH ?
reopen pls, need fix

**Comment by dutchy1001** [comment]
does it need a "bug" tag too?
