### ISSUE TITLE
"App quit unexpectedly" when quitting on macOS

### ISSUE THREAD

**Issue by nathanchapman** [popcorntime/popcorntime#293]
Operating System Version:

macOS 10.12.1

Popcorn Time Version:

0.3.10

Download date:

Just upgraded to 0.3.10 yesterday

#### Expected Behaviour

App should quit normally with CMD-Q or quitting from menu

#### Actual Behaviour

Alerts "App quit unexpectedly, report issue..."

#### Steps to reproduce the behaviour

1. Open Popcorn Time
2. Quit with CMD-Q or from menu
3. See error prompt

**Comment by team-pct** [comment]
Error generated from frame line on package.json and Related to nwjs

**Comment by kim0** [comment]
@team-pct .. why is this being closed ? if this is an upstream bug, is it at least reported there ?

**Comment by team-pct** [comment]
Hello Kim0 , i myself have MAC and from my tests changing package.json on the Ressources/app.nw
and removing frame line would fix that but again it is ugly , i will keep working on fixing it

**Comment by kim0** [comment]
Awesome!! You'll work on it, so perhaps this bug report should be re-opened

**Comment by ChristopheCVB** [comment]
It was already opened there : 
https://github.com/popcorn-official/popcorn-desktop/issues/285

**Comment by ChrisAlderson** [comment]
#388

**Comment by thewoz** [comment]
Why you don't official release the new version?

**Comment by whatthehomepod** [comment]
Found the solution! Steps to resolve:
```
git clone https://github.com/popcorn-official/popcorn-desktop.git
cd /popcorntime-desktop/
yarn && yarn gulp run
yarn gulp build
```
