### ISSUE TITLE
Genre tab on Android 2.9 and Desktop 3.10 not working

### ISSUE THREAD

**Issue by heathcliffr** [popcorntime/popcorntime#295]
Operating System Version:
Windows 10, Android 4.

Popcorn Time Version:
Android 2.9, Desktop 3.10

Download date:
October 31

#### Expected Behaviour
Previously, genre tabs showed films in their categories

#### Actual Behaviour
Clicking on Film Noir in genre on the Android yields nothing.  Bar remains grey, and doesn't click-through to another page.  Clicking Film Noir in genre on the Desktop, clicks through to "No movies found."
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/160#issuecomment-246207757

https://github.com/popcorn-official/popcorn-android/issues/20
