### ISSUE TITLE
Memory leak on version 0.5.0

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2955]
**Operating System Version:**

Windows 10 / 11

**Popcorn Time Version:**

0.5.0 (with the newest NW.js)

**Expected Behaviour:**

RAM used during downloads / uploads / seeds / etc. is allocated and used, then released.

**Actual Behaviour:**

The app uses roughly 300 MB of RAM when idle (which is ok). It doesn't fluctuate if no downloads are started.
It goes to roughly 415 MB/430 MB when downloading one new 1.6 GB file (which is also ok).
It starts to steadily climb its RAM usage even after the download is done. If the app is open for a few hours, it will easily reach 1GB RAM, even if it's idling and no other downloads start.

If you try to download 10 or 12 files at once, for instance, the RAM usage will quickly climb (which is expected), but it does never go back down again. It quickly climbs to 3 or 4GB and it steadily goes up. 

**Steps to reproduce the behaviour:**

Downloading even one 1.6 GB file will enable this behaviour. If you want to fast-track it, you can try downloading 8 or 9 files at once (and make sure they're all active) and you'll be able to see the RAM usage spike really high and never return to its original usage (and to keep climbing as well).
 
Thank you all for looking into it.

**Comment by ghost** [comment]
Hello there.

>  It quickly climbs to 3 or 4GB **and it steadily goes up.**
> (and to **keep climbing** as well).

RAM usage does not stop at 3/4 GB. It keeps climbing. Eventually the app is eating 7/8 GBs of RAM with no actual downloads happening. I understand that external components may be involved in the issue, but it's important to make this distinction here - this is not a reflection of actual usage - it's about a neverending RAM usage climb. I've had the app simply close after a while.

Thanks all.

**Comment by ghost** [comment]
I haven't. After a while (after the downloads themselves were finished), there was no upload activity either, so there should be no reason for memory to be going up (and most of it should've been reclaimed by now since the bulk of the activity was over already).

Also, I had PT configured to always delete the cached files after cleaning the Seedbox, which made cleaning it kinda impractical - but I'll gladly change this and test it again with a clean Seedbox if you believe it will help.

Thanks!

**Comment by merseyV** [comment]
>If you try to download 10 or 12 files at once, for instance, the RAM usage will quickly climb (which is expected), but it does never go back down again. It quickly climbs to 3 or 4GB and it steadily goes up.

It's down to the WebTorrent engine.  

Popcorntime was always intended to be a streaming  player .. rather than a streaming downloader. It was originally built by Federico for his mum (nice lad) ... Point, Click, Watch!!  Wasn't designed as a torrent client, per se. If used as intended - it's manageable (most users don't notice). I sometimes download the odd file, for later. But, I'd use qBittorrent for anything more serious (that's what it was made for?).  

Unless the devs can get WebTorrent 2.x.x to work with Popcorntime (not a small job, by all accounts!) ... we learn to live with it. And if you think it's bad now ... you obviously weren't around 9 mths ago?

**Comment by ghost** [comment]
> If used as intended 
> (that's what it was made for?)

Hmmmmmmmmmmmm. Heh.

Well, I had to try.

Thank you all for keeping PT alive.
