### ISSUE TITLE
"Popcorn Time" title is everywhere and app icon changed to Fish and more...

### ISSUE THREAD

**Issue by algorithm-developer** [popcorntime/popcorntime#2957]
#### Operating System Version:
Windows 11 Pro x64 b23H2

#### Popcorn Time Version:
0.5.0

#### Download date:
2024 March 23 then installed used until today without any bugs but bugs appeared then uninstalled it and downloaded same version again from official release. After install same bugs still in there. 

#### Download url:
Downloaded from official github's release:
[Popcorn-Time-0.5.0-win64-Setup.exe](https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.0/Popcorn-Time-0.5.0-win64-Setup.exe)

#### Expected Behaviour:

"Popcorn Time" title is everywhere and app icon changed to Fish and video player's toolbars are hidden while playing in fullscreen mode and not showing until pause movie even move cursor its not showing toolbar.

#### Actual Behaviour:

It must be doesn't include "Popcorn Time" title in media title
App icon must be popcorn logo
Video player's toolbar is not showing while playing media on fullscreen mode even move mouse cursor. It shows only when i pause the media via mouse1 or space button.

#### Steps to reproduce the behaviour:

1. Just open app after fetch movies you will see the titles of some media content included "Popcorn Time" in it
2. Open app and see the Logo of app from main bar there will be a Fish logo instead of Popcorn logo
3. Play any movie in fullscreen mode

#### Popcorn Time title in movie's title
![00](https://github.com/popcorn-official/popcorn-desktop/assets/17625859/eddd0242-b628-4ffc-ade0-1d4d248aad87)
![01](https://github.com/popcorn-official/popcorn-desktop/assets/17625859/9e7a6930-1845-4c51-ba70-220d4c9a8f41)
![03](https://github.com/popcorn-official/popcorn-desktop/assets/17625859/8a2260fc-c5a0-4c42-b9bf-9e6660d62971)
![04](https://github.com/popcorn-official/popcorn-desktop/assets/17625859/befeef93-7466-4701-8b32-90de5fa9684a)

#### Fish icon
![02](https://github.com/popcorn-official/popcorn-desktop/assets/17625859/556430ed-8d05-40d9-b2e4-00bcfe7452bc)

#### All bugs in this single video. But i didnt include video player bug in video because of the file size is not allowed to upload on this issue. So i cut the video for make it short and small file size.

https://github.com/popcorn-official/popcorn-desktop/assets/17625859/970b8f21-8acc-4126-9a61-7c3cf1ee9317

**Comment by merseyV** [comment]
About 8.5hrs into April ... Mongolia wins the "spot the fish" 2024 competition!

Christmas Island .. you've missed the boat again? :D

**Comment by atyrode** [comment]
Just finished watching [Reality](https://www.imdb.com/title/tt2392672/) and this had me questioning my sanity 
![harrywhat](https://github.com/popcorn-official/popcorn-desktop/assets/20166883/47cd0315-73da-4f69-8456-5b8aaeccde0e)

**Comment by merseyV** [comment]
The fish has been spotted flying over Paris? ... only 20minutes before it gets to "old Blighty!"  👀

<img width="855" alt="Screenshot 2024-04-01 at 00 01 15" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/e5fc019f-acb5-4449-8442-fa6aa7f5f0ca">

**Comment by dutchy1001** [comment]
Always makes me laugh when this happens.

Can we add something for Haloween that something pops out the screen in 3d style..... 😈😈😈

**Comment by algorithm-developer** [comment]
> Happy April Fools day! 😄
> 
> (if it bothers you you can disable it in the Settings, its the 'Celebrate various events' option in the 'User Interface' section)
> 
> EDIT: Oh as for the native player overlay issue, where it doesn't show up, download the latest dev build from the 'Actions' page, it has been fixed (#2912) but this was after 0.5.0 was released (or just wait for 0.5.1 though the dev build is perfectly good, they are not dev builds in the traditional sense..)

Oops i got it bro :D. It's just as you planned, i'm fooled haha
