### ISSUE TITLE
Bug in the subtitles, where they are?

### ISSUE THREAD

**Issue by tadahiwin** [popcorntime/popcorntime#296]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
This is already the ham time, updated to 3.10 yesterday.

#### Steps to reproduce the behaviour

1. Use version 3.9
2. upgrade to version 3.10
3. And look at that when you open a movie does not have the bar to choose the subtitle language and can not put legend in your movie.
![legend](https://cloud.githubusercontent.com/assets/23197103/19901121/1ef701f4-a04d-11e6-83ea-ffa962cc03db.png)

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/227#issuecomment-255477682
