### ISSUE TITLE
Popcorn-time.exe error when installing

### ISSUE THREAD

**Issue by ezmerelda** [popcorntime/popcorntime#297]
Operating System Version: Windows 10

Popcorn Time Version: 3.10 install

Download date: 1.11.16

#### Expected Behaviour
expected it to install 

#### Actual Behaviour
installed all but popcorn-time.exe as it wouldnt write
...

#### Steps to reproduce the behaviour
Installed as required but would not write the exe to run the program.

1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Wouldn't write ?

**Comment by pkpn** [comment]
I am experiencing the same. It gives this error: (screenshot)

I am sorry as it's in Danish I will do my best to translate:

"Error writing to file:

"Path\Popcorn-Time.exe"
Press Abort to cancel the installation.
Try Again to try writing the file again o
Ignore to ignore this file and continue"

![screenshot_17](https://cloud.githubusercontent.com/assets/7557704/19912334/047cb7c2-a09a-11e6-84aa-6e57ec96bde3.png)

I had version 3.9 installed when I got the Download to update reminder at startup.
Downloading and installing as it asked gave me 3.10 as promised. First install went fine. End of install when asked to Start Popcorn Time and/or to create a shortcut on desktop I selected both. Nothing happened except the shortcut got created. No Popcorn Time started. When trying the shortcut it returns missing link/file. Further investigations show the .exe file to be missing. Reinstalling gives the error as shown in the screenshot. (Btw. when installing prior to the error it tells me Popcorn Time is running and if I want to shut it down for the installer to continue - selected Yes. - All this even with Popcorn Time not showing either on screen or on task list)

---

EDIT:
Apparantly my Bitdefender antivirus blocked the .exe file quietly.

![screenshot_18](https://cloud.githubusercontent.com/assets/7557704/19912953/98d2c00c-a09e-11e6-98d9-4ee56d27e8dd.png)

**Comment by marcusyap** [comment]
i have the same problem. Tried many times and still the same. 

![capture-20161102-135928](https://cloud.githubusercontent.com/assets/23206819/19918271/c6b602c0-a104-11e6-8300-fa1deda008f2.png)

**Comment by ChrisRast** [comment]
Same with Avast on windows. Had to manually tell him to shut up.

**Comment by pkpn** [comment]
All of a sudden it worked fine. I guess my antivirus update must've fixed it.

**Comment by ezmerelda** [comment]
Not fixed for me yet.  tried again today without my antivirus being on.  no luck.

**Comment by marcusyap** [comment]
![poppic1](https://cloud.githubusercontent.com/assets/23206819/19990401/5be76c58-a268-11e6-805a-2f1c238bccf3.png)
![poppic2](https://cloud.githubusercontent.com/assets/23206819/19990402/5bf4a35a-a268-11e6-9b6c-116ae9652759.png)

well, without doing anything i managed to reinstall successfully.
BUT, 3.10 is pretty banged up.
Thumbnails are not showing. It is erratic. Movies and Series tab, same thing.
still can watch them just that those damn thumbnails are not showing or extremely slow to load.

Probably switch back to 3.9 ?

**Comment by VitorVRS** [comment]
I had an issues with slow loading, can you confirm if is that?
If possible can you print logs (F12)?

**Comment by pkpn** [comment]
ezmerelda: try to uninstall it and remove the folder and all files from your AppData\Local path. And then install it again without antivirus or whitelist it in your antivirus.
Update both windows and your antivirus before this.

**Comment by ezmerelda** [comment]
pkpn i did as instructed and finally got it to install.  all seems to be fine.  thanks for your help.
