### ISSUE TITLE
The "more..." button no longer works in 0.5.1 (0.44.5)

### ISSUE THREAD

**Issue by LRGB** [popcorntime/popcorntime#2982]
#### Operating System Version:

Windows
#### Popcorn Time Version:

Popcorn-Time-0.5.1-win64-0.44.5
#### Download date:

04-16-24
#### Download url:

https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe
#### Expected Behaviour:

...
Clicking "more..." should list additional torrent options.
#### Actual Behaviour:

...
The loading icon just keeps spinning, no list of additional torrents is displayed.
#### Steps to reproduce the behaviour:

1. ...Install Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe
2. ...Choose a movie/series/anime
3. ...Click on "more..."

**Comment by merseyV** [comment]
Same for `Popcorn-Time-0.5.1-osx64-0.44.5.zip`.

**Comment by trollfalgar** [comment]
Yes, I can confirm. Not working anymore.

**Comment by Dalbouh02** [comment]
same here
