### ISSUE TITLE
The macOS ARM 5.0.1 version cannot be opened

### ISSUE THREAD

**Issue by Ioan-Popovici** [popcorntime/popcorntime#2986]
#### Operating System Version:
macOS X Sonoma 14.4.1

#### Popcorn Time Version:
5.1

#### Download date:
2024-04-17

#### Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-osxarm64.zip

#### Expected Behaviour:
Open
...

#### Actual Behaviour:
“Popcorn-Time” is damaged and can’t be opened. You should move it to the Trash.
...

#### Steps to reproduce the behaviour:
Control+Open

the [x64](https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-osx64.zip) version works fine.

**Comment by merseyV** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/2981

Opened and closed?  

It's necessary to manually remove the quarantine flag using Mac's 'Terminal' (command line) utility. 
The command is `xattr -c` "/path/to/application.app".

**Comment by Ioan-Popovici** [comment]
I completely forgot about the quarantine flag, thanks!

**Comment by merseyV** [comment]
Just missed you there!!

Edit: Now that's very interesting! You can open Popcorn-Time-0.5.1-osx64.zip on a Silicon Mac (under Rosetta2)?

**Comment by Ioan-Popovici** [comment]
@merseyV Yes, there was no ARM version until 5.0.0. I've been using it for 3 years now. And 5.0.1 works under rosetta too just slower...

**Comment by merseyV** [comment]
@Ioan-Popovici 

Thanks! for getting back to me.

Tried 0.5.1 (nwjs 0.86.0 update) on my M1 Mac (Ventura 13.6.6) during development - several times. Bounces in the dock for about 2.5 minutes, then crashes. Wasn't bothered as I use the arm64 version.

**Comment by Ioan-Popovici** [comment]
@merseyV Yeah, it works, but it wasn't ideal. It had some crashes and it was slow. The native version is much better. :D

**Comment by merseyV** [comment]
>It had some crashes and it was slow

Lol .. maybe not good news, after all? I'll do a bit more digging. It could involve Rosetta2 and the Chromium update? (beyond my pay-grade, though!)

Just have to wait for feedback from MacIntel users ... We're ok!? 👍

**Comment by Ioan-Popovici** [comment]
@merseyV Sure, It is. For those with no ARM CPUs it should run much smoother anyway. It's Rosetta2 that causes most crashes. When I switched to M1 it was noticeable :))
Anyway, I'm glad development has resumed to the point that some much-needed updates were implemented.
I kept hoping an ARM version would be compiled, and now it's here! It works great, and I'm grateful for the devs that have kept this alive all these years despite all odds.

**Comment by swapniel99** [comment]
> #2981
> 
> Opened and closed?
> 
> It's necessary to manually remove the quarantine flag using Mac's 'Terminal' (command line) utility. The command is `xattr -c` "/path/to/application.app".
> 
> **Edit:** Now that's very interesting! You can open `Popcorn-Time-0.5.1-osx64.zip` on a Silicon Mac? (Rosetta2)

You should add this bit in Readme. I was also using osx64 all this time.

**Comment by inspiredearth** [comment]
Just to say same thing occurs on M1 Macs.
Will disable quarantine.
