### ISSUE TITLE
Fix the Brew installation

### ISSUE THREAD

**Issue by magic890** [popcorntime/popcorntime#2987]
#### Operating System Version:

macOS 14.4.1

#### Download date:

18/04/2024

#### Download url:

N/A
Brew installation

#### Expected Behaviour:

Installation of Popcorn Time via Brew command

#### Actual Behaviour:

Failed installation

#### Steps to reproduce the behaviour:
Steps mentioned in the README.

```
brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
#export HOMEBREW_POPCORN_TIME_BUILD=false
brew install --cask popcorn-time #--no-quarantine
```

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

```
~ ❯ brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
#export HOMEBREW_POPCORN_TIME_BUILD=false
brew install --cask popcorn-time #--no-quarantine
==> Tapping popcorn-official/popcorn-desktop
Cloning into '/opt/homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop'...
remote: Enumerating objects: 57812, done.
remote: Counting objects: 100% (2087/2087), done.
remote: Compressing objects: 100% (408/408), done.
remote: Total 57812 (delta 1776), reused 1834 (delta 1608), pack-reused 55725
Receiving objects: 100% (57812/57812), 38.76 MiB | 22.90 MiB/s, done.
Resolving deltas: 100% (39114/39114), done.
Tapped (341 files, 53.6MB).
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
Warning: Cask 'popcorn-time' is unavailable: No Cask with this name exists.
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Searching for similarly named casks...
Error: No casks found for popcorn-time.
```

**Comment by r4kh4t** [comment]
Same for me

**Comment by massimobrivio** [comment]
Same here

**Comment by jjfantini** [comment]
same here

**Comment by sushantgupta** [comment]
same here

**Comment by bora89** [comment]
seems like it is broken, nobody give a s...t

**Comment by merseyV** [comment]
>Are you guys crazy or just don't know how github works?

We are Groot!!

![We are groot!!](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/d863da6d-6097-4b68-b0ce-87fff23acbb6)

**Comment by gunjikarmahesh** [comment]
Worked for me..
Alternative: Download the zip from https://mega.nz/folder/SgpTXCpb#6ZJfAxwl2IV9kHhBHQm0PQ/folder/S4gX3YCI based on the mac you have (M series or previous).
Unzip the package, move the app to application folder.
Run the app. 

**"FOR M series mac user additionally run the following on your terminal
xattr -c "/Applications/Popcorn-Time.app/"
