### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by Franck78** [popcorntime/popcorntime#299]
Hello,

Probably a null pointer lost somewhere. Random appearance. Can start sometime, asking 'I agree license', display show list, then bang !

nec@ntkiller2:/opt/pop> ./Popcorn-Time 
*** Error in `/opt/pop/Popcorn-Time': free(): invalid next size (fast): 0x00007fe5e82c6870 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x727df)[0x7fe5df2f77df]
/lib64/libc.so.6(+0x7804e)[0x7fe5df2fd04e]
/lib64/libc.so.6(+0x78d56)[0x7fe5df2fdd56]
/lib64/libcrypto.so.1.0.0(CRYPTO_free+0x1d)[0x7fe5d87f047d]
/lib64/libcrypto.so.1.0.0(BN_free+0x35)[0x7fe5d882e375]
/lib64/libcrypto.so.1.0.0(+0xbb5cd)[0x7fe5d88405cd]
/lib64/libcrypto.so.1.0.0(EC_POINT_free+0x17)[0x7fe5d883f387]
/lib64/libcrypto.so.1.0.0(EC_GROUP_free+0x62)[0x7fe5d883f402]
/lib64/libcrypto.so.1.0.0(EC_KEY_free+0x3e)[0x7fe5d88489ce]
/lib64/libssl.so.1.0.0(+0x4267a)[0x7fe5d8beb67a]
/lib64/libssl.so.1.0.0(SSL_free+0x1be)[0x7fe5d8be7dce]
/opt/pop/lib/libnode.so(+0x113302)[0x7fe5d1b99302]
======= Memory map: ========
1d2f800000-1d2f8f2000 rw-p 00000000 00:00 0 
11d1cd00000-11d1ce00000 rw-p 00000000 00:00 0 
17f27200000-17f27201000 ---p 00000000 00:00 0 
17f27201000-17f27202000 rw-p 00000000 00:00 0 
17f27202000-17f27204000 ---p 00000000 00:00 0 
17f27204000-17f273fc000 rw-p 00000000 00:00 0 
17f273fc000-17f27400000 ---p 00000000 00:00 0 

Operating System Version:
opensuse 13, kernel
Linux ntkiller2 3.16.7-48-desktop #1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 x86_64 x86_64 GNU/Linux

Popcorn Time Version:
3.10 (1 novemeber)

**Comment by Franck78** [comment]
no interest on tracking a SIGILL signal ?

you know this kind of thing is never good and should not happen !

at least give me symbols to make gdb happier.........

Franck

**Comment by VitorVRS** [comment]
Can you try another version, an actual build or even an old build?

**Comment by Franck78** [comment]
well, I didn't uninstall 3.9 ;-) It never had a sigill. Continuing using it on my Opensuse 13.2.

What are  you calling 'actual build' ? You want me to build it on my machine ?

On an Ubuntu (14.04 or 16.04 not sure), no sigill.

**Comment by VitorVRS** [comment]
Here we have all builds: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

From 3.9 to 3.10, nodewebkit was updated, have you tried to search if there are issues with your OS and nodewebkit?

**Comment by Franck78** [comment]
Perhaps related to #298 ?
It's difficult to track for me. Who doest what... who is who
libnw.so is webkit (recent) compiled by you (not patched), and you think on Opensuse it have problems ? 

I don't find a package with full debug info in Jenkins. And since Mars (3.9) you added lot of modification !

Given the reaction on my system, it looks like a return function is not checked ? Using somewhere after a bad pointer. Because the code is 'executed', maybe a thread ? 
gdb Pop310 shows plenty of thread launched during startup. 
It fails very often before asking 'license agreement'.

An old database is not the problem because I tried on  a clean account.

What is happening during the init phase, problem is here.

Franck

**Comment by Franck78** [comment]
I think this bug will stay for the posterity... Something wrong somewhere.

Anyway, I will upgrade my still supported not so old opensuse 13.2 to LEAP_42. No more siggill.
During a short period starting right now, I have the two systems up and running. If someone interested in putting a name on the culprit component.
