### ISSUE TITLE
New version is not installing

### ISSUE THREAD

**Issue by central4all** [popcorntime/popcorntime#2995]
All the new version of Popcorn time are not installing.
From properties i see that is not blocked, all other installations are working.
Is obvious that the problem is mine , but cant find a solution and is driving me mad.
Can somebody help me?
Thank you in advance

**Comment by central4all** [comment]
Windows 11 Enterprise
with AMD Ryzen 5 processor

**Comment by central4all** [comment]
Practically is doing nothing at all, shows that is start working the small cycle, and then stops, 
no antivirus logs nothing at all.

**Comment by central4all** [comment]
I did more than 10 times , i checked everything , nothing seems to block it.

**Comment by central4all** [comment]
I tried zip file , open the run message and after nothing again.

**Comment by central4all** [comment]
When you install an application, there is a pop up for the setup wizard to install

**Comment by dutchy1001** [comment]
Have you checked the quarentine folder of your anti virus?
Happend to me that without any warnings it was put in the quarentine folder.

**Comment by central4all** [comment]
@dutchy1001 yes i did

**Comment by central4all** [comment]
it did it 1-2 times and is not doing it anymore

**Comment by dutchy1001** [comment]
If you already had an installed version of Popcorn Time (PCT) check the default locations (C:\Users\Your user name\AppData\Local and C:\Users\Your user name\AppData\Local\Temp) if there is a PCT folder. 

If you not do not care about the "bookmarks, movies, settings, shows and watched" you saved then delete those 2 folders mentioned above, if you do want to save those, make a copy of the data folder located C:\Users\Your user name\AppData\Local\Popcorn-Time\User Data\Default\data. 

Install a fresh copy and see if that works. 
You can then later copy the inside of the data folder back 1 by one and see if this fixes your issue (most likely the settings DB can give an issue so pobably best to skip that one and manual do those settings)

**Comment by central4all** [comment]
@dutchy1001 Thank you i will try it

**Comment by central4all** [comment]
@dutchy1001 Thank you i will try it
