### ISSUE TITLE
Ukranian as a default content language does not preselect translaction, event when it's available in the dropdown (English selected all the time)

### ISSUE THREAD

**Issue by olehmelnyk** [popcorntime/popcorntime#2996]
#### Operating System Version:
macOS, 14.4.1 (23E224)

#### Popcorn Time Version:
0.5.1

#### Download date:
29th of April 2024

#### Download url:
[from this repo](https://mega.nz/folder/SgpTXCpb#6ZJfAxwl2IV9kHhBHQm0PQ/file/DsJ0wTKB)

#### Expected Behaviour:
when I select Ukrainian ("українська") as a default content language - I expect it will select Ukranian translations by default (same as it works for other languages, ex. "русский язик")

#### Actual Behaviour:
When Ukrainian is selected as dafualt content language - after restart - English is selected, even when Ukrainian translation is available in the dropdown menu

#### Steps to reproduce the behaviour:

1. ...
2. ...
3. ...

**Comment by ivan1986** [comment]
but `uk` it's `united kingdom`

**Comment by olehmelnyk** [comment]
> but `uk` it's `united kingdom`

'uk' is correct langiage code for Ukraine (this is language code, not country, so the United Kingdom is "en" or "en-GB" / "en_GB')

[WIKI - List of ISO 639 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
