### ISSUE TITLE
Subtitle does not go on TV

### ISSUE THREAD

**Issue by Residentcl** [popcorntime/popcorntime#30]
Subtitle does not appear in the TV to send from Windows via DLNA.
### Steps to Reproduce
1. Select Movie,
2. Add subtitle.
3. Send to TV
### Technical details:
- Popcorn Time Version: stable 0.3.9
- Downloaded from: popcorntime.sh
- Connection: 40mbs.
- OS: Windows 10 Update November 10.0.10586.
- Samsung UN32J4303.

**Comment by team-pct** [comment]
Please Try https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/35/

**Comment by Residentcl** [comment]
Does not leave the subtitle Compiling version # 35 (Feb 25, 2016 11:19:46)

![sin titulo](https://cloud.githubusercontent.com/assets/1659401/13334521/05817172-dbeb-11e5-9699-3795e6eaff0f.png)

**Comment by Residentcl** [comment]
database.js:6 Database path: C:\Users\xxxxxxxxxx\AppData\Local\Popcorn-Time
app.js:11 [INFO] Scanning: Local Network for Airplay devices
app.js:11 [INFO] Scanning: Local Network for DLNA devices
app.js:11 [INFO] Scanning: C:\Program Files
app.js:11 [INFO] Scanning: C:\Program Files (x86)
bootstrap.js:61 loading npm /butter-settings-/ butter-settings-popcorntime.io
bootstrap.js:24 loading local provider cache_provider.js
bootstrap.js:24 loading local provider cache_providerv2.js
bootstrap.js:24 loading local provider favorites.js
bootstrap.js:24 loading local provider opensubtitles.js
bootstrap.js:24 loading local provider torrent_cache.js
bootstrap.js:24 loading local provider trakttv.js
bootstrap.js:24 loading local provider tvapi.js
bootstrap.js:24 loading local provider tvshowtime.js
bootstrap.js:24 loading local provider watchlist.js
bootstrap.js:24 loading local provider ysubs.js
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-yts
generic.js:27 added yts to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-tvapi
generic.js:27 added tvapi to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-haruhichan
generic.js:27 added haruhichan to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-vodo
generic.js:27 added vodo to provider registry
app.js:11 [INFO] Found External Player: MPC-HC64 in C:\Program Files\MPC-HC
app.js:11 [INFO] Found External Player: mplayer in C:\Program Files (x86)\Universal Media Server\win32
app.js:11 [INFO] Found External Player: VLC in C:\Program Files (x86)\VideoLAN\VLC
app.js:11 [INFO] External Players: scan finished
app.js:11 [INFO] Loading DB
bootstrap.js:35 loaded cache_provider.js
generic.js:27 added Favorites to provider registry
bootstrap.js:35 loaded favorites.js
generic.js:27 added OpenSubtitles to provider registry
bootstrap.js:35 loaded opensubtitles.js
bootstrap.js:35 loaded cache_providerv2.js
generic.js:27 added Trakttv to provider registry
bootstrap.js:35 loaded trakttv.js
generic.js:27 added TorrentCache to provider registry
bootstrap.js:35 loaded torrent_cache.js
generic.js:27 added TVApi to provider registry
bootstrap.js:35 loaded tvapi.js
app.js:11 [INFO] Spawning new provider TVApi Object
generic.js:27 added Watchlist to provider registry
bootstrap.js:35 loaded watchlist.js
generic.js:27 added ysubs to provider registry
bootstrap.js:35 loaded ysubs.js
generic.js:27 added TVShowTime to provider registry
bootstrap.js:35 loaded tvshowtime.js
app.js:11 [INFO] Spawning new provider yts?&apiURL=https://api-fetch.website/movies/, Object
app.js:11 [INFO] Spawning new provider tvapi?&apiURL=https://api-fetch.website/tv/, Object
app.js:11 [INFO] Spawning new provider haruhichan Object
app.js:11 [INFO] Spawning new provider vodo Object
app.js:11 [INFO] Spawning new provider OpenSubtitles Object
app.js:11 [INFO] Spawning new provider Trakttv Object
app.js:11 [INFO] Spawning new provider TVShowTime Object
bootstrap.js:107 loaded Array[7]
app.js:11 [INFO] Initializing HTTP API server
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider TVShowTime
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider OpenSubtitles
generic_collection.js:142 pre--- undefined TraktTv Array[1]
generic_collection.js:19 pre all Array[3]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
app.js:11 [INFO] Returning cached provider tvapi?&apiURL=https://api-fetch.website/tv/,
app.js:11 [INFO] Returning cached provider haruhichan
app.js:11 [INFO] Returning cached provider vodo
app.js:6 [DEBUG] Butter 0.3.9 startup time: 6599.000ms
generic_collection.js:24 post all Object true Array[50]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
item.js:241 Object {type: "movie", imdb_id: "tt2910904", title: "The Dressmaker", year: 2015, genre: Array[1]…} "Movie"
app.js:11 [INFO] Show movie detail (tt2910904)
app.js:11 [INFO] Subtitles: none
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
item.js:241 Object {type: "movie", imdb_id: "tt2080374", title: "Steve Jobs", year: 2015, genre: Array[2]…} "Movie"
app.js:11 [INFO] Show movie detail (tt2080374)
app.js:11 [INFO] Subtitles: none

**Comment by team-pct** [comment]
@Residentcl  Make sure on settings your default subtitle is selected

**Comment by Residentcl** [comment]
Follow the problem :(

database.js:6 Database path: C:\Users\Residentcl\AppData\Local\Popcorn-Time
app.js:11 [INFO] Scanning: Local Network for Airplay devices
app.js:11 [INFO] Scanning: Local Network for DLNA devices
app.js:11 [INFO] Scanning: C:\Program Files
app.js:11 [INFO] Scanning: C:\Program Files (x86)
bootstrap.js:61 loading npm /butter-settings-/ butter-settings-popcorntime.io
bootstrap.js:24 loading local provider cache_provider.js
bootstrap.js:24 loading local provider cache_providerv2.js
bootstrap.js:24 loading local provider favorites.js
bootstrap.js:24 loading local provider opensubtitles.js
bootstrap.js:24 loading local provider torrent_cache.js
bootstrap.js:24 loading local provider trakttv.js
bootstrap.js:24 loading local provider tvapi.js
bootstrap.js:24 loading local provider tvshowtime.js
bootstrap.js:24 loading local provider watchlist.js
bootstrap.js:24 loading local provider ysubs.js
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-yts
generic.js:27 added yts to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-tvapi
generic.js:27 added tvapi to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-haruhichan
generic.js:27 added haruhichan to provider registry
bootstrap.js:61 loading npm /butter-provider-/ butter-provider-vodo
generic.js:27 added vodo to provider registry
app.js:11 [INFO] Found External Player: MPC-HC64 in C:\Program Files\MPC-HC
app.js:11 [INFO] Found External Player: mplayer in C:\Program Files (x86)\Universal Media Server\win32
app.js:11 [INFO] Found External Player: VLC in C:\Program Files (x86)\VideoLAN\VLC
app.js:11 [INFO] External Players: scan finished
app.js:11 [INFO] Loading DB
bootstrap.js:35 loaded cache_provider.js
bootstrap.js:35 loaded cache_providerv2.js
generic.js:27 added Favorites to provider registry
bootstrap.js:35 loaded favorites.js
generic.js:27 added OpenSubtitles to provider registry
bootstrap.js:35 loaded opensubtitles.js
generic.js:27 added TorrentCache to provider registry
bootstrap.js:35 loaded torrent_cache.js
generic.js:27 added Trakttv to provider registry
bootstrap.js:35 loaded trakttv.js
generic.js:27 added TVShowTime to provider registry
bootstrap.js:35 loaded tvshowtime.js
generic.js:24 double definition of tvapi function (args) {
    var that = this;
    try {
        var Client = require('node-tvdb');
        var tvdb = new Client('7B95D15E1BE1D75A');
        tvdb.getLanguages()
            .then(function (langlist) {
                that.TVDBLangs = langlist
            });
    } catch (e) {
        that.TVDBLangs = false
        console.warn('Something went wrong with TVDB, overviews can\'t be translated.');
    }
    TVApi.super_.call(this);

```
if (args.apiURL)
    this.apiURL = args.apiURL.split(',');

this.quality = args.quality;
this.translate = args.translate;
this.language = args.language;
```

} Object is the same as function (args) {
    var that = this;
    try {
        var Client = require('node-tvdb');
        var tvdb = new Client('7B95D15E1BE1D75A');
        tvdb.getLanguages()
            .then(function (langlist) {
                that.TVDBLangs = langlist
            });
    } catch (e) {
        that.TVDBLangs = false
        console.warn('Something went wrong with TVDB, overviews can\'t be translated.');
    }
    TVApi.super_.call(this);

```
if (args.apiURL)
    this.apiURL = args.apiURL.split(',');

this.quality = args.quality;
this.translate = args.translate;
this.language = args.language;
```

}
app.js:21 [ERROR] couldn't find provider TVApi
generic.js:27 added Watchlist to provider registry
bootstrap.js:35 loaded watchlist.js
generic.js:27 added ysubs to provider registry
bootstrap.js:35 loaded ysubs.js
generic.js:27 added TVApi to provider registry
bootstrap.js:35 loaded tvapi.js
app.js:11 [INFO] Spawning new provider yts?&apiURL=https://api-fetch.website/movies/, Object
app.js:11 [INFO] Spawning new provider tvapi?&apiURL=https://api-fetch.website/tv/, Object
app.js:11 [INFO] Spawning new provider haruhichan Object
app.js:11 [INFO] Spawning new provider vodo Object
app.js:11 [INFO] Spawning new provider OpenSubtitles Object
app.js:11 [INFO] Spawning new provider Trakttv Object
app.js:11 [INFO] Spawning new provider TVShowTime Object
bootstrap.js:107 loaded Array[7]
app.js:11 [INFO] Initializing HTTP API server
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider TVShowTime
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
app.js:11 [INFO] Returning cached provider Trakttv
app.js:11 [INFO] Returning cached provider OpenSubtitles
generic_collection.js:142 pre--- undefined TraktTv Array[1]
generic_collection.js:19 pre all Array[3]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
app.js:11 [INFO] Returning cached provider tvapi?&apiURL=https://api-fetch.website/tv/,
app.js:11 [INFO] Returning cached provider haruhichan
app.js:11 [INFO] Returning cached provider vodo
app.js:6 [DEBUG] Butter 0.3.9 startup time: 6471.000ms
generic_collection.js:24 post all Object true Array[50]
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
item.js:241 Object "Movie"
app.js:11 [INFO] Show movie detail (tt1741273)
app.js:11 [INFO] Subtitles: none
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
item.js:241 Object "Movie"
app.js:11 [INFO] Show movie detail (tt3682448)
app.js:11 [INFO] Subtitles: none
app.js:11 [INFO] Returning cached provider yts?&apiURL=https://api-fetch.website/movies/,
item.js:241 Object "Movie"
app.js:11 [INFO] Show movie detail (tt1618448)
app.js:11 [INFO] Subtitles: none

**Comment by lechatmagik** [comment]
I am the same problem.
Pleeeeaaase, fix it. :)
