### ISSUE TITLE
Not displaying any DLNA devices

### ISSUE THREAD

**Issue by ajayHD** [popcorntime/popcorntime#300]
Operating System Version:

windows 10
Popcorn Time Version:

3.10
Download date:

31/10/16
#### Expected Behaviour

...
connect to my Kodi or chromecast
#### Actual Behaviour

...
no option for Kodi or chromecast comes up - only butter and vlc
#### Steps to reproduce the behaviour

1. ...open kodi (all netowrk settings are correct)
2. ...picked a show
3. ...waited for it to show as an option

**Comment by team-pct** [comment]
Try Open Kodi / TV 
- Then open Popcorn Time
  As detection should be started once

**Comment by r-e-l1** [comment]
check if you have VPN on ... A friend who have the same issue says he always need to first load the app and only then turn VPN on or it wont see his devices. In his case it was an Xbox so don't know if this is same issue or not. the funny part Windows 10, always see those devices and can do "Cast to" ... Will be good if the Dev will try to use the same API windows uses that seems to always work.

**Comment by miehilmie** [comment]
It happened to me too. Sometime it shows my smart tv, and sometime it doesn't. But my device still appear in win 10 "Cast to" menu when it doesn't in PT.

**Comment by liorbp** [comment]
Any updates regarding this?

**Comment by Persei08** [comment]
Can any of you (not windows user) test if things are improved with [dev build #286](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/286/) ?
