### ISSUE TITLE
Not an issue, but an important question about PCT source

### ISSUE THREAD

**Issue by inspiredearth** [popcorntime/popcorntime#3001]
I'm not sure where else to ask this, so please excuse me for posting on the Issue system here.

Popcorn time notified me there was a new version. I was able to click YES in the popup to "close popcorn time, and download new version" (paraphrasing here).

Nothing opened up. So I went online and searched for "popcorn-time". The second result (in Qwant, the SE I use) was for a page on Techspot.com, here: https://www.techspot.com/downloads/6450-popcorn-time.html

AFAIK, Techspot are typically considered to be trustworthy. However, I got suspicious because the version number (v6.2.1) is many iterations higher than the one I have installed (v 0.5.0).

My question is, can someone tell me whether the popcorn-time you see there on Techspot has anything to do with this project?

Thank you.

**Comment by dutchy1001** [comment]
Very simple, NO.
The version you mentioned is from a different fork/people.
For your update plz go to [here](https://mega.nz/folder/SgpTXCpb#6ZJfAxwl2IV9kHhBHQm0PQ). Choose the folder "Android or Desktop" and go from there.

Closing this as there is no further issue, feel free to reply if you have any more questions.
