### ISSUE TITLE
no audio coming from the app

### ISSUE THREAD

**Issue by miles5600** [popcorntime/popcorntime#3002]
#### Operating System Version:
MacOS Ventura

#### Popcorn Time Version:
V0.5.1

#### Download date:
Today May 10th 2024

#### Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-osx64.zip

#### Expected Behaviour:
output audio

#### Actual Behaviour:
not outputting audio

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):
![image](https://github.com/popcorn-official/popcorn-desktop/assets/31892943/d3e6fba9-0e6e-4474-9ac2-c6651d225620)

**Comment by merseyV** [comment]
Newer nwjs 0.86.0 version`Popcorn-Time-0.5.1-osx64.zip` doesn't have all the  Dolby codecs (in the PT player) that the older nwjs runtime version `[Popcorn-Time-0.5.1-osx64-0.44.5.zip)` has?  This is unlikely to change .. any time soon! 

So, unless you can use the  0.44.5 version .. you would have to use an alternative player: like [VLC](https://www.videolan.org) media player (has all codecs). 

Download VLC player to your 'Applications' folder, and PTapp will show it in the [**'Watch Now'**](https://i.postimg.cc/52M9nb2p/Watch-Now.png) menu?

**Comment by miles5600** [comment]
why doesn't it have the dolby codecs though?

**Comment by dutchy1001** [comment]
nwjs 0.86.0 is a third party piece of code that is maintained bij others. We have no say in what they add or don't add. 
I presume they will have a Github repository (or simular site) where you could ask that.
