### ISSUE TITLE
Update NW.js runtime to 0.88.0

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#3006]
This will improve performance and security

**Comment by dutchy1001** [comment]
As soon our devs have it working as they want they will update to the new version. The new NW.js has to work with all other modules PCT is using or we will have other issue's.

**Comment by merseyV** [comment]
I think they're in holiday mode ... maybe Christmas!! 🤣🤣🤣

**Comment by cheof** [comment]
https://github.com/nwjs/nw.js/issues/8184 , Linux/X11: crash on 0.85.0+  I'd like have an update to 0.92 or 0.93

**Comment by merseyV** [comment]
>crash on 0.85.0+ I'd like have an update to 0.92 or 0.93

It could be a good while? ... Devs are having some "me time!"

I assume you're using 0.82.0 (or 0.44.5) atm? Just stick with that for now?

**Comment by fisforfaheem** [comment]
hahah!
