### ISSUE TITLE
Release Next version, also add Hindi dubbed support

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#3007]
Kindly

**Comment by dutchy1001** [comment]
What you mean with this?
Do you want PCT in Hindi or do you want the movies, series and anime in Hindi?

Hindi as default language can be choosen in the settings under "Language" section.

If you want the movies, series and anime in Hindi then this is something our devs can't do, this depends on the API what is included.
If you got an account with Opensubtitle.org the Hindi subs can be choosen from the "subtitle" dropdown menu (not sure what the Hindi flag is) on the movie/serie you want to see. Saying this, they have to be available on Opensubtitle of course.

**Comment by fisforfaheem** [comment]
I meand there should be AUDIO SELECTION for movies that are also dubbed in hindi

**Comment by dutchy1001** [comment]
If audio is available at the same corner were you can choose a subtitle you can choose audio
![Screenshot 2024-05-30 194904](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/ffed3711-2f96-40e7-b240-e45a146dce42)
This screenshot is taken from th movie Argylle

PCT isn't responsible for the content, this all comes by an API. If the API doesn't have Hindi then there is nothing PCT can do about.

As this issue isn't PCT related I close the topic. Feel free to continue here if needed.

**Comment by dutchy1001** [comment]
On a different note,
when using a 3rd party player (like smplayer or VLC) you have more options sometimes to choose languages and subtitles. Again this is depened with each movie/serie different.

**Comment by fisforfaheem** [comment]
Sure, but kindly ask the team to update regularly.. also try for use electron built-in update tool

**Comment by fisforfaheem** [comment]
Also the assets section seems weirdly named for a noob non dev.

**Comment by dutchy1001** [comment]
> Sure, but kindly ask the team to update regularly

Updates have been regular over the last few months, just check the "action" tab on top of this page for new builds.
It's quiet for now as we just had mayor updates done over the last months, no new big issue's have been found so far so no need for new builds.

> Also the assets section seems weirdly named for a noob non dev.

not sure what you mean with that

**Comment by merseyV** [comment]
>ask the team to update regularly

@dutchy1001 
Lol .. best of luck with that?

Old Popcorntime.io Team?

![old popcorntime team](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/0cb47cff-96e6-4880-a42d-cba035d7f6b6)

Todays outing!!

![team-pct](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/9d519f1c-ccf0-4823-803c-796143d4b576)

At least they're both facing the same way? 🤣

**Comment by fisforfaheem** [comment]
Also the assets section seems weirdly named for a noob non dev.

 it means the place where we can download the .exe or .dmg files... in
releases

**Comment by dutchy1001** [comment]
Is kiriles at the front or at the back. On the other pic it looks like persei08 sits in the middle with a red shirt 🤣🤣🤣


>  it means the place where we can download the

For various reasons this has to be that way if you know what I mean 😉

**Comment by merseyV** [comment]
> it looks like persei08 sits in the middle with a red shirt

If you look closely? He's just about to leave the boat to borrow some sugar from his neighbour! And we haven't seen him since? 

... just hope her name wasn't Annie? 🤣

**Comment by fisforfaheem** [comment]
That's funny! whats going on?
