### ISSUE TITLE
Support for own subtitles when viewed on Chromecast and LG WebOS

### ISSUE THREAD

**Issue by Mazufa** [popcorntime/popcorntime#3008]
I wish the next version of Popcorn Time would include support for own subtitles, even if I'm watching a movie on Popcorn Time via Chromecast or LG webOS. Currently, you can't use native subtitles on your computer when using Chromecast or LG webOS, and that's not a good thing at all. Sometimes Popcorn Time's online subtitles are timed correctly, but very often they are not timed correctly, and with the subtitles I have downloaded from OpenSubtitles, I have always had correctly timed subtitles. But at the moment my own subtitles are of no use because they can't be used on Chromecast or LG webos. All Popcorn Time movies don't even have subtitles available, neither subtitles in Finnish nor in any other language. So I hope that these shortcomings will be fixed in the next update. Thank you!

**Comment by dutchy1001** [comment]
Not sure how this might work as I dont have Chromecast but...
You can use 3rd party players with PCT like VLC. VLC has loads more options (for audio and subtitles) and can be streamed to a tv. 
It's worth a try to do if that helps.

Edit:
Link [how to cast vlc to chromecast](https://www.androidauthority.com/cast-vlc-player-to-tv-3191053/)

**Comment by merseyV** [comment]
@dutchy1001
I don't think VLC supports casting subtitles to Chromecast. I've had  few of their devices over the years ... at some point (many years ago) it just stopped working (latest device still a no-go). This is what they support:

<img width="1214" alt="Chromecast Subs support" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/eaf50d5e-7da4-48a3-b15b-d5fdc6e2077b">

Some third party apps get round it by burning the subs as it streams .. I don't think there's much chance the guys are going down that road?

Not sure what OP means by webOS playback ... but I think kiriles will confirm his LG (like mine) will play subs (from Popcorntime app) over DLNA. No option to play (own) download subs though, I think? I'm sure Kirilies/Ivan would have done it by now (for themselves) if it was possible/easily done?

**Comment by Mazufa** [comment]
> @dutchy1001 En usko, että VLC tukee tekstityksen heittämistä Chromecastiin. Minulla on ollut muutamia heidän laitteitaan vuosien varrella ... jossain vaiheessa (monta vuotta sitten) se vain lakkasi toimimasta (uusin laite edelleen ei toimi). Tätä ne tukevat:
> 
> <img alt="Chromecast Subs support" width="1214" src="https://private-user-images.githubusercontent.com/137357177/335370895-eaf50d5e-7da4-48a3-b15b-d5fdc6e2077b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDY4MTEsIm5iZiI6MTcxNzEwNjUxMSwicGF0aCI6Ii8xMzczNTcxNzcvMzM1MzcwODk1LWVhZjUwZDVlLTdkYTQtNDhhMy1iMTViLWQ1ZmRjNmUyMDc3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQyMjAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTQ5YWMzYjFkZjg4YjMxZDc2MmViMDdiOWY3OGJmMmQyN2I5YmZiZTE3NmJlZTE1NTJlYjAyYWE2NjJiYTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BObDN3e5MvlqzERLXtplD9ZWzMujnTstowf1X97jac0">
> Jotkut kolmannen osapuolen sovellukset kiertää sen polttamalla subs kuin se streaming .. En usko, että on paljon mahdollisuuksia kaverit ovat menossa alas, että tie?
> 
En ole varma, mitä OP tarkoittaa webOS-toistolla ... mutta luulen, että @kiriles90 vahvistaa hänen LG:nsä (kuten minunkin) toistavan subs (Popcorntime-sovelluksesta) DLNA:n kautta. Ei kuitenkaan ole mahdollisuutta toistaa (omia) ladattuja subs, luulisin? Olen varma, että Kirilies/Ivan olisi jo tehnyt sen (itselleen), jos se olisi mahdollista/helppoa?

I'm talking about the DLNA on the LG TV. I have now watched James Bond movies on Popcorn Time and in very many of the movies the online subtitles on Popcorn Time have not been timed correctly, and some have not had any Finnish subtitles at all. I have then had to find them myself on Opensubtitles.com, and the problems start here, as these subtitles, which are on my own computer, cannot be connected if I use LG DLNA or Chromecast. It would be really great if this could be sorted out in the future so that the subtitles I'm looking for myself could be sent via Popcorn Time to LG DLNA and Chromecast, which is not possible at the moment.

For some reason, VLC media player cannot find LG DLNA even though my computer and LG TV are on the same network. I would have tried to see if I could add subtitles by watching movies via Popcorn Time with VLC media player, then connect the subtitles from my computer via VLC and then send it via VLC to LG DLNA, but for some reason VLC can't find LG DLNA.

**Comment by Mazufa** [comment]
I'm talking about the DLNA on the LG TV. I have now watched James Bond movies on Popcorn Time and in very many of the movies the online subtitles on Popcorn Time have not been timed correctly, and some have not had any Finnish subtitles at all. I have then had to find them myself on Opensubtitles.com, and the problems start here, as these subtitles, which are on my own computer, cannot be connected if I use LG DLNA or Chromecast. It would be really great if this could be sorted out in the future so that the subtitles I'm looking for myself could be sent via Popcorn Time to LG DLNA and Chromecast, which is not possible at the moment.

For some reason, VLC media player cannot find LG DLNA even though my computer and LG TV are on the same network. I would have tried to see if I could add subtitles by watching movies via Popcorn Time with VLC media player, then connect the subtitles from my computer via VLC and then send it via VLC to LG DLNA, but for some reason VLC can't find LG DLNA.

Another solution would be to make a dedicated Popcorn Time app for LG smart TVs. Unfortunately, LG TV does not use Android TV, so the current Android-based Popcorn Time program cannot be used here. If a custom Popcorn Time program were made for the LG TV, I could then install the Popcorn Time program on the LG TV, and then I could import the subtitles, say with a flash drive, to the LG TV, and then add them to the movie via the Popcorn Time program. Then I wouldn't have the problem that Chromecast has with not being able to add subtitles on my computer.

**Comment by dutchy1001** [comment]
the reason I started with 

> Not sure how this might work as I dont have Chromecast but...

I watch on the pc with my headset so my wife aint complaining about all the silly stuff I watch 😎😎😎

**Comment by merseyV** [comment]
>Another solution would be to make a dedicated Popcorn Time app for LG smart TVs.

Definitely not going to happen ... unless someone else wants to build their own version? (unlikely).

>For some reason, VLC media player cannot find LG DLNA even though my computer and LG TV are on the same network
>with VLC media player, then connect the subtitles from my computer via VLC

The reason being VLC doesn't directly support DNLA. The workarounds to enable it are not worth considering (unstable at best). You'll have to ask them?
As I said earlier: VLC doesn't support streaming subs to Chromecast (well documented). Seen some talk |(online) about a fix in the pipeline ... probably just Forum gossip! Obviously, nothing to do with PTapp?

> the online subtitles on Popcorn Time have not been timed correctly,

That'll be an Opensubtitles.com question? PTapp gives you (keyboard) controls for adjusting the sync within a reasonable limit ... but sometimes subs constantly drift, no matter what you do? Popcorntime doesn't create subs or host torrents ... it's an aggregator (links to other content providers).

There were plans for some further subs improvements .. still a work in progress, I think. I can't remember if it included custom subs?

**Comment by Mazufa** [comment]
I wish I could code so I could do development work myself, but I don't have that skill.  

It seems that I have to build a movie computer and connect it with an HDMI cable to the TV. Then I can add my own subtitles in Popcorn Time from my computer and then watch the movies through Popcorn Time on the TV.

**Comment by dutchy1001** [comment]
@Mazufa If you are building a separate pc just for pct then I would use a3rd party player as it got more options. Also you can then make this pc as a media server with lots more then just PCT

**Comment by Mazufa** [comment]
This is a very good proposal. I actually should have all the components needed to build this media server computer. I will then install Popcorn Time on it. Surely Plex would be a good choice for media server software?
