### ISSUE TITLE
KAT Replacement

### ISSUE THREAD

**Issue by idtzoli** [popcorntime/popcorntime#301]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

I thought that the KAT integration would be removed with a new release, but it didn't happen. The KAT is offline for months, can you replace with another alternative? TPB for example?

**Comment by ChrisAlderson** [comment]
KAT could be replaced with TPB or ExtraTorrent or both (I think).

**Comment by kim0** [comment]
isn't https://kat.am/ a continuation of some form

**Comment by ChrisAlderson** [comment]
No, KAT (Kickass or whatever synonym) is down. Mirrors like https://kat.am or https://kickass.cd/ did show up, but they are not a successor to https://kat.cr (down).

I haven't looked into how to replace the KAT search with ExtraTorrent or TPB, but modules for both options are available:
- https://github.com/t3chnoboy/thepiratebay
- https://github.com/ChrisAlderson/extratorrent-api (promoting my own module, I'm shit).

**Comment by ChrisAlderson** [comment]
Talked internally, ExtraTorrent will be the first to replace KAT. Then we will see about implementing TPB.

**Comment by ChrisAlderson** [comment]
#309
