### ISSUE TITLE
Popcorn time gets stuck

### ISSUE THREAD

**Issue by nsitaman** [popcorntime/popcorntime#3012]
Searched for some specific movie "Guru: Bhagwan, His Secretary & His Bodyguard (2010)" (https://www.imdb.com/title/tt1735976/mediaviewer/rm2391534849/). Clicked on the results. Popcorn time stops responding.

#### Operating System Version:

Linux
#### Popcorn Time Version:

Popcorn-Time-0.5.1-linux64.zip
nwjs 123.0.6312.87 

#### Download date:

15.06.2024
#### Download url:

github release page
#### Expected Behaviour:

Open the movie page

#### Actual Behaviour:

gets stuck.

#### Steps to reproduce the behaviour:

1. Search for 'Guru bhagwan' movie.
2. Click on the result.
3. Popcorn time stops responding.

Have noticed with some other movies as well. I am using latest popcorn time version downloaded from gihub release page on linux mint.

**Comment by merseyV** [comment]
It's not surprising ... 1 seed / 1 peer? If the health (dot) is red, the torrent is (probably) not going to work. You can't download unless others (with a copy) are available to share it. It's p2p (bittorent) .. not an on demand service?

<img width="439" alt="340135283-334d9545-364a-4340-9f55-a2e64c03def3" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/6ba0f5bd-2adf-4e99-876b-7ab3da033726">
