### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JLTOURVILLE** [popcorntime/popcorntime#3014]
#### Expected Behaviour:

...

#### Actual Behaviour:

...

#### Steps to reproduce the behaviour:

1. ...
2. ...
3. ...

**Comment by merseyV** [comment]
An invisible bug report ... not sure if our Devs are au fait with the Kaluza-Klein Dimensions!! 🤣

**Comment by dutchy1001** [comment]
I click the visable  close button
