### ISSUE TITLE
Make it possible to find movies based on searching for actor names in the search box

### ISSUE THREAD

**Issue by Umeaboy** [popcorntime/popcorntime#3018]
**Is your feature request related to a problem? Please describe.**
Lets say that one doesn't remember exactly which movies a certain actor was in there's currently no way to do a more specific search. 

**Describe the idea you'd like**
You type the name of one or more actors and hit Enter. This will show all the movies based on your name search.

**Describe alternatives you've considered**
There are none that I know in PopcornTime atm.

**Additional context**
![Search for movies with Walter Matthau](https://github.com/popcorn-official/popcorn-desktop/assets/714473/c80c3492-0b51-4595-a525-e6078594892d)

**Comment by dutchy1001** [comment]
That will be depending if the API has this information. We dont have a say in what info an API "fetches" as they are 3rd party code. 

It is just as simple to open a  browser and type a name there to find out who is playing in what movie (probably also a lot faster that way).
