### ISSUE TITLE
I have created an open subtitles account but when I go to the settings enter my user name and pass word for open subs, then click connect below it tells me that my user name is wrong, I am 100% percent sure both the user name and password are correct.

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#3021]
#### Operating System Version:
Windows 10 Home

#### Popcorn Time Version:
Current Latest

#### Download date:
Today some hours ago (5/7/2024)

#### Download url:
I downloaded it from here https://github.com/popcorn-official/popcorn-desktop/releases

#### Expected Behaviour:
I was expecting it to check and tick my user name and password when I clicked connect with open subtitles account
...

#### Actual Behaviour:
The app just put an x over username
...

#### Steps to reproduce the behaviour:

1. I created an open subs account (using a vpn because for some reason it is banned in my country)
2. Enter the user name and pass in the app settings in the subtitles category
3. Click Connect to opensubtitles.org below

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):
![2024-07-05 02_51_30-](https://github.com/popcorn-official/popcorn-desktop/assets/144116579/28500778-6da0-4eb0-82ac-705a05395639)

**Comment by dutchy1001** [comment]
Have you tried to log into the website from Opensubtitle with the current details?

What is the web adress you used to create an account?

(Other issues they (opensubtitle) could have is maintenance or server outage)

**Comment by ghost** [comment]
Yes I did and it logged on fine, ***@***.*** is the email.

Στις Παρ 5 Ιουλ 2024, 10:10 ο χρήστης dutchy1001 ***@***.***>
έγραψε:

**Comment by ghost** [comment]
Maybe I need to enter the email not my user name in popcorn time?

Στις Παρ 5 Ιουλ 2024, 12:03 ο χρήστης Apostolis Sofkos ***@***.***>
έγραψε:

**Comment by dutchy1001** [comment]
Sorry my mistake, I ment the website adress. 

Ofcourse we dont need your private email adress.

**Comment by ghost** [comment]
What website? Open subtitles is opensubtitles.org. other website?

Στις Παρ 5 Ιουλ 2024, 13:39 ο χρήστης dutchy1001 ***@***.***>
έγραψε:

**Comment by dutchy1001** [comment]
yes that's the correct one, there are some others websites that provide subtitles which we don't use, just to make sure.

I never had an issue with logging into opensubtitles but cant remeber if I used username or email to login.

**Comment by ghost** [comment]
Maybe the problem is that I used a vpn to create my open subs account? Open subs is banned in my country so I used a vpn.

**Comment by dutchy1001** [comment]
I use a VPN too but it signs me in with username (not with email)  and password. I just logged out and back in to check.

**Comment by ghost** [comment]
i just tried to change the password and try but nothing

**Comment by dutchy1001** [comment]
It also let me login on the website with VPN on (with username and password)

**Comment by ghost** [comment]
I used a vpn to make my open subs account from a browser vpn extension when i use popcorn time app i dont have any vpn there

**Comment by ghost** [comment]
it logs me in just fine in the open subs website

**Comment by dutchy1001** [comment]
can you not try PCT with vpn?

**Comment by ghost** [comment]
ill try now just a moment

**Comment by ghost** [comment]
Yes with vpn in popcorn time it logged me in, now if i disable the vpn and use popcorn time will it stay connected? i dont like using it with vpn because of low download speed

**Comment by ghost** [comment]
it stays logged in but no subtitle options with no vpn

**Comment by dutchy1001** [comment]
That is something you need to test yourself, I can't check this as Opensub is not banned in my country.

An other option is to use a 3rd party player (like VLC or SMplayer) you can download the sub of a movie before you start watching and then add the downloaded sub through the 3rd party player. 

I know it's more work but probably cheaper then a VPN with better connections.

**Comment by ghost** [comment]
Yes that's what I did yesterday when I wanted to watch smth, I guess I'll
continue doing that thanks

Στις Παρ 5 Ιουλ 2024, 14:04 ο χρήστης dutchy1001 ***@***.***>
έγραψε:

**Comment by ghost** [comment]
by the way one last thing, if there is an update in the movie or series database, it will inform me to update right?

**Comment by dutchy1001** [comment]
If you have the setting to show notification for updates ticked it will inform you for "major" updates. 
If you like to updates in between check the "action" tab on top here. The last build is now 3 months old.

I will close this issue as we found out it is working with VPN for you. We can still continue here if you need any more answers.
