### ISSUE TITLE
Subtítulos

### ISSUE THREAD

**Issue by edzon187** [popcorntime/popcorntime#3022]
No puedo conectarme a Opensubtitles.org a través de la página de configuración de PopCorn. Sin embargo ingreso sin problemas al sitio web de Opensubtitles. Mucho agradecería vuesta colaboración en tal sentido. Muchas Gracias.

**Comment by dutchy1001** [comment]
Issues have to be in english only
Los números deben estar solo en inglés.

Not sure is Spain is blocking opensubtitles.org but try a VPN and see if it works then. We recently had the same issue with somebody from Greece.

**Comment by edzon187** [comment]
Nice day. Thank you very much for the prompt response. I have tried VPN without success. The strange thing is that in previous versions of Popcorn, it worked perfectly. It is in these last two versions that the failure has occurred. What's more: I have subscribed to Opensubtiles with other usernames/passwords, and with none of them I have been able to get lucky... (¿?). Thank you very much again, and a cordial greeting.

**Comment by dutchy1001** [comment]
I use myself opensubtitles.org for every film/serie I watch and have no issue with PCT.
I presume you have been able to login to the website itself as you made a new account. 
What PCT version do you use?
It could be that some settings are stuck. 
I recommend to uninstall PCT, remove all folders from the "appdata\local" folders and reinstall the latest release build from [here](https://popcorntimeapp.netlify.app/). 

You can make a backup from the database in the "settings" tab (cogwheel right top, scroll down to "Database") so you dont loose the movies/series/favorites you have seen already but I strongly suggest not to put the "settings.db" back as this might be the cause.

let me know how you get on with this.

PS. When applying new settings I suggest the "dutchy's dark orange" theme 🤣🤣🤣

**Comment by edzon187** [comment]
Dear.

I appreciate your patience with this issue. I'm using version 0.5.1. I have proceeded punctually as you indicated in your email, without luck. Perhaps it is useful to note that I cannot connect to "Track-TV" either.

 �

**Comment by merseyV** [comment]
>PS. ... I suggest the "dutchy's dark orange" theme 🤣🤣🤣

Lol .. You should charge a licence fee? I'm (obviously) exempt!! 🤣

**Comment by dutchy1001** [comment]
Trakt-TV disabled my account for not using it so I cant check this. 
Not sure if anti-virus software (or simular) can block access through PCT but if you have one try to disable it for a test. 
What OS do you have?
Do you have the posibility to try this on an other pc?

@merseyV 
your free subscription will come with your Slack account 🤣🤣

**Comment by merseyV** [comment]
I'd go with what @dutchy1001 has (already) said.  Also working for me (macOS). I don't use it that much, can go AWOL occasionally, but generally works .. sometimes without even being signed-In? Works with/without VPN for me (UK). 

>The strange thing is that in previous versions of Popcorn, it worked perfectly. It is in these last two versions that the failure has occurred. 

The last two versions include the update (switch) to the new OpenSubtitles REST API change  - introduced (and required) by Opensubtitles, themselves (apparently?). 

I think dutchy1001 has just about covered your options ... try using your old (previous) version, if you have any doubts?

@dutchy1001 
I imagine Slack is pretty lonely, these days? ... everyone's on an "extended" vacation!! 😄

**Comment by edzon187** [comment]
Hello! I proceeded to deactivate the anti-virus (ESET), without positive result. My OS is Windows 11-23H2. Good idea!! I'll try it on a Notebook and keep you posted... Thank you

 �

 �

**Comment by edzon187** [comment]
Thank you very much for the attention. I will continue trying and trying on another PC or failing that, reinstalling another version of pct (prior to 0.5….). Cordial Greetings.

 �

**Comment by dutchy1001** [comment]
As a last resort to get subtitles working you can use a 3rd party player (like VLC or SMPlayer) and manual download from opensubtitle.org.

To do this you need to have a player installed. 
Click the little arrow next to the "Watch Now" button and choose from there. When the player starts, right click to get the popup showing and click on "subtitle". 
From there you can navigate to where the subtitle is downloaded.

Hopes this helps you temporally to watch with subs.

**Comment by edzon187** [comment]
Dear Duchy1001: I use VLC, a program through which subtitles are automatically downloaded (if they exist). I also use Serviio. Only that I wanted to unravel the mystery of the failure in the PCT. I tell you that I reinstalled version 0.4.9 cleanly, and the one that previously worked correctly. Not so this time. Also, I've installed the app on the Notebook, and it works perfectly. Grateful for your time and big hug.

 �

 �

 �

**Comment by merseyV** [comment]
>Dear Duchy1001 .... grateful for your time and big hug.

![a8ec886e2e1bfd28aeabb1825d33622f](https://github.com/user-attachments/assets/8a96fffc-178b-4165-b604-7f0f2241a73f)

😄

**Comment by merseyV** [comment]
>Dear Duchy1001 .... grateful for your time and big hug.

![a8ec886e2e1bfd28aeabb1825d33622f](https://github.com/user-attachments/assets/8a96fffc-178b-4165-b604-7f0f2241a73f)

😄

**Comment by dutchy1001** [comment]
@edzon187 
It looks to me then that this is an issue with the pc in question. 
Does the notebook have the same windows 11? , if so compare settings to try and find out what blocks it on your pc an not on the notebook.

I'm closing this issue as it is not a PCT issue. You can keep posting here how you get on to find out this issue, it might help others later on.

**Comment by edzon187** [comment]
I have fixed the problem by restarting the PC in Safe Mode with Networking. Best regards

 �

 �

**Comment by edzon187** [comment]
I have fixed the problem by restarting the PC in Safe Mode with Networking. Best regards

 �

 �
