### ISSUE TITLE
New platform

### ISSUE THREAD

**Issue by Nikitosik69** [popcorntime/popcorntime#3023]
I want to commend you on this amazing project! It's incredibly convenient and user-friendly. I believe integrating this application into an Android format as an .apk would be extremely beneficial for users who prefer mobile viewing. Could you kindly let us know if there are any plans to implement this feature? Thank you so much for your hard work and dedication!

**Comment by dutchy1001** [comment]
there is alread an Android version you can get it from [here](https://popcorn-time.site/), click the "Download" button (which brings you to Mega) and from there you can choose "android" or "desktop"

The android version is not as far developed as the desktop version unfortunately.

**Comment by Nikitosik69** [comment]
> there is alread an Android version you can get it from [here](https://popcorn-time.site/), click the "Download" button (which brings you to Mega) and from there you can choose "android" or "desktop"
> 
> The android version is not as far developed as the desktop version unfortunately.

Thx
