### ISSUE TITLE
Usability questions: resume playback, do not delete files.

### ISSUE THREAD

**Issue by refaelsh** [popcorntime/popcorntime#3025]
Hello,

Couple of questions please:
1. I want to resume movie playback from the last known timestamp. How?
1. It keeps deleting whatever was downloaded every time I quit the app. How to prevent it?

Thanks.

**Comment by merseyV** [comment]
* 2 I'll do this one first .. it's easier.
By default, Popcorntime clears the Cache Directory (where your downloads reside) when you close the PTapp. You could simply untick the selection box (next to "Clear Cache Folder") in 'Settings'. 
You might want to change the cache folder to somewhere more accessible ... just click in the grey "cache directory" address box and select a different location (Desktop, maybe?).

* 1 Mine just starts from where it left off (with the Popcorntime player) when I start the download again ("Watch Now") .. even if I close the app and re-open it or restart the computer? If I drag the (completed) downloaded file back into the window, it starts again - from the beginning. Any change to playback option will reset timestamp.
If you're using a third party player like VLC or iiNA - it won't work through "Watch Now" ... you would have to open/watch it directly with the third party player - for its timestamp to work.

**Comment by refaelsh** [comment]
> If you're using a third party player like VLC or iiNA - it won't work through "Watch Now" ... you would have to open/watch it directly with the third party player - for its timestamp to work.

Understood.

> You could simply untick the selection box (next to "Clear Cache Folder") in 'Settings'.

It is unchecked. Hmm... It looks like a bug. I will open a separate issue just for that.



Thank you very much for you reply.

**Comment by refaelsh** [comment]
For future googlers, here is the link to the issue: https://github.com/popcorn-official/popcorn-desktop/issues/3026
