### ISSUE TITLE
The "Clear cache folder after closing the App?" checkbox does not work

### ISSUE THREAD

**Issue by refaelsh** [popcorntime/popcorntime#3026]
#### Popcorn Time Version:
0.5.1

#### Download date:
Approximately on 23/07/2024

#### Download url:
I used the NixOS package.

#### Expected Behavior:
I expected the cache folder not to be cleared when the checkbox is unchecked.

#### Actual Behavior:
The cache folder is always cleared no matter if the checkbox is checked or not.

#### Steps to reproduce the behavior:
1. Uncheck the checkbox.
2. Download a movie.
3. Close the app.
4. Open the app - the movie is gone from the cache folder.

**Comment by merseyV** [comment]
Beyond my pay-grade - looks like a Dev jobbie!!

>It is unchecked. Hmm...

Just curious: Did you mean the option was already unticked (default setting wasn't applied) or you already unticked it yourself?

**Comment by merseyV** [comment]
From your previous post/issue.

>It is unchecked. Hmm...  

Just curious: Did you mean (by that) the option was already unticked (default setting wasn't applied) ... or you had already unticked it yourself, manually?

**Comment by refaelsh** [comment]
> From your previous post/issue.
> 
> > It is unchecked. Hmm...
> 
> Just curious: Did you mean (by that) the option was already unticked (default setting wasn't applied) ... or you had already unticked it yourself, manually?

I dont really remember what was the default state.

**Comment by dutchy1001** [comment]
Default state is that it clears the cache folder. 
This only will be reset when doing a clean install, if only updating to newer version it will keep the settings that have been set before.

**Comment by dutchy1001** [comment]
Just re-tested this on a windows 11 pc but all working as it should. When ticked the cache is emptied (deleted) and when unticked all files are still there.

If this is still an issue plz comment (so I can add a "bug" label) or close it

**Comment by refaelsh** [comment]
> If this is still an issue plz comment (so I can add a "bug" label) or close it

Its still an issue, yes.

**Comment by refaelsh** [comment]
I am extremely curious to what fixes that. Is there a PR I can look at?
