### ISSUE TITLE
Cant View TV Series 

### ISSUE THREAD

**Issue by caiusp** [popcorntime/popcorntime#303]
Operating System Version: w10 

Popcorn Time Version:

0.3.9-12

Download date:

a couple of days ago

hi, im having this issue with popcorntime.
i re-installed it but nothing changed.
what could be the problem??
ps: im having a really hard time streaming tv series w/ my chromecast, mostly of the time there's no audio..

**Comment by VitorVRS** [comment]
From where did downloaded? It's seems your version it is not from this popcorn.

**Comment by caiusp** [comment]
Hi @VitorVRS , i downloaded from the first link in google search : http://popcorntimece.ch/

**Comment by Ragolay** [comment]
Download from here: https://popcorntime.sh

**Comment by caiusp** [comment]
i always get confuse with all those popcorntime.xx around the web! 
thanks @Ragolay

**Comment by caiusp** [comment]
ehm, why its blocked by chrome??
http://imgur.com/a/ujKQe

**Comment by Ragolay** [comment]
I don't know because I use Firefox, but I have too problems with Avast. Read this: https://github.com/popcorn-official/popcorn-desktop/issues/284

I hope that this can help you :D
