### ISSUE TITLE
Popcorn-time API code version 0.5.1

### ISSUE THREAD

**Issue by Outterlimits** [popcorntime/popcorntime#3030]
Hey, does anyone have the api list for series and anime? I get an error code when I try to update the server list automatically . Thanks!

**Comment by merseyV** [comment]
copy/paste https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/ .... for movies, series and anime.

And clear the "Automatically update ...." tick-box, if the Error pop-up notice bothers you?

Server API (auto-update) problem seems to have started about a week ago.

**Comment by merseyV** [comment]
copy/paste `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/` .... for movies, series and anime.

And clear the "Automatically update ...." tick-box, if the Error pop-up notice bothers you?

Server API (auto-update) problem seems to have started about a week ago.

**Comment by merseyV** [comment]
copy/paste `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/` .... for movies, series and anime.

Server API (auto-update) problem - seems to have begun about a week ago.

**Comment by Outterlimits** [comment]
You are amazing!!!🎉 Thank you!Sent from my iPhoneOn Aug 4, 2024, at 11:45 AM, merseyV ***@***.***> wrote:﻿
copy/paste https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/ .... for movies, series and anime.
And clear the "Automatically update ...." tick-box, if the Error pop-up notice bothers you?
Server API (auto-update) problem seems to have begun about a week ago.

**Comment by koitkorela** [comment]
Nice. Thanks @merseyV

**Comment by Nikolay0110** [comment]
> копировать/вставить `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`.... для фильмов, сериалов и аниме.
> 
> И снимите галочку «Автоматически обновлять…», если всплывающее уведомление об ошибке вас беспокоит?
> 
> Проблема с API сервера (автоматическое обновление) - похоже, началась около недели назад.
Thanks!)

**Comment by dutchy1001** [comment]
looks like this is sorted.
Closing this

**Comment by merseyV** [comment]
>looks like this is sorted.
>Closing this

@dutchy1001 
Just curious ... have you (successfully) tried it again. I've just done (yet another) clean install and it's still not (automatically) updating?

Still getting API update issues reported on the Subreddit. I'm even getting my replies deleted by the moderator ... lol. I can take a hint .. tthink I'll go join @Persei08 **:p**

**Comment by merseyV** [comment]
>looks like this is sorted.
>Closing this

@dutchy1001 
Just curious ... have you (successfully) tried it again. I've just done (yet another) clean install and it's still not "automatically" updating?

Still getting API update issues reported on the Subreddit. I'm even getting my replies deleted by the moderator ... lol. I can take a hint - think I'll go join @Persei08 **:p**

**Comment by merseyV** [comment]
>looks like this is sorted.

@dutchy1001 
Just curious ... have you (successfully) tried it again. I've just done (yet another) clean install and it's still not "automatically" updating?

Still seeing API update issues reported on the Subreddit. I've even had my replies deleted by "the moderator" ... lol. I can take a hint .. think I'll go join @Persei08 **:p**

**Comment by Outterlimits** [comment]
The automatic updating has not worked for me, but the API codes I used is working just fine. Don’t know what to do if I need new API codes someday

**Comment by dutchy1001** [comment]
@merseyV 
I still get the same error when updating manual. 
If you look at it in an other way..... If there is no change to the API then there is nothing to update which might be the cause of displaying an error.
I'll test this in the next few minutes of writing this post, if it will keep giving me an error I will reopen this issue.

**Comment by dutchy1001** [comment]
After tesing with different API's and then trying to update to the latest ones has failed.

I will reopen this issue

**Comment by Outterlimits** [comment]
It was annoying so I just unticked the update box.  But I’d love to correct this just in case the codes change. Thanks!

**Comment by merseyV** [comment]
>and then trying to update to the latest ones has failed.

Now you've done it ... you're in the same boat as the rest of us: If you deleted your original data? 

>I will reopen this issue

Maybe change the title to "Automatically update API's .... " not working (or something similar?). It's not just related to version 0.5.1 (I tried it on 0.4.9, as well?).

**Comment by Outterlimits** [comment]
My original post was about the API codes.  This thread morphed into automatic updates of API since they are related.

I don’t know how to change the title. Maybe close this thread and start a new one??

**Comment by dutchy1001** [comment]
> Maybe change the title to "Automatically update API's .... " not working (or something similar?). It's not just related to version 0.5.1 (It fails with 0.4.9, as well?).

I'm not able to change topic names, the OP should be able (next to the topic name you see "edit and (in green) New issue, click on "edit").
I would go for "Automatically update API's server URL's not working"

**Comment by dutchy1001** [comment]
opened a new topic for this #3035

**Comment by francis-drake** [comment]
But just now.. It not problem to updates api. so after restart this only black screen... Favorites is ok but not connection with ant server...

**Comment by merseyV** [comment]
The default API's seem to be broken or withdrawn. Apart from the YTS API for movies, the only option you've got is a 'Torrent Collection ' search or using your own magnet link? Not great, but that's it until someone fixes it (or doesn't?).

By the way, this GitHub doesn't support your app any more! "But it's still called Popcorntime?" (long story ;) There's no Devs or development for the old popcorntime, any more. What's left of the refuseniks are camped out [here!](https://www.reddit.com/r/PopcornTimeOriginal/)

**Comment by francis-drake** [comment]
It's complicated; the APIs aren't working. After uninstalling and reinstalling the servers, they still don't work. However, after checking the links to different servers in my favorites, the search function works. It's unfortunate, but let's be honest and say that we haven't supported it. Zero resources contributed, and if this means the loss of this excellent work and valuable effort...

**Comment by Outterlimits** [comment]
None of the API seem to be connecting. Only movies saved in Favorites are
available right now.  No one has any answers

**Comment by merseyV** [comment]
@Outterlimits , 
not quite right (movies are showing using yts.gg API in Settings? How much benefit that is to you ... pass! No API alternatives for series/anime, though! You'd have to use the apps 'Torrent Collection' search (basically TPBay) .. PTapp is after all, a sequential (streaming) torrent client (at heart). It's no longer under development (no Devs, anymore!)

However, there's no point in posting here ... there's only ghosts left (like me! :), passing through? This GitHub has been "taken-over" for a completely different legal[sic] project, which happens to be called "Popcorntime" ... don't ask? ;)

**Comment by Outterlimits** [comment]
I just tried yts.gg and still nothing under movies.  I tried restarting it
too :(

**Comment by Outterlimits** [comment]
Wait, I spoke too soon.  I had to reboot my computer, then it worked! thank
you I got my movies back 👍

**Comment by merseyV** [comment]
>you I got my movies back 👍

Don't forget .. I'm only passing through? 

The few of us left abide [here!](https://www.reddit.com/r/PopcornTimeOriginal/) :)

**Comment by Outterlimits** [comment]
Haha, thanks!
