### ISSUE TITLE
why does it freeze all the time

### ISSUE THREAD

**Issue by LastStoneGiant** [popcorntime/popcorntime#3031]
why does it always freeze click one takes forever to respond

**Comment by merseyV** [comment]
Not enough information?

Here's an exemplar of how to post an issue: From the inimitable [@dutchy1001](https://github.com/popcorn-official/popcorn-desktop/issues/3029#issue-2438372935)

The more detail, ithe better!

**Comment by dutchy1001** [comment]
Why does someone ask questions without giving all the info asked (on the submit form) when submitting a bug report

**Comment by dutchy1001** [comment]
as we are depending on available seeds it can sometimes take a bit of time.

closing this as there was no further info given.
