### ISSUE TITLE
0.44.5 can play but 0.51 displays black screen

### ISSUE THREAD

**Issue by fastrizwaan** [popcorntime/popcorntime#3032]
both in Windows build and Linux build 0.44.5 plays all videos, whereas 
0.51 can't play some videos like "Deadpool & Wolverine"; "House of the Dragon" series etc.

**Comment by merseyV** [comment]
>both in Windows build and Linux build 0.44.5 plays all videos,

Just use what works for you? ... 0.44.5. 

The 0.56.0 runtime version has missing codecs in the Popcorntime video player. Not likely to change any time soon, as it relies on "third-party" pre-built binaries for NWjs.

0.56.0 versions will work normally with an alternative - like VLC player, etc.

**Comment by merseyV** [comment]
>both in Windows build and Linux build 0.44.5 plays all videos,

Just use what works for you? ... 0.44.5. 

The 0.56.0 runtime version has missing codecs in the Popcorntime video player. Not likely to change any time soon, as it relies on "third-party" pre-built binaries for NWjs.

0.56.0 versions will work normally with an alternative - like VLC player, etc.

**Comment by merseyV** [comment]
>both in Windows build and Linux build 0.44.5 plays all videos,

Just use what works for you? ... 0.44.5. 

The 0.56.0 runtime versions have missing codecs in the Popcorntime video player. Not likely to change any time soon, as it relies on "third-party" pre-built binaries for NWjs.

0.56.0 versions will work normally with an alternative - like VLC media player, etc.

**Comment by merseyV** [comment]
>both in Windows build and Linux build 0.44.5 plays all videos,

Just use what works for you? ... 0.44.5. 

The 0.56.0 runtime versions have missing proprietary codecs in the Popcorntime video player. Not likely to change any time soon, as it relies on "third-party" pre-built binaries for latest NWjs.

0.56.0 versions will work normally with an alternative - like VLC media player, etc.
**n.b.** [FAQ](https://github.com/popcorn-official/popcorn-desktop/wiki/FAQ)

**Comment by dutchy1001** [comment]
This is a known issue that we cant change due to a "3rd party" part of the code. Unfortunatelly some codecs have been left out with the newer version of that.

Closing this topic
