### ISSUE TITLE
Can't select Audio language if multi audio video is there.

### ISSUE THREAD

**Issue by fastrizwaan** [popcorntime/popcorntime#3036]
Linux 0.5.1-4.4.5 

file is not playing my preferred language (English). 

And I can't select the audio in the Watch area. 

Workaround is to open the cache folder and use mpv/vlc to select audio as per requirement. 

Is it possible to select audio launguage in PT inbuild video player?

**Comment by dutchy1001** [comment]
This can sometimes depend on the file. This is mostly with MKV files that have the extra's build in.

> Workaround is to open the cache folder and use mpv/vlc to select audio as per requirement.

You can already select a 3rd party player like the ones you mentioned from the drop down menu

![Screenshot 2024-08-21 174949](https://github.com/user-attachments/assets/3460257c-dff7-4030-9b33-8c54e2ed4c94)
This way you dont have to open the cache folder. 
When select a 3rd party player ir will remember this for the next movie or serie you want to watch.
To be honnest I prefere a 3rd party player
