### ISSUE TITLE
Maximize button not working on certain window sizes

### ISSUE THREAD

**Issue by theakhandpatel** [popcorntime/popcorntime#3039]
#### Operating System Version:
Windows 11 22631.4037

#### Popcorn Time Version:
0.5.1 https://github.com/popcorn-official/popcorn-desktop/commit/e484724a

#### Download date:
23 Aug 2024

#### Download URL:
https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.5.1

#### Expected Behaviour:
Click on maximize button and it should maximize to the full width.

#### Actual Behaviour:
The app is not maximized, will have to right-click on the title bar and select maximize

#### Steps to reproduce the behaviour:
I am using an external monitor(2560 x 1440). 
1. resize the window to Height: 1153.6px Width:  1738.4px.  Similar to the below, the bottom goes beyond the visible screen.
![pptime](https://github.com/user-attachments/assets/9b1d06bc-4dd5-4081-b85f-01152670065a)

2. Click on the Maximize button. it will not work
3. right click on the title bar and click on, maximize it will do its job.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

It is not happening in all sizes but in specific dimensions.
![Maximize](https://github.com/user-attachments/assets/3ecef635-8680-458b-9bc4-0b1af69452a0)

![image](https://github.com/user-attachments/assets/235b9e58-bc6c-436a-be06-af1538866fc8)
![image](https://github.com/user-attachments/assets/bcabbc35-bc97-403c-ac2b-e4e8831465ea)

**Comment by dutchy1001** [comment]
I have tried many resolutions, expand and minimize again but I can't reproduce this.
As long all default resolutions work I dont think this is an issue to be looked at
