### ISSUE TITLE
WebTorrent Implementation

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#304]
- [x] Switching From Peerflix to Webtorrent
- [x] First commit on a P2P updater 
- [x] Seed The update if we are on the last version
- [x] Global Declaration of Webtorrent ( Webtorrent Should be Initiated on Start then we just use it as torrent client)

Related PR #292

**Comment by team-pct** [comment]
@vzamanillo  any suggestion are welcome 
@ChrisAlderson  Same

**Comment by vzamanillo** [comment]
Looks pretty good!

About seeding the update if we are on the last version, would not have a negative impact on consumption of network resources on the host machine? should be delimited (clients, bandwith)?

**Comment by team-pct** [comment]
I am still thinking about this side of seeding the update , probably a limit on number of client would be a good start

**Comment by danoctavian** [comment]
will this end up in butter-desktop? what's the relationship with that project in terms of "General" fixes like this one ? (that apply to both)

**Comment by team-pct** [comment]
@danoctavian We will send PR once we finish , then it will depend on the Butter-Desktop Team if they accept our PR

**Comment by team-pct** [comment]
Updater now Seed the update , can be disabled from the settings if needed
