### ISSUE TITLE
0.51 osx arm64 binary is damaged

### ISSUE THREAD

**Issue by mkuznetsov** [popcorntime/popcorntime#3043]
Have Mac mini with m1 and Mac OS sequoia 
1) download zip with binary
2) unpack it and launch
3) system dialog pop up. Application is damaged. 
4) checked privacy&security settings app don't appear in section with manual app accept launch. 

Tried same steps  with osx64 and in privacy&security it appears and I allow it to start. Enter user password in dialog. but It don't work. Just chilling in launch bar and don't show any windows

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by merseyV** [comment]
Yeah ... latest osx64 no longer working on Silicon (and possibly some macIntel too?)

You'll need to strip the quarantine flag/s from your Arm64 download. [Try this](https://github.com/popcorn-official/popcorn-desktop/issues/3000#issuecomment-2092390369)

**Comment by popcorn2024ok** [comment]
Hello friend please dmg new version Mac 2024 september Popcorntime

**Comment by merseyV** [comment]
>please dmg new version

Sorry ... .will only be available as a zip download.

It wouldn't make any difference to Gatekeeper checks, if that's what your thinking?

**Comment by rmelchner** [comment]
i did
` xattr -c "/Applications/Popcorn-Time.app/" 
` 
and it worked - could you try?

**Comment by dzape** [comment]
> i did `xattr -c "/Applications/Popcorn-Time.app/" ` and it worked - could you try?

This worked for me, thainks. I am on macOS Sequoia 15.0.1.
