### ISSUE TITLE
All API are failing to respond after manually switching and reinstalling several times 

### ISSUE THREAD

**Issue by Mobkre** [popcorntime/popcorntime#3046]
Operating System Version:
 Windows 10

Popcorn Time Version:
 0.5.1

Download Date: 
 15/10/2024, 14:43

Download url:
(https://mega.nz/folder/SgpTXCpb#6ZJfAxwl2IV9kHhBHQm0PQ/folder/S4gX3YCI)

Expected Behaviour:
Allow streaming of torrented series/movies/anime
...

Actual Behaviour:
Fail to load the API's to get the torrent
...

Steps to reproduce the behaviour:
1. Install from the download link
2. Extract to its own folder
3. Run the Popcorn time.exe 

Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):
![image](https://github.com/user-attachments/assets/dd2a3800-3fbd-46bb-a1b7-2015cad6df0d)
![image](https://github.com/user-attachments/assets/534c96e6-dfb8-4b83-a7d9-f6403da885ed)
![image](https://github.com/user-attachments/assets/582ac5b8-6baa-4972-a227-897694d8d593)
![image](https://github.com/user-attachments/assets/9d52725c-b824-4c6b-b4bd-0dd2fc7c7880)
![image](https://github.com/user-attachments/assets/f4239529-f3e0-47e9-9f98-ff46ddecef38)

**Comment by dutchy1001** [comment]
Those are not the API's listed to use in issue #3035.
Try those API's and it will work again.

Closing this as there is already a bug report for this.
