### ISSUE TITLE
API Server URLs could not be updated

### ISSUE THREAD

**Issue by gdwmw** [popcorntime/popcorntime#3047]
#### Operating System Version:
Windows 11

#### Popcorn Time Version:
0.5.1

#### Download date:
Today

#### Download url:
Github

#### Expected Behaviour:
Successfully updated API Server URLs

#### Actual Behaviour:

...

#### Steps to reproduce the behaviour:

1. ...
2. ...
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

![Screenshot 2024-10-20 002104](https://github.com/user-attachments/assets/c279e87e-1269-4c55-a4d1-7ab80f11b3af)

**Comment by merseyV** [comment]
Already open: Automatically update API's server URL's not working #3035

**Comment by merseyV** [comment]
Already open: Automatically update API's server URL's not working #3035

For now any API updates can only be done manually. 

For anyone requiring an API update:  `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`

Copy/paste the full-set (above) into the 3 'API Server' address boxes (movie, series, anime) in 'Settings'. Then restart app. (you might still get a transient error message, for about 10secs.)

**Comment by merseyV** [comment]
Already open: **Automatically update API's server URL's not working** #3035

For now any API updates can only be done manually. Anyone requiring an API update:  
`https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`

Copy/paste the full-set (above) into the 3 'API Server' address boxes (movie, series, anime) in 'Settings'. Then restart app. (you might still get a transient error message, for about 10secs.)

**Comment by merseyV** [comment]
**Stop press!!**
@ivan1986 (and friend) has fixed Automatically update API's. .......... **fix read dht from net**: #3048

**Comment by merseyV** [comment]
**Stop press!!**
Devs have fixed Automatically update API's.
**"Looks like auto-update's back on the menu  boys!"**

![CGWhG9](https://github.com/user-attachments/assets/33e27aa7-fdc0-4c7e-a169-83be1353eee6)

#3048

**Comment by dutchy1001** [comment]
I stll cant see what it updates when clicking on the update button in the settings tab.
@ivan1986, can you explain how the update(to the letter) works as I have conflicting answers?

**Comment by ivan1986** [comment]
@dutchy1001 we use the same library on the client that we use on the server
It seems like it doesn't have a problem with windows now

**Comment by ivan1986** [comment]
oh shit, i need to start a virtual machine, install windows...
