### ISSUE TITLE
Popcorn and Chromium are the same on Ubuntu

### ISSUE THREAD

**Issue by duard** [popcorntime/popcorntime#305]
Operating System Version:
Ubuntu 16.10
GNOME 3.22

Popcorn Time Version: 3.10

Download date: Nov 2

#### Actual Behaviour
When open CHROMIUN and Popcorn, they are the same on the DASHBOARD, both applications has just one ICON => Chromium 

#### Steps to reproduce the behaviour
1 - wget https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-64.tar.xz -O popcorntime.tar.xz
2 - extract
3 - open popcorntime
4 - open chromiun 

Look on the CHROMIUM icon on my Dash Dock Bar, are 2 circles, one for chromium and the another for PopcornTime 

![screenshot from 2016-11-02 19-56-22](https://cloud.githubusercontent.com/assets/36894/19948995/7b5a1eec-a136-11e6-8496-6f600822ce52.png)

**Comment by Persei08** [comment]
Hi,

I have this too.

I use PCT 3.10 and Ubuntu 14.04 with unity desktop

**Comment by ChrisAlderson** [comment]
What version of Chromium are you using because I cannot reproduce this issue with Chromium Version 54.0.2840.71 (64-bit).

**Comment by duard** [comment]
Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)
installed via => apt install chromium

**Comment by Persei08** [comment]
Hi,
Hmm, I was a bit wrong here. For me it's 2 icons both with chromium icon. Maybe it's a different bug :|

![capture du 2016-11-03 15 02 29](https://cloud.githubusercontent.com/assets/22459458/19968868/3e11c1e6-a1ce-11e6-87f4-4a96294b1fe7.png)

If it's always helpfull Chromium 53.0.2785.143-0ubuntu0.14.04.1.1142

**Comment by duard** [comment]
I think is the same bug.
The diference is because I'm using Gnome 3 + Dash Dock and you are using Unit.
On my screenshot you can see TWO chromiuns indicators

**Comment by valentinconesa** [comment]
Same problem here.  Chromium  55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
![bug](https://cloud.githubusercontent.com/assets/1935754/22853907/15d0a3d6-f062-11e6-93c9-56fba62e617f.png)

**Comment by simplemachine-zz** [comment]
Same here, any solutions?

**Comment by cerberus10** [comment]
still having the same issue with the lastest version. Any tips on workarounds?

**Comment by simplemachine-zz** [comment]
@cerberus10:
You can choose to use Chrome instead of Chromium, or another browser. I just managed to solve it that way.

**Comment by cerberus10** [comment]
I think this is still and issue in the other builds

**Comment by TheSecureTux** [comment]
Hi, this is still a problem. Ubuntu 17 + Chromium and Popcorn time at the last version, I can't open Chromium unless I do it from the command line. Clicking the Chromium icon always opens "Butter" rendering Chromium unusable.

**Comment by fpoletto** [comment]
It certainly has something to do with this file that Popcorntime creates at the **/.local/share/applications/** folder. It's called chromium-browser.desktop (wich means is a shortcut to be placed on the desktop).

Here are the contents:

_[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Butter
Icon=chromium-browser.png
Exec=/opt/popcorntime/Popcorn-Time
StartupNotify=false
StartupWMClass=Chromium-browser
OnlyShowIn=Unity;
X-BAMFGenerated=true_

I don't know what some of these entrances mean, but I'm sure it says to run Popcorn-Time every time you type chromium-browser, and it has the chromium icon.

I hope it helped.

**Comment by roma-guru** [comment]
Try to remove this _chromium-browser.desktop_ from **~/.local/share/applications** and replace it with popcorn-time.desktop:
```ini
[Desktop Entry]
Version=1.0
Type=Application
Name=Popcorn Time
Icon=/absolute/path/to/Popcorn-Time.png
Exec=/absolute/path/to/Popcorn-Time
Comment=Time for Popcorn
Categories=Internet;
Terminal=false
```
BTW - [here](https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html) is file format spec.

**Comment by philipvdp** [comment]
I have the exact same issue. Recently installed popcorn time and I have Chromium.
Is it possible to have a more extensive helpme to change both the .desktop files? Preferably without using the terminal.

Thank you in advance

**Comment by Persei08** [comment]
@philipvdp 

1. Open ~/.local/share/applications in your file manager
2. Rename chronium-browser.desktop into popcorn-time.desktop
3. Edit this `popcorn-time.desktop` file and replace the **Icon** and **Exec** values by the path to your PT icon and the path of PT binary
4. Save
5. Double click this `popcorn-time.desktop` to be sure it launch PT. If it don't work, go back to step 3.
6. Check it appear in your applications menu, if not, logout and login to your session or restart

**Comment by fergusincoronato** [comment]
StartupWMClass is only used to group windows with the same class name. You need to look at changing the class with the exec command if the program supports gtk options.

Try running the executable with `--class="Popcorn-Time"`. Worked for me.

See also:
· https://askubuntu.com/a/809353/545569
· https://github.com/micheleg/dash-to-dock/issues/483
· https://elementaryos.stackexchange.com/a/16088/10290

**Comment by jpsmaia** [comment]
Clean install from this link
https://gist.github.com/flyingluscas/a462388c9452d2d71485a4035d577160

Replace step 4 from here

4. Creating the application launcher

sudo nano /usr/share/applications/popcorntime.desktop

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Popcorn Time
Exec=/opt/popcorntime/Popcorn-Time --class="Popcorn-Time"
Icon=/opt/popcorntime/src/app/images/icon.png
Categories=Application;

**Comment by Kr3m** [comment]
> Clean install from this link
> https://gist.github.com/flyingluscas/a462388c9452d2d71485a4035d577160
> 
There's no need to do a clean install.  Simply modifying popcorntime.desktop and relaunching should fix the issue.

**Comment by gaugedev2** [comment]
Sometimes `Exec=/opt/popcorntime/Popcorn-Time --class="PopcornTime"` might work (notice the missing `-` in class name.

**Comment by avra911** [comment]
Sometimes `Exec=/opt/popcorntime/Popcorn-Time --class="PopcornTime"` might work (notice the missing `-` from the class name.
