### ISSUE TITLE
IMDB Score never accurate - Please automatically update IMDB scores every once in a while

### ISSUE THREAD

**Issue by Endrit-alt** [popcorntime/popcorntime#3050]
Hey,

I rely on IMDB score's to decide what movie I want to watch. On popcorntime the IMDB scores shown, rarely match the actual IMDB scores on the IMDB website.

Is it possible to have the IMDB scores refresh weekly/monthly especially in the first few months of a movie release? The older a movie is, the less it could be refreshed.

Example : 
- IMDB score on popcorntime : 8.2/10
- Actual IMDB score on the website : 4.6/10

(in this scenario my time has been wasted because I have to double check the score on the official website of IMDB.)

Example 2 : 
- IMDB score on popcorntime : 4/10
- Actual IMDB score on the website : 7.5/10

(In this scenario, I've skipped this movie, whilst if the actual real score was shown I would have probably watched it.)

Best regards,
Endrit

**Comment by dutchy1001** [comment]
This is because the ratings shown are not from IMDB but from [TMDB](https://www.themoviedb.org/?language=en).
The reason behind this is because you have to pay to use the IMDB API  and the TMDB is free.

Closing this as it's not an issue. Feel free to reply further here if needed.
