### ISSUE TITLE
Please update this APP

### ISSUE THREAD

**Issue by fisforfaheem** [popcorntime/popcorntime#3052]
Please update the APP

**Comment by fisforfaheem** [comment]
???

**Comment by merseyV** [comment]
>???

Lol ... Exactly! I think that's the reason! Not specific enough?

By all means post about an issue, or request a particular feature. I doubt the app will be updated unless/until the Devs have a "body of work" to incorporate into a new release. Or if the Popcorntime app falls-over (maintenance mode). 

As you have some coding skills: If you want to "rustle-up" a few tidbits yourself  - please feel free to present any solutions .. for build testing.

"The only way to improve your coding skills is to share your knowledge and help others" .... wise words!

**Comment by merseyV** [comment]
>???

Lol ... Exactly that!  Not specific enough?

By all means post about an issue, or request a particular feature. I doubt the app will be "updated" unless/until the Devs have a "body of work" to incorporate into a new release. Or if the Popcorntime app falls-over (maintenance mode). 

As you have some coding skills: If you want to "rustle-up" a few tidbits yourself  - please feel free to present any solutions .. for build testing.

"The only way to improve your coding skills is to share your knowledge and help others" .... wise words!

**Comment by merseyV** [comment]
>???

Lol ... Exactly that!  Not specific enough?

By all means post about an issue, or request a particular feature. I doubt the app will be "updated" unless/until the Devs have a "body of work" to incorporate into a new release. Or if the Popcorntime app falls-over (maintenance mode). 

As you have some coding skills: If you want to "rustle-up" a few tidbits yourself  - please feel free to present any solutions .. for build testing.

"The only way to improve your coding skills is to share your knowledge and help others" .... wise words!
