### ISSUE TITLE
Seasons/Eps not showing

### ISSUE THREAD

**Issue by PsycloneTM** [popcorntime/popcorntime#3057]
#### Operating System Version:

Windows 11
#### Popcorn Time Version:

#2984 
#### Download date:

When the new release came out.
#### Download url:

https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.5.1
#### Expected Behaviour:

...
Show all seasons or episodes.
#### Actual Behaviour:

...
It has missing seasons or episodes. I understand that some shows might not have places available to watch that season or ep but I think it still should be shown.
#### Steps to reproduce the behaviour:

1. Go to any show (ex Outer Banks)
2. Try to find season 3.
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

![image](https://github.com/user-attachments/assets/a7cbed28-b286-4296-a3dd-f44bba42abeb)

**Comment by dutchy1001** [comment]
PCT is depending on a 3rd party API, if the API cant find it PCT cant show it.
This API is out of our control to what it finds.

This is not an issue from PCT so I will close this. Feel free to comment after if needed

**Comment by merseyV** [comment]
If what you're looking for isn't in the movie/series tab - PTapp has a torrent search feature: Click on the 'Torrent Collection' link (three lines icon, top-right) and put `Outer Banks S03` into the search box. 

Click on the file name that suits you (size, quality, seeds?). In the episodes window click on "Store this torrent", for easier access later. And choose your playback option (if there's a choice?) on the right. Just click on the episode to playback.
