### ISSUE TITLE
Video quality selector UX issue

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#306]
![popcorn time video quality selector ux issue](https://cloud.githubusercontent.com/assets/1769879/19951888/cff73954-a13f-11e6-8d4a-2ca1fe9ca391.png)

**Comment by team-pct** [comment]
Can you Send a PR about that?

**Comment by ghost** [comment]
Sure! https://github.com/butterproject/butter-desktop/pull/471
Is that correctly done?, sorry, I'm not familiarised with GitHub (designer, ahem), let me know if I made the PR in the way that you expect. Thanks.

**Comment by team-pct** [comment]
Please follow these steps
- Fork The Repo
- Make your changes 
- Open PR on the same branch that you have forked from

Worst case scenario , fork and let me know i will open the PR for you

**Comment by ghost** [comment]
Sorry, but I don't get it.

I'm here, the selected branch is "Development"
![image](https://cloud.githubusercontent.com/assets/1769879/19960196/08e8a05a-a18a-11e6-960e-0c20bf768582.png)

I click on "New pull request" and I get this (that's what I did before)
![image](https://cloud.githubusercontent.com/assets/1769879/19960092/70285568-a189-11e6-949e-a32ec3a1f5d8.png)

Please let me know exactly what to do and sorry for the inconvenience.

**Comment by team-pct** [comment]
You have first to fork the repo , You can click directly on Fork Icon 
Once you have the repo on your github account make the needed changes for quality selector 
Then submit PR

**Comment by ghost** [comment]
Oh, I think I understand now. You are saying that I make the changes on the code. 

This is a design decision that is better considering before do any code work. Is a analysis of a little UX problem and a solution on how to solve it (with arguments and some UI wireframes).

Maybe this is not the right place to work on this type of design problems?
If exist a right way to let the design team look my suggestion, let me know. I see the "Issue" tab and think that was the more appropriate way to do it, that's why I put this here.

Thanks!

**Comment by team-pct** [comment]
Understood , i  will let this issue open until someone will want to implement it

**Comment by Persei08** [comment]
I'm ok with problem 1 and 2:
1. Not clear what option is selected
2. Color contrast problem on blue option
but I think it's ok to keep "XXXp" naming. Youtube use that naming, torrent trackers use it too and most of the users know what it is about. so, i'm not convinced the "quality" label is relevant too.

I can make few changes for adding a round corners background on the selected quality. it's just easy changes in themes files.
