### ISSUE TITLE
All links are expired 

### ISSUE THREAD

**Issue by popcorn2024ok** [popcorntime/popcorntime#3060]
![Screenshot_20241118_233312_Chrome](https://github.com/user-attachments/assets/b176c780-f8c7-4d59-a90c-89215152ccf8)

All links are expired the new version popcorntime for the mac version stable

**Comment by merseyV** [comment]
Ignore them. The only links you need are [these!](https://github.com/popcorn-official/popcorn-desktop/releases)?

**Comment by merseyV** [comment]
Ignore them (not significant). The only links you need are [these!](https://github.com/popcorn-official/popcorn-desktop/releases)

**Comment by merseyV** [comment]
Ignore them (not significant). The only links needed (for now)are [these!](https://github.com/popcorn-official/popcorn-desktop/releases)

**Comment by merseyV** [comment]
Forget them (not significant). The only links needed (for now) are [these!](https://github.com/popcorn-official/popcorn-desktop/releases)

**Comment by merseyV** [comment]
Forget them (wasn't significant). The only links needed (for now) are [these!](https://github.com/popcorn-official/popcorn-desktop/releases)
