### ISSUE TITLE
"Memory leaks", increased GPU usage, etc...

### ISSUE THREAD

**Issue by seeingterra** [popcorntime/popcorntime#3061]
So not much a bug report (perhaps) at this point perhaps.

There are plenty of logical reasons why memory leaks happen within software in general. Some times it's an oversight, in modern times it might be a mining script let loose. Popcorn time is a perfect app to apply some kick-back methods too. Hell, I don't judge you pretty much what-so-ever! Hey, you created a simple platform to view on demand content. Like in my case I am able to watch some movies and shows in better quality than the OG platforms are able to deliver. I subscribe to the services of which that carries some shows i rather stream to PT so I can get proper resolution and HDR support. So good enough for me.

Guys, gals.. If you do some mining through this app, go for it. My recommendation is that you stand with by it and add it as part of your clause. Your work should be rewarded, but "opt in" the user in this experience. I bet a good amount of people would spare some resources for you to mine, and even leave the app open for longer if you did. 

If you like to disrupt. this is a surprisingly clean way!

Thanks for following up on PopcornTime, but some times we use your app while multitasking heavy workloads. If you give us an option to throttle the mining it will incentivize a lot of users to fairly share resources in a much greater extent. Imagine actually getting proper I/O access voluntarily?

Just do an opt in or opt out! You will be respected for it

#### Expected Behaviour:

...

#### Actual Behaviour:

...

#### Steps to reproduce the behaviour:

1. ...
2. ...
3. ...

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads just use a generic torrent client for downloading. Or just use PTapp when you're having some quiet time?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that would completely debilitate memory in certain circumstances. It's noticeable better now - especially for those of us using minimum memory.

You can try the (limited) dl options in 'Settings'  .. other than that "it is what it is".

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some quiet time?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that would completely debilitate memory in certain circumstances. It's noticeable better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that "it is what it is".

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that would completely debilitate a PC in certain circumstances. It's noticeable better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is".

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that would completely debilitate a PC in certain circumstances. It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is".

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that could completely debilitate a PC in certain circumstances. It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is". 

https://github.com/popcorn-official/popcorn-desktop/issues/2776  
https://github.com/popcorn-official/popcorn-desktop/issues/1373

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that could completely debilitate a PC in certain circumstances. (#1373 , #2776)   It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is". 


**n.b.**
<img width="964" alt="Popcorntime player" src="https://github.com/user-attachments/assets/e725577a-a6ab-4160-bc09-d0fa265e46b0">

Popcorntime (default) video player - playback only!

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here .. ever!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that could completely debilitate a PC, in certain circumstances. (#1373 , #2776)   It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is". 


**n.b.**
<img width="964" alt="Popcorntime player" src="https://github.com/user-attachments/assets/e725577a-a6ab-4160-bc09-d0fa265e46b0">

Popcorntime (default) video player - playback only!

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here .. ever!!! If you want to reduce your overheads -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that could completely debilitate a PC, in certain circumstances. (#1373 , #2776)   It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is". 

**n.b.**

<img width="956" alt="5" src="https://github.com/user-attachments/assets/f4655243-066c-4f5b-9c10-d28829c058d5">


This (popular) 9.5GB / 250 peer download would have froze/crashed after about 30% previously .. before fix!

**Comment by merseyV** [comment]
Lol .. who do you think our Devs are - Gimli and Glóin? 

No mining here .. ever!!! If you want to reduce your "overheads" -  use a generic torrent client for downloading. Or just use PTapp when you're having some "quiet time"?

PT integrates WebTorrent as its torrent client ... that's where most of the usage occurs. If you think it's bad now ... you obviously never experienced some of the earlier versions? 0.5.0 fixed a bug in WebTorrent that could completely debilitate a PC, in certain circumstances. (#1373 , #2776)   It's much better now - especially for those of us with base (spec) memory.

You can try the (limited) dl options in 'Settings'  .. other than that: "it is what it is". 

**n.b.**

<img width="956" alt="5" src="https://github.com/user-attachments/assets/f4655243-066c-4f5b-9c10-d28829c058d5">


This 9.5GB / 250 Peer download would have froze/crashed (for me) at about 30%, previously .. before the Dev fix!
