### ISSUE TITLE
Can't run Popcorntime 0.3.10 with double click on Kubuntu

### ISSUE THREAD

**Issue by Nutomic** [popcorntime/popcorntime#307]
Operating System Version:

Kubuntu 16.10

Popcorn Time Version:

0.3.10

Download date:

today

#### Expected Behaviour

When I double click on `Popcorn-Time`, it should start the program.

#### Actual Behaviour

I get this dialog instead.
![popcorntime](https://cloud.githubusercontent.com/assets/1044450/19952322/ba83b44a-a1a7-11e6-903f-f797288d1ede.png)

Note that `./Popcorn-Time` runs it as expected, and the binary has execute permissions. I didn't have this issue with the previous version.

#### Steps to reproduce the behaviour

1. Download `Popcorn-Time-0.3.10-Linux-64.tar.xz`
2. extract it
3. try to run it

**Comment by Persei08** [comment]
Hi,

Same here.

![screenshot from 2016-11-05 18 07 50](https://cloud.githubusercontent.com/assets/22459458/20032085/b195e3f6-a37a-11e6-8760-0aaaeac2f563.png)

Ubuntu 14.04 64bits

**Comment by Nutomic** [comment]
Is this fixed?

**Comment by randyyaj** [comment]
I don' think this is fixed yet but you can just write a shell script (run.sh) to the same directory and in it add these lines

```
#!/bin/bash
./Popcorn-Time
```

Then save and grant executable permission to the script.

```
chmod +x run.sh
```

Then you will be able to double click or what not on it to launch popcorn time.
Hope this helps!
