### ISSUE TITLE
Cant open movies favorited from watchlist

### ISSUE THREAD

**Issue by tuuuubes** [popcorntime/popcorntime#308]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
November 2nd, 2016

#### Expected Behaviour
Open the movie page upon clicking on it from the Favorites tab

#### Actual Behaviour
Nothing happens

#### Steps to reproduce the behaviour

1. Link takt.tv account
2. Open watchlist tab
3. Favorite any item by clicking on the heart symbol on the bottom right corner of its thumbnail
4. Open favorites tab
5. Clic on the recently added item from step 3

![image](https://cloud.githubusercontent.com/assets/23235491/19963271/ec120b06-a1bb-11e6-9580-2658ddfe4965.png)

**Comment by JimiC** [comment]
Same as #273.

**Comment by JimiC** [comment]
Same issue as #273. (at least on Windows).
![screen shot 11-05-16 at 10 36 am](https://cloud.githubusercontent.com/assets/1716442/20028804/f90bda38-a343-11e6-95ff-aeda2c3bc63a.PNG)

**Comment by maclir** [comment]
The same issue arises when you click on an item in the watch list:

1. Link takt.tv account
2. Open watchlist tab
3. Click on any show/movie

**Comment by kunalgolani** [comment]
The watchlist is not opening for me on Mac OS X, app v0.3.10.

![image](https://cloud.githubusercontent.com/assets/3034551/23187501/50720a8a-f88b-11e6-91dd-06764da87476.png)

**Comment by JimiC** [comment]
This is a known issue. I have managed to have it working by 90%. The only thing I still have to figure out is how to resolve the torrents object. Due to lack of free time this may take a while.

**Comment by kunalgolani** [comment]
@JimiC maybe I can help. Whenever you have time, can you point me to the problem and your 90% solution?

**Comment by JimiC** [comment]
@kunalgolani I haven't pushed the code on my fork yet. The solution is to map in `watchlist/details` the info that comes from `tract.tv` to the respective `Model` (`movie`, `show`) that `popcorn` can handle. I have it all mapped except the `torrents` object. Once this is achieved the `watchlist` will be fully functional again.

**Comment by JimiC** [comment]
@kunalgolani I finally found the time to push my attempt to fix the `watchlist` provider. You can find it @ https://github.com/JimiC/popcorn-desktop/blob/watchlist_fix/src/app/lib/providers/watchlist.js
The `TODO` comments are those that need to be resolved.

**Comment by gabrielbiel7** [comment]
@JimiC hi! how did u fix the watchlist issue? i don't know how to change codes and those stuff, can u guide me? thanks

**Comment by JimiC** [comment]
@gabrielbiel7 Locate `watchlist.js` on your machine and replace the file with the one from the provided link.

**Comment by gabrielbiel7** [comment]
@JimiC can you post a video please? i really don't understand anything. please help me

**Comment by vhoyer** [comment]
so @gabrielbiel7, i can not post a video, due to tecnical reasons, but I'll try to help:

if you are on Windows:
1. open your windows menu and start typing: %appdata%
2. press Ctrl+L you will see the highlighted line, erase the last word and type "Local\Popcorn-Time\src\app\lib\providers" (without the quotes)
3. in that folder you'll find the file JimiC was talking `watchlist.js` (or maybe, just `watchlist`)
4. open [this link](https://raw.githubusercontent.com/JimiC/popcorn-desktop/watchlist_fix/src/app/lib/providers/watchlist.js) and copy its content (Ctrl+A, Ctrl+C)
5. open for `watchlist.js` for edtition (maybe with notepad)
6. replace all content on the file with the one on your clipboard (Ctrl+A, Ctrl+V)

It should work, as far as I understand (if you think something will break, make a backup of your original `watchlis.js` with another name)

If you are on another system... well, try to get around 1 and 2, and start on 3.

**Comment by gabrielbiel7** [comment]
@vhoyer @JimiC thanks so much for the help, i've already changed watchlist.js code, but now there is another error. I am logged into trakt.tv from settings but when a click in the watchlist button, it says that i have to put my credentials. I used this code: https://github.com/JimiC/popcorn-desktop/blob/watchlist_fix/src/app/lib/providers/watchlist.js // photo:
![esbrxhx](https://user-images.githubusercontent.com/35086390/34597282-ebf90162-f1cc-11e7-9513-632f42443392.png)

**Comment by gabrielbiel7** [comment]
While I was using the original code, that issue never happened. it has just started now that i've changed the code. Can you help me again, please? thanks

**Comment by gabrielbiel7** [comment]
why in the original code there are only a few lines, but in the code @JimiC provided, there are more than 200 lines? photo of original code opened in notepad:
![kkakak](https://user-images.githubusercontent.com/35086390/34613192-0b7d6b44-f214-11e7-803e-a4a9849327c7.png)

**Comment by gabrielbiel7** [comment]
can someone answer me, please? i still have this issue.
