### ISSUE TITLE
Anime No Subtitles

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#310]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
31/10/2016

#### Expected Behaviour
To have subtitles in the Anime movies and TV shows

#### Actual Behaviour
Anime doesn't have any subtitles and i can't watch them because they are in Japanese

#### Steps to reproduce the behaviour
To add subtitles in Anime movies and TV shows

**Comment by ChrisAlderson** [comment]
VideoJS doesn't support SSA/ASS. All the anime content should have subtitles in this format which can be viewed in VLC.
