### ISSUE TITLE
Issue with thumbnail images

### ISSUE THREAD

**Issue by JimiC** [popcorntime/popcorntime#313]
Operating System Version:
All OS

Popcorn Time Version:
0.3.10

**Problem:**
Turns out that thumbnail images are mostly fetched from [fanart](https://fanart.tv/). Unfortunately this service has a slow response time.

I have noticed that some images are trying to be fetched from `walter.trakt.us` and they fail because this service has been moved to `walter.trakt.tv`.

**Solution:**
Consider switching the image fetching to https://walter.trakt.tv/

**Comment by VitorVRS** [comment]
The image URL's come from API, popcron just use it to show.
Maybe @ChrisAlderson can solve this?

**Comment by JimiC** [comment]
@VitorVRS I'm totally aware of that, but have no clew who is controlling the API or where that project is.

**Edit:** I take my above statement back, the API project is obviously at https://github.com/popcorn-official/popcorn-api 🐵

**Comment by JimiC** [comment]
Opened this issue on API project at https://github.com/popcorn-official/popcorn-api/issues/49.

Consider leaving this issue open until issue on API project is discussed or resolved.

**Comment by ChrisAlderson** [comment]
Move the discussion to https://github.com/popcorn-official/popcorn-api/issues/49, `popcorn-desktop` has no relevant code which can resolve this issue.
