### ISSUE TITLE
Replace Mousetrap by Nw.Shortcut

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#315]
Mousetrap is buggy 
Why not use Nwjs Shortcuts ? http://docs.nwjs.io/en/latest/References/Shortcut

**Comment by ChrisAlderson** [comment]
http://docs.nwjs.io/en/latest/References/Shortcut

> // Register global desktop shortcut, which can work without focus.

http://docs.nwjs.io/en/latest/References/App/#appregisterglobalhotkeyshortcut

> Register a global keyboard shortcut (also known as system-wide hot key) to the system.

Shortcuts by nwjs don't work in our case.
