### ISSUE TITLE
Thumbnails are not loading on Linux (Ubuntu Gnome 16.10)

### ISSUE THREAD

**Issue by mangkukulam** [popcorntime/popcorntime#318]
Operating System Version:
Linux 4.8.0-26-generic  28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Popcorn Time Version:
0.3.10 Beta

Download date:
6 Nov 2016

#### Expected Behaviour
Should show thumbnails in Movie, TV show and Favorites lists

#### Actual Behaviour
Does not load any of the thumbnails mentioned above

#### Steps to reproduce the behaviour
Just open the application.

![screenshot from 2016-11-06 19-52-13](https://cloud.githubusercontent.com/assets/183945/20040140/963ed47e-a45a-11e6-9c18-587a1029dd01.png)

#### Other details:

In the developers tools it shows that it tries to fetch multiple of the images required but the never seem to start downloading. The stay in Pending status. If I copy the link to another browser then the image starts to load.

![screenshot from 2016-11-06 19-55-23](https://cloud.githubusercontent.com/assets/183945/20040171/44769ff4-a45b-11e6-9eb2-0c7dbf3e862e.png)

**Comment by VitorVRS** [comment]
Actually, they load, but its very slow.
See this topic for more info: https://github.com/popcorn-official/popcorn-desktop/issues/313
