### ISSUE TITLE
Last working version??

### ISSUE THREAD

**Issue by voddan** [popcorntime/popcorntime#322]
Hi! 
I am sorry to say that, but I can't find a single version of Popcorn Time which would work after building from sources.

I've tried: master, development, 0.3.10

All those builds result in an app which does not show the movie lists themselves. It is just black windows with all the other buttons at place.
![butter_and_popcorn-desktop_ _nwjs_helper_ _gulp_term_program_apple_terminal_shell__bin_bash_ _80x24](https://cloud.githubusercontent.com/assets/5666566/20055641/2b9f91b4-a4f3-11e6-9a7f-22464f244ce7.jpg)

Operating System Version:
OS X 10.11

Steps to reproduce:

- cd popcorn-desktop
- git checkout <version>
- chmod +x ./make_popcorn.sh
- pressing "yes", then "no"
- gulp run

**Comment by VitorVRS** [comment]
Cleanup your project and at branch development, run:
- npm install
- gulp build
- gulp run

Paste here PCT error log, you can get them on developer tools  (F12)

**Comment by voddan** [comment]
> Database path: /Users/voddan/Library/Application Support/Popcorn-Time/Default
> app.js:11 [INFO] Scanning: Local Network for Airplay devices
> app.js:11 [INFO] Scanning: Local Network for DLNA devices
> app.js:11 [INFO] Scanning: Local Network for Chromecast devices
> app.js:11 [INFO] Scanning: /usr/bin
> app.js:11 [INFO] Scanning: /usr/local/bin
> app.js:11 [INFO] Scanning: /Applications
> app.js:11 [INFO] Scanning: /Users/voddan/Applications
> bootstrap.js:61 loading npm /butter-settings-/ butter-settings-popcorntime.io
> bootstrap.js:24 loading local provider cache_provider.js
> bootstrap.js:24 loading local provider cache_providerv2.js
> bootstrap.js:24 loading local provider favorites.js
> bootstrap.js:24 loading local provider opensubtitles.js
> bootstrap.js:24 loading local provider torrent_cache.js
> bootstrap.js:24 loading local provider trakttv.js
> bootstrap.js:24 loading local provider tvshowtime.js
> bootstrap.js:24 loading local provider watchlist.js
> bootstrap.js:61 loading npm /butter-provider-/ butter-provider-movies
> generic.js:27 added MovieApi to provider registry
> bootstrap.js:61 loading npm /butter-provider-/ butter-provider-tvapi
> generic.js:27 added TVApi to provider registry
> bootstrap.js:61 loading npm /butter-provider-/ butter-provider-anime
> generic.js:27 added AnimeApi to provider registry
> bootstrap.js:61 loading npm /butter-provider-/ butter-provider-vodo
> generic.js:27 added vodo to provider registry
> app.js:11 [INFO] Found External Player: VLC in /Applications/VLC.app/Contents/MacOS
> app.js:11 [INFO] External Players: scan finished
> bootstrap.js:35 loaded cache_providerv2.js
> generic.js:27 added Favorites to provider registry
> bootstrap.js:35 loaded favorites.js
> bootstrap.js:35 loaded cache_provider.js
> generic.js:27 added TorrentCache to provider registry
> bootstrap.js:35 loaded torrent_cache.js
> generic.js:27 added OpenSubtitles to provider registry
> bootstrap.js:35 loaded opensubtitles.js
> generic.js:27 added Trakttv to provider registry
> bootstrap.js:35 loaded trakttv.js
> generic.js:27 added Watchlist to provider registry
> bootstrap.js:35 loaded watchlist.js
> app.js:11 [INFO] Loading DB
> generic.js:27 added TVShowTime to provider registry
> bootstrap.js:35 loaded tvshowtime.js
> app.js:11 [INFO] Spawning new provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/, Object
> app.js:11 [INFO] Spawning new provider TVApi?&apiURL=https://tv-v2.api-fetch.website/, Object
> app.js:11 [INFO] Spawning new provider AnimeApi?&apiURL=https://anime.api-fetch.website/, Object
> app.js:11 [INFO] Spawning new provider vodo Object
> app.js:11 [INFO] Spawning new provider OpenSubtitles Object
> app.js:11 [INFO] Spawning new provider Trakttv Object
> app.js:11 [INFO] Spawning new provider TVShowTime Object
> app.js:11 [INFO] Spawning new provider TorrentCache Object
> generic.js:27 added ysubs to provider registry
> app.js:16 [WARNING] I loaded ysubs from npm but you didn't add it to your package.jsonwin.warn @ app.js:16
> app.js:11 [INFO] Spawning new provider ysubs Object
> bootstrap.js:107 loaded Array[9]
> app.js:11 [INFO] Initializing HTTP API server
> app.js:11 [INFO] Returning cached provider Trakttv
> app.js:11 [INFO] Returning cached provider TVShowTime
> app.js:11 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,
> generic_collection.js:116 pre--- undefined undefined Array[1]
> generic_collection.js:19 pre all Array[3]
> app.js:11 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,
> app.js:11 [INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,
> app.js:11 [INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,
> app.js:11 [INFO] Returning cached provider vodo
> app.js:6 [DEBUG] Butter 0.3.10 startup time: 10444.180ms
> app.js:6 [DEBUG] Updating to version 0.3.11-0
> generic_collection.js:24 post all Object true true
> generic_collection.js:126 provider error err ReferenceError: images is not defined(…)(anonymous function) @ generic_collection.js:126
> generic_collection.js:116 pre--- undefined undefined Array[1]
> generic_collection.js:19 pre all Array[3]
> app.js:6 [DEBUG] Downloading update... Please allow a few minutes
> app.js:6 [DEBUG] Update downloaded!
> app.js:6 [DEBUG] Verifying update authenticity with SDA-SHA1 signature...
> generic_collection.js:24 post all Object true true
> generic_collection.js:126 provider error err ReferenceError: images is not defined(…)(anonymous function) @ generic_collection.js:126

![developer_tools_-_chrome-extension___hecfofbbdfadifpemejbbdcjmfmboohj_src_app_index_html_and_popcorn-time_and_popcorn-desktop_ _nwjs_helper_ _gulp_term_program_apple_terminal_shell__bin_bash_ _80x24](https://cloud.githubusercontent.com/assets/5666566/20057835/d8b859b6-a4fe-11e6-92cb-690ee6099355.jpg)

**Comment by VitorVRS** [comment]
Sorry, i could't go deeper on this. If you download our latest build, it works?
It shows the same error on master and 0.3.10?

What node version are you using?

**Comment by voddan** [comment]
The latest build from the site works. My node is v6.1.0.

Also, a couple of months ago I build PCT from `development`, and it worked. I wonder what has changed and when. My commuter setup stayed the same, that is for sure.

**Comment by team-pct** [comment]
@voddan git stash / rm -rf node_modules / git pull / NPM install / gulp build / gulp run

**Comment by voddan** [comment]
@team-pct that worked! Thank you!

Could you please fix the `make_popcorn.sh` so that it includes this sequence?
