### ISSUE TITLE
Anime list does not load most icons

### ISSUE THREAD

**Issue by voddan** [popcorntime/popcorntime#326]
Operating System Version:
OS X 10.11

Popcorn Time Version:
Version 0.3.10 (0.3.10)
branch `development` commit 5aabb4b810d48c36501ae7342d09f728edc290be

Download date:
2016/11/09

#### Expected Behaviour
Show the anime list with icons of the series

#### Actual Behaviour
Most of the anime icons did no load; the default place holder was shown instead

![popcorn-time](https://cloud.githubusercontent.com/assets/5666566/20138784/796abd8c-a693-11e6-87de-24486c6aa857.jpg)

#### Steps to reproduce the behaviour

 - Start PCT
 - Go to the "Anime" tab

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-api/issues/49
