### ISSUE TITLE
Make IMDB ratings updated

### ISSUE THREAD

**Issue by DragonzMaster** [popcorntime/popcorntime#327]
Operating System Version:

Win 10 64x
Popcorn Time Version:

3.10
Download date:

7/11

The IMDB ratings are differ from ratings on site, So please is there any chance to get rantings from IMDB live and keep it up-to-date.
Thanks in advance.

**Comment by ChrisAlderson** [comment]
Ratings don't come from [IMDB](https://imdb.com/), they come from [Trakt.tv](https://trakt.tv/').

**Comment by DragonzMaster** [comment]
I got it, but why not using IMDB rating (with this one) ??

**Comment by ChrisAlderson** [comment]
Why do you think the IMDB rating is more important than the Trakt.tv one.

**Comment by DragonzMaster** [comment]
No but usually there would be more than one rating like Rotten Tomatoes or Meta Critic and may be not all people depends on trakt.tv for ratings. As example (for me) I usually don't watch movies less than 6.5 (IMDB) so sometimes ratings are important. It is just an opinion 😄
