### ISSUE TITLE
PopcornTime Takes A Long Time To Open

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#328]
Operating System Version:
Windows

Popcorn Time Version:
0.3.10

Download date:
31/10/2016

#### Expected Behaviour
To start immediately when i open it

#### Actual Behaviour
The app takes like 30 seconds to open

#### Steps to reproduce the behaviour
Make the app open faster

**Comment by ChrisAlderson** [comment]
Popcorn Time basically is a web browser (Chromium). This issue lays outside of the scope of this project.

**Comment by Cyclone47** [comment]
Chrome does not take 30 seconds to start up.
Popcorn time takes up to a minute to start up on an SSD.
