### ISSUE TITLE
Old Domain in make_popcorn.sh

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#33]
Saying "yes" to the first question in the script breaks it because popcorntime.io is down:

```
Looks like we are inside a git repository, do you wish to clone inside it? (yes/no) [no] yes
You've chosen to clone inside the current directory
Cloning Popcorn Time
Where do you wish to clone popcorn time to? [popcorn-app] 
Cloning into 'popcorn-app'...
fatal: unable to access 'https://git.popcorntime.io/popcorntime/desktop.git/': Failed to connect to git.popcorntime.io port 443: Connection timed out
Popcorn Time encountered an error and could not be cloned
```

**Comment by 394394394** [comment]
Hello @cathalgarvey,

You probably wouldn't believe me, but I came here just to start work to update the [make_butter.sh](https://github.com/popcorn-official/popcorn-desktop/blob/1783d2fadc2e3ae1cc8d1fc11481e54ed025f56d/make_butter.sh) file.

If you have a `make_popcorn.sh` file then you're probably using the old repository. Please make sure that you pulled from https://github.com/popcorn-official/popcorn-desktop.git.

Sadly the `make_butter.sh` script won't ~~work~~ download Popcorn Time. Try the [Getting Started](https://github.com/popcorn-official/popcorn-desktop#getting-started) guide. If you have any problems we can help.

Cheers.

**Comment by ghost** [comment]
I got it from the "official" linux download on the website rather than from Github! So, easy solution?

On 25 February 2016 22:45:03 GMT+00:00, 394394394 notifications@github.com wrote:

> Hello @cathalgarvey,
> 
> You probably wouldn't believe me, but I came here just to start work to
> update the
> [make_butter.sh](https://github.com/popcorn-official/popcorn-desktop/blob/1783d2fadc2e3ae1cc8d1fc11481e54ed025f56d/make_butter.sh)
> file.
> 
> If you have a `make_popcorn.sh` file then you're probably using the old
> repository. Please make sure that you pulled from
> https://github.com/popcorn-official/popcorn-desktop.
> 
> Sadly the `make_butter.sh` script won't work. Try the [Getting
> Started](https://github.com/popcorn-official/popcorn-desktop#getting-started)
> guide. If you have any problems we can help.
> 
> Cheers.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/popcorn-official/popcorn-desktop/issues/33#issuecomment-189017181

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 394394394** [comment]
That's odd. Did you get it from the https://popcorntime.sh website? If so then we'll need to wait for a dev to show up since that file (apparently) shouldn't exist.

The latest version can be downloaded from [here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/).

**Comment by z11h** [comment]
@394394394 do you know why the make_butter.sh isnt working (i might have it working)

**Comment by 394394394** [comment]
It should work but it would build [Butter](https://github.com/butterproject/butter-desktop) instead of Popcorn Time. There's a [make_popcorn.sh](https://github.com/popcorn-official/popcorn-desktop/blob/master/make_popcorn.sh) now. Please pull the latest commits. If you have any problems we can help.

**Comment by 394394394** [comment]
Hey @cathalgarvey, can we close this? Is it working now?
