### ISSUE TITLE
How to upgrade (keep existing settings)

### ISSUE THREAD

**Issue by zainengineer** [popcorntime/popcorntime#331]
Operating System Version:
Linux
Popcorn Time Version:
Upgrading to 3.1.0

Download date:
 Today

#### Expected Behaviour
Suggest to import previous settings
...

#### Actual Behaviour
Initializes new settings
...

#### Steps to reproduce the behaviour

1. Install an old version 
2. Then Download and run newer version
3. ...

**Comment by ChrisAlderson** [comment]
There is an option to export (and import the databasese).
