### ISSUE TITLE
Fake ratings

### ISSUE THREAD

**Issue by angelfae** [popcorntime/popcorntime#334]
Operating System Version:
Windows 8

Popcorn Time Version:
0.3.10-0

Download date:
November 10 2016

#### Expected Behaviour
Show me each movie's actual IMDB's rating
...

#### Actual Behaviour
Some movies ratings seem completely random, they don't match their actual IMDB page

#### Steps to reproduce the behaviour

1. Open the app
2. ...
3. ...

**Comment by r-e-l1** [comment]
yes. I don't know if its fake or not but for sure not true

**Comment by Persei08** [comment]
I think ratings come from Trakt.tv datas.
I replied to someone about that on reddit: [Whats up with fake ratings for movies??](https://www.reddit.com/r/PopCornTime/comments/5auqvk/whats_up_with_fake_ratings_for_movies/)

**Comment by ChrisAlderson** [comment]
what @Persei08 said.
