### ISSUE TITLE
Slow thumbnail loading/ not loading

### ISSUE THREAD

**Issue by angelfae** [popcorntime/popcorntime#335]
Operating System Version:
Windows 8

Popcorn Time Version:
0.3.10-0

Download date:
November 10 2016

#### Expected Behaviour
That each movie listed has a thumbnail of its poster
...

#### Actual Behaviour
The  space above the movie tittle sometimes stays completely blank, or shows pocoli
...

#### Steps to reproduce the behaviour

1. Open the app
2. Go past the first set of movies shown on the trends sorting
3. Or pick any other type of sorting

**Comment by team-pct** [comment]
https://github.com/popcorn-official/popcorn-api/issues/49
