### ISSUE TITLE
Audio Out of sync

### ISSUE THREAD

**Issue by Crayy** [popcorntime/popcorntime#336]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3. 10

Download date:
5.11.16

#### Expected Behaviour
Audio in sync with video 
...

#### Actual Behaviour
Audio not in sync with video. 
...

#### Steps to reproduce the behaviour

Seems like it starts to happen after 30-60 minutes and only gets worse. At around 60-70 minutes I estimate its lagging with around 1 sec delay. 
. Is there any fixes or solutions about this? Worked  fine before update

**Comment by ChrisAlderson** [comment]
Give a specific issue case and I'll re-open
