### ISSUE TITLE
Ubuntu unity icon

### ISSUE THREAD

**Issue by zainengineer** [popcorntime/popcorntime#338]
### Description

Application does not create unity Icon
### Steps to Reproduce

1. Download and run application

**Expected behavior:** [What you expect to happen]
Unity Popcorn time icon is created.
It was created by old popcorn time version
I found a snippet online but it is not part of current repository
http://askubuntu.com/a/433445/554554

**Actual behavior:** [What actually happened]

No unity icon is created
### Technical details
 
- Please include your OS and what version of the OS you're running.
  Ubuntu 
- Please mention the version of Butter you're running (find out in the About tab).
0.3.10 beta
- Open the developer tools (F12 or cmd+0) and report any error (in red) from the "console" tab.
no error messages

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-desktop/blob/development/Create-Desktop-Entry

it's a bash script.
