### ISSUE TITLE
Video reproduction not fluid

### ISSUE THREAD

**Issue by marcomontani** [popcorntime/popcorntime#339]
Operating System Version:
 Windows 10 Home x64

Popcorn Time Version:
3.10

#### Expected Behaviour
The video stream should be fluid (all episode already downloaded)

#### Actual Behaviour
Whenever i move the mouse, it has "lags".
I think there is a problem reproducing videos with high density monitors (3200x1800px).
The problem does only appear when i use the butter video player, not with VLC for example.
Also, it get's better if i watch the video in windowed mode with a smaller window

#### Steps to reproduce the behaviour
1. Open the application
2. Pick a film
3. move the mouse during reproduction

**Comment by ChrisAlderson** [comment]
Probably fixed when #96 is fixed.
