### ISSUE TITLE
Chromecast Video Controls Not Forwarding or Rewinding.

### ISSUE THREAD

**Issue by jamesvillarrubia** [popcorntime/popcorntime#340]
Operating System Version:
OS X 10.12

Popcorn Time Version:
3.10

Download date:
Nov 13

#### Expected Behaviour
Expected fast forward button on chromecast option to actually fast forward. 

#### Actual Behaviour
 instead it jumps me back to the opening of the movie.

#### Steps to reproduce the behaviour
1. Turn off VPN
2. Open PT
3. Select movie
4. Select Chromecast
5. Turn on VPN
6. Click watch movie.
7. Wait for movie to start playing.
8. Click fast forward.

**Comment by ChrisAlderson** [comment]
Don't do step 5.

**Comment by Breaking1** [comment]
@ChrisAlderson  is there no easy way to fix this? I deff need my VPN running when using popcorntime and it was super annoying that there was no way to get back to a point in the movie/serie without having to watch the hole thing over again when using Chromecast.

**Comment by team-pct** [comment]
I can confirm the bug , 
Not only Behind VPN 

I will fix that

**Comment by NoelArzola** [comment]
I'm sure you know as it's prob cast coding related just wanted to add same issue on Windows 10 version 3.10

**Comment by team-pct** [comment]
Fixed on d0bcd1cd1e9b24b5b81998bc5c8e75d8459ee67c

**Comment by cyberhck** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/d0bcd1cd1e9b24b5b81998bc5c8e75d8459ee67c#r39329006
