### ISSUE TITLE
Problems in the 3.10 version

### ISSUE THREAD

**Issue by Ragolay** [popcorntime/popcorntime#343]
Operating System Version:

Windows 7

Popcorn Time Version:

3.10

Download date:

15/11/2016

#### Expected Behaviour

I expected 3.10 to be better than the previous one, but it gets worse.

#### Actual Behaviour

- There are many IMPORTANT movies that were in the previous versions (Star Wars V, VI ...)
- There are missing subtitles in many movies.
- Synopsis not translated.
- It's impossible to open a program without getting behind Butter. Never in front.
- Video playback is not as fluid like in previous versions.

#### Steps to reproduce the behaviour

1. Open Butter.
2. Search in "Movies".
3. Realize that there are many films missing.

1. Open Butter.
2. Click on other window in Windows toolbar (e. g. Chrome).
3. Realize that the window of Chrome opens behind of Butter.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
