### ISSUE TITLE
Crashes to destkop whenever a character is entered into the search bar

### ISSUE THREAD

**Issue by PopcorntimeStarWars** [popcorntime/popcorntime#344]
Operating System Version:
Win 7 Pro

Popcorn Time Version:
3.10.0

Download date:
~11/14/2016

#### Expected Behaviour
Previous versions allowed one to search for a given title without crashing
...

#### Actual Behaviour
Any character typed into the search bar automatically results in crashing to destkop
...

#### Steps to reproduce the behaviour
Type in the search bar as the very first character, regardless of letter, number or symbol, causes crash to desktop

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
