### ISSUE TITLE
Randomize button load indefinitely 

### ISSUE THREAD

**Issue by a3zzat** [popcorntime/popcorntime#346]
Operating System Version: Windows 10

Popcorn Time Version: 0.31.10-0

Download date: 10-11-2016

#### Expected Behaviour: 

... when click randomize button the movies is randomized 

#### Actual Behaviour: 

... the interface load indefinitely (waited for hours and no changes happened)

#### Steps to reproduce the behaviour

1. ... open popcorn
2. ... click randomize button 
3. ...  the interface just keep loading

**Comment by team-pct** [comment]
Known Bug

**Comment by user440** [comment]
To fix random button replace "index.js" inside "butter-provider-movie" folder with new version of "index.js" from https://github.com/ChrisAlderson/butter-provider-movies/blob/master/index.js

And keep replacing it until new popcorn release include this new "index.js".
