### ISSUE TITLE
Can´t syncronize with trakt.tv

### ISSUE THREAD

**Issue by SSamDav** [popcorntime/popcorntime#350]
Operating System Version:
 Windows 10
Popcorn Time Version:
0.3.10

Download date:
Today

#### Expected Behaviour
Syncronize with trakt.tv
...

#### Actual Behaviour
Open a tab in my browser 
...

#### Steps to reproduce the behaviour
Try to syncronize with trakt

1. ...
2. ...
3. ...

**Comment by maclir** [comment]
I have the same issue on Mac.

![screen shot 2016-12-05 at 17 23 03](https://cloud.githubusercontent.com/assets/1525425/20892703/8697e846-bb0f-11e6-9e79-9960dfd0be0c.png)

**Comment by xIO3Y** [comment]
Apparently a code to synchronize with Trakt is generated 'behind the scenes'. Just found out you can paste the code and press Continue. Tried it twice, to be sure.

**Comment by maclir** [comment]
@xIO3Y Where/How can I find this code?

**Comment by xIO3Y** [comment]
@maclir Just Ctrl/CMD + V in the field where you have to enter the code. The code was automatically generated when you clicked 'Connect' in Popcorn Time.

**Comment by maclir** [comment]
@xIO3Y It is automatically copied to my clipboard?

**Comment by xIO3Y** [comment]
@maclir It is. Just paste it and you're ready to go.

**Comment by ChrisAlderson** [comment]
Should be fixed with #398.
