### ISSUE TITLE
Popcorn time won't open after download (freeze during verification loading) on iMac OSX 10.12.1

### ISSUE THREAD

**Issue by oheyhellooo** [popcorntime/popcorntime#351]
Operating System Version:
OS X 10.12.1

Popcorn Time Version:
Since version 217

Download date:
Since 15 of November

#### Expected Behaviour
Verify app after first download by OSX

#### Actual Behaviour
After being downloaded and opened for the first time, freeze 2/3 through verification by OSX

**Comment by team-pct** [comment]
Right Click and hit open
