### ISSUE TITLE
update notification not working

### ISSUE THREAD

**Issue by ItamarShDev** [popcorntime/popcorntime#354]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
long time ago

#### Expected Behaviour
notification comes up, you click on the buttons and they are working

#### Actual Behaviour
the notification shown, each of the two buttons are not working

#### Steps to reproduce the behaviour
open the 0.3.9 version and wait for the popup

**Comment by ChrisAlderson** [comment]
http://status.popcorntime.sh/
