### ISSUE TITLE
subtitles control while casting to chromecast

### ISSUE THREAD

**Issue by ItamarShDev** [popcorntime/popcorntime#355]
perating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
updating each version, updating to 3.10 today

#### Expected Behaviour
show controls on the computer

#### Actual Behaviour
no controls are shown anywhere

#### Steps to reproduce the behaviour
just cast any movie

**Comment by team-pct** [comment]
Are you building your own version?

**Comment by ItamarShDev** [comment]
No. official

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
