### ISSUE TITLE
no subtitles for movies

### ISSUE THREAD

**Issue by ItamarShDev** [popcorntime/popcorntime#357]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.9

Download date:
today 20.11.16

#### Expected Behaviour
the usual subtitles selection should be displayed
...

#### Actual Behaviour
the subtitles selections is gone
...

#### Steps to reproduce the behaviour
open a movie

**Comment by ChrisAlderson** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/227#issuecomment-255477682

**Comment by ItamarShDev** [comment]
so. guess im streaming to Chromecast, and my default language has no subtitles.
I wouldnt know until ill play the movie, and i couldnt change the language besides playing with the defaults on the settings?

**Comment by Breaking1** [comment]
@ItamarShDev  correct, there are no subtitles features supported in PT when it comes to Chromecast other than to use the default subtitle language in settings.

You can always check in butter what subtitles are available before streaming to Chromecast, then set the default subtitle language to one that was available and you can understand.
