### ISSUE TITLE
make_butter.sh

### ISSUE THREAD

**Issue by 394394394** [popcorntime/popcorntime#36]
I updated the script to work with the current repository.

I made two versions, one became `make_popcorn.sh` and the other `make_popcorn_time.sh` and where it said `butter` in the code now says `popcorn` and `popcorn-time`, respectively.

I'll send two pull requests so that you (devs and community) can decide which one is more adequate.

If something is off please let me know.

**Comment by team-pct** [comment]
Thank you again man !
