### ISSUE TITLE
What would happen to PT if an "infinite" amount of valid data got to be delivered by the API?

### ISSUE THREAD

**Issue by popcornenthusiast** [popcorntime/popcorntime#365]
Right now both PT and the API are quite polite asking for and delivering only one page of limited data per request, but what would happen to PT if an attacker acquired control over the API and decided to deliver infinite amounts of valid data? So, I'm not talking about a problem due to a lack of sanitization, but rather a problem due to a huge amount of valid data. Can PT already handle something like this? Would the data retrieving be canceled?

**Comment by team-pct** [comment]
How an attacker would execute his attack first ... 
After PT will handle like any Chrome Browser using available memory/cpu
