### ISSUE TITLE
List of torrents in Torrent Collection not showing anymore

### ISSUE THREAD

**Issue by m-a-x-s-e-e-l-i-g** [popcorntime/popcorntime#368]
Operating System Version:
Windows 10 x64

Popcorn Time Version:
0.3.10-0

There's a torrent collection folder at AppData\Local\Popcorn-Time\TorrentCollection where I put all my torrents. In a previous build the torrents would be listed in Popcorn Time when I click Torrent Collection. 
After the latest update the list won't show.

**Comment by ChrisAlderson** [comment]
Check if the directory is still there, it might have been deleted somehow.
