### ISSUE TITLE
Add option to disable search history

### ISSUE THREAD

**Issue by adzie95** [popcorntime/popcorntime#369]
[This](http://s11.postimg.org/7h75ugzk3/756434.png) is simply an invasion of privacy for me and offers no useful function. I don't need every movie i have searched to show up on the search bar, please remove it or add an option to remove it.

**Comment by popcornenthusiast** [comment]
It is not an invasion of privacy. It's a local search history and it isn't logged by the PT servers. Furthermore, there's no practical difference between having an entry on search history and adding a movie to the bookmarks.

**Comment by adzie95** [comment]
Having all of my search history on display without an option to delete it is an invasion of privacy, how would you like it if you never had the option to clear your google search history. Bookmarks are on a completely different page and are comprised of movies that i WANT on display which is a huge difference.

It is also just an ugly white box that doesnt even fit in with the rest of the program. Alteast give the option to disable it.

**Comment by popcornenthusiast** [comment]
> Having all of my search history on display without an option to delete it is an invasion of privacy,

To be a invasion someone needs to invade something first.

> how would you like it if you never had the option to clear your google search history. 

Well, you don't _really_ have that option. Your Google search history is in Google servers, not in your computer. They can do whatever they want with your search history and you can do nothing about it.

> It is also just an ugly white box that doesnt even fit in with the rest of the program. Alteast give the option to disable it.

Yes, it is ugly and yes, it would be better to have the option to disable it.

**Comment by VitorVRS** [comment]
Maybe putting an "autocomplete=off" here: https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/templates/browser/filter-bar.tpl#L53

@team-pct there is a problem doing that?

**Comment by ChrisAlderson** [comment]
#371
