### ISSUE TITLE
Butter player not displaying media

### ISSUE THREAD

**Issue by Ehntae** [popcorntime/popcorntime#372]
Operating System Version:
Windows 7

Popcorn Time Version:
Latest version

Download date:
5 minutes prior to posting this

#### Expected Behaviour
Play the media and display visually in the player

#### Actual Behaviour
Gave no visual feedback, subtitles and audio did work.

#### Steps to reproduce the behaviour
Surely this issue exists on this Windows 7 PC, but I have not been able to find the cause, help towards a fix is greatly appreciated, thanks.

**Comment by ChrisAlderson** [comment]
What media? Be more specific please.

**Comment by Ehntae** [comment]
The problem is that there is simply no video displayed, yet audio and subtitles work. The screen remains black

**Comment by ChrisAlderson** [comment]
Which movie/series episode/anime episode? And in what quality. It's probably a codec issue and if it is you can always use an external player like VLC to play the content.

**Comment by Ehntae** [comment]
I tried around 50 of all kinds, and all quality settings. Is there a list of redists so that I can manually install them on the target PC? I have installed VLC on the target PC but it was not in the dropdown list next to Butter, to select as a player.

**Comment by Breaking1** [comment]
@Aeomi VLC needs to be installed in the default location (Programfiles) for PT to find it, it only searches that folder(s) for any installed players on your computer.

**Comment by ChrisAlderson** [comment]
Reinstall.
