### ISSUE TITLE
sound doesn't sync up with the the video

### ISSUE THREAD

**Issue by csaw13** [popcorntime/popcorntime#374]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0 "popcorn s love" beta - head (28112167

Download date:
11/25/2016

#### Expected Behaviour
play normally like it did before the upgrade
...

#### Actual Behaviour
audio and video aren't synced up very annoying
...

#### Steps to reproduce the behaviour
play a movie....

1. ...
2. ...
3. ...

**Comment by csaw13** [comment]
sorry I don't have any files to drag and drop
Please help me solve this problem its driving me crazy and this is my favorite app

**Comment by VitorVRS** [comment]
This happend with every movie/show? Or is it with an specific torrent? Have you tried another player (like VLC)?
