### ISSUE TITLE
API change!

### ISSUE THREAD

**Issue by Malik96** [popcorntime/popcorntime#375]
Operating System Version:
Windows 7 64-bit

Popcorn Time Version:
0.3.10v

Download date:
30/11/2016

#### Expected Behaviour
In the previous version I was able to change APIs through changing "index.js" file.
...

#### Actual Behaviour
Now any change to "index.js" script breaks the program!
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
It's never recommend to change the API since you are technically changing code. Therefor is you don't know what you are doing you can break the build. In that case you need to reinstall.

**Comment by Malik96** [comment]
Do you inted tp add API change option just like CE version? If not, plz tell me how to change it manually in 3.10v and I'll take responsibility for my actions!
