### ISSUE TITLE
Close windows button doesn't work

### ISSUE THREAD

**Issue by woutcam** [popcorntime/popcorntime#379]
Operating System Version:
Windows 10

Popcorn Time Version:
Latest build #237 (1 dec)

Download date:
2nd dec

#### Expected Behaviour
close screen
...

#### Actual Behaviour
Did nothing
...

#### Steps to reproduce the behaviour

1. start a movie or series
2. when watching try to close the play window using the X in the top right corner
3. Nothing happens. Player continues and you're trapped

**Comment by NesooseN** [comment]
I also confirm all above.

**Comment by ZedoGado** [comment]
OAuth error in console when it happens.
To avoid having to force close Popcorn Time you can open console (F12) and then press F5 to refresh app.

**Comment by TheSparrowLenz** [comment]
Confirmed that the best solution so far, short of restarting the app entirely is refreshing it using the method described above.

**Comment by team-pct** [comment]
F11 would restart the app aswell

**Comment by Bokerdev** [comment]
I also confirm all above. Another solution, I use VLC. I think those are the butter issue.
OS: Ubuntu 16.04

**Comment by ChrisAlderson** [comment]
Should be fixed with #399.
