### ISSUE TITLE
Seek not working on macOS and win10

### ISSUE THREAD

**Issue by drahgon55** [popcorntime/popcorntime#382]
Operating System Version:

macOS and win10

Popcorn Time Version:

3.10, also happens in 3.9

Download date:

#### Expected Behaviour

should seek when I click the seek bar. Also the double arrows do not work

#### Actual Behaviour

nothing. I see seeking in the console but nothing happens

#### Steps to reproduce the behaviour

1. ...Try to seek in any movie on windows or mac
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
See #388

**Comment by ChrisAlderson** [comment]
Wrong issue my bad.

**Comment by drahgon55** [comment]
The seems to work in the latest versions that were in jenkins. Not sure what commit fixed it. Feel free to close or confirm that this is not longer an issue. Only tested on Mac
