### ISSUE TITLE
Chromecast issues

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#383]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
A month ago

When casting to a Chromecast you are unable to decide where in the movie you want to play from. Lets say I watched an hour of a movie and then stopped. If I wanted to resume at that point the next day or something I can't. Basically I would like to be able to press on the progress bar like I can when I watch the movie on my computer.

Also, if you open Popcorn Time while something else is casting, you are not able to cast. You have to close Popcorn Time, stop casting whatever it is you are casting, and then open Popcorn Time again to be able to cast. With most casting apps you are able "overwrite" whatever's currently casting and "take over" the Chromecast from the previous casting apps.

Finally, it would nice to be able to use all the keyboard shorcuts when casting.

**Comment by ghost** [comment]
To add to the second issue, it doesn't seem to want to cast when the TV is turned off. To fix it you have go through the same steps of opening and closing Popcorn Time.

**Comment by darkdrifter** [comment]
To add to this issue, it seems that custom torrent file doesn't work with the Chromecast.

**Comment by Breaking1** [comment]
The seeking issue when using Chromecast is fixed in the latest build, you can now press anywhere on the progress bar or use the forward/backward symbols to skip forward/backward.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/
