### ISSUE TITLE
The displayed ratings

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#384]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
A month ago

Now I might be mistaken, but I am under the impression that the ratings showed on the movies are the IMDb ratings. If that is the case then pretty much all of them are wrong. If not, I am sorry that I wasted your time.

**Comment by NesooseN** [comment]
@EAminy Ratings are not from IMDB but from TRAKT.TV
