### ISSUE TITLE
Popcorn Time Crashes when quitting on Mac OS X via Cmd-Q consistently

### ISSUE THREAD

**Issue by AlJohri** [popcorntime/popcorntime#388]
Operating System Version:
OS X 10.11.4

Popcorn Time Version:
0.3.10

Download date:
12/6/2016

#### Expected Behaviour
I expected the program to close.

#### Actual Behaviour
It crashes and shows a crash report.

![screen shot 2016-12-06 at 3 22 47 pm](https://cloud.githubusercontent.com/assets/2790092/20942098/de4edaa0-bbc7-11e6-9d84-9ea2b191a94d.png)

#### Steps to reproduce the behaviour

1. Open Popcorn Time
2. Press Cmd-Q

Full Stack Trace: https://gist.github.com/AlJohri/58b3cf77cd616ebf05be85cd10b3675e

**Comment by team-pct** [comment]
NWJS Related bug which was reported , It will be fixed on next Nwjs version

**Comment by AlJohri** [comment]
Upstream issue for reference: https://github.com/nwjs/nw.js/issues/5516

**Comment by AlJohri** [comment]
Apparently I referenced the wrong issue. @team-pct do you know where the issue was reported?

**Comment by tironman** [comment]
This is happening even in my mac tooo... Pls help me...

**Comment by cs-ark** [comment]
This is explained in this issue : https://github.com/nwjs/nw.js/issues/3095

**Comment by peterjgithub** [comment]
I also experience this today
macOS 10.12.6 (16G29)
Popcorn Time Version 0.3.10 (0.3.10)
Download date: 3 September 2017
Expected Behaviour: I expected the program to close.
Actual Behaviour: It crashes and shows a crash report.

**Comment by thewoz** [comment]
Why you don't official release the new version?

**Comment by tnmygrwl** [comment]
This issue still persists.
**System Information:**
OS: macOS Mojave 10.14 18A377a x86_64
Host: MacBookPro12,1
