### ISSUE TITLE
Buffering doesn't resume after a network failure

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#395]
**Operating System Version:**
Windows 10 Pro

**Popcorn Time Version:**
0.3.10 Beta

**Expected Behaviour**
After a temporary network failure, buffering should resume automatically.

**Actual Behaviour**
After a temporary network failure, buffering stops, forcing me to exit and restart the stream.

**Steps to reproduce the behaviour**
1. Start streaming something
2. Have a network failure (e.g pull the WAN cable from the router) before buffering is complete
3. Wait for return of connectivity.
4. Hover the mouse pointer on the EYE icon to confirm the 0 KB/s speed.

**Proposed solution (to be implemented)**
Wrap the download code in a loop with a 10-second window for a connection check at start (to be repeated until a working connection can be detected).

**Comment by NesooseN** [comment]
This would be nice, as I experienced same problem.

**Comment by beppe9000** [comment]
@ChrisAlderson care to explain for us mortals?
