### ISSUE TITLE
Popcorntime gets stuck at the loading screen.

### ISSUE THREAD

**Issue by jmorez** [popcorntime/popcorntime#396]
Clicking "Loading stuck? Click here!" does not work. Using Ubuntu 16.04, nodejs v6.9.4

**Comment by khalilhas** [comment]
Same problem in Kali Linux

**Comment by ChrisAlderson** [comment]
Delete the temp directory: `$HOME/.config/Butter`

**Comment by jmorez** [comment]
What causes this issue?
