### ISSUE TITLE
[Issue] Torrent collection (full season) - Wont play the episode I want it to play

### ISSUE THREAD

**Issue by MrDemocracy** [popcorntime/popcorntime#397]
Operating System Version:
Mac OSX 10.12.1

Popcorn Time Version:
Version 0.3.10 from http://popcorntime.sh

Download date:
December 1. 2016

#### Expected Behaviour

I'm trying to watch a torrent with multiple video files in it (a season). I clicked on S01E01 and expected it to play. 

*Side note: The episodes that is listed seems to be unorganized, it does not list it in a chronological     order with the first episode first, and the last episode at the bottom.

#### Actual Behaviour

In my case it always plays the episode that is listed on the top, no matter what episode I click.

#### Steps to reproduce the behaviour

1. Drag torrent of complete season of a series into Popcorntime.
2. Wait for it to connect.
3. Click on the episode you want to watch.

**Edited notes:**

* I also am just now noticing the player is not displaying the name of the episode, but instead the name of the torrent.

* It would also be nice if the player could automatically go to the next episode when the first one is done playing.

* This same issue applies for torrents with a full movie collection. For example the X-Men collection.

**Comment by vidra87** [comment]
I have a problem with some episodes of Vikings season in Popcorn-Time
When i see the red dot of torrent life the episodes downloading is very low although when i download it with utorrent there seems to be more seeders and leechers than in Popcorn-Time.
one example of episode is Vikings -Season2, Episod 5 - Answer in Blood (Vikings S02E05 HDTV x264-2HD[ettv])
max 125 KB/s in Popcorn-Time
and max 6.1 MB/s in uTorrent
I use Popcorn-Time version 0.3.10-0 "Popcorn in Love" Beta - HEAD (28112f67)

**Comment by CFarzaneh** [comment]
Have the same issue!

**Comment by sarthak0415** [comment]
any updates, it happens with all the torrents with multiple files, only the first file is played not matter which is clicked. Please fix this, its very irritating.

**Comment by Nekaravaev** [comment]
Same issue. 

UPD: rebuild from source fixed it. 🤞🏻
