### ISSUE TITLE
Watchlist doesn't work

### ISSUE THREAD

**Issue by GuiChevis** [popcorntime/popcorntime#4]
I am synchronized with Trakt.tv but when I open the watchlist the message says that i'm not.

**Comment by NicholasAsimov** [comment]
Same here.

**Comment by mahe0543** [comment]
This is still an issue. Plese help. I have connected to trakttv, but it still asks to check settings

**Comment by JimiC** [comment]
Same as #121

**Comment by ChrisAlderson** [comment]
Moved to #121
