### ISSUE TITLE
Both Mac and Windows apps doesn´t launch

### ISSUE THREAD

**Issue by bfnxcorvo** [popcorntime/popcorntime#40]
Hey There.

Downloaded both versions from the website, for OsX and Win10 and can´t made it to work on any of the devices I´ve tried. It stays on the "loading" status.

![image](https://cloud.githubusercontent.com/assets/3242838/13350782/99537c14-dc82-11e5-85ae-61ebae48dfd8.png)

**Comment by Wesley21** [comment]
Same here.. Just downloaded the latest build and I was hoping it would use OpenSubtitles for series and movies so I could finally watch The Walking Dead with subtitles, but that's not going to happen since it stays on the same screen forever.

Edit:
Build number 38 works fine right now :)

**Comment by bfnxcorvo** [comment]
Yep, tried previous beta 0.3.8-6 and works for me on Windows
