### ISSUE TITLE
[Feature Request] Able to limit the download speed?

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#400]
This has most likely been requested before so sorry if it has. Im requesting this because some of us who use popcorn time dont exactly have the fastest of internet connections.

So instead of downloading at full speed until its downlaoded the whole of the movie/tv show, could you let us add a limit or even an option to slow down so that it only downloads say 5 minutes ahead of where im watching from.

Thanks, awesome job by the way! :)

**Comment by fizzvr** [comment]
The global problem of the Internet - Speed

**Comment by syl3n7** [comment]
It could be a feature, like automatically do a speedtest , there is a .py script that could be incorporated, and then it would determine the actual speed , and do the math, limit the speed for ahm, lets say .. one quarter of the speed you have and done.
On the advanced settings you could have also the option do disable it or so, i think its a must have for people that have low bandwidth ..

**Comment by Persei08** [comment]
Also it could be interesting to have a option "minimal optimal speed" which will change according to quality selected.
Something like this:
```
- 480p => 1Mbits/s
- 720p => 4Mbits/s
- 1080p => 8Mbits/s
```

**Comment by fizzvr** [comment]
@Persei08 sounds good!

**Comment by chtrinh** [comment]
I have PR that address this issue on the webTorrent side of things. Not sure when this is going to be merged back to master: https://github.com/feross/webtorrent/pull/1040

In the mean time feel free to use this branch:
https://github.com/chtrinh/webtorrent/tree/feature/163_global_download_upload_limit

pass down "downloadLimit" or "uploadLimit" as a options to the "webTorrent" instance. 
Just a note: this is an aggregate limit for all connections thru a "webTorrent" client/instance. 

When I'll get to it, I'll add this branch to a PR and slap on some UI to adjust these values.

**Comment by kiriles90** [comment]
#2265 merged
