### ISSUE TITLE
Black screen after click on Anime - Indie - Anime

### ISSUE THREAD

**Issue by MinionAttack** [popcorntime/popcorntime#407]
Operating System Version: Windows 10 Pro 64 bits up to date.

Popcorn Time Version: 0.3.10 64 bits (Jenkins build 239)

Download date: 13 December 2016

#### Expected Behaviour
Show the anime series and all other GUI elements.

#### Actual Behaviour
Black screen, only can click on Minimize, Maximize and Close. (on the top-right)

#### Steps to reproduce the behaviour
1. Open Popcorn Time
2. Click on Anime section.
3. Click on Indie section.
4. Click on Anime section.
5. Everything on the GUI has gone except the system icons on the top -right (minimize, maximize, close)

![screenshot](https://cloud.githubusercontent.com/assets/10078549/21371370/4457d5b4-c711-11e6-9722-233af167396b.png)

**Comment by Breaking1** [comment]
It works fine in my version, also on Jenkins build 239.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.

**Comment by MinionAttack** [comment]
Why do you close it? Still happens on the new build 240. See the attached image, it's the console output.
![console output](https://cloud.githubusercontent.com/assets/10078549/21468576/6b957a18-ca19-11e6-9a38-8f87bced42dd.png)
