### ISSUE TITLE
proxy support?

### ISSUE THREAD

**Issue by pinkeshbadjatiya** [popcorntime/popcorntime#41]

**Comment by YIFYtorrents** [comment]
Would be very nice.

**Comment by pinkeshbadjatiya** [comment]
But one tradeoff is, most of yhe organisations that use proxy already block these p2p ports so it makes it senseless to have proxy support.

Any ideas?

**Comment by YIFYtorrents** [comment]
What about ssh proxies on port 21? Are they blocked as well?

**Comment by pinkeshbadjatiya** [comment]
yeah. port 22 and 21 are blocked for security reasons.
I rather use corkscrew on port 443 to ssh on AWS.

**Comment by YIFYtorrents** [comment]
> But one tradeoff is, most of yhe organisations that use proxy already block these p2p ports so it makes it senseless to have proxy support.

I am not talking about proxy websites that offer free proxies to track you. That would NOT make sense at all. Most of this free proxies make you the product and I am not even talking about how extremely slow they are if they somehow have 21/22 ports opened. 

I am talking about popcorntime user who have somehow access to dedicated servers. That's what I meant.
