### ISSUE TITLE
Stuck on "Waiting For Subtitles"

### ISSUE THREAD

**Issue by Kavnor** [popcorntime/popcorntime#410]
Operating System Version: Linux

Popcorn Time Version:0.3.10-0

Download date:17/12/2016

#### Expected Behaviour

...if no subtitles found for download, skip subtitles download and start playing video.

#### Actual Behaviour

...stuck in "Waiting For Subtitles" screen.

#### Steps to reproduce the behaviour

1. ...set default subtitles for any language.
2. ...find any movie/series without subtitles at all.
3. ...press "Watch Now" in the screen of selected movie/series.
![screenshot_20161222_142751](https://cloud.githubusercontent.com/assets/16723564/21425606/df88fbe8-c852-11e6-9975-0321a4b19f64.png)

**Comment by Breaking1** [comment]
Try the latest build and see if the issue is already fixed:

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

**Comment by Kavnor** [comment]
Still the same.

**Comment by zappe** [comment]
Same issue here.

**Comment by rfigueroa-zz** [comment]
using development version 1bbf0c1a, can reproduce the issue trying the same movie as in the screen shot

```[INFO] Show about
app.js:11 [INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
app.js:11 [INFO] Show movie detail (tt4527400)
app.js:11 [INFO] Subtitles: none
app.js:11 [INFO] Loading torrent
app.js:11 [INFO] Returning cached provider OpenSubtitles
app.js:11 [INFO] Loading torrent: startingDownload
app.js:11 [INFO] 0 subtitles found
app.js:11 [INFO] Loading torrent: waitingForSubtitles

**Comment by vvbv** [comment]
If the connection is initially slow, the subtitles are skipped. :/

**Comment by ghost** [comment]
Use Appcleaner clean all the application and put back the Popcorn app from Trash - and you will be grant
