### ISSUE TITLE
Feature request: Hardcoded subtitles to get subtitles working with Apple TV & DLNA

### ISSUE THREAD

**Issue by strinpe** [popcorntime/popcorntime#411]
Operating System Version:
Latest MacOS

Popcorn Time Version:
Latest build #240

Download date:
Today, first time.

I was hoping to see a movie and see the subtitle on Apple TV. But the subtitle does not work on Apple TV. I am pretty sure that it is because you can not stream two files to Apple TV e.g. mp4 and srt. The solution is that you need to have hardcoded subtitles to get the subtitles working with Apple TV.

There is another app called Airflow that works like this and it is really easy to just click on a button and then the subtitles are hardcoded and then it works like a charm. But that app is not working with torrents and does not have the same library as PT.

I would really love to use PopcornTime but I need to see the subtitles then.

Cheers and Merry xmas.

**Comment by ChrisAlderson** [comment]
We don't like to hardcore anything
