### ISSUE TITLE
Allow user to chose between rating platforms

### ISSUE THREAD

**Issue by boogersss** [popcorntime/popcorntime#414]
Operating System Version:
OS X 10.12

Popcorn Time Version:
0.3.10

Download date:
24/12/2016

Follow-up from reddit thread : https://www.reddit.com/r/PopCornTime/comments/5auqvk/whats_up_with_fake_ratings_for_movies/

How about a new feature to allow the PCT user to chose from different rating platforms from the Settings (e.g RottenTomatos.com, Trackt.tv, IMDB.com) ?

N.B : I personally chose to check IMDB ratings of every movie on PCT before I launch them, because Trackt users do not reflect my taste in movies.

This might already be in the pipeline, but I didn't come across this idea. 

Thanks ! 🙏

**Comment by a3zzat** [comment]
thumb up 
I really want this feature
