### ISSUE TITLE
PT and CC(chromecast) communication/network issue

### ISSUE THREAD

**Issue by Keithw12** [popcorntime/popcorntime#416]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
Update from older version today.

I am troubleshooting a very interesting problem with PT and chromecast.  I can always stream to my chromecast from my chrome browser without issue, but half the time I'm not able to cast from PT.  When this is the case, I'll reboot my router and chromecast and this will usually fix the problem.  However, after a couple reboots from all devices, I had no luck this time and was impatient.  So I updated PT to 3.10, no luck.  Updated to build #240, no luck.  Now I'm trying to see if anyone here knows how PT tries to communicate with CC.  How do I see if PT is able to detect my CC at a deeper level and what does PT use to identify a CC on my network?  Whatever script its using at the moment isn't doing a good job of detecting the CC on the network.  If PopcornTime isn't able to stream to my CC, but Chrome is, doesn't that eliminate the possibility of my router being the issue?

**Comment by Persei08** [comment]
Can't reproduce personally, but some users on reddit face this issue and are able to cast from google chrome.

@Keithw12 PT use ["chromecasts": "1.9.0" package](https://www.npmjs.com/package/chromecasts), you can see dependencies in package.json.  
Also can you try to cast with https://webtorrent.io/desktop/ and tell us if it work? it use same package

**Comment by Breaking1** [comment]
Couldn't reproduce this one either, i use build 239 and it works fine as long as i don't have any VPN or similar programs running when starting popcorntime.

**Comment by Keithw12** [comment]
Seems to be a router/network based firewall issue.  I'm using an Arris Surfboard SBG6782-AC and setting my device on the network to DMZ resolves the issue.  Strange that it had no issue with Chrome but an issue with PT.
