### ISSUE TITLE
Black screen after clic on Anime - Indie - Anime

### ISSUE THREAD

**Issue by MinionAttack** [popcorntime/popcorntime#418]
After get closed the old issue without ask for more information and only say "I can't reproduce" I've opened again with a screenshot of the error.

- Operating System Version: Windows 10 Pro 64 bits up to date.
- Popcorn Time Version: 0.3.10 64 bits (Jenkins build 239 and 240) (happens on both versions)
- Download date: 13 December 2016 and 22 December 2016 (happens on both versions)
- Expected Behaviour: Show the anime series and all other GUI elements.
- Actual Behaviour: Black screen, only can click on Minimize, Maximize and Close. (on the top-right)
- Steps to reproduce the behaviour:
1. Open Popcorn Time
2. Click on Anime section.
3. Click on Indie section.
4. Click on Anime section.
5. Everything on the GUI has gone except the system icons on the top -right (minimize, maximize, close)

I attach an image of error on the dev console:

![a](https://cloud.githubusercontent.com/assets/10078549/21525591/8db98dde-cd1e-11e6-933a-6fe07102bdc8.png)

**Comment by rfigueroa-zz** [comment]
Can't reproduce

**Comment by Persei08** [comment]
I have similar issue with builds 239, 240, 241 on ubuntu 14.04 64bits

1. go on Indie tab (empty section, no movies)
2. switch tab (PT is empty and black, same than what OP as described)

![capture du 2017-01-27 11 06 30](https://cloud.githubusercontent.com/assets/22459458/22367330/40758896-e481-11e6-92f5-a6db8f7101d8.png)
