### ISSUE TITLE
Streaming video is ok, but how can it also stream subtitels

### ISSUE THREAD

**Issue by air13032** [popcorntime/popcorntime#419]
Operating System Version:
 Windows 10

Popcorn Time Version
0.3.10

Download date:
just today. i tryed the latest download, but it stays a problem.

#### Expected Behaviour
the mediacenter i use is a bit slow for my tv: Minix NGC1=on a 3840x2150 res for the TV.
so i would like to stream the movies to the tv. It works fine, but i can t get the subtitels on the stream.
big problem for wife and childeren.
The subtitels works with buter, but than the movies are to slow.
is there a solution
...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by rfigueroa-zz** [comment]
on the settings page you can select the default language for subtitles

**Comment by air13032** [comment]
I placed these settings. Still, on Butter we see it, but not on stream...

**Comment by rfigueroa-zz** [comment]
Can you provide the logs?

**Comment by ripper2hl** [comment]
same problem , with chromecast 2

**Comment by rfigueroa-zz** [comment]
Can you guys, provide the logs, or specify reproducing steps?

**Comment by air13032** [comment]
Sorry, but I have a time problem. That is why it took so long. Thing is that I don’t have subtitles at all if I use VPN. When I don’t, I have subtitles with butter, but not when I steam. Where can I find the logs you want? I use Windows10

**Comment by Breaking1** [comment]
@air13032 reproduce the problem and then press f12 and it should bring up a new window. Go to the console tab and screenshot the log and post it here.

Can you try this build and see if it works correctly?

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/239/

I can use my VPN + Popcorntime when streaming to Chromecast without problems, and off course with subtitles when they are available.

Are you sure your TV supports subtitles when streaming? Many TV's only supports subs if they are hardcoded in the video file, others may only support srt. 

What kind of TV do you have?

**Comment by air13032** [comment]
The TV is a UE65HU8500 of samsung. I use a minix NGC- iB WINDOWS 10 PRO NUC Mini pc to run Popcorn. The video output is to slow (not in the specs, because I both this PC for this purpose)  for the resolution of the TV, so this is why I want to stream. 
I added the logs as you told me. I have 2 TV’s who can handle streams, as you see.  I did not know that the TV maybe could not handle the subtitles? I thought it was handled by the PC?
![with vpn butter](https://cloud.githubusercontent.com/assets/24812526/22286107/63a528e2-e2ee-11e6-8349-14811720a1c7.PNG)
![without vpn butter](https://cloud.githubusercontent.com/assets/24812526/22286109/63a85c60-e2ee-11e6-96fe-4d7a2f0f1a6b.PNG)
![stream tv](https://cloud.githubusercontent.com/assets/24812526/22286108/63a56e2e-e2ee-11e6-8bcc-077cc7ed8619.PNG)

**Comment by Breaking1** [comment]
@air13032 my TV only support srt subtitle files so if it is in another format  it wont show so yes the subtitles and the video file is handled by the TV if you stream directly to the TV from popcorntime. 

Many TV's only supports hard coded subtitles so just check what your TV supports and i am sure you can find a solution.

**Comment by nakp** [comment]
the current download available from the website has this problem (tried on mac), using the latest build from jenkins did solve the problem for me
