### ISSUE TITLE
No updates on Movies List?

### ISSUE THREAD

**Issue by faroutxxx** [popcorntime/popcorntime#420]
Operating System Version:
Kernel: 3.13.0-24-generic x86_64 (64 bit) Desktop: Xfce 4.11.8 Distro: Linux Mint 17 Qiana

Popcorn Time Version:
Popcorn-Time-0.3.10_linux64

Download date:
2016 Dec 27 12:36 GMT

#### Expected Behaviour
Select "Movies" tab
Select "Sort by" drop down menu and choose "Last added"
First film in list is Abattoir(2016)
After a week at least this should be a newly added film

#### Actual Behaviour
In the last week at least the first film in the list sorted by "Last added" has been Abattoir(2016).
The rest of the films on the list look the same too.
I have tried multiple installs on different days with the same behaviour.
I can also see the same list on the Android version.
Is this a problem with the source or the sorting?

#### Steps to reproduce the behaviour
Select "Movies" tab
Select "Sort by" drop down menu and choose "Last added"
First film in list is Abattoir(2016)

**Comment by ChrisAlderson** [comment]
We don't control the releases of movies, shows or any other kind of content.

**Comment by pedrorijo91** [comment]
but how is "last added" used? does it use any information that's not controled by popcorn ? or does it look for the latest DB entry or something like that? @ChrisAlderson
