### ISSUE TITLE
Issue installing version 3.10 on Windows 10 Home

### ISSUE THREAD

**Issue by OniKaze** [popcorntime/popcorntime#421]
Operating System Version:

Windows 10 Home

Popcorn Time Version:

Windows version 3.10

Download date:

Had the 3.9 version which worked perfectly.
Downloaded version 3.10 and I'm having problems installing it. Tried deleting everything from previous version, but didn't work.

![image](https://cloud.githubusercontent.com/assets/24814248/21528233/44c46762-cd18-11e6-89d5-faade2b16bbf.png)

The message says: 
Popcorn-Time 0.3.10 Installer stopped working.
A problem made the program stop working correctly. Windows will close the program and notify if a solution is available. 

#### Expected Behaviour

The installer would install the app without problems, as did the previous versions.

#### Actual Behaviour

Cannot install apps version 3.10

#### Steps to reproduce the behaviour

1. Download available windows 3.10 version from https://popcorntime.sh/en_US
2. Double click the installer file
3. Begin installation

**Comment by ChrisAlderson** [comment]
Uninstall Popcorn Time completely and try to reinstall again.
