### ISSUE TITLE
PopcornTime does not load movies. Endless loading screen

### ISSUE THREAD

**Issue by ojoma** [popcorntime/popcorntime#422]
Operating System Version:
Ubuntu Linux 16.04

Popcorn Time Version:
0.3.10 Beta

Download date:
Dec 29 2016

#### Expected Behaviour
Display movie selection thumbnails
...

#### Actual Behaviour
Endless spining of load icon
...

#### Steps to reproduce the behaviour

1. sh Popcorn-Time.sh

`[8072:8109:1228/175649:ERROR:socket_stream.cc(210)] Closing stream with result -100
:1:1228/180025:ERROR:KeyboardEventManager.cpp(344)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
couldn't lock 16384 bytes of memory (secret_session): Cannot allocate memory
[1:1:1228/180054:ERROR:KeyboardEventManager.cpp(344)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()`

**Comment by duard** [comment]
Same problem here

**Comment by eline2244** [comment]
hee same problem here now
