### ISSUE TITLE
Crashes after closing player

### ISSUE THREAD

**Issue by hacdias** [popcorntime/popcorntime#425]
**Operating System Version:**
Windows 10

**Popcorn Time Version:**
0.3.10

The app crashes after closing the player.

**Steps:**

1. Open Popcorn Time
2. Choose a movie
3. Start the movie
4. Click on "x" to close the window
5. Crashes. Need to force quit.

It has been happening for a lot of time now. It happens every time I click on "x".

**Comment by ChrisAlderson** [comment]
Cannot reproduce on build #241.
