### ISSUE TITLE
Controls and cursor won't fade out if player is on fullscreen on non-primary monitor

### ISSUE THREAD

**Issue by Ingvix** [popcorntime/popcorntime#426]
Operating System Version:
Windows 7

Popcorn Time Version:
0.3.10-0

Download date:
11/1/2016

#### Expected Behaviour
Hide the play controls, overlays and cursor after a moment of inactivity when popcron-time is on fullscreen on second monitor with cursor on the movie screen.

#### Actual Behaviour
Does not hide above mentioned things. Not that major issue because it does hide them after a moment of inactivity if cursor is moved to primary monitor but still a bit annoying.

#### Steps to reproduce the behaviour

1. Start watching a movie or series with the app's own player.
2. Move the app to non-primary monitor and set it fullscreen.
3. Wait a moment with the cursor in the same monitor and the controls and others won't fade out.
4. Move cursor to primary monitor and they do fade out while the player is in the non-primary monitor.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.

**Comment by crlsgms** [comment]
I'm having the same issue using windows 7 64, popcorn time v 0.3.10 28112f67. 

Using vlc or other players on popcorn the hud fade works fine,but with butter they still always on screen on the second monitor, using HDMI.

**Comment by tomcornall** [comment]
Same issue on Mac reproduces this issue:

### Steps:

1. Start on laptop screen (mac mini 900p in my case), open popcorn time
2. Plug in monitor display (1080p in my case)
3. Play Popcorn Time full screen

Now the menus will not hide after leaving the cursor still.

### Workaround

Quit Popcorn Time, and re-open **after** plugging in monitor 👍
