### ISSUE TITLE
i have a question, when i'm searching actors but popcorn says no films, why??

### ISSUE THREAD

**Issue by nuh42** [popcorntime/popcorntime#427]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by rfigueroa-zz** [comment]
Search does not support search by actor name

**Comment by ChrisAlderson** [comment]
This feature is not supported by the API which has files the search requests.

**Comment by nuh42** [comment]
when it's coming back any idea???

**Comment by rfigueroa-zz** [comment]
the feature has never been there
