### ISSUE TITLE
black screen flickering random times

### ISSUE THREAD

**Issue by jo2dan23** [popcorntime/popcorntime#429]
i am on the latest beta. and i just started getting screen flickers when watching movies. it isnt my pc because i opened them in vlc player and they play without any flicker. i have googled this issue and it looks like it was brought up a while back but fixed which it was because i didnt have this problem on previous betas i cant pinpoint exactly which beta build it started on. am i the only one that can reproduce this? i hope not :(

**Comment by ChrisAlderson** [comment]
Please discuss this issue here: [butter-desktop#565](https://github.com/butterproject/butter-desktop/issues/565).
