### ISSUE TITLE
Magnet links

### ISSUE THREAD

**Issue by tkarrde36** [popcorntime/popcorntime#43]
I want to download the file to my computer for later viewing.  For example, download the good dinosaur now so the kids can watch it tomorrow afternoon.  It used to open bit torrent or frostwire before and start downloading.  now it opens a web page.  any way to fix this?

**Comment by v-unit** [comment]
yeah i have that same problem please fix it

**Comment by Juanca881** [comment]
yes, also happens to me same problem please fix it !!

**Comment by team-pct** [comment]
Fixed on  4e95148 , Build 43 on Jenkins

**Comment by Juanca881** [comment]
Ok, Very Thanks!!!
