### ISSUE TITLE
Imdb rating !== popcorntime

### ISSUE THREAD

**Issue by robiXxu** [popcorntime/popcorntime#430]
Operating System Version:
OS X 10.11

Popcorn Time Version:
0.3.10

Download date:
4 january 2017

#### Expected Behaviour
Show the exact imdb rating

#### Actual Behaviour
On imdb for the Marauders the rating is 5.4/10 and on PopcornTime is 7/10

#### Steps to reproduce the behaviour
1.click on the "Marauders".
2.check the rating in app
3.check the rating on imdb.

![screen shot 2017-01-08 at 12 49 15 am](https://cloud.githubusercontent.com/assets/1962141/21745854/2061791e-d53d-11e6-9ccf-ecdfe9905548.png)

**Comment by ChrisAlderson** [comment]
Rating never came from IMDb in 3.10, it comes from Trakt.tv

**Comment by robiXxu** [comment]
ok makes sense
