### ISSUE TITLE
Not all thumbnails for movies show in Linux version

### ISSUE THREAD

**Issue by dsocolobsky** [popcorntime/popcorntime#431]
Operating System Version:
Ubuntu 16.10 / ElementaryOS 0.4 Loki

Popcorn Time Version:
0.3.10-0 "Popcorn is Love" BETA

Download date:
Today (08/01/2017)

#### Expected Behaviour
The "Movies" tab doesn't show all the thumbnails for the movies.
![butter_001](https://cloud.githubusercontent.com/assets/889301/21755444/a773c1f4-d5f2-11e6-8b30-9be4036f5480.png)

#### Actual Behaviour
It should show all the images for the movies, like it does in the Windows version.

#### Steps to reproduce the behaviour
Just install Popcorntime in Ubuntu 16.10. I have also confirmed this happens in the latest ElementaryOS, but since it's based in Ubuntu as well; I can not confirm this happens in other Linux distros.

**Comment by jmorez** [comment]
Happens in 16.04 as well.

**Comment by ChrisAlderson** [comment]
Sometimes there are no images available.
