### ISSUE TITLE
thumbnail not showing , win 10 , latest version

### ISSUE THREAD

**Issue by recky261194** [popcorntime/popcorntime#432]
Operating System Version:
windows 10

Popcorn Time Version:
latest 0.3.10 

Download date:
10 jan 2017

#### Expected Behaviour
show all thumbnails of movies shows etc 
...

#### Actual Behaviour
thumbnail of a large amount of movies , shows are not present 
...

#### Steps to reproduce the behaviour
i dont know , i just downloaded , installed and ran it. 
![noname](https://cloud.githubusercontent.com/assets/25031600/21805806/1bd4017a-d75c-11e6-8577-be8af245ae5b.jpg)

**Comment by ChrisAlderson** [comment]
Dup #431
