### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by jmorez** [popcorntime/popcorntime#435]
Operating System Version:
Ubuntu 16.04LTS

Popcorn Time Version:
https://github.com/popcorn-official/popcorn-desktop/commit/222b694a9c589b (i.e. cloned from master)

Download date:
12/1/2017
#### Expected Behaviour
Install popcorn time

#### Actual Behaviour
It displays an error "npm: command not found"

#### Steps to reproduce the behaviour
Just try to install popcorn time on vanilla Ubuntu, which does not have npm by default. 

#### Suggested fix:
check if the npm command exists, if not, install npm

**Comment by ChrisAlderson** [comment]
No users just need to install NodeJS themselves inorder to build this project. I think it's a bad idea to install mom during the `make_popcorn.sh` process.
