### ISSUE TITLE
czech subtitles and coding CP1250

### ISSUE THREAD

**Issue by joazif** [popcorntime/popcorntime#436]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10 

Hi,
I have problem with coding CP1250. Czech letter " ž " is not unavailable.
Problem is that subtitles at opensubtitles are CP1250 ( UTF-8 is ok )   :( 
Is it possible fix this problem ?

**Comment by Cysioland** [comment]
Same might possibly happen with Polish, since subtitles tend to use the same codepage.

**Comment by MrMysakovich** [comment]
I have this problem too. On Android app version and on Android TV version too :/
