### ISSUE TITLE
ADD MULTI LINGUAGE DUBBING ON TV SHOWS

### ISSUE THREAD

**Issue by ciro1997** [popcorntime/popcorntime#437]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ciro1997** [comment]
I have Windows 10 and the popcorn time Version 5.6

**Comment by ChrisAlderson** [comment]
Not our version.
