### ISSUE TITLE
Torrent Collection stopped working again

### ISSUE THREAD

**Issue by HekutoruMAC** [popcorntime/popcorntime#438]
Clicking over names or individual buttons in torrent collection does nothing.
Clicking over magnet icons and lower right corner buttons does work, though.

Problem handled previously by removing several **currently present** `$( ... ).context` from the openFileSelector function on the file [torrent_collection.js](https://github.com/popcorn-official/popcorn-desktop/commits/development/src/app/lib/views/torrent_collection.js)

[Here](https://github.com/popcorn-official/popcorn-desktop/commit/ef9d50708661d0b6aab5ff30ea6eb4ee04b5e541?diff=unified#diff-f7847d725e4a233b43d20b518bc499ce) is the old fix.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
