### ISSUE TITLE
Movie thumbnails don't show up

### ISSUE THREAD

**Issue by tapir** [popcorntime/popcorntime#439]
Operating System Version:
Arch Linux 64 bit

Popcorn Time Version:
Latest linux binary from website

#### Expected Behaviour
Show movie thumbnails

#### Actual Behaviour
At least half of them are missing

#### Steps to reproduce the behaviour
Run popcorntime 3.10 linux 64 bit

**Comment by ghost** [comment]
The error message: 
Failed to load resource: the server responded with a status of 403 (Forbidden)

Reason:
PT tries to reach the server with http instead of https!

**Comment by a3zzat** [comment]
Thumbnails not showing #441

**Comment by skykanin** [comment]
Having the same issue as commentators above. Thumbnails not showing #441

**Comment by Persei08** [comment]
This is actually related to covers from amazon. 
The weird thing is PT receive an error 403 when trying to display the cover, but if you open the urls with a browser they are available.
Look like amazon's restriction

**Comment by recky261194** [comment]
^ 
yea i noticed that too. those url works fine in browser.

**Comment by GMarkfjard** [comment]
403 forbidden seems to appear when amazon resources is loaded over HTTP. Try changing to HTTPS and it works just fine.

**Comment by skykanin** [comment]
How to I change to HTTPS in the Popcorn time application

**Comment by Persei08** [comment]
It happen both with HTTP and HTTPS but error messages are a bit different: http://imgur.com/a/P02ve

Maybe HTTPS error is related to this: https://sslmate.com/blog/post/ct_redaction_in_chrome_53

**Comment by Persei08** [comment]
ok apparently switching to [nwjs 0.18.8](https://get.popcorntime.sh/repo/nw/v0.18.8/) fix this issue. ~~Do you guys want/need a push request for just that ?~~

**Comment by recky261194** [comment]
how did you switch? please help .

**Comment by Persei08** [comment]
At the moment just wait.
I have send a push request, if it's ok, they will merge it and a new build will be generated on ci.popcorntime.sh, but I'm not sure if we can use this version.

**Comment by recky261194** [comment]
i dont know if there were any changes made to the version but i downloaded latest build 244 that was created 1 day 9 hours ago and the issue still persists.

**Comment by Breaking1** [comment]
@aakash261194 they didn't make any changes regarding this problem, You can see why they closed he's PR here:

https://github.com/popcorn-official/popcorn-desktop/pull/455

The good news is that they are working on it.
