### ISSUE TITLE
Cant fast forward nor rewind while streaming

### ISSUE THREAD

**Issue by rashid19961** [popcorntime/popcorntime#440]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
1/16/2017

#### Expected Behaviour
Able to fast forward or rewind movie

#### Actual Behaviour

when i click on fast forward or rewind it doesn't do anything

#### Steps to reproduce the behaviour

1. Choose A movie
2. stream to TV (LG TV (43LF631V))
3. try to click on rewind and fast-forward, Or timeline to skip to a certain part

**Comment by ghost** [comment]
I am not one of the devs and have no ideo of how to fix this. But, if you really are desparate to rewind/fast forward you can do so by almost connecting to the Chromecast with any other device. For example, if you start the Chromecast plugin for Chrome you get the popup to select which Chromecast to connect to. Select the Chromecast that Popcorn Time is casting to and there should be a little interface which should allow you to fast forward/rewind. Just a handy work around if you don't want to waste an hour for you movie to get back to the place you were.

**Comment by Breaking1** [comment]
@EAminy it already works to skip forward/backwards when using Chromecast from the build below, you can use the buttons to skip 30 sec forward/backwards or press anywhere on the progress bar and it will jump to that time.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/239/

What doesn't work is skiping forward/backwards when you stream to a TV like @rashid19961 are trying, it's probably using DLNA to stream directly to the TV from the desktop client.

**Comment by rashid19961** [comment]
@Breaking1 Another Question if i may, Does popcorntime only support chromecast?, Does it support other streaming device like roku?

**Comment by natcohen** [comment]
@Breaking1 In my version OSX 3.10, I can't move the progress bar...

**Comment by jackbillstrom** [comment]
You should checkout the [Cast reference  ](https://developers.google.com/cast/docs/reference/chrome/cast.framework.RemotePlayerController) again and invoke some sort of function which listens from `Sender` and updates the `SeekPosition` ?

**Comment by bronestly** [comment]
Same issue on Mac OSX
