### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by captaintourettes** [popcorntime/popcorntime#441]
Operating System Version:

Windows 10
Popcorn Time Version:

0.3.10-0
Download date:

1/16//2017
#### Expected Behaviour

... Load all thumbnails

#### Actual Behaviour

...Only load about 1/3 to 1/2 of the movie thumbnails. Some of the Anime thumbs are missing also.

#### Steps to reproduce the behaviour

1. ...Load popcorn time.
2. ...Click Movies
3. ...Click Anime

**Comment by captaintourettes** [comment]
Installed around 9:40 am EST Thumbs and posters missing.  After playing around with it all day, around 6:25 pm EST (clicking on various movies) Posters for movies with missing thumbnails started appearing as well as the thumb for that movie. 11:00 pm Everything seemed like it was better but after scrolling a few pages down, or switching sorts, it's back to missing thumbs.

**Comment by a3zzat** [comment]
have the same issue for movies 
some thumbnails are missing

**Comment by NesooseN** [comment]
I also confirm this, large amount of thumb are not showing.

**Comment by ChrisAlderson** [comment]
dupe #439
