### ISSUE TITLE
bad torrent

### ISSUE THREAD

**Issue by treacledragon** [popcorntime/popcorntime#447]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by treacledragon** [comment]
the torrent i am bolt just shows a test screen

**Comment by ChrisAlderson** [comment]
skip to 2:45

btw we don't manage the content
