### ISSUE TITLE
custom subtitles

### ISSUE THREAD

**Issue by Juanca881** [popcorntime/popcorntime#45]
not work upload custom subtitles in the movie, in Popcorn Time  v0.3.9
please fix it
Very Thanks

**Comment by Residentcl** [comment]
The same problem.

**Comment by GSaban** [comment]
I have the same problem too!!
because I have a hearing problem, I need to customize the subtitles.
please, could you  solve this small problem for you
is very important for peple in same problemsof hearing
Thank you!!

**Comment by alvartabe** [comment]
Thank You for fixing custom subtitles
