### ISSUE TITLE
thumbnails not showing up for movies , tried all the builds

### ISSUE THREAD

**Issue by recky261194** [popcorntime/popcorntime#453]
movie thumbnails are not showing for me . i have also tried all the builds. build 242 , 241 and even 239 ( where a user suggested that this issue is not there but it is still there for me ) .
i pressed f12 and saw these in console logs. the url from images-na.ssl-images-amazon.com is getting blocked or is failing to load .
so can anybody please tell me how to fix this?
here is the imgur link to console log - http://imgur.com/a/1KsGy

im on windows 10

**Comment by ChrisAlderson** [comment]
Dup #439
