### ISSUE TITLE
Audio goes out of sync when full screened

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#454]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10 (64-bit version)

Download date:
3-4 months ago (October/November)

#### Expected Behaviour
When I go full screen I expect the video to run normally.

#### Actual Behaviour
So when I go full screen the audio starts going out of sync, I've had it happen to "Hell and High Water" "Trolls" and "Sherlock" S04E01. It starts out OK but gets worse the longer you watch. And it only happens in full screen, if it is windowed it runs fine.

#### Steps to reproduce the behaviour
Now I'm guessing it is a universal problem so I guess just pick any movie and go full screen. Wait like 5 min and then watch the mouths of people talking. It becomes pretty obvious quite quickly.

**Comment by Breaking1** [comment]
I can't reproduce this problem, is it the same if you use an external player like VLC or MPC HC or just the popcorntime player?

**Comment by ghost** [comment]
I only use VLC, but it doesn't have the same problem.

**Comment by Breaking1** [comment]
@EAminy  try this build and see if it works correctly.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**Comment by ghost** [comment]
I just watched 10 minutes of some random movie but it seems to have been fixed, great job!
