### ISSUE TITLE
Code Black S02E14 magnet link is only a 1 minute sample

### ISSUE THREAD

**Issue by HML-vP** [popcorntime/popcorntime#456]
Operating System Version:
 Windows 7

Popcorn Time Version:
 0.3.10

Download date:
 unknown

#### Expected Behaviour
 Download the whole episode
...

#### Actual Behaviour
 Download a 1 minute sample of the episode only
...

#### Steps to reproduce the behaviour

1. Go to series 'Code Black' S02E14
2. Select magnet link and download via uTorrent
3.

**Comment by Persei08** [comment]
Torrent is named: Code.Black.S02E14.SOURCE.SAMPLE.720p.HDTV.x264-FLEET[rarbg]

torrent containing .SOURCE.SAMPLE. tags should be exclude I presume.
[search "sample" on rarbg](https://rarbg.to/torrents.php?search=sample&category%5B%5D=48&category%5B%5D=17&category%5B%5D=44&category%5B%5D=45&category%5B%5D=42&category%5B%5D=18&category%5B%5D=41)

**Comment by ChrisAlderson** [comment]
PT doesn't control the content.

**Comment by Persei08** [comment]
@ChrisAlderson you know better, but i was thinking it could be done on the popcorn-api side
