### ISSUE TITLE
Unable to Cast

### ISSUE THREAD

**Issue by jkb509** [popcorntime/popcorntime#457]
Operating System Version:
windows 10

Popcorn Time Version:
3.10

Download date:
01/20/17

#### Expected Behaviour
Cast to Smart TV
...

#### Actual Behaviour
 No Casting buttons is available 
...

#### Steps to reproduce the behaviour

1. ...Reinstall and also deleted all previous versions
2. ...
3. ...

**Comment by superbikerider69** [comment]
same problem here - was fine last week and now no option to cast

**Comment by Breaking1** [comment]
It works just fine with my Chromecast, if the Chromecast doesn't show up in the players menu i just restart PT and it usually does the trick.

If you are running a VPN service try to stop it before starting popcorntime, make sure the Chromecast shows up in the players menu. Then start the VPN service and continue as usual.
If you have any special characters in the Chromecast name like an apostrophe or something, remove it and then try.

If none of the above works please try this build and see if it works @superbikerider69 @jkb509 

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**Comment by zedszanue** [comment]
I also cannot see a Chromecast button in the app on Windows 10 even though my Chromecast is on and connected.
