### ISSUE TITLE
Stuck on "connecting", "timeout" ensues

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#458]
Operating System Version:
 OS X 10.12

Popcorn Time Version:
0.3.10-0 (84a68ce6)

Download date:
11th nov. 2016

#### Expected Behaviour
Start downloading a torrent

#### Actual Behaviour
Nothing happens. The app is stuck on "connecting".

![capture d ecran 2017-01-28 a 18 57 33](https://cloud.githubusercontent.com/assets/5691712/22398624/ecbd63b0-e58c-11e6-8538-264aa3ecf61f.png)

#### Steps to reproduce the behaviour
N/A 
First, I was afraid this issue was linked to my new ISP's router but then I tried with my phone over 4G, it still didn't work. Is there a way to conduct a deeper analysis?

I've no issues with downloading torrents and my internet connection is quite fast (~90 Mbps).

Thanks a lot.

Connection parameters:

![capture d ecran 2017-01-28 a 19 10 53](https://cloud.githubusercontent.com/assets/5691712/22398672/858705f6-e58d-11e6-9040-5546d14eee81.png)

**Comment by aesthese** [comment]
I have the same problem on MacOS 10.12.2 with PT 0.3.10.

**Comment by Claudjineo** [comment]
I have the same problem too on MacOS 10.10.5 with Popcorn Time 0.3.10
