### ISSUE TITLE
Magnet Links

### ISSUE THREAD

**Issue by tkarrde36** [popcorntime/popcorntime#46]
Was told a fix was was done for the magnet links.  However that was code written and the current version of Popcorn Time, 0.3.9 does not allow the Magnet Link to work.  Clicking on it only allows an option to open a file in the internet program of my choice.  It does not open in a torrent application.  How can this be resolved?  Do I need to rewrite the code myself with what was posted?

**Comment by Breaking1** [comment]
It's fixed in this build, you need to download from jenkins if you want all the latest improvements:

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/43/

**Comment by tkarrde36** [comment]
Which file?  When i chose win 32 it began an installation then aborted because of an error

**Comment by team-pct** [comment]
You can unzip the Windows file too , but if you do not mind please share the error

**Comment by Breaking1** [comment]
@tkarrde36 If you are using windows you can use the links with this ending
- win32-Setup.exe
- Win.zip

Win zip file you probably need to unzip but setup.exe should guide you trough the installation process.

**Comment by tkarrde36** [comment]
doesn't want to work.  I click on the above link posted by Breaking1 and when i choose either the win32 or with win zip i get the following message:
HTTP ERROR 404

Problem accessing /job/Popcorn-Time-Desktop/43/artifact/Release/Popcorn-Time-Win.zip. Reason:

```
Not Found
```

**Comment by Breaking1** [comment]
@tkarrde36 sorry about that, try this link.

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

**Comment by tkarrde36** [comment]
Thanks for the help.  Just an FYI the zip file says it is unable to be unpacked/uncompressed.  didn't give an error code but the setup link did work.
