### ISSUE TITLE
Update from latest Butter

### ISSUE THREAD

**Issue by maclir** [popcorntime/popcorntime#464]
There has been many fixes and improvements on the butter project which would be great to have on this project. e.g. https://github.com/butterproject/butter-desktop/commit/f07f3bc37a31727c067509132ef55d583cd6155d

**Comment by JimiC** [comment]
Actually, the code from `butter` doesn't resolve the issue but we are one step closer.

**Comment by JimiC** [comment]
I found out what's wrong. For the `movie` we need to resolve the `cover` property and for the `episodes` the `images` property. Hopefully, I'll find some time on the weekend to provide a PR, unless someone else beats me to it.
