### ISSUE TITLE
Bugs Help Needed

### ISSUE THREAD

**Issue by snorlex** [popcorntime/popcorntime#466]
i keep getting common  issues while trying to get it to work 

    gulp run

If you encounter trouble with the above method, you can try:

    npm install -g bower gulp (Linux: you may need to run with sudo)

    npm install
    bower install
    gulp build
    gulp run
i get bugs while trying to install them things missing etc if anyone can help please do

**Comment by chtrinh** [comment]
Do you see something similar to this? 
https://github.com/popcorn-official/popcorn-desktop/issues/468

If you do try using this PR: https://github.com/popcorn-official/popcorn-desktop/pull/469

**Comment by snorlex** [comment]
I fixed it but the scripts don't update from the source code stays the same stuff

**Comment by chtrinh** [comment]
Do you have screenshots or more details about the error message you are getting?

**Comment by snorlex** [comment]
It's not really an error just stays the same and nothing changes when I try updating the scripts

**Comment by chtrinh** [comment]
Correct me if I'm wrong, but this doesn't sound like a bug with the software, but a lack of 
knowledge of how this works... 

This might help if you know modern day web development: 
```
⌘+0 (opens up developer tools similar to chrome's)
```

**Comment by snorlex** [comment]
The first one was a bug that I fixed the one in the post
