### ISSUE TITLE
Watchlist is not working

### ISSUE THREAD

**Issue by xuko** [popcorntime/popcorntime#467]
Operating System Version:
Linux

Popcorn Time Version:
0.3.10 Beta

Download date:
5/2/2017

#### Expected Behaviour
On watchlist when I click an item must go to its detail
...

#### Actual Behaviour
On watchlist when I click an item it stay loading
...

#### Steps to reproduce the behaviour

1. go to watchlist
2. click an item
3. wait forever

![image](https://cloud.githubusercontent.com/assets/6314677/22625291/169eab7a-eb92-11e6-89cf-87862ff559b6.png)

**Comment by JimiC** [comment]
A known issue as `Watchlist` `detail` doesn't return a `Promise`. Duplicate with #308.
