### ISSUE TITLE
Popcorn Time download/connection issues.

### ISSUE THREAD

**Issue by kircaaaaa** [popcorntime/popcorntime#473]
Operating System Version:
Widows 10

Popcorn Time Version:
3.10 

Download date:
 Been using it a long time, reinstalled a couple of times hoping it would fix my situation.

#### Expected Behaviour
 Download my TV show with somewhere around 500kb/s - 5mb/s 

#### Actual Behaviour
 Download is very slow, getting stuck at 6kb/s or in some cases fluctuating between 300kb/s and 20/kbs like crazy.
...

#### Steps to reproduce the behavior
 I suppose it's not really a bug, but I know its not my Internet causing the issue 

1. 
2. 
3.

**Comment by joannajohn** [comment]
what about the subs??? i can't watch my movies on greek subs.

**Comment by chtrinh** [comment]
Have you tried clearing out your temporary cache and/or flushing your database in the settings? Check your disk/swap space.

**Comment by kircaaaaa** [comment]
@chtrinh  I have tried that.

**Comment by chtrinh** [comment]
@kircaaaaa: do you have a specific torrent or movieId, I can use to test this behavior out?

**Comment by ChrisAlderson** [comment]
Probably a lack of seeders, can't do anything about that.

**Comment by AussieA** [comment]
i can't even see what is available.
