### ISSUE TITLE
Notification of "no subtitles" irrelevant

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#476]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
2 days

#### Expected Behaviour

Expected the app to notify of "no subtitles avaialable" only when there are no subtitles available. 

#### Actual Behaviour
The app notifies me of "no subtitles avaialable" 100% of the time, even where there is subtitles loaded and subtitles are shown in the movie. 

#### Steps to reproduce the behaviour
- go to settings
- enable subtitles to Francais
- link opensubtitles account
- go to movie list
- click on a movie
- click on button to watch movie
( here the yellow notification of no subtitles is shown on top-right of the screen, even when subtitles are effectively loaded)
- watch the movie and note that the subtitle are shown

**Comment by RoiArthurB** [comment]
I've got the same issue (french ftw \o/ ), but there're no subtitles at all...
I've create a request on the subreddit here : https://www.reddit.com/r/PopCornTime/comments/5v5ejt/no_subtitles_on_movies/

**Comment by Breaking1** [comment]
@pouledodue try this build and see if everything works correctly.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**Comment by stragu** [comment]
Haven't tried the linked build yet, but just wanted to confirm with PT 0.3.10 and English subtitles on an Ubuntu 14.04-based system. The pop-up appears every time, even when subtitles are loaded fine.

**Comment by Breaking1** [comment]
@stragu the pop up msg with no subtitles available when they are should also be fixed in the version i linked too.

Please report back if you are experiencing any problems with the build i posted.

**Comment by ghost** [comment]
@Breaking1 works great thanks for the fix
