### ISSUE TITLE
Subtitles not working!! Old version, help me!

### ISSUE THREAD

**Issue by Fellipebio** [popcorntime/popcorntime#478]
Operating System Version;
Windows 8

Popcorn Time Version:
0.39 I guess (old version) 

Download date:
 I don't remember 

#### Expected Behaviour:
Portuguese (Brazil) subtitles must work

#### Actual Behaviour:
 It doesn't open the subtitles

#### Steps to reproduce the behaviour

1. Open any movie
2. Search the Portuguese (Brazil) subtitles, actually anyone are not working.
3. Subtitles are disabled.

**Comment by Trisky** [comment]
Hi and welcome to github!

Well, it seems that you didn't fill the issue template,we really can't help you with your issue because we can't reproduce your problem. Please add the required information, thank you!

**Comment by Fellipebio** [comment]
Ok! I completed the issues.

**Comment by ChrisAlderson** [comment]
Update to 0.3.10, see if it helps.
