### ISSUE TITLE
New Update and Stability Improvements Fixing

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#479]
When is the new update and stability improvements coming out? 😕

**Comment by iMansoorAliKhan** [comment]
Looking to get this re-opend in 2018-2019, can you atleast give us new update / proposed update list?

**Comment by team-pct** [comment]
you can always use ci.popcorntime.sh that is all what we can offer !

**Comment by iMansoorAliKhan** [comment]
@team-pct is that a dev link and are those setup file safe to be installed?

**Comment by team-pct** [comment]
yes they are built from the code on github , you can have a look here https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/console
