### ISSUE TITLE
Cannot stream to Xbox One any longer.

### ISSUE THREAD

**Issue by BeardedDraggon** [popcorntime/popcorntime#481]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
A few weeks ago I had to reinstall.

#### Expected Behaviour
I could stream to my xbox one before the reinstall, now it won't.
...

#### Actual Behaviour
Will stream to chromecast but not to my xbox any longer.
...

so over the last week, I had to reinstall popcorn time due to someone messing with my pc and causing issues with programs.  After the reinstall, it won't stream to Xbox One anymore.  I uninstalled and reinstalled again but to no avail. It streams to Chromecast fine, but I like the Xbox One streaming more, where I can use the controller to pause/rewind/fast foward.  Anyone have any issues?

**Comment by Breaking1** [comment]
I guess this one can be closed since it seems to work correctly in the latest version.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/


https://www.reddit.com/r/PopCornTime/comments/5uun6f/pct_wont_stream_to_xbox_one_anymore/
