### ISSUE TITLE
Cannot stream to Apple TV.

### ISSUE THREAD

**Issue by justinjsp** [popcorntime/popcorntime#482]
Operating System Version:
OS X 10.11

Popcorn Time Version:
0.3.10-0

Download date:
JANUARY 2017

#### Expected Behaviour
Stream to my appleTV
...

#### Actual Behaviour
Nothing
...

#### Steps to reproduce the behaviour
Stream to an appleTV?

1. ...
2. ...
3. ...

**Comment by Breaking1** [comment]
@justinjsp have you tried this one, it's made for Apple TV.

https://github.com/PopcornTimeTV/

**Comment by justinjsp** [comment]
I would, except in using a 3rd gen AppleTV.
