### ISSUE TITLE
Can't delete text on MacBook Pro mid-2012

### ISSUE THREAD

**Issue by jaybirddanglade** [popcorntime/popcorntime#483]
Operating System Version:
<OS X 10.12.3>

Popcorn Time Version:
<5.5.1.3>

Download date:
<January 2017>

#### Expected Behaviour
<>
...delete text in search bar when delete key is pressed
#### Actual Behaviour
<>
...nothing, no text edited

#### Steps to reproduce the behaviour
<>
Type text in the search bar and try to delete it
1. ...type text in search bar
2. ...place cursor at rightmost point after text
3. ...press delete key (backspace on other keyboards)

Workaround for me has been highlighting all text and retyping... this removes the text and replaces it.

**Comment by ChrisAlderson** [comment]
Not our version.
