### ISSUE TITLE
nwjs stop working on pct 3.10

### ISSUE THREAD

**Issue by Jamwalker** [popcorntime/popcorntime#484]
Operating System Version:
 Windows 7 64bits

Popcorn Time Version:
 3.10 

Download date:
02/19/2017

#### Expected Behaviour

 Open 

#### Actual Behaviour
When I try to run the executer a window show up saying the nwjs stop working

#### Steps to reproduce the behaviour

1. install the 3.10 version
2. try to run the executer.
![sem titulo](https://cloud.githubusercontent.com/assets/25890231/23109698/1ef8dae8-f6fa-11e6-8f58-1f5a345fee76.png)

**Comment by Trisky** [comment]
Did you try restarting your computer or disabling 3rd party software (antivirus maybe?) and then restart?

ps: welcome to github.

**Comment by Jamwalker** [comment]
@Trisky  Actually I downloaded the Popcorn-Time-0.3.10-win64-Setup.exe from Jekins and now its working fine. Thanks.  Here is the link I get from reading other Issues on  @Github.
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/
