### ISSUE TITLE
Opensubtitles

### ISSUE THREAD

**Issue by Berserker357** [popcorntime/popcorntime#490]
Operating System Version:
Windows 8

Popcorn Time Version:
0.3.10 

Download date:
 2 weeks ago but i think he update yesterday

#### Expected Behaviour
 App was doing fine 
...

#### Actual Behaviour
Since yesterday noon the app does not conect to opensubtitltes so i don´t have subtitles during the reproducing of films and series. Already try to click and conect to open subtitles a few times but didn´t work
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by khaledali1001** [comment]
i can connect my account to Opensubtitle, but even there is no subtitles since yesterday
when click on subtitle button, only "Disabled & Custom" there!

**Comment by Berserker357** [comment]
I can´t conect the app don´t make the conection.... and the same happen´s to me with the sub´s only apear the options disabled ans personalize.... But i thought that was because of not been conected to opensubtitles

**Comment by MinistroDolar** [comment]
I'm having the same problem u.u

**Comment by brjuba84** [comment]
I have the same problem. Captions "off or customize" and when the movie starts to be transferred a message informs that no subtitles were found and informs to return later. I hope it's temporary

**Comment by RenatoPeixoto23** [comment]
I have the same problem.
No caption appears. I've even reinstalled and it still does not work.
Please help

**Comment by NiRovil** [comment]
I have the same problem, it's so sad...

**Comment by marwarakka** [comment]
same problem also since two weeks ago

**Comment by bsm0325** [comment]
same for me. who will address this problem?

**Comment by Berserker357** [comment]
I don´t know how to do that.... thought the moderators pay atention on issues we insert here!!!

**Comment by intermalta** [comment]
[ERROR] OpenSubtitles.login() 414 Unknown User Agent

**Comment by Berserker357** [comment]
I Already try to login at opensubtitles and there´s no problem, work
fine... at popcorn time the app do not establish the conection to
opensubtitles.


2017-03-01 16:27 GMT+00:00 intermalta <notifications@github.com>:

**Comment by bsm0325** [comment]
That's my point. Why isn't any of the moderators or devs picking up on this error or malfunction?!

**Comment by team-pct** [comment]
Because we are still looking with @opensubtitles 
Meanwhile you can modify your User-agent in src/app/lib/providers/opensubtitles.js to 

> Butter v1

**Comment by jpjocaramos** [comment]
Has anyone managed the solution to login and download subtitles automatically?

**Comment by diego-treitos** [comment]
+1 with the problem here

**Comment by JimiC** [comment]
Confirming that changing the User-agent to `Butter v1` works. Subtitles are downloading again.

**Comment by jpjocaramos** [comment]
@JimiC How can I make this change in User-agent ? Is there any tutorial to do this setup?

**Comment by JimiC** [comment]
No tutorial, sorry. Locate where `Popcorn` is installed on your machine and find the `src/app/lib/providers/opensubtitles.js` file. Open it in an editor and make the change.

**Comment by brjuba84** [comment]
Hmm! Does anyone know the way to get there using an iMac?

**Comment by diego-treitos** [comment]
For me changing the User Agent is not working: it does not log in.

**Comment by jpjocaramos** [comment]
@JimiC Okay. I have opensubtitles.js open, what code do I change? Was this?

`var formatForButter = function (data) {
        data = normalizeLangCodes(data);
        for (var lang in data) {
            data[lang] = data[lang].url;
        }
        return Common.sanitize(data);
    };

    OpenSubtitles.prototype.fetch = function (queryParams) {
        queryParams.extensions = ['srt'];
        return openSRT.search(queryParams)
            .then(formatForButter);`

**Comment by Berserker357** [comment]
No scroll the file to your Right side until you find User agent.... change
what´s in front for Butter v1


2017-03-02 21:58 GMT+00:00 jpjocaramos <notifications@github.com>:

**Comment by Berserker357** [comment]
Team-pct Thanks for your answer.... This was my 1st post so i didn´t have
sure if you guys pay atention to all issues we put here.
No i know you are !!

Can you please tell me if is possible to chose different subtitles??
Because some of them aren´t synchronized with the movie\serie...

Thanks

2017-03-01 19:12 GMT+00:00 team-pct <notifications@github.com>:

**Comment by jpjocaramos** [comment]
@Berserker357 , @JimiC I changed the code but I can not log in to open substitutes, can anyone solve this?

* Code that I changed:

 var OpenSubtitles = function () {
        openSRT = new OS({
            useragent: 'Butter v1', 
            username: Settings.
            password: Settings.

**Comment by Berserker357** [comment]
I can´t to but if u change useragent subtitles are working
Try...

2017-03-02 22:26 GMT+00:00 jpjocaramos <notifications@github.com>:

**Comment by hugobme** [comment]
I changed the useragent, it worked during two episodes but now doesn't not working again. I can log in to opensubtitles on settings but the subtitles don't show up again. :(

**Comment by brunotacca** [comment]
+1 same problem.

Changing the user agent to Butter v1 works, but still can't connect with OpenSub.
