### ISSUE TITLE
No Sound - when chrome casting 720p or 1080p in "Series" episodes only!

### ISSUE THREAD

**Issue by khaledali1001** [popcorntime/popcorntime#491]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
2/28/2017

#### Expected Behaviour
The sound will work when chrome casting 720p or 1080p Series episode
...

#### Actual Behaviour
No sound when chrome casting 720p or 1080p Series episode, while it works only 420p
...

#### Steps to reproduce the behaviour
1. Select any series episode with 720p or 1080p
2. Chrome cast a series episode on 720p or 1080p
3. No sound will appear.

**Comment by rfigueroa-zz** [comment]
the old Chromecast does not support AC3 audio, this may be the issue you are experiencing

**Comment by Trisky** [comment]
hi, i have a first gen Chromecast and it works just fine with 720p or 1080p

Have you tried to test it with youtube or spotify just to make sure it's not a popcorntime issue?
Also, reseting the chromecast may be a good idea.

**Comment by khaledali1001** [comment]
yes tried youtube and it works, also popcorn time "movies" on 720p or 1080p works fine!
only series episodes on 720p, doesn't have sound? weird !!

**Comment by ChrisAlderson** [comment]
Dupe of #262.
