### ISSUE TITLE
[Request] Flatpack Repository

### ISSUE THREAD

**Issue by Eeveel** [popcorntime/popcorntime#492]
Hi,
Is it possible to have a Flatpack Repository, that can allow to easily update the PopcornTime version for Linux environment user?
Thanks for your hard work!

**Comment by ChrisAlderson** [comment]
I would rather see this issue move to Butter since they already have an issue about it here: https://github.com/butterproject/butter-desktop/issues/559.

**Comment by aiamuzz** [comment]
there are some efforts happening in this regard ...

https://gitlab.com/Preisschild/popcorntime-flatpak/blob/master/README.md
