### ISSUE TITLE
Subtitles are all out of sync or wrong for all the shows 

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#495]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10 Beta 

Download date:
Yesterday for last time

#### Expected Behaviour
Download right subtitle for the show I want to see
...

#### Actual Behaviour
Since many month, I can't have any show with the right subtitle.
In the dropdown, I can see many language sometimes, but none of them is synchronized with the show or it's a subtitle for another show.
...

#### Steps to reproduce the behaviour
1. Click on one of my favorite show, "english" is default subtitle or select another language
2. Subtitle is not right or out of synch

Thanks

**Comment by dandeveloper** [comment]
I usually solve the subtitles sync issue just using the key G to delay or key H to advance the subtitles sync time.

**Comment by BearKiss** [comment]
Confirm this bug. Subtitles (English and Finnish, have not tested other languages) are all wrong, probably from another movie or something. Tested with several movies. Downloading subtitles separately and Subtitles -> Custom and opening the downloaded subtitle file shows subtitles correctly.

**Comment by akirayamamoto** [comment]
I tried syncing the subtitle for Carandiru movie by clicking on the up and down arrows and it didn't work. I tried loading a custom subtitle and use the sync but didn't work either.

**Comment by Apollinaire** [comment]
I found that if you have set a default subtitle it will be out of sync all the time. It seems that the subtitles are read at a different speed than the video, because syncing them manually with G or H keys always results to a desync after a few minutes. Also, the other languages don't desync, only the language set as default.
**To solve this, just unset the default subtitles.**
Too bad, because this feature is quite nice.
Found this bug on Ubuntu 16.04, using Butter player.

**Comment by awesomeguy3** [comment]
@Apollinaire I'm having the same issue, will try out your solution, but I had no problem with this up until few days ago and I had default subtitles set in my settings. Strange

**Comment by dutchy1001** [comment]
Nice necro post 🤣🤣🤣

Most subtitles are coming from a 3rd party download (some are build within the file which are usually a better match) , it will search for the best matching file name. This can then cause the sync issue. There is not much they can do about this as it's a 3rd party not involved of the development of PCT, hence this was a closed topic.
