### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by nzvicente** [popcorntime/popcorntime#501]
Operating System Version:
Windows 10 pro

Popcorn Time Version:3.1.0 beta
3.1

Download date:
3 months ago

#### Expected Behaviour
search by date and actor name
...

#### Actual Behaviour
i can't search by date and actor name. Its work only y movies name...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by nzvicente** [comment]
I can't to search by date or by actor name.

**Comment by nzvicente** [comment]
how can i search any movies typing date or actor name?

**Comment by PauloHenriqueDosSantos** [comment]
I can't search some movies and series by name, for exemplo: if I search for Grey's Anatomy or Anathomy or Grey's, I don't get anything, but if I search for Grey, then it works. Please, let the search function bring all the content that matches. Thanks!
