### ISSUE TITLE
Search by actor, director, writer

### ISSUE THREAD

**Issue by amnchre** [popcorntime/popcorntime#505]
This used to be possible in the Community Edition at some point in time and now it doesn't. Also crediting actors and directors in the description would make this app perfect.
Thanks people.

**Comment by nzvicente** [comment]
I can't search by year, actor or diretor. I can do it only by movie name

**Comment by a3zzat** [comment]
that's a nice feature to have

**Comment by stivens13** [comment]
++

That would be superb to have this ability, especially if you want to watch a series of movies with the same actor or director.
