### ISSUE TITLE
popcorn-desktop build failing on guppy pre-commit

### ISSUE THREAD

**Issue by DimensionsGaming** [popcorntime/popcorntime#507]
Operating System Version: Ubuntu 17.04

Popcorn Time Version: 0.3.10

Download date: 24/03/17

#### Expected Behaviour

...
When running npm install, the install to complete without any errors.
#### Actual Behaviour

...
When running npm install, the install fails on guppy pre-commit. I've checked and node is correctly installed. 
#### Steps to reproduce the behaviour

1. cd into popcorn-desktop directory
2. run npm install

I'll attach the log file from the install.
[npm-debug.txt](https://github.com/popcorn-official/popcorn-desktop/files/867236/npm-debug.txt)

**Comment by DuncanFairley** [comment]
I also get this from latest development branch, when installing from `make_popcorn.sh`.

**Comment by DuncanFairley** [comment]
Sounds weird, but I fixed this by not installing as root.
chown the entire directory to a non-root user then `npm install`.
