### ISSUE TITLE
No subtitles (app.js:21 [ERROR] subtitleProvider.fetch() 401 Unauthorized)

### ISSUE THREAD

**Issue by hejman** [popcorntime/popcorntime#509]
Operating System Version:
Mac Sierra 10.12.3

Popcorn Time Version:
0.3.10.0

Download date:
Today

#### Expected Behaviour
Expected subtitles to show
...

#### Actual Behaviour
No subtitles are available
...

#### Steps to reproduce the behaviour
Watch movie with subtitle setting on.

From console:
app.js:21 [ERROR] subtitleProvider.fetch() 401 Unauthorized

Additionally the program crashes everytime i close it.

**Comment by streger** [comment]
Try with latest nightly from ci.popcorntime.sh
