### ISSUE TITLE
[Feature Request] Stream Music

### ISSUE THREAD

**Issue by a3zzat** [popcorntime/popcorntime#510]
Adding the ability to stream (video) music albums. So instead of download music torrents users would be able to stream music torrents directly. This will increase the user base significantly.

**Comment by streger** [comment]
no.

**Comment by ChrisAlderson** [comment]
out of scope

**Comment by milahu** [comment]
any alternative solutions? popcornmusic-desktop?

music torrent sources:

- [thepiratebay.org > music](https://thepiratebay.org/search.php?q=category:101)
- [1337x.to > music](https://1337x.to/popular-music)
- [kickasstorrents.to > music](https://kickasstorrents.to/music/)
- [torlock.com > music](https://www.torlock.com/music.html)
- [limetorrents.lol > music](https://www.limetorrents.lol/browse-torrents/Music-Music/)
- [torrentdownloads.pro > music](https://www.torrentdownloads.pro/category/5/Music)
- [rutracker.org > music](https://rutracker.org/forum/index.php?c=8)
- [isohunts.to > music](https://isohunts.to/music_isohunt.html)
- [mixtapetorrent.com](http://www.mixtapetorrent.com/)
- [torrentfunk.com > music](https://www.torrentfunk.com/music.html)
- [audionews.org](https://audionews.org/) - audio production and editing software
- [DHT database dumps](https://github.com/btdig/dhtcrawler2/issues/5)
  - https://tnt.maiti.info/dhtd/
  - search for music files: mp3, flac, m4a, aac, opus, ...
  - many dead torrents

the category system can be too strict, so music can also be in the `other` section

music metadata sources:

- discogs.com
  - https://data.discogs.com/
  - [Discogs complete database in SQLite (2.7 GB)](https://old.reddit.com/r/DataHoarder/comments/x2n4hr/discogs_complete_database_in_sqlite_27_gb/) (2022-08-31)
  - https://github.com/philipmat/discogs-xml2db
- [last.fm](https://www.last.fm/) - recommendations, popular tracks

**Comment by dutchy1001** [comment]
How about this for a nerco answer

**Comment by merseyV** [comment]
lol .. sure you didn't mean necro?

**Comment by merseyV** [comment]
>for a nerco answer

lol .. sure you didn't mean necro?  


![po-fall](https://github.com/user-attachments/assets/5d2ea3db-9f0b-4281-920f-be46a5101b5f)

**Comment by dutchy1001** [comment]
what else is it called when trying to reviving an old post?

⚰️⚰️⚰️


> necro post:

> (Internet, slang, transitive, intransitive) To post to a long, inactive discussion thread on a forum.

**Comment by dutchy1001** [comment]
@milahu 
Instead of giving a tumbs down make a fork and start implementing it.

If our main devs think this can be added then I'm sure they will have a good think about it. On the other hand, I presume this will be overkill for PCT and a new app on the same basis might be the better option.

I would also like to say that this will attract way more attention then we want if you get my drift 🤔🤔🤔

**Comment by milahu** [comment]
> a new app on the same basis might be the better option

this is what i was asking with "alternative solutions"
because services like youtube or spotify just suck...

> this will attract way more attention then we want

stealing music is worse than stealing movies? nah
anyway, [mirror](https://github.com/git-bug/git-bug) to [darktea](https://github.com/milahu/darknet-git-hosting-services), run more seedboxes in all countries

in my view, the the copyright trolls' only attack surface are "commercial" services
having ads on your website already qualifies as "commercial"
see thepiratebay.org or torrent.to
but for most users, filesharing is an expensive hobby, with zero profit
so the takedown requests are safe to ignore (at least here in [germany](https://www.szenebox.org/73-%C2%A7%C2%A7_rechtsfragen/16280-modue_nicht_zahlen_bei_torrent_abmahnung/))

**Comment by dutchy1001** [comment]
> stealing music is worse than stealing movies?

Indeed there is no differance there I agree but, if you know the history of PCT then you should understand that we (as a team) would like the attention from certain organisations to be kept to a minimum. Adding an other layer they wont like will bring more attention to the app.
If we are compaired to "the piratebay" for example a whole tin of other organisations will try to stop this.

So if you deside to create a similar app but then for music, just let me know and I'll have a look (I just don't code myself).

**Comment by merseyV** [comment]
>but, if you know the history of PCT ...

This "feature request" has been turned down (consistently) every time it's been raised. Chris Alderson's closing comment "Out of scope" .. just about covers it? Additionally, when the OP started this thread (early-2017), there were a lot more Devs than are currently present [sic]. Any chance has now long passed?

Fast forward: popcorntime-desktop appears to be in maintenance-mode atm?  Notwithstanding, its rejection ... there's no-chance of anything that involved being undertaken - for the foreseeable?

Your aspirations are worthy .. just don't expect it to happen here?

**Comment by merseyV** [comment]
>but, if you know the history of PCT ...

This "feature request" has been turned down (consistently) every time it's been raised. Chris Alderson's closing comment "Out of scope" .. just about covers it? Additionally, when the OP started this thread (early-2017), there were a lot more Devs than are currently present [sic]. Any chance has now long passed?

Fast forward: popcorntime-desktop appears to be in maintenance-mode atm?  Notwithstanding, its rejection: There's no-chance of anything that involved being undertaken - for the foreseeable?

Your aspirations are worthy .. just don't expect it to happen here?

**Comment by merseyV** [comment]
>but, if you know the history of PCT ...

This "feature request" has been turned down (consistently) every time it's been raised. Chris Alderson's closing comment "Out of scope" .. just about covered it? Additionally, when the OP started this thread (early-2017), there were a lot more Devs than are currently present [sic]. Any chance has now long gone!

Fast forward: popcorntime-desktop appears to be in maintenance-mode atm?  Notwithstanding, its rejection: There's no-chance of anything that involved being undertaken - for the foreseeable?

Your aspirations are worthy .. just don't expect it to happen here?

**Comment by merseyV** [comment]
>but, if you know the history of PCT ...

This "feature request" has been turned down (consistently) every time it's been raised. Chris Alderson's closing comment "out of scope" .. just about covered it? Additionally, when the OP started this thread (early-2017), there were a lot more Devs than are currently present [sic]. Any chance has now long gone!

Fast forward to now, popcorntime-desktop appears to be in maintenance-mode atm?  Notwithstanding, its rejection: There's no-chance of anything that involved being undertaken - for the foreseeable?

Your aspirations are worthy .. just don't expect it to happen here?

**Comment by merseyV** [comment]
>but, if you know the history of PCT ...

This "feature request" has been turned down (consistently) every time it's been raised. Chris Alderson's closing comment "out of scope" .. just about covered it? Additionally, when the OP started this thread (early-2017), there were a lot more Devs than are currently present [sic]. Any chance has now long gone!

Fast forward to now, popcorntime-desktop appears to be in maintenance-mode atm? There's no-chance of anything "that involved" being undertaken - for the foreseeable?

Your aspirations are worthy .. just don't expect it to happen here?

**Comment by milahu** [comment]
blah...

> out of scope

yes, i was asking for "alternative solutions"

a video player is very different from a music player
just like videophiles are very different people than audiophiles
the main commonality here is "free and open-source"

**Comment by merseyV** [comment]
yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with me and @dutchy1001 at the helm? 

Closest I came to a solution was the (now defunct) Deemix projects, and a Deezer free trial. I managed to download a shed-load of flac files .. for my personal "Library".

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with me and @dutchy1001 at the helm? 

Closest I came to a solution was the (now defunct) Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files .. for my personal "Library".

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with Statler and Waldorf at the helm? 

Closest I came to a solution was the (now defunct) Deezloader/Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files .. for my personal "Library". I still use Deezer as a "radio" (background music).

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with Statler and Waldorf at the helm? 

Closest I came to a solution was the (now defunct) Deezloader/Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files - for my personal "Library". I still use Deezer free as a "radio" (background music).

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with Statler and Waldorf at the helm? 

Closest I came to a solution was the (now defunct) Deezloader/Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files - for my personal "Library". 

I still use Deezer free as a "radio" (background music). ... It's on now!! :)

<img width="1118" alt="Screenshot 2024-12-03 at 12 49 00" src="https://github.com/user-attachments/assets/95989ef6-762d-4cb5-b09c-cc7842f79b9f">

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread on the "Marie Celeste" ... with Statler and Waldorf at the helm? 

Closest I came to a solution was the (now defunct) Deezloader/Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files - for my personal "Library". 

I still use Deezer free as a "radio" (background music). ... It's on now!! :)

<img width="1118" alt="Screenshot 2024-12-03 at 12 49 00" src="https://github.com/user-attachments/assets/95989ef6-762d-4cb5-b09c-cc7842f79b9f">


You can wade through [**this lot**](https://fmhy.net/audiopiracyguide) ... if you haven't already? Not sure how up to date all the links are, though.

**Comment by merseyV** [comment]
>yes, i was asking for "alternative solutions"

lol ... I'd have chosen a better place to ask: Not a dead thread, on the "Marie Celeste" - with "Statler and Waldorf" at the helm? 

Closest I came to a solution was the (now defunct) Deezloader/Deemix projects, and a Deezer free account/trial. I managed to download a shed-load of flac files - for my personal "Library". 

I still use Deezer free as a "radio" (background music). ... It's on now!! :)

<img width="1118" alt="Screenshot 2024-12-03 at 12 49 00" src="https://github.com/user-attachments/assets/95989ef6-762d-4cb5-b09c-cc7842f79b9f">


You can wade through [**this lot**](https://fmhy.net/audiopiracyguide) ... if you haven't already? Not sure how up to date all the links are, though.

**Comment by milahu** [comment]
problem: all "official" music collections are censored

example: deezer has censored ...

- böhse onkelz
- chris ares
- K.I.Z - Frei sein RMX
- Blokkmonsta, Schwartz, Uzi - Fick die BPJM
- [Wizo - Eine Revolution für die Anarchie](https://genius.com/Wizo-kein-gerede-lyrics)
  - deezer only has the instrumental version: Wizo - Kein Gerede
  - this song is officially banned in germany, because of "incitement to violence"

... so i still want an uncensored peer-to-peer music collection

https://fmhy.net/audiopiracyguide#download-sites looks useful : )

**Comment by milahu450** [comment]
> problem: all "official" music collections are censored

also: its too hard to download music from "official" sources like youtube
compared to protocols like bittorrent or rsync
which let me "fire and forget" and they just work
(voluntary micropayments for seeders with [nano coins](https://nano.org/) would be nice)

example: download all music from [my youtube channel](https://m.youtube.com/@milahu)
(all uploads and playlists)
yt-dlp fails on many videos with http 403
