### ISSUE TITLE
High RAM usage over long period of time

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#512]
Operating System Version:
Win 10 Pro x64

Popcorn Time Version:
0.3.10

Download date:
about a month ago

#### Expected Behaviour
Not using a lot of RAM (~2GB) when idle.

#### Actual Behaviour
One of the nwjs processes had a peak of about 2 gb ram usage. It took several minutes to free up that memory after clicking the "X" mark of the popcorn window.

This is the culprit child process:
![immagine](https://cloud.githubusercontent.com/assets/6625123/24429000/93c8a9ec-1410-11e7-9170-0562997d133f.png)

#### Steps to reproduce the behaviour
I didn't try to reproduce this behaviour yet. I had Popcorn Time open since st patrick up to yesterday. I usually hibernate my pc instead of shutting it down.

-------------------------

O.T. Are CI builds available for download somewhere?

**Comment by streger** [comment]
try with lastest ci version.

ci.popcorntime.sh
