### ISSUE TITLE
Audio and video loosing sync

### ISSUE THREAD

**Issue by gojirian** [popcorntime/popcorntime#513]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
Reinstalled on 28th March 17

#### Expected Behaviour
Play a video
...

#### Actual Behaviour
Video looses sync with the audio. don't have this issue on my Fedora PC.
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by a3zzat** [comment]
I faced the same issue 
It mainly happens after seeking the video several times it lose sync (using arrows and shift ...etc)

**Comment by streger** [comment]
Probably problem with actual video that is and never have been under pt influence or with the statted system resources.
Recommendation:
1. clean your windows pc totally software-wise
2. upgrade it physically
3. download latest ci version and test again
4. use VLC, MPC-HC as your external player from pt.
