### ISSUE TITLE
[Feature Request] UTF-8 support for subtitles

### ISSUE THREAD

**Issue by blackshot** [popcorntime/popcorntime#515]
the title says all, its annoying to read some words with unreadable chars.

**Comment by streger** [comment]
It depends what language you are using as default in your system. Help out and make this a proper report. What language are you using as default on your system? What is the most common language code for your language? What system are you using? Are there some or any chars that work ok?
...

**Comment by blackshot** [comment]
spanish (LatinAmerican) or ES_CL (Chile)

**Comment by blackshot** [comment]
response time sucks here
