### ISSUE TITLE
More Subtitle Sources for Bulgarian Language

### ISSUE THREAD

**Issue by Dellius** [popcorntime/popcorntime#517]
I see that PopCornTime is using OpenSubtitles to find subtitles for movies, but at least for Bulgarian there are two more very important sites, which actually house most, if not all Bulgarian subtitles - susbsunacs.net and subs.sab.bz are the top providers for subtitles for this language and very often they will have subtitles for movies when OpenSubtitles doesn't have anything.

Please consider adding these sites to PopCornTime's engine as well.

**Comment by streger** [comment]
To achive this, both of those bg sites should use some kind of API to serve subs. Please go to https://github.com/butterproviders/butter-provider and check if those sites can be compiled to make a working version for pt. If not I suggest you to try to investigate this more and find more about how all this works. In idea it's very simple: if you have an API that serve some content, make the simple code to be adequate for pt and it will work.

**Comment by ubone** [comment]
Just FYI [VLC](http://www.videolan.org/vlc/) easily finds and applies bulgarian subtitles.
