### ISSUE TITLE
Magnet links/torrent link crashing android app

### ISSUE THREAD

**Issue by Josecjr** [popcorntime/popcorntime#52]
I'm using  a galaxy S5  with android 5.0. When i try to open a magnet or torrent link,  its buffer the video.  But when the video player opens,  the app crashes.  Here the link example magnet:?xt=urn:btih:081FBC9A4D852329BE6C9A5411DCD1B96543EC03&dn=Dragon.Ball.Kai.Completo.Parte.1.2011.720p-WOLVERDONFILMES.COM&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.ccc.de%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337

**Comment by team-pct** [comment]
Please post your issue here https://github.com/popcorn-official/popcorn-android/issues
