### ISSUE TITLE
[Feature Request] Notification?

### ISSUE THREAD

**Issue by brij1234** [popcorntime/popcorntime#521]
Some kind of notification system, when a favorited TV show adds a new episode?

I would get started on this but I barely know JS. I'm a C#/ASP.NET programmer.

Operating System Version:
Latest OSX

Popcorn Time Version:
latest

**Comment by Persei08** [comment]
At the moment there is a watchlist tab, it's partially broken but it should sync with your trakt.tv account.
It display the covers of followed shows when you have episodes to watch, but it's broken when you click this covers.

related to this issue https://github.com/popcorn-official/popcorn-desktop/issues/308

**Comment by a3zzat** [comment]
Actually it would be nice to have this feature locally without website support

**Comment by brij1234** [comment]
Or, maybe add a banner on top of the thumbnail saying "Updated", when an episode is added.

**Comment by streger** [comment]
Cute stuff, but do think of the requests that app would need to do...what every minute, or...every second to the API's that are needed for the app to run.
Maybe in some future when somebody thinks about fully shared, distributed system that doesn't take a lot resource hog to couple of computers somewhere in the world.

Maybe in some universe like in Silicon Valley universe episodes.
