### ISSUE TITLE
The application popcontime for pc or phone and tablet is slow, freezes ... except the version of pc, the others do not load subtitles or allow to personalize it ...It is absurd that even the version popcorn-time.to having malware is more faster starting and allows to select subtitles

### ISSUE THREAD

**Issue by rodegaston2** [popcorntime/popcorntime#522]
Operating System Version:
 win 10

Popcorn Time Version:
 3.10

Download date:
a week ago

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by rodegaston2** [comment]
The application popcontime for pc or phone and tablet is slow, freezes ... except the version of pc, the others do not load subtitles or allow to personalize it ...It is absurd that even the version popcorn-time.to having malware is more faster starting and allows to select subtitles

**Comment by Persei08** [comment]
This is an opensource project, If you know how to code, you can try to fix issues, and submit your patches for review.
If you don't know how to code, you can always try to convince new developers to join the project, report issues, or ask for features, improvements.

At the moment, the way you're reporting issues is not helpful, and seem to be motivated for lowering developers motivation.

Also the funny part is you can't even write a short and digest title... Nobody is perfect :)

**Comment by rodegaston2** [comment]
That's funny ... you don't have a platform of suggestions with indicated
scores, so the long title was done on purpose, I thought it was obvious ..
but hey, no one is perfect..
   Sorry if I offended you, it wasnt my intention.
   Apparently it is more efficient to ask nonconformists to fix the problem
for you, even if it is an open source program :-D , Which is in fact
happening in many pages and there create fasters versions without this
problems, with the exception of a thousand Trojans, malware and all that
shit.. :-(
   Try to be grateful to the opinions of people who take the trouble to
download your program and even contact with you guys, you depend on the
recommendations of the users...we spread the word... Iti's mean you can be
better, not just believes you're better than everyone else.
   Your program is great, keep that way... thanks

**Comment by fernandofleury** [comment]
you can either help fixing it, or download the trojan version instead of complaining. don't try to mask it with "opinion". you are plain straight complaining about something 100% free. feel free to help.
