### ISSUE TITLE
Error loading data, try again later

### ISSUE THREAD

**Issue by wimvanerp** [popcorntime/popcorntime#523]
Operating System Version:

Popcorn Time Version:

0.3.10-0 

Download date:

08-04-2017

#### Expected Behaviour

I thought there wouldn't be an error message, but there was.

#### Actual Behaviour

Give an error message

#### Steps to reproduce the behaviour

1. Open a movie
2. In the top righthand position a message will appear

**Comment by streger** [comment]
Oh, c'mon...this issue is ready for closing.
