### ISSUE TITLE
Subtitles disabled problem[FIXED]

### ISSUE THREAD

**Issue by MMK005** [popcorntime/popcorntime#524]
Operating System Version: Windows 10

Popcorn Time Version: latest

Download date: 08.04.17

#### Expected Behaviour

Subtitles used to work perfectly till last week

#### Actual Behaviour

subtitles option is disabled and it not even responding to custom subtitles

**Comment by Persei08** [comment]
here some [log from the debug console](http://imgur.com/a/p92TV)

**Comment by joaopjt** [comment]
It seems to be working on again! Try it out again.. Maybe the subtitles api was off by yesterday... I was having the same problem, but it's working now.
