### ISSUE TITLE
No audio while casting on Chromecast

### ISSUE THREAD

**Issue by zedszanue** [popcorntime/popcorntime#525]
Operating System Version:
Windows 7 Professional

Popcorn Time Version:
3.10

Download date:
April 5, 2017

#### Expected Behaviour
Have audio play through TV while casting TV show
...

#### Actual Behaviour
Video plays on TV, but no audio plays on TV or computer while casting
...

#### Steps to reproduce the behaviour
   

1. ...Turn on TV and allow Chromecast to connect to internet
2. ...Load Popcorn Time and select a TV show
3. ...Select Chromecast and select Watch Now --> video plays on TV, but no audio

**Comment by Persei08** [comment]
Please provide some examples of movies, episodes (with selected quality) you encounter this issue with, so it can be tested and see if it's because audio codec aren't supported by chromecast or something else.

**Comment by zedszanue** [comment]
Using the arm64 version on my galaxy s6 edge, I am able to chromecast both movies and TV shows with sound. However, using the arm 7 version on my galaxy tab S I can only chromecast movies with sound. TV shows like Suits Season 6 Episode "she's gone" for instance only casts video.


Using the most recent chromecast hardware. 




On Thu, Apr 13, 2017 at 8:37 AM -0400, "Persei08" <notifications@github.com> wrote:












Please provide some examples of movies, episodes (with selected quality) you encounter this issue with, so it can be tested and see if it's because audio codec aren't supported by chromecast or something else.

**Comment by zedszanue** [comment]
Just tried today using Windows 10 desktop - Bates Motel series (specifically tried Season 5 episode 1)
