### ISSUE TITLE
Mac version is supposed to run on OSX 10.7 and above - but it doesnt run on my OSX 10.8.5

### ISSUE THREAD

**Issue by curiousguy2017** [popcorntime/popcorntime#526]
Operating System Version:
OS X 10.8.5

Popcorn Time Version:
0.3.10 (downloaded from https://popcorntime.sh/)

Download date:
10.april 2017

#### Expected Behaviour
Launch on OSX 10.8.5 since all websites (including https://popcorntime.sh/ list minimum OSX version as 10.7 and up

#### Actual Behaviour
The app has large X over its icon and when started displayes error: "You have OS X 10.8.5. The application requires OS X 10.9 or later."

#### Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found?

1. donwload from official site https://popcorntime.sh/
2. try to run on OSX 10.8.5 or supposedly anything bellow 10.9 according to error message

either the minimum requierements stated on all official materials "OSX 10.7 and up" is not correct or there is some issue manifesting on my Mac that might be bothering other mac users too...

please help
thank you

**Comment by benjavalero** [comment]
Reproduced with good old Lion 10.7.5

**Comment by streger** [comment]
Will test this tomorrow on 10.12, but if it ends with that it's not supported on your systems please don't get mad ;)

**Comment by losh11** [comment]
Looks like Minimum OS version has been bumped to macOS 10.9. See info.plist:

```
<key>LSMinimumSystemVersion</key>
<string>10.9.0</string>
```
