### ISSUE TITLE
Greek Subtitles are not syncronized

### ISSUE THREAD

**Issue by wikedismassive** [popcorntime/popcorntime#529]
Operating System Version:
Windows 10 Ultimate

Popcorn Time Version:
0.3.10

Download date:
16/4/2017

#### Expected Behaviour
Playing Greek Subtitle Normal

#### Actual Behaviour
In mostly all Movies and Series the Greek Subtitles are not syncronized and when i switch to English subs they play normaly. There was a Subtitle delay button on previous version, but not in this..

#### Steps to reproduce the behaviour
1. Sync Greek Subs
2. Restore Subtitle Delay button

**Comment by streger** [comment]
Try with G and H on your keyboard.
That feature exists you now(syncing subs)...but if still you have problems report them to greek subtitles providers on opensubtitles.org.
