### ISSUE TITLE
Doesn't work for Ubuntu 15.10

### ISSUE THREAD

**Issue by wellyal** [popcorntime/popcorntime#53]
It doesn't execut at all with the last version of ubuntu desktop.

**Comment by team-pct** [comment]
can you sh make_popcorn.sh ?

**Comment by wellyal** [comment]
sh: 0: Can't open make_popcorn.sh

**Comment by VitorVRS** [comment]
It seems like you are on wrong directory or "make_popcorn.sh" doesnt exist.
Can you "ls -l" your dir?

**Comment by wellyal** [comment]
libffmpegsumo.so
nw.pak
Popcorn-Time

**Comment by VitorVRS** [comment]
You don't have Popcorn source code.
You can run "./Popcorn-Time", but i dont recommend because i dont know where did you get this files.

Try  download the last build on CI: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/
