### ISSUE TITLE
Slow downloading/buffering time 

### ISSUE THREAD

**Issue by BestPortal** [popcorntime/popcorntime#530]
Speed test results: 15ms 38.4 mb/s 
torrents (multiple) health: green as an apple.
Downloading/buffering at 20KB/s at max? help please!
using latest popcorn time from the official site

**Comment by DhooreBE** [comment]
Here is a video on how i fixed it. I was used to get around 10 KB/s now i get 15 MB/s
https://www.youtube.com/watch?v=vK6stMlqQGI

**Comment by Persei08** [comment]
@DhooreBE , You don't really fixed it, you 've done it another way by using two other softwares. 
Bittorent is faster because it have DHT enabled. In PT DHT is disabled to avoid leaking real IP address.
