### ISSUE TITLE
Subtitles are not allowed 

### ISSUE THREAD

**Issue by apophis80** [popcorntime/popcorntime#531]
Operating System Version: Windows 10 and Android 5.0

Popcorn Time Version:
Windows: 0.3.10 Beta october , 31, 2016
Android: 2.8.0-76

Download date:
04/20/2017

#### Expected Behaviour
Choose subtitles in the download of the movies files...

#### Actual Behaviour
The subtitles are not allowed in the files archives in both apps (for windows and Android), its show just 2 options to choice: "no subtitles" and "Customized subtitles" and this last one just open an search in the device.
...

#### Steps to reproduce the behaviour

1. choose the movie
2. click subtitles (android)

**Comment by streger** [comment]
You'we probably just loaded the item that actually doesn't have any subtitles available. 

Two options for you:
1. wait
2. download it(or any .srt file) manually and load it or just drop it on-screen (ofc not in android) in desktop.

Please report after you've tried this.

**Comment by artgraves** [comment]
I tried that. A week ago all movies had a list of subtitles. Now, there are none and an orange flag appears when a movie is loaded saying 'no subtitles available'. I have not had this problem before and I often use subtitles.
