### ISSUE TITLE
Popcorn Time Community Edition download and 13 reasons why

### ISSUE THREAD

**Issue by isarns** [popcorntime/popcorntime#532]
Operating System Version:

win 7
Popcorn Time Version:

3.10 beta offical
Download date:

today 22.04.17
#### Expected Behaviour

...
1)Popcorn Time Community Edition windown 3.9 download would work 
2)13 reasons why would show up as it showed up in the old version (or the web version)

#### Actual Behaviour

1)page 404 (the exe seems to have other name / not on the server)
2) 13 reasons why would show up on the new version

#### Steps to reproduce the behaviour

1. try to download Popcorn Time Community Edition windown 3.9
2. search for 13 reasons why

**Comment by epubebooks45** [comment]
<p>Love to read 13 reasons why. Its one of the best science fiction novel I have ever read. it amazing to see these types of works. Its a must read book for you from my side. I you dont have access to hard copy you can download the ebook from here: <a href="url"> https://epubebooks.net/13-reasons-why-epub-review/ </a></p>
