### ISSUE TITLE
Custom sub .. Prison brake 2015/2017????

### ISSUE THREAD

**Issue by Xh0st** [popcorntime/popcorntime#534]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
https://www.reddit.com/r/PopCornTime/comments/6bkts6/prison_break_no_subtitles/
