### ISSUE TITLE
Title bar/time bar not hiding on fullscreen

### ISSUE THREAD

**Issue by Thibaultfq** [popcorntime/popcorntime#535]
**Operating System Version:**

Windows 8.1

**Popcorn Time Version:**

3.10 beta official

**Download date:**

Reinstalled 25/04/17

#### Expected Behaviour

It should hide the extra information panels in fullscreen. (title bar, pause button, progress bar, subtitle button.....). It should also hide the mouse pointer

#### Actual Behaviour

It keep it active, as well as my mouse pointer. It seems to think that my mouse is constantly active which is not the case (i disabled it on my notebook and it kept doing the same). Not sure if it's down to OS-level or something with butter.

#### Steps to reproduce the behaviour

1. Start any movie/serie and enter fullscreen in every possible way (double click, f-key, button)

**Comment by streger** [comment]
It seems that this issue is raised multiple times. Try to check your system for all kinds of malware with all the free (and paid) apps.

This doesn't happen on any of 3 OS's that were using, so be thorough with the examination of your system.

**Comment by Draxler** [comment]
@Thibaultfq
Maybe you could press key F12 when this issue occur, to open app console which could pointed out issue and then posted this screenshot of your app console here. I'm sure some nice dev here :) could look at this console and maybe found where is the issue and tell you what to do if it's on your end.. 
Regards

**Comment by pardinn** [comment]
Hello... since no one added the log and the issue is still happening, I'm adding mine. Hope it helps.  

[popcorntime_issue.txt](https://github.com/popcorn-official/popcorn-desktop/files/1254792/popcorntime_issue.txt)

**Comment by pardinn** [comment]
I'm still facing the problem.... Is there anybody looking into this issue?

**Comment by marcelpaulo** [comment]
I'm running **0.3.10-0 Beta** on **Xubuntu 17.10** and I'm having the same issue.

**Comment by Thibaultfq** [comment]
@pardinn me too (though now on win 10) but i found a quick fix that seems to work: put your cursor at the top edge of the screen, right in the middle. Make sure you're not hovering the title or the text on the right top corner of the videoplayer. When i do this it hides everything except my cursor. 
Better than nothing i guess...

**Comment by GameBurrow** [comment]
Have it happening a lot of times also. The temporary fix @Thibaultfq posted does work though.

**Comment by tomcornall** [comment]
Similar issue when changing displays on **Mac** reproduces this issue.

### Steps:

1. Start on laptop screen (mac mini 900p in my case), open popcorn time
2. Plug in monitor display (1080p in my case)
3. Play Popcorn Time full screen

Now the menus will not hide after leaving the cursor still.

### Workaround

Quit Popcorn Time, and re-open **after** plugging in monitor 👍

**Comment by nickjackoo45** [comment]
Jawaharlal Nehru Technological University, Kakinada is a public university, in Kakinada, East Godavari district, north of the Indian state of Andhra Pradesh. It is one of India's leading universities focusing on engineering
<a href='http://jntutalk.com/'>JNTUA 4-2 Results</a>
<a href='http://jntutalk.com/'>JNTUK 1-1 Results</a>
<a href='http://jntutalk.com/'>JNTUK 1-2 Results</a>
<a href='http://jntutalk.com/'>JNTUK 2-1 Results</a>

**Comment by Squirenetic** [comment]
Bug still happening on Mac OS Catalina 10.15.6 (19G2021). Also now, subtitles reappear whenever fullscreen is toggled, even when the subtitle icon says no subtitles, and have to be manually turned off

**Comment by kiriles90** [comment]
@Squirenetic what version / build are you using? Update to the latest build from ci.popcorntime.app (439 at the moment)
