### ISSUE TITLE
FEATURE REQUEST: URI support

### ISSUE THREAD

**Issue by pranaygp** [popcorntime/popcorntime#536]
## Motivation

I've only recently started to hack with Popcorn Time (currently using the API in two projects) and I noticed that URI support would be really nice (I don't know if this is something that should be brought up in this repo specifically since it seems like it needs to implemented across the API, Desktop and Android clients)

## Proposal

Anywho, the idea would be that, when you query the API, every Movie/Show(/Episode)/Anime(/Episode) endpoint would also provide a URI that may look something like:

`popcorntime://movies/:id` or for a tv show episode `popcorntime://shows/:imdb_id/episodes/:tvdb_id`

At the same time, the android and desktop clients should intercept requests made to these URIs and would have to support opening the respective page (or go straight to a stream if we also embed resolution settings to the URI)

## Why?

This could be really cool for all sorts of integrations. To name a few off the top of my head:

* Listing sites with a "Watch on PopcornTime" button
* Todo list/calendar entry with a link to "watch episode" (one of the projects I have this on, lol)
* Synchronized streaming startups (there are many shows that people across the world watch at the exact same time while talking to each other over IRC/Whatsapp, and I've been part of these groups where we'd all torrent a file and had a script to start playback in VLC at the exact same time)

## "Reach" feature:

URIs also support a timestamp within the video in question. effectively bookmarking a certain part of the video. This could easily help popcorn time in the future with being able to continue playback on a video, smarter background buffering (buffer around the last seen timestamp), and even "continue on other device" which would let you move to your phone from your laptop

## Wrap Up

Obviously, there are a lot of cool things that can be done, and there are other implementations available over supporting URIs, but I think URIs for popcorn time could provide us a "Swiss Army knife" of sorts to tackle all sorts of things in the future (a lot of those other use cases I mentioned are thing I know people would love but are rather huge changes. URI support would be one step in that direction)

**Comment by streger** [comment]
Please take a look at https://github.com/webtorrent/webtorrent-desktop/issues/83
and all the connected issues.

**Comment by bettysteger** [comment]
So it will not be possible, because of the issues?
