### ISSUE TITLE
Can't re-install popcorn time, crash when installing

### ISSUE THREAD

**Issue by vitheca** [popcorntime/popcorntime#538]
Operating System Version:

WINDOWS 10

Popcorn Time Version:

3.10
Download date:

05/08
#### Expected Behaviour

Install normally, like in the first time.

#### Actual Behaviour

After I uninstalled one time, i can't install again anymore.
It crashes when is extracting.

#### Steps to reproduce the behaviour

1. Uninstall.
2. Download 3.10 version again.
3. Try to install.

**Comment by streger** [comment]
What really happens. Some logs please, any kind of error pop-up, warning maybe.
Try to disinfect you computer and try again.
And, ofc please give more details.

**Comment by vitheca** [comment]
Really happen what I said. I have no more details to give. I've got no error pop-up, the installation just stopped and closed. I've found a fix to this, reboot the computer into Secure mode and install it.
