### ISSUE TITLE
[Feature Request] Keep the subtitle configuration for the next episode is possible ?

### ISSUE THREAD

**Issue by vvbv** [popcorntime/popcorntime#539]
In the function "processNext: function () " on "player.js", this function plays the next episode automatically, is possible keep the subtitle configuration for the next episode?

I try make this with my hands, but i get "U need update minimach > 2.0.2".
$npm -v minimach and the response is 3.0.4, i don't know why this no work. 

Operating System Version:
Debian 8

Popcorn Time Version:
0.3.10

Thanks.

**Comment by streger** [comment]
hm...interesting...so you tried to keep the i.e. subtitle timings for next episode in line...good work man...dig deep.
If you need any help with understanding whole thing out, give a shout.
This seems like a cool FR.

**Comment by ChrisAlderson** [comment]
In settings choose the default subtitle.
