### ISSUE TITLE
Cannot play media that is fully cached

### ISSUE THREAD

**Issue by VulcanTourist** [popcorntime/popcorntime#544]
Operating System Version:
Windows 10 r1703

Popcorn Time Version:
0.4.1-5

Download date:
unknown

#### Expected Behaviour
A media was completely streamed while paused (the only practical thing to do when the tyranny of the popularity contest results in too few seeds to actually stream in real-time).  Without viewing the paused media, Popcorn-Time CE was closed.  When Popcorn-Time CE was next started, the media *should* have been immediately viewable since it was fully cached/downloaded, but it was not.
...

#### Actual Behaviour
Popcorn-Time CE acted as if it had never been streamed/downloaded.  I confirmed that the media actually existed in the cache, and in fact **was able to play it** directly from the cache as an MP4 file with another media player.

**Comment by streger** [comment]
This will be closed shortly since you're on the wrong site. If you want to download a free/open-source and security-wise aware Popcorn Time go to popcorntime.sh and try again.

**Comment by VulcanTourist** [comment]
I apologize for my error.  I have now begun using the current release of this code base.  If I see the same behavior reflected in it, I will revise this post if it remains.

**Comment by VulcanTourist** [comment]
I apologize for my error.  I have now begun using the current release of this code base.  If I see the same behavior reflected in it, I will revise this post if it remains.

**Comment by bolshakov** [comment]
@streger could you explain what wrong with reporting issues here? There is a link pointing to this repository in the header of popcorntime.sh.

**Comment by streger** [comment]
@bolshakov He was using totally different PCT, which you can see by his version number.

**Comment by markalfred** [comment]
This is a problem for me in `Version 0.3.10 (0.3.10)`
