### ISSUE TITLE
Cant log in GitLab & Movies have no covers

### ISSUE THREAD

**Issue by lerman01** [popcorntime/popcorntime#545]
Operating System Version: Windows 10
Popcorn Time Version: 0.3.10
Download date: 23.05.17

#### Bugs : 
1. Cant log in to GitLab to report issue
2. Partial movies have no covers

#### Actual Behaviour
1. When trying to log in its just freeze with spinner near the password
screenshot with Console error :
![image](https://cloud.githubusercontent.com/assets/9982172/26342251/f7c6473c-3f9f-11e7-8fa5-fd2e2bb9d494.png)

2. I've checked out and found that your JSON response from MovieApi 
(http://movies-v2.api-fetch.website/movies/1?sort=trending&limit=50&genre=All&order=-1) 
return 'images/posterholder.png' for all images,
screenshot:
![image](https://cloud.githubusercontent.com/assets/9982172/26342500/03dfe8ce-3fa1-11e7-9d90-7033358ba7f6.png)

#### Steps to reproduce the behaviour
1. Just log in to GitLab
2. Just open 'Movies'

**Comment by streger** [comment]
Please install latest version from development releases from ci.popcorntime.sh and try again.

**Comment by lerman01** [comment]
thats what i did from the beginning, but still i tried to completely remove the application and install from ci.popcorntime.sh but the bugs still exists.
about the covers bug, i dont understand how the application related to the empty covers, because its the MovieAPI that return in the response 'empty covers'.

another bug i just pay attention now its the AnimeApi not working at all, im getting HTTP code : 522 for each request, probably something with hummingbird.me server, for example:
https://static.hummingbird.me/anime/poster_images/000/000/115/large/14917l.jpg?1416601498
screenshot: 
![image](https://cloud.githubusercontent.com/assets/9982172/26393234/e397ac42-4071-11e7-9daa-d158fb761514.png)

i think you need to change this API to 'Kitsu API'

**Comment by ChrisAlderson** [comment]
covers is a known issue, and Gitlab should be removed/replaced. Make a seperate issue on the Gitlab error.
