### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by ItachiSan** [popcorntime/popcorntime#548]
Operating System Version:
Linux (ArchLinux, latest packages)

Popcorn Time Version:
Last commit in Git, development branch.

Build date:
Today, 2017/05/27

#### Expected Behaviour
Building the package propely.

#### Actual Behaviour
The build fails for the module `thepiratebay`.

#### Steps to reproduce the behaviour
Build against latest commit in the *development* branch.
You can test the compilation with ArchLinux.

#### Workaround
Install manually first the version *1.4.0* of the module `thepiratebay`.

**Comment by ChrisAlderson** [comment]
Isn't this an issue at `thepriatepay`, not us?

**Comment by ItachiSan** [comment]
Yup, it was. Tried today to update to the latest version and works fine.
