### ISSUE TITLE
Incomplete episode 4 from Season 1 of Hannibal in 480p

### ISSUE THREAD

**Issue by Altward** [popcorntime/popcorntime#550]
Operating System Version:
Windows 10.

Popcorn Time Version:
0.3.10

Download date:
Three weeks ago.

#### Expected Behaviour
I know most people prefer 720p, but for certain reasons I tried to run the 480p version of the episode, expecting a complete one.
...

#### Actual Behaviour
While the subs are synced at least, unlike the 720p version where you have to constantly resync yourself, the 480p only lasts about 21 minutes and cuts out all the family killers part of the episode, like a sort of abridged version.
...

#### Steps to reproduce the behaviour

1. Search for the Hannibal series
2. Select the 4th episode of the 1st season in 480p
3. Select the 4th episode of the 1st season in 720p to compare

**Comment by ChrisAlderson** [comment]
Out of scope.
