### ISSUE TITLE
Doesn't play anything after switcing to 0.3.10

### ISSUE THREAD

**Issue by Kakadu** [popcorntime/popcorntime#551]
I recently upgraded to 0.3.10 from 0.3.9 after the news about subtitle attack but in the new version all movies and shows are not played: everything is stuck after showing "connecting..." label. I checked out terminal output without luck: no errors there and in general 0.3.10 seems to write much less there (or verbose output is disabled by default). I also rolled back to 0.3.9 and everything works fine now. 

Any ideas how to debug this?

P.S. GNU/Linux x64

**Comment by fsacer** [comment]
Same here :(

**Comment by ChrisAlderson** [comment]
Cannot reproduce with the current information.

**Comment by Kakadu** [comment]
@ChrisAlderson can you recommend some debugging techniques? enabling more log, gdb-like stuff, anything?

**Comment by ChrisAlderson** [comment]
F12 key should display the developer tools. Logs and stacks are always welcome.

**Comment by Kakadu** [comment]
This appears after every attempt to watch something

````
app.js:11 [INFO] Closing loading view
app.js:11 [INFO] Streaming cancelled
app.js:11 [INFO] Loading torrent
app.js:21 [ERROR] TypeError: this.nodes.on is not a function
  win.error @ app.js:21
  handleErrors @ streamer.js:89
````

**Comment by ChrisAlderson** [comment]
Seems to be happening something before `app.js:11 [INFO] Closing loading view`.

**Comment by Kakadu** [comment]
But it is not in a log. I closed 'connecting' window, switched to another movie and still got in the 'connecting' window with this log


````
[INFO] Closing loading view
[INFO] Streaming cancelled
[INFO] Loading torrent
[ERROR] TypeError: this.nodes.on is not a function
[INFO] Closing loading view
[INFO] Streaming cancelled
[INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
[INFO] Show movie detail (tt1082807)
[INFO] Subtitles: none
[INFO] Loading torrent
[ERROR] TypeError: this.nodes.on is not a function
````
