### ISSUE TITLE
Popcorn Black Magic

### ISSUE THREAD

**Issue by pralium444** [popcorntime/popcorntime#555]
Operating System Version:

Windows 10 x64 Pro Build 1607 (14393.1198) 16Go RAM I7 4790K GTX960
Popcorn Time Version:

0.3.10-0 HEAD (9e25e9f0)
Download date:

Today

#### Actual Behaviour

Let's do a magic Trick ! 
Open Popcorntime, click on Anime, then click on Indie, Then click again on Anime, Popcorn time is blank ! All Black. Only the Title bar and the window,  everything has disappeared ! Like Magic ;o)
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Magic is a lie.
Also bug already reported #418

**Comment by pralium444** [comment]
glad to contribute ;o)

**Comment by ChrisAlderson** [comment]
Duplicate
