### ISSUE TITLE
AVI files stuttering

### ISSUE THREAD

**Issue by fsacer** [popcorntime/popcorntime#556]
Operating System Version:
Fedora 25 Linux using nouveau/NVIDIA 375.66 drivers

Popcorn Time Version:
0.3.10

Download date:
today

#### Expected Behaviour
avi files would not stutter

#### Actual Behaviour
video played from avi files stutter

#### Steps to reproduce the behaviour
play torrent containing avi video

**Comment by Persei08** [comment]
can't reproduce.

Tested with one movie (avi format), no stutter. (Ubuntu 16.04.2, radeon driver)

Do you have more infos (torrent names?) and also does it also stutter when playing in vlc? What is your OS, which version ? What is your graphic driver?

**Comment by fsacer** [comment]
I updated the info, it happens with any .avi file.

**Comment by Persei08** [comment]
also happens when playing in VLC ? 
also will be appreciate if you provide some torrent names so we can test the same files and not random ones which could have different codecs or parameters.

**Comment by fsacer** [comment]
In VLC file plays normally. This is one example https://thepiratebay.org/torrent/17160984/Big.Little.Lies.S01E01.WEBRip.XviD-FUM[ettv]

**Comment by Persei08** [comment]
Ok better, now I can reproduce the issue.

Here I have screen recorder the issue: https://streamable.com/hv85k
