### ISSUE TITLE
[feature request] Add option for dubbing select

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [popcorntime/popcorntime#557]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.3.10-win64 from Jenkins CI

Download date:
09.06.2017

It would be nice to add an option to select dubbing if multiple audio tracks are available in the movie. Unfortunately, movies in the catalogue are all in English, so people speaking other languages do not have a choice. However, as long as it is possible to open an arbitrary torrent file, it would be nice to have an ability to change the dubbing language. The "bad and ugly" Popcorn Time from popcorn-time.to has this option, but lacks the ability to open arbitrary torrents. So why not to make a "better" version actually the better one.

**Comment by stivens13** [comment]
Would be really helpful, at this point, PT available only for English-speaking population

**Comment by spaceboypsy** [comment]
Yes please! Not only is it a shame that non-English speakers can't enjoy films with audio in their language, it would be really helpful to language learners like me who want to listen in non-English. Hopefully now this has been implemented by popcorntime.to it wouldn't be too hard to implement here?

**Comment by spicajames** [comment]
This will be so Netflix killer feature. So easy but so powerful. Please do this.

**Comment by spaceboypsy** [comment]
Why closed? Because it's being implemented?? :D
