### ISSUE TITLE
House of cards 

### ISSUE THREAD

**Issue by Fialho-** [popcorntime/popcorntime#558]
Operating System Version:

Windows 10

Popcorn Time Version:

3.10

Download date:

November, 1st 2016

#### Expected Behaviour

...
The subtitles, Portuguese-BR, of episodes 1 and 2 of season 1 of House of Cards are desincronized.
I don't know about other episodes of the same season or the others seasons.

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by derinbay** [comment]
This is a subtitle issue, not about pt. I suggest try to sync manually by pressing g or h.

**Comment by Fialho-** [comment]
That worked.

Thanks,
