### ISSUE TITLE
Breaking Bad... :(

### ISSUE THREAD

**Issue by Dennyzinha** [popcorntime/popcorntime#559]
Hi,

The serie Breaking Bad have no image!!!
tks!

Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Dennyzinha** [comment]
Hi,
The serie Breaking Bad have no image!!!
Tks!

**Comment by calandria000** [comment]
Me neither
