### ISSUE TITLE
-I-can-not-install-popcorn-time

### ISSUE THREAD

**Issue by rmm26** [popcorntime/popcorntime#560]
Windows 10

Popcorn Time Version: 3.10

Download date:15/06/17

#### Expected Behaviour
Install the software
...

#### Actual Behaviour
The installer failed to start the component extraction. The error message was that the installer stopped working and that windows was looking for a solution....

#### Steps to reproduce the behaviour
I have already tried to run as administrator on installation.
 I have already manually removed the components that did not disappear in the folders of the program file. 
I already did cleaning (antivirus and such) of the pc.
I always downloaded the installer through popcorntime.sh

**Comment by ChrisAlderson** [comment]
Out of scope.
