### ISSUE TITLE
Seasons and episodes don't show

### ISSUE THREAD

**Issue by EmilyTheChosen** [popcorntime/popcorntime#570]
Operating System Version: Windows 10

Popcorn Time Version: 0.3.10

Download date:

 In the last month  (June)

#### Expected Behaviour 
It was going to show me all seasons

...

#### Actual Behaviour
 It didnt show all of them it showed some

...

#### Steps to reproduce the behaviour 
Just selected a series like South Park or Walking Dead and it didnt show me all of the seasons

1. ...
2. ...
3. ...

**Comment by ruben87** [comment]
Parks and Recreation only shows sound and the image is all black.
