### ISSUE TITLE
Anime covers are not loading

### ISSUE THREAD

**Issue by ProdigyV21** [popcorntime/popcorntime#573]
Operating System Version:

Windows 10
Popcorn Time Version:

3.10
Download date:

10 july 2017

Hi, I am pretty new with popcorntime and my experience so far is great, it has everyting i want to watch (Movies, TV series and Anime) in one place in HD, but there is one problem the anime covers are not loading. I already tried reinstalling popcorntime but it did not work, are there more people having this problem or is it just me? And is there a fix or solution?
Sorry for my bad english :)

**Comment by Majubs** [comment]
I'm having the same issue, and some anime are not loading, don't know if it's related.

The animes that did not work for me were Steins;Gate, Durarara and Bakuman.
When I click watch, the connecting screen shows for a second and than closes.

OS: Linux Mint 18.1
Popcorn Time: 3.10

**Comment by ChrisAlderson** [comment]
Issue with the popcorn-api, move the discussion here: https://github.com/popcorn-official/popcorn-api/issues/83
