### ISSUE TITLE
Fear The Walking Dead - season 3 episode 5 missing

### ISSUE THREAD

**Issue by BrunaBrandao** [popcorntime/popcorntime#574]
Operating System Version:
 Windows 7 professional 32bits

Popcorn Time Version:
 0.3.10 Beta

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Breaking1** [comment]
Just search for it with Torrent collection (The folder next to your favourites) or drag/Drop/copy/paste any magnet/torrent link from your favourite torrent site.
Popcorntime has no control over the content, it just uses different API's to pull content from different providers of torrents and subtitles, so if something is missing it's probably missing where popcorntime pulls content from.

**Comment by BrunaBrandao** [comment]
Thank you Breaking1!!
I appreciate your kindness in replying me :3  I'm a newbie :v
