### ISSUE TITLE
solution for subtitles, change please the source rest api

### ISSUE THREAD

**Issue by skypce** [popcorntime/popcorntime#577]
Operating System Version:

linux
Popcorn Time Version:

latest 
Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

Hi, i was thinkling and i believe that the actual restful api may be can have problems loading subtitles:
Why? ,  Becouse the hash of files may be is different from yts.ag. This is the reason that do not found subtitles and load wrong subtitles i believe , i was tested in few movies with the source changed and works fine.
More reasons: Yts.ag have more people more seeds and leechers, torrent will load more faster.
Credits to this guy that made it possible :https://www.reddit.com/r/PopCornTime/comments/6jzhoa/solved_movie_api_change_to_yts/

**Comment by Persei08** [comment]
PT API use YTS.ag, movies are the same with same number of seeders and leechers. Your arguments are no valid, sorry
