### ISSUE TITLE
Chromecast not appearing

### ISSUE THREAD

**Issue by Birdy978** [popcorntime/popcorntime#579]
Operating System Version:

Windows 10
Popcorn Time Version:

3.10
Download date:

couple of months ago
#### Expected Behaviour

...
Show an option for chromecast, however it only shows the option for Butter.

Steps I have Taken:
1. I have reinstalled twice and that hasn't worked
2. I have chromecast running the whole time, so that is not a solution

Chromecast was working perfectly until today, and now it seems that it doesn't show, even after two reinstalls

**Comment by Persei08** [comment]
Are you using VPN?
Have you tried to restart Chromecast?
Can you cast a youtube video with google chrome, or another app to the chromecast?

**Comment by Birdy978** [comment]
I'm not using a VPN, whilst popcorn time has not been working, all my other forms of chromecast have been

**Comment by ghost** [comment]
Did you tried allowing PopCorn-Time.exe in Windows Firewall?

**Comment by almeidamarcell** [comment]
I have the same problem. Chromecast is working for everything (music, youtube, chrome) but my TV is not appearing on the popcorn time app. I'm on Mac using the latest version.

**Comment by christiandrades** [comment]
Estou com o mesmo problema! Chromecast totalmente funcionando com todos os outros apps, mas com o Popcorn Time 3.10 não dá opção de streamming.


I have the same problem! Chromecast fully working with all other apps, but with Popcorn Time 3.10 gives no streaming option.
