### ISSUE TITLE
Chromecast Subtitles

### ISSUE THREAD

**Issue by RaidForums** [popcorntime/popcorntime#581]
Using Windows 10
Please allow me to cast subtitles to chromecast too, or can someone tell me how I can use popcorn time on my chrome since its basically a chromium extension so I can cast a tab with subtitles since the other option is to cast my whole screen which includes computer sounds.

Is it possible to cast subtitles with other versions like android? I really want this feature.

**Comment by ChrisAlderson** [comment]
Dupe of #196
