### ISSUE TITLE
How do we report bad health torrent links?

### ISSUE THREAD

**Issue by trosel** [popcorntime/popcorntime#583]
How do we report them and how can _I_ help fix them?

**Comment by trosel** [comment]
@ChrisAlderson Is the bad health issue related to the YTS database? If so, I'll take it up with them.

I'm looking for some information on how I can help to improve the selection in the app though. A lot of bad health torrents lately.

**Comment by ChrisAlderson** [comment]
Popcorn Time only uses the torrents from YTS (for movies). It doesn't upload any torrents and there is little to do when the health of a torrent is bad.
