### ISSUE TITLE
fix  arabic translate 

### ISSUE THREAD

**Issue by samarcorn** [popcorntime/popcorntime#585]
Operating System Version:

windows 7
Popcorn Time Version:

Popcorn-Time 0.3.10
Download date:

Tuesday, ‎July ‎25, ‎2017, ‏‎12:55:57 AM
#### Expected Behaviour

...fix the problem(the Arabic translate not according with the actors voices)

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ghost** [comment]
How are we supposed to help you?
