### ISSUE TITLE
Incorrect Search value using JSONRPC api filtersearch

### ISSUE THREAD

**Issue by anikrajc** [popcorntime/popcorntime#587]
Operating System Version:
OS X 10.10.3

Popcorn Time Version:
0.3.10

Download date:
5th August 2017

#### Expected Behaviour
Call to `filtersearch([string term])` should search by string value in term

#### Actual Behaviour
Call results in filling the search bar with `[object Object]`

#### Steps to reproduce the behaviour

1. Get usename and password and ping using the RPC api
2. Run the `filtersearch` method with params `term`
```
POST  HTTP/1.1
Host: 192.168.0.10:8008
Authorization: Basic cG9wY29ybjpwb3Bjb3Ju
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "id": 11,
    "method":"filtersearch",
    "params":[{"term":"cards"}]
}
```
3. Popcorn time shows `[object Object]` in search and no shows found.

![screen shot 2017-08-06 at 5 31 14 am](https://user-images.githubusercontent.com/6180066/28999587-beb3b9da-7a68-11e7-8e3c-ca1d80f1273b.png)

Thanks.

**Comment by ChrisAlderson** [comment]
[That's because you need to pass in a string not an object in the `params` field](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/httpapi.js#L561):

```
{
    "jsonrpc": "2.0",
    "id": 11,
    "method": "filtersearch",
    "params": ["cards"]
}
```

**Comment by anikrajc** [comment]
Thanks
