### ISSUE TITLE
Subtitles doesn't arrive on apple TV or VLC

### ISSUE THREAD

**Issue by tonytozoo** [popcorntime/popcorntime#59]
I've downloaded the software from the official site
I've seen that now subtitles start to work again, and sound come to AppleTV perfectly, but when I try to stream on AppleTV subtitles doesn't come on it.
Even when on VLC the subtitles doesn't come.

I'm Using Mac OS 10.10
AppleTV 2

**Comment by team-pct** [comment]
Hello, Apple TV is not new , we still don't have a reliable solution for subs 
for VLC if you can give us more details it would be great

**Comment by tonytozoo** [comment]
What do u mean for more details? the version of VLC?
Currently i'm running Version 2.2.2

what else can i tell you?

**Comment by Breaking1** [comment]
@tonytozoo try the latest build #52 there subtitles works just fine with VLC.

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

**Comment by tonytozoo** [comment]
Yes, It works on VLC, but not on Apple, i'll keep waiting for it.
I also see that I've lost my bookmarks, but i think i should open another topic, with more specs

**Comment by fawzibr** [comment]
I did a patch for the old popcorntime.io for Airplay subtitles. I changed it for this version and it seems to be working for me. 

[https://drive.google.com/file/d/0B28HxkxF9er_TVh1OG03N1pHZUU/view?usp=sharing](https://drive.google.com/file/d/0B28HxkxF9er_TVh1OG03N1pHZUU/view?usp=sharing)

**Comment by Ahmed707707** [comment]
can you explain more please😬 it's slightly different on mac. the files path is not exactly the same as the note guide says. I got the subtitle setting shown but couldn't get it working on tv.

**Comment by fawzibr** [comment]
I haven't tested it on the Mac just Windows. I think on Mac you have to copy the files inside the Popcorn Time application (the Mac application is actually a packaged file containing a lot of files and directories).

**Comment by tonytozoo** [comment]
I've tried your patch by overwriting the content of the Resources but nothing is changed.

**Comment by cwagner22** [comment]
Any update on a fix for Apple TV subtitles?

**Comment by pablomendoza-wundeman** [comment]
@fawzibr On OSX, I've applied the patch, edited browser.js and downloaded FFMPEG/FFPROBE but when I select Airplay and press Play the PT Console says "No FFMPEG FOUND :(" just before the movie is streaming in AppleTV.

Copied FFMPEG/FFPROBE everywhere inside the .app container and still throws that error.

**Comment by interfaceslivres** [comment]
could not achieve the patch goal.
VLC works fine, but no appearences of subtitles on Apple TV
