### ISSUE TITLE
VLC not showing as a player option

### ISSUE THREAD

**Issue by p-mannn** [popcorntime/popcorntime#590]
Operating System Version:
MAC OS Sierra 10.12.16

Popcorn Time Version:
3.10

Download date:
15 August 2017

#### Expected Behaviour
Works fine except I don't have the option to stream via VLC
...

#### Actual Behaviour
Doesn't give me the option to stream via VLC
...

I used to have a Windows laptop where I could stream via VLC, but I am not getting this option with my MacBook Pro. Any idea why? Is the feature even available? I am still able to stream to my Sony TV like I used to even though I don't have apple tv.

**Comment by p-mannn** [comment]
Solved:

When I installed VLC, I dragged the icon from the drive folder. 

To correct it, I had to drag the icon in to the applications folder and then drag that on to the dock. Now it shows up in popcorn time.

I'm new to MacBooks 😂

**Comment by YavuzSesame** [comment]
found one from google results https://www.winxdvd.com/streaming-video/how-to-play-popcorn-time-on-vlc.htm
Give it a shot!
