### ISSUE TITLE
Search should list exact matches with titles involving non alpha-numeric characters

### ISSUE THREAD

**Issue by checkaayush** [popcorntime/popcorntime#595]
Operating System Version:
Linux

Popcorn Time Version:
0.3.10

Download date:
5 months ago

#### Expected Behaviour
Searching for Grey's anatomy on Series search bar should be successful. Search should include exact matches with case-insensitive media names. 

#### Actual Behaviour
Searching for Grey's anatomy shows no results, but searching for grey results in Grey's anatomy.

**Comment by arshanq** [comment]
@checkaayush  It's showing the correct result on top for the query **grey's anatomy**
