### ISSUE TITLE
kat search and rarbag search in torrent collection not working and synopsis translation issue

### ISSUE THREAD

**Issue by raphcool12** [popcorntime/popcorntime#6]
Hi, I Notice that kat search and rarbg search are not working the circle is turning indifinitly and the synopsis translation are not working too it's only in english and I'm set on french translation

thanks in advance :)

sorry for my bad english :Pp

**Comment by team-pct** [comment]
Corrected,  please use last build on ci.popcorntime.sh

**Comment by raphcool12** [comment]
ok I download the last build and now the result appear but when I click on a torrent file form the list nothing is happen
