### ISSUE TITLE
Settings 'celebrate various events' can't be deselected

### ISSUE THREAD

**Issue by user440** [popcorntime/popcorntime#602]
Operating System Version:
Win7

Popcorn Time Version:
0.3.10 beta build #252

Download date:
today

#### Expected Behaviour
deselect settings "celebrate various events'

#### Actual Behaviour

...

#### Steps to reproduce the behaviour
1. go to settings and try to click on option 'celebrate various events'
2. it can't be deselected and window just jumps down for couple of lines

**Comment by user440** [comment]
To fix this edit "settings-container.tpl" file.

 Find lines:
                <input class="settings-checkbox" name="events" id="cb7" type="checkbox" <%=(Settings.events? "checked='checked'":"")%>>
                <label class="settings-label" for="cb7"><%= i18n.__("Celebrate various events") %></label>

and replace that "cb7" with "cb8". Save and restart.

**Comment by flamber** [comment]
@team-pct This actually overwrote #474 which had already taken `cb8`, so the problem is the same, but just with a different setting conflict now.

**Comment by team-pct** [comment]
fixed cb44e3f
