### ISSUE TITLE
URGENT - pasting magnet link does NOT work correctly

### ISSUE THREAD

**Issue by YIFYtorrents** [popcorntime/popcorntime#61]

**Comment by VitorVRS** [comment]
Actually, the magnet link data is fetched on src/app/lib/providers/torrent_cache.js

It uses peerflix to read the torrent and then save its info on tpmDir (/tmp im my case).
The torrent is saved as "/tmp/md5hash.torrent", this file have all information, including movie/serie name.

You should see how peerflix gets this info, i guess.

**Comment by YIFYtorrents** [comment]
I've placed `console.log('magnet link: '+torrent);` and `$('.file-list').html(torrent);` after this line [src/app/lib/providers/torrent_cache.js#L196](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/torrent_cache.js#L196). The logging seems to work, but it (`$('.file-list').html(torrent);`) doesn't copy the magnet link to [src/app/templates/file-selector.tpl#L6](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/templates/file-selector.tpl#L6)

`src/app/templates/file-selector.tpl` doesn't seem to be loaded yet, when `$('.file-list').html(torrent);` is being executed. That's why `$('.file-list').html(torrent);` is not able to access `src/app/templates/file-selector.tpl`,

There needs to be some other way to get `&dn=MovieNameHERE&`, but this solution is very close.

**Comment by VitorVRS** [comment]
I didn't proposed a solution, i just describe to you what the code does.
If peerflix parse "dn", "tr" and any others variables you should read peerflix documentation and maybe use the same torrent file created on tmp.

It's not very clear what you want to do.

**Comment by YIFYtorrents** [comment]
I need to get the magnet link somehow to file-selector.tpl

**Comment by YIFYtorrents** [comment]
I don't need peerflix to parse "dn", "tr". I can do this with simple javascript, but the problem is how can I actually get the magnet link a the file-selector.tpl

**Comment by VitorVRS** [comment]
The magnet link is not stored as link, you only can get its information by this.model.get('torrent')  (as you said before).

You could implement something to pass the link to the model. 
Sorry if i couldnt help.

**Comment by YIFYtorrents** [comment]
>You could implement something to pass the link to the model. 
Your model idea sounds very good @VitorVRS but `win.debug('torrent: '+torrent);` does not work as well. Could you please have a look at it.

[/src/app/lib/providers/torrent_cache.js#L141-L151](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/torrent_cache.js#L141-L151)
`
        handleSuccess: function (filePath, torrent) {
            win.debug('TorrentCache.handleSuccess() ' + filePath + ' stopped: ' + !stateModel);
	    win.debug('torrent: '+torrent); //my code
            if (!stateModel) {
                return;
            }
            var torrentStart = new Backbone.Model({
                torrent: filePath,
                is_file: true,
		external_url: torrent //my code
            });
            App.vent.trigger('stream:start', torrentStart);
        },
`
This seems to be the line that is pointing to the above function.
https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/torrent_cache.js#L230

PS: I will close the issue when this debug works: `win.debug('torrent: '+torrent); //my code`
