### ISSUE TITLE
Double icon on GNOME dash

### ISSUE THREAD

**Issue by dyskette** [popcorntime/popcorntime#62]
![captura de pantalla](https://cloud.githubusercontent.com/assets/6687927/13496748/8fc16adc-e117-11e5-84a6-5ff4f72c6393.png)

The first icon is from a .desktop file.

```
[Desktop Entry]
Name=Popcorn Time
Comment=Watch Movies and TV Shows instantly
Exec=popcorntime %U
Icon=popcorntime
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
StartupNotify=false
Categories=AudioVideo;Video;Network;Player;P2P;
Type=Application
```

GNOME also shows "unknown" instead of the application name.

![captura de pantalla](https://cloud.githubusercontent.com/assets/6687927/13496875/35c4354a-e118-11e5-805f-739d3a95fad0.png)

**Comment by VitorVRS** [comment]
Aren't you installed PCT before? Its seems like "garbage" from another installation.

**Comment by dyskette** [comment]
No, that is a .desktop file I created in ~/.local/share/applications and the icon is different because is using the one from the icon theme and is executing the binary linked to ~/.local/bin. Opening the application with that launcher is fine, but the issue is that it places another icon in the dash because it doesn't get "linked" with the icon from the launcher. It may be because the application doesn't report a window class or any other form of identification of the window.

There is only this:

```
WM_NAME(UTF8_STRING) = "Butter"
_NET_WM_NAME(UTF8_STRING) = "Butter"
```

But I can't use that on the .desktop file.

**Comment by VitorVRS** [comment]
My PCT is showed as Unkown by Gnome too, maybe you should remove your ~/.local/share/applications PCT entries (or just move to see what happens).

**Comment by dyskette** [comment]
Removing it will certainly result in not having double icon on the dash at the expense of not having a launcher, but that is not the point. This should be fixed in the source code.

**Comment by igorantun** [comment]
I'm having the exact same issue. Does it have any manual fix?
