### ISSUE TITLE
Official version of nwjs prevents streaming 

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#624]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
19/09/17

I did a lot of testing on popcorntime and I realized that the official version of nwjs (from here: https://dl.nwjs.io/ )prevented streaming so I'd like to know why and how I could change it, thank you. 

Screenshot:
![2017-09-22_20-24-26](https://user-images.githubusercontent.com/26660840/30758813-2c04bf94-9fd4-11e7-8d2f-e945dfca052b.png)

**Comment by ChrisAlderson** [comment]
The official version of nwjs doesn't support the video and audio codecs to play the partially downloaded files. This is why we need to compile the codecs ourselfs and include them in the nwjs buidling process. That's why we build with [this repo](https://get.popcorntime.sh/repo/nw/).

**Comment by christianbueno1** [comment]
Hello pals, please share us a link about how use that [nwjs](https://get.popcorntime.sh/repo/nw/v0.20.1/) with popcorn-time or any link that allow us to going in the right direction.
On fedora-28 PCT v0.3.10 doesn't work , only the earlier version 0.3.9 works well.
