### ISSUE TITLE
Add option to view and add torrent sources

### ISSUE THREAD

**Issue by laving1977** [popcorntime/popcorntime#626]
Operating System Version: Windows 10
Popcorn Time Version: 0.3.10-0
Download date: June 2017?

#### Expected Behaviour
What did you think the app was going to do?
There is another Popcorn-time application on the market which offers worse UX BUT has way better selection of movies available.
Somehow they manage to have all new moview way earlier available.
If I could add my own sources, maybe it could help to fix that

#### Actual Behaviour
Not updating the list of available movies too often

#### Steps to reproduce the behaviour
nothing to reproduce.

**Comment by ChrisAlderson** [comment]
You can use the TorrentCollection feature if you want to play content which is not available through Popcorn Time. Or use [`butter-providers`](https://github.com/butterproviders/butter-provider) to add your own sources.
