### ISSUE TITLE
Installer Fails In Linux Mint 18.2 Mate

### ISSUE THREAD

**Issue by veraxy** [popcorntime/popcorntime#627]
Operating System Version:

Linux
Popcorn Time Version:

3.10
Download date:

I didn't that's the issue
#### Expected Behaviour

... Install

#### Actual Behaviour

... give me these error messages
150347 silly postinstall yargs@3.32.0 /home/v/Downloads/popcorn-desktop/node_modules/.staging/yargs-4cab32c0
150348 info lifecycle yargs@3.32.0~postinstall: yargs@3.32.0
150349 silly lifecycle yargs@3.32.0~postinstall: no script for postinstall, continuing
150350 silly postinstall guppy-cli@1.0.1 /home/v/Downloads/popcorn-desktop/node_modules/.staging/guppy-cli-f6bc7a94
150351 info lifecycle guppy-cli@1.0.1~postinstall: guppy-cli@1.0.1
150352 silly lifecycle guppy-cli@1.0.1~postinstall: no script for postinstall, continuing
150353 silly postinstall guppy-pre-commit@0.4.0 /home/v/Downloads/popcorn-desktop/node_modules/.staging/guppy-pre-commit-fcdadf4f
150354 info lifecycle guppy-pre-commit@0.4.0~postinstall: guppy-pre-commit@0.4.0
150355 verbose lifecycle guppy-pre-commit@0.4.0~postinstall: unsafe-perm in lifecycle false
150356 verbose lifecycle guppy-pre-commit@0.4.0~postinstall: PATH: /usr/share/npm/bin/node-gyp-bin:/home/v/Downloads/popcorn-desktop/node_modules/guppy-pre-commit/node_modules/.bin:/home/v/Downloads/popcorn-desktop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
150357 verbose lifecycle guppy-pre-commit@0.4.0~postinstall: CWD: /home/v/Downloads/popcorn-desktop/node_modules/guppy-pre-commit
150358 silly lifecycle guppy-pre-commit@0.4.0~postinstall: Args: [ '-c', 'guppy pre-commit' ]
150359 info lifecycle guppy-pre-commit@0.4.0~postinstall: Failed to exec postinstall script
150360 verbose unlock done using /home/v/.npm/_locks/staging-14338b1facb32c66.lock for /home/v/Downloads/popcorn-desktop/node_modules/.staging
150361 silly rollbackFailedOptional Starting
150362 silly rollbackFailedOptional Finishing
150363 silly runTopLevelLifecycles Starting
150364 silly runTopLevelLifecycles Finishing
150365 silly install printInstalled
150366 warn optional Skipping failed optional dependency /chokidar/fsevents:
150367 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.2
150368 verbose stack Error: guppy-pre-commit@0.4.0 postinstall: `guppy pre-commit`
150368 verbose stack spawn ENOENT
150368 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
150368 verbose stack     at emitTwo (events.js:87:13)
150368 verbose stack     at ChildProcess.emit (events.js:172:7)
150368 verbose stack     at maybeClose (internal/child_process.js:821:16)
150368 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
150369 verbose pkgid guppy-pre-commit@0.4.0
150370 verbose cwd /home/v/Downloads/popcorn-desktop
150371 error Linux 4.8.0-53-generic
150372 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
150373 error node v4.2.6
150374 error npm  v3.5.2
150375 error file sh
150376 error code ELIFECYCLE
150377 error errno ENOENT
150378 error syscall spawn
150379 error guppy-pre-commit@0.4.0 postinstall: `guppy pre-commit`
150379 error spawn ENOENT
150380 error Failed at the guppy-pre-commit@0.4.0 postinstall script 'guppy pre-commit'.
150380 error Make sure you have the latest version of node.js and npm installed.
150380 error If you do, this is most likely a problem with the guppy-pre-commit package,
150380 error not with npm itself.
150380 error Tell the author that this fails on your system:
150380 error     guppy pre-commit
150380 error You can get information on how to open an issue for this project with:
150380 error     npm bugs guppy-pre-commit
150380 error Or if that isn't available, you can get their info via:
150380 error     npm owner ls guppy-pre-commit
150380 error There is likely additional logging output above.
150381 verbose exit [ 1, true ]
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by rcotrina94** [comment]
I think this is related to #507
