### ISSUE TITLE
Better to use MPC for streaming

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#63]
Hello,

It's better to use MPC for streaming because users can tweak quality related settings according to hardware and personal preferences.

Thank you.

**Comment by ghost** [comment]
MPC as in Media Player Classic? PCT currently uses torrent-stream (with peerflix) for streaming torrents which I seriously doubt is gonna change in the foreseeable future. If you mean to have MPC as an option to play torrents to like with VLC, I guess that's possible then.

**Comment by ChrisAlderson** [comment]
You have the option to use an external media player, including MPC, with popcorn time, the option is right next to the play button.
