### ISSUE TITLE
anime covers not loading need fixed

### ISSUE THREAD

**Issue by vanhelsing2042** [popcorntime/popcorntime#633]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by hvhallmann** [comment]
same here

**Comment by TheProxyRE** [comment]
If someone have time he could port api from this project [KawAnime](https://github.com/Kylart/KawAnime)
it uses [MAL](https://myanimelist.net/) as primary anime info gathering and it works pretty well. Also it have couple good api's other thatn Horrible Subs

**Comment by FoxInFlame** [comment]
It looks like the current backend that Popcorn Time uses provides the cover images from Hummingbird.me.
Hummingbird renamed its services to Kitsu.io, so no wonder the requests are failing.

This should be a fairly quick fix in the code, so please fix it ASAP!

**Comment by rawsp33d** [comment]
https://github.com/popcorn-official/popcorn-api/issues/83 is marked closed, but I still have the issue.

**Comment by locodicegr** [comment]
Please Fix.
