### ISSUE TITLE
[feature request] IINA support

### ISSUE THREAD

**Issue by drummwill** [popcorntime/popcorntime#634]
Operating System Version:
macOS 10.13

Popcorn Time Version:
0.3.10

Download date:
2016 Oct 31

being able to stream to IINA as with VLC

also AirPlay no longer functions because of new iOS 11 authentication.

**Comment by rfigueroa-zz** [comment]
INNA doesn't currently supports a way to be called from the CLI, they are planning on supporting a way to control INNA with the [cli](https://github.com/lhc70000/iina/issues/898) but until the implement that, popcorn can't stream to INNA

**Comment by kjyv** [comment]
They now do. I've added this to ext-player.js and it works fine
         'IINA': {
            type: 'mpv',
            cmd: '/Contents/MacOS/iina-cli',
            subswitch: '--mpv-sub-file=',
            fs: '--mpv-fs'
        },
