### ISSUE TITLE
Bypass censorship with Javascript implementation of the Tor (or Tor like) anonymizer project (The Onion Router)

### ISSUE THREAD

**Issue by YIFYtorrents** [popcorntime/popcorntime#64]
Both APIs, yts.ph and yts.ag are now being blocked by Belgium and the Netherlands.

This project https://github.com/Ayms/node-Tor is very important, but I cannot figure out how to install this nice piece of software. 
The following installation does not work.

```
git clone http://github.com/Ayms/node-Tor.git

cd node-Tor

npm link
```

npm-debug.log

```
0 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'link' ]

2 info using npm@1.4.28

3 info using node@v0.10.37

4 verbose node symlink /usr/bin/node

5 verbose linkPkg /home/user/Desktop/git/node-Tor

6 error Error: EACCES, symlink '/home/user/Desktop/git/node-Tor'

6 error  { [Error: EACCES, symlink '/home/user/Desktop/git/node-Tor']

6 error   errno: 3,

6 error   code: 'EACCES',

6 error   path: '/home/user/Desktop/git/node-Tor' }

7 error Please try running this command again as root/Administrator.

8 error System Linux 3.16.0-62-generic

9 error command "/usr/bin/node" "/usr/bin/npm" "link"

10 error cwd /home/user/Desktop/git/node-Tor

11 error node -v v0.10.37

12 error npm -v 1.4.28

13 error path /home/user/Desktop/git/node-Tor

14 error code EACCES

15 error errno 3

16 error stack Error: EACCES, symlink '/home/user/Desktop/git/node-Tor'

17 verbose exit [ 3, true ]
```

**Comment by z11h** [comment]
interesting, ill look into this and see what i can do!

**Comment by YIFYtorrents** [comment]
@ZakariaRidouh Thank you so much. I've created the same [issue](https://github.com/Ayms/node-Tor/issues/5) last week ago, still I don't know why the npm installation does not work any longer. Could this also be used to change your ip address while downloading. That would be a real REVOLUTION guys, but it actually sounds too good to become reality.

**Comment by VitorVRS** [comment]
This is an awesome change, but will not cause slow downloading?

**Comment by YIFYtorrents** [comment]
forget the downloading with tor because somebody else will get that warning letter (even if you haven't downloaded anything), but it would be really cool to use it for the blocked APIs. I can already see the grinning faces as I don't see any difference between Northkorea and Belgium when it comes to internet censorship.
