### ISSUE TITLE
Unable to stream to smart TV

### ISSUE THREAD

**Issue by p-mannn** [popcorntime/popcorntime#646]
Operating System Version:
MAC OS High Sierra 10.13

Popcorn Time Version:
3.10

Download date:
15 August 2017

#### Expected Behaviour
When selecting my smart TV from the menu in popcorn time, it has previously streamed to the TV

#### Actual Behaviour
I am having trouble streaming to my smart TV. I am using a MacBook Pro, it worked previously but it doesn't anymore but I am still getting the option in popcorn time itself, it is just nothing then happens on the TV. Any ideas? 

Thanks

**Comment by verygod** [comment]
Same issue here. Any news?

**Comment by p-mannn** [comment]
Turns out that my TV doesn't support .mp4 files which most movies were whereas most tv series files are a different format. So it is a compatibility issue for me.
