### ISSUE TITLE
“Popcorn-Time quit unexpectedly.” message when quitting

### ISSUE THREAD

**Issue by Flerex** [popcorntime/popcorntime#647]
**Operating System Version:** OS X 10.13

**Popcorn Time Version:** 0.3.10

**Download date:** 11/11/2017

#### Expected Behaviour
PT should close without showing any error

#### Actual Behaviour
If you exit the app by quitting (`CMD + Q` or PopcornTime menu → “Quit Popcorn Time”) a “Popcorn-Time quit unexpectedly.” error message is shown.

![Error message screenshot](https://user-images.githubusercontent.com/3910120/32240910-f1363ea6-be6e-11e7-8312-08512aacdd82.png)

Notice that this doesn't happen if you clic the red close button on the top left side of the window.

#### Steps to reproduce the behavior

1. Open the app
2. Press CMD + Q

----

I want to say that this problem has happened to me for a long time (it already happened in the El Capitan times). According to Reddit, it seems that I'm not the only one experiencing this.

**Comment by thewoz** [comment]
It its already fixed.
But is not yet released the official version.
You need to download from GitHub a compile it.

https://github.com/popcorn-official/popcorn-desktop/issues/293

**Comment by ChrisAlderson** [comment]
#388
