### ISSUE TITLE
Missing movies on ubuntu

### ISSUE THREAD

**Issue by mssartori** [popcorntime/popcorntime#652]
Operating System Version:
Ubuntu 16.04.3 LTS

Popcorn Time Version:
3.10 64

Download date:
11/05/17 (yesterday)

#### Expected Behaviour
On watch.popcorntime tv, i can see a lot of movies like halloween 4, halloween 5, etc. I was expecting to watch then on the ubuntu app, as the watch.popcorn doesn't work on ubuntu.

#### Actual Behaviour
The ubuntu app doesn't have this and a lot of other movies.

**Comment by ChrisAlderson** [comment]
We have no association with `watch.popcorntime.tv`
