### ISSUE TITLE
"Error loading data, try again later..."

### ISSUE THREAD

**Issue by tonjf** [popcorntime/popcorntime#656]
Operating System Version:
 OS X 10.13

Popcorn Time Version:
 3.10

Download date:
 2016

#### Expected Behaviour
 Show/play movies and series
...

#### Actual Behaviour
 Not showing movies and series, shows only the ones in my favorites and a message "Error loading data, try again later..." comes up when i click any
...

#### Steps to reproduce the behaviour

1. ... Open popcorntime
2. ... Nothing shows, go to favorites
3. ... Click on any title

**Comment by SandroCoutinho** [comment]
I've the same issue on OS X 10.12.6

Sometimes to fix this issue you have to restart the computer due to the program being stuck open without the option to close it (even force closing).
