### ISSUE TITLE
No option for changing quality after hit 'Watch now' button – the VPN suggestion popup does not provide back or close functionality. 

### ISSUE THREAD

**Issue by zilahir** [popcorntime/popcorntime#661]
Operating System Version: OS X 10.12.5 

Download date:
2017.11.14

#### Expected Behaviour
When clicked on a watch now button, on the popup for suggesting VPN, i want to close it and go back to the cover listing pa.ge
...

#### Actual Behaviour

When clicked on a watch now button, on the popup for suggesting VPN, there it's not possible to go back to the cover listing page. Only option is to quite the app and start over, or start the movie then press the 'X'

#### Steps to reproduce the behaviour

1. Open popcorntime
2. Search for a movie
3. Hit watch now button
4. Try to change the quality of the video. You cant! You either have to start watching it, or cmd+q the app and start it over.

**Comment by ChrisAlderson** [comment]
This version does not have a 'popup for suggesting VPN'
