### ISSUE TITLE
MOVIE DOESNT MATCH THE ONE DISPLAYED ON THE LIST

### ISSUE THREAD

**Issue by alfredodiazslp** [popcorntime/popcorntime#665]
THE MOVIE "CARGO" (2017), IS SUPPOSED TO BE ONE ABOUT A DAD TRYING TO GET HIS BABYGIRL TO SAFETY DURING AN INFECTION OUTBRAKE, BUT INSTEAD, IT PLAYS A CARTOON MOVIE CALLED "CAR GO"

**Comment by Wotcheruk** [comment]
Yes noticed the same
