### ISSUE TITLE
Allow to save and restore user data

### ISSUE THREAD

**Issue by beppe9000** [popcorntime/popcorntime#668]
I often move between systems and would like to be able to save and restore user data since i have many copies of the following files so I think the imported data should be added to and not replace the existing data.

- bookmarks.db
- movies.db
- settings.db
- shows.db
- watched.db

Is something like this already implemented? I tried to search for similar issues but nothing showed up.

**Comment by beppe9000** [comment]
Was this clossed because its's implemented?

**Comment by team-pct** [comment]
<img width="371" alt="screen shot 2018-11-24 at 22 12 44" src="https://user-images.githubusercontent.com/17107280/48972986-2980b080-f036-11e8-876b-95e40e879172.png">

**Comment by beppe9000** [comment]
Is the existing database overwritten or merged ? The OP was also about optionally merging from the backup.

**Comment by team-pct** [comment]
probably overwritten ,
you can submit a PR for merging the database we would be happy to look into it

**Comment by beppe9000** [comment]
is it more appropriate to look into this at Butter level ?

**Comment by team-pct** [comment]
You can submit the code here too as we keeping an active version ci.popcorntime.sh
