### ISSUE TITLE
msg:  remote movies api failed to respond

### ISSUE THREAD

**Issue by kimberlytics** [popcorntime/popcorntime#67]
movies not loading

**Comment by raphcool12** [comment]
same thing for me need to be fix

**Comment by BubbyWoodz** [comment]
Same for me, I checked the status and it said it was up and running. By the way love u guys bc I can't pay for Netflix! :)

**Comment by BubbyWoodz** [comment]
Needs to be fixed soon

**Comment by arsenelupinn** [comment]
Same here.

**Comment by team-pct** [comment]
Should be fixed
