### ISSUE TITLE
App not working properly

### ISSUE THREAD

**Issue by themythmaster** [popcorntime/popcorntime#672]
Operating System Version:
 windows 10

Popcorn Time Version:
 version 3.10

Download date:
 do not remember

#### Expected Behaviour
 it was expected to show all the tv shows and movies
...

#### Actual Behaviour
 it just keeps loading and nothing is showing on screen
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
