### ISSUE TITLE
How to report bad quality torrents added ? 

### ISSUE THREAD

**Issue by Dr-Hack** [popcorntime/popcorntime#674]
Operating System Version:
Windows 10

Popcorn Time Version:
5.5.1.2
Download date:
-N/A
#### Expected Behaviour
N/A

Many a times we get 720p and 1080p listed but obviously the movie is not where else to be found but still I am like "lets try it out" and it turns out to be a cam rip (too good to be true)

so how do we report such added movie ?
a user based Quality voting system ? 

thanks

**Comment by ChrisAlderson** [comment]
You're not using this version.
