### ISSUE TITLE
Cloudflare is blocking some IP from accessing PT API

### ISSUE THREAD

**Issue by mbpDeveloper** [popcorntime/popcorntime#676]
Operating System Version:
Windows 10 x64

Popcorn Time Version:
Popcorn Time 3.10

Download date:
1 week ago updated.

#### Expected Behaviour
Working properly before 2-3 weeks ago, if i remember right.

#### Actual Behaviour
Infinite loading bar.

#### Steps to reproduce the behaviour
I had 2 dedicated server and 1 cloud. On all servers, OpenVPN installed. The thing is i'm the one using these vpn's but when i try to open popcorntime website or any of the api's cloudflare validation pops up. I dont understand why that showing. When i disconnect vpn, app works very well.
I pressed F12 on PopcornTime while it tries to load page, and on the console i clicked the api link. 
As you can see on the picture, cloudflare validation still pops up.
I tried to solve this on reddit but didnt find any solution. 
I think problem is cloudflare validation shows up, and the app cant get any data.
Reddit Link: https://www.reddit.com/r/PopCornTime/comments/7h963d/popcorntime_not_working_with_vpn/

Pictures;
![image](https://user-images.githubusercontent.com/34423338/33808287-c2f9616c-ddf4-11e7-966e-e4dd2b91a4a2.png)
![image](https://user-images.githubusercontent.com/34423338/33808289-cc4c9a4a-ddf4-11e7-9d85-58cc9c990526.png)
![image](https://user-images.githubusercontent.com/34423338/33808290-d082a172-ddf4-11e7-977f-b682222c07ee.png)

**Comment by Persei08** [comment]
I think "Cloudflare is blocking some IP from accessing PT API" could be a better title :)

Seem like another user is having this issue too: https://www.reddit.com/r/PopCornTime/comments/7loh66/my_popcorn_time_wont_connect/

I don't know if it could be bypassed or handled in PT. Maybe some Cloudflare Web Application Firewall rules to adjust ?

also @mbpDeveloper  can you check if your vpn ip are in listed in [The project Honeypot](http://www.projecthoneypot.org/search_ip.php) ? (cloudflare use that list)

**Comment by anonymouse1989** [comment]
This is exactly what is happening to me. This happens to all my PT even using ios and tvos version, I think its cloudflare blocking the ip so it cant access PT API. The only difference is that when I use vpn like tunnelbear, it lets me access PT, but when using my home fiber connections it doesnt.

**Comment by Persei08** [comment]
@anonymouse1989, Plz provide more details (from which site have you downloaded PT? PT version number? OS?). 
Also PT team don't provide or support ios or tvos versions, there are lot of PT clones/forks but not all use PT API.

What is happening when you access the PT API from your web browser, is the cloudflare security test showing up?

**edit:** Oops my bad, I guess you are the guy from the reddit post I linked above.

**Comment by anonymouse1989** [comment]
I downloaded fro popcorntime.sh, and I get the same issue started with Cloudflare giving me recaptcha, then when loading PT it gives me infinite loading, same as above. I tried using different connections and they worked fine with PT, i used my other fiber connection and my cellular from my carrier, all worked fine. Only with this current connection that it doesnt connect, all PT fork and non fork version doesnt work. I am also using fork version from kinglilrowrow for ios and tvos.

**Comment by mbpDeveloper** [comment]
@Persei08 Thanks, i changed the title like you said :)
The guy is having same problem as mine i think, thanks to cloudflare.

**Comment by Persei08** [comment]
@mbpDeveloper Thanks, I hope it will help other users to find the issue.

**Comment by Persei08** [comment]
@mbpDeveloper can you try to ask project honeypot to whitelist your VPN Ip, seem like it fixed the issue for @anonymouse1989

**Comment by mbpDeveloper** [comment]
@Persei08 sorry for late answer, but the honeypot thing worked. I whitelisted my ip address, and now i can open the app without problem. Thanks again :)

**Comment by Persei08** [comment]
Great, thanks for the feedback

**Comment by jorgeEF** [comment]
Hello, i'm having this problem too. My ip is already whitelisted on honeypot but I can't access PT API address in the browser without filling the cloudflare captcha, wich obviously PT can't fill by itself so it can't access the API meaning nothing loads on PT. Any workaround?
