### ISSUE TITLE
Watchlist not working

### ISSUE THREAD

**Issue by gabrielbiel7** [popcorntime/popcorntime#683]
Operating System Version:

Windows 10

Popcorn Time Version:

0.3.10

Download date:

3 weeks ago

### My problem:
When I click in a series from watchlist, it gets stuck in the loading circles. I've connected my trakt account and I'm using the last version (3.10) on my Windows 10. I've read this has been an issue from ages ago, can u fix pls? thanks!

![oo](https://user-images.githubusercontent.com/35086390/34547853-3d64dd3e-f0e5-11e7-896f-1c9b0aff3ab0.png)

**Comment by gabrielbiel7** [comment]
why closed? my problem is still not solved and i didn’t get any help. :/

**Comment by ChrisAlderson** [comment]
dupe of #308

**Comment by gabrielbiel7** [comment]
@ChrisAlderson i've already commented there and it didn't help, that's why i posted this issue. :/

**Comment by ChrisAlderson** [comment]
The times of your posting show you opened this issue 5 hours prior to you commeting on #308.

**Comment by gabrielbiel7** [comment]
...

**Comment by vhoyer** [comment]
it's because we use the github issues, not as support tickets, but to track errors, so just one per problem
