### ISSUE TITLE
subtitle issue

### ISSUE THREAD

**Issue by jmmdjr2000** [popcorntime/popcorntime#685]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

... The subtitle apears at the moment the person say something.

#### Actual Behaviour

... the subtitle is apearing before the peson say the santence.

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
You can use the H and the G keys to offset the subtitles.
