### ISSUE TITLE
The App gets frozen in the "loading" state

### ISSUE THREAD

**Issue by adityachandrapv** [popcorntime/popcorntime#686]
Operating System Version: Win 10

Popcorn Time Version: 3.10

Download date: Jan 8th, 2018

#### Expected Behaviour
Expecting App to show-up the list of movies when opened, in their traditional thumb-nail mode.

#### Actual Behaviour
App doesn't even get loaded, gets stuck, no movies shown at all.

#### Steps to reproduce the behaviour
Just open popcorn time

![image](https://user-images.githubusercontent.com/35212848/34660365-c460a7a2-f467-11e7-9ab6-d5f9f67dde80.png)

**Comment by Persei08** [comment]
Sound like your ISP is blocking the API domain (court order).

Try to use other DNS, if it don't solve the issue, try with a reliable (not a free one) VPN.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
