### ISSUE TITLE
mobile-armeabi-v7a-release-0.2.9.apk - Green screen and flickering on most movies and series

### ISSUE THREAD

**Issue by hcosteira** [popcorntime/popcorntime#687]
Operating System Version:
MIUI TV (Android) - (https://www.displayspecifications.com/en/model/2b08d11)

Popcorn Time Version:
mobile-armeabi-v7a-release-0.2.9.apk

Download date:
Jan 10, 2018 

#### Expected Behaviour
Load and play the movie correctly 
...

#### Actual Behaviour
as soon as the movie (or series) starts playing the screen goes green and flickers
...

#### Steps to reproduce the behaviour
1. ... Install on mobile-armeabi-v7a-release-0.2.9.apk on a Xiaomi TV 4A 32"
2. ... Open popcorn time and select a movie to watch (i've tried a lot. You can use LOGAN)

Thank you

**Comment by ChrisAlderson** [comment]
This repo is for the desktop application.
