### ISSUE TITLE
subtitle issues on happy death day 

### ISSUE THREAD

**Issue by ccollante** [popcorntime/popcorntime#688]
Operating System Version:  Windows 10

Popcorn Time Version:
dont know

Download date:
dont know

#### Expected Behaviour
play the movie happy death day with spanish subtitles 

#### Actual Behaviour
it does play the movie with spanish subtitles but the subtitles are not synchronized with the movie and are greatly delayed. 

#### Steps to reproduce the behaviour

1. play happy death day with spanish subtitles

**Comment by ChrisAlderson** [comment]
Use the g and h keys to offset the subtitle delay.

**Comment by ChrisAlderson** [comment]
Use the g and h keys to offset the subtitle delay.
