### ISSUE TITLE
No subtitle to choose

### ISSUE THREAD

**Issue by arsenelupinn** [popcorntime/popcorntime#69]
I'm using the last version of .sh (3.9) on W10.
No matter what show/anime/movie I pick there are no subtitles to choose on the player window (even english subtitles). When I try to put a custom subtitle, or it doesn't work or it shows weird symbols instead of some words (ex: fianc£e instead of fiancée). Any thoughts?

P.S.: Also I can't connect the opensubtitle account on conf.

**Comment by arsenelupinn** [comment]
Also I can't connect the opensubtitle account on conf.

**Comment by Breaking1** [comment]
Try the latest build from here and see if it works:

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/
