### ISSUE TITLE
Unable to Run/Install popcorn on Linux ... downloaded from ... 'popcorn-time.to'

### ISSUE THREAD

**Issue by aiamuzz** [popcorntime/popcorntime#690]
#### Operating System Version:

Running Linux (Deepin OS)

#### Popcorn Time Version:

Version 5.6.1 for Linux 64bit !!! ... downloaded from [HERE](https://popcorn-time.to/linux64.html) ...

#### Download date:

trying to install ... from quite a few days ... including today ...

#### Expected Behaviour

... expected it to install !!!

#### Actual Behaviour

... ... double clicking on the popcorn executable has no effect, an attempt to run it from the terminal with the command '`./Popcorn-Time`' gives the following error ...

`./Popcorn-Time: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
`
#### Steps to reproduce the behaviour

Download and Install the linux version from the above url ... and it fails to install !!!

#### appreciate help to install/run this program on my Linux machine ?

thanks.

**Comment by aiamuzz** [comment]
the downloaded archive for linux has the following 3 files and the popcorn executable just does not run or install from the terminal as well as from the file manager ...

![unnamed](https://user-images.githubusercontent.com/3283676/34989447-8f3a9c2c-fae8-11e7-83b3-3dd3362dfc10.png)

**Comment by ChrisAlderson** [comment]
This is the repo of the [popcorntime.sh](https://popcorntime.sh/) branch, not the .to branch.

**Comment by aiamuzz** [comment]
oh ... i did have a doubt about that !!!
thanks ...

ok ... what about the ['Popcorn-Time'](https://play.google.com/store/apps/details?id=com.popfreetime.roid&hl=en) android app ... is that part of this repository ?

thanks ...

**Comment by aiamuzz** [comment]
the reason why i ask is because ... i have one version of popcorn-time already installed and running(the version from my Linux distro's repositories using the command `'sudo apt-get install popcorn-time'`) on the same machine i have described in the opening post ... and then a while ago i went ahead and installed the android version of popcorn available from the android playstore.

I found that the android version had a lot more of the movies that i couldn't find in the desktop version i installed from my linux distro's repository ... 

I would surely like to have the same movies i can find on the Android version on my desktop version as well.

so well i guess that's been my quest and hope of raising this issue here in the issue tracker !!!

**Comment by Persei08** [comment]
Popcorntime.sh android github repo : https://github.com/popcorn-official/popcorn-android
