### ISSUE TITLE
Torrents of a collection that has many files has match problem on playback (macOS)

### ISSUE THREAD

**Issue by carloscarvallo** [popcorntime/popcorntime#693]
Operating System Version:
```
macOS High Sierra
10.13.2 (17C205)
OS X 10.13.2 (I think)
```
Popcorn Time Version:
```
Popcorn-Time-0.3.1.0
```
Nodejs version:
```
$ node -v
v8.2.1
```
Download date:
```
August, 17
```
#### Expected Behaviour
Download a torrent file, drop in, select the episode that you want yo see and OK
#### Actual Behaviour
When I download a torrent that has many files (think of a series torrent), and then you drop on popcorn, the episode that you choose (click) doesn't match with the selected 
#### Steps to reproduce the behaviour
Download a torrent file that has several files (some series for example) select the episode that you want to see and then you will see that play other file (or other episode) of the torrent but not the one that you choose

**Comment by Persei08** [comment]
Does it happen everytimes, even after restarting PT ?

**Comment by carloscarvallo** [comment]
yes
