### ISSUE TITLE
.onion or .i2p site if you don't want to add proxy support at all to the application for browsing.

### ISSUE THREAD

**Issue by Sanyy** [popcorntime/popcorntime#694]
- Would it not be more useful to add a (Secure)website also (for people who live in the 21st century) next to the desktop application (which is still good for grampa)?

- Even just opening/browsing your application triggers an alarm at some ISPs.

- Every platform supports Tor & I2P.

**Do you care the privacy of your users?** 

(_Don't send your 'then bhy a weepeeN' trolls_ at me please. I am not against your advertised service. I admit that a good VPN is still needed. thanks)

**Comment by Persei08** [comment]
I don't understand?  
Can you explain the difference between opening a .onion url and https://popcorntime.sh in Tor Browser. 
 
What more ISP will not see?

edit: Maybe you want the APIs to have .onion urls to bypass ISP blocking?

**Comment by Sanyy** [comment]
> want the APIs to have .onion urls to bypass ISP blocking?

no, i think that would be a lot of work, simpler to put a proxy option in them or to bind its port to use Tor (ex:127.0.0.1:9050) for browsing in it.

Can i specify the port of the application? I don't like to be connected constantly to a VPN and tunneling everything through it just because of an application.

> in Tor Browser

**If they block popcortine.sh (with the help of google)** as thepiratebay **the tor browser will not be able to help you.**
