### ISSUE TITLE
series' episodes missing

### ISSUE THREAD

**Issue by gabrielbiel7** [popcorntime/popcorntime#695]
Operating System Version:

Windows 10

Popcorn Time Version:

3.1.0

Download date:

Last year

#### Please add episodes 12 and 13 of The Gifted, and seasons 3 and 4 for Black Mirror. If you don't add episodes, please send me the site and i will ask them if they can add those episodes. thanks

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
