### ISSUE TITLE
Error while 'gulp run' (libnode.so not found)

### ISSUE THREAD

**Issue by Gerben-Tx** [popcorntime/popcorntime#696]
Operating System Version:
Linux

Popcorn Time Version:
0.3.10

Download date:
03-02-2018

#### Expected Behaviour
Start popcorn time that was build from source

#### Actual Behaviour
error:
```
Running linux64 from cache
[5857:5857:0203/175950:FATAL:nw_content_renderer_hooks.cc(48)] Failed to load node library (error: libnode.so: cannot open shared object file: No such file or directory)
```

#### Steps to reproduce the behaviour
1. Clone repo
2. Run `sudo npm install`
3. Run `sudo gulp build`
4. Run `sudo gulp run`

**Comment by Gerben-Tx** [comment]
libnode.so exists, but i'm not sure if it is in the right location
Result from `sudo find ./ | grep libnode.so`

```
./build/Popcorn-Time/linux64/lib/libnode.so
./cache/0.18.6-sdk/linux64/lib/libnode.so
```

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
