### ISSUE TITLE
Casting to Chromecast with no audio

### ISSUE THREAD

**Issue by achilescamilo** [popcorntime/popcorntime#697]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10, build #256

Download date:
05/02

#### Expected Behaviour
Cast to Chromecast with image, audio and subtitle.
...

#### Actual Behaviour
Casting only image and sometimes the subtitle, but with no audio...
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
#525 #491 #262 #155

> 1. [Use the GitHub issue search — check if the issue has already been reported.](https://github.com/popcorn-official/popcorn-desktop/blob/development/CONTRIBUTING.md#bug-reports)
