### ISSUE TITLE
How can I add subtitles to a series or movie?

### ISSUE THREAD

**Issue by Zal575** [popcorntime/popcorntime#698]
Operating System Version:
 Windows 10

Popcorn Time Version:
 Beta 5.6.1

Download date:
 2.8.18

#### Expected Behaviour
 Let me add subtitles just like the app netflix
...

#### Actual Behaviour
 opens a folder an that it, what can I do next?
...

#### Steps to reproduce the behaviour
 Its not a bug I think so.

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
This is the repo of the popcorntime.sh branch, not the .to branch.
