### ISSUE TITLE
LEGENDAS NÃO TEM SINCRONISMO.

### ISSUE THREAD

**Issue by Paulinho2018PA** [popcorntime/popcorntime#699]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Paulinho2018PA** [comment]
EPISÓDIOS NÃO SEGUE UMA TRADUÇÃO!

**Comment by Sinara-Dias** [comment]
The film The Foreing with the actor Jackie Chen, the subtitles have no synchronism with the film. I was very frustrated. Because the movie sounds good to me. But it is impossible to understand.


Att.,
Sinara#

**Comment by Sinara-Dias** [comment]
The film The Foreing with the actor Jackie Chen, the subtitles have no synchronism with the film. I was very frustrated. Because the movie sounds good to me. But it is impossible to understand.
