### ISSUE TITLE
nwjs helper using almost 100% CPU on OSX

### ISSUE THREAD

**Issue by kessiler** [popcorntime/popcorntime#70]
<img width="659" alt="screen shot 2016-03-07 at 2 30 56 am" src="https://cloud.githubusercontent.com/assets/4087757/13564117/d6fb79e0-e40c-11e5-9b06-2eb722da2adf.png">

I'm using the last version of .sh (3.9).

**Comment by ChrisAlderson** [comment]
This issue should be fixed with #223
