### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bugz8unny69** [popcorntime/popcorntime#705]
There have minor commits lately, is this project still being actively develop? I took a looked a butterproject as well but there isn't seem to be any activity there as well?

**Comment by bugz8unny69** [comment]
I am guessing the Answer is no?

**Comment by HLFH** [comment]
@lhorace `webtorrent-desktop` is more modern. https://github.com/webtorrent/webtorrent-desktop
And you [have recent releases](https://github.com/webtorrent/webtorrent-desktop/releases).
