### ISSUE TITLE
Popcorn-Time not logging into Trakt TV

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#708]
Operating System Version:
Windows 7 64 bit Ultimate

Popcorn Time Version:
3.10

Download date:
02/03/2018

#### Expected Behaviour
Connect to and sync my Trakt TV account

#### Actual Behaviour
After logging in and clicking allow access to my Trakt TV account the window closes and doesn't connect my account. Can click the login button again and re-allow my account and get same out come

#### Steps to reproduce the behaviour

1. Start Popcorn Time
2. Go to Settings
3. Click Connect to Trakt TV
4. Login & Allow account
5. Wonder why nothing happened ;) (But seriously why does this happen)

![Preview GIF](https://i.imgur.com/Dxu4Pae.gif "Preview GIF")

**Comment by ljohnso16** [comment]
confirmed

**Comment by Bjoren** [comment]
Yup, I'm having the same issue

**Comment by Persei08** [comment]
Can reproduce with 3.10 beta but not with dev builds 239, 249, 256.
So I think dev builds >239 aren't impacted.
Ubuntu 16.04 64bits.

@ljohnso16 @WARDOGSK93 and @Bjoren , Maybe you should try the last dev build. it's more recent than your version: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

**Comment by ghost** [comment]
Just gave that ago @Persei08 and can confirm that after uninstalling my current version and installing the version you linked, it fixed the issue and now syncs my Trakt TV account

:grinning: thanks a ton @Persei08

**Comment by Persei08** [comment]
Yep, Trakt.tv authentication have changed in later dev builds.

**Comment by Midifreakz** [comment]
Same issue! How do I install these dev builds? I'm on Mac and it seems to struggle with the .tar.xz file

EDIT: "The Unarchiver" did the trick. Issue seems to be fixed in this Dev version

**Comment by SP3C5** [comment]
I am having this issue, The link provided does not seem to be working.

Is there another location I can download it from?

**Comment by CarlosCano93** [comment]
Same here!

**Comment by Persei08** [comment]
@SP3C5 @CarlosCano93 the link should work now: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

**Comment by rpgiacon** [comment]
Not an option. The last dev build (#277) have an even worst bug... the keyboard wont work and the subtitles wont load most the custom subs

**Comment by Persei08** [comment]
This issue is about "Popcorn-Time not logging into Trakt TV" and it's actually working with dev build 277.
Other issues have their own report.

**Comment by SP3C5** [comment]
Needed to reinstall Popcorn and the link is not working again since the update

p.s when will this issue be resolved in the main release?

**Comment by Persei08** [comment]
@SP3C5 dev builds are here: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**Comment by SP3C5** [comment]
There is no Windows installs

**Comment by Persei08** [comment]
Click on "Previous Build" until one appear

**Comment by christian130** [comment]
this https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/279/

**Comment by dannyeuu** [comment]
With Ubuntu 18.04 I am having this problem too.

**Comment by ApexModder** [comment]
Any reason why the `Windows Installer` from [Popcorntime](https://popcorntime.sh/) is outdated? Does the website no longer get updated?

I'm always having to come back to this issue to get link for [CI Build Page](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/) to get a installer that actually installs a working version of the [TraktTV](https://trakt.tv) support

* [Windows Installer Version from Website: *3.10*](https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Setup.exe)
* [Windows Installer Version from CI Build: _[Build \# 279 (Apr 30, 2018 6:30:15 AM)]_ *0.3.10*](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/279/)

[CI Build Page](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/) looks to say its the same version but download from website and [TraktTV](https://trakt.tv) never works, download from [CI Build Page](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/) and [TraktTV](https://trakt.tv) works fine.

**Comment by Ikkegwn** [comment]
@ApexModder i'm confused, what do you have to do? Where and how do you download stuff? What needs to be downloaded?

**Comment by Persei08** [comment]
@ApexModder 
>Any reason why the Windows Installer from Popcorntime is outdated? Does the website no longer get updated?

The website host the beta versions, the versions on CI are dev builds. The dev builds are less tested than beta versions in theory but actually no new beta was released and the dev builds are working a bit better in facts.

**Comment by ApexModder** [comment]
@Ikkegwn - basically downloading windows installer from website always ships with broken Trakt TV support, from CI latest windows installer ships with fixed working Trakt TV support

@Persei08 - Ahh that makes sense, but would've thought that at least some dev would have released a beta version that fixes the Trakt TV in the current versions on the website, especially since the 2 version numbers look almost identical imo (3.10 -> 0.3.10)

Edit: TL;DR if you want to use Popcorn Time on Windows and also have Trakt TV download from [here](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/), dont see a Windows Installer click previous build until one pops up 😉 

Latest build that includes Windows Installer as of posting this is [# 279](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/279)

**Comment by Persei08** [comment]
>@Persei08 - Ahh that makes sense, but would've thought that at least some dev would have released a beta version that fixes the Trakt TV in the current versions on the website, especially since the 2 version numbers look almost identical imo (3.10 -> 0.3.10)

Version number 3.10 don't really exist, it's just a shortcut refering to 0.3.10 in reality. The 3.10 beta version available on main site is in fact the dev build # 200

**Comment by hyperkalade** [comment]
This helped me to fix logging problem, but then other appeared.

It syncs it, but won't load playlist and just stays in loading proccess.
![image](https://user-images.githubusercontent.com/2884098/42342201-20cb845e-809e-11e8-99df-fdbc487ed848.png)
Selecting show from Series or Movies tabs works fine.

**Comment by hungpham2411** [comment]
Ubuntu 18.04 confirmed same issue.

**Comment by eljaunis** [comment]
Confirmed on OS X High SIerra

**Comment by j3rrey** [comment]
Same here, dev build works tho.
Buuut all my previously watched stuff(marked as seen) is not being synced...

**Comment by chriszd** [comment]
I am on Mac and downloading the Popcorn-Time-0.3.10_osx64.tar.xz file from the links in this thread. 

The issue I have is that when opening this file it keeps extracting another compressed file. This keeps on looping for me. 

Can please someone send me the proper file to use on a Mac with the latest build that fixes the trakt.tv connection issue. 

thanks a lot

**Comment by ivanovyordan** [comment]
I'll give it a try.

**Comment by ChristopheChirat** [comment]
I can't connect to Track.tv since my version of popcorntime (Mac Version). 

Any news ?

**Comment by MarcusMonroe** [comment]
Now full working with #363 new player format and trakt.tv working
https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/
(https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/363/)

Great Work

**Comment by ghost** [comment]
cannot download from the ci site, Network error always occur

2019-02-27 20:18:25 (804 KB/s) - Read error at byte 487435/85182356 (The TLS connection was non-properly terminated.). Retrying.

--2019-02-27 20:18:31--  (try: 7)  https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/artifact/build/Popcorn-Time-0.3.10_linux64.tar.xz
Connecting to ci.popcorntime.sh (ci.popcorntime.sh)|104.20.6.128|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 85182356 (81M), 84694921 (81M) remaining [application/x-xz]
Saving to: ‘Popcorn-Time-0.3.10_linux64.tar.xz.2’

Popcorn-Time-0.3.10_linux64.tar.xz.2    0%[                                                                        ] 555.34K  --.-KB/s    in 0.1s    

2019-02-27 20:18:32 (683 KB/s) - Read error at byte 568664/85182356 (The TLS connection was non-properly terminated.). Retrying.

**Comment by heyitsbea** [comment]
> cannot download from the ci site, Network error always occur

I'm having this issue too

**Comment by allan-andrade** [comment]
> cannot download from the ci site, Network error always occur
> 
> 2019-02-27 20:18:25 (804 KB/s) - Read error at byte 487435/85182356 (The TLS connection was non-properly terminated.). Retrying.
> 
> --2019-02-27 20:18:31-- (try: 7) https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/artifact/build/Popcorn-Time-0.3.10_linux64.tar.xz
> Connecting to ci.popcorntime.sh (ci.popcorntime.sh)|104.20.6.128|:443... connected.
> HTTP request sent, awaiting response... 206 Partial Content
> Length: 85182356 (81M), 84694921 (81M) remaining [application/x-xz]
> Saving to: ‘Popcorn-Time-0.3.10_linux64.tar.xz.2’
> 
> Popcorn-Time-0.3.10_linux64.tar.xz.2 0%[ ] 555.34K --.-KB/s in 0.1s
> 
> 2019-02-27 20:18:32 (683 KB/s) - Read error at byte 568664/85182356 (The TLS connection was non-properly terminated.). Retrying.


Having this same issue too. Actually, tried in all previous builds and just keeps getting this error.

**Comment by juanpsm** [comment]
This fixed it for me https://github.com/popcorn-official/popcorn-desktop/issues/816#issuecomment-416063848
