### ISSUE TITLE
No subs in remote mode with my TV.

### ISSUE THREAD

**Issue by georgr86** [popcorntime/popcorntime#709]
Hello,

I have an issue with the Popcorn Time software. When I send the movie/series to my TV remotely, the subs disappear. I can't have subs at my TV but in Butter mode I can see subs. Is there any software bug with downloading subs to my TV remote projection?

Thanks in advanced!

Operating System Version:
 Windows 7

Popcorn Time Version:
 0.3.10

Download date:
 19/02/2018

#### Expected Behaviour

To project subs with the movie to my TV remotely.
#### Actual Behaviour

No sub in TV remote mode.

**Comment by speedycoyote** [comment]
Hi,
This is happening to me also
And, when I open the movie for the first time, the subtitles open (but only in computer), but if I want to see the movie again, they don't appear anymore.
