### ISSUE TITLE
Where is TorrentCollection repo ? 

### ISSUE THREAD

**Issue by ripper2hl** [popcorntime/popcorntime#714]
I try compile with nodejs 8, but the engine of an dependency cause an problem and i update this dependency(cpasbien-api) and need to update this dependency in TorrentCollection but i cant find the repo 

https://www.npmjs.com/package/TorrentCollection

```
[3/5] Fetching packages...
error cpasbien-api@1.1.1: The engine "node" is incompatible with this module. Expected version "4.2.0".
error An unexpected error occurred: "Found incompatible module".

```

**Comment by Persei08** [comment]
Is working for me (nodejs 8.10.0)

But I also search for TorrentCollection because it use xtorrent dependencie 0.2.2 and it seem it cause a bug in torrentCollection search

**Comment by Persei08** [comment]
I delete my comment, my branch wasn't sync, I will try later

**Comment by ripper2hl** [comment]
mmm okay please, only need update this dependency

**Comment by Persei08** [comment]
oops, I forgot to reply. I haven't seen this error, but I got lot of error messages so I could have missed it. I have rolled back to node 7 actually.

But TorrentCollection package.json doesn't seem to have version restriction for cpasbien-api. Will it not update if yadomi publish 1.1.2 ?

**Comment by ripper2hl** [comment]
TorrentCollection dont have the restriction, the restricion is for cpasbien-api, i update package.json and fixit, but i don know why yadomi doesnt create the tag 1.1.2 :B

https://github.com/yadomi/cpasbien-api/pull/13
