### ISSUE TITLE
[Request] Since this project is almost dead why not concentrate your efforts on another project

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#717]
Helping or fussioning with another project
Ex: https://github.com/bbougot/Popcorn

**Comment by Persei08** [comment]
Why not the contrary ?

**Comment by ghost** [comment]
@Persei08 I don't know, asked another developer (LeonFlix, Benjamin Bougot) to come help you it would be great

**Comment by Persei08** [comment]
Why not, but I'm not a developer of Popcorntime. Just an user :)

**Comment by PatriceVignola** [comment]
Well, it only supports Windows 7 so far, which seems like a bad idea. I guess this is more performant than using a framework like Electron or nwjs, but multiplatform is more important than performance. Am I missing something?

**Comment by sheepdestroyer** [comment]
doesn't it support linux? I unsuccessfully tried to build dev branch on linux for a while now
