### ISSUE TITLE
not loading movie seeds and subtitles

### ISSUE THREAD

**Issue by iMansoorAliKhan** [popcorntime/popcorntime#720]
Operating System Version:

win10

Popcorn Time Version:

recent 
Download date:

3 years or more may be
#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...
All in a sudden, now the new movies dont have seeds, so cant really watch them, whtas going on>?

Also the downloading rate is becoming very slow to non-existing.
Please help

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
