### ISSUE TITLE
Cross don't work

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#722]
Operating System Version:
Windows 10

Popcorn Time Version:
v0.3.10  #262

Download date:
17/03/2018

#### Expected Behaviour
Clicking the cross should normally close the current video and return to the previous menu.

#### Actual Behaviour
Nothing, the video remains open and to return to the menu I must restart the application (ALT+F4) and relaunch it.

#### Steps to reproduce the behaviour

1. Open a movie, a TV show or even a trailer.
2. The cross don't work and you can't go back 
3. Need to force application to stop

**Comment by Persei08** [comment]
Duplicate #713.

Disable "Continue seeding from Tmp Folder" option and restart PT.
