### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#725]
Operating System Version:
      Windows 10 Pro 1709 Build 16299.309

Popcorn Time Version:
      0.3.10 build 277

Download date:
     18/03/2018

#### Expected Behaviour
Esc, Start/Stop, subs sync and volume regulation by keys.
(no command works, these that I have named are those that I consider most important).

#### Actual Behaviour
keyboard commands do not produce effects
Unplug&plug the keyboard doesn't work, neither changing the input method to other language.

#### Steps to reproduce the behaviour
I could not figure out how to reproduce this problem, but it has always been there since I started using popcorn over 1 year ago.

**Comment by Persei08** [comment]
>I could not figure out how to reproduce this problem, but it has always been there since I started using popcorn over 1 year ago.

Does it happen ramdomly or everytime?

**Comment by Leoxur** [comment]
With last build keyboards shortcuts never works, with the build I was using before (just after the subtitle problem: (https://www.google.it/amp/s/www.forbes.com/sites/emmawoollacott/2017/05/25/put-away-the-popcorn-viruses-hidden-in-subtitles-can-let-hackers-take-over-your-device/amp/ ) works most of the time

**Comment by Persei08** [comment]
oh, ok. 
For me (ubuntu 16.04 dev build 277, 266 ), spacebar and esc aren't detected, arrow up and down work, g and h too.

dev build 239 and 257 not impacted for me.

**Comment by danielahmartins** [comment]
Is there any way to fix this? I've just installed 277 to fix the Trakt log in problem, but now, can't use any keyboard shortcuts

**Comment by Leoxur** [comment]
Although I have much esteem for VLC, the popcorn player is (in my opinion) the top of the top, simple and extremely functional (I know that the keyboard shortcuts are the same as vlc, or almost, but I prefer it). I hope we can solve this problem.

**Comment by danielahmartins** [comment]
For me too. The popcorn player is really good, and I only use VLC when absolutely necessary, so I'm looking forward to a solution for this problem. Is there any way to get one of the previous builds, like 239/257 like @Persei08 mentioned?

**Comment by Leoxur** [comment]
https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/ yes you should try to get "previous build" from this page. Theoretically should be available

**Comment by danielahmartins** [comment]
I only have access to #264 or 200. I've tried 264 and it doesn't work (I had 3 problems before updating: 1- Subtitles not working; 2- Trakt log in + Watchlist not loading / The 277 fixed these problems, but now hte shortcuts don't work)

**Comment by Persei08** [comment]
@Leoxur , @danielahmartins . What are your keyboards layouts? mine is azerty

**Comment by Leoxur** [comment]
@Persei08 Mine is qwerty, I also tried to change input language still not working

**Comment by danielahmartins** [comment]
Mine is qwerty too.

**Comment by Leoxur** [comment]
Is this a fix guys? have you been able to understand what it depends on?

**Comment by Shuen-Di** [comment]
my shortcuts started to work after i started the video with VLC and then closed and started with popcorn, seems everything work but Esc.

**Comment by Persei08** [comment]
@Leoxur , Yes, it seem to fix shortcuts issue. Now we have to wait it to be merged and included in next dev build

**Comment by Leoxur** [comment]
Very very happy to hear that ;D

**Comment by Persei08** [comment]
@team-pct dev build 278 have an issue with butter-provider-vodo : https://github.com/popcorn-official/popcorn-desktop/issues/741#issuecomment-379910165
