### ISSUE TITLE
[Request] Update dependencies, devdependencies and Nwjs

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#729]

**Comment by Persei08** [comment]
Nwjs version used in PT is a custom build supporting additional codecs. Don't know who compile it, there was a compile script somewhere on github but it was just for linux IIRC.

**Comment by ghost** [comment]
@Persei08 Do you have the link? I can easily compile the latest version of Nwjs with this script

**Comment by Persei08** [comment]
Was discuted here : butterproject/butter-desktop#647

https://github.com/butterproject/nwjs-build
