### ISSUE TITLE
Updated Build MacOS

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#734]
Would it be possible to get an updated release? The last one was from 2016, and while there have only been minor patches some of them have fixed pretty annoying things, such as the error message that appears at every CMD + Q on mac.

Having trouble setting up the dependencies myself and would appreciate a compiled version.

**Comment by jasondamour** [comment]
+1

**Comment by cmdshft** [comment]
+1, the latest CI build #277 doesn't launch on latest macOS either. Quarantine CL doesn't fix it, either.

**Comment by ChrisAlderson** [comment]
Duplicate of #388
