### ISSUE TITLE
some series from pocorntime from this week you can hear them but the screen is in black

### ISSUE THREAD

**Issue by TBPLAWYER** [popcorntime/popcorntime#735]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Please provide more details.

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
