### ISSUE TITLE
Title of media issues (see the screenshot)

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#739]
Operating System Version:
Windows 10 pro 1709 

Popcorn Time Version:
Build 277

Download date:
18/03/2018
#### Expected Behaviour
Normal tittle
#### Actual Behaviour
Popcorntime+name of the film/series

#### Steps to reproduce the behaviour
Don't know

![image](https://user-images.githubusercontent.com/9626769/38175812-cc179408-35e2-11e8-8ad9-224a5f63edd9.png)

![screenshot 50](https://user-images.githubusercontent.com/9626769/38175819-e40c3cd0-35e2-11e8-88d5-affa4496294c.png)

**Comment by ChrisAlderson** [comment]
Do you know what day it is today?

**Comment by Leoxur** [comment]
Are you saying that it's an easter egg? Loll you are right, didn't think about it, didn't expect ;D
