### ISSUE TITLE
Walking Dead S08E14 Still gotta mean something

### ISSUE THREAD

**Issue by althtnmore** [popcorntime/popcorntime#742]
Walking Dead S08E14 Still Gotta Mean Something
The Video isn't Walking Dead. It is labeled as" Another fake from EZTV.EG Stay away from those shitty sites" and it isn't walking dead. It's some old dude talking in front of a wall.

Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10.0

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Leoxur** [comment]
Yes, i noticed, select the 480p video in the meantime

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
