### ISSUE TITLE
The copy of Molly's Game is bad.  only 12 minutes of the film is working.  Please remove it and add a new version.  

### ISSUE THREAD

**Issue by u2guess** [popcorntime/popcorntime#743]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Movies listed in PT come from YTS.ag

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
