### ISSUE TITLE
Monster Family

### ISSUE THREAD

**Issue by 123Olairy** [popcorntime/popcorntime#744]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by 123Olairy** [comment]
This film only plays in German even though features British actors etc. 
Please can we have a version with English soundtrack
Many thanks

**Comment by ghost** [comment]
This stuff is dealt with by MovieApi not the devs of Popcorn Time.

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
