### ISSUE TITLE
Problem Installing from Source Code

### ISSUE THREAD

**Issue by sheilambadi** [popcorntime/popcorntime#745]
Operating System Version:

Linux Mint

Popcorn Time Version:

3.10

Download date:

06/04/2018. 

#### Expected Behaviour

Load movies and series to watch

#### Actual Behaviour

on executing 'gulp run' program opens but the screen is black, no content can be seen

#### Steps to reproduce the behaviour

1. Follow instructions on installing the program
2. Run 'gulp run' after installing gulp and bower
![popcorntime](https://user-images.githubusercontent.com/25798203/38394738-5868d270-3938-11e8-9b3c-85df03fbbb5a.png)

**Comment by Simon-Davies** [comment]
I am having the same issue installing from source on Fedora-26. I've built Popcorn Time fine in the past.

**Comment by sheilambadi** [comment]
I hope we get a solution soon

**Comment by Persei08** [comment]
Duplicate #741

**Comment by Persei08** [comment]
Quick fix posted in #741

**Comment by sheilambadi** [comment]
Thank you @Persei08. It worked well
