### ISSUE TITLE
Problem Krypton Series S01E03 - is Fake - Porn Gay Video

### ISSUE THREAD

**Issue by leoquinino** [popcorntime/popcorntime#746]
Warning... Atention....

Problem Krypton Series S01E03 - is Fake - Porn Gay Video

Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.
