### ISSUE TITLE
Build from Source broken on Fedora 26

### ISSUE THREAD

**Issue by Simon-Davies** [popcorntime/popcorntime#748]
Operating System Version:

Fedora 26

Popcorn Time Version:

Latest development source

Download date:

08/04/18

#### Expected Behaviour

Builds from source and binary functions

#### Actual Behaviour

Builds from source but binary doesn't work. There is just a black screen like stated in a previous issue.

#### Steps to reproduce the behaviour

1. Build from latest development source on either Fedora 26 of Linux Mint

**Comment by Persei08** [comment]
Duplicate #745, #741

**Comment by Persei08** [comment]
Quick fix posted in #741

**Comment by Simon-Davies** [comment]
@Persei08 The quick fix worked. Thank you.

**Comment by mateushonorato** [comment]
The quick fix worked for me too. Using KDE Neon (based on Ubuntu 16.04). Thank you very much!
