### ISSUE TITLE
Commit breaks hide anime/indie feature

### ISSUE THREAD

**Issue by exadeci** [popcorntime/popcorntime#751]
@team-pct
This commit  https://github.com/popcorn-official/popcorn-desktop/commit/ebfe8e0f645678b3d40ae3fdc8d9cc73f27d98a0#diff-7c4b8ea2f2821d130f9b0b223f68681e
removed the changes in `settings` and `settings-container` made by:
https://github.com/popcorn-official/popcorn-desktop/commit/7d63ada455ac0e803d50a73a2414c8cfdbbe9f97#diff-7c4b8ea2f2821d130f9b0b223f68681e+

And thus breaking the feature, it might have affected other changes.

**Comment by Persei08** [comment]
Submitted PR #461 some time ago, but finally closed it and deleted my branch because I was thinking PT will be based on new butter version.

@Nallat resubmitted it with #726 but the diff is weird (like every lines have changed)
