### ISSUE TITLE
Jessica Jones

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#755]
Operating System Version:

window 10
Popcorn Time Version:

277
Download date:

18/03/2018
#### Expected Behaviour

See the two season and related episodes
#### Actual Behaviour

![image](https://user-images.githubusercontent.com/9626769/38811859-023e87c2-418b-11e8-855f-65b761a25983.png)

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Popcorn Time doesn't host any of the content. The content on Popcorn Time is pulled off third party sources. If you want to watch content which isn't available via Popcorn Time you can use the Torrent Collection feature.

**Comment by aiamuzz** [comment]
is there any way to add the torrent collection manually ?

**Comment by Persei08** [comment]
@aiamuzz not sure what you mean, but you can drag and drop any torrent or magnet link on PT window to download it. 
Torrent Collection is a feature allowing to search online for magnet link (and saving them for later eventually). ![Check this picture to use it](https://user-images.githubusercontent.com/22459458/39400935-2efb37fc-4b3a-11e8-9920-0c30e4950b3c.gif)

**Comment by Leoxur** [comment]
wow! didn't know that function!!

**Comment by Persei08** [comment]
It's actually broken in dev builds but next dev build (>=279) should have it back. Credit to yiannis309 for the fix :)
