### ISSUE TITLE
movies/TV/Anime APIs not showing any results. Only spinning circles even though in the website, all services seem to be working.

### ISSUE THREAD

**Issue by Kosmyn89** [popcorntime/popcorntime#760]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. Open PopcornTime
2. Navigate to Movies/Series/Anime tabs
3. See spinning circles and eventually i see the error shown in the second screenshot (although the status page shows all green)

![image](https://user-images.githubusercontent.com/17832482/38940260-61c1d14c-4332-11e8-8ac6-94294fd8c094.png)
 
![image](https://user-images.githubusercontent.com/17832482/38940342-8cda84dc-4332-11e8-8e57-3daddca36b56.png)

**Comment by eline2244** [comment]
yes me too

**Comment by Kosmyn89** [comment]
for me it's fixed now. I'm closing this.
