### ISSUE TITLE
Strange behavior downloading content

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#764]
Operating System Version:

Popcorn Time Version:

Download date:

#### Actual Behaviour

Even with extremely seeded content, the streaming part but for some strange reason crashes. It happens more and more often.
The download starts at the maximum speed of my network and then drops until it stops on a random value (either high or low) but stops downloading:
![screenshot 52](https://user-images.githubusercontent.com/9626769/39070370-6fc1d988-44e3-11e8-9d46-dbc8f30d8589.png)
![screenshot 53](https://user-images.githubusercontent.com/9626769/39070375-75087ab4-44e3-11e8-8207-e90924a4be3a.png)

#### Steps to reproduce the behaviour

It's random I think, sometimes it works wonders, but more and more often I can not see anything

**Comment by Persei08** [comment]
Just tried on windows 10 + dev build #277 + VLC 3.0.0 + same episode in 720p, cannot reproduce :confused:  

OS version ?
Popcorntime version ? 
VLC version ?
Does it also happen when you play in Butter player ?
Does it happen if you restart PT ?
What is the frequency of that issue? (every 2 / 5 / 10  play?)

**Comment by Leoxur** [comment]
I thought I wrote information, sorry :)
-Os windows 10 
-popcorntime v277 (but it also happened before with the last 0.3.10 stable)
-vlc updated to the latest release happens -Regardless of the unknown 
-frequency player, it may not happen and it can happen continuously

**Comment by ChrisAlderson** [comment]
Cannot reproduce.

**Comment by HannesBBR** [comment]
I experience the same behaviour in build 279.
- OS: Windows 10
- PT.: Build 279
- Latest version of VLC
- Frequency: Everytime

Behaviour:
First it says 'Downloading', then it gets stuck on 'Starting Download'. This happens both when using butter or chromecast. With or without Default subtitle doesn't make a difference. The console log does not show an error.

**Comment by Persei08** [comment]
@HannesBBR if you are stuck on "Connecting", it's not the same issue :/ .
