### ISSUE TITLE
Create a flatpak version of Popcorn on flathub

### ISSUE THREAD

**Issue by LeandroStanger** [popcorntime/popcorntime#769]

**Comment by aiamuzz** [comment]
i second it ... a flatpak version is a must have ... will save a lot of time having to install when migrating/testing other linux distros ... 

In case anybody is wondering what i am talking about ... i have a separate flatpak remote created and mapped to an exclusive partition meant only for flatpak apps ... an install-once-and-forget-about-it ... between OS re-installs and migrations.

**Comment by mrmcq2u** [comment]
was there a reason for closing this?

**Comment by PureTryOut** [comment]
I'm sure lot of people still want this, me included, please re-open this issue.

https://gitlab.com/Preisschild/popcorntime-flatpak can be used as a starting point.

**Comment by faveoled** [comment]
Flathub doesn't want this app in their store:
https://github.com/flathub/flathub/pull/701#issuecomment-435594510
