### ISSUE TITLE
Popcorn doesn't load

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#770]
Operating System Version:
Windows 10

Popcorn Time Version:
build 278

Download date:
26/04/2018 

#### Expected Behaviour
Load the library

#### Actual Behaviour

![image](https://user-images.githubusercontent.com/9626769/39365851-a091cd1c-4a32-11e8-80e6-a1d0777842e9.png)

#### Steps to reproduce the behaviour
I tried installing over 277 and clean install, no way to make it work

**Comment by mezcalbert** [comment]
Same result with Ubuntu Linux 18.04, with a previous version and the latest version just uploaded on 26/04.

**Comment by himanuuu** [comment]
Me sucede el mismo problema :(
