### ISSUE TITLE
failed from building from windows 7

### ISSUE THREAD

**Issue by christian130** [popcorntime/popcorntime#774]
Operating System Version:
windows 7 32 bit

Popcorn Time Version:
@latest

Download date:
april 29th, 2018 at 15:30 (-4 GMT)

#### Expected Behaviour
Generate the binaries...

#### Actual Behaviour
C:/~/popforntime\popcorn-desktop>gulp build
[19:10:02] Using gulpfile ~\popforntime\popcorn-desktop\gulpfile.js
[19:10:02] Starting 'build'...
[19:10:02] Starting 'injectgit'...
Branch: development
Commit: f381d448
[19:10:02] Finished 'injectgit' after 42 ms
[19:10:02] Starting 'css'...
Stylus files compiled in G:\~\popforntime\popcorn-deskt
src\app\themes\
[19:10:04] Finished 'css' after 2.62 s
[19:10:04] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.9.1
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.

npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
[19:10:08] Finished 'nwjs' after 3.5 s
[19:10:08] Finished 'build' after 6.17 s

#### Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found?

1. ...npm install
2. ...bower install
3. ...gulp build
npm version is 
G:\~\popforntime\3>node -v
v8.11.1

G:\~\popforntime\3>npm -v
5.6.0

**Comment by christian130** [comment]
seems to work if the prod flag in the gulpfile is disabled... please go to https://github.com/Persei08/butter-desktop/issues/5

**Comment by Persei08** [comment]
Hi maybe, I've found something for you.

Can you install the latest npm 4 and retry ? (Maybe the windows command is `npm install -g npm@latest-4`)

Please test and tell if it work. Thx

**Comment by christian130** [comment]
ok, I'll do it, but the NPM bundle in windows is distributed with the proper node version...
I think there would be an update in the NPM for this, to go on, if not please tell me your NPM and node version you're building/working with?

**Comment by Persei08** [comment]
I haven't tried on windows, but if you already have npm, it should allow you to install the npm version you want, else try a node version manager (nvm, nodist) to easily switch between node versions and install node 7, it should come with npm 4.6.0 if i remember correctly


My versions:
```
user@host:~ $ node -v
v8.11.1
user@host:~ $ npm -v
4.6.1
```

**Comment by christian130** [comment]
it seems it's working with the 
user@host:~ $ node -v
v8.11.1
and the
user@host:~ $ npm -v
4.6.1
```
C:\Users\user\popforntime>gulp build
[15:10:37] Using gulpfile ~\gulpfile.js
[15:10:37] Starting 'build'...
[15:10:37] Starting 'injectgit'...
Branch: HEAD
Commit: 14160f40
[15:10:37] Finished 'injectgit' after 131 ms
[15:10:37] Starting 'css'...
Stylus files compiled in C:\Users\user\popforntime\src\app\themes\
[15:10:40] Finished 'css' after 3.47 s
[15:10:40] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in C:\Users\user\popforntime\cache\0.18.6-sdk
Using cache for: win32
Create release folder in C:\Users\user\popforntime\build\Popcorn-Time\win32
[15:19:23] Finished 'nwjs' after 8.72 min
[15:19:23] Finished 'build' after 8.77 min
C:\Users\user\popforntime>node -v
v8.11.1
```

**Comment by christian130** [comment]
the issue could be fixed by DOWNGRADING the npm... to the version 4.6.1

Latest NODE LTS Version: 8.11.1 (includes npm 5.6.0)

https://www.google.com/search?q=how+to+downgrade+npm+windows

https://we.tl/uttfaHmSiK

**Comment by Persei08** [comment]
Yeah, "downgrading" if you prefer.

**Comment by christian130** [comment]
@Persei08 i dont know if with this should be fixed, given that the npm is a default maker... unless should be appointing in the README.md file

**Comment by Persei08** [comment]
I don't know, maybe dependencies have to be upgraded to work with npm 5 :/
