### ISSUE TITLE
Sound sync issue as the video is playing

### ISSUE THREAD

**Issue by flooomi** [popcorntime/popcorntime#778]
Operating System Version:

Windows 10

Popcorn Time Version:

0.3.10 "Popcorn is Love" Beta Popcorntime.sh version

Download date:

18/03/2018

#### Expected Behaviour

Read the video normally like it used to do before

#### Actual Behaviour

The video start with the sound synchronized but as the video goes on the sound start to desynchronized a lot (happens on VLC & Butter)
When I play directly on Butter, I need to quit the video and then start it again so the sound is sync again.
On VLC, I don't need to close the video but just to move 2 or 3 seconds before and the sound reajust correctly with the video.

#### Steps to reproduce the behaviour

1. Start a video
2. Wait for a few minutes (really depends on the mood of popcorn time ^^)
3. Then the sound desync and is not playing at the right time

I tried to reinstall popcorntime (on the 18/03/2018) but didn't change, the problem was still here

PS: I could read on other post that I'm not the only one wth this issue but their post have been archived without a solution... So please I'm counting on you !! 😄

**Comment by Logerfo** [comment]
Same problem here.

**Comment by Persei08** [comment]
>the sound start to desynchronized a lot (happens on VLC & Butter)

if it happens on VLC too, maybe it's more something with the video, the system or ffmpeg eventually

**Comment by Logerfo** [comment]
@Persei08 probably not the video, since this happens to me with everything i watch through popcorntime

**Comment by Persei08** [comment]
@Logerfo and with VLC too ?

**Comment by Logerfo** [comment]
@Persei08 yes. and exactly as the OP described, with VLC i can fix without closing the player.

**Comment by Persei08** [comment]
What if you play in VLC the video file directly from the download/cache folder? Does it desync too?

**Comment by Logerfo** [comment]
I'll have to test that later

**Comment by Logerfo** [comment]
Yes, it desync too. I guess the problem is not with popcorntime, the file or the player then.

**Comment by Persei08** [comment]
@Logerfo , maybe look at your graphic or audio hardware settings. Sometimes some settings could add a postprocess treatment on video or audio and potentially generate a desync.

**Comment by Logerfo** [comment]
I managed to mitigate the problem by lowering the sound quality on my hardware settings, but I found a complete solution by changing my windows power settings to best performance instead of balanced (not sure if that's how they're called in english)

**Comment by Will-I-am-not** [comment]
I have the same problem every time I playback series or a movie.  My Windows 10 PC is hooked to an A/V receiver and I usually use the by-pass mode to avoid using the whole 5.1 channels, but rather the TV speakers.  The problem is that neither the TV, nor the receiver have negative values for lip sync or audio delay.  That would be a nice feature to add in order to correct the issue.

**Comment by Persei08** [comment]
@Will-I-am-not You can always open a feature request for adding a feature to offset audio. But for the moment I suggest you to look at your sounds settings and see if it can improve things.
