### ISSUE TITLE
Impossible to connect to trakt.tv

### ISSUE THREAD

**Issue by oxydeon** [popcorntime/popcorntime#779]
Operating System Version:
OS X 10.11, Windows 10

Popcorn Time Version:
0.3.10 

Download date:
Less than 2 month, march 2018

#### Expected Behaviour
Connect to Track.tv

#### Actual Behaviour
Impossible to connect to trakt.tv

#### Steps to reproduce the behaviour
1. Go to settings

2. Connect to Trakt
..popup of connexion
..token receive in popup

3. Nothing append

**Comment by Persei08** [comment]
Should work with development branch, try the [last successful dev build (\#279 at this moment)](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/)
