### ISSUE TITLE
Missing download speed throttle like any other bittorrent client includes

### ISSUE THREAD

**Issue by notmutiny** [popcorntime/popcorntime#783]
Operating System Version:
All

Popcorn Time Version:
All

Download date:
n/a

#### Expected Behaviour
Download speed -> limit -> e.g. 500kbps

#### Actual Behaviour
Start torrent -> popcorntime takes over my bandwidth -> rest of network cannot use internet because popcorntime is downloading at maximum capacity

#### Steps to reproduce the behaviour
1. use popcorntime
2. start streaming

**Comment by Persei08** [comment]
Duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/400
