### ISSUE TITLE
Open with VLC option is not present

### ISSUE THREAD

**Issue by githubtefo** [popcorntime/popcorntime#784]
Operating System Version:
Ubuntu 18.04

Popcorn Time Version:
Last build from popcorntime.sh at 05/12/18. VLC 3.0.1

Download date:
05/12/18

#### Expected Behaviour
When I open a .torrent or magnet:, I expect that the option for opening it with VLC is present.

#### Actual Behaviour
Only the Butter option appears in the list.

**Comment by githubtefo** [comment]
Solved: I should install vlc under apt-get and not using snap packages.

**Comment by Persei08** [comment]
Should work in dev builds > 247 (If i remember correctly). 
![screenshot from 2018-05-13 12-38-05](https://user-images.githubusercontent.com/22459458/39966339-94c0b38e-56aa-11e8-930c-283b01880330.png)


You should probably try the last dev build if you want the last fixs (and bugs): https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

You will need to remove vlc apt version and/or reinstall vlc snap version else it will detect both but use the most recently installed.
