### ISSUE TITLE
Freeze after a few seconds under Manjaro/Arch Linux

### ISSUE THREAD

**Issue by klorydryk** [popcorntime/popcorntime#786]
Operating System Version:
Manjaro, kernel 4.14.39-1
Cinnamon 3.8.2
Intel i7-6700
NVidia GTX980

Popcorn Time Version: 0.3.10-3 installed with the official Manjaro repository.

#### Actual Behaviour
The application freezes after 10-12 seconds, whatever the page I'm on. Then need to be killed.

#### Steps to reproduce the behaviour
Just start the application, go on whatever page you want. After a few seconds, the application does not respond anymore.

Launched with the terminal, I get this errors:

> [6913:6913:0514/200245:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x557218589860]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
> [6913:6913:0514/200245:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x557218589860]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
> [6913:6913:0514/200246:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x557218589860]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
> [6913:6913:0514/200246:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x557218589860]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
> [6913:6913:0514/200246:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
> [6913:6913:0514/200246:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
>

**Comment by raphaelbernardino** [comment]
Duplicate #780

**Comment by Persei08** [comment]
gles2_cmd_decoder.cc is OpenGL ES component.
Maybe it's related to hardware acceleration.

I think a workaround could be to start PT with `--disable-gpu` argument but it will run slightly slower

**Comment by klorydryk** [comment]
@raphaelbernardino Ok, I don't have the same error now as the first time, and I get now the same error as #780 

@Persei08 with the option `--disable-gpu` I still get the same error as #780 
And logs.txt contains:

> Error: listen EADDRINUSE :::8008
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Object.listen (/usr/share/popcorntime/node_modules/json-rpc2/src/server.js:65:18)
    at Promise_then_fulfilled (/usr/share/popcorntime/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/usr/share/popcorntime/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/usr/share/popcorntime/node_modules/q/q.js:1229:9)
    at Promise_done_task (/usr/share/popcorntime/node_modules/q/q.js:871:28)

I'll update #780

**Comment by Persei08** [comment]
You could have kept this issue open I think since `--disable-gpu` argument isn't really a fix
