### ISSUE TITLE
Problem with Swedish subtitles

### ISSUE THREAD

**Issue by hundenstar** [popcorntime/popcorntime#789]
Operating System Version:
Iphone

Popcorn Time Version:
3.2.17

Download date:
2018-05-18

#### Expected Behaviour
Show Swedish subtitles

#### Actual Behaviour
Swedish subtitles work but the 3 extra letters compared to english alphabet å ä ö show up in diffrent symbols depending on font. This appears on both new and older movies.
...

#### Steps to reproduce the behaviour

1. Turned on Swedish subtitles on the application.
2. ...
3. ...

**Comment by Persei08** [comment]
Wrong project. 

This github repo is for PopcornTime desktop version from popcorntime.sh
Popcorntime.sh don't provide Iphone version
