### ISSUE TITLE
Can't open Popcorntime since last commit (8a36996)

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#79]
I can't open Popcorntime since last commit (8a36996)

I'm on OS X and when I launch the app with the "grunt start" command, Popcorntime is blocked at beginning during loading (see picture).

![screen shot 2016-03-09 at 23 14 42](https://cloud.githubusercontent.com/assets/12370868/13652634/9869c6da-e64d-11e5-93de-52062e43452b.png)

In the Terminal, the only output message with ERROR is the following one : `>> [533:0309/232119:INFO:CONSOLE(21)] ""%c[%cERROR%c] couldn't find provider" "color: black;" "color: red;" "color: black;" "tvapi"", source: app://host/src/app/app.js (21)`

**Comment by VitorVRS** [comment]
This occurred due to DMCA changes...

Same issue with a fix: https://github.com/popcorn-official/popcorn-desktop/issues/102
