### ISSUE TITLE
Build #281 No windows x64 download link?

### ISSUE THREAD

**Issue by locodicegr** [popcorntime/popcorntime#790]
https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/281/

Any reason for no windows download?

**Comment by Persei08** [comment]
Builds for windows have failed?

**Comment by karloluis** [comment]
I have the same questions.

**Comment by Tecko71** [comment]
please build 281 for windows ... i am waiting for subtitle support chromecast. Now i have to cast entire desktop to get subtitle.

**Comment by locodicegr** [comment]
Ye its now 2 months since the last windows build

**Comment by Persei08** [comment]
@Tecko71 
Casting subtitles to chromecast should works, but sometimes it require to wait few minutes (2 / 3 / 5 ?) before retrying because opensubtitles dont return the subs if you request too often.
