### ISSUE TITLE
Movie that the title don't match

### ISSUE THREAD

**Issue by manoelnetotto** [popcorntime/popcorntime#791]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.3.10

Download date:
Don't remember

#### Expected Behaviour
Play the movie that is on the title
...

#### Actual Behaviour
Like i said, the movie don't match the title

...

#### Steps to reproduce the behaviour
Just do that

1. ...Open First Blood Part 1
2. ...When opened, you 'll see what i am talking about. The movie is First Blood Part 2 intead First Blood Part 1
3. ...Just fix it please!

**Comment by Persei08** [comment]
See with content providers.
