### ISSUE TITLE
[Request] Search and download subtitles directly

### ISSUE THREAD

**Issue by gpaesa** [popcorntime/popcorntime#793]
Media Player Classic has a search tool to download subtitles directly from OpenSubtitles. You don't need to open a browser and download it. 

Make this, please!

**Comment by Persei08** [comment]
This feature already exist.

**Comment by gpaesa** [comment]
Where?

If the subtitle is out of sync I have to download subtitles from OpenSubtitles in my browser and test each one to find the right.

**Comment by Persei08** [comment]
oh ok, my bad. I understand better now
