### ISSUE TITLE
Can't change subtitles 

### ISSUE THREAD

**Issue by PadreJesus** [popcorntime/popcorntime#795]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
IDK

#### Expected Behaviour
Works normally in chromecast stream

#### Actual Behaviour
I can't change the subtitles when I'm streaming on my TV via Chromecast. I watch the movies with PT-BR sutitles and some movies don't have or it's desyncronized with movie's audio so i download from internet and drop into the player normally.

#### Steps to reproduce the behaviour
I just select to stream to my Chromecast i can't change the subtitles. I tried to grab and move into the APP but doesn't works.

**Comment by kiriles90** [comment]
@Persei08 duplicate issue, close please
