### ISSUE TITLE
Can't compile development branch: some version conflicts...

### ISSUE THREAD

**Issue by Kakadu** [popcorntime/popcorntime#797]
Operating System Version: GNU/Linux
Popcorn Time Version: development branch
Download date: today
Expected Behaviour: it compiles
Log: https://gist.github.com/Kakadu/8db2638edb91a08e2b423119abaa5622

**Comment by Persei08** [comment]
You need to use npm 4 and node 7 or 8.

related to  #774.

**Comment by Kakadu** [comment]
Well, now it's better -- I see the window but get a message `Loading stuck. Click here`. 
Is there a manual how to enable debug log for projects like this?

**Comment by Persei08** [comment]
I've never used this script, I just type each commands: https://github.com/popcorn-official/popcorn-desktop#quickstart

**Comment by Kakadu** [comment]
I found this in the log:

    app.js:21
    [ERROR] Error starting up TypeError: App.Providers.Generic.prototype.parseArgs is not a function(…)

I will keep investigating...

**Comment by sergiomb2** [comment]
[popcorntime-official.nwjs.patch.txt](https://github.com/popcorn-official/popcorn-desktop/files/2088118/popcorntime-official.nwjs.patch.txt)

this patch fix build with npm 5 and also fix core dump on Fedora 27

**Comment by Kakadu** [comment]
@sergiomb2 I can confirm that the patch is helpful.
