### ISSUE TITLE
Failure to run on Ubuntu 18.04

### ISSUE THREAD

**Issue by vipul657** [popcorntime/popcorntime#798]
Operating System Version:
Ubuntu 18.04 LTS

Popcorn Time Version:
I was using the git repository, checked out the master branch.

Download date:
28 May 2018

#### Expected Behaviour
Launch the app
...

#### Actual Behaviour
cache/0.18.6-sdk/linux64/nw: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Popcorn-Time exited with code 127
...

#### Steps to reproduce the behaviour
1.Clone the repo 
2.git pull
3.run make-popcorn.sh
4.gulp run

**Comment by Persei08** [comment]
You need to install some dependencies on Ubuntu 18.04: `sudo apt-get install libgconf-2-4`
and maybe libcanberra-gtk-module too if it throw an error about it in the terminal.

**Comment by vipul657** [comment]
Thanks a lot , this resolved the issue
