### ISSUE TITLE
Add new screenshots

### ISSUE THREAD

**Issue by 394394394** [popcorntime/popcorntime#8]
The .io version used [this](https://i.imgur.com/EoO0bc0.gif) GIF, any thoughts?

**Comment by 2BReality** [comment]
Very cool

On Fri, Feb 19, 2016 at 6:17 PM, 394394394 notifications@github.com wrote:

> The .io version used this https://i.imgur.com/EoO0bc0.gif GIF, any
> thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/popcorn-official/popcorn-desktop/issues/8.

## 

Derek D.Stanton
124 Buck Hill Road
Canterbury, CT 06331-1201
(860) 428-6341

**Comment by team-pct** [comment]
we would like to avoid any copyright infirgment material hosted on github

**Comment by 394394394** [comment]
Of course, agreed.

**Comment by 2BReality** [comment]
@2BReality
