### ISSUE TITLE
Track releases on Github

### ISSUE THREAD

**Issue by ItachiSan** [popcorntime/popcorntime#80]
Hey there,
I am an ArchLinux pacakger and I am packaging PopcornTime on the AUR.
Still, I have to download specific commits tarballs, as there is no release marked on Github.
It would be nice if you can mark specific commits as release. Thank you.

**Comment by team-pct** [comment]
we are working on that

**Comment by z11h** [comment]
@team-pct I think he means using the Github releases/tags feature not build numbers pushing updates in the updater.

**Comment by ItachiSan** [comment]
Yeah, exactly.

**Comment by beppe9000** [comment]
When you do, please attach a zipped "binary" to releases.

**Comment by team-pct** [comment]
https://github.com/popcorn-official/popcorn-desktop/releases/tag/0.3.10
