### ISSUE TITLE
The startscreen doesn't load

### ISSUE THREAD

**Issue by Thomasnei** [popcorntime/popcorntime#800]
Operating System Version:

Mac os Sierra 10.12.6

Popcorn Time Version:

V. 0.3.10

Download date:

05/02/2018

#### Expected Behaviour

Show the movies

#### Actual Behaviour

Keeps on loading
![schermafbeelding 2018-05-31 om 20 16 44](https://user-images.githubusercontent.com/39807975/40800251-1bf04374-6510-11e8-9fea-0e29773a0303.png)

#### Steps to reproduce the behaviour

1. start popcorntime

**Comment by MineyMine** [comment]
I have the same problem  but on a Windows operating system -_-

**Comment by Persei08** [comment]
PT can't contact PT API, often it's becauseof your ISP DNS blocking the API domain. Try to switch your dns for google dns (8.8.8.8, 8.8.4.4) or cloudflare dns (1.0.0.1, 1.1.1.1)
