### ISSUE TITLE
Problem to connect to trakt.tv

### ISSUE THREAD

**Issue by guhenning** [popcorntime/popcorntime#801]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time 0.3.10

Download date:
27/05/18

#### Expected Behaviour
Connect to trakt.tv normally as it did with the TVShow Times.

#### Actual Behaviour
It doesn't connect with trakt.tv, it does open a new window  witch says "Allow Butter to use your account?" and with the buttons YES or NO, if I press YES it shows a code with six digits but extremely quickly so I cant see whats written, and suddenly it closes automatically, if  I press NO it opens a webpage on my Google Chrome witch says 
"TRAKT
OAUTH ERROR
The authorization server does not support this response type."

#### Steps to reproduce the behaviour

1. Go to Settings and press Connect to Trakt
2. Press Yes
3. ...
![capture](https://user-images.githubusercontent.com/39813412/40813610-111db05e-653c-11e8-9fd3-9f34508c0ca2.PNG)
![capture2](https://user-images.githubusercontent.com/39813412/40813603-088068f6-653c-11e8-9fb1-3c630ccb9d78.PNG)

**Comment by leidsongermano** [comment]
I'm getting a similar error. After click on yes, it shows for a few seconds the activation code to put on trakt.tv/active and after that it closes the window.

**Comment by Persei08** [comment]
It is fixed in dev builds: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

If last dev build not available for windows use previous ones (279).

**Comment by felipebraz** [comment]
I'm having the same problem on MacOS... When this fix will be available on the nov dev build? Thanks!!

**Comment by Persei08** [comment]
@felipebraz If i'm not wrong it's fixed since 2016-12-13 in dev builds

**Comment by guhenning** [comment]
Persei08  Sorry, is there a tutorial on how to install the dev build to fix it, and witch one from this link https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/ should I use?  This? 

Popcorn-Time-0.3.10_osx64.tar.xz

I have a windows 10 x64

Again sorry I really don't know what I need to do!  Many thanks!

**Comment by Persei08** [comment]
@guhenning 

>If last dev build not available for windows use previous ones (279).

It mean you have to click "previous build" 2 times to go on build 279 page and you download "Popcorn-Time-0.3.10-win64-Setup.exe", then you double-click the downloaded file to start the install process and it should overwrite the previous version.

After that, if your issue is solved, please close the issue.

**Comment by juanpsm** [comment]
This fix https://github.com/popcorn-official/popcorn-desktop/issues/816#issuecomment-416063848
