### ISSUE TITLE
Does not advance beyond the loading page

### ISSUE THREAD

**Issue by tkdmed** [popcorntime/popcorntime#802]
Operating System VWindows 10

Popcorn Time Version:

3.10
Download date:
 2016

#### Expected Behaviour
show me movies
...

#### Actual Behaviour

does not advance beyond the loading page

...

#### Steps to reproduce the behaviour

1. ...open the app
2. ...click on the movie
3. ...play movie

![image](https://user-images.githubusercontent.com/39802036/40835851-ff516b50-6594-11e8-80c1-502793647746.png)

**Comment by Persei08** [comment]
Try with last dev builds: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

If last dev build not available for windows use previous ones (279).

**Comment by HannesBBR** [comment]
Build 279 has the same behaviour on Windows 10. See issue #764

**Comment by Persei08** [comment]
You are stuck on connecting. Try to switch your dns for google dns (8.8.8.8, 8.8.4.4) or cloudflare dns (1.0.0.1, 1.1.1.1) , then restart PT and retry to see if it's better
