### ISSUE TITLE
Is there a way to point popcorntime to the VLC (UWP) instead of the normal application?

### ISSUE THREAD

**Issue by leekslk** [popcorntime/popcorntime#807]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
Reinstalled today but had it for while

#### Expected Behaviour
Select VLC as player, plays in VLC

#### Actual Behaviour
Only works with VLC (normal app), will not detect the UWP version from the microsoft store.

Perhaps I've missed something, I know that the VLC player is selected based on it's installation path being on the C: drive. Would there be a possibility to point it to the UWP applications ?(they have a weird path)

**Comment by Persei08** [comment]
Can you use it (VLC UWP) via CLI ?
What is the path where it is installed?

The file for external players is in <pt install folder>/src/app/lib/device/ext-player.js

**Comment by leekslk** [comment]
I'm not sure what you mean, through the command line?

Would I be able to point the ext.player.js file to the VLC UWP instead?

**Comment by Persei08** [comment]
>I'm not sure what you mean, through the command line?

Yes, via command line.

>Would I be able to point the ext.player.js file to the VLC UWP instead?

No, ext-player.js, is a file containing players arguments and functions to run command lines. So, if VLC UWP support command line, it will just require to add the necessarry arguments to the existing list

**Comment by leekslk** [comment]
As far as I know, I could launch vlc through the command line (Win+R) by typing vlc:

I'm not sure about the path apart from it being in the Program Files/WindowsApps folder (as with most UWP apps)

What should I add in the ext-player.js?

**Comment by Persei08** [comment]
I don't know, `Program Files/WindowsApps` seem protected but I'm not familiar with UWP apps.

ext-player.js have a list of players and arguments (lines [7 to 88](https://github.com/popcorn-official/popcorn-desktop/blob/be800aa98cb9ef16f7e00737bbc51ba69204ed8f/src/app/lib/device/ext-player.js#L7)) but there is also a detection process to find `.exe` files, so if nwjs can't detect the app, it will not work.

Finally, i don't think you can make it works as easily as i was thinking :/
