### ISSUE TITLE
FFmpegDemuxer: no supported streams

### ISSUE THREAD

**Issue by Kakadu** [popcorntime/popcorntime#808]
Operating System Version: Linux
Popcorn Time Version: development branch
Download date: yesterday

#### Expected Behavior 
It plays movies

#### Actual Behavior
It doesn't

It is a continuation of #797: I managed to compile everything and browse movies but I can't watch movies because of an error from console output

    [4379:4425:0611/161932.071663:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
    [4379:4379:0611/161932.072712:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS

I tried to replace `ffmpeg` libraries by the ones bundled with previous distributions but got linking errors and no success. I also found an [issue](https://github.com/nwjs/nw.js/issues/6482) but I'm unexperienced in node.js and can't apply this knowledge. Can you give any advice?

P.S. If anybody interested the latest bundle from the website doesn't work after I updated to Ubuntu 18.04. So I'm trying myself.

**Comment by Persei08** [comment]
>It is a continuation of #797: I managed to compile everything and browse movies but I can't watch movies because of an error from console output

I guess it's because the patch provided by @sergiomb2 use the official nwjs which doesn't have the necessary codecs.

At this point the only fix I could think is to compile a custom nwjs >0.35 with all necessary codecs like in the issue you linked but it take lot of time.

For ubuntu 18.04, check #798

**Comment by Kakadu** [comment]
@Persei08 issue #798 is not helpful. I don't get any errors in the terminal log. It just asks about acceptance of license and nothing: no movies, no tabs, no text in terminal.

**Comment by Persei08** [comment]
@kadada can you open another issue report for the ubuntu 18.04 issue because here it will be confusing to deal with 2 issues in one report.

**Comment by Kakadu** [comment]
@Persei08 done

**Comment by Persei08** [comment]
Thx

**Comment by gtklocker** [comment]
I'm having the same issue on Arch Linux with your CI build 362. I've tried multiple libffmpeg.so, including the two in your build but to no avail.

**Comment by dahagag** [comment]
Same error on MacOS Catalina
