### ISSUE TITLE
Can not build from Development Repository 14.06.2018

### ISSUE THREAD

**Issue by Simon-Davies** [popcorntime/popcorntime#810]
Operating System Version:
Linux - Fedora-28

Popcorn Time Version:
Development Repository

Download date:
14.06.2018

#### Expected Behaviour
App builds

#### Actual Behaviour

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/popcorn-official/butter-settings-popcorn.git /root/.npm/_cacache/tmp/git-clone-9dc487c8
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-9dc487c8': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-14T01_30_26_513Z-debug.log
Local dependencies encountered an error while installing
```

#### Steps to reproduce the behaviour

Build Popcorn Time from source:
```
chmod +x make_popcorn.sh
./make_popcorn.sh
```

**Comment by Persei08** [comment]
Cannot reproduce on xubuntu 18.04.

**Comment by Simon-Davies** [comment]
I am building on a fedora-28 template in Qubes OS 4.0.

Xubuntu 18.04 is a different distro.

Edit: I got it to build by running:

```
sudo npm install -g bower gulp
npm install -f
bower install -f
gulp build
```
I then run Popcorn Time with:

`gulp run`

It opens, I see the accept screen and then it closes straight away.

I get the below in the Terminal:

```
[user@fedora-28 linux64]$ ./Popcorn-Time 
Illegal instruction (core dumped)
```

**Comment by Persei08** [comment]
What `node -v && npm -v` return ?

**Comment by Simon-Davies** [comment]
Looks like the same issue as #776

node -v

`v8.11.3`

npm -v

`5.6.0`

**Comment by Persei08** [comment]
>Looks like the same issue as #776

Doesn't sound like what you described, #776 is related to nwjs and your error is with npm :/

Try with npm version 4 `npm install -g npm@4`

**Comment by Simon-Davies** [comment]
I can get npm install to work with the -f flag.

I then build successfuly but the app crashes which is the same issues as #776. I'm running Fedora 28.

**Comment by Simon-Davies** [comment]
I now have a running build by following your workaround in #766 

I hope Popcorn Time is updated to work on Fedora 28 so we can use the included version of nwjs-sdk and libffmpeg.so with greater codec support.
