### ISSUE TITLE
3.10 tarball doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Kakadu** [popcorntime/popcorntime#811]
Operating System Version: Ubuntu GNU/Linux 18.04
Popcorn Time Version: 3.10 archive from website

#### Expected Behaviour
It works

#### Actual Behaviour
Doesn't. It asks about license and shows nothing: no movies, no tabs, no errors in the stdout. Before the upgrade I think that it worked OK. Previous version 3.09 works OK

P.S. This was splitted from #808 by request from @Persei08

**Comment by Persei08** [comment]
Can you explain step by step how you install/run it please, because I really don't see :/

edit: Maybe not step by step, but describ a bit more where you put it, how you run it, ... Thx

**Comment by Kakadu** [comment]
I redownloaded and it seems to start working now. Sorry for the noise
