### ISSUE TITLE
Trakt do not sync watchlist

### ISSUE THREAD

**Issue by Tecko71** [popcorntime/popcorntime#817]
Windows 10

Popcorn Time Version:
Popcorn-Time-0.3.10-win64-Setup.exe, build #279

Download date:
When did you install Popcorn Time? Su 8 juli

#### Expected Behaviour
What did you think the app was going to do? Showing watchlist trakt
...

#### Actual Behaviour
What does the app do instead? Hanging
...

#### Steps to reproduce the behaviour

1. klick the watchlist button
2. Loading takes some time
when klicking movie or serie app hangs...keeps on loading
3. ...

**Comment by stellaki13** [comment]
please same issue build 363 laptop nvidia samsyng with windows 7 alla in jenkins files try to doanload with manager says remote server closed connection  so how fix the trakt sync problem no connect?
