### ISSUE TITLE
[Request] Separate favorites between movies and series

### ISSUE THREAD

**Issue by arnii5** [popcorntime/popcorntime#819]
I was thinking it could be a nice usability feature to make a visible distinction between movies and series in the favourites tab. Many people add series they want to follow but when you save some movies that look interesting for later it results in a messy tab.

The simplest way could be to put series on the top and then add a small line/visual element before starting to show the movies one has favorited. I guess movies and series are identifiable by code? But i'm not sure how PT handles this stuff.

**Comment by Persei08** [comment]
There is actually this kind of feature. You can use the "Type" menu (near sorting menu) to choose to only display all/movies/series/animes

**Comment by arnii5** [comment]
How did I not see this possibility :o 
I wasn't able to find it through Google but yes this totally answers my needs.
Thanks for pointing it out to me!
