### ISSUE TITLE
Improve Updater

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#82]
- Create build number ( instead of updating 0.3.9 , we update build number to keep user automatically update with last developments ) 
- Switch zip to tar.gz 

Reference : https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/updater.js

**Comment by z11h** [comment]
Good idea, but why move to using tar.gz over zip?

**Comment by VitorVRS** [comment]
I think is for Windows compatibility :/

**Comment by team-pct** [comment]
tar.gz over zip because zip sometimes when we were updating previous Popcorn Time version we had an issue with path too long
