### ISSUE TITLE
Hybrid Intel+AMD Gpu +installing MadVr = black screen video in Popcorntime 

### ISSUE THREAD

**Issue by KickassMcFuckyeah** [popcorntime/popcorntime#820]
Operating System Version:
Windows 7

Popcorn Time Version:
3.10

Download date:
Just 5 minutes ago

#### Expected Behaviour
Show video
...

#### Actual Behaviour
Play audio and subtitles but show black screen
...

#### Steps to reproduce the behaviour

1. Have hybrid Intel+AMD gpu
2. Install MadVR
3. Popcorntime is now broken.
4. Uninstall MadVr, still broken
5. Play around with whatever settings, popcorn time refused to show anything but black screen,

**Comment by ozkanpakdil** [comment]
delete every configuration related to popcorn and butter in windows c:\users\yourusername\applicationdata maybe. I use linux. then re-install popcorn.
