### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by lcmartinezdev** [popcorntime/popcorntime#821]
Hello

Operating System Version:
All SO

Download date:
7/22/2018

#### Actual Behaviour
The last one release was Oct 31, 2016.

So my question is: When is the next release?

Thank you.

**Comment by Persei08** [comment]
Usually beta releases were dev builds selected to be beta releases (not sure if based on random criterias or what), but now beta release wasn't updated for long time as you already know.


If you want the more up to date version, you can use the latest dev builds (https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/) or build it from the development branch yourself (https://github.com/popcorn-official/popcorn-desktop/tree/development#quickstart)

**Comment by rafsanjani** [comment]
I've been asking myself this same question for some time. I've been trying to build it from the development branch but I've always been overwhelmed by the numerous errors I encounter and JavaScript is not my specialty.

**Comment by Persei08** [comment]
Hi @rafsanjani 

Please provide console output of the commands you're typping.

Also PT should be built with npm 4

**Comment by lcmartinezdev** [comment]
@Persei08 
I think the best option is provide a updated installable package to all people; I use one from https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/ but if somebody can put updated installable package in the oficial web page will be nice.

So, Who can update links in PT web page?

**Comment by Persei08** [comment]
>So, Who can update links in PT web page?

PT devs? look at who merge pull requests
