### ISSUE TITLE
Can't watch the serie's episode!

### ISSUE THREAD

**Issue by rosoubr** [popcorntime/popcorntime#825]
Operating System Version:
 Windows 10

Popcorn Time Version:
 Popcorn Time 0.3.10

Download date:
 Around July, 30th

#### Expected Behaviour
 Stream the tv serie episode I chose from the list of episodes shown.
...

#### Actual Behaviour It keep showing the message 'Conecting' and nothing happens! I've waited several minutes and it keeps 'conecting' without ever showing the episode!
...

#### Steps to reproduce the behaviour
 

1. ...Choose the tv series "Father Brown"
2. ... Choose season 3
3. ... Choose any episode and try to watch it

I've installed the app about a week ago and couldn't watch a single episode of the series yet!
Sincerely,

**Comment by Breaking1** [comment]
Every episode has a health indicator, when you enter an episode up to the right next to the magnet link yo will see a little dot. Red is bad, yellow-ok and green good. Check first if the health indicator shows yellow or green so it's watchable.  Can you try a different series from the updated section just to make sure it works.

**Comment by rosoubr** [comment]
Thank you for answering. I have already notice the little dot system. In
this case the lillte dot was grey, or maybe it just meant it got no color,
no health indication maybe. After trying and not being able to watch, when
I get back to the list of chapters, the little dot related to the chapter I
tried becomes red! It happened most times! But just after the failed
attempt.
Rosane


Em qua, 5 de set de 2018 às 18:46, Breaking1 <notifications@github.com>
escreveu:

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please
