### ISSUE TITLE
Movie list doesn't update

### ISSUE THREAD

**Issue by mickwheeler** [popcorntime/popcorntime#826]
Operating System Version: Windows 10?
Popcorn Time Version: 0.3.10-0

Download date: 6/2/2018

#### Expected Behaviour: update list of movies when new movies are available - sorted by "Last Added"
...

#### Actual Behaviour: Movie list has not updated in weeks. Avengers: Infinity War is the first movie when sorted by "Trending" and yet does not appear in the list when sorted by "Last Added"
...

#### Steps to reproduce the behaviour: Sort movies by "Last Added"

1. Open Popcorn Time
2. Sort movies by "Last Added"
3. Old movies...

![image](https://user-images.githubusercontent.com/42160249/43749488-52cc5414-99c2-11e8-97b3-da1347fc677d.png)

**Comment by mickwheeler** [comment]
And when sorted by "Trending"

![image](https://user-images.githubusercontent.com/42160249/43749527-8be0a75a-99c2-11e8-97bf-12aa7828b905.png)

**Comment by Persei08** [comment]
Hi,

"Trending" is based on https://trakt.tv/movies/trending except movies not availlable are not displayed and i think results are also cached and served by Movies APi to avoid users to flood Trakt.tv servers with requests.

For "Last added" I don't know exactly
