### ISSUE TITLE
werkt niet 

### ISSUE THREAD

**Issue by stephaniexzara** [popcorntime/popcorntime#829]
popcorn time gedownload omdat iedereen er zo goed over bezig was om de vele films. 

en nu werkt het niet al 2x verwijderd en opnieuw geinstalleerd, maar werkt nog niet. Ik open de app en dat blijft maar laden en werkt niet.. en er komt ook voor de rest niets op.. 

mvg

**Comment by owenselles** [comment]
blokkeert je internet provider popcorntime?

**Comment by luuk00000000000000000000000000000000000** [comment]
I'll just translate it

**Title:** 
Doesn't work

**Body:**
I downloaded popcorn time because everyone said it was good and it had a lot of movies.

It doesn't work, I reinstalled it twice but it still doesn't work. I open the app but it keeps endlessly loading. Nothing happens.
