### ISSUE TITLE
PKG for OsX 

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#83]
- Switch DMG by some PKG installer that can be built on LINUX

**Comment by JamesBream** [comment]
Any reason we can't use mkfs.hfsplus to create the DMG on linux? Really would avoid a PKG installer at all costs, it completely invalidates the simple drag-and-drop installation method that Mac users are used to. Also screams "Malware" in my opinion.

**Comment by team-pct** [comment]
@JamesBream I tried mkfs.hfplus and i failed , if you know better please let me know

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/pkg-for-osx/104
