### ISSUE TITLE
Application flickers

### ISSUE THREAD

**Issue by Kizburb** [popcorntime/popcorntime#830]
Operating System Version:

Windows 10

Popcorn Time Version:

3.10

Download date:

Not sure

#### Expected Behaviour

Stream torrents so I could watch series/movies without problems.

#### Actual Behaviour

Randomly flickers black.

#### Steps to reproduce the behaviour

Not sure, just occured while using the app after setting up 2 monitors and watching in fullscreen (One set to 120Hz and one on 144Hz)

**Comment by Breaking1** [comment]
Did it work properly before this set up with 2 monitors?

**Comment by Kizburb** [comment]
Yes.
