### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by IhRr** [popcorntime/popcorntime#831]
I need help, the subtitles arn't synchronized with the movie. Or it came 10 seconds before the character speaks or 10 seconds later. How can I fix that?

**Comment by Breaking1** [comment]
Go to settings and press the the pic of a keyboard on top of the settings page, there you will find all the shortcuts you can use in popcorntime including how to sync subtitles.

**Comment by IhRr** [comment]
Thanks for the help!!!

Em qua, 5 de set de 2018 às 18:39, Breaking1 <notifications@github.com>
escreveu:

**Comment by derrix060** [comment]
Close it?
