### ISSUE TITLE
I dont have idioms and any subtitules

### ISSUE THREAD

**Issue by esven888** [popcorntime/popcorntime#832]
Operating System Version:
 Windows 10

Popcorn Time Version:
Popcorn-Time-0.3.10-Setup.exe

Download date:
  26/08/2018

#### Expected Behaviour
 have idioms
...

#### Actual Behaviour
 the aplication doesnt have idioms
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by alvitawa** [comment]
Sometimes it works to close the video and open it up again, but most of the time nothing :(
