### ISSUE TITLE
JSON-RPC api broken?

### ISSUE THREAD

**Issue by Jokimbe** [popcorntime/popcorntime#833]
Operating System Version:
macOS 10.13.6

Popcorn Time Version:
https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/281/

I decided to pick up working on a remote again which I created around a year ago and it worked fine, but now with the current version I keep getting
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "TypeError: Cannot read property 'currentView' of undefined"
  },
  "id": 10
}
when using: 
* "getselection"
* "getcurrentlist"

However the following work just fine:
* establishing a connection
* "ping"
* "getviewstack"

**Comment by kiriles90** [comment]
Something tells me this has something to do with the Marionette v3 update and the issue it caused in the viewstack. Check
https://github.com/popcorn-official/popcorn-desktop/pull/721
https://github.com/popcorn-official/popcorn-desktop/issues/725
https://github.com/popcorn-official/popcorn-desktop/pull/736 
you might find something there.

**Comment by Jokimbe** [comment]
You're probably right, however I don't know enough about how the code works to make any sense of what could be broken...

I hope someone with more knowledge can fix this, I'd love to be able to get my remote working again
