### ISSUE TITLE
I use Express VPN but its IP address does not appear in Popcorn Time 'Remote Control" but my Local IP address does? Does this mean that VPN is not working?

### ISSUE THREAD

**Issue by Rupert288** [popcorntime/popcorntime#845]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Both are not related all is normal remote control should be your local ip
