### ISSUE TITLE
Many New Shows (Sept 30+) Failing to Cast

### ISSUE THREAD

**Issue by torivt** [popcorntime/popcorntime#846]
Operating System Version:
OS X 10.13.6

Popcorn Time Version:
3.10-0

Download date:
Last year?

#### Expected Behaviour
Cast all shows to Chromecast

#### Actual Behaviour
Shows the loading bar on the TV and then immediately goes away to the black screen with the Chromecast symbol.

#### Steps to reproduce the behaviour

1.  Error has occurred when trying the Sept 30 air date of episodes from Always Sunny, Fear the Walking Dead, Bob's Burgers
2. Watching these shows on laptop is fine
3. Sept 30 episode of Alaskan Bush People works fine
4. Movies are fine
5. Have flushed databases and reset default settings

**Comment by Persei08** [comment]
I noticed this issue with a 480p avi (xvid) episode while the 720p mkv (h264) of the same episode play fine.

I think it's because of the [videos format supported by the chromecast](https://developers.google.com/cast/docs/media) (container, video/audio codec).

Just sharing my idea

**Comment by torivt** [comment]
Does the 720p version play w/ sound? It never has for me, possibly the same compatibility issue. Maybe I just need to get a Chromecast Ultra.
Thanks

**Comment by Persei08** [comment]
No, sound wasn't working with this 720p (Walking dead s09e07). I didn't noticed at first, was just testing chromecast
