### ISSUE TITLE
i can't see got with subtitles on vlc

### ISSUE THREAD

**Issue by RickyGameplays** [popcorntime/popcorntime#850]
Operating System Version: Windows 10

Popcorn Time Version: 3.10

Download date: 13/10/2018

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by RITACOUTO** [comment]
Não tenho mais as legendas. Sumiram. O que faço? Obrigada.
