### ISSUE TITLE
When i try to watch anything the screen gets black and there is just sound. 

### ISSUE THREAD

**Issue by gssfxs** [popcorntime/popcorntime#853]
Operating System Version:
 It's a Windows 8.1

Popcorn Time Version:
 0.3.10

Download date:
 In April 2017.

#### Expected Behaviour
 Until a month ago he was working was it supposed to work, showing tv shows and movies without having to downloading or anything.   
...

#### Actual Behaviour
Now, he does't show me anything anymore. The tv shows load but the screen gets black and there is just sound, not the imagens anymore. I tried to watch in other player in my computer as they give us the option, and it was working so far, but now in the other player there is only the IMAGE, and not the SOUND. So as you can see, nothing is working as it supposed to anymore.
...

#### Steps to reproduce the behaviour

1. ... I don't know man 
2. ... Looks like i'm the only one with this problem so show me how to update the site
3. ... Help me find a solution because i really need this app...

**Comment by Vanessa1978** [comment]
I have this issue also.. when I want to watch an episode in 480p (only there is this problem), I get only sound and no video...
When the 720 and 1080p are not available, I can not watch the episode..

**Comment by Melokap** [comment]
I have this problem too, only in 480p. Tengo el mismo problema, en 480p los episodios de las series no se pueden ver pero si escuchar. Espero que lo puedan resolver.

**Comment by ozkanpakdil** [comment]
install VLC and choose VLC as player. https://www.videolan.org/vlc/

**Comment by Vanessa1978** [comment]
Thank you !!! It works

Van: özkan pakdil
Verzonden: zondag 28 oktober 2018 09:17
Aan: popcorn-official/popcorn-desktop
CC: Vanessa1978; Manual
Onderwerp: Re: [popcorn-official/popcorn-desktop] When i try to watch anythingthe screen gets black and there is just sound. (#853)

install VLC and choose VLC as player.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Deze e-mail is door AVG-antivirussoftware gecontroleerd op virussen. 
www.avg.com

**Comment by Melokap** [comment]
Thanks, takes a little longer but works!!

> 
> 
> install VLC and choose VLC as player. https://www.videolan.org/vlc/



> 
> 
> install VLC and choose VLC as player. https://www.videolan.org/vlc/

Thanks!! It takes a little longer but works!!

**Comment by darshan92kumar** [comment]
Facing the same problem. This should be fixed as priority 1

**Comment by darshan92kumar** [comment]
> 
> 
> install VLC and choose VLC as player. https://www.videolan.org/vlc/

Steps to do the above please ?

**Comment by ozkanpakdil** [comment]
![image](https://user-images.githubusercontent.com/604405/47962258-6bf83400-e01a-11e8-9383-1af251a7fd9b.png)
if you install VLC. you will see the option

**Comment by Persei08** [comment]
Can someone tell what show and episode are concerned ? and if they are encoded with xvid?
