### ISSUE TITLE
Trojan Virus detected when i download windows apk

### ISSUE THREAD

**Issue by Robbielol** [popcorntime/popcorntime#855]
Using windows 10, popcorn time 6.0, install over several days. I attempt to open popcorn but it eventually just closes on me.  Sometimes i cant even grab the metadata for a movie and if i do it just closes.
Sorry about this i really love popcorn time i show it to everyone i know!

**Comment by team-pct** [comment]
Wrong website , wrong version popcorntime.sh is the website that you need to download from
