### ISSUE TITLE
seem lot of movies (almost all) aren't indexed

### ISSUE THREAD

**Issue by WorldWalkr** [popcorntime/popcorntime#856]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
November/ 2016

#### Expected Behaviour
Update the Movie index
...

#### Actual Behaviour
Spy who dumped me and Incredibles 2 were released days ago in yts.am yet they haven't appeared in Popcorntime's listings.
...

**Comment by Persei08** [comment]
seem all newly added movies are missing, maybe the last one indexed was around "The Hollow Child" (YTS api's movie id = 9276)
