### ISSUE TITLE
[Question] Get Popcorn Time watched movies database

### ISSUE THREAD

**Issue by lsonnino** [popcorntime/popcorntime#857]
Hi,
I would like to make a desktop app to keep track of the movies I have watched and to keep a watch list of the movies I have watched. Therefor, I have a question: where does Popcorn Time store the list of the movies I have watched ? So that my app can get that database and import it or update it.

Thanks in advance

**Comment by ozkanpakdil** [comment]
Hi
here is win10 location
C:\Users\USERNAME\AppData\Local\Popcorn-Time\User Data\Default\data\watched.db

you can find it in linux or mac like this
find ~|grep Popcorn|grep "watched.db"

**Comment by lsonnino** [comment]
Thank you, I found the location. What are those numbers in the file ? For instance for the movie:
```{"movie_id":"tt1515091","date":{"$$date":1534014605707},"type":"movie","_id":"30ePZw6bVd2H6dPv"}```
```tt1515091``` seems to correspond to the IMDB movie id but what are ```$$date``` and ```_id```?

**Comment by ozkanpakdil** [comment]
date probably unix timestamp. comes from javascript check https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/database.js#markMovieAsWatched

_id no idea. probably some internal id which looks like a random string

**Comment by lsonnino** [comment]
Ok thank you for helping me
