### ISSUE TITLE
Problems with series in 480p 

### ISSUE THREAD

**Issue by Melokap** [popcorntime/popcorntime#858]
Operating System Version:

Windows 8.1
Popcorn Time Version:

0.3.10
Download date:

3 years ago/Hace 3 años
#### Expected Behaviour

...Audio+video in 480p/audio + video en 480p

#### Actual Behaviour

...Only audio/Solo audio

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by 8qBITs** [comment]
same problem here..

**Comment by ozkanpakdil** [comment]
I believe https://github.com/popcorn-official/popcorn-desktop/issues/853#issuecomment-433685537 can fix your issue

**Comment by Melokap** [comment]
> 
> 
> I believe [#853 (comment)](https://github.com/popcorn-official/popcorn-desktop/issues/853#issuecomment-433685537) can fix your issue

Yeah! I use it as alternative, thanks for the tip!! 👍

**Comment by Persei08** [comment]
Can someone tell what show and episode are concerned ?

**Comment by Melokap** [comment]
> 
> 
> Can someone tell what show and episode are concerned ?

Almost every show that I watch have the problem, there is no specific ones.

**Comment by Persei08** [comment]
Does it happen only with episodes encoded with xvid codec ?
