### ISSUE TITLE
Failed to fetch list of the movies

### ISSUE THREAD

**Issue by dzianisv** [popcorntime/popcorntime#860]
Operating System Version:
Linux Fedora 27

Popcorn Time Version:
3.10

Download date:
6.11.2018

#### Expected Behaviour
The list of the films

#### Actual Behaviour
Black screen and circular progress bar

#### Steps to reproduce the behavior
Launch a freshly installed PopcornTime

![popcorntime](https://user-images.githubusercontent.com/2119348/48034326-03bb6680-e170-11e8-923c-493ebc4293fe.gif)

**Comment by Persei08** [comment]
Try to switch your dns servers for cloudflare Dns (1.0.0.1, 1.1.1.1) or Google Dns (8.8.8.8, 8.8.4.4) it's probably because your ISP Dns servers are blocking API domain.

**Comment by dzianisv** [comment]
Can you point me to the API endpoint, it seems, that public DNS also doesn't help me.

**Comment by hadifarnoud** [comment]
I have the same issue. seems like this fork of popcorn time is not being updated anymore. it's been ages ago they released 3.10

**Comment by Persei08** [comment]
@denis4net movies api is here: https://movies-v2.api-fetch.website/status

**Comment by dzianisv** [comment]
> @denis4net movies api is here: https://movies-v2.api-fetch.website/status

why did you close issue, do you know how to fix this issue? I see that all services are available on the page, but popcorntime still doesn't work. Can you help me with debugging?

**Comment by hadifarnoud** [comment]
and also, what am I supposed to do with the API endpoint you gave me?

**Comment by team-pct** [comment]
If you can access this URL , then you have the lastest one

**Comment by team-pct** [comment]
hadifarnoud you can use the last version https://ci.popcorntime.sh this is the version being developed when we will have stable version we will release a new version
