### ISSUE TITLE
Subtitle is not shown when casting to chromecast

### ISSUE THREAD

**Issue by msamyelsheikh** [popcorntime/popcorntime#864]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn time butter Beta 0.3.10-0

Download date:
4-Nov-2018

#### Expected Behaviour
Display the subtitle when casting to chromecast
...

#### Actual Behaviour
Subtitle doesn't appear when casting to chromecast
...

#### Steps to reproduce the behaviour
1. Go to settings
2. Change language to Arabic in "Default Subtitle"
3. In OpenSubtitiels, connect to your opensubtitle account with your opensubtitle username/password
4. close the settings
5. open the movie page
6. Play with cast to chrome option
7. The movie will be played on chromecast device but subtitle is not shown

**Comment by andreasvirkus** [comment]
Same issue on OSX (10.12.6 High Sierra)

**Comment by Noxillio** [comment]
Same issue on Windows, happens when streaming to all types of devices, including VLC/Google Cast.

Complains that there are no subtitles found, even though they are most certainly available when playing through Butter.

**Comment by msamyelsheikh** [comment]
Thanks in advance @team-pct.
Do you have any comment on this issue please?

**Comment by team-pct** [comment]
Sometimes Subtitle server take time to start , i have been trying to fix this issue by waiting on the server when casting , i will push any solution i might find
