### ISSUE TITLE
Jenkins fails to build the Windows installers after dev build #277

### ISSUE THREAD

**Issue by kiriles90** [popcorntime/popcorntime#865]
Operating System Version:
Windows (all of them)

Popcorn Time Version:
All 0.3.10 ci. dev builds newer than 277 (279 actually but this one has dropped off the builds list in ci.)

Download date:
18-11-2018

#### Expected Behaviour
Have a Windows installer
...

#### Actual Behaviour
Doesnt have a Windows installer because Jenkins failed while building it
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

*Can someone check if it was https://github.com/popcorn-official/popcorn-desktop/pull/772/ what broke it? Specifically https://github.com/popcorn-official/popcorn-desktop/commit/f3135466bd5b103c202929e21c45e7b2db25b1ae and those changes on gulpfile.js line 218 (line 214 is just reverting changes made earlier that day with https://github.com/popcorn-official/popcorn-desktop/commit/1a0b13b0d4b070e1f48b34de1c3d3a9c8172bff5 and https://github.com/popcorn-official/popcorn-desktop/commit/1dafac2149db6f62654da81a27b2636fc224bac0)

**Comment by team-pct** [comment]
Fixed

**Comment by kiriles90** [comment]
I saw, thank you!!
