### ISSUE TITLE
Use xdg-open as alternative to external players in Linux

### ISSUE THREAD

**Issue by Preisschild** [popcorntime/popcorntime#868]
It would be nice if there would be an option to switch between auto-detecting external players and using [xdg-open](https://linux.die.net/man/1/xdg-open), to let the user automatically handle this. This would make packaging PCT with external player support to Flatpak possible.

**Comment by Preisschild** [comment]
I was thinking to maybe use it as default option in the external player dropdown menu. xdg-open would take the preferred media-player nevertheless.

**Comment by Persei08** [comment]
Just looking a bit at it and trying to think how it could be implemented. 
It seem xdg-open only take an URI as argument, and open the associated app based on mime-type associations.

PT create an http stream to play the video, so if I type `xdg-open http://127.0.0.1:58117/0` it open firefox (my default browser)... which isn't what we want.

Eventually, it will require to play the file directly from filesystem, so it will check mime-type and open the associated app... (for me... VLC for video/avi and Parole media player for video/mp4), but i guess it will lost the default downloaded subtitles sometimes and controls buttons from PT UI.

**Comment by Persei08** [comment]
maybe this could help:

https://github.com/flathub/org.filezillaproject.Filezilla/issues/40#issuecomment-613315991
