### ISSUE TITLE
Can't hear sound very well

### ISSUE THREAD

**Issue by zerak029** [popcorntime/popcorntime#870]
Operating System Version:
Windows 8

Popcorn Time Version:
6.1.0

Download date:
Within the last 3 months

#### Expected Behaviour
Play movie with good sound

#### Actual Behaviour
Can barely hear  what the people in movie/show are saying even when i have the volume super high

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
You don't use the version of this project. the version number don't match.

**Comment by zerak029** [comment]
??

**Comment by zerak029** [comment]
So which version do i use

**Comment by Persei08** [comment]
The version here is 3.10 (or 0.3.10) and the website is https://popcorntime.sh/.

![Short explanation](https://i.imgur.com/cRBrr6z.png)

**Comment by zerak029** [comment]
hm okay im gonna try it now with that version

**Comment by zerak029** [comment]
im not sure why but im not able to stream to my tv now.

**Comment by Persei08** [comment]
Issue board is for  reporting issue or talking about development. For help, you can ask on [/r/PopCornTime/](https://www.reddit.com/r/PopCornTime/).
