### ISSUE TITLE
DATABASE fails to open from times to times

### ISSUE THREAD

**Issue by Franck78** [popcorntime/popcorntime#880]
Operating System Version:
Linux opensuse leap 42.3

Popcorn Time Version:
3.10

Download date:
the day after releasing  (~2016)

There is no way to reproduce this bug. It happens say 1 time over 50 launches.

At startup, Popcorn completly fails to 'see' the database.

A pop-up appears stating something I don't really remember.

If you reply 'OK' you loose all the database and get a new one
If you CANCEL, it's ok, restart Popcorn and everything is fine

Something busy at some exact moment ? A race condition on some resources ? I have no idea.

Thank you

**Comment by Franck78** [comment]
cool, got it! Not the database.

It is asking for the license agreement.

If you say yes, pfuittt no more database...
You have to say NO, your are safe.

![popcorn-bad](https://user-images.githubusercontent.com/1778884/48983378-82138480-f0ee-11e8-8f4e-ca45857485cc.jpg)

**Comment by Persei08** [comment]
So it seem sometimes it can't detect/read your config :/.
Any feature enabled on your system which can potentially bug that (disk encryption, sandbox, ... ?)

How have you installed PT ?.. where ?.. in /opt, in your home?

Maybe try a clean install, (don't forget to backup your database in advanced settings or by copying the "~/.config/Popcorn-Time/Default/data/" folder)

Also maybe, it something, more related to 0.3.10 beta and it was fixed in [dev builds](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/).

**Comment by Franck78** [comment]
Hello,
no special features, installed in /opt. Maybe sometime my system is 'loaded' and Pop is impatient ? Add a silent retry ?

Just tried build #332 linux64, not working. Generates a crashdump and nothing more.
With a clean .config/Popcorn-Time  (eg no data at all)

[chromium-extension-minidump-5bca654c38622ed8.dmp.gz](https://github.com/popcorn-official/popcorn-desktop/files/2634543/chromium-extension-minidump-5bca654c38622ed8.dmp.gz)

Still annoyingly ask for opening kdeWallet before crashing.

Franck

**Comment by Franck78** [comment]
If this can help , tried manually lauch 'payload binary'

it crashes dump with build #332 
it tries to do the job under released 3.10

fc@ntkiller2:/opt/pop> ./payload 
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_crtbegin_for_eh_o
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_crtbegin_o
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_crtend_o
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_ld_nexe
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_libcrt_platform_a
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_libgcc_a
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_libpnacl_irt_shim_dummy_a
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_pnacl_llc_nexe
[1130/195511:ERROR:payload.cc(233)] Could not read /opt/pop/./pnacl/pnacl_public_x86_64_pnacl_sz_nexe
[1130/195512:ERROR:payload.cc(129)] Error writing payload.json ; write result:-1 expected:1551532

fc@ntkiller2:/opt/pop.bad> ./payload       
Erreur de segmentation (core dumped)

**Comment by team-pct** [comment]
seems related to NW 
have you tried build it alone?

**Comment by Franck78** [comment]
sorry, don't know exactly what is NW. So no, no local build of it (or Popcorn).

Is the 'payload thing' relevant ?

**Comment by team-pct** [comment]
try follow instructions for building it will build a local popcorntime and download nwjs auto

**Comment by Franck78** [comment]
Oh , just saw the last suggestion !
No I did not try with nwjs auto.

But now it's kind of a reflex : I choose "No / Quit" then restart and my database is preserved. Remember 1 on 50 launches.

Still running 3.10 so I close this
