### ISSUE TITLE
Unable to cast to Chromecast

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#882]
Operating System Version:

OS X 10.14.1

Popcorn Time Version:

Jenkins build 293: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/293/

Download date:

Today

#### Expected Behaviour

Casting to Chromecast should work.

#### Actual Behaviour

Casting to Chromecast gets stuck in the Downloaded screen with a very low % number.

#### Steps to reproduce the behaviour

1. Select the episode or movie you want to play
2. Change to Chromecast in the Watch Now menu

**Comment by team-pct** [comment]
Probably Playing an unsupported format Please check

**Comment by Agusum** [comment]
No. I tried to play the same one with the latest official release and it works just fine.
