### ISSUE TITLE
Persistent datase corruption

### ISSUE THREAD

**Issue by axelfilisola** [popcorntime/popcorntime#884]
Operating System Version: Arch Linux

Popcorn Time Version: 0.3.10.0

Download date: September 9

#### Expected Behaviour

Save the bookmarks and track Watched episodes

#### Actual Behaviour

- The database gets corrupted all the time and has to be recreated.
- Cannot flag an episode as Watched, clicking either on the "eye" i con or in the "Mark as watched" do not mark it, instead, the application has to be restarted to be able to open another Movie/Serie (The mark is not saved, and the episodes are still as "unwatched")
- Once the database gets corrupted it might only display a few items, changing the order "By Title", "By year", etc. hangs the application and it just displays and empty backgroud (need to restart to show the options again).
- The dependencies are completely outdated.

#### Steps to reproduce the behaviour

Random, mark an episode as watched, add an item to the bookmark, installation of a new version, etc.

### Extra comments
This is not a rage bug submit, I have followed this application since the beginning and I really thank you guys for what  you have done.
However, this database corruption has been persistent during many years, and it is really annoying having to set all the bookmarks and watched episodes over and over.
Thanks for the great job and countless hours of fun ;)

**Comment by team-pct** [comment]
Have you tried ci.popcorntime.sh version?

**Comment by axelfilisola** [comment]
Interesting!
So much time and I was not aware of that repository.
I have tried with 3 versions from AUR: popcorntime, popcorntime-bin and
popcorntime-git.
I will give this one a try, thanks for the recommendation!
Also thanks for the prompt response.

Have a great day! :)
