### ISSUE TITLE
Unable to cast to Chromecast

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#886]
Reopening of issue #882 as the videos that I've tried to cast are castable with the stable build.

Operating System Version:

OS X 10.14.1

Popcorn Time Version:

Jenkins build 293: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/293/

Download date:

Today

Expected Behaviour
Casting to Chromecast should work.

Actual Behaviour
Casting to Chromecast gets stuck in the Downloaded screen with a very low % number.

Steps to reproduce the behaviour
Select the episode or movie you want to play
Change to Chromecast in the Watch Now menu

**Comment by team-pct** [comment]
CMD+0 and please send us more info to debug

**Comment by Agusum** [comment]
Here is the Console log: https://gist.github.com/Agusum/36a234d19695729277f3f5bcbd53b919

It got stuck here:
![image](https://user-images.githubusercontent.com/4369698/49188356-60223800-f362-11e8-9430-5142ab93b60f.png)

It happens with every episode I try to cast. Playing on my laptop works fine.

**Comment by Persei08** [comment]
look like a unsupported format(codec) issue. :/ 

Which video it is and which selected quality? thx

**Comment by Agusum** [comment]
The Big Bang Theory S12E05 480p.

**Comment by Persei08** [comment]
The Big Bang Theory S12E05 480p don't works for me for both 3.10 beta and dev build 293.
The Big Bang Theory S12E05 720p half works (no audio) for both 3.10 beta and dev build 293.

When I look at mediainfo details for S12E05 480p, it's Avi video file encoded with XVID. And it's not supposed to be supported by chromecast (unless i'm wrong).

Can you check again and confirm your 2 PT versions are from popcorntime.sh ? 
Can you also confirm you played The Big Bang Theory S12E05 480p from the series tab ?
Also can you also confirm you played The Big Bang Theory S12E05 480p via the built-in cast feature in PT ?

**Comment by Agusum** [comment]
I can confirm that the stable version is the one from popcorntime.sh too.

The casting error happens with every media that I've tried in the new build so it's not limited to that one episode specifically.

**Comment by Arazriel** [comment]
Wait a minute folks... I don't have any Chromecast ability/option in the application from the popcorntime.sh site.

**Comment by Persei08** [comment]
@Agusum, Please provide more details about the video. You can find the path of the folder were your videos are temporary saved in advanced settings > "cache directory". There, check videos files details (container, codecs) with vlc in tools menu > "Codec Information" tool or with mediainfo app.

**Comment by Agusum** [comment]
![image](https://user-images.githubusercontent.com/4369698/49480522-e20cd800-f81e-11e8-8f0f-76365f2f3b52.png)
I just realised that the error is not necessary on casting itself but on even playing the file as you were saying, as it now doesn't seem to work in the newest build either. The release version can play it correctly though.

**Comment by team-pct** [comment]
Chromecast does not support xvid sorry mate ,
as i understand well its not popcorn time related , i can close this issue?

**Comment by Agusum** [comment]
To reiterate: Playing this file in the current stable Popcorn Time release **works fine**. So does casting it.

Therefore I believe it's a regression not being able to play it using the current build.

**Comment by Persei08** [comment]
@Agusum, what you tell us sound impossible. The chromecast device have it's own built-in player and capabilities and don't support xvid codec and/or avi container (and it isn't related to the fact the PT built-in player could play the file or not).

I think, maybe you're current PT version isn't from popcorntime.sh and play another file which is compatible with chromecast or maybe you cast to chromecast via VLC or another soft (which re-encode the video on the fly to make it compatible with chromecast).

**Comment by lg188** [comment]
I've been having issues with casting to my chromecast as well. Building it with the previous video.js statement in package.json it worked. (`7.x.x`) I'm not sure if this is exactly the same issue, but it gave me errors about not finding the right stream.

**Comment by Persei08** [comment]
@lg188 please provide more details: OS, PT version, Chromecast model/version, movie name/episode number, selected quality and eventually console output (F12 key> "console" tab. If needed you should clean log from IPs and personal details). 

We can always spend time to try to reproduce the issue with random PT version and movies/episodes and parameters, but at least knowing the movie name/episode number, and PT version, we will know we don't waste time testing random ones which will maybe not allow us to reproduce your issue. So please, give us a bit more of your time and tell us. It could really help to understand things quicker.

Thx

**Comment by lg188** [comment]
@Persei08 Never mind, it seems that the libffmpeg.so provided with the build isn't as compatible as my live build. By renaming it and falling back to my local ffmpeg it worked. It couldn't decode the stream. I'd suggest making it possible to build with a local ffmpeg?

**Comment by kiriles90** [comment]
@Persei08 close this please
