### ISSUE TITLE
Show posters are zoomed in

### ISSUE THREAD

**Issue by ChrisAlderson** [popcorntime/popcorntime#89]
The posters for shows are zoomed in. I believe it has something to do with [this line](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/styl/views/show_detail.styl#L41). Changing the `background-size` value from `auto` to `134px` seems to fix it.

Thanks in advance.

**Comment by raphcool12** [comment]
thanks you  @ChrisAlderson to have moved the issue at the right place for me sorry for my mistake :)

**Comment by team-pct** [comment]
Fixed
