### ISSUE TITLE
[Help Needed] Player Skin

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#898]
- Video.Js Skin https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/styl/views/player.styl and https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/styl/views/videojs.styl need be upgraded to the new Video JS 7 
- Video.JS new Skin example https://github.com/VD39/videojs-iplayer-skin-1
- Video.js small documentation https://docs.videojs.com/tutorial-skins.html

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
