### ISSUE TITLE
Thumbnail not showing, 500 internal error

### ISSUE THREAD

**Issue by igoronesimo** [popcorntime/popcorntime#899]
Operating System Version:
windows  10

#### Expected Behaviour
show movie thumbnails

#### Actual Behaviour
doesn't show movie thumbnails

#### Steps to reproduce the behaviour
1.open popcorn
2. go to movie section

popcorn time is not showing movie thumbnails beause it is trying to get them from https://assets.fanart.tv instead of https://fanart.tv wich causes an internal error 500.

**Comment by tr0yspradling** [comment]
This is affecting me as well. Only some of them are loading.

**Comment by tr0yspradling** [comment]
Seems to be working again, for me at least.

**Comment by robert-nol-zz** [comment]
Still not working, still loading from assets...Is there a way to manually change https://assets.fanart.tv to https://fanart.tv because without assets loading images

**Comment by igoronesimo** [comment]
> Still not working, still loading from assets...Is there a way to manually change https://assets.fanart.tv to https://fanart.tv because without assets loading images

I don't think so :( we'll have to wait...

**Comment by iamtakingiteasy** [comment]
Apparently assets.fanart.tv introduced some form of rate-limiting, after N requests in some time unit, returning 503. After a few seconds without requests, thumbnail becomes available. But popcorntime is not re-trying failed thumbnail requests, thus most of thumbnails in app are not displayed.
