### ISSUE TITLE
[Feature Request] Update Executables

### ISSUE THREAD

**Issue by zero77** [popcorntime/popcorntime#902]
Operating System Version:

all
Popcorn Time Version:

3.10 

At the moment the newest executable on the website is, 3.10 which was released on the 31 Oct 2016.

There has been many changes sins then so, can you please update all the executables on the popcorntime.sh website.

Thanks

**Comment by team-pct** [comment]
Once we have a stable version on development we will

**Comment by zero77** [comment]
@team-pct 
Is there no developer executable currently available, for users to try.

**Comment by team-pct** [comment]
ci.popcorntime.sh

**Comment by zero77** [comment]
@team-pct 
Thanks althow, what about for android or windows.

**Comment by team-pct** [comment]
https://ci.popcorntime.sh for windows android linux mac ....

**Comment by zero77** [comment]
thanks
