### ISSUE TITLE
Frame issues - Cannot see Close, Maximise and Minimise buttons

### ISSUE THREAD

**Issue by flumpiey** [popcorntime/popcorntime#903]
Operating System Version:
Windows 10 Home

Popcorn Time Version:
Stable release #352

Download date:
2018 - 12 - 05

#### Expected Behaviour
Show the correct window frame buttons

#### Actual Behaviour
The Buttons Glitch

#### Steps to reproduce the behaviour
Open PopcornTime

![image](https://user-images.githubusercontent.com/15123171/49500521-8f143e80-f879-11e8-95c7-6fe5a069577b.png)

![image](https://user-images.githubusercontent.com/15123171/49500535-989da680-f879-11e8-9475-b9134e49261f.png)

**Comment by team-pct** [comment]
Can you switch to Default theme and tell us if same problem or just theme related issue

**Comment by team-pct** [comment]
Same as #906 906

**Comment by flumpiey** [comment]
It happens with all themes. It has been a recurring bug since # 340

![image](https://user-images.githubusercontent.com/15123171/49572992-9ef95480-f945-11e8-81bd-c00120dc8b66.png)

**Comment by team-pct** [comment]
Can you give a try to https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/358 ?

**Comment by flumpiey** [comment]
I have. I did a clean install. Same issue.

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/frame-issues-cannot-see-close-maximise-and-minimise-buttons/97
