### ISSUE TITLE
Unable to export or Import Database

### ISSUE THREAD

**Issue by flumpiey** [popcorntime/popcorntime#904]
Operating System Version:
Windows 10 Home

Popcorn Time Version:
Jenkins version # 352

Download date:
Today 2018 - 12 - 05

#### Expected Behaviour
I expected to be able to import, export and change location of the database.

#### Actual Behaviour
On selecting any of the options the windows explorer opens, but only the option to open a folder is given, and when you try to open an old database it fails.

#### Steps to reproduce the behaviour

1. Go to Advanced Settings
2. Click Import ot Export or the folder button
3. Click open on Explorer and watch it fail

**Comment by team-pct** [comment]
Yes normal , new NW.js dont allow the use of node-fdialog we will look into that

Thank you

**Comment by flumpiey** [comment]
Thank you, You guys are doing great work!

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/359/
Should fix that   6a4c861  
Let me know

**Comment by reddo** [comment]
359 has not fixed this, neither did 360 :(
(win 10 64 bit)

**Comment by team-pct** [comment]
Can you explain your not fixed ? 
Any error ?
EDIT : Working very well on MAC osx

**Comment by reddo** [comment]
@team-pct 

Clicking on `Import Database` shows an error like this:
![annotation 2018-12-06 160859](https://user-images.githubusercontent.com/1180060/49589138-4475ed80-f971-11e8-9c22-3731b9bfcd97.jpg)

Clicking on any of the folder icons just opens a file explorer and clicking inside the actual input for the database does nothing.

**Comment by team-pct** [comment]
You have to select the folder or the zip file first

**Comment by team-pct** [comment]
We are trying to draw it better

**Comment by reddo** [comment]
That's what I'm saying, there's no way to select the file first. The folder icons just open a file explorer, and you can't select a file there. Not for import nor export.
(Sensitive info cropped)
![annotation 2018-12-06 162002](https://user-images.githubusercontent.com/1180060/49589852-1db8b680-f973-11e8-893e-10f77a110fdf.jpg)

**Comment by reddo** [comment]
Got the new build. Importing and exporting seem to work in 361.

**Comment by team-pct** [comment]
Awesome , thank you for your help

**Comment by reddo** [comment]
Let me know how else I can help. I've tried running the app locally on my windows, from `master`, but no luck. I have node/npm and yarn installed, but `yarn install` hangs and fails. Any detailed instructions on how to get it to run?

**Comment by team-pct** [comment]
git checkout development
yarn install
gulp build
gulp run

**Comment by reddo** [comment]
Tried `yarn install` and it hangs at this step:

![annotation 2018-12-06 195247](https://user-images.githubusercontent.com/1180060/49602190-86faf280-f990-11e8-953a-9b3445347e7b.jpg)

**Comment by team-pct** [comment]
Let it hang yet its downloading dev deps 
you can still do npm install instead of yarn install

**Comment by reddo** [comment]
I've let it go for more than an hour and it never finished.

**Comment by team-pct** [comment]
npm install instead or just ctrl+c then retry

**Comment by team-pct** [comment]
any more tester can confirm this issue can be closed ?
