### ISSUE TITLE
Feature request: soundtrack languages indicator and filters

### ISSUE THREAD

**Issue by narcisgarcia** [popcorntime/popcorntime#905]
Operating System Version: For all platforms

Popcorn Time Version: Next version

#### Expected Behaviour
Videos catalog / movies list / home: Dropdown list for each item, to select between available soundtracks (en, es, fr, ...).

Preferences tab: Soundtracks section to select between: List all videos (default) and List only videos with available soundtrack in X, Y, Z languages. Both modes with dropdown list of preferred language(s) to indicate and play by default. Default configuration should pre-select user's language.

Butter player: Dropdown list as a soundtrack switch for current file.
...

#### Actual Behaviour
No movie languages support in version 0.3.10

**Comment by team-pct** [comment]
have you tried https://ci.popcorntime.sh version ? we have that already the issue would be with the sources

**Comment by narcisgarcia** [comment]
Is that a derivative? Some versions and forks map anywhere?
Neither "About" nor license information there.

**Comment by narcisgarcia** [comment]
Which one is the real or official 0.3.10 version of Popcorn Time?

**Comment by team-pct** [comment]
ci version is the dev version its listed everywhere ...

**Comment by narcisgarcia** [comment]
I've just tried ci/dev version, and there is Subtitle and Audio Language selector at movie sheet.
I think this issue should be reopened because I was asking for more features, such as filters and auto-selection.

**Comment by narcisgarcia** [comment]
Adding related features to request:
1. Subtitles preferences should allow to enable more than one language to be automatically enabled for movie subtitles in case of preferred language isn't available at soundtracks.

2. "List all videos" and "List only videos..." will be better in three options:
a) List all videos
b) List only videos with preferred audio or subtitle languages
c) List only videos with preferred audio languages

**Comment by team-pct** [comment]
I think you are not understanding we do not have the resources to implement new features you are welcome to contribute

**Comment by narcisgarcia** [comment]
Yes, I understand and I assume that feature request is not an order but a wish that can be as a future "to do". Filtering configurations is very important for usability out of Elisabeth and Donald kingdoms, and something like that can really increase number of users and contributors.
You seem to be saying "This cannot be done at short term", okay.

**Comment by narcisgarcia** [comment]
Maintaining this issue closed means also to not be a possible feature for the future.

**Comment by narcisgarcia** [comment]
Build #363 (Dec 30, 2018 3:53:15 PM) breaks when trying to play a video (any player, on Debian 10 amd64 Gnome).
Only Popcorn-Time-0.3.10 from home website plays videos.
