### ISSUE TITLE
Title Bar Buttons

### ISSUE THREAD

**Issue by 1337-537h** [popcorntime/popcorntime#906]
Operating System Version:
Windows 10 x64 1809 17763.134

Popcorn Time Version:
Build #356 win64

Up right corner https://i.imgur.com/2LdNbOm.gifv
That appears almost in every build after 279 till now.

**Comment by team-pct** [comment]
I will try to look into that as soon as i get hand of a windows machine

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/358

**Comment by 1337-537h** [comment]
Unfortunately same issue with 358 with clean install.

**Comment by team-pct** [comment]
Ok , it will have to wait having a proper windows machine ,
if you can find out why meanwhile don't hesitate to PR

**Comment by reddo** [comment]
Same issue with build  360. 

Maybe try a virtual machine with Virtualbox?

**Comment by team-pct** [comment]
No more ressource on the machine , NWJS building is already running

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/title-bar-buttons/95
