### ISSUE TITLE
App won't play/steam any movie or TV show

### ISSUE THREAD

**Issue by Syborg49** [popcorntime/popcorntime#907]
Operating System Version:
<Ubuntu 18.10>

Popcorn Time Version:
<Build #360 (Dec 6, 2018 1:41:36 PM) from ci.popcorntime.sh>

Download date:
< 20:00 GMT+6 12/6/2018>

#### Expected Behaviour
<Wanted to stream a movie or a TV show>
...

#### Actual Behaviour
<App doesn't play any of the movie or TV show & instead shows [this](https://ibb.co/sKWt3Wc) message>
...

#### Steps to reproduce the behaviour

1. Open popcorn time
2. Select any movie or TV show to play
3. It won't play

**Maybe I'm an idiot but is the subtitle option not working? I can't find any subtitle & it shows "Caption off" & I can't even use custom ones.

**Comment by reddo** [comment]
Same here. 

Win 10 x64

![annotation 2018-12-06 182556](https://user-images.githubusercontent.com/1180060/49597098-6a58bd80-f984-11e8-85a6-503e1b63dd58.jpg)

Not all movies, but some. It opens with VLC.

**Comment by team-pct** [comment]
Problem of codec , the NW.js version for DEV have no all codecs , 
Custom Subtitle is broken for now on the DEV
Use Default Subtitles on the Settings 
- Use VLC for watching

**Comment by team-pct** [comment]
OK we have included a nwjs 0.33.4 with Basic codecs  ( H264 ) which will let you watch using popcorn time let us know if it work

**Comment by reddo** [comment]
Just tried it:
- Supergirl 402 480p doesn't play, 720p plays without picture, just sound (guessing it's mkv, which is fine);
- Supergirl 403: 480p doesn't play, 720p video plays with no sound.

**Comment by team-pct** [comment]
Movies?

**Comment by reddo** [comment]
Tried a few movies, they worked.

**Comment by team-pct** [comment]
good for testing i guess
