### ISSUE TITLE
Missing thumbnails/buttons

### ISSUE THREAD

**Issue by reddo** [popcorntime/popcorntime#908]
Operating System Version:
Windows 10 x64

Popcorn Time Version:
0.3.10 build 361

Download date:
12.01.2018

#### Expected Behaviour
PopcornTime shows all thumbnails and info about movies/series.

#### Actual Behaviour
Most of the thumbnails are missing, it's showing the default thumbnails for them.
![annotation 2018-12-06 181439](https://user-images.githubusercontent.com/1180060/49596579-53659b80-f983-11e8-9fd1-8fb4734fd9a6.jpg)

Opening some of the favourites brings up a screen with missing info/buttons:
![annotation 2018-12-06 181943](https://user-images.githubusercontent.com/1180060/49596662-8740c100-f983-11e8-81f3-ef27b05d33ba.jpg)

**Comment by team-pct** [comment]
Fanart.tv is down 

https://assets.fanart.tv/fanart/movies/335983/moviebanner/venom-5bb7c913dec8c.jpg error 500

**Comment by Preisschild** [comment]
@team-pct Is there a possibility to directly use the imdb pictures, like many other movies do?

**Comment by team-pct** [comment]
we use them all but nothingg is perfecttt
