### ISSUE TITLE
Movie Tiles / Images Missing

### ISSUE THREAD

**Issue by SeriouslyMaD** [popcorntime/popcorntime#911]
Operating System Version:
MacOS Mojave 10.4.2

Popcorn Time Version:
Build #361

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by team-pct** [comment]
Metadata provider is down it will be back without any action from our part

**Comment by SeriouslyMaD** [comment]
Thank you. Wasn't aware of how it functioned. Thanks for all you guys do! :)
