### ISSUE TITLE
Fonts looks ugly on LinuxMint

### ISSUE THREAD

**Issue by nicolasegp** [popcorntime/popcorntime#913]
#### Operating System Version:
LinuxMint 19 XFCE

#### Popcorn Time Version:
0.3.10-0

#### Download date:
December 01, 2018

#### Actual Behaviour
fonts looks ugly on LinuxMint (I tested in Manjaro KDE and no problem)

#### Steps to reproduce the behaviour
I installed popcorn-time manually

1. `mkdir /opt/popcorn-time`
2. `wget https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-64.tar.xz`
3. `tar -xf Popcorn-Time-0.3.10-Linux-64.tar.xz -C /opt/popcorn-time/`
4. `sudo ln -sf /opt/popcorn-time/Popcorn-Time /usr/bin/popcorn-time`

#### Screenshot
![img1](https://user-images.githubusercontent.com/138731/49677315-993e6480-fa54-11e8-9a6a-81306efdff48.png)

![img2](https://user-images.githubusercontent.com/138731/49677341-b6733300-fa54-11e8-976c-d7af2033b119.png)

**Comment by team-pct** [comment]
hmmm are they loading ?

**Comment by nicolasegp** [comment]
![image](https://user-images.githubusercontent.com/138731/49688499-a5283600-fae9-11e8-87ba-7cd10b470a3d.png)

@team-pct  Seeing the application inspector I see that it has the same problem, it seems to be a problem of the instance of the web emulator.

Is there any way to update? I already tried installing chromium but it didn't work.

**Comment by nicolasegp** [comment]
Yeah, it's a NW.Js problem.
 Do you know any solution? :(

![Screenshot](https://user-images.githubusercontent.com/138731/49689577-6c905880-faf9-11e8-9960-0ce2cc7bb815.png)

**Comment by team-pct** [comment]
Try another nwjs binary

**Comment by nicolasegp** [comment]
Where to download it?
Which files should I replace?

**Comment by nicolasegp** [comment]
How to update NW.js binary in Linux??

**Comment by PTony** [comment]
For me this issue was fixed at dev build 296 when nwjs was updated to version 35

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/fonts-looks-ugly-on-linuxmint/94
