### ISSUE TITLE
Popcorn Time for Mac OS stopped working properly

### ISSUE THREAD

**Issue by Rebellious300** [popcorntime/popcorntime#914]
#### Operating System Version:
OS X 10.14.2

#### Popcorn Time Version:
0.3.10

#### Download date:
12-7-2018

#### Expected Behaviour
Display every image cover for the available movies and shows. Play each video when "Watch Now" is clicked.

#### Actual Behaviour
Plenty of the image covers don't display, and none of the videos play, even if the health status is on green. When the "Watch Now" button is clicked, the screen changes to the "Cancel" button and stays there without doing anything.

#### Steps to reproduce the behaviour
- I have reinstalled the app. 
- Restarted the computer. 
- Clear the cache. 
- Change the VPN server. 
- Connect without VPN. 
- Connect using different wifi connections.

<img width="1245" alt="screen shot 2018-12-08 at 3 06 59 am" src="https://user-images.githubusercontent.com/45708310/49683664-64eb9800-fa96-11e8-9e1f-bf01cb37b21b.png">

**Comment by team-pct** [comment]
- Cover issue is from Metadata provider we are sorry for that ! 
- For Peers try ci.popcorntime.sh version it should get more peers
