### ISSUE TITLE
JSON-RPC API over HTTPS

### ISSUE THREAD

**Issue by stevepiron** [popcorntime/popcorntime#917]
Hi,

I'm developing a cross-browser remote, which I'd ultimately turn into a Progressive Web App. Locally, everything works fine (remote run from my computer) but when published to GitHub Pages, I'm getting the following error:

```
(index):233 OPTIONS https://192.168.1.20:8008/ net::ERR_CONNECTION_CLOSED
```

I've recently made a change in the Javascript to run the XHR over HTTPS since GitHub Pages have SSL enabled.

Demo: https://stevepiron.github.io/remote/

**Comment by team-pct** [comment]
hmmm what is the point of SSL on LAN ?? remove https:// on Local network you dont need them 
so you should request directly via http

**Comment by team-pct** [comment]
also How github gonna connect to your LAN iP?? you should or give him your public ip and here you can use https

**Comment by stevepiron** [comment]
Hi, thanks for replying.

The thing is I'd like to publish this app and let people install it on their home screen. To do so, it needs to be hosted online and must be served from a secure origin (see https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https).

For now, I got it to work when hosted online on a non-secure origin, but this does not enable users to install the app and launch it full screen just like any other native app. I hope you get my point.
