### ISSUE TITLE
The popcorn app shows dark screen(No interface is visible) after opening

### ISSUE THREAD

**Issue by neerajyadavs** [popcorntime/popcorntime#918]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10.0

Download date:
6th Aug 2018

#### Expected Behaviour
Supposed to show the interface after opening
...

#### Actual Behaviour
Shows a black screen area instead of the app interface
...

#### Steps to reproduce the behavior
Just open in my system(Lenovo ThinkPad, windows 10)

**Comment by team-pct** [comment]
where you downloaded your version?

**Comment by neerajyadavs** [comment]
@team-pct from https://popcorntime.sh, the same version works perfectly on a different laptop.

**Comment by team-pct** [comment]
F12 when you run popcorn time and get the dark interface to show console to under better your problem

**Comment by neerajyadavs** [comment]
@team-pct even the console is empty, after another click the console also goes from white to black.
Attaching screenshot:
![popcorntimescreen](https://user-images.githubusercontent.com/24876639/49746759-e24a1f00-fcc7-11e8-86e1-c2979fb233db.png)
Here, the black screen in the background is the popcorn time interface and white screen is the console.

**Comment by team-pct** [comment]
You should uninstall popcorn time and go look for cache folder and remove it and retry

**Comment by neerajyadavs** [comment]
I have uninstalled and reinstalled several times, where can I find the cache folder?

**Comment by team-pct** [comment]
Not sure but you can check on another windows if you have go to settings > Advanced settings it will give you a path it should be almost the same

**Comment by neerajyadavs** [comment]
Deleted the database folder (Cache folder was already deleted I suppose with the uninstallation) and reinstalled, to no avail. Still the same black screen.
Can it be some other issue?

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/ get the zip for your windows and try without install

**Comment by neerajyadavs** [comment]
Nope, still the same, old black screen, but I did see windows firewall blocking it and I allowed it. Even checked in the firewall settings and popcorn-time.exe is allowed there as well

**Comment by team-pct** [comment]
I still have no idea how to help better , same happening with stable version and ci version ?

**Comment by neerajyadavs** [comment]
0.3.10-0 for Win 10 and the zip versions both have the same issue.

**Comment by Persei08** [comment]
Any antivirus (or security soft) which could conflict and block PT ?

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/the-popcorn-app-shows-dark-screen-no-interface-is-visible-after-opening/105
