### ISSUE TITLE
[5311:0311/175341:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by waldyd** [popcorntime/popcorntime#92]
Version:  Popcorn-Time-0.3.9-Linux-32 (fedora 23)
Download date:  march 11
#### Expected Behaviour

Download series and movies
#### Actual Behaviour

The following is being prompted:

[5311:0311/175341:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
#### Steps to repoduce the behaviour

1. Click on movies/series tab
2. Click on any movie/serie
3. ...

**Comment by ademar111190** [comment]
It seems the same problem of issue [49](https://github.com/popcorn-official/popcorn-desktop/issues/49)
