### ISSUE TITLE
Movies covers not being displayed

### ISSUE THREAD

**Issue by rodrigopires** [popcorntime/popcorntime#920]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10

Download date:
December 10, 2018

#### Expected Behaviour
All movies covers to be displayed correctly

#### Actual Behaviour
Most movies covers are not being displayed (print attached)

#### Steps to reproduce the behaviour
1. Open the program :)

![popcorn-movies-covers](https://user-images.githubusercontent.com/1280409/49731996-40451b00-fc64-11e8-931b-39043019d9aa.PNG)

**Comment by user8614** [comment]
> Operating System Version:
> Windows 10
> 
> Popcorn Time Version:
> 0.3.10
> 
> Download date:
> December 10, 2018
> 
> #### Expected Behaviour
> All movies covers to be displayed correctly
> 
> #### Actual Behaviour
> Most movies covers are not being displayed (print attached)
> 
> #### Steps to reproduce the behaviour
> 1. Open the program :)
> 
> ![popcorn-movies-covers](https://user-images.githubusercontent.com/1280409/49731996-40451b00-fc64-11e8-931b-39043019d9aa.PNG)

use the vpn

**Comment by rodrigopires** [comment]
@user8614 not using the vpn is what's causing this problem? I never used and yet the covers always were displayed correctly...

**Comment by team-pct** [comment]
Fanart provider was down it should be all ok now

**Comment by rodrigopires** [comment]
It seems a little bit better at this moment, but a few covers are still not being loaded.

I noticed this problem started happening a few days ago when I uninstalled a previous version (actually a different port) of Popcorn on my machine, so was I wondering if this problem could be because of some internal folder or file was deleted inappropriately during the uninstall...
