### ISSUE TITLE
BS Player Option

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#921]
Can you please add an option to watch the movies with BS Player

**Comment by team-pct** [comment]
Hello Gkid94 , 
I would love to add BSplayer option but they do not have any OSX version to test on , you are welcome to submit changes on https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js

**Comment by GKid94** [comment]
What about Windows

**Comment by team-pct** [comment]
Let see if someone have windows willing to submit a PR for it

**Comment by GKid94** [comment]
I have Windows 10

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/bs-player-option/96
