### ISSUE TITLE
Sound doesn't play well

### ISSUE THREAD

**Issue by Heusdens97** [popcorntime/popcorntime#923]
If I select some tv show, it doesn't always play sound.

Operating System Version:
MacOS Mojave 10.14.1

Popcorn Time Version:
Version with latest commit 2391505f129e0b591c0f13db1613afb867c4324e "Create Jenkinsfile"

Download date:
Tuesday 11/12/2018

#### Expected Behaviour
It should play the sound of the tv show.

#### Actual Behaviour
It didn't always play the sound of the tv show.

#### Steps to reproduce the behaviour

1. Open PopcornTime,
2. select some tv show,
3. play.

**Comment by team-pct** [comment]
It doesnot have all codecs yet .. for enjoying TVSHOW ( not testing ) you should for now use external player like VLC
