### ISSUE TITLE
Only one subtitle

### ISSUE THREAD

**Issue by Heusdens97** [popcorntime/popcorntime#924]
PopcornTime only shows one subtitle, which is the default subtitle from settings. It also shows a black background, which you unfortunately can't remove? You also cannot click on 'custom' to select a .srt file.

Operating System Version:
MacOS Mojave 10.14.1

Popcorn Time Version:
Version with latest commit 2391505f129e0b591c0f13db1613afb867c4324e "Create Jenkinsfile"

Download date:
Tuesday 11/12/2018

#### Expected Behaviour
It should show all the possible subtitles.

#### Actual Behaviour
It only shows one subtitle.

#### Steps to reproduce the behaviour

1. Open PopcornTime,
2. select some tv show,
3. play,
4. click on CC.

<img width="110" alt="popcorntime" src="https://user-images.githubusercontent.com/17343694/49837531-f7e24600-fda6-11e8-8256-dc361a235b2d.png">

**Comment by team-pct** [comment]
Work in progress , Subtitles are moved  @ Movie Detail you can choose from there , for TVShow ( Settings and choose Default Subtitle) 
We moved to Video.js 7 so some old function are deprecated like SRT reading

**Comment by Nak99999** [comment]
> Work in progress , Subtitles are moved @ Movie Detail you can choose from there , for TVShow ( Settings and choose Default Subtitle)
> We moved to Video.js 7 so some old function are deprecated like SRT reading

Same problem and I can't add custom subtitles when there is no subtitles at my language.
Click the "custom" button and nothing show up
Already choosed in Default Subtitle

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
