### ISSUE TITLE
Fav Menu doesn't work

### ISSUE THREAD

**Issue by Proshat** [popcorntime/popcorntime#925]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
sometime in 2016

#### Expected Behaviour
to show a list of movies I added to favs.
...

#### Actual Behaviour
it only shows 4 of almost 20 starting a week ago...

#### Steps to reproduce the behaviour

1. Lunch Popcorn time
2. when movies load, click on the heart button
3. the list wont show!
![image](https://user-images.githubusercontent.com/45858055/49961261-81b91d00-ff27-11e8-9761-05ed2c9bb4d0.png)

**Comment by team-pct** [comment]
have you tried the last ci.popcorntime.sh if the bug is still here?

**Comment by Proshat** [comment]
It persists. I tried removing a fav and noticed that it always show only 5 favs at a time.

**Comment by team-pct** [comment]
<img width="2076" alt="screen shot 2018-12-18 at 09 28 44" src="https://user-images.githubusercontent.com/17107280/50141256-56c42580-02a7-11e9-9a13-828c487f6e41.png">
I am not able on build 362
