### ISSUE TITLE
[Solved] Trakt connection doesn't work

### ISSUE THREAD

**Issue by Gliscor** [popcorntime/popcorntime#930]
Operating System Version:
Windows 7 Home Premium 64 bits

Popcorn Time Version:
0.3.10 beta - HEAD 28112f67

Download date:
December 17, 2018

#### Expected Behaviour
Connected to Trakt account
...

#### Actual Behaviour
Does not connect to Trakt
...

#### Steps to reproduce the behaviour

1. Open "Settings"
2. Click the "Connect to Trakt" button 
3. Enter your Trakt username and password and click "YES" to authorize Butter to use your account
4. Wait a few seconds while the blue circle loads and then the "Connect to Trakt" button doesn't change to "Connected to Trakt"

**Comment by team-pct** [comment]
It was fixed after that you can test on ci.popcorntime.sh or build your own branch of Dev

**Comment by Gliscor** [comment]
Downloaded build #362. Issue is fixed now, connection to Trakt.tv works as intended. Thanks!
