### ISSUE TITLE
Opening a video always fails

### ISSUE THREAD

**Issue by ItachiSan** [popcorntime/popcorntime#936]
Operating System Version:

Antergos (ArchLinux), latest packages installed

Popcorn Time Version:

0.3.10, branch: *development*, commit: `584d9b`

Download date:

The source code was downloaded and built today, using:

    npm install
    gulp build

#### Expected Behaviour

When running the app in the *build* folder, I was expecting the video to run as intended.

#### Actual Behaviour

The video does not run; the app reports *No supported stream* and in the terminal the message *MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS* appears.

#### Steps to reproduce the behaviour

1. Have an updated ArchLinux environment.
2. Download this repository.
3. `npm install`
4. `gulp build`
5. `./build/Popcorn-Time/linux64/Popcorn-Time`

**Comment by team-pct** [comment]
Yes sadly most of the codecs are not already included on the dev version of nwjs , all movies should work correctly but TV show you will have some issues of codecs

**Comment by ItachiSan** [comment]
Hey @team-pct no worries, I have found BTW an issue in `gulpfile.js` which unpacks FFMpeg in the wrong place.
I have made a patch for my ArchLinux package, but now I will create a pull request here, as it would be better.

**Comment by ItachiSan** [comment]
The related pull request is: #938

**Comment by alecmerdler** [comment]
Still seeing this issue on `development@1537575b4130ba603674a962f3f4ace6067e7be6`.

**Comment by alecmerdler** [comment]
Strange that the exit code is success (`Popcorn-Time exited with code 0`).

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
