### ISSUE TITLE
App Update Notification

### ISSUE THREAD

**Issue by sweatycorndog19000** [popcorntime/popcorntime#937]
Please add an notification in the app to notify the person that a new version of the app is available. This way users will not need to sign up to the email service to notify them and not hand over their email address.

**Comment by team-pct** [comment]
We have already an updater notification when the an update is available , handing over AN email is not mandatory , some people wanna be updated by email and we give them this option

**Comment by bdrnglm** [comment]
> We have already an updater notification when the an update is available , handing over AN email is not mandatory , some people wanna be updated by email and we give them this option

I'm sorry but I don't see where are the _update notifications_.
I used to use the app we can download on [popcorntime.sh](https://popcorntime.sh) which seems to be a build from 2016.
I built the latest version of the app from the _development_ branch which has been uploaded 3 months ago I guess, and I didn't see any place where it's notified that there is a new version of the app available.
I looked for an option to look for an update and fetch it but didn't find any in both versions.

Is that update notification option in the app itself or did I just misunderstand?

**Comment by team-pct** [comment]
@bdrnglm are you sure you are reading the code of the app? , 2016 was the last stable version for dev version you can use ci.popcorntime.sh , we do not notify Dev progress only stable version once a we release one you will get notification , 
I guess i have to show you 
Desktop : https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/updater.js
Android : https://github.com/popcorn-official/popcorn-android/blob/development/mobile/src/main/java/butter/droid/activities/base/ButterBaseActivity.java#L65
