### ISSUE TITLE
voice and picture don't match

### ISSUE THREAD

**Issue by rainh20** [popcorntime/popcorntime#940]
Operating System Version:

Popcorn Time Version:
0.3.10

Download date:
1-25-2017

#### Expected Behaviour
voices match picture
...

#### Actual Behaviour
voices don't match picture
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by lg188** [comment]
Does this happen to a particular movie, or all of them?

**Comment by Persei08** [comment]
Operating System ?
Movie ?

**Comment by EndiM** [comment]
This happens to me too, audio and video get out of sync as the movie or series is playing and it gets more distinct as the time passes. Restarting player returns it to normal until it get out of sync again.
Operating System: Windows 10
Version: 0.3.10
All movies and series.

**Comment by Persei08** [comment]
Does it also do that when you play in VLC ?

**Comment by EndiM** [comment]
@Persei08 No, VLC is ok, just the internal player.

**Comment by ghost** [comment]
This also happens to me. have to pause the video, wait 30 seconds and resume again.

**Comment by Persei08** [comment]
@vrgomes On with OS, windows 10 too ?

**Comment by ghost** [comment]
Hi yes. Happens on a Amd desktop and a Intel notebook.
Both win 10 latest updates.

Greetings.

**Comment by ghost** [comment]
The issue is now closed, but with the internal player the issue still occurs :(

Greetings.

**Comment by team-pct** [comment]
Give Example so that we can test,
are you using the last version?

**Comment by ghost** [comment]
Just checked and was using the standard 0.3.10
Will test this week on the latest 0.4.1

Greetings.
