### ISSUE TITLE
Option to choose a custom subtitle for Chromecast

### ISSUE THREAD

**Issue by Dulb26** [popcorntime/popcorntime#942]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.3.9 - Build 116

Download date:
06/26/2016

Expected Behaviour
Let me choose a custom subtitle (.srt) when playing on Chromecast.

Actual Behaviour
I Can only choose custom subtitles when playing in Butter player or external players like VLC.

Steps to reproduce the behaviour
1.Open PopcornTime
2. Choose a Movie/Serie
3. Choose Chromecast
4. (Don't) Choose custom subtitles

**Comment by osrl** [comment]
Or any dlna device

**Comment by kiriles90** [comment]
@Persei08 duplicate of #1540 , close please
