### ISSUE TITLE
no casting

### ISSUE THREAD

**Issue by Tecko71** [popcorntime/popcorntime#944]
Operating System Version
Windows 10

Popcorn Time Version:
#363

Download date:
6-1-2019

#### Expected Behaviour
cast to chromecast (shield) should work

#### Actual Behaviour
not able to cast to shield (build in chromecast)
App hangs on connecting

**Comment by Tecko71** [comment]
I restarted the app. App is connecting but than hangs on streaming.

**Comment by Persei08** [comment]
Seem like this issue happen when the video format isn't supported by the chromecast.

As a workaround you can play with VLC and select you chromecast as the renderer in VLC menus. (VLC should transcode on the fly to a compatible format)

**Comment by kiriles90** [comment]
@Persei08 duplicate, close please
