### ISSUE TITLE
How can i view the movie(downloaded from popcorn time) in my downloads

### ISSUE THREAD

**Issue by haroon957** [popcorntime/popcorntime#946]
Operating System Version:
<! Windows 10-->

Popcorn Time Version:

3.10
Download date:

3days ago
#### Expected Behaviour

...i am using popcorn time from past 4 to 5 years. It used to save th movies/tv series in the downloads folder,but now it doesn't happen.

#### Actual Behaviour

... Does not save the content

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by EndiM** [comment]
@haroon957 Did you check your cache directory is setup correctly in advanced settings?

**Comment by kiriles90** [comment]
@Persei08 not an issue, close please
