### ISSUE TITLE
Cyrillic subtitles are unreadable

### ISSUE THREAD

**Issue by Sh1d0w** [popcorntime/popcorntime#948]
Downloaded https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/ for macOS (the latest build from the CI for macOS is broken).

When loading a Bulgarian subtitle it seems they don't get properly decoded, and symbols are unreadable. Could be related to the font used for the subtitles.

Old version of popcorn player never had this problem.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
