### ISSUE TITLE
latest CI build not running on mac

### ISSUE THREAD

**Issue by Vidhin05** [popcorntime/popcorntime#949]
Operating System Version:

OS X 10.14.2

Popcorn Time Version:

0.3.10 Build 363 

#### Actual Behaviour

App does not open, showing that app is damaged or incomplete

#### Steps to reproduce the behaviour

1. https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/363/
2. click on osx zip or tar link
3. try running app

**Comment by team-pct** [comment]
Right Click and then click open to confirm opening , please use the .tar.xz as the zip has reported being having issues

**Comment by Sh1d0w** [comment]
@team-pct same problem with .tar.xz, after extracting the app is damaged

**Comment by Vidhin05** [comment]
@team-pct same problem with .tar.xz, after extracting the app is damaged. Also, 4mb seems too small even for a .tar.xz file.

**Comment by davidosullivan** [comment]
same here

**Comment by Vidhin05** [comment]
@team-pct Any updates to this?

**Comment by team-pct** [comment]
Try last build
