### ISSUE TITLE
Crashes when clicking play on a movie - Fedora 29

### ISSUE THREAD

**Issue by Simon-Davies** [popcorntime/popcorntime#951]
Operating System Version:
Fedora 29

Popcorn Time Version:
Latest version from git

Download date:
12/01/2019

#### Expected Behaviour
The movie should play

#### Actual Behaviour
The app crashes

#### Steps to reproduce the behaviour
Click play on any movie
App crashes

**Comment by AndrewNelis** [comment]
Same issue as #956

**Comment by kiriles90** [comment]
@Persei08 duplicate close please
