### ISSUE TITLE
no im

### ISSUE THREAD

**Issue by ruben87** [popcorntime/popcorntime#953]
Windows 10

The serie Parks and Recreation only shows sound and the image is all black.

**Comment by kiriles90** [comment]
Use a supported external player (e.g VLC or any of the other in https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js)

**Comment by kiriles90** [comment]
Use a supported external player (e.g VLC or any of the other listed in /src/app/lib/device/ext-player.js)

**Comment by Persei08** [comment]
I close this because it related to supported codec. Try with v4 or else use external player as suggested by @kiriles90
