### ISSUE TITLE
Latest version on site

### ISSUE THREAD

**Issue by KarelPeeters** [popcorntime/popcorntime#954]
`README.md` says:

>The master branch which contains the latest release.

The last commit on the master branch is 4cb26191, but on the site the downloadable version is 28112f67, the commit before that. Why hasn't the site been updated?

**Comment by kiriles90** [comment]
Not all commits are made into a release version (even if they are merged in the master branch too).
Check ci.popcorntime.sh for dev builds, the latest one is 99.9% of the time fully updated with github's development branch.

**Comment by KarelPeeters** [comment]
Makes sense, thanks for the response.
