### ISSUE TITLE
popcorntime is no longer working, when I choose a movie or episode it doesn't go beyond connecting. can you please help me 

### ISSUE THREAD

**Issue by haniasoliman** [popcorntime/popcorntime#955]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Related to your network, often when this happens it's because ISP are blocking some trackers domains. Switch your DNS for google dns, cloudflare dns or opendns dns and retry. If it don't work better, use a VPN with a server location that allow P2P.

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
