### ISSUE TITLE
Please make a new release 

### ISSUE THREAD

**Issue by ohld** [popcorntime/popcorntime#959]
0.3.10 is very outdated, please release a fresh one! Much appreciated!

**Comment by iamart** [comment]
there's a crazy amount of commits in dev branch but it seems like it's mostly fixes. Nothing noticeable from running the latest dev.
Gotta say though, even 2016 version is still holding up pretty good.

**Comment by ohld** [comment]
I can't agree. It is almost impossible to use the mac os client for Mojave. I have a lot of crashes, especially when watching with VLC.

My system:
![image](https://user-images.githubusercontent.com/5613295/52918736-790c0b00-330b-11e9-9692-74269a17a4d4.png)

I believe that every bug that I've met has been already fixed. I (and all users that upvoted my comments) really need a fresh build. Thanks in advance.

We. Need. Bugfixes.

**Comment by ohld** [comment]
Can someone please prepare a release and upload here in comments? Thanks

**Comment by Vidhin05** [comment]
Builds are available on http://ci.popcorntime.sh
The latest build doesn't run on a mac(Check out the size, the tar is about 4mb. Seems like an error)
I would love a new release though.

**Comment by ohld** [comment]
@ArtDesire @Vidhin05 Sorry, but I can not download the built releases from https://ci.popcorntime.sh I receive `Network error`. Can someone please upload a fresh release to the repo? Thaks
![image](https://user-images.githubusercontent.com/5613295/53687223-0d7e6080-3d43-11e9-9636-3e1e26ec4050.png)

**Comment by Vidhin05** [comment]
Refer to #963

**Comment by ohld** [comment]
For those who struggle to get a new release: I've uploaded a new version from CI to my repo:
https://github.com/ohld/popcorntime-release

**Comment by Vidhin05** [comment]
@ohld Is this https://github.com/ohld/popcorntime-release the latest release? If not, which version?

**Comment by ohld** [comment]
@Vidhin05 This is the latest available to be successfully downloaded from ci.popcorntime.sh
