### ISSUE TITLE
Problem in terminal while initializing popcorn-time [12357:12373:0125/162826:ERROR:nss_util.cc(809)] After loading Root Certs, loaded==false: NSS error code: -8018

### ISSUE THREAD

**Issue by ProfGuille** [popcorntime/popcorntime#960]
Operating System Version:
Debian 9

Popcorn Time Version:
0.3

Download date:
Today again.

#### Expected Behaviour
Start the program without bringing that error in terminal: popcorn-time
[12357:12373:0125/162826:ERROR:nss_util.cc(809)] After loading Root Certs, loaded==false: NSS error code: -8018

...

#### Actual Behaviour

...It starts the program but it appears in terminal the message: popcorn-time
[12357:12373:0125/162826:ERROR:nss_util.cc(809)] After loading Root Certs, loaded==false: NSS error code: -8018

#### Steps to reproduce the behaviour

1. ...In terminal start popcorn-time.
2. ...
3. ...

**Comment by iwconfig** [comment]
Same here. Popcorn-time seems to run just fine but when i start a movie, this happens. Debian 9, built from latest in development branch, 1537575.

**Comment by iwconfig** [comment]
I think i got it working. I'm not a node developer so i don't fully understand this but i followed [this comment](https://github.com/popcorn-official/popcorn-desktop/issues/776#issuecomment-390812243), changed to the latest nwjs version (v0.36.0) and got an error message saying that the specified version of [nwjs-ffmpeg-prebuilt](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases) doesn't exist. So then i used the latest release of [nwjs-ffmpeg-prebuilt](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases) instead and now it works as expected!

Steps:

1. Ensure cache/ and build/ directories are removed with `rm -rf cache/ build/` before continuing. Also make sure all dependencies are installed.
2. Go to https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases and copy latest release version
3. Open gulpfile.js, [go to line 6](https://github.com/popcorn-official/popcorn-desktop/blob/1537575b4130ba603674a962f3f4ace6067e7be6/gulpfile.js#L6) and change `nwVersion` to the latest version of `nwjs-ffmpeg-prebuilt` (in my case 0.35.4)

        const nwVersion = '0.35.4',
4. Run `gulp build`
5. Run PCT with `gulp run` or copy `build/Popcorn-Time/linux64/` directory to wherever you want it

**Comment by iwconfig** [comment]
Hmm, although, i still get the ` After loading Root Certs, loaded==false: NSS error code: -8018` error message. I didn't diagnose carefully enough and i think i misread @tarjetasprof. I get the message when PCT is initialized only, so maybe my solution and this issue this is unrelated. Oh well! Anyway, there you have solution to _my_ issue.

Edit: I guess [this](https://github.com/popcorn-official/popcorn-desktop/issues/956#issuecomment-461222456) does the same as my solution

**Comment by team-pct** [comment]
Fixed on last build
