### ISSUE TITLE
Freezes the entire system for a half a minute

### ISSUE THREAD

**Issue by thecoffeehog** [popcorntime/popcorntime#962]
Operating System Version:
macOS Mojave 10.14.3

Popcorn Time Version:
Version 0.3.10 (0.3.10)

Download date:
27th January 2019

#### Expected Behaviour
Not Freeze my enter system for almost half a minute

#### Actual Behaviour
Freezes my enter system for almost half a minute

#### Steps to reproduce the behavior
Open the app on a Mac Book Pro 2017 and you will see the laptop freezes

**Comment by kiriles90** [comment]
Go to Settings > Security & Privacy > Accessibility and uncheck Popcorn Time

**Comment by Agusum** [comment]
Amazing, this did the trick for me! Regardless, it'll be great if a proper fix was put in place for the average user who doesn't check GitHub.

**Comment by thecoffeehog** [comment]
Didn't work for me.

**Comment by whatthehomepod** [comment]
Didn’t work for me either but this project is dead anyways.

**Comment by RyanBeckett** [comment]
The above suggestion did work for me.

**Comment by Persei08** [comment]
Closing, i think this one is now obsolete
