### ISSUE TITLE
Unable to download any version from Jenkins

### ISSUE THREAD

**Issue by flumpiey** [popcorntime/popcorntime#963]
Operating System Version:
Windows 10

I have Tried using Chrome, Firefox and Edge and on multiple computers. Each time the download either fails due to "Network error" or it sits at 0%.

**Comment by andremeireles** [comment]
Using a download manager solves this problem.
On Linux, [Xtreme Download Manager](http://xdman.sourceforge.net) works for me.

**Comment by dincercelik** [comment]
> Operating System Version:
> Windows 10
> 
> I have Tried using Chrome, Firefox and Edge and on multiple computers. Each time the download either fails due to "Network error" or it sits at 0%.

Same here with OSX. Does not matter whether you use a download manager.

**Comment by ghost** [comment]
Same issue here.

**Comment by MrRory** [comment]
@team-pct

**Comment by mrd0ll4r** [comment]
wget log:
```
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastBuild/artifact/build/Popcorn-Time-0.3.10_linux64.tar.xz
Resolving ci.popcorntime.sh (ci.popcorntime.sh)... 104.20.6.128, 104.20.5.128, 2606:4700:10::6814:580, ...
Connecting to ci.popcorntime.sh (ci.popcorntime.sh)|104.20.6.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 85182356 (81M) [application/x-xz]
Saving to: ‘Popcorn-Time-0.3.10_linux64.tar.xz’

Popcorn-Time-0.3.10_linux64.tar.xz                            0%[                                                                                                                                           ]  79.38K  --.-KB/s    in 0.08s   

2019-02-01 09:49:44 (1006 KB/s) - Read error at byte 81289/85182356 (The TLS connection was non-properly terminated.). Retrying.
```

**Comment by trexx** [comment]
Using wget, add `/*view*/` to the end of your URL, then rename the resulting file to the `.tar.xz` extension.

**Comment by dincercelik** [comment]
Using aria2c works like a charm.

`aria2c -m0 -j5 -s5 https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/artifact/build/Popcorn-Time-0.3.10_osx64.tar.xz`

**Comment by Eienn** [comment]
> Using aria2c works like a charm.
> 
> `aria2c -m0 -j5 -s5 https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/artifact/build/Popcorn-Time-0.3.10_osx64.tar.xz`

Have no idea why - but aria2c works) THX

**Comment by ohld** [comment]
This is how you can install this `aria2c` on a mac:

``` bash
brew install aria2
```

And then run the command by @dincercelik.

**Comment by ohld** [comment]
For those who can not get the new popcorn time app version by yourself: I've uploaded the new version from CI to my repo: https://github.com/ohld/popcorntime-release.
you can download popcorn time there.

**Comment by stellaki13** [comment]
WINDOWS 7 64 BIT 3.1O NO BUILTS BECAUSE JENKING SERVER ERROR PCONNECTION PROBLEM AND NO SYNC TRAKT .HOW WE CAN SYNC?THE SAME CONNECTED WITH BUTTER BUT NOTHING ,IF MAKE UPDATE OR FORMAT HOW WE CAN COPY /PASTE FAVORITES BOOKMARKS?WHERE ARE ?IN USER DATA ?OR ANYWHERE ELSE?

**Comment by NathanHazout** [comment]
https://ci.popcorntime.sh does not load at all for me in the browser. Anyone else?

**Comment by NathanHazout** [comment]
New URL: https://ci.popcorntime.app/
