### ISSUE TITLE
Linux i386 popcorntime dosen't play audio during the video on default video player.

### ISSUE THREAD

**Issue by axelconselvan** [popcorntime/popcorntime#967]
Operating System Version:
Linux Xubuntu 18.04 i386

Popcorn Time Version:
0.3.10

Download date:
02-05-2019

#### Expected Behaviour
Popcorn time default player should play videos witch sound.
...

#### Actual Behaviour
Popcorn time default player show video and subtitles but dosen't play audio. This behaviour occurs just in default player, on vlc and chromecast dosen't occurs.
...

#### Steps to reproduce the behaviour

1. Extract popcorn time.
2. Open popcorn time.
3. Play any movie.

**Comment by axelconselvan** [comment]
If there is anything I can do to get more information to help, just tell me.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by axelconselvan** [comment]
How o close the issue?

**Comment by kiriles90** [comment]
@axelconselvan should be a close button at the bottom, if you cant no worries Persei08 can close it too

**Comment by axelconselvan** [comment]
Should tou close for me. Thank's for all
