### ISSUE TITLE
When wanting subtitles Popcorn asks for login. Where do I get it?

### ISSUE THREAD

**Issue by correiaantonieta53** [popcorntime/popcorntime#970]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
opensubtitles.org

**Comment by kiriles90** [comment]
Popcorn Time fetches subtitles from the same place mostly everyone else does, opensubtitles.org.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
