### ISSUE TITLE
Where does it pull the library from?

### ISSUE THREAD

**Issue by tiotrom** [popcorntime/popcorntime#974]
I was curious what is using to pull its library? I cannot find most documentaries I am searching from and I was curious what it uses to index? Thanks!

**Comment by kiriles90** [comment]
YTS.am for movies, EZTV.io for series, and some others for anime and metadata

**Comment by kiriles90** [comment]
YTS.am for movies, EZTV.io for series, and some others for anime, subtitles and various metadata

**Comment by tiotrom** [comment]
Thank you! I have a curated documentary-based website videoneat.com where we post many hand-curated documentaries. And we seed. Is it possible to be added somehow to Popcorntime? To index from videoneat as well?

**Comment by kiriles90** [comment]
Technically ofc. If you have an API and someone writes a wrapper (or a scraper but API+wrapper is preferred) then its pretty straightforward. For the official fork.. not sure if the devs want to pick up on this and maybe add a documentary tab but open an issue/request with any details you can provide and see. The idea isnt bad imo.
