### ISSUE TITLE
Download folder name named after the torrent and not after the video file as before

### ISSUE THREAD

**Issue by vageliskatsiotis** [popcorntime/popcorntime#976]
Operating System Version:

Antergos - 4.19.23-1-lts

Popcorn Time Version:

0.3.10-5, popcorntime-bin from AUR

Download date:

Updated last week

#### Expected Behaviour

Download torrent in folder named like the video file, as it did before the update

#### Actual Behaviour

Downloads torrent in folder name named after the torrent file.

#### Steps to reproduce the behaviour

1. Just stream anything

**Comment by noobkid** [comment]
same here, for example:
[PATH]\Popcorn Time\70fd833d34b03603a38403a2f3f0ed752fb4886e\Supernatural.S12E16.HDTV.x264-LOL[ettv]
instead of:
[PATH]\Popcorn Time\Supernatural.S12E16.HDTV.x264-LOL[ettv]

**Comment by Persei08** [comment]
Already fixed in development branch and dev builds available via CI.

Your aur package use the old 0.3.10 beta from november 2016. 

Maybe try [AUR package "popcorntime" from ItachiSan](https://aur.archlinux.org/packages/popcorntime/) for a most recent dev version

**Comment by vageliskatsiotis** [comment]
Persei hi. Thanx for the tip. Got it working with the version you proposed!! One thing though. My bookmarks button is gone now. Any ideas on this maybe? Thanx again!
