### ISSUE TITLE
closing ex player of previous video stops new download

### ISSUE THREAD

**Issue by noobkid** [popcorntime/popcorntime#978]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
25/02/2019

#### Expected Behaviour
no action in popcorn time app

#### Actual Behaviour
closing the external player closes the video download

#### Steps to reproduce the behaviour
1. watch show/movie using an external player (i used mpc and vlc) and finish download
2. close the download (not the player) and start a new one
3. close the player of the previous video -> it closes the new download

**Comment by kiriles90** [comment]
Just close the player of the previous video before you start a new download?  
Or if for some reason you dont want to, keep it there until the second one has finished also?

**Comment by noobkid** [comment]
yeah, i do that.... just wanted to let you know of this behavior

**Comment by kiriles90** [comment]
@Persei08 close please
