### ISSUE TITLE
Popcorn-Time not logging into Trakt TV (again) - ci site is not working either.

### ISSUE THREAD

**Issue by allan-andrade** [popcorntime/popcorntime#981]
Operating System Version:
Windows 10 64bit Ultimate

Popcorn Time Version:
3.10

Download date:
03/03/2018 from https://popcorntime.sh/

#### Expected Behaviour
Connect to and sync my Trakt TV account

#### Actual Behaviour
After put the right user and password doesn't connect my account. Can click the login button again and a quick pin code appears but can't be read.

#### Steps to reproduce the behaviour
1) Start Popcorn Time
2) Go to Settings
3) Click Connect to Trakt TV
4) Login 

p.s.: Cannot download from the ci site either. Network error always occurs. In all builds!

![giphy](https://user-images.githubusercontent.com/10637454/53751691-a3250780-3e8b-11e9-9d4c-918053b08b20.gif)

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/963 & https://github.com/popcorn-official/popcorn-desktop/issues/816

**Comment by allan-andrade** [comment]
> Duplicate #963 & #816

Thanks. #816 helps me. Didn't find before. How can i close this issue?

**Comment by kiriles90** [comment]
There should be a 'close issue' button for you somewhere. (bottom-right next to the 'comment' button?)
