### ISSUE TITLE
nwjs profile error

### ISSUE THREAD

**Issue by Swag-M** [popcorntime/popcorntime#982]
Operating System Version:
MacOS 10.14.2

Popcorn Time Version:
#362

Download date:
4 March
#### Expected Behaviour

To open the app without an error.

#### Actual Behaviour

Gives me an error then opens the app.

#### Steps to reproduce the behaviour

1. Open the app

<img width="453" alt="skaermbillede 2019-03-05 kl 00 17 28" src="https://user-images.githubusercontent.com/48227094/53771176-e8742400-3ee1-11e9-8a6a-242bf849dc4e.png">

**Comment by Persei08** [comment]
not a bug. is related to nwjs, because at some point you have used a version of PT which used a most recent version of nwjs.

You can delete you user data dir:

http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir

but you will lost your PT settings
