### ISSUE TITLE
App is not showing any list of movies or series n constantly buffering .

### ISSUE THREAD

**Issue by tanamy-dave** [popcorntime/popcorntime#984]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.3.10 Beta

Download date:
About a year ago

 Expected Behaviour
Ap can stream movies and series online using p2p protocol.

Actual Behaviour
From yesterday app started to buffer, it is even not showing the list of movies or series. 

![screenshot 9](https://user-images.githubusercontent.com/48272450/53859941-5f560d80-4005-11e9-8dcf-36a51c707f11.png)

**Comment by kiriles90** [comment]
Maybe your ISP blocked the API urls? Try changing your DNS to google, cloudflare etc or use a VPN

**Comment by carolinemo** [comment]
i'll try it

**Comment by kiriles90** [comment]
@Persei08 not an actual Popcorn Time issue, close please
