### ISSUE TITLE
Popcorn-Time quits unexpectedly 

### ISSUE THREAD

**Issue by JSwamie** [popcorntime/popcorntime#985]
Operating System Version:

OS X 10.14.3 (Mojave)

Popcorn Time Version:

0.3.10

Download date:

March 7, 2019

#### Expected Behaviour

Quit the app

#### Actual Behaviour

It quits the app but hangs for a bit, then gives me an app quit unexpectantly error. I have seen issues #388 #293 but neither one has a solution that works.

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Streusel** [comment]
I can confirm this issue.  

```
Process:               nwjs [36434]
Path:                  /Applications/Popcorn-Time.app/Contents/MacOS/nwjs
Identifier:            com.nw-builder.popcorn-time
Version:               Version 0.3.10 (0.3.10)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nwjs [36434]
User ID:               501

Date/Time:             2019-03-08 20:32:33.184 -0800
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12

Time Awake Since Boot: 1300000 seconds
Time Since Wake:       20000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 000000010d105000-000000010d106000 [    4K] r-x/rwx SM=COW  /Applications/Popcorn-Time.app/Contents/MacOS/nwjs
```

**Comment by whatthehomepod** [comment]
Dev build resolved the issue.

Steps to resolve:
```
git clone https://github.com/popcorn-official/popcorn-desktop.git
cd /popcorntime-desktop/
yarn && yarn gulp run
yarn gulp build
```

**Comment by Aerozolic** [comment]
> Dev build resolved the issue.
> 
> Steps to resolve:
> 
> ```
> git clone https://github.com/popcorn-official/popcorn-desktop.git
> cd /popcorntime-desktop/
> yarn && yarn gulp run
> yarn gulp build
> ```

Unfortunately dev build doesn't work at all:

![Screen Shot 2019-03-21 at 22 28 00](https://user-images.githubusercontent.com/25500346/54782886-a01a6d00-4c28-11e9-9ba4-23dd6113091a.png)

**Comment by whatthehomepod** [comment]
You are right, I tested the dev build but didn’t work. However you could use the 325 ci build, this one worked for me without any issues! If you need any help I would love to help. 

Verstuurd vanaf mijn iPhone

**Comment by Aerozolic** [comment]
> You are right, I tested the dev build but didn’t work. However you could use the 325 ci build, this one worked for me without any issues! If you need any help I would love to help. Verstuurd vanaf mijn iPhone
> […](#)

How to get the specific 325 ci build? I'm a bit noob with this.

**Comment by whatthehomepod** [comment]
No problem, I guess you own mac because of the issues you currently have. 

Download first xdman, find it at Google. You need a download manager because the CI links are broken, don’t know why but this is how we did it. If you have done that let me know. 

Verstuurd vanaf mijn iPhone

**Comment by Aerozolic** [comment]
> No problem, I guess you own mac because of the issues you currently have. Download first xdman, find it at Google. You need a download manager because the CI links are broken, don’t know why but this is how we did it. If you have done that let me know. Verstuurd vanaf mijn iPhone
> […](#)

Done

**Comment by whatthehomepod** [comment]
Good add this link to xdman

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/artifact/build/Popcorn-Time-0.3.10_osx64.zip

Unzip and start, open PT, close with command+q, and check if you have still this error. If not enjoy this version. You have new options to this. You can sync your progress to TV Time. 

Verstuurd vanaf mijn iPhone

**Comment by Aerozolic** [comment]
> Good add this link to xdman https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/362/artifact/build/Popcorn-Time-0.3.10_osx64.zip Unzip and start, open PT, close with command+q, and check if you have still this error. If not enjoy this version. You have new options to this. You can sync your progress to TV Time. Verstuurd vanaf mijn iPhone
> […](#)

With that version I get this:
![Screen Shot 2019-03-22 at 23 17 23](https://user-images.githubusercontent.com/25500346/54853518-c1e32500-4cf8-11e9-927f-177c8db653c4.png)

**Comment by whatthehomepod** [comment]
This is the correct version. The latest has a lot of bugs. With what are you unzipping the file? There are indeed issues with unzip and downloading, but I’m going to help you. 

Verstuurd vanaf mijn iPhone

**Comment by Aerozolic** [comment]
> This is the correct version. The latest has a lot of bugs. With what are you unzipping the file? There are indeed issues with unzip and downloading, but I’m going to help you. Verstuurd vanaf mijn iPhone
> […](#)

I used unarchiver

**Comment by whatthehomepod** [comment]
Are you sure you used the correct build? The one I have sent you?
You need xdman to download the file otherwise your download will be be corrupted, open the program, click on the add button, drop the link into that prompt, and download the file, wait until its done and unarchive the file.

I just tried yet again to reproduce and I have a working application after unzipping.

**Comment by diwu1989** [comment]
Still seeing this issue and the linked jenkins build is expired.

Can we please release a new official version 0.3.11?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
