### ISSUE TITLE
"Subtitles service you need to Log in"

### ISSUE THREAD

**Issue by juanstoledoc** [popcorntime/popcorntime#989]
Operating System Version:
macOS Sierra 10.12.6 

Popcorn Time Version:
Version 0.3.10

Download date:
Reinstalled March 21, 2019

#### Expected Behaviour
Simply load the desired subtitles.

#### Actual Behaviour
Instead of the subtitles for the film/series it displays a message saying "subtitles service you need to log in," although I have already successfully logged in to OpenSubtitles in the configuration (got the green check, and it says I'm logged in). Before yesterday, it even worked without logging in.

#### Steps to reproduce the behaviour
Simply select any subtitles in any language in any film or episode, and I get the same message, whether I am logged in or not.

![Bildschirmfoto-2019-03-21-um-1 21 57-AM](https://user-images.githubusercontent.com/28882527/54736343-9c2f1200-4b78-11e9-8d65-de749c2ae999.jpg)

**Comment by StraleStrah** [comment]
same problem.

**Comment by StraleStrah** [comment]
It is not bug in popcorn it is some bug in OpenSubtitles

Same happens in BS player with their titles.


![image](https://user-images.githubusercontent.com/48879801/54878123-75970280-4e28-11e9-8a30-028e2ca91b42.png)

**Comment by user440** [comment]
It seems that OpenSubtitles is sometime blocking some players (probably because of some abuse of their service). One day OpenSubtitles was blocked (giving above message lines) in Popcorn while on the same machine Stremio was working fine. So it is not IP related. Next day OpenSubtitles worked fine on Popcorn again.

Popcorn is using "downloadFromUrl" to get subtitle file, but maybe OpenSubtitles direct APIs should be used: "LogIn" + "DownloadSubtitles".

**Comment by vageliskatsiotis** [comment]
Hi all. In my case I discovered that's because of my VPN connection. When disabling VPN popcorn downloads subs fine.

**Comment by FAQuller** [comment]
Still same problem: never ever saw this message "service subtitles you need to Log In" before. Where is this suddenly coming from?
And how do you Log In in PopcornTime?

**Comment by hassanjamil-magma** [comment]
> Hi all. In my case I discovered that's because of my VPN connection. When disabling VPN popcorn downloads subs fine.

Worked for me, Thanks Man!

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
