### ISSUE TITLE
Butter - no subtitles 

### ISSUE THREAD

**Issue by weissko** [popcorntime/popcorntime#990]
I used to watch movies only through Butter and subtitles always loaded English (or i choosed them from the list "buble option" right corner of the screen.

Now there is suddenly written "disabled" or custom .. and i need to find them in pc or so.. 

i checked more movies.. the same problem which has not been there before...

i used to learn English to hear and to watch at the same time..

thank you for explanation what is happening.. your fan Erik

**Comment by Persei08** [comment]
PT version number ? 
OS ?

**Comment by weissko** [comment]
popcorn time 3.10 - i tried also re-installation (no success)
windows 8 

just few days ago i been watching with subs through Butter.

and suddenly they are not there as option

**Comment by weissko** [comment]
i got the latest version of desktop application to run the popconr time and
butter and windows 8 ...

all subs been perfect and showed up automatically as option.. but just one
day after they all gone and i tried to check more movies... i also
connected account with open subs in case its somehow running together as
source..

but nothing has changed...

now i see there only DISABLES and CUSTOM... I tried to change settings in
application to english subs and right after i played movie and there was
suddenly written text that no subs available... so the same story once
again...

i did not change anything... this feature just stopped working for no
reason :D

thanks for help

**Comment by user440** [comment]
This is probably related to issues #603 and #410 which are solved in current development version (you need to download it manually to fix those issues).

Check https://github.com/popcorn-official/popcorn-desktop/pull/609/files

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
