### ISSUE TITLE
Wrong subtitles on Android apk

### ISSUE THREAD

**Issue by matheusnb99** [popcorntime/popcorntime#991]
Operating System Version:
Android 9

Popcorn Time Version:
3.2.2.134

Download date:
09/09/2018

#### Expected Behaviour
Play show with subtitles

#### Actual Behaviour
Subtitles of another show

#### Steps to reproduce the behaviour

1. Download show A
2. Start to download show B
3. Start to watch show A
4. (now the show A has the subtitles of show B)

**Comment by Persei08** [comment]
This repo is for the desktop app. 
The issue board for the android app is here:https://github.com/popcorn-official/popcorn-android/issues
