### ISSUE TITLE
Time bar pops-up unexpectedly in fullscreen mode

### ISSUE THREAD

**Issue by rypz79** [popcorntime/popcorntime#992]
Following Issues #535 #546 , the bug goes on and I can't find any solution or a workaround to it.

Operating System Version:
Windows 10
Popcorn Time Version:
0.3.10-0
Download date:
09/02/2019

#### Expected Behavior

In full screen mode do not show or popup the the time bar without a cursor movement
#### Actual Behavior

After you enter fullscreen mode it pops-up the time bar without any cursor movement after ~1 second, then after ~3 seconds timeout it hides it, then again pops it up then again hides it  (loop) and so on...   

#### Steps to reproduce the behavior

1. Run Popcorn-time
2. Start a movie or an episode in a series
3. .Enter fullscreen mode (pointed with red arrow in the attached picture)

<img width="960" alt="popcorn" src="https://user-images.githubusercontent.com/28814757/55280942-b8337000-533d-11e9-8376-d70cb3fbcf8f.png">

**Comment by Juansero29** [comment]
I am also experiencing this issue, any solutions?

**Comment by kiriles90** [comment]
@Persei08 close this I think, a lot have changed since then
if someone with 0.4.4+ reopens at least we'll know it didnt get fixed since its specific to certain systems and not easy to replicate
