### ISSUE TITLE
Build from source broken on ArchLinux

### ISSUE THREAD

**Issue by ItachiSan** [popcorntime/popcorntime#993]
Operating System Version:

ArchLinux, specifically Antergos; all updates up to today are installed.

Popcorn Time Version:

0.3.10, commit: 01d3b09080f458e3a2eb95506655e9d174922ef5

Download date:

Today, 2019-03-31.

#### Expected Behaviour

1. Build from source
2. Clean run the app (removed the profile folder `~/.config/Popcorn-Time`)
3. The app works

#### Actual Behaviour

The app doesn't show any window at all.

#### Steps to reproduce the behaviour

1. Build the AUR package `popcorntime`, available here: https://aur.archlinux.org/packages/popcorntime/

If you have any question Arch-related, please do ask. :smile:

**Comment by kiriles90** [comment]
@ItachiSan is this still an issue?
@Persei08 probably close this? too much have changed since then

**Comment by Persei08** [comment]
I close it, issue is too old and @ItachiSan 's pkgbuild is set to build 0.4.4
