### ISSUE TITLE
Popcorntime and Butter Icon in dock not grouped

### ISSUE THREAD

**Issue by kronikpillow** [popcorntime/popcorntime#996]
Operating System Version: ArcoLinuxB-openbox v19.04.4
Popcorn Time Version: 0.3.10-5
Download date: 06.04.2019

I have popcorntime pinned to my dock, but when i run it, it opens a WM Class called Butter and it cant be pinned, in other words i have a double icon, one that is used to run the app and is pinned, and the other one I can't even pin at all ...  

Popcorn Time.desktop contains
[Desktop Entry]
Name=Popcorn Time
Comment=Watch Movies and TV Shows instantly
Exec=popcorntime %U
Icon=popcorntime
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
StartupNotify=false
Categories=AudioVideo;Video;Network;Player;P2P;
Type=Application

tried adding
StartupWMClass=Popcorn Time

didn't work ... :-/

this problem is also present on Solus Budgie, Mint, Ubuntu ... basically everywhere

**Comment by ozkanpakdil** [comment]
I think this is related to nwjs. and you can try to build by

yarn config set yarn-offline-mirror ./node_modules/
yarn install --ignore-engines
yarn build
yarn gulp run

upgrade it and see if it fixes.

**Comment by kronikpillow** [comment]
I installed the package via Arch Linux AUR, not yarn
just installed yarn and followed your steps but when i get to
yarn build
i get a 
[kronikpillow@susanoo ~]$ yarn build
yarn run v1.15.2
error Couldn't find a package.json file in "/home/kronikpillow"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

but like i said, this is present in Solus, Ubuntu, Arch Linux, on Solus and Ubuntu i installed it via the executable off the official website, on Arch i installed it via the AUR package repository

**Comment by kronikpillow** [comment]
and no feedback ...... is any development being done on popcorn?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by kiriles90** [comment]
@Persei08 close please
