### ISSUE TITLE
Partial string search not working

### ISSUE THREAD

**Issue by igormcoelho** [popcorntime/popcorntime#997]
Operating System Version:
Linux Deepin

Popcorn Time Version:
3.10

Download date:
06/04/2019

#### Expected Behaviour
Substring search not working. For example, if you look for "blackKklansman" and type "black", the movie won't appear on list. Don't know the exact problem.
...

#### Actual Behaviour
Substring search not working. For example, if you look for "blackKklansman" and type "black", the movie won't appear on list. Don't know the exact problem.
...

#### Steps to reproduce the behaviour
For example, if you look for "blackKklansman" and type "black", the movie won't appear on list. 

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
This is an API issue:

Try https://tv-v2.api-fetch.website/movies/1?sort=rating&order=-1&genre=all&keywords=hop it won't return movies containing "hope"

**Comment by igormcoelho** [comment]
Thanks for the explanation :+1:
